### ISSUE TITLE
OOMKilled error for gitclone does not say which container was killed? init, main, wait ?

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#10007]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

![image](https://user-images.githubusercontent.com/33283496/200968673-03e7384a-93e4-46aa-b12e-5c162c2972f1.png)

 i have 5g memory set for this step, sometimes works, sometimes doesn't

not sure if i need to increase init or wait container memory too?

is it possible to make the error message say which container was OOMkilled?

### Version

3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
https://github.com/argoproj/argo-workflows/blob/9f5759b5bd2a01d0f2930faa20ad5a769395eb99/examples/input-artifact-git.yaml like this one
```

### Logs from the workflow controller

kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

### Logs from in your workflow's wait container

kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

**Comment by tczhao** [comment]
If it says "Error" then it's init or wait container issue
If it says "Failed" then it's main container.

In our case, we have metrics and logging setup to infer from there.
also, having request and limit set to the same value for init and wait container could help. I don't see how the extra overhead (limit) in init/wait container is too helpful
