### ISSUE TITLE
UI: Hide navbar items from configuration

### ISSUE THREAD

**Issue by julienduchesne** [argoproj/argo-workflows#10011]
# Summary

Argo Workflows has lots of options in the navbar that we do not use. We would like to be able to hide the following from the navbar:

- Event Flow
- Event Sources
- Sensors
- Workflow Event Bindings
- Reports
- API Docs
- Plugins

We don't really need to disable the URLs, just clean up the navbar. It'd be nice if there was a config to hide items, or list all the ones we do want to show

# Use Cases

We provide Argo Workflows to our internal teams, and we only want to expose the features that they should care about/the ones we're currently using.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Duplicate https://github.com/argoproj/argo-workflows/issues/7088
