### ISSUE TITLE
daemon container won't be delete if deadline exceeded happen

### ISSUE THREAD

**Issue by henrywangx** [argoproj/argo-workflows#10029]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

We use the daemon container of argo workflow, but the workflow happened hang forever sometimes.
The processes workflow:
1. running computing steps;
2. delete daemon container when all computing steps finished.

logs:
```bash
 level=error msg="error in entry template execution" error="Deadline exceeded"
```

And I checked source code as bellow, whether `ErrDeadlineExceeded` the workflow won't be reconciled if workflow only one daemon container in the end unless restart controller?
https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/operator.go#L346-L353

### Version

v3.2.6

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Hard to reproduce.
```

### Logs from the workflow controller

 level=error msg="error in entry template execution" error="Deadline exceeded"

### Logs from in your workflow's wait container

no useful log

**Comment by alexec** [comment]
I think we’d need a workflow to reproduce this if we want to investigate it.

**Comment by HRusby** [comment]
To Note, I believe this is the same issue as in https://github.com/argoproj/argo-workflows/issues/9934 which does have reproducible workflows attached

**Comment by agilgur5** [comment]
> To Note, I believe this is the same issue as in #9934 which does have reproducible workflows attached

That one doesn't use a `daemon` container, so would not apply to this issue.

Otherwise that issue is now resolved.

If you're still encountering this, please provide a reproducible Workflow with a `daemon` on the `:latest` version
