### ISSUE TITLE
Upgrade rpc module to v2.0.3 

### ISSUE THREAD

**Issue by MaxClercEricsson** [argoproj/argo-workflows#10030]
# Summary

The actual version of rpc is depreciated and dates back several years. 

The `go.mod`  use jcmturner/rpc.v0 v0.0.2 that is decrepeted . It would be interesting to upgrade to version jcmturner/rpc.v2 2.0.3

# Proposal

Upgrade hdfs v1.1.4 to 2.3.0  it should upgrade the jcmturner/rpc version to the jcmturner/rpc.v2 2.0.3

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Would you like to submit a PR?

**Comment by SakshiT25** [comment]
Hey, I would like to work on this issue. But don't know how to proceed with it.

**Comment by shogohida** [comment]
Hi @terrytangyuan, I decided to work on this issue and already made a draft pull request! Still waiting for the tests to pass

**Comment by terrytangyuan** [comment]
Or run `go mod tidy`

**Comment by shogohida** [comment]
I ran `go mod tidy` but it deletes the lines related to `rpc.v2 v2.0.3` although I want to keep them.... Which is the redundant line you mentioned?

**Comment by terrytangyuan** [comment]
You can run `make lint STATIC_FILES=false` to reproduce

**Comment by callmetushar123** [comment]
@terrytangyuan Hello can you assign this issue to me, I would like to work on it

**Comment by sonbui00** [comment]
As I check, this should upgrade gopkg.in/jcmturner/gokrb5.v5 on workflow/artifacts/hdfs/

**Comment by sonbui00** [comment]
This should be closed by https://github.com/argoproj/argo-workflows/pull/11543
@terrytangyuan Please help me close this.
