### ISSUE TITLE
Artifact GC is using default service account instead of configured one

### ISSUE THREAD

**Issue by elemental-lf** [argoproj/argo-workflows#10036]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

While running a slightly modified version of the `handle-large-output-results.yaml` example I noticed that the controller was unable to delete artifacts after workflow completion. It seems that even though another service account is specified in the workflow the artifact GC starts a pod with the default service account.

Error message from the GC's pod (main container):

```
handle-large-output-results-259nm-artgc-wfcomp-2166136261 main workflowartifactgctasks.argoproj.io is forbidden: User "system:serviceaccount:ceph:default" cannot list resource "workflowartifactgctasks" in API group "argoproj.io" in the namespace "ceph"
```

### Version

v3.4.3 and latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: handle-large-output-results-
  # Added namespace to example
  namespace: ceph
spec:
  entrypoint: handle-large-output-results
  # START: Changes to the original example
  serviceAccountName: benji
  artifactGC:
    strategy: OnWorkflowCompletion
  # END: Changes to the original example
  templates:
    - name: handle-large-output-results
      steps:
        - - name: get-items
            template: get-items
        - - name: sequence-param
            template: echo
            arguments:
              parameters:
                - name: index
                  value: "{{item}}"
              artifacts:
                - name: items
                  from: "{{steps.get-items.outputs.artifacts.items}}"
            withSequence:
              count: "{{steps.get-items.outputs.parameters.count}}"
    - name: get-items
      container:
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        # This small array is just for an example. Make sure the count matches the actual size of
        # your JSON array.
        args: ["echo '[\"a\", \"b\", \"c\"]' > /tmp/items && echo '3' > /tmp/count"]
      outputs:
        artifacts:
          - name: items
            path: /tmp/items
        parameters:
          - name: count
            valueFrom:
              path: /tmp/count
    - name: echo
      inputs:
        parameters:
          - name: index
        artifacts:
          - name: items
            path: /tmp/items
      container:
        image: stedolan/jq:latest
        command: [sh, -c]
        # jq is just one way to get the appropriate item.
        args: ["cat /tmp/items | jq '.[{{inputs.parameters.index}}]'"]
```

### Logs from the workflow controller

time="2022-11-15T15:21:58.918Z" level=info msg="Processing workflow" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:21:58.921Z" level=info msg="adding artifact GC finalizer" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:21:58.921Z" level=info msg="Updated phase  -> Running" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:21:58.921Z" level=info msg="Steps node handle-large-output-results-259nm initialized Running" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:21:58.921Z" level=info msg="StepGroup node handle-large-output-results-259nm-2550562900 initialized Running" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:21:58.921Z" level=info msg="Pod node handle-large-output-results-259nm-2515898911 initialized Pending" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:21:58.929Z" level=info msg="Created pod: handle-large-output-results-259nm[0].get-items (handle-large-output-results-259nm-get-items-2515898911)" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:21:58.929Z" level=info msg="Workflow step group node handle-large-output-results-259nm-2550562900 not yet completed" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:21:58.929Z" level=info msg="TaskSet Reconciliation" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:21:58.929Z" level=info msg=reconcileAgentPod namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:21:58.933Z" level=info msg="Workflow update successful" namespace=ceph phase=Running resourceVersion=917717473 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.930Z" level=info msg="Processing workflow" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.931Z" level=info msg="Task-result reconciliation" namespace=ceph numObjs=1 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.931Z" level=info msg="task-result changed" namespace=ceph nodeID=handle-large-output-results-259nm-2515898911 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.931Z" level=info msg="node changed" namespace=ceph new.message= new.phase=Succeeded new.progress=0/1 nodeID=handle-large-output-results-259nm-2515898911 old.message= old.phase=Pending old.progress=0/1 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.931Z" level=info msg="Step group node handle-large-output-results-259nm-2550562900 successful" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.931Z" level=info msg="node handle-large-output-results-259nm-2550562900 phase Running -> Succeeded" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.931Z" level=info msg="node handle-large-output-results-259nm-2550562900 finished: 2022-11-15 15:22:08.931919429 +0000 UTC" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.931Z" level=info msg="StepGroup node handle-large-output-results-259nm-3691190729 initialized Running" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.931Z" level=info msg="SG Outbound nodes of handle-large-output-results-259nm-2515898911 are [handle-large-output-results-259nm-2515898911]" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.932Z" level=info msg="Pod node handle-large-output-results-259nm-3715707525 initialized Pending" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.937Z" level=info msg="Created pod: handle-large-output-results-259nm[1].sequence-param(0:0) (handle-large-output-results-259nm-echo-3715707525)" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.937Z" level=info msg="Pod node handle-large-output-results-259nm-1060231633 initialized Pending" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.942Z" level=info msg="Created pod: handle-large-output-results-259nm[1].sequence-param(1:1) (handle-large-output-results-259nm-echo-1060231633)" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.942Z" level=info msg="Pod node handle-large-output-results-259nm-3066201165 initialized Pending" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.948Z" level=info msg="Created pod: handle-large-output-results-259nm[1].sequence-param(2:2) (handle-large-output-results-259nm-echo-3066201165)" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.948Z" level=info msg="Workflow step group node handle-large-output-results-259nm-3691190729 not yet completed" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.948Z" level=info msg="TaskSet Reconciliation" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.948Z" level=info msg=reconcileAgentPod namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.955Z" level=info msg="Workflow update successful" namespace=ceph phase=Running resourceVersion=917717594 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:08.960Z" level=info msg="cleaning up pod" action=labelPodCompleted key=ceph/handle-large-output-results-259nm-get-items-2515898911/labelPodCompleted
time="2022-11-15T15:22:18.939Z" level=info msg="Processing workflow" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:18.940Z" level=info msg="Task-result reconciliation" namespace=ceph numObjs=1 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:18.941Z" level=info msg="node changed" namespace=ceph new.message= new.phase=Succeeded new.progress=0/1 nodeID=handle-large-output-results-259nm-3715707525 old.message= old.phase=Pending old.progress=0/1 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:18.941Z" level=info msg="node changed" namespace=ceph new.message= new.phase=Running new.progress=0/1 nodeID=handle-large-output-results-259nm-1060231633 old.message= old.phase=Pending old.progress=0/1 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:18.941Z" level=info msg="node changed" namespace=ceph new.message= new.phase=Succeeded new.progress=0/1 nodeID=handle-large-output-results-259nm-3066201165 old.message= old.phase=Pending old.progress=0/1 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:18.941Z" level=info msg="SG Outbound nodes of handle-large-output-results-259nm-2515898911 are [handle-large-output-results-259nm-2515898911]" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:18.941Z" level=info msg="Workflow step group node handle-large-output-results-259nm-3691190729 not yet completed" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:18.942Z" level=info msg="TaskSet Reconciliation" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:18.942Z" level=info msg=reconcileAgentPod namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:18.946Z" level=info msg="cleaning up pod" action=terminateContainers key=ceph/handle-large-output-results-259nm-echo-1060231633/terminateContainers
time="2022-11-15T15:22:18.947Z" level=info msg="Workflow update successful" namespace=ceph phase=Running resourceVersion=917717762 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:18.952Z" level=info msg="cleaning up pod" action=labelPodCompleted key=ceph/handle-large-output-results-259nm-echo-3715707525/labelPodCompleted
time="2022-11-15T15:22:18.952Z" level=info msg="cleaning up pod" action=labelPodCompleted key=ceph/handle-large-output-results-259nm-echo-3066201165/labelPodCompleted
time="2022-11-15T15:22:28.949Z" level=info msg="Processing workflow" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.950Z" level=info msg="Task-result reconciliation" namespace=ceph numObjs=1 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.950Z" level=info msg="node changed" namespace=ceph new.message= new.phase=Succeeded new.progress=0/1 nodeID=handle-large-output-results-259nm-1060231633 old.message= old.phase=Running old.progress=0/1 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.950Z" level=info msg="SG Outbound nodes of handle-large-output-results-259nm-2515898911 are [handle-large-output-results-259nm-2515898911]" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="Step group node handle-large-output-results-259nm-3691190729 successful" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="node handle-large-output-results-259nm-3691190729 phase Running -> Succeeded" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="node handle-large-output-results-259nm-3691190729 finished: 2022-11-15 15:22:28.951254328 +0000 UTC" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="Outbound nodes of handle-large-output-results-259nm-3715707525 is [handle-large-output-results-259nm-3715707525]" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="Outbound nodes of handle-large-output-results-259nm-1060231633 is [handle-large-output-results-259nm-1060231633]" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="Outbound nodes of handle-large-output-results-259nm-3066201165 is [handle-large-output-results-259nm-3066201165]" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="Outbound nodes of handle-large-output-results-259nm is [handle-large-output-results-259nm-3715707525 handle-large-output-results-259nm-1060231633 handle-large-output-results-259nm-3066201165]" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="node handle-large-output-results-259nm phase Running -> Succeeded" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="node handle-large-output-results-259nm finished: 2022-11-15 15:22:28.951411761 +0000 UTC" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="Checking daemoned children of handle-large-output-results-259nm" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="TaskSet Reconciliation" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg=reconcileAgentPod namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="Updated phase Running -> Succeeded" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="Marking workflow completed" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.951Z" level=info msg="Checking daemoned children of " namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.956Z" level=info msg="Workflow update successful" namespace=ceph phase=Succeeded resourceVersion=917717864 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:28.956Z" level=info msg="cleaning up pod" action=deletePod key=ceph/handle-large-output-results-259nm-1340600742-agent/deletePod
time="2022-11-15T15:22:28.967Z" level=info msg="cleaning up pod" action=labelPodCompleted key=ceph/handle-large-output-results-259nm-echo-1060231633/labelPodCompleted
time="2022-11-15T15:22:38.977Z" level=info msg="Processing workflow" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:38.978Z" level=info msg="Creating Artifact GC Task handle-large-output-results-259nm-artgc-wfcomp-2166136261-0" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:38.983Z" level=info msg="creating pod to delete artifacts: handle-large-output-results-259nm-artgc-wfcomp-2166136261" namespace=ceph strategy=OnWorkflowCompletion workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:38.989Z" level=info msg="Checking daemoned children of " namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:38.994Z" level=info msg="Workflow update successful" namespace=ceph phase=Succeeded resourceVersion=917717957 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:48.947Z" level=info msg="cleaning up pod" action=killContainers key=ceph/handle-large-output-results-259nm-echo-1060231633/killContainers
time="2022-11-15T15:22:48.991Z" level=info msg="Processing workflow" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:48.992Z" level=info msg="reconciling artifact-gc pod" message= namespace=ceph phase=Failed pod=handle-large-output-results-259nm-artgc-wfcomp-2166136261 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:48.992Z" level=info msg="processing completed Artifact GC Pod \"handle-large-output-results-259nm-artgc-wfcomp-2166136261\"" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:48.995Z" level=info msg="Checking daemoned children of " namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:49.000Z" level=info msg="Workflow update successful" namespace=ceph phase=Succeeded resourceVersion=917718061 workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:59.002Z" level=info msg="Processing workflow" namespace=ceph workflow=handle-large-output-results-259nm
time="2022-11-15T15:22:59.003Z" level=info msg="Checking daemoned children of " namespace=ceph workflow=handle-large-output-results-259n

### Logs from in your workflow's wait container

No logs were found:

$ kubectl logs -n ceph -c wait -l workflows.argoproj.io/workflow=handle-large-output-results-259nm,workflow.argoproj.io/phase!=Succeeded
error: container wait is not valid for pod handle-large-output-results-259nm-artgc-wfcomp-2166136261

**Comment by tooptoop4** [comment]
u need to configure 2nd block https://argoproj.github.io/argo-workflows/walk-through/artifacts/#service-accounts-and-annotations

**Comment by alexec** [comment]
AFAIK artifact GC does not use `spec.serviceAccountName` it uses `spec.artifactGC.serviceAccountName`.

**Comment by elemental-lf** [comment]
Thanks for the help, that was it! Missed that part in the documentation.
