### ISSUE TITLE
Archived workflows UI - labels tries to fetch every distinct value - very slow

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#10032]
when i type the key of the label (ie s3-file) there is a +30 second delay where it then populates the dropdown with all distinct values of s3-file (1000s). i would like a faster way to enter the direct value, else have to construct the URL in browser

![image](https://user-images.githubusercontent.com/33283496/201767960-73eee471-00d4-484d-9f33-2006f71c61af.png)

**Comment by terrytangyuan** [comment]
This would be addressed in https://github.com/argoproj/argo-workflows/pull/9999. Would you like to test it out?

**Comment by caelan-io** [comment]
@tooptoop4 - a fix for this was recently merged (#9999). Would you be able to retest this issue using `latest`? If you're not able to retest, we'll close this issue as fixed. Thanks for your help!

**Comment by terrytangyuan** [comment]
We have tested it so we can close this now (strangely the PR didn't close this automatically).

Feel free to re-open if needed.
