### ISSUE TITLE
Argo sees the pod in "Pending" phase after an error in init container occurs

### ISSUE THREAD

**Issue by CiprianAnton** [argoproj/argo-workflows#10060]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Noticed this behavior a couple of times, that if an error happens in an init container, Argo considers the pod in pending phase forever.

Here is the error I encountered in the init container:
`
Error (exit code 1): artifact ------- failed to load: failed to create new S3 client: WebIdentityErr: failed to retrieve credentials caused by: InvalidIdentityToken: Couldn't retrieve verification key from your identity provider, please reference AssumeRoleWithWebIdentity documentation for requirements status code: 400, request id: -------
`

I would expect Argo would detect this failure and mark the workflow as failed, but it's staying in progress for ever.

This is how Argo server is showing this:
![image](https://user-images.githubusercontent.com/4946899/202716661-0305748f-57a0-4e44-a21e-e62b3fcf28e4.png)

Not sure exactly how to reproduce this, but may be worth simulating an error in init container and see if the workflow fails or hangs.

### Version

v3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
-
```

### Logs from the workflow controller

-

### Logs from in your workflow's wait container

-

**Comment by terrytangyuan** [comment]
This will be fixed by https://github.com/argoproj/argo-workflows/pull/10047
