### ISSUE TITLE
Template level service account

### ISSUE THREAD

**Issue by bakayolo** [argoproj/argo-workflows#1009]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
Currently, it is only possible to specify a service account for a whole workflow.

**What you expected to happen**:
I d like to be able to specify a service account per step.
Indeed, my cicd needs to create a service at the very end and I need a specific service account just for this step.

**Comment by bappr** [comment]
Any feedback on this one?
My whole workflow is gaining a lot of access while only 1 step needs it.

**Comment by jessesuen** [comment]
This is a valid request. It should be simple to add this at a template level.
