### ISSUE TITLE
Python SDK PodDisruptionBudgetSpec Should Allow Integers 

### ISSUE THREAD

**Issue by yjabri** [argoproj/argo-workflows#10127]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I'm using the Python SDK for Argo Workflows (`pip install argo-workflows==6.4.3`). According to https://argoproj.github.io/argo-workflows/fields/#poddisruptionbudgetspec, `PodDisruptionBudgetSpec` should allow for int or string. However when I try to use an integer I get

```
argo_workflows.exceptions.ApiTypeError: Invalid type for variable 'min_available'. Required value type is str and passed type was int at ['min_available']
````

Here's a minimal example to reproduce the error

```python
from argo_workflows.models import IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec


IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec(
    min_available=1,
)
```

If I use '1' I get 

```
Failed: Unable to create PDB resource for workflow, example-s2lhp error: PodDisruptionBudget.policy "example-s2lhp" is invalid: spec.minAvailable: Invalid value: intstr.IntOrString{Type:1, IntVal:0, StrVal:"1"}: a valid percent string must be a numeric string followed by an ending '%'
```

edit: I get the above error when trying to run a CronWorkflow that contains
```yaml
    podDisruptionBudget:
      minAvailable: '1'
```
I haven't validated this with regular Workflows, but the issue here appears to be that the python SDK is being too strict.

### Version

Tested on both v3.0.1 and v3.4.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

This issue is with the SDK and not about a specific workflow

### Logs from the workflow controller

This issue is with the SDK and not about the controller.

### Logs from in your workflow's wait container

This issue is with the SDK and not about  a specific workflow.

**Comment by yjabri** [comment]
Of course it didn't occur to me until I posted this that I could simply do
```
pod_disruption_budget=PodDisruptionBudgetSpec(
    min_available=1,
    _check_type=False
),
```
to circumvent the issue.

**Comment by terrytangyuan** [comment]
It's a known bug from open-api-generator. Closing as duplicate.
