### ISSUE TITLE
Release build broke due to Cosign 

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#10123]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Build should pass. 

https://github.com/argoproj/argo-workflows/actions/runs/3545014347/jobs/5954053716

### Version

Latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by terrytangyuan** [comment]
@34fathombelow

**Comment by 34fathombelow** [comment]
@alexec Were the Cosign secrets created?  It appears the secrets were not found, only the workflow-controller manifest was pushed as `latest` due to the failure.  
![Screenshot_20221128_071725](https://user-images.githubusercontent.com/76892343/204332741-a831509e-b484-40c0-8aa3-65e3bef067b2.png)

**Comment by terrytangyuan** [comment]
@alexec @sarabala1979 Could you add the secrets? Otherwise, the release workflow fails.

**Comment by sarabala1979** [comment]
secreted

**Comment by 34fathombelow** [comment]
I believe this issue can now be closed. Release workflow is now working.

`https://github.com/argoproj/argo-workflows/actions/runs/3578364822`
`https://github.com/argoproj/argo-workflows/actions/runs/3575972353`

**Comment by terrytangyuan** [comment]
Thanks!
