### ISSUE TITLE
UI: retry just one step, not whole workflow

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#10139]
is there anyway to just retry one step  (ie clicking through the UI)  in a workflow without resubmitting whole workflow (which would run all steps)?

cc @dpadhiar

**Comment by terrytangyuan** [comment]
You can select nodes to retry via the CLI but I don't think it's available in the UI.

**Comment by SamuelJohnson01997** [comment]
Hi. Can I take this up?

**Comment by tooptoop4** [comment]
sure! u can raise PR without being 'assigned'
