### ISSUE TITLE
Workflow TTL Strategy based on number of workflows in different phases

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#10154]
# Summary

What change needs making?

The current TTL strategy is time-based to delete workflows after x/y/z seconds of success/failure/completion.

Alternatively, we can support only deleting a subset of the workflows. For example, only keep a maximum of x/y/z number of succeeded/failed/completed workflows. All remaining completed workflows are deleted.

# Use Cases

When would you use this?

Some users want to keep a number of workflows in each phase for analysis or debugging purposes. It's also easier to see a list of current running workflows + history of the failed/successful ones in one page.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
> Alternatively, we can support only deleting a subset of the workflows. For example, only keep a maximum of x/y/z number of succeeded/failed/completed workflows. All remaining completed workflows are deleted.

This was/is possible already with `retentionPolicy` as of https://github.com/argoproj/argo-workflows/pull/6854, duplicating #5639
