### ISSUE TITLE
Suggestion: skip unnecessary workflows if only have documentary changes

### ISSUE THREAD

**Issue by LinuxSuRen** [argoproj/argo-workflows#10156]
# Summary

As I mentioned in the title. It's totally not necessary to run the whole workflow all the time.

# Use Cases

As you can see below, I only made some documentary changes in this PR

![image](https://user-images.githubusercontent.com/1450685/205197073-f1ec7cfc-4f13-45a2-b223-35dd0a266296.png)

See https://github.com/argoproj/argo-workflows/pull/10155

We could skip the e2e workflow by some filters.
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by caelan-io** [comment]
agreed. we are considering this. related to #10265
