### ISSUE TITLE
Implement retries in the process of uploading artifacts to the GCS

### ISSUE THREAD

**Issue by laughingman7743** [argoproj/argo-workflows#10174]
# Summary

Implement retries in the process of uploading artifacts to the GCS.

# Use Cases

I am using GCS's as a repository for artifacts, and the workflow sometimes fails due to a TLS handshake timeout on the upload of the workflow log.
```
Error (exit code 1): upload /tmp/argo/outputs/logs/main.log: writer close: Post "https://storage.googleapis.com/upload/storage/v1/bargo-artifacts/o?alt=json&name=argo-workflows%2F2022%2F12%2F05%2Ffoobar-1670202000%2Ffoobar-1670202000-3856682942%2Fmain.log&prettyPrint=false&projection=full&uploadType=multipart": net/http: TLS handshake timeout
```
I think it is not essential that the workflow process itself succeeds, the log upload causes an error, and the entire workflow fails. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by kevholmes** [comment]
@laughingman7743 what version of Argo Workflows are you using where you see this error?

**Comment by laughingman7743** [comment]
@kevholmes I am still using 3.3.6. Thanks for your PR, looks like a good change. I am hoping it will be merged.
