### ISSUE TITLE
Local DevContainer setup Issue, User being prompted to provide password when using sudo

### ISSUE THREAD

**Issue by sid8489** [argoproj/argo-workflows#10224]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

For users whose username contains "."  eg: **siddharth.agr**, the configuration of adding that user to sudoers list with NOPASSWD [Here](https://github.com/argoproj/argo-workflows/blob/master/.devcontainer/Dockerfile#L17) is buggy.
 User is Still being prompted to provide password.

Reason : 
[Including other Files within Sudoers
](https://www.sudo.ws/docs/man/1.8.15/sudoers.man/#Including_other_files_from_within_sudoers)
> sudo will read each file in /etc/sudoers.d, skipping file names that end in ‘~’ or contain a ‘.’ character to avoid causing problems with package manager or editor temporary/backup files.

Fix:
Either hardcode the file name (I don't see any issue) or remove the . from name variable 

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
NA
```

### Logs from the workflow controller

```text
NA```


### Logs from in your workflow's wait container

```text
NA
```

**Comment by sarabala1979** [comment]
@sid8489 Is it Argo workflow issue? Can you provide more information about your scenario?

**Comment by sid8489** [comment]
> @sid8489 Is it Argo workflow issue? Can you provide more information about your scenario?

Yes, Any user who has a dot in his/her username would not be able to run argo workflow locally using devcontainer.
eg: Consider a User whose username is **siddharth.agr**  .  If such a user  starts devcontainer , he will be promted to provide password to run sudo commands in startup.sh script [Here](https://github.com/argoproj/argo-workflows/blob/master/.devcontainer/startup.sh#L4).
![image](https://user-images.githubusercontent.com/85802930/207947436-f59e1788-25ba-4dbb-ac01-c1e90cc05bad.png)


Reason :
the configuration of adding that user to sudoers list with NOPASSWD [Here](https://github.com/argoproj/argo-workflows/blob/master/.devcontainer/Dockerfile#L17) is buggy.

[Including other Files within Sudoers](https://www.sudo.ws/docs/man/1.8.15/sudoers.man/#Including_other_files_from_within_sudoers)

sudo will read each file in /etc/sudoers.d, skipping file names that end in ‘~’ or contain a ‘.’ character to avoid causing problems with package manager or editor temporary/backup files.

**Comment by agilgur5** [comment]
I think this is no longer an issue as the [devcontainer](https://github.com/argoproj/argo-workflows/tree/v3.5.0-rc1/.devcontainer) has changed a good bit.

Please file a new issue if you're having a trouble with the devcontainer
