### ISSUE TITLE
Investigate if ArtifactsSuite/TestArtifactGC is flakey

### ISSUE THREAD

**Issue by isubasinghe** [argoproj/argo-workflows#10230]

**Comment by isubasinghe** [comment]
@juliev0 I believe it is this one: https://github.com/argoproj/argo-workflows/actions/runs/3691130662/jobs/6248880760

**Comment by juliev0** [comment]
> @juliev0 I believe it is this one: https://github.com/argoproj/argo-workflows/actions/runs/3691130662/jobs/6248880760

Thanks for finding it!

**Comment by juliev0** [comment]
For some reason the wait container isn't saving the artifact into minio some of the time, so then when the test expects that the artifact was not deleted, it was never saved in the first place. I'll try to determine why the artifact isn't getting saved.

**Comment by juliev0** [comment]
It seems like maybe the wait container is dying before it's finished, according to this sequence of events:
1. [Here](https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/operator.go#L1387) the Controller determines that it can send a SIGTERM to the Pod only once the main container is done (but the wait container may still be running)
2. The wait container has tied its context to SIGTERM, such that the context is marked 'done' when the SIGNAL arrives [here](https://github.com/argoproj/argo-workflows/blob/master/cmd/argoexec/commands/wait.go#L38).
3. Maybe the context has been passed into some of the logic required for saving an artifact, which doesn't perform the action if the context is stopped ?

**Comment by juliev0** [comment]
It seems like maybe the wait container is dying before it's finished, according to this sequence of events:
1. [Here](https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/operator.go#L1387) the Controller determines that it can send a SIGTERM to the Pod only once the main container is done (but the wait container may still be running)
2. The wait container has tied its context to SIGTERM, such that the context is marked 'done' when the SIGNAL arrives [here](https://github.com/argoproj/argo-workflows/blob/master/cmd/argoexec/commands/wait.go#L38).
3. Somehow the wait container seems to be issuing an exit code 2 when the SIGTERM arrives. I'm not sure what would cause an Exit Code 2?
