### ISSUE TITLE
Request to support cancel any in-progress workflow

### ISSUE THREAD

**Issue by LinuxSuRen** [argoproj/argo-workflows#10251]
# Summary

The [synchronization](https://argoproj.github.io/argo-workflows/synchronization/) feature could set the workflow running limitation. But in some cases, we hope the old workflows could be canceled, then run the latest one only.

# Use Cases

Similar to the [GitHub Workflows](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency). For a pull-request, it's not necessary to all every single workflow. Run the latest one is good enough. So, I suggest that we could have this one.

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by tooptoop4** [comment]
similar to https://github.com/argoproj/argo-workflows/issues/8904 and maybe tracked by https://github.com/argoproj/argo-workflows/issues/11849

**Comment by agilgur5** [comment]
> maybe tracked by #11849

No that issue is mostly a syntactic / naming clarity and does not change existing semantics.

> similar to #8904

Yes, I think these are both effectively superseded by #12757.
