### ISSUE TITLE
Better segmentation of tests

### ISSUE THREAD

**Issue by isubasinghe** [argoproj/argo-workflows#10265]
# Summary

Currently every single test is run on a PR, we should only run tests if they are relevant to the changed files. 

# Use Cases
This will increase the speed of iteration for developers, but more importantly it will lessen the probability of blocking PRs due to flakey tests. A documentation PR should not be blocked by a flakey test for example.

**Comment by caelan-io** [comment]
Discussed today in contributor meeting: cc @sarabala1979 @juliev0 
- We're okay to remove tests for docs changes
- We're open to segmenting the tests, so next step is to look into a way to implement this with GitHub Actions
- exception: when the Argo Controller changes, we need to run all tests

**Comment by agilgur5** [comment]
assigned this to myself as I had mentioned it in https://github.com/argoproj/argo-workflows/pull/11301#issuecomment-1625787551 and had looked into it. I was looking to make this change recently as I was fixing E2E flakes, adding auto retries etc (as discussed in [recent](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.fvdawp2rsh5d) [contributor meetings](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.k1l4irxjo6vc)). 

as I mentioned there, https://github.com/tj-actions/changed-files is the most commonly used, popular, and recently updated Action for this.

the only thing is that we'd have to do this naively based on manual glob search, as Make isn't tracking the full list of dependent files etc to automatically recognize what needs to run.
