### ISSUE TITLE
Workflow failure doesn't print the template name and pod name in workflow controller logs

### ISSUE THREAD

**Issue by Sushant20** [argoproj/argo-workflows#10270]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

In v3.2.6, Workflow controller logs used to show logs in below format when particular workflow used to fail after retries.

`time="2022-06-14T19:16:55.821Z" level=info msg="Pod failed: Error (exit code 1)" displayName="test-wf-stage(0)" namespace=argo pod=test-workflow-list-fjgcx-4290651735 templateName=test-wf-stage workflow=test-workflow-list-fjgcx`

Above logs was very useful to get display name/template name, pod name along with workflow name

After upgrade to 3.4.4, 

Above logs are not absent , I could now see below log format on failure (Template name and pod names are absent)

`time="2022-12-19T11:46:24.991Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=test-workflow-list-fnecr`

This seems like a bug, is there a way to get template name/display name and pod name on failure from workflow controller pod logs? 

### Version

3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
NA
```

### Logs from the workflow controller

```text
NA
```

### Logs from in your workflow's wait container

```text
NA
```

**Comment by Sushant20** [comment]
@alexec @sarabala1979 Probably relates to enhancement made in this PR: https://github.com/argoproj/argo-workflows/issues/7996

**Comment by sarabala1979** [comment]
@Sushant20 Do you like to add it back? Please submit the PR
