### ISSUE TITLE
SSO RBAC is not working in version 3.4.3 when keycloak is used as OIDC provider

### ISSUE THREAD

**Issue by sujaykulkarn** [argoproj/argo-workflows#10294]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Hi,
I am trying to bring up the argo server with SSO enabled, I have followed the documentation (https://argoproj.github.io/argo-workflows/argo-server-sso/#sso-rbac) created required secret and other necessary stuff. 
When I login with the keycloak user, I am able to login but the service account associated with the group is not showing in UI, nor it's taking automatically. Please help me with this issue. 

![image](https://user-images.githubusercontent.com/31735981/210201761-dc619ba1-de72-4502-979f-eae7adef9f38.png)

My RBAC configuration is as follows:

`apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argoAdmin
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  verbs:
  - get
  - list
  - watch
  - delete
  - patch
- apiGroups:
  - "policy"
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workfloweventbindings
  - workflowtemplates
  - cronworkflows
  - cronworkflows/finalizers
  - workflowtemplates
  - cronworkflows
  - cronworkflows/finalizers
  - workflowtaskresults
  - workflowtasksets
  - workflowartifactgctasks
#  - clusterworkflowtemplates #If creating crb ,please uncomment this
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argoadmin-cluster-template
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argoAdmin
subjects:
- kind: ServiceAccount
  name: argoadmin
  namespace: argotest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argoadmin
  namespace: argotest
  annotations:
    workflows.argoproj.io/rbac-rule: "'argoadmingroups' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
`
No error or warning logs are present in the argoserver logs. 

### Version

v3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
NA
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
NA
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

NA
```

**Comment by sarabala1979** [comment]
@sujaykulkarn Do you like to debug and fix this issue?
Here the code
https://github.com/argoproj/argo-workflows/tree/master/server/auth/sso#:~:text=2%20years%20ago-,sso.go,-fix%3A%20Ensure%20the

**Comment by umi0410** [comment]
I think Keycloak SSO worked on my environment like the following.

![CleanShot 2023-07-16 at 10 55 10](https://github.com/argoproj/argo-workflows/assets/33250725/9f182676-3a1c-4332-a230-65b955006ed9)

![CleanShot 2023-07-16 at 10 56 10](https://github.com/argoproj/argo-workflows/assets/33250725/1466ac9b-9ba8-4b81-bdaf-7d6f04f7d8ed)

This is my environment.

| Name | Name | 
|  -- |  --  |
| Kubernetes | k3s 1.26.4 |
| Keycloak | 17.0.1-legacy |
| Argo Worfklows | v3.4.8 |

If there is someone who needs more detailed information about my environment, I would be happy to assist . However, at the moment, I don't think there is anyone.

**Comment by agilgur5** [comment]
Going to close this out as two users were unable to reproduce and OP never responded.
I also have SSO RBAC working (and have contributed features to it), albeit with Dex, not Keycloak.

Please open a new issue with a minimal reproduction if you experience a problem with SSO RBAC.
