### ISSUE TITLE
can i assign parallelism from inputs parameter? i try to do like below, but error occurs

### ISSUE THREAD

**Issue by leveryd** [argoproj/argo-workflows#10305]
# Summary

<img width="938" alt="image" src="https://user-images.githubusercontent.com/1846319/210479624-484ce73b-b1ca-4062-9f11-9615bc958b99.png">

it seems like "https://github.com/argoproj/argo-workflows/issues/1780" is the same needs

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by sasagarw** [comment]
I can try working on this

**Comment by agilgur5** [comment]
Yea this would be a duplicate of #1780. Making the type able to parse strings as mentioned there would fix this.
