### ISSUE TITLE
slack?

### ISSUE THREAD

**Issue by krisdock** [argoproj/argo-workflows#10315]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

the slack links on the website go to non-existent channels on the cncf slack. does argoproj have its own slack now?

### Version

na

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
na
```

### Logs from the workflow controller

```text
na
```

### Logs from in your workflow's wait container

```text
na
```

**Comment by sarabala1979** [comment]
it is taking to right page for me

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/33908564/211167975-3a45c489-0669-4d67-9782-9398ac1ff9e5.png">

**Comment by sarabala1979** [comment]
you can find the channels in below

**Comment by krisdock** [comment]
do the channel links on that page work for you?

**Comment by sarabala1979** [comment]
it is working for me.
https://cloud-native.slack.com/archives/C01QW9QSSSK
Can you try this link?

**Comment by caelan-io** [comment]
Works for me as well. Argo Workflows URL match the channel ID for #argo-workflows

**Comment by krisdock** [comment]
<img width="1158" alt="Screen Shot 2023-01-13 at 1 20 41 PM" src="https://user-images.githubusercontent.com/2001313/212391767-b2f9cb4f-12a0-497d-be94-8b10e2fcf438.png">

**Comment by krisdock** [comment]
i get that when i click on any of the channels on that page

**Comment by krisdock** [comment]
i figured out the issue. my slack account was marked as a guest account, limiting which channels i could see. got this resolved.
