### ISSUE TITLE
Beyond Input/Output Artifacts: Pipes and Ports 

### ISSUE THREAD

**Issue by vicaire** [argoproj/argo-workflows#1031]
FEATURE REQUEST: 

Today, Argo supports Artifacts, where a container can store a file in a local volume, and where Argo will automatically upload that file to either the default artifact repository, or to the location specified by the user. 

Would it make sense to have similar support for pipes and ports? For instance: 
- A container would just read/write to a named pipe. Argo would stream data into/from the container through the pipe from/to, for instance, a Pub/Sub queue. This would provide support for streaming so that the input data does not need to be entirely downloaded to the disk before it can be processed. 
- A container would just make service calls to a local port. Argo would wire this port to the correct endpoint. 

Together, these options would make containers completely independent of infrastructure. They would just write/read from ports/local files/pipes. Argo would take care of wiring these locations to the correct source/destination.

**Comment by wookasz** [comment]
Have you checked out https://github.com/argoproj/argo-events?

**Comment by vicaire** [comment]
wookasz@, what we are looking for is an integrated solution: 
- We can define a complex workflow using Argo. 
- One container within that workflow can output data to a Named Pipe
- Argo automatically forward the data outputed through the named pipe to the default storage location. 

I am not sure how to use argo-events within an Argo workflow to accomplish this.

**Comment by Duske** [comment]
@vicaire Interesting feature request, I'm currently looking for such a solution as well. It basically describes a similar functionality like [Apache Camel](https://github.com/apache/camel) for routing data, doesn't it?
Have you found an alternative solution/approach?

**Comment by vicaire** [comment]
@Duske, yes, I think it would be very useful for Argo to support this feature.

**Comment by alexec** [comment]
Apache Pulsar?

**Comment by alexec** [comment]
See #4988

**Comment by alexec** [comment]
I think that #4988 duplicates this issue.
