### ISSUE TITLE
Workflow can not find WorkflowTemplate when deployed together with Helm chart

### ISSUE THREAD

**Issue by i540608** [argoproj/argo-workflows#10344]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Hi,

I have a project that deploys all the artifacts to Kubernetes cluster as Helm package
and it includes multiple Argo workflows, that re-use same workflowtemplates to avoid copy-pasting same steps over and over again;

i noticed that whenever i deploy a Argo workflow that uses Workflowtemplate with Helm to the empty Kubernetes cluster, then the workflow fails with template-not-found error and it's never retried; Although i am able to see template on cluster; 

I would expect that 
* a Argo workflow would find a template regardless of order by which Helm applies templates to the Kubernetes cluster
*  and i would expect that Argo workflow would at least retry if retryStrategy is specified;

I am wondering if it's known issue and if there's a way to deploy workflows together with templates without depending Helm's order?

### Version

v3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
I attached zip file with Helm templates to the ticket because it requires a bit more than just a yaml file;
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep argo-not-found-workflow

Found 2 pods, using pod/workflow-controller-77b45cd56b-6l9c6
time="2023-01-11T10:51:05.750Z" level=info msg="Processing workflow" namespace=default workflow=argo-not-found-workflow
time="2023-01-11T10:51:05.750Z" level=info msg="Updated phase  -> Error" namespace=default workflow=argo-not-found-workflow
time="2023-01-11T10:51:05.750Z" level=info msg="Updated message  -> workflowtemplates.argoproj.io \"argo-not-found-template\" not found" namespace=default workflow=argo-not-found-workflow
time="2023-01-11T10:51:05.750Z" level=info msg="Marking workflow completed" namespace=default workflow=argo-not-found-workflow
time="2023-01-11T10:51:05.750Z" level=error msg="Unable to set ExecWorkflow" error="workflowtemplates.argoproj.io \"argo-not-found-template\" not found" namespace=default workflow=argo-not-found-workflow
time="2023-01-11T10:51:05.750Z" level=info msg="Checking daemoned children of " namespace=default workflow=argo-not-found-workflow
time="2023-01-11T10:51:05.756Z" level=info msg="cleaning up pod" action=deletePod key=default/argo-not-found-workflow-1340600742-agent/deletePod
time="2023-01-11T10:51:05.757Z" level=info msg="Workflow update successful" namespace=default phase=Error resourceVersion=47927 workflow=argo-not-found-workflow
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=argo-not-found-workflow,workflow.argoproj.io/phase!=Succeeded

No resources found in argo namespace.
```

**Comment by i540608** [comment]
Helm template for reproducing the issue:
[argo-not-found.zip](https://github.com/argoproj/argo-workflows/files/10391956/argo-not-found.zip)

**Comment by sarabala1979** [comment]
@tico24 Can you help with this issue? JP mentioned you already helped with helm hook

**Comment by tico24** [comment]
I haven't done any helm deployment of workflows, no.

**Comment by tico24** [comment]
Hi @i540608 @sarabala1979  - I ran the .zip. This is not a helm issue. The same will happen with a hand-crafted yaml that's applied using kubectl apply. I personally don't see it as an issue, this is how I would expect things to work.

I would not expect the retrystrategy to kick in because the workflow is effectively invalid (because the template is missing).

As you summised, you will need to make an order dependency if you wish to deploy both items with the same helm chart.

**Comment by dongyingbo** [comment]
I just tried that after adding

  annotations:
    "helm.sh/hook": post-install
to Workflow and CronWorkflow CRs they are rendered and installed after WorkflowTemplate as expected.

NOTE: it works for helm3 only but not helm2.
