### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by linyao22** [argoproj/argo-workflows#10373]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have previous 5yr experience in backend using C++. I'm also learning go in concrete projects in recent months. No experience in frontend.**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #9913 or #5464, but open to other issue if fits better. Our team have a few other ideas that may need advice as well.**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: Open to sync to kick off, and async afterwards. Temporarily in China Standard Time (UTC+8) for now. But I will be in Eastern Standard Time (UTC-4/5) most of time going forward.

**Comment by juliev0** [comment]
I can try to help out some, although still relatively new to this code as well. We can focus on the areas of the code for the two issues you’re interested in.

**Comment by juliev0** [comment]
By the way, typically we recommend newcomers to start with the issues labeled [good-first-issue](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22). Would you want to do that first, or jump straight into the issues you are wanting? I presume https://github.com/argoproj/argo-workflows/issues/9913 and https://github.com/argoproj/argo-workflows/issues/5464 are the ones you're interested in for your own project? It looks like the first one may require some front end as well so you may need to learn some basic React.

**Comment by linyao22** [comment]
Thanks Julie!
Our team listed a few items already and these two are existing issues matching our list so far.  As we do not distinguish front/backend role per person in the long run so I will learn React sooner or later.
For first item only, seems to me https://github.com/argoproj/argo-workflows/issues/9913 is easier to work on so I'll probably start with it. I'm learning some React basics by making changes for it. I'll probably submit commits next week or DM via Slack if hit blocker.

**Comment by juliev0** [comment]
Great. How about you contact me at julie_vogelman@intuit.com and let me know any specific questions? or if you want a general overview of things? (With Argo Workflows the code is so big that I'm always needing to spend time to learn the code myself when I pick up something new.)

**Comment by juliev0** [comment]
By the way, it sounds like you already started on this issue so you probably already found [workflow-logs-viewer.tsx](https://github.com/argoproj/argo-workflows/blob/master/ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx) where the code lives? And are you able to run things locally according to the instructions [here](https://argoproj.github.io/argo-workflows/running-locally/)? (or if you have another way that's fine) And are you using the Developer Tools on your browser for debugging?

You may already know but the Argo Server HTTP listener is set up in [argoserver.go](https://github.com/argoproj/argo-workflows/blob/master/server/apiserver/argoserver.go#L319). As I recall, the backend endpoint hit here is [/artifact-files](https://github.com/argoproj/argo-workflows/blob/master/server/apiserver/argoserver.go#L192).

**Comment by Radolumbo** [comment]
Thanks Julie! :)

**Comment by linyao22** [comment]
Thanks for Julie's help! I've submit this PR https://github.com/argoproj/argo-workflows/pull/10397 and all checks passed.
