### ISSUE TITLE
option to append timestamp to workflowname

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#10372]
alternative to https://github.com/argoproj/argo-workflows/issues/6807

basic issue trying to solve is wf name conflicts (when generated via cronwf) as 5 random characters is not unique

**Comment by agilgur5** [comment]
Is this achievable with an [expression](https://argoproj.github.io/argo-workflows/variables/#expression)?

I have done used an expression with a timestamp before for `resource` templates, but have never tried on a CronWorkflow.

**Comment by agilgur5** [comment]
Your other issue https://github.com/argoproj/argo-workflows/issues/7900 I think is a more generic option that would supersede this.

> Is this already achievable with an [expression](https://argoproj.github.io/argo-workflows/variables/#expression)?
> 
> I have used an expression with a timestamp before for `resource` templates, but have never tried on a CronWorkflow.

I described this a bit in https://github.com/argoproj/argo-workflows/issues/7900#issuecomment-2421494824 as well
