### ISSUE TITLE
Add AWS Session Token support

### ISSUE THREAD

**Issue by jhsmith** [argoproj/argo-workflows#1039]
This is a feature request.

Please add support for AWS session tokens as an optional credential for S3 access. In our corporate account we have to use session tokens in addition to the access key and secret key when doing local development.

I see that you create a minio client with NewWithRegion. It looks like you could pass in a Session Token  you instead use NewWithCredentials instead.

**Comment by mocsharp** [comment]
Any workaround for using temporary credentials and a session token to access MinIO artifact store?

**Comment by agilgur5** [comment]
This was superseded by #5446 which has more upvotes and PRs out to be merged soon.
