### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by luyang93** [argoproj/argo-workflows#10409]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I am a newbie on Go, and have some experience on Kubernetes**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #873**, execute WDL in argo.

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: async better, utc+8

**Comment by luyang93** [comment]
I find that WDL uses antlr4 as its primary grammar definition and parser generation tool.
https://github.com/openwdl/wdl/tree/main/versions/1.0/parsers

**Comment by caelan-io** [comment]
Hi there, welcome to the Argo community! @isubasinghe can provide guidance based on his prior work on integrating with CWL listed on the issue. Commenting directly on the PRs listed in [this comment](https://github.com/argoproj/argo-workflows/issues/873#issuecomment-1063370137) might be the best first step.

**Comment by caelan-io** [comment]
Hi @luyang93 - Have you been able to make any progress on WDL support? We're considering reviving these PRs for a release this year. Please let me know what your plan is. Thanks!

**Comment by shuangkun** [comment]
I‘m working on it, we can have a if you have time. @luyang93
