### ISSUE TITLE
Replace `httpbin` with something up to date

### ISSUE THREAD

**Issue by rafrafek** [argoproj/argo-workflows#10427]
`httpbin` is no longer maintained and does not support arm64 architecture.

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/23004737/215749567-f4e2a7dc-1661-452d-85cd-7775a74ca3ce.png">

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by rafrafek** [comment]
To be honest I don't know. Argo is new for me and I have never worked with httpbin before. I just wanted to raise this topic to the community.

**Comment by rafrafek** [comment]
I googled `"replace httpbin with"` and `"replaced httpbin with"` (with double quotes) and found other alternatives:
- https://github.com/pomerium/pomerium/pull/1702
- https://github.com/microsoft/azure-pipelines-tool-lib/issues/44
- https://github.com/apache/trafficserver/issues/8767
- https://github.com/AngleSharp/AngleSharp.Io/commit/f11e802275f9533342e3de1627be78ee86222f92

**Comment by sonbui00** [comment]
I have the same issue, can not run on Mac M1. This also happens for hello world example (use image docker/whalesay:latest): https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/hello-world.yaml
