### ISSUE TITLE
`argosay` uses `amd64` architecture instead of `arm64` on `arm64` machine

### ISSUE THREAD

**Issue by rafrafek** [argoproj/argo-workflows#10435]
# Summary

[argosay](https://hub.docker.com/r/argoproj/argosay/tags) should also be available for arm64, not only for amd64.

# Use Cases

Many people use arm64 machines.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by sonbui00** [comment]
The base image also have security issue;
https://hub.docker.com/layers/library/ubuntu/trusty-20190515/images/sha256-2feffff9eeca4e736f9f8e57813a97fe930554f474f7795ffa5a9261adeaaf44?context=explore

**Comment by terrytangyuan** [comment]
The Dockerfiles are here. Feel free to submit a PR to fix: https://github.com/argoproj/argo-workflows/tree/a68ea0feabc87c09d5e13d12e6f0d1a61adc5b16/test/e2e/images/argosay

**Comment by jyje** [comment]
Hello. I've noticed that there is still no images available for the linux/arm64 architecture after b0909c6 commit. As shown in the Argo Project Docker Hub, https://hub.docker.com/r/argoproj/argosay/tags ![image](https://github.com/argoproj/argo-workflows/assets/109659358/505b71fe-91de-463f-9937-7ef1cb889d4e) there seems to be a lack of recent updates for the `linux/arm64` architecture

Is there any plan to release a new image supporting the linux/arm64 architecture? Please let me know your plans for this issue.

I believe the following two options might be promising:
- OPTION 1: overwrite `argoproj/argosay:v2` by adding a `linux/amd64` image
- OPTION 2: add `argoproj/argosay:v3` which would include images for both `linux/amd64, linux/arm64`.

I hope that I can run argosay in my raspberry pi cluster soon 😊. Thank you in advance.

**Comment by jyje** [comment]
@sonbui00 @terrytangyuan Hello. Is there any update for this?

**Comment by sonbui00** [comment]
@jyje I think the code have been approved, but the container has not built and pushed to the docker. Let's me check with the team

**Comment by jyje** [comment]
Thank you 😊
