### ISSUE TITLE
how get argo-client-java source code

### ISSUE THREAD

**Issue by simonChen0317** [argoproj/argo-workflows#10440]
how can I get argo-client-java source code。thanks

**Comment by OneCricketeer** [comment]
You can use `openapi-generator` with the OpenAPI spec. At least, this is how the Python client is built.

**Comment by agilgur5** [comment]
It's the same for the Java SDK, see its [Makefile](https://github.com/argoproj/argo-workflows/blob/c80b2e91ebd7e7f604e88442f45ec630380effa0/sdks/java/Makefile)
