### ISSUE TITLE
Update Issue - `Failed to load version/info Error: Unsuccessful HTTP response`

### ISSUE THREAD

**Issue by paologodinho** [argoproj/argo-workflows#10477]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

After I update for any version above V3.0.2 I lost the access to my application and I'm receiving one issue:
```
Failed to load version/info Error: Unsuccessful HTTP response
```
When my system call the internal API from argo-workflow I tracked the follow error:

My API: https://argo-xxx.int.xxx.eu/api/v1/info

Request URL: https://argo-yyyy.int.yyyy.eu/api/v1/info
Request Method: GET
Status Code: 401 
Remote Address: 34.240.226.59:443
Referrer Policy: strict-origin-when-cross-origin

![Argo erro https Error](https://user-images.githubusercontent.com/56321676/216927393-9b8cd890-d21f-47df-99ac-31ec6864500d.png)

**Comment by paologodinho** [comment]
hey guys, any update about my question?

**Comment by JPZ13** [comment]
Hey @paologodinho. Thanks for reporting the issue - is the issue that you are being forced to login/authenticate after upgrading?

Additionally, can you fix the formatting in your post above? It makes it hard to read and figure out what's going on

**Comment by paologodinho** [comment]
> Hey @paologodinho. Thanks for reporting the issue - is the issue that you are being forced to login/authenticate after upgrading?
> 
> Additionally, can you fix the formatting in your post above? It makes it hard to read and figure out what's going on

Hey @JPZ13 yes, after the update it's happen.
