### ISSUE TITLE
Redirect querystring is ignored during login when redirecting to archived workflow

### ISSUE THREAD

**Issue by jmeridth** [argoproj/argo-workflows#10481]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

## Current

- user clicks link to argo-workflows from external location (example: GitHub check)
  - the URL is the non-archived version of the workflow but the workflow has been archived
- user is not logged in
- user logs in
- user is redirected to workflow dashboard (.../workflows)

## EXPECTED

- user clicks link to argo-workflows from external location (example: GitHub check)
  - the URL is the non-archived version of the workflow but the workflow has been archived
- user is not logged in
- user logs in
- user is redirected to specific archived workflow (.../archived-workflows/WORKFLOW-NAMESPACE-HERE/WORKFLOW-UUID-HERE)

[Related PR](https://github.com/argoproj/argo-workflows/pull/7854) that handled redirecting users to archived workflows view if they workflow has been archived

### Version

v3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Not workflow specific, so any will do.  This is a URL redirect issue
```

### Logs from the workflow controller

```text
redirect happens in the UI, not able to find anything specific in the server logs
```

### Logs from in your workflow's wait container

```text
redirect happens in the UI, not able to find anything specific in the server logs
```

**Comment by jmeridth** [comment]
I would like to tackle this one

**Comment by caelan-io** [comment]
Thanks for taking this on, @jmeridth ! Please let me or @isubasinghe know if you have any questions.

**Comment by jmeridth** [comment]
I'm starting to think this can't be fixed.  🤔 

Since the SSO endpoint typically just calls `$ARGO_WORKFLOW_URL/oauth2/callback` callback URL and does not include the `?redirect=path_to_workflow` the user will be redirected to `/workflows` which is already working.  If the user is still authenticated and doesn't need to reauth with SSO, the user is redirected correctly to `/archived-workflows` for archived workflows.

**Comment by jmeridth** [comment]
Gonna brush up on my oauth2 metadata/query params.  That may be the answer.

**Comment by jmeridth** [comment]
Yep, looks like the `state` parameter/querystring.

**Comment by jmeridth** [comment]
[Here](https://github.com/argoproj/argo-workflows/blob/b16b53d6ae46de609bab7d65baea69556fc0f6f5/server/auth/sso/sso.go#L208) and [here](https://github.com/argoproj/argo-workflows/blob/b16b53d6ae46de609bab7d65baea69556fc0f6f5/server/auth/sso/sso.go#L229) is where state is included for SSO calls.

**Comment by jmeridth** [comment]
Not stale. Working on this in next few days.

**Comment by jmeridth** [comment]
Closing.  This is moot once 3.5 releases with the unified Workflows and Archived Workflows view.
