### ISSUE TITLE
archive cli not working

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#10497]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

```
bash-5.1# ./argo-linux-amd64 list -n x
NAME                     STATUS      AGE   DURATION   PRIORITY   MESSAGE
readact-1676011800   Succeeded   1m    22s        0

bash-5.1# ./argo-linux-amd64 archive list -n x
FATA[2023-02-10T06:51:24.824Z] this is impossible if you are not using the Argo Server, see https://argoproj.github.io/argo-workflows/cli/
bash-5.1#
```

### Version

v3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by gocpplua** [comment]
me too, argo: v3.4.2

**Comment by tooptoop4** [comment]
https://argoproj.github.io/argo-workflows/cli/argo/ gives some hints that default mode doesn't work with archive, need to use diff mode but the error message should be cleared up as 'https://argoproj.github.io/argo-workflows/cli/' page is unreadable

**Comment by gocpplua** [comment]
> https://argoproj.github.io/argo-workflows/cli/argo/ gives some hints that default mode doesn't work with archive, need to use diff mode but the error message should be cleared up as 'https://argoproj.github.io/argo-workflows/cli/' page is unreadable

Didn't see diff mode

**Comment by nicolas-vivot** [comment]
please link that "diff mode" stuff, where is it ?
