### ISSUE TITLE
Specify behavior when a container does not exist. 

### ISSUE THREAD

**Issue by vicaire** [argoproj/argo-workflows#1055]
FEATURE REQUEST: Behavior when a container does not exist.

When a container does not exist and is used as a step of the workflow, it seems that Argo retries forever.  

Could we make this behavior configurable for each step so that, for instance, we could specify that there should be no retires, retries, or a timeout?

**Comment by alexec** [comment]
I've not need this behaviour. Please re-open if you see it.
