### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by sandeepk8s** [argoproj/argo-workflows#10563]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have previous experience with kubernetes and no experience in Go.**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #9651 **

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: (async/sync) (timezone) async or sync both works for me as per mentor convenience (EST)

**Comment by sandeepk8s** [comment]
Hi @caelan-io thanks for the reply, Option 1, I think

I'm new to Go and never did core development (only devops stuff with some scripting 😄 ) but I would like to write the code for it (to learn). I only need help in setting up local development environment first and would like to test it with the changes. Would you or someone be able to help in setting up the env ?

**Comment by caelan-io** [comment]
Sounds good. What timezone are you in? If you are in the CNCF Slack please DM me so I can put you in touch with someone to help with the local dev setup. This blog post is also helpful: https://pipekit.io/blog/how-to-run-argo-workflows-codebase-locally

**Comment by sandeepk8s** [comment]
EST -- Sure will check thanks

**Comment by caelan-io** [comment]
@sandeepk8s and I are in touch over Slack. Closing the issue.

**Comment by agilgur5** [comment]
Just noting here for posterity that OP successfully fixed #9651 in #10664 🎉

**Comment by caelan-io** [comment]
So mentoring did work, eh??

**Comment by agilgur5** [comment]
I mean I wasn't opposed to it per #11805  / #11802 (and have been helping several folks over reviews).

But in my analysis (and at this point I have gone through every mentoring issue), a successful outcome was unfortunately in the minority of cases -- most were abandoned and/or never timely responded to 😕 
The majority of those that were successful also already had an issue in mind to work on.
