### ISSUE TITLE
Add documentation about `--qps` and `--burst` settings of controller

### ISSUE THREAD

**Issue by sgutwein** [argoproj/argo-workflows#10566]
# Summary

The [vertically-scaling](https://argoproj.github.io/argo-workflows/scaling/#vertically-scaling) section in the argo-workflows documentation currently only recommends to adapt the `--qps` and `--burst` setting of workflows controller. I couldn't find any (other) documentation about these settings, neither what the default values are.

# Related issues

https://github.com/argoproj/argo-workflows/issues/4634
https://github.com/argoproj/argo-workflows/issues/8576

# Use Cases

Setup the scaling of argo-workflows.

---

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by caelan-io** [comment]
@juliev0 - this become a top voted issue and it's a docs issue. Do you have any notes from your recent work related to this internally that we could use as a first draft for a docs PR to close this? Thanks!

**Comment by juliev0** [comment]
Oh wow, I didn't know this issue existed. I'd be happy to do this in the near future.
