### ISSUE TITLE
A potential risk of argo makes a worker node get the cluster's admin secret

### ISSUE THREAD

**Issue by younaman** [argoproj/argo-workflows#10594]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Hello argo security maintainers:
# Summary:
There are argo-server/workflow-controller that exists on the worker nodes randomly, while the argo-server/workflow-controller's cluster role can delete pods, and the argo-server's cluster role can get secrets. In a scenario where multiple Kubernetes third-party applications are deployed in the same cluster(i.e., antrea/weave-net and argo), if a malicious user controls one worker node, he/she can leverage the ClusterRole of argo's components and antrea-agent/weave-net to get the cluster's admin secret, making a privilege escalation.

# Background:
For the argo, the argo-server and workflow-controller are running on worker nodes randomly, while the ClusterRole of argo-server/workflow-controller can delete pods, and the ClusterRole of argo-server can get secrets. 

For the antrea/weave-net, there exists DaemonSet called antrea-agent/weave-net on EACH node. The ClusterRole of antrea-agent/weave-net can both patch node/status.

# Pre-condition:
In a Kubernetes cluster that runs argo and antrea/weave-net together, if a malicious user controls a worker node that has workflow-controller:
# Attacking strategy:
*  He/she can leverage the antrea-agent/weave-net to path all other nodes/status with "number of pods' capacity:0". And when the argo-server of argo is rescheduled, the argo-server will be rescheduled to the malicious worker node.
* He/She can use the token of workflow-controller to delete argo-server pods, which will be recreated and run on the malicious worker node.
* After the argo-server runs on the malicious worker node, he/she can leverage its token to get all secrets in the whole cluster, get the cluster admin's token and make a cluster-level privilege escalation.
# Mitigation Discussion:
* For argo, the workflow-controller&argo-server can remove the delete verbs of pods, and the argo-server can remove the get verbs of secrets. However, it still needs a careful revisit of the argo's source code.
* For antrea/weave-net, the antrea-agent/weave-net can remove the patch verbs of nodes/status. However, it also needs a careful revisit of the components' source code.

By the way, I know this problem is not carried out by the argo only itself, but in a real deployment scenario, there are multiple third-party apps run in the same cluster, and the gap between different applications can be leveraged to make multiple "uncritical" issue become a real attacking strategy. I have sent this letter to the antrea/weave-net developers to help them make further considerations.

Installation and environment:
We follow the [argo](https://github.com/argoproj/argo-workflows/releases/tag/v3.4.5)/antrea/weave-net official guide to install the argo/antrea/weave-net on a four-node Kubernetes cluster(1.24.2). I'm looking forward to hearing back from you!

Regards,
Nanzi Yang

I have sent a mail to the argo security mailing list(cncf-argo-security@lists.cncf.io), the sender's mail is 952508578nanziyang@gmail.com. However, I have got NO response after five days, so I write this issue here and trying to get a "quick" response, I am sorry if I trigger some "ethical considerations":(
Looking forward to your reply!

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
None workflow
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by JPZ13** [comment]
Hey @younaman - Thanks for reporting. This does seem to be a setup-specific issue though. Is this attack vector still present in the case where only Argo Workflows is present on the cluster without Weave Net? For background, Argo WF will need to be able to delete pods and get secrets for normal functionality of running a workflow to work. If you would prefer to talk through attack vectors offline instead of posting on a public issue, can you send me a DM on the CNCF Slack? My handle is `@J.P.Zivalich`

**Comment by JPZ13** [comment]
Hey @younaman - my apologies for running a bit behind on this. I got tied up with work and some logistics issues. I'll be connecting you with @tico24 on Slack to chat about more about the issue

**Comment by tico24** [comment]
Just to circle back on this, following our conversation on slack:

- You were installing the cluster-wise installation of argo workflows. This naturally has cluster-wide access.
- I recommended you use the namespace install (available under each release in github)
  - https://argoproj.github.io/argo-workflows/managed-namespace/
  - https://argoproj.github.io/argo-workflows/installation/#installation-options
  
Obviously anything else you choose to install into the argo-workflows namespace will also have access to those same namespace-bound elements.
