### ISSUE TITLE
Archive UI broken since v3.4.5

### ISSUE THREAD

**Issue by nakamorichi** [argoproj/argo-workflows#10606]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

<img width="788" alt="Screenshot 2023-02-24 at 12 57 32" src="https://user-images.githubusercontent.com/36138/221740936-132dff2d-384e-4e03-a4c8-6811480877ec.png">

<img width="1013" alt="Screenshot 2023-02-24 at 12 57 55" src="https://user-images.githubusercontent.com/36138/221740950-34b6f5e7-5966-45ef-b35f-017d61f46382.png">

<img width="648" alt="Screenshot 2023-02-24 at 12 58 22" src="https://user-images.githubusercontent.com/36138/221740965-227a2d0b-5608-45ae-bf57-ff11fabb774f.png">

NOTE: v3.4.4 does not have the issue

### Version

v3.4.5, master (786639d4e1bb279894e4f36388f83b721990b261)

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
not related to particular workflow, but Archived Workflows UI component. Apparently regression after v3.4.4.
```

### Logs from the workflow controller

```text
No errors
```

### Logs from in your workflow's wait container

```text
N/A (not related to workflow execution)
```

**Comment by juliev0** [comment]
I think I broke this [here](https://github.com/argoproj/argo-workflows/pull/10399/files#diff-3a5b95b0f54cd08ec8cbfbb5ba11b4f95b2a53c0148716d26e3d5c97c2057b2f) so I will take this.

**Comment by Kitanotori** [comment]
@juliev0 I have fix already, submitting PR in a moment.

**Comment by juliev0** [comment]
> @juliev0 I have fix already, submitting PR in a moment.

Great! Thank you!
