### ISSUE TITLE
how set arguments.artifacts in this condition

### ISSUE THREAD

**Issue by simonChen0317** [argoproj/argo-workflows#10655]
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-conditional-artifacts-
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: flip-coin
            template: flip-coin
          - name: heads
            depends: flip-coin
            template: heads
            when: "{{tasks.flip-coin.outputs.result}} == heads"
          - name: tails
            depends: flip-coin
            template: tails
            when: "{{tasks.flip-coin.outputs.result}} == tails"
          - name: java1
            depends: "heads.Succeeded || tails.Succeeded"
            template: java-example
            arguments:
              artifacts: 
              - name: message
                from: "{{tasks.heads.outputs.artifacts.result}}"
    - name: flip-coin
      script:
        image: 192.168.252.252:5566/argo/python:v1.0
        command: [ python ]
        source: |
          import random
          print("heads" if random.randint(0,1) == 0 else "tails")
    - name: heads
      script:
        image: 192.168.252.252:5566/argo/python:v1.0
        command: [ python ]
        source: |
          with open("/result.txt", "w") as f:
            f.write("it was heads")
      outputs:
        artifacts:
          - name: result
            path: /result.txt
    - name: tails
      script:
        image: 192.168.252.252:5566/argo/python:v1.0
        command: [ python ]
        source: |
          with open("/result.txt", "w") as f:
            f.write("it was tails")
      outputs:
        artifacts:
          - name: result
            path: /result.txt
    - name: java-example
      inputs:
        artifacts:
        - name: my-input-artifact
          path: /app.jar
          s3:
            endpoint: 192.168.252.115:30900
            bucket: argo-bucket
            insecure: true 
            key: test/jiedian1/helloword-1.0-SNAPSHOT.jar
            accessKeySecret:
              name: minio
              key: accesskey
            secretKeySecret:
              name: minio
              key: secretkey
        - name: message
          path: /tmp/message
        - name: message1
          path: /tmp/message
      container:
        image: 192.168.252.252:5566/devops/openjdk:8u322
        command: [sh, -c]
        args: ["ls  && pwd && java -jar app.jar "]

this condition "java-example" need use  heads.output or tails.output . how set arguments.artifacts in "java-example"

**Comment by tico24** [comment]
Mentoring requests are intended for people asking for a mentor to help them contribute to the project.

I think you want either the github discussion, or the [argo-workflows slack channel ](https://argoproj.github.io/community/join-slack)for this type of question.

It would also be much more useful if you could provide formatted code in future. Thanks.
