### ISSUE TITLE
Download for kit_ull_Linux requests `null` release

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-workflows#10697]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

https://github.com/argoproj/argo-workflows/actions/runs/4432615175/jobs/7776893708?pr=10689#step:12:497
```
+ curl --retry 3 -L https://github.com/kitproj/kit/releases/download/null/kit_ull_Linux_x86_64.tar.gz
```

CI shouldn't fail for reasons unrelated to a PR

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
https://github.com/argoproj/argo-workflows/pull/10689
```

### Logs from the workflow controller

```text
...
```

### Logs from in your workflow's wait container

```text
...
```

**Comment by terrytangyuan** [comment]
@alexec Seems related to our workflow that uses Kit's releases.

**Comment by alexec** [comment]
The instals.sh script could be more robust, essentially if fails getting the latest release tag, trying to install "null" version. Unhelpful.
