### ISSUE TITLE
Controller fails to delete workflowtaskresults due to timeout

### ISSUE THREAD

**Issue by acobaugh** [argoproj/argo-workflows#10727]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

With workflows with a large enough number of workflows, or a namespace with a large enough number of pre-existing WorkflowTaskResults, the controller fails to delete them:

```level=warning msg="failed to delete task-results" error="Timeout: request did not complete within requested timeout - context deadline exceeded" namespace=partner-integrations-prod workflow=realpage-moves-ec1683-7s64k```

After this, the results from this workflow are essentially "orphaned" and have to be cleaned up manually using a command like, which takes many minutes (maybe 5m on average).
`k delete -n partner-integrations-prod workflowtaskresult -l workflows.argoproj.io/workflow=realpage-moves-ec1683-7s64k`

I would expect the controller to properly handle this delete, as this eventually becomes a compounding situation with hundreds of thousands of results in a single namespace, that then further prevents other results from being deleted.

Additionally, I might expect a background process that could handle deleting "orphaned" results asynchronously, as anything that interrupts the deletion process could leave results behind as the code appears to only attempt to delete results once after workflows are completed.

### Version

v3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Will provide one if necessary.
```

### Logs from the workflow controller

```text
time="2023-03-22T03:31:51.248Z" level=warning msg="failed to delete task-results" error="Timeout: request did not complete within requested timeout - context deadline exceeded" namespace=partner-integrations-prod workflow=realpage-moves-ec1683-7s64k
```

### Logs from in your workflow's wait container

```text
n/a
```

**Comment by n0tAD0ct0r** [comment]
@terrytangyuan - we run roughly 200 workflows each night for data processing, and about 70 are the `realpage-moves` workflows referenced above. All of our workflows are set up as dag-of-dags; some are as large as 50k steps.

**Comment by a3lk4i** [comment]
+1 facing a similar issue where there are close to a million workflowtaskresult objects generated over time and the controller eventually fails to handle any new workflows

**Comment by terrytangyuan** [comment]
Might be fixed via https://github.com/argoproj/argo-workflows/pull/11048

**Comment by alexec** [comment]
This should be fixed by the issue @terrytangyuan mentioned. Not sure how this didn’t get caught sooner. 🤷
