### ISSUE TITLE
kit not downloading

### ISSUE THREAD

**Issue by tico24** [argoproj/argo-workflows#10768]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I submitted a Documentation enhancement PR #10767

The build repeatedly fails, not on the docs ci but on the main CI.  Specifically it loops over and over again with 

```
 + curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ jq -r .tag_name
+ tag=
+ [  =  ]
+ jq -r .tag_name
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ tag=
+ [  =  ]
+ jq -r .tag_name
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ tag=
+ [  =  ]
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ jq -r .tag_name
+ tag=
+ [  =  ]
+ jq -r .tag_name
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ tag=
+ [  =  ]
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ jq -r .tag_name
+ tag=
+ [  =  ]
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ jq -r .tag_name
+ tag=
+ [  =  ]
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ jq -r .tag_name
+ tag=
+ [  =  ]
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ jq -r .tag_name
+ tag=
+ [  =  ]
+ jq -r .tag_name
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ tag=
+ [  =  ]
+ jq -r .tag_name
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ tag=
+ [  =  ]
+ jq -r .tag_name
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ tag=
+ [  =  ]
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ jq -r .tag_name
+ tag=
+ [  =  ]
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ jq -r .tag_name
+ tag=
+ [  =  ]
+ jq -r .tag_name
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
+ tag=
+ [  =  ]
+ jq -r .tag_name
+ curl -fsL https://api.github.com/repos/kitproj/kit/releases/latest
```

I see little benefit on wasting CPU cycles testing the code that hasn't changed, and this blocks me getting my PR for review.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
n/a
```

**Comment by terrytangyuan** [comment]
It looks passing now

**Comment by tico24** [comment]
@terrytangyuan this is not the case. Still failing for the same reason: https://github.com/argoproj/argo-workflows/actions/runs/4550791846/jobs/8024160087?pr=10767

**Comment by terrytangyuan** [comment]
@alexec Could you take a look?

**Comment by tico24** [comment]
Failing for this PR too: https://github.com/argoproj/argo-workflows/pull/10778

**Comment by alexec** [comment]
If anyone can explain why a simple `curl` command fails, I’d look to know. I’m lost.

**Comment by tico24** [comment]
Maybe drop the `-s` to see why it's failing?

The `-f` won't work if it's getting a 401 for example, and supressing the failure seems to be doing more harm than good anyway?

My guess besides "github actions suck" is its something to do with being inside the github ecosystem is making it require auth or something.

**Comment by alexec** [comment]
Good idea I’ll add `-v` and we can hopefully diagnose the issue.

**Comment by alexec** [comment]
Done.

**Comment by tico24** [comment]
Looks like GitHub rate limits it's own access to the api. 

So the only solutions I see are:

- Don't host kit on GitHub. 

- Don't run ci on GitHub.

**Comment by terrytangyuan** [comment]
Also try authenticating the GitHub API requests?

**Comment by tico24** [comment]
@terrytangyuan do you have access to secrets in this repo? Otherwise @alexec will have to make this change.

**Comment by terrytangyuan** [comment]
Only @alexec and @sarabala1979

**Comment by terrytangyuan** [comment]
@alexec We hit this quite frequently recently. Would you mind taking a look whenever you get a chance?
