### ISSUE TITLE
Display title and description annotations on workflow archive view

### ISSUE THREAD

**Issue by jmeridth** [argoproj/argo-workflows#10771]
# Summary

In workflow archive view, display title and description if annotations exist

Related to #9805 which handles this for the main workflow view

Since we're already allowing it for the main workflow list, we should support it in the archive view also to give a consistent user experience IMO.

# Use Cases

When viewing the archive list, I'd want to see the titles/descriptions just like I would on the main workflow list

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by jmeridth** [comment]
I'm working on this already and will push PR up shortly.

**Comment by jmeridth** [comment]
Will be moot due to #11121

**Comment by terrytangyuan** [comment]
Thank you for working on it!
