### ISSUE TITLE
Fix documentation of `argo stop --dry-run`

### ISSUE THREAD

**Issue by jminuse** [argoproj/argo-workflows#10782]
# Summary

While reading the argo documentation, I ran into the following confusing message:
`--dry-run                      If true, only stop the workflows that would be stopped, without stopping them.`
https://argoproj.github.io/argo-workflows/cli/argo_stop/

Same confusing message here on github: https://github.com/argoproj/argo-workflows/blob/d4a30a556a7093068624dbe16f05b381705dc6e0/cmd/argo/commands/stop.go#L74

I didn't think this merited a bug report, but it would be nice to have a more comprehensible message, such as `If true, only print the workflows that would be stopped, without stopping them.` The equivalent message for `--dry-run` on the `argo delete` page is `Do not delete the workflow, only print what would happen` which also seems like a good description.
https://github.com/argoproj/argo-workflows/blob/d4a30a556a7093068624dbe16f05b381705dc6e0/cmd/argo/commands/delete.go#L90

# Use Cases

More accurate documentation.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by JessieTeng89** [comment]
Hi @jminuse 
Could you please assign this issue to me? Later I will create a PR to fix it.

**Comment by jminuse** [comment]
> Hi @jminuse Could you please assign this issue to me? Later I will create a PR to fix it.

As far as I can see, I don't have permission to assign the issue to you.
