### ISSUE TITLE
Enable the option of Workflows being deleted when Artifact GC fails

### ISSUE THREAD

**Issue by juliev0** [argoproj/argo-workflows#10788]
# Summary

I'm trying to gauge the interest for this. I've heard some people mention in other threads they may want it. 

Currently, if Artifact GC fails (even after exponential backoff), the Artifact GC Pods and the Workflow (which has an ownership reference to it) remain around (there is a finalizer on the Workflow that's not being removed in that case). The idea behind that was:
- if you want your Artifacts deleted first, maybe your Workflow shouldn't be deleted yet
- there is evidence of what went wrong there that you may be able to use, both in a "Condition" in the Workflow Status and the log of the Artifact GC Pod

Is there interest in enabling the finalizer to be removed if Artifact GC fails? (I'm thinking it would make sense to define it on the Workflow level if so, although potentially defined for the Workflow Controller as a whole ?.)

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by tico24** [comment]
If it's something that can be defined at the workflow level, then defining it in the workflowdefaults in the configmap should satisfy your workflow controller-level requirement.
