### ISSUE TITLE
Minor: incomplete log in workflow-controller logs

### ISSUE THREAD

**Issue by tico24** [argoproj/argo-workflows#10790]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

This log line appears in the workflow-controller logs when the configmap changes:

```
level=info msg="Successfully Workflow Controller config map argo/workflow-controller-configmap updated"
```

Presumably this should be `Successfully updates Workflow Conroller..."?

### Version

v3.4.5, latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a

Update the workflow controller map.
```

### Logs from the workflow controller

```text
level=info msg="Successfully Workflow Controller config map argo/workflow-controller-configmap updated" logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
n/a
```

**Comment by Joibel** [comment]
This message was removed in https://github.com/argoproj/argo-workflows/commit/26bad2f6e63d95d9349b33a2f0e19515cd494b0a.

**Comment by tico24** [comment]
Thanks @Joibel
