### ISSUE TITLE
Workflows are not showing up for first-time users

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#10821]
![Image](https://user-images.githubusercontent.com/4269898/229898735-7143dd06-977e-4ae5-bf5a-8eefd5e7e251.png)

**Comment by agilgur5** [comment]
Noticed this as well locally. Clicking "Continue" will show the Workflow List.

@terrytangyuan you didn't provide a description here of what to change this to.

I'm thinking it may make sense to show the whole list and just leave this info box at the top of the page. Then change "Continue" to "Hide"

**Comment by terrytangyuan** [comment]
Sounds good

**Comment by agilgur5** [comment]
This appears to have been added in #8596 based on Alex C's request during review.

That also explains why I only saw this locally recently, as this was added in 3.4.0 and we were using 3.3.8 I believe.

This perhaps could be removed and instead consolidated into an upgrade note in the new version modal for 3.4.0
