### ISSUE TITLE
first letter of base64 encoded Subject should not be capitalised

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#10827]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

![image](https://user-images.githubusercontent.com/33283496/229963989-4fafa222-2214-4b0d-a202-d2097f63d41a.png)

"workflows.argoproj.io/creator" : "Cf...dFL...s...bla"

its also missing == at end of the base64 string

when i base64 decode this value it shows wrong value but if i change first letter to lowercase then base64 decode it gives correct value

not sure if that capitalisation is being done by argo or if in response from dex idp

### Version

3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by sarabala1979** [comment]
@tooptoop4 Argo server is not encoding or decoding the subject. Do you like to triage it?

**Comment by tooptoop4** [comment]
https://github.com/dexidp/dex/issues/1719 mentions Dex is doing it
