### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by afshin-deriv** [argoproj/argo-workflows#10838]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have experience  with Go, Kubernetes and a little Typescript but not React**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #10294**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: (async) (UTC +8 MYT timezone)

**Comment by agilgur5** [comment]
This pre-dates me joining as an active contributor, but nonetheless apologies that this never got a timely response from anyone!

We have now removed the mentoring template as there is not enough bandwidth to support all mentees and we prefer to assist directly on an issue or PR per #11805
