### ISSUE TITLE
cronwf of every hour schedule does not stay paused

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#10889]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

a cronwf with below  Schedule 0 * * * * Every hour  does not stay paused (ie suspend setting) it seems to auto resume itself after a while

cronwfs of other schedules stay paused

### Version

3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by tico24** [comment]
> n/a

Please provide an example workflow so that we have the possibility of helping you.

**Comment by agilgur5** [comment]
Closing as stale since a reproduction was not provided as asked for in previous comments.
