### ISSUE TITLE
Document the difference between "retry" and "resubmit"

### ISSUE THREAD

**Issue by nhavens** [argoproj/argo-workflows#10906]
# Summary

The difference in semantics between clicking "retry" and "resubmit" in the UI for a failed workflow is not self-evident. The closest thing I have found to "official" documentation is #2320, but that issue was closed without any updates to official docs.  Please create or clarify official documentation on the difference between the two options.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by tico24** [comment]
@nhavens would you like to submit a PR for this?

**Comment by aakankshabhende** [comment]
@tico24 @nhavens  I would like to work on this issue. Could you please assign me this?

**Comment by agilgur5** [comment]
This hasn't had any progress, so going to reassign this to myself as I am working on a few related issues

**Comment by agilgur5** [comment]
Added a PR for CLI and CLI docs in #11625. Will address the UI as part of #9541
