### ISSUE TITLE
Task level priorities.

### ISSUE THREAD

**Issue by hden** [argoproj/argo-workflows#1092]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What happened**:
Implement priorities (a.k.a. weights) when dealing with tasks collectively consumes more resource than the underlying system can handle. A typical use case would be to set a (global| dag) parallelism and prioritise tasks that need to be scheduled first. When we have long running tasks mixed with short tasks, this can improve overall execution time.

Apache Airflow captured the concept by `priority_weight` and `weight_rule` variables where each task can accumulate or discard weights from its downstream dependencies. [link](https://airflow.apache.org/code.html#baseoperator)

A key difference from k8s pod priority and preemption is that k8s does not have the dependency information so that weight_rule calculation is not possible.

**Comment by alexec** [comment]
While old, this feels like a valid feature request.

**Comment by alexec** [comment]
@jessesuen @sarabala1979 this is a sufficiently popular feature I think we should implement. Before we do - is this already possible?

**Comment by antoniomo** [comment]
>A key difference from k8s pod priority and preemption is that k8s does not have the dependency information so that weight_rule calculation is not possible.

Another key difference is that even if it was possible, the k8s pod priority and priority classes are preemptive, although there's a non-preemptive beta feature at k8s 1.19, that's too new to be usable for most of us: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#non-preempting-priority-class.
