### ISSUE TITLE
Controller: change the ""Get leases 200"" and "Update leases 200" messages from "info" to "debug"

### ISSUE THREAD

**Issue by vitalyrychkov** [argoproj/argo-workflows#10959]
# Summary

Currently workflow controller writes the "Get leases 200"  and  "Update leases 200" messages every 5 seconds to the job log.
Unless there is an error, users are not concerned with the success "200" messages, but they pollute the log and make it harder to find really important messages. This can be solved by changing the Lease-related non-error messages from "info" to "debug".

# Use Cases

Analyzing job log of the workflow controller

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Already changed in https://github.com/argoproj/argo-workflows/pull/10938

**Comment by vitalyrychkov** [comment]
Hi @terrytangyuan , the messages are still shown as "info" in the v.3.4.8:
```
time="2023-06-26T13:40:42.577Z" level=info msg="Get leases 200"
time="2023-06-26T13:40:42.586Z" level=info msg="Update leases 200"
time="2023-06-26T13:40:47.593Z" level=info msg="Get leases 200"
time="2023-06-26T13:40:47.602Z" level=info msg="Update leases 200"
time="2023-06-26T13:40:52.610Z" level=info msg="Get leases 200"
time="2023-06-26T13:40:52.619Z" level=info msg="Update leases 200"
time="2023-06-26T13:40:54.162Z" level=info msg="List workflows 200"
time="2023-06-26T13:40:57.627Z" level=info msg="Get leases 200"
time="2023-06-26T13:40:57.637Z" level=info msg="Update leases 200"
time="2023-06-26T13:41:02.644Z" level=info msg="Get leases 200"
time="2023-06-26T13:41:02.688Z" level=info msg="Update leases 200"
```
Could it be that there other places to change the level apart from what you have done in April?

**Comment by terrytangyuan** [comment]
It's not part of the release yet

**Comment by terrytangyuan** [comment]
No schedule yet. Depends on whether we have many critical fixes.
