### ISSUE TITLE
there's no nodeID in `msg="Checking daemoned children of "`

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-workflows#10960]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I was watching a coworker review logs and noticed:
`msg="Checking daemoned children of "`

A quick search shows that it happens quite often:
https://github.com/search?q=repo%3Aargoproj%2Fargo-workflows+%22Checking+daemoned+children+of+%22&type=issues

expected results? There should either be a different message for the case when there's no node id, or it shouldn't happen.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
The workflow in #10840 triggered it so it could be used
```

### Logs from the workflow controller

```text
msg="Checking daemoned children of " namespace=argo-workflows
```

### Logs from in your workflow's wait container

```text
...
```

**Comment by jsoref** [comment]
Afaict there's only one place that generates this string:
https://github.com/argoproj/argo-workflows/blob/981fe4b55433781efa43ae5719bfc1e50b457364/workflow/controller/exec_control.go#L102

**Comment by terrytangyuan** [comment]
Would you like to submit a PR to reduce the log?

**Comment by jsoref** [comment]
I'm not quite sure what things should say......

I mean, I could make it:
```go
if (nodeID) {
  woc.log.Infof("Checking daemoned children of %s", nodeID) 
} else {
  woc.log.Infof("Checking daemoned children" )
}
```

If that's desired, I'm happy to make a PR.

**Comment by terrytangyuan** [comment]
The else block does not seem necessary. Also maybe change it to debug level.
