### ISSUE TITLE
Search by name for WorkflowTemplates in UI

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-workflows#11004]
# Summary

Add search bar in UI to search for WorkflowTemplates, ClusterWorkflowTemplates, CronWorkflows by name.

# Use Cases

Searching by name makes sense if there is a large number of templates in a cluster. Some devs in our team submit WorkflowTemplates manually regularly. It's always a pain to scroll through all the templates.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by mozarik** [comment]
Maybe using Elasticsearch can be usefull when also searching for Log. Because i like to find some flow that have same error log

**Comment by terrytangyuan** [comment]
> @terrytangyuan 
> 
> Hello. I would like to be in charge of improving the filtering function by name.
> 
> 

Feel free to submit a PR

**Comment by shmruin** [comment]
As kubernetes api doesn't support pattern searching, so far I also think 'searching whole on every page move' OR 'some caching' is inevitable to make name pattern search UI. 
But the former can make a performance issue, and the latter requires some storage.
