### ISSUE TITLE
Wrong documentation about Emissary executor and image index/cache

### ISSUE THREAD

**Issue by fpaparoni** [argoproj/argo-workflows#11037]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

As stated in [11204](https://github.com/argoproj/argo-workflows/issues/11024) there is a problem on the documentation related to Emissary executor and image management.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n.a.
```

### Logs from the workflow controller

```text
n.a.
```

### Logs from in your workflow's wait container

```text
n.a.
```

**Comment by maxsxu** [comment]
Issue confirmed. We indeed need to clarify the emissary cache strategy.

**Comment by terrytangyuan** [comment]
Fixed in https://github.com/argoproj/argo-workflows/pull/11038
