### ISSUE TITLE
Argo SSO UserInfo Groups field change to configurable param

### ISSUE THREAD

**Issue by Shanjian2033** [argoproj/argo-workflows#11034]
# Summary

We are running Argo Workflow, the SSO authentication works nicely, but we do not see the users's groups. Because the user info got from remote userInfoPath does not have "groups" field, but "memberof" field, and default UserInfo struct can not receive the response. Now we want to make the groups field to configurable param in ConfigMap, so that we can flexible configure userInfo "groups" field according to individual necessary.

Default UserInfo struct: 
![image](https://user-images.githubusercontent.com/131253001/236370517-475d2081-b99f-4d82-8371-c98e261985e2.png)

# Use Cases
We can add "sso.userInfoGroupsField=memberof" in argo-workflows-workflow-controller-configmap, and argo sso will get user info groups info by "memberof" field from remote userInfoPath.
<img width="385" alt="image" src="https://user-images.githubusercontent.com/131253001/236370661-e55baaa4-bcca-4f2d-b6d9-9a8d1725e9df.png">

---
**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
You can already use `customGroupClaimName` to achieve this. See https://argoproj.github.io/argo-workflows/argo-server-sso/#custom-claims
