### ISSUE TITLE
Get rid of staticfiles dependency

### ISSUE THREAD

**Issue by isubasinghe** [argoproj/argo-workflows#11052]
# Summary

We rely on an unmaintained utility to support embedding static files in Argo, seen [here](https://github.com/argoproj/argo-workflows/blob/master/Makefile#L164). 

We should get rid of this ASAP.

**Comment by terrytangyuan** [comment]
Some progress here https://github.com/argoproj/argo-workflows/pull/11707

**Comment by isubasinghe** [comment]
@terrytangyuan thanks for the ping, will review now

**Comment by agilgur5** [comment]
#11654 has more details in its issue, so gonna close this one out in favor of that one.
