### ISSUE TITLE
Argo Python SDK test code error

### ISSUE THREAD

**Issue by franciscuskim** [argoproj/argo-workflows#11084]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Running the api_instance.list_workflows function in the official releases(6.3.0rc2) will throw an AttributeError.

  File "C:\Users\Anaconda3\envs\argo_library\lib\site-packages\argo_workflows\model_utils.py", line 175, in __repr__
    return self.to_str()
  File "C:\User\Anaconda3\envs\argo_library\lib\site-packages\argo_workflows\model_utils.py", line 516, in to_str
    return pprint.pformat(self.to_dict())
  File "C:\Users\Anaconda3\envs\argo_library\lib\site-packages\argo_workflows\model_utils.py", line 512, in to_dict
    return model_to_dict(self, serialize=False)
  File "C:\Users\Anaconda3\envs\argo_library\lib\site-packages\argo_workflows\model_utils.py", line 1661, in model_to_dict
    res.append(model_to_dict(v, serialize=serialize))
  File "C:\Users\Anaconda3\envs\argo_library\lib\site-packages\argo_workflows\model_utils.py", line 1633, in model_to_dict
    if model_instance._composed_schemas:
AttributeError: 'dict' object has no attribute '_composed_schemas'

### Version

argo-workflows==6.3.0rc2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
import os
import unittest
from pprint import pprint

import argo_workflows
from argo_workflows.api import workflow_service_api
from argo_workflows.model.container import Container
from argo_workflows.model.io_argoproj_workflow_v1alpha1_template import IoArgoprojWorkflowV1alpha1Template
from argo_workflows.model.io_argoproj_workflow_v1alpha1_workflow import IoArgoprojWorkflowV1alpha1Workflow
from argo_workflows.model.io_argoproj_workflow_v1alpha1_workflow_create_request import \
    IoArgoprojWorkflowV1alpha1WorkflowCreateRequest
from argo_workflows.model.io_argoproj_workflow_v1alpha1_workflow_spec import \
    IoArgoprojWorkflowV1alpha1WorkflowSpec
from argo_workflows.model.object_meta import ObjectMeta

configuration = argo_workflows.Configuration(host="http://127.0.0.1:2746")
configuration.api_key['BearerToken'] = os.getenv("ARGO_TOKEN")


class ClientTest(unittest.TestCase):

    def test_create_workflow(self):
        manifest = IoArgoprojWorkflowV1alpha1Workflow(
            metadata=ObjectMeta(generate_name='hello-world-'),
            spec=IoArgoprojWorkflowV1alpha1WorkflowSpec(
                entrypoint='whalesay',
                templates=[
                    IoArgoprojWorkflowV1alpha1Template(
                        name='whalesay',
                        container=Container(
                            image='docker/whalesay:latest', command=['cowsay'], args=['hello world']))]))

        api_client = argo_workflows.ApiClient(configuration)
        api_instance = workflow_service_api.WorkflowServiceApi(api_client=api_client)
        api_response = api_instance.create_workflow(
            namespace='argo',
            body=IoArgoprojWorkflowV1alpha1WorkflowCreateRequest(workflow=manifest),
            _check_return_type=False)
        pprint(api_response)
        api_response = api_instance.list_workflows(
            namespace='argo',
            _check_return_type=False
        )
        pprint(api_response)

if __name__ == '__main__':
    unittest.main()
```

### Logs from the workflow controller

```text
python ./sdks/python/tests/client_unittest.py
```

### Logs from in your workflow's wait container

```text
-
```

**Comment by sarabala1979** [comment]
@flaviuvadan Can you please take quick this issue?   I think you have a little more knowledge of python. Can you help us triage it?

**Comment by JPZ13** [comment]
@sarabala1979 - I had a quick chat with @flaviuvadan who mentioned that they are no longer using the Python SDK under the hood with Hera. For next steps, let's poll the community to see if people are still using the generated Python SDK. If they are not, let's deprecate it and push people to Hera given that it is actively maintained and not generated code

**Comment by terrytangyuan** [comment]
> let's deprecate it and push people to Hera given that it is actively maintained and not generated code

Seems like Hera is also using generated code but using a different codegen tool?
https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/models/io/argoproj/workflow/v1alpha1.py

**Comment by terrytangyuan** [comment]
We can add a notice and add a link to Hera

**Comment by tooptoop4** [comment]
have u tried hera/couler?

**Comment by MasonM** [comment]
The Python SDK has been deprecated (https://github.com/argoproj/argo-workflows/pull/13719), so I'm going to go ahead and close this. As @tooptoop4 said, https://github.com/argoproj-labs/hera-workflows and https://github.com/couler-proj/couler are two community-maintained libraries you can try.
