### ISSUE TITLE
Default initialised NodeStatus causes random false failures. 

### ISSUE THREAD

**Issue by isubasinghe** [argoproj/argo-workflows#11102]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When a nodeID is missing from the NodeStatus hashmap, this should cause an error and that condition should be handled. 
Unfortunately thanks to Go's design of maps, a default initialised value of a NodeStatus is returned instead of panicking (which is arguably the sane thing to do). Instead of assuming a value for the NodeStatus, either mark that node as an error or wait till the field has been populated. 

### Version

:latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by isubasinghe** [comment]
!

**Comment by caelan-io** [comment]
@isubasinghe - qq: does this fall under the larger effort in https://github.com/argoproj/argo-workflows/issues/10267 or is this separate?

**Comment by isubasinghe** [comment]
This is a separate issue, one of the container set related issues. 
I need to open more issues for the other container set PRs
