### ISSUE TITLE
Check All checkbox on Workflow DAG filter dropdown

### ISSUE THREAD

**Issue by jmeridth** [argoproj/argo-workflows#11129]
# Summary

A new `Select All` checkbox on Workflow DAG filter dropdown

All unchecked, `Select All` unchecked:

![Screenshot 2023-05-25 at 12 59 37 PM](https://github.com/argoproj/argo-workflows/assets/35014/ee93f589-d0a3-4aaa-a722-86c17606312d)

All checked, `Select All` is checked:

![Screenshot 2023-05-25 at 12 59 44 PM](https://github.com/argoproj/argo-workflows/assets/35014/20114386-52c6-463d-a806-76a1cd61aab9)

One unchecked, `Select All` is unchecked:

![Screenshot 2023-05-25 at 12 59 50 PM](https://github.com/argoproj/argo-workflows/assets/35014/d26dc72c-ce26-4fd8-9d89-0fa6a401fc5f)

# Use Cases

To quickly uncheck or check all filter checkboxes.  Currently you have to do it one by one manually.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by isubasinghe** [comment]
Tested it locally and looks good to me!
