### ISSUE TITLE
Add label selectors to `argo cron list` command

### ISSUE THREAD

**Issue by dbragdonmw** [argoproj/argo-workflows#11158]
# Summary

My team has many different cronworkflows, and we often use the `argo cron list` command to summarize them. Sometimes we wish to only view different groups of related workflows, which we cluster together using kubernetes labels. We really like the functionality of `argo cron list` for the information it provides regarding last runs, next runs, etc, but sometimes we only want to select a subset of cronworkflows based on specific labels. Currently our solution is to pipe the output of `argo cron list` to something like `grep`, but this only allows us to filter the result based on the name of the cronworkflow. 

I would like for there to be a label selector option when using the `argo cron list` command. I imagine it would look something like this:

```bash
argo cron list -l environment=production,client=importantclient -n argo
```

Where these labels are stored in the metadata of the cronworkflow itself:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
   name: my-cronwf
   labels:
      environment: production
      client: importantclient
```

What change needs making?

It appears that there is a `labelSelector` being used in 

https://github.com/argoproj/argo-workflows/blob/58793a8ca54486c0a929ba7197d30b9f3cb3ce17/cmd/argo/commands/cron/list.go#L41

Perhaps this can be extended to appropriate the labels passed by the user before querying the kubernetes cluster for existing cronworkflows?

# Use Cases

When would you use this?

As noted above, it would be quite useful to utilize label selectors when querying for cronworkflows, especially when teams like ours have many, in order to give a glimpse at how certain "groups" of cronworkflows are running in our cluster. As another example, if a team has multiple cron workflows related to a specific use case, such as all cronworkflows configured for a specific business client, it would be useful use label selectors to grab all cronworkflows related to that client, in order to get an easily readable summary, rather than the entire list of cronworkflows in your cluster/namespace. 

Thank you argo team for your time and for an amazing product! 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
This would be a good enhancement. Would you like to contribute to it?

**Comment by dbragdonmw** [comment]
> This would be a good enhancement. Would you like to contribute to it?

I can't promise that I can deliver it in timely fashion but I can take a crack at it!
