### ISSUE TITLE
Custom resources documentation mentions only 3 of the 8 CRDS

### ISSUE THREAD

**Issue by ramanNarasimhan77** [argoproj/argo-workflows#11167]
# Summary

Improve documentation on the Custom resources available in Argo workflows.

Argo workflows installation deploys 

```shell
clusterworkflowtemplates.argoproj.io
cronworkflows.argoproj.io
workflowartifactgctasks.argoproj.io
workfloweventbindings.argoproj.io
workflows.argoproj.io
workflowtaskresults.argoproj.io
workflowtasksets.argoproj.io
workflowtemplates.argoproj.io
```

But the documentation mentions only
![image](https://github.com/argoproj/argo-workflows/assets/52691361/f856ff8a-a460-430e-ad01-799e8a019502)

# Use Cases

This would improve overall understanding of how to use the other Custom resources, and whether they are User facing or used internally by Argo workflows.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
The remaining ones are for internal uses.

**Comment by terrytangyuan** [comment]
We should definitely add some docs. I am working on some related content. Stay tuned.

**Comment by terrytangyuan** [comment]
I have a presentation that mentions some other CRDs in case it's helpful: https://docs.google.com/presentation/d/1IU0a3unnr3tBRi38Zn3EHQZj3z6yvocfG9x9icRu1LE/edit?usp=sharing

I doubt that we need to document them publicly as it relates to implementation detail and likely to change in the future.

**Comment by agilgur5** [comment]
@terrytangyuan just stumbled upon this and glanced through the presentation.
Could you link that in [the Contributing docs](https://argoproj.github.io/argo-workflows/CONTRIBUTING/) if it's ready or otherwise document it? I was thinking of adding READMEs in subfolders to describe some of the layout and different modules and your presentation describes a good bit of that!

**Comment by terrytangyuan** [comment]
Added in https://github.com/argoproj/argo-workflows/pull/11650
