### ISSUE TITLE
the difference between error and failed status?

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-workflows#1117]
**Is this a BUG REPORT or FEATURE REQUEST?**:
REQUEST

what is the difference between error and failed status? 

Thanks.

**Comment by alexec** [comment]
Documenting this would be low hanging fruit. @rbreeze would you be interested in diving into this? Making sure that `NodeStatus` is correctly documented - and more over - `NodeStatus` doubles as `WorkflowStatus` which I think would have different meanings.

**Comment by rbreeze** [comment]
@alexec Just seeing this. Would be happy to look into this and document it.

**Comment by alexec** [comment]
Thank you @rbreeze . I'll assign it to you. I think we just need to comment `workflow_types.go/NodeStatus`
