### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by Transmitt0r** [argoproj/argo-workflows#11174]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have previous experience in Go.**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #11131**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: async

**Comment by terrytangyuan** [comment]
Welcome! Assigned the issue to you and let us know if you have any questions.

**Comment by agilgur5** [comment]
Closing this out as OP had some successful contributions in https://github.com/argoproj/argo-workflows/issues/11131#issuecomment-1576613243 and #11186 🎉 

Great analysis and work on those! Feel free to take on more issues and ask any questions on issues directly
