### ISSUE TITLE
Argo workflow UI compilation error 

### ISSUE THREAD

**Issue by chethan-devopsnow** [argoproj/argo-workflows#11183]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Cloned the latest argo-workflow repo
Followed every steps mentioned here [f](https://github.com/argoproj/argo-workflows/blob/master/docs/running-locally.md)
Opened the code is VSCode and ran open in dev container
make start UI=true 
I was supposed to see a properly working argo ui but found compilation error
<img width="1440" alt="Screenshot 2023-06-06 at 9 20 06 AM" src="https://github.com/argoproj/argo-workflows/assets/91748832/838190e3-b0f0-4f12-99ab-41e4ad7d06e8">

### Version

 v3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
git clone git@github.com:argoproj/argo-workflows.git
set $GOPATH ~/home/go/src/github.com/argoproj/argo-workflows
Use dev container plugin on vscode to open the repo
edit the hosts file and add the following entries 
127.0.0.1 dex
127.0.0.1 minio
127.0.0.1 postgres
127.0.0.1 mysql
127.0.0.1 azurite
Run make start and then stop and run make start UI=true
Access the frontend on localhost:8080
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by chethan-devopsnow** [comment]
Findings:
Error: Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile` so I deleted the yarn.lock file on the local UI folder and ran the make start command to see it with compilation error

**Comment by juliev0** [comment]
@Joibel I think you use Dev Container, right? Any comments here?

**Comment by Joibel** [comment]
I can reproduce this inside a dev container by deleting `ui/yarn.lock`, but the UI builds OK if you don't do that.
I am unable to build the UI outside of a dev container at the moment, so can't compare to see if it does work correctly outside, and I'm not enough of a UI person to diagnose further.

**Comment by Joibel** [comment]
As far as I can tell just deleting yarn.lock and hoping for the best isn't normally successful, and actual curated updating is the way to go. I'm not sure this is a bug as such.

**Comment by agilgur5** [comment]
Agreed with the above; deleting `yarn.lock` means changing build versions and is not a normal procedure.

The specific build error mentioned here is from upgrading `swagger-ui-react`, which I investigated in #11640 and is no longer relevant.

So this is not a bug per both of the above.

> Error: Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`

If you want to intentionally update a dependency, you can temporarily remove the `--frozen-lockfile` setting from the `.yarnrc`. I have done this quite frequently recently as I've been updating the UI build (e.g. #11628) and deps
