### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by gameloser** [argoproj/argo-workflows#11203]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer:  Yes I have read the mentoring guide.

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: I have limited experience in Go and Kubernetes.

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: Not sure which one is still available to be assigned.

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: async (slack, issue comments)

**Comment by terrytangyuan** [comment]
Pleas pick up an issue and let us know if you have any questions.

**Comment by agilgur5** [comment]
Closing as stale as OP never responded.
We have also removed the mentoring template as there is not bandwidth to support all mentees and we prefer to assist directly on an issue or PR per #11805
