### ISSUE TITLE
Custom claim with oidc sso "HTTP ERROR 401"

### ISSUE THREAD

**Issue by nathan-bowman** [argoproj/argo-workflows#11256]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I'm trying to get SSO working with my org's OIDC. 

`kustomization.yaml:`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Branches: https://github.com/argoproj/argo-workflows/branches/
resources:
- github.com/argoproj/argo-workflows//manifests/cluster-install?ref=release-3.4.8
- ./argo-workflows-secrets-store.yaml
- ./argo-workflows-secrets.yaml
- ./argo-workflows-server-sa-readonly.yaml
- ./argo-workflows-clusterrole-readonly.yaml
- ./argo-workflows-clusterrolebinding-readonly.yaml

patches:
  - path: ./argo-workflows-cm.yaml
    target:
      kind: ConfigMap
      name: workflow-controller-configmap
  - path: ./argo-workflows-server-sa-admin.yaml
    target:
      kind: ServiceAccount
      name: argo-server
  - path: ./argo-workflows-server-deployment.yaml
    target:
      kind: Deployment
      name: argo-server
```

`argo-workflows-server-deployment.yaml:`
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  template:
    spec:
      containers:
        - name: argo-server
          args:
            - --loglevel
            - debug
            - --gloglevel
            - "6"
            - server
            - --auth-mode
            - sso
```

`argo-workflows-server-sa-admin.yaml:`
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-server
  annotations:
    workflows.argoproj.io/rbac-rule: "'argo_worflows_admins' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
```

`argo-workflows-cm.yaml:`
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-workflows-cm
  namespace: argo
  labels:
    app.kubernetes.io/name: argo-workflows-cm
    app.kubernetes.io/part-of: argo
data:
  sso: |
    issuer: https://my.org.com/oidc/endpoint/default
    clientId:
      name: argo-workflows-secrets-oidc
      key: clientId
    clientSecret:
      name: argo-workflows-secrets-oidc
      key: clientSecret
    redirectUrl: https://argo-workflows-server.my.org.com/oauth2/callback
    scopes:
      - groups
      - email
      - profile
    rbac:
      enabled: true
    insecureSkipVerify: true
    customGroupClaimName: myCustomClaim
```

Starting up:
```
time="2023-06-22T17:01:22.355Z" level=debug msg="CLI version" version="{untagged 2023-05-30T13:31:45Z 58793a8ca54486c0a929ba7197d30b9f3cb3ce17 untagged clean go1.20.4 gc linux/amd64}"
time="2023-06-22T17:01:22.355Z" level=info msg="not enabling pprof debug endpoints"
I0622 17:01:22.355321       1 merged_client_builder.go:121] Using in-cluster configuration
I0622 17:01:22.355465       1 merged_client_builder.go:163] Using in-cluster namespace
time="2023-06-22T17:01:22.355Z" level=info authModes="[sso]" baseHRef=/ managedNamespace= namespace=argo secure=true ssoNamespace=argo
time="2023-06-22T17:01:22.355Z" level=info msg="Generating Self Signed TLS Certificates for Secure Mode"
I0622 17:01:23.374084       1 round_trippers.go:553] GET https://10.100.0.1:443/api/v1/namespaces/argo/configmaps/workflow-controller-configmap 200 OK in 1017 milliseconds
I0622 17:01:23.383117       1 round_trippers.go:553] GET https://10.100.0.1:443/api/v1/namespaces/argo/secrets/argo-workflows-secrets-oidc 200 OK in 5 milliseconds
I0622 17:01:23.805059       1 round_trippers.go:553] POST https://10.100.0.1:443/api/v1/namespaces/argo/secrets 409 Conflict in 44 milliseconds
I0622 17:01:23.809951       1 round_trippers.go:553] GET https://10.100.0.1:443/api/v1/namespaces/argo/secrets/sso 200 OK in 4 milliseconds
time="2023-06-22T17:01:23.810Z" level=info msg="SSO configuration" clientId="{{argo-workflows-secrets-oidc} clientId <nil>}" insecureSkipVerify=true issuer="https://my.org.com/oidc/endpoint/default" issuerAlias=DISABLED redirectUrl="https://argo-workflows-server.my.org.com/oauth2/callback" scopes="[groups email profile openid]"
I0622 17:01:23.810589       1 reflector.go:219] Starting reflector *v1.ServiceAccount (20m0s) from pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167
I0622 17:01:23.810602       1 reflector.go:255] Listing and watching *v1.ServiceAccount from pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167
I0622 17:01:23.812702       1 round_trippers.go:553] GET https://10.100.0.1:443/api/v1/serviceaccounts?limit=500&resourceVersion=0 200 OK in 1 milliseconds
I0622 17:01:23.817408       1 round_trippers.go:553] GET https://10.100.0.1:443/api/v1/serviceaccounts?allowWatchBookmarks=true&resourceVersion=38164028&timeout=7m29s&timeoutSeconds=449&watch=true 200 OK in 1 milliseconds
I0622 17:01:23.910722       1 shared_informer.go:285] caches populated
time="2023-06-22T17:01:23.910Z" level=info msg="SSO enabled"
I0622 17:01:23.916583       1 round_trippers.go:553] GET https://10.100.0.1:443/api/v1/namespaces/argo/configmaps/workflow-controller-configmap 200 OK in 5 milliseconds
time="2023-06-22T17:01:23.916Z" level=info msg="Starting Argo Server" instanceID= version=untagged
time="2023-06-22T17:01:23.916Z" level=info msg="Creating event controller" asyncDispatch=false operationQueueSize=16 workerCount=4
time="2023-06-22T17:01:23.921Z" level=info msg="GRPC Server Max Message Size, MaxGRPCMessageSize, is set" GRPC_MESSAGE_SIZE=104857600
time="2023-06-22T17:01:23.921Z" level=info msg="Argo Server started successfully on https://localhost:2746" url="https://localhost:2746"
time="2023-06-22T17:01:41.559Z" level=info duration="102.201µs" method=GET path=index.html size=473 status=0
time="2023-06-22T17:01:45.592Z" level=info duration="65.141µs" method=GET path=/oauth2/redirect size=304 status=302
time="2023-06-22T17:02:01.110Z" level=info duration=986.410411ms method=GET path=/oauth2/callback size=0 status=401
time="2023-06-22T17:02:01.559Z" level=info duration="138.079µs" method=GET path=index.html size=473 status=0
```

![image](https://github.com/argoproj/argo-workflows/assets/2992876/8ef0ccab-1f63-40c3-a6a6-5ec78888458c)

I just can't find where the problem lies. I've enabled debug logging, but as you can see, the logs don't actually include debug logs for the authentication process.

I've tried troubleshooting with this Chrome extension: https://chrome.google.com/webstore/detail/saml-ws-federation-and-oa/hkodokikbjolckghdnljbkbhacbhpnkb. I can see that my request works, and my org's OIDC provider responds successfully.

But I'm blind to seeing the claims come down to me from my org's OIDC provider. 

I've read through the docs over and over: https://argoproj.github.io/argo-workflows/argo-server-sso/

How can I troubleshoot this further??

### Version

v3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Does not apply
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

Does not apply
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

Does not apply
```

**Comment by juliev0** [comment]
I see in your ConfigMap you have a pipe character here:
```
data:
  sso: |
```

Could that be the issue? I think the yaml would treat that as a multi-line string, wouldn't it?

I can tell you that we do not have that.

**Comment by nathan-bowman** [comment]
> I see in your ConfigMap you have a pipe character here:
> 
> ```
> data:
>   sso: |
> ```
> 
> Could that be the issue? I think the yaml would treat that as a multi-line string, wouldn't it?
> 
> I can tell you that we do not have that.

I don't think so? I see documentation that uses that here: https://argoproj.github.io/argo-workflows/workflow-controller-configmap.yaml

**Comment by juliev0** [comment]
I see. You're right. And that's actually updating the workflow-controller-configmap, right? (I'm not familiar with how you're using kustomize with the target name specified)

**Comment by nathan-bowman** [comment]
> I see. You're right. And that's actually updating the workflow-controller-configmap, right? (I'm not familiar with how you're using kustomize with the target name specified)

Yes, kustomize is patching it, so basically a merge. I tried removing the `|` and it barfed, so that part is correct at least...

**Comment by juliev0** [comment]
And which button are you clicking in the UI?

**Comment by nathan-bowman** [comment]
I think this PR might help me: https://github.com/argoproj/argo-workflows/pull/11033

I'm not sure when the change will land in a release, though.

**Comment by nathan-bowman** [comment]
> And which button are you clicking in the UI?

After I click LOGIN here:
<img width="208" alt="image" src="https://github.com/argoproj/argo-workflows/assets/2992876/82987246-2bda-4a57-a0c7-b0cf9137b547">

It redirects me to my org's OIDC. I can successfully authenticate, but then the redirect back throw's 401.

**Comment by juliev0** [comment]
I did notice this in your log as well: not sure what that POST request is, but that's logged on start up, right?:
```
POST https://10.100.0.1:443/api/v1/namespaces/argo/secrets 409 Conflict 
```

**Comment by nathan-bowman** [comment]
> I did notice this in your log as well: not sure what that POST request is, but that's logged on start up, right?:
> 
> ```
> POST https://10.100.0.1:443/api/v1/namespaces/argo/secrets 409 Conflict 
> ```

Yes logged on start up. I saw that also, I'm not totally sure if it matters...

**Comment by juliev0** [comment]
That's too bad that there's no debug level logging for that. If you want to take a look at the sso code it's [here](https://github.com/argoproj/argo-workflows/blob/master/server/auth/sso/sso.go).

**Comment by nathan-bowman** [comment]
> That's too bad that there's no debug level logging for that. If you want to take a look at the sso code it's [here](https://github.com/argoproj/argo-workflows/blob/master/server/auth/sso/sso.go).

I think this PR might help: https://github.com/argoproj/argo-workflows/pull/11033. I'm not sure if/when the change will appear in the next release.

There probably needs to be A LOT more debugging in sso.go

golang isn't my strong suit...

**Comment by juliev0** [comment]
Yeah, that's a good call if you're also seeing that same 401 and using customGroupClaimName. I see you're setting `customGroupClaimName`: `myCustomClaim`. Do you know if the `myCustomClaim` field is coming back from the sso endpoint undefined?

**Comment by nathan-bowman** [comment]
> Yeah, that's a good call if you're also seeing that same 401 and using customGroupClaimName. I see you're setting `customGroupClaimName`: `myCustomClaim`. Do you know if the `myCustomClaim` field is coming back from the sso endpoint undefined?

I am pretty blind to what is coming back. I have OIDC working just fine with Argo CD and other services, so I _know_ it works in other instances. I just can't pinpoint what is going wrong with Argo Workflows OIDC...

**Comment by sandeepk8s** [comment]
As it works with ArgoCD. Verify your client secret once again if they match with your ArgoCD one (assuming you have same client secret and app registration)

Try fetching the token generated from your service account (admin one). Use `Bearer <token>` and try to login into the server, check if you are able to

**Comment by nathan-bowman** [comment]
> As it works with ArgoCD. Verify your client secret once again if they match with your ArgoCD one (assuming you have same client secret and app registration)
> 
> Try fetching the token generated from your service account (admin one). Use `Bearer <token>` and try to login into the server, check if you are able to

Using this: `kubectl -n argo exec deployments/argo-server -- argo auth token`

Generates a bearer token and login just fine.

**Comment by sandeepk8s** [comment]
This issue can be closed

**Comment by nathan-bowman** [comment]
Through a lot of troubleshooting, I found that my `clientid` and `clientsecret` secrets were not base64 encoded. This goes against Kubernetes secrets docs, where they state `The values for all keys in the data field have to be base64-encoded strings`.

It still stands that `sso.go` really needs to provide some debug output inside the `argo-server` pod. If that was available, I think I would have solved my issue a lot faster.
