### ISSUE TITLE
[Feature Request] Queuing should support namespace-based queues

### ISSUE THREAD

**Issue by howinator** [argoproj/argo-workflows#1127]
Queueing is included in the Argo roadmap. My request is for that specific feature is that the queues should be namespace-based. My use case is the following:

We are using Argo to deploy environments per-pull request. So, we have multiple workflows which could be operating on the same PR. It would be nice to put each workflow into a queue for that specific pull request so that we could sequence builds/deploys for that pull request.

I can definitely expand more on this if it would be helpful.

**Comment by alexec** [comment]
Closing as queuing is not on roadmap anymore

**Comment by likku123** [comment]
@alexec 
May I know the reason why queuing is not there in argoworkflow roadmap. Is it because of the 3rd party tools  already available to support this feature ? I am looking if I can use Armada queues with argoworkflow jobs.
