### ISSUE TITLE
Token is not valid for running mode, because m in the more then 130 AD groups and generated token is of more bytes.

### ISSUE THREAD

**Issue by atul-bhardwaj-sp** [argoproj/argo-workflows#11277]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I have two Azure  AD tenant group AD1 and AD2, and in AD1 m in 6 groups and in AD 2 m in more then 130 groups.
when i use AD1 then m able to login successfully but with AD2 m not able to login as generated token is of bigger size  like 10 times then AD1  token due to groups as we are passing the Groups struct while encryption.

`raw, err := jwt.Encrypted(s.encrypter).Claims(argoClaims).CompactSerialize()` in sso.go

some people are able to login because they are in less groups and some are not because they are in more groups.

I tried by removing group struct from below code  then atleast m able to login with default service account because it's generating less byte token not 19 20 lines of token.
`argoClaims := &types.Claims{
		Claims: jwt.Claims{
			Issuer:  issuer,
			Subject: c.Subject,
			Expiry:  jwt.NewNumericDate(time.Now().Add(s.expiry)),
		},
		Email:                   c.Email,
		EmailVerified:           c.EmailVerified,
		Name:                    c.Name,
		ServiceAccountName:      c.ServiceAccountName,
		PreferredUsername:       c.PreferredUsername,
		ServiceAccountNamespace: c.ServiceAccountNamespace,
	}`
	

### Version

In all version

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
NA
```

### Logs from the workflow controller

```text
NA
```

### Logs from in your workflow's wait container

```text
NA
```

**Comment by atul-bhardwaj-sp** [comment]
We solved is by changing the group claim settings in AD to this and `Groups assigned to the application (recommended for large enterprise companies to avoid exceeding the limit on the number of groups a token can emit) and uncheked all other settings, As the group increases of a user then the token also increases in siz.
`

**Comment by agilgur5** [comment]
Duplicate of #10153, #9530, etc.

The solution above works, but Argo now has a feature to filter groups to workaround this limitation as well: #11774
