### ISSUE TITLE
Archived workflows cannot be batch deleted

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#11324]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

The changes in https://github.com/argoproj/argo-workflows/pull/11121 currently only supports deleting either/both archived/live workflows individually in workflow details page. However, users cannot delete a batch of them together in the list view and only live (non-archived) workflows can be deleted. 

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Any workflow
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by terrytangyuan** [comment]
Would anyone like to contribute a fix before I get to it?

**Comment by Jack-R-lantern** [comment]
Is it okay if I try it?
