### ISSUE TITLE
[Pre-release] Workflows are shown as not archived after workflow GC

### ISSUE THREAD

**Issue by toyamagu-2021** [argoproj/argo-workflows#11367]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?
 
AhivedWorkflows are marked `Archive: false` in UI after workflows GC.

1. Submit Workflow, then marked as `Archived`.
    ![image](https://github.com/argoproj/argo-workflows/assets/83329336/e2f5b2c8-0f95-4df2-bee6-8aee0305bfa2)
2. After GC, workflows marked as `Pending`
    ![image](https://github.com/argoproj/argo-workflows/assets/83329336/2d70097e-f852-4ab9-9596-c533a5c8806c)
3. Workflow are  marked as not archived in workflow list page
    ![image](https://github.com/argoproj/argo-workflows/assets/83329336/4a3a28c6-13cc-4b3c-8be5-75be0c4e03d4)

Should we change this logic?

https://github.com/argoproj/argo-workflows/blob/97b6fa84441c423c68ecc8a8f1af5e26402d118e/ui/src/models/workflows.ts#L544-L546

### Version

master

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
ANY Workflows
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by terrytangyuan** [comment]
This should probably be fixed in the backend. Those workflows with labels "Pending" are the ones in the database. They didn't become "Archived" yet since they were still being archived. We should change it to "Archived" before saving in the database.

**Comment by toyamagu-2021** [comment]
Thanks. 
Firstly, I think we should change serverside, but I noticed it may intended behavior as commended below.

https://github.com/argoproj/argo-workflows/blob/97b6fa84441c423c68ecc8a8f1af5e26402d118e/server/workflow/workflow_server.go#L143-L144

It is easy to save workflows as `Archived` in the following function, but I worry break related logic....
https://github.com/argoproj/argo-workflows/blob/97b6fa84441c423c68ecc8a8f1af5e26402d118e/persist/sqldb/workflow_archive.go#L85

If you agree with changing the server side, I try to write a PR.

**Comment by terrytangyuan** [comment]
We can simply the logic in the first link you posted to the following: mergedWfs = append(mergedWfs, v[0])

**Comment by alexec** [comment]
You can’t label a workflow as `Archived` until after it is archived because any failure during archiving will result in the workflow never getting archived. Workflows in the archive will always be labeled `Pending`.

**Comment by terrytangyuan** [comment]
@alexec I meant that we don't modify the live workflow YAML at all. We only use modify the YAML that's sent to the database. So in the live workflow, the archival status will still reflect the true status. The archived workflow YAML in the database will be have "Archived" label since it's already saved in the database.

**Comment by toyamagu-2021** [comment]
OK, I think we should distinguish the following status for clarification.

1. Pending: has live manifest and is not archived
2. Archived: has live manifest and is archived
3. Retrieved: retrieved from DB (may or a may not be lived)

We should distinguish 2 from 3 for batch deletion on the frontend or convenience.
What do you think about this?
sample PR: https://github.com/toyamagu-2021/argo-workflows/pull/3

**Comment by terrytangyuan** [comment]
Sounds good to me.
