### ISSUE TITLE
Periodly healthz check may cause serious problems of apiserver/etcd

### ISSUE THREAD

**Issue by cwdsuzhou** [argoproj/argo-workflows#11374]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

lightly do healthz check

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
When we deploy the controller by namespace and we have more one hundreds namespaces. We found apiserver/etcd may meet serious problems due to the health check.
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by terrytangyuan** [comment]
>When we deploy the controller by namespace and we have more one hundreds namespaces. We found apiserver/etcd may meet serious problems due to the health check.

What is the specific issue you are trying to address? What do you mean by "serious problems"?

**Comment by cwdsuzhou** [comment]
> > When we deploy the controller by namespace and we have more one hundreds namespaces. We found apiserver/etcd may meet serious problems due to the health check.
> 
> What is the specific issue you are trying to address? What do you mean by "serious problems"? Using the lister might not surface all potential issues.

workflow is a `CRD`, kueb-apiserer do not have caches, so if we list from apiserver, we should first list from etcd every time. Issue in my environment is frequent healthz check can cause apiserver cpu/menory increase when deployed in many namespace and we have a large number of `CR` exist in the cluster.
And, actually we have used informer where caches exist, why not get from it directly?
IMO, Health check directly relays on apiserver/etcd is too heavy.

**Comment by terrytangyuan** [comment]
The default only lists 200 wfs and you can reduce `HEALTHZ_LIST_LIMIT` if you want. Would that be sufficient?

**Comment by cwdsuzhou** [comment]
> The default only lists 200 wfs and you can reduce `HEALTHZ_LIST_LIMIT` if you want. Would that work for you?

When the result of `List` is 0, we would still iterate all `CRs`(of that namespace) from etcd/apisever. And almost every `List` return 0 result.

Why not get  results from informer?

**Comment by cwdsuzhou** [comment]
> > > When we deploy the controller by namespace and we have more one hundreds namespaces. We found apiserver/etcd may meet serious problems due to the health check.
> > 
> > 
> > What is the specific issue you are trying to address? What do you mean by "serious problems"? Using the lister might not surface all potential issues.
> 
> workflow is a `CRD`, kueb-apiserer do not have separate caches(all crd named unstructured.Unstructure), so if we list from apiserver, we may first list from etcd every time. Issue in my environment is frequent healthz check can cause apiserver cpu/menory increase when deployed in many namespace and we have a large number of `CR` exist in the cluster. And, actually we have used informer where caches exist, why not get from it directly? IMO, Health check directly relays on apiserver/etcd is too heavy.

sorry, here may be misleading, we would list from apiserver due to the resourceVersion is "".

**Comment by juliev0** [comment]
I am actually wondering myself what the issue found with using the informer was, described [here](https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/healthz.go#L33) by @alexec - do you recall, Alex?

**Comment by juliev0** [comment]
We have seen issues of this call timing out (seeing a "context canceled" log message) which I believe causes a 500 error message. The K8S API Server is I believe timing out when hitting etcd. Theory was that it might be related to the size of the Workflows being listed being too big.

As a side note, if using an informer is deemed the wrong way to go, someone suggested using pagination for this query (I guess `ListOptions` has a `Continue` field) so the same Workflows aren't always retrieved every time.

**Comment by cwdsuzhou** [comment]
@terrytangyuan @juliev0 @jonas  @JPZ13  Do you have other suggestions.

As a K8s cluster developer and maintainer of our team, I found the issue, especially when we have many `workflow` CRS.

https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/healthz.go#L34

List from apiserver with resourceVersion not set , we will go to

https://github.com/kubernetes/kubernetes/blob/v1.27.4/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L751

and call c.storage.GetList(ctx, key, opts, listObj) ， this call request from `etcd`, directly and go to

https://github.com/kubernetes/kubernetes/blob/v1.27.4/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L723.

What more, when we can not get enough `iterms`(< `limit`), we will continuously get results from etcd.

**Comment by terrytangyuan** [comment]
I don't have objections to switch to either lister or resource version=0. I don't remember why `avoid problems with informers, but directly querying the API` comment was there and cannot think of any existing issues.

**Comment by terrytangyuan** [comment]
cc @alexec @sarabala1979 @jessesuen who might have more context

**Comment by cwdsuzhou** [comment]
Can anyone give some  feedback about change the health check method

**Comment by juliev0** [comment]
Trying to understand. I'm new to the `resourceVersion` concept. I see that not specifying `resourceVersion`, as we are doing, only returns the latest version of the Workflow, right? If we specified `resourceVersion=0`, then that would return `Any` version - does that include previous versions of the Workflow? What would the Status of those be?

If we did decide to use the Informer cache, one option would be to make it configurable so that users could opt in for that?

**Comment by terrytangyuan** [comment]
FYI I am moving forward with this change https://github.com/argoproj/argo-workflows/pull/11375. We can revert later if we observe any issues.

**Comment by cwdsuzhou** [comment]
> Trying to understand. I'm new to the `resourceVersion` concept. I see that not specifying `resourceVersion`, as we are doing, only returns the latest version of the Workflow, right? If we specified `resourceVersion=0`, then that would return `Any` version - does that include previous versions of the Workflow? What would the Status of those be?
> 
> If we did decide to use the Informer cache, one option would be to make it configurable so that users could opt in for that?

Due to we use limit and labelSelector, `resourceVersion=0` is still not work, and we will fetch from etcd -> apiserver->client.  so IMO best way is health check from informer
