### ISSUE TITLE
[Pre-release] UI crashes when thare are archived workflows which has same name and namespace.

### ISSUE THREAD

**Issue by toyamagu-2021** [argoproj/argo-workflows#11371]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### Behaviour

- UI crashes when there are archived workflows that have the same name and namespace.

### To reproduce

- Create two archived workflow which has the same name.
- Open a workflow detail page.
- ![image](https://github.com/argoproj/argo-workflows/assets/83329336/a53c16e2-fdd9-43e8-8d2d-3b03b7cfa344)
- ![image](https://github.com/argoproj/argo-workflows/assets/83329336/32685976-61b6-45ad-981f-f947246f39d9)

### Cause

- [getWorkflow] pass to backend only ${name} and ${namespace} to backend
  -  https://github.com/argoproj/argo-workflows/blob/22d4e179c3818918c6c4a1fd5ea8d28c816462cc/ui/src/app/shared/services/workflows-service.ts#L69-L70
- Backend returns error when there are one more than workflows in DB
  - https://github.com/argoproj/argo-workflows/blob/22d4e179c3818918c6c4a1fd5ea8d28c816462cc/persist/sqldb/workflow_archive.go#L279

### To resolve

- I'm not sure, but we should pass uid to WorkflowDetails.ts by routing?
  - https://github.com/argoproj/argo-workflows/blob/22d4e179c3818918c6c4a1fd5ea8d28c816462cc/ui/src/app/workflows/components/workflows-container.tsx#L3

### Version

master

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by terrytangyuan** [comment]
The existing workflow with the same name+namespace should be deleted before submitting another one. Perhaps when performing resubmit, we should delete the existing one first?

**Comment by toyamagu-2021** [comment]
I think This issue does not relate to resubmitting itself.
ArchivedWorkflow should be queried by uid, right?
Currently, that is queried by only name and namespace.
Therefore, raises an error when DB has more than workflows which has the same name.

Before v3.4.8, the above situationsworks well because archived workf query by following.
```ts
    get(uid: string, namespace: string) {
        if (namespace === '') {
            return requests.get(`api/v1/archived-workflows/${uid}`).then(res => res.body as models.Workflow);
        } else {
            return requests.get(`api/v1/archived-workflows/${uid}?namespace=${namespace}`).then(res => res.body as models.Workflow);
        }
    },
```

(Forgive me if I terribly taken something wrong)

**Comment by terrytangyuan** [comment]
Support for get archived workflow by name+namespace is added in https://github.com/argoproj/argo-workflows/pull/11055. The assumption of using that is users would avoid submitting duplicate workflows. Perhap in the UI, we can stick with querying archived workflow by UID. Would you like to give that a try?

**Comment by JPZ13** [comment]
@terrytangyuan and @toyamagu-2021 - given #11055 and UID querying, should we close this issue?

**Comment by terrytangyuan** [comment]
This will be fixed in https://github.com/argoproj/argo-workflows/pull/11373
