### ISSUE TITLE
Why can't use a devcontainer-based development environment using codespace?

### ISSUE THREAD

**Issue by Yaminyam** [argoproj/argo-workflows#11423]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

[running-locally](https://github.com/argoproj/argo-workflows/blob/master/docs/running-locally.md)
If you look at the documentation, it says that you can't work in codespace based on devcontainer, but it doesn't explain why.

As a result of running it myself, it seems that the installation fails in the middle due to insufficient capacity.
<img width="698" alt="image" src="https://github.com/argoproj/argo-workflows/assets/31057849/ad5cfe0a-bd2c-4fbf-996e-17144a9ed9c6">

So, as described in the document https://containers.dev/implementors/json_reference/#min-host-reqs, I think it can be solved by setting the storage of hostrequirements as needed.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
.
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
Feel free to send a PR for any changes if you can get Codespaces working!

As far as I know (I haven't tried myself), Codespaces have had various issues running Argo like this one. Had this pop up yesterday [on Slack](https://cloud-native.slack.com/archives/C020XM04CUW/p1690204870404329?thread_ts=1690204870.404329&cid=C020XM04CUW) too.

**Comment by Joibel** [comment]
The `kit pre-up` line (https://github.com/argoproj/argo-workflows/blob/7310e9c41a03cb128bc644cb3b734d89a8b0436e/.devcontainer/pre-build.sh#L33) is the cause. Kit doesn't seem to work properly as part of pre-build. If you comment that line out on a fork and run up the codespace, and then run kit once it is working it seems to work, but that's as far as I got with codespaces.

**Comment by agilgur5** [comment]
Got Codespaces working in #11981!
