### ISSUE TITLE
Need a way to analyze JSON in conditional

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-workflows#1145]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**What happened**:

Workflow step outputs JSON. The next step is conditional. I should be executed based on one of the JSON fields value. The whole json should be passed to the step as input.

Currently user would have to inject one more step just to extract field value using e.g. `jq` so it can be used in `when` expression.

**What you expected to happen**:

It would be useful to support JSON parsing function in `when` expression to avoid having extra step which parses JSON

**Environment**:
- Argo version: v2.2.0

**Comment by alexmt** [comment]
@WeiTang114 , @jmcarp please let us know are interested in this feature as well ( I've noticed you created issues related to argo conditionals supports ). Discussion about implementation in https://github.com/argoproj/argo/pull/1146

**Comment by harry0123** [comment]
Hi @alexmt! I'm an engineer on the ML Platform team at Intuit. We have a use case that could leverage this feature as well. I'll see if I can work on this for my team. Feel free to Intuit Slack me or setup a meeting if you want to discuss the use case!

**Comment by alexec** [comment]
Fixed by expression tag templates in v3.

**Comment by kevinpauli** [comment]
> Fixed by expression tag templates in v3.

Hello, this describes my predicament exactly.  Could we get an example of usage?  Googling led me here, and I can't find any good examples...
