### ISSUE TITLE
Build failures related to Node upgrade

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#11459]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

https://github.com/argoproj/argo-workflows/actions/runs/5676125574/job/15383405669

```
 /home/runner/runners/2.306.0/externals/node16/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

https://github.com/argoproj/argo-workflows/actions/runs/5676115276/job/15382363976

```
error argo-ui@1.0.0: The engine "node" is incompatible with this module. Expected version ">=20". Got "18.17.0"
```

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Not needed
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
The `snyk` workflow needs to use [Node v20](https://github.com/argoproj/argo-workflows/blob/90930ab88b18b7fba3074cdc06059eb6460b50d9/.github/workflows/snyk.yml#L34) similar to the `ci-build` workflow's [`setup-node` step](https://github.com/argoproj/argo-workflows/blob/90930ab88b18b7fba3074cdc06059eb6460b50d9/.github/workflows/ci-build.yaml#L251). I'll write up a PR for that in a jiffy

**Comment by terrytangyuan** [comment]
The first issue is on publish-release workflow

**Comment by agilgur5** [comment]
Oh... the version on the runner _itself_ is failing to run `checkout` (which is in JS) due to the `--openssl-legacy-provider`. The reason it works during `ci-build` is because its [`NODE_OPTIONS`](https://github.com/argoproj/argo-workflows/blob/90930ab88b18b7fba3074cdc06059eb6460b50d9/.github/workflows/ci-build.yaml#L248) is currently missing that flag.

That's gonna take a few more changes to get working
