### ISSUE TITLE
Expose cronWorkflowWorkers as config item.

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#11454]
# Summary
Currently `cronWorkflowWorkers' was hardcoded. In some scenarios, if the user is using cron workflow heavily, they need more workers to process the cronworkflow.

What change needs making?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by tooptoop4** [comment]
does it mean if I have 9 different cronworkflows set to run hourly that one will be missed?

**Comment by agilgur5** [comment]
Added in #11457

**Comment by agilgur5** [comment]
> does it mean if I have 9 different cronworkflows set to run hourly that one will be missed?

I believe it's more that there are 8 threads running by default. So if you have 9 trigger simultaneously, they all get added to the queue and up to 8 can be processed in parallel (also depends on number of cores and other things running etc).
A CronWorkflow primarily [creates Workflows](https://argoproj.github.io/argo-workflows/cron-workflows/#workflowspec-and-workflowmetadata), so I'd imagine all 8 could be processed in less than a second before the 9th then gets processed.

@sarabala1979 feel free to correct me as you obviously know this code better than me!

**Comment by agilgur5** [comment]
(^that is also given a single controller instance without any [sharding](https://argoproj.github.io/argo-workflows/scaling/#sharding))
