### ISSUE TITLE
resources for the artgc pod

### ISSUE THREAD

**Issue by roelarents** [argoproj/argo-workflows#11485]
# Summary

Ability to set resources for the artifact garbage collection (artgc) pod.

Currently, the resources are [hard coded](https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/artifact_gc.go#L450) (to 64Mi mem and 0.1 cpu).

I could imagine being able to provide a `podSpecPatch` for the artifactgc pod with each workflow-template. And falling back to the defaults in [`mainContainer.resources`](https://argoproj.github.io/argo-workflows/workflow-controller-configmap.yaml). But perhaps there are other ways that make more sense.

@juliev0 , do you have any ideas/opinion about this as the author of the artifact gc code?

# Use Cases

We have workflows with many artifacts (magnitude of millions). The artifact garbage collection pods (`*-artgc-*`) for these get OOMKilled. Leaving the workflow in an undeletable (unless forced) state and leaving behind uncollected garbage artifacts.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by juliev0** [comment]
That's a good idea. Perhaps `podSpecPatch` could be added to [ArtifactGC](https://github.com/argoproj/argo-workflows/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go#L1047) or [WorkflowLevelArtifactGC](https://github.com/argoproj/argo-workflows/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go#L1039C6-L1039C6) struct? (the latter may be sufficient and less complicated)
