### ISSUE TITLE
Allow skipping condition in retry strategy

### ISSUE THREAD

**Issue by dvavili** [argoproj/argo-workflows#1150]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
The current retry strategy does not offer control on when the pod is retried. Having a `skipWhen` condition in retryStrategy can help with this and offer more flexibility on when a praticular task/step is retried.

**What you expected to happen**:
When a user specifies a skipWhen clause (which can accept parameters or step/task result from stdout), the step/task should be retried accordingly.
 
**Environment**:
- Argo version: 2.2.0
- Kubernetes version : 1.9.4

**Comment by epa095** [comment]
A very natural usecase for this is to skip depending on the exit code of the step. We have steps which can fail for many reasons, some make sense to retry, some do not.

**Comment by macpoint** [comment]
Hi everyone, any progress on this one?

**Comment by tbasim** [comment]
Hi, this would be a super helpful feature to have. Any updates around this?

**Comment by alexec** [comment]
Would someone like to raise a PR to add this feature?

**Comment by simster7** [comment]
I'll be happy to take this one
