### ISSUE TITLE
The workflow cannot be restored using argo resume after using Argo stop

### ISSUE THREAD

**Issue by felix0080** [argoproj/argo-workflows#11511]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

**The workflow cannot be restored using argo resume after using Argo stop
apply workflow yaml 
argo submit xxx.yaml
when argo get @latest get running**
Name:                dag-diamond-rrfs4
Namespace:           default
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Running
Conditions:
 PodRunning          True
Created:             Thu Aug 03 12:34:02 +0800 (2 minutes ago)
Started:             Thu Aug 03 12:34:02 +0800 (2 minutes ago)
Duration:            2 minutes 38 seconds
Progress:            0/1

STEP                  TEMPLATE  PODNAME                            DURATION  MESSAGE
 ● dag-diamond-rrfs4  diamond
 └─● A                echo      dag-diamond-rrfs4-echo-3327412467  2m

**then stop
argo stop @latest
get status:
argo get @latest **
Name:                dag-diamond-rrfs4
Namespace:           default
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Failed (Terminated)
Message:             Stopped with strategy 'Stop'
Conditions:
 PodRunning          False
 Completed           True
Created:             Thu Aug 03 12:34:02 +0800 (4 minutes ago)
Started:             Thu Aug 03 12:34:02 +0800 (4 minutes ago)
Finished:            Thu Aug 03 12:38:07 +0800 (9 seconds ago)
Duration:            4 minutes 5 seconds
Progress:            0/1

STEP                  TEMPLATE  PODNAME                            DURATION  MESSAGE
 ✖ dag-diamond-rrfs4  diamond
 ├─✖ A                echo      dag-diamond-rrfs4-echo-3327412467  4m        workflow shutdown with strategy:  Stop

**then resume the workflow but now working, The state is still stop
argo resume @latest
get status:
argo get @latest **
Name:                dag-diamond-rrfs4
Namespace:           default
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Failed (Terminated)
Message:             Stopped with strategy 'Stop'
Conditions:
 PodRunning          False
 Completed           True
Created:             Thu Aug 03 12:34:02 +0800 (6 minutes ago)
Started:             Thu Aug 03 12:34:02 +0800 (6 minutes ago)
Finished:            Thu Aug 03 12:38:07 +0800 (2 minutes ago)
Duration:            4 minutes 5 seconds
Progress:            0/1

STEP                  TEMPLATE  PODNAME                            DURATION  MESSAGE
 ✖ dag-diamond-rrfs4  diamond
 ├─✖ A                echo      dag-diamond-rrfs4-echo-3327412467  4m        workflow shutdown with strategy:  Stop

### Version

v3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
# The following workflow executes a diamond workflow
#
#   A
#  / \
# B   C
#  \ /
#   D
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        depends: "A"
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        depends: "A"
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        depends: "B && C"
        template: echo
        arguments:
          parameters: [{name: message, value: D}]

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command:
      - sleep
      - "360"
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
time="2023-08-03T04:34:02.746Z" level=info msg="Processing workflow" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:02.754Z" level=info msg="Updated phase  -> Running" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:02.754Z" level=info msg="DAG node dag-diamond-rrfs4 initialized Running" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:02.755Z" level=info msg="All of node dag-diamond-rrfs4.A dependencies [] completed" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:02.755Z" level=info msg="Pod node dag-diamond-rrfs4-3327412467 initialized Pending" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:02.772Z" level=info msg="Created pod: dag-diamond-rrfs4.A (dag-diamond-rrfs4-echo-3327412467)" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:02.772Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:02.772Z" level=info msg=reconcileAgentPod namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:02.783Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=17678000 workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:12.774Z" level=info msg="Processing workflow" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:12.774Z" level=info msg="Task-result reconciliation" namespace=default numObjs=0 workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:12.774Z" level=info msg="node changed" namespace=default new.message= new.phase=Running new.progress=0/1 nodeID=dag-diamond-rrfs4-3327412467 old.message= old.phase=Pending old.progress=0/1 workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:12.775Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:12.775Z" level=info msg=reconcileAgentPod namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:12.794Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=17678079 workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:22.796Z" level=info msg="Processing workflow" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:22.796Z" level=info msg="Task-result reconciliation" namespace=default numObjs=0 workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:22.797Z" level=info msg="node unchanged" namespace=default nodeID=dag-diamond-rrfs4-3327412467 workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:22.798Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:34:22.798Z" level=info msg=reconcileAgentPod namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.696Z" level=info msg="Processing workflow" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.696Z" level=info msg="Task-result reconciliation" namespace=default numObjs=0 workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.696Z" level=info msg="node unchanged" namespace=default nodeID=dag-diamond-rrfs4-3327412467 workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.696Z" level=info msg="Terminating pod as part of workflow shutdown" namespace=default podName=dag-diamond-rrfs4-echo-3327412467 shutdownStrategy=Stop workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.696Z" level=info msg="node dag-diamond-rrfs4-3327412467 phase Running -> Failed" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.696Z" level=info msg="node dag-diamond-rrfs4-3327412467 message: workflow shutdown with strategy:  Stop" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.696Z" level=info msg="node dag-diamond-rrfs4-3327412467 finished: 2023-08-03 04:38:07.696715387 +0000 UTC" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.697Z" level=info msg="Skipped node dag-diamond-rrfs4-3344190086 initialized Omitted (message: omitted: depends condition not met)" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.697Z" level=info msg="Skipped node dag-diamond-rrfs4-3360967705 initialized Omitted (message: omitted: depends condition not met)" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.698Z" level=info msg="Skipped node dag-diamond-rrfs4-3377745324 initialized Omitted (message: omitted: depends condition not met)" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.698Z" level=info msg="Outbound nodes of dag-diamond-rrfs4 set to [dag-diamond-rrfs4-3377745324]" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.698Z" level=info msg="node dag-diamond-rrfs4 phase Running -> Failed" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.698Z" level=info msg="node dag-diamond-rrfs4 finished: 2023-08-03 04:38:07.69820802 +0000 UTC" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.698Z" level=info msg="Checking daemoned children of dag-diamond-rrfs4" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.698Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.698Z" level=info msg=reconcileAgentPod namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.698Z" level=info msg="Updated phase Running -> Failed" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.698Z" level=info msg="Updated message  -> Stopped with strategy 'Stop'" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.698Z" level=info msg="Marking workflow completed" namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.698Z" level=info msg="Checking daemoned children of " namespace=default workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.702Z" level=info msg="cleaning up pod" action=terminateContainers key=default/dag-diamond-rrfs4-echo-3327412467/terminateContainers
time="2023-08-03T04:38:07.702Z" level=info msg="https://100.123.0.1:443/api/v1/namespaces/default/pods/dag-diamond-rrfs4-echo-3327412467/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=main&stderr=true&stdout=true&tty=false"
time="2023-08-03T04:38:07.703Z" level=info msg="cleaning up pod" action=deletePod key=default/dag-diamond-rrfs4-1340600742-agent/deletePod
time="2023-08-03T04:38:07.712Z" level=info msg="Workflow update successful" namespace=default phase=Failed resourceVersion=17679444 workflow=dag-diamond-rrfs4
time="2023-08-03T04:38:07.807Z" level=info msg="signaled container" container=main error="<nil>" namespace=default pod=dag-diamond-rrfs4-echo-3327412467 stderr= stdout="killing 1 with terminated\n"
time="2023-08-03T04:38:07.807Z" level=info msg="https://100.123.0.1:443/api/v1/namespaces/default/pods/dag-diamond-rrfs4-echo-3327412467/exec?command=%2Fvar%2Frun%2Fargo%2Fargoexec&command=kill&command=15&command=1&container=wait&stderr=true&stdout=true&tty=false"
time="2023-08-03T04:38:07.920Z" level=info msg="signaled container" container=wait error="<nil>" namespace=default pod=dag-diamond-rrfs4-echo-3327412467 stderr= stdout="killing 1 with terminated\n"
time="2023-08-03T04:38:12.716Z" level=info msg="cleaning up pod" action=deletePod key=default/dag-diamond-rrfs4-echo-3327412467/deletePod
time="2023-08-03T04:38:37.921Z" level=info msg="cleaning up pod" action=killContainers key=default/dag-diamond-rrfs4-echo-3327412467/killContainers
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
get nil
```

**Comment by agilgur5** [comment]
Did you mean to use [`argo suspend`](https://argoproj.github.io/argo-workflows/cli/argo_suspend/)?
`argo suspend` pauses the Workflow, whereas `stop` can be seen more like a variant of `terminate` (see also [terminate vs stop](https://github.com/argoproj/argo-workflows/issues/4454#issuecomment-721821469))

**Comment by felix0080** [comment]
@agilgur5 Thank you for your reply. 

I use [argo stop](https://argoproj.github.io/argo-workflows/cli/argo_stop/)
because argo resume --help say 'Resume a workflow that has been stopped or suspended'

[argo resume](https://argoproj.github.io/argo-workflows/cli/argo_resume/) --help
resume zero or more workflows

Usage:
  argo resume WORKFLOW1 WORKFLOW2... [flags]

Examples:
# Resume a workflow that has been stopped or suspended:

  argo resume my-wf

# Resume the latest workflow:
  argo resume @latest

**Comment by felix0080** [comment]
argo suspend can resume . but argo suspend can't stop running node already. for example . a pod running with GPU, It can be a waste of resources because training takes a long time.
 So argo stop is more appropriate, but it cannot resume after verification

**Comment by agilgur5** [comment]
Yea I think that documentation might be incorrect, I need to double check the source code.

`argo suspend` is what you are looking for if you meant to pause a Workflow (it used to be called `argo pause`)

**Comment by agilgur5** [comment]
> argo suspend can resume . but argo suspend can't stop running node already. for example . a pod running with GPU, It can be a waste of resources because training takes a long time. So argo stop is more appropriate, but it cannot resume after verification

Ah I see. In that case `argo stop` followed by [`argo retry`](https://argoproj.github.io/argo-workflows/cli/argo_retry/) might be appropriate

**Comment by felix0080** [comment]
@agilgur5 Thank you very much : )  
[argo retry](https://argoproj.github.io/argo-workflows/cli/argo_retry/) can start the node again. I have added the hook of recycling custom resource (PytorchJob) in OnExit.When I Executing [argo stop](https://argoproj.github.io/argo-workflows/cli/argo_stop/) ,it will  recycling custom resource . but I found The OnExit method will only be executed once  , After [argo retry](https://argoproj.github.io/argo-workflows/cli/argo_retry/) recovery workflow, the OnExit method will not be executed if stop is executed again .
I need to verify again

**Comment by agilgur5** [comment]
> but I found The OnExit method will only be executed once , After [argo retry](https://argoproj.github.io/argo-workflows/cli/argo_retry/) recovery workflow, the OnExit method will not be executed if stop is executed again .

Hmm. I believe it only retries _failed_ nodes, so this might be a behavior edge case. I think there might be some issues around this as well as initialization steps for retries.

That being said, in your case, maybe `argo terminate` followed by `argo retry` will suffice? `terminate` [does not run exit handlers](https://github.com/argoproj/argo-workflows/issues/4454#issuecomment-721821469)

**Comment by felix0080** [comment]
@agilgur5 I need to run exit handlers, because running pod can be a waste of resources, so i use argo stop to run exit template .

**Comment by felix0080** [comment]
Thank you for your help. I will explore it myself. If there is a solution, I will synchronize it here

**Comment by agilgur5** [comment]
> I need to run exit handlers, because running pod can be a waste of resources, so i use argo stop to run exit template .

Yea it depends on your clean-up needs. [`argo resubmit`](https://argoproj.github.io/argo-workflows/cli/argo_resubmit/) might be applicable if the whole Workflow has to be restarted, not just a single step. See also [`retry` vs. `resubmit`](https://github.com/argoproj/argo-workflows/issues/2320#issuecomment-592060487)

**Comment by agilgur5** [comment]
Another option worth noting is [`argo retry --restart-successful --node-field-selector`](https://argoproj.github.io/argo-workflows/cli/argo_retry/#options) (there is one [example](https://argoproj.github.io/argo-workflows/async-pattern/#retrying-failed-jobs) of this). That allows you to retry successful steps, but requires a selector. 
So that may or may not help your use-case. Could potentially run `argo retry` twice, once with the flags and once without

**Comment by agilgur5** [comment]
> Thank you for your help. I will explore it myself. If there is a solution, I will synchronize it here

I submitted a PR (#11624) to fix the erroneous CLI docs, but please add any solutions here even if the issue is closed, as that may help other users with similar use-cases!
