### ISSUE TITLE
workflow-controller-configmap/parallelism setting not working in 3.4.9

### ISSUE THREAD

**Issue by andef** [argoproj/argo-workflows#11541]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I have pasted a small bash script that starts minikube and installs argo with 3.4.9 and configuring parallelism to 5.
Then submit 10 workflows and watches the result. In 3.4.8 this works as expected, but not in 3.4.9 or latest.

### Version

3.4.9

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```bash
#!/usr/bin/env bash

minikube delete
minikube start
kubectl create namespace argo

# Install argo.
#kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.4.8/install.yaml
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.4.9/install.yaml
#kubectl apply -n argo -k https://github.com/argoproj/argo-workflows/manifests/cluster-install

echo "Wait for controller to start..."
kubectl wait --for=condition=available --timeout=60s deployment/workflow-controller -n argo

# Add parallelism: 5 to configmap.
kubectl patch configmap workflow-controller-configmap -n argo -p '{"data":{"parallelism": "5"}}'

# Restart controller.
kubectl -n argo get pod|grep controller|cut -d " " -f1|xargs kubectl -n argo delete pod

echo "Wait for server to start..."
kubectl wait --for=condition=available --timeout=60s deployment/argo-server -n argo

WORKFLOW=$(cat <<EOF
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sleep-
  namespace: argo
spec:
  entrypoint: sleep
  templates:
  - name: sleep
    container:
      image: busybox:latest
      command: [sleep]
      args: ["30"]
EOF
)

for _ in {1..10}
do
   echo "${WORKFLOW}" | argo submit -n argo - 
done

watch argo -n argo list

```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by terrytangyuan** [comment]
Can you try restarting the Argo controller pod after your configmap patch?

**Comment by agilgur5** [comment]
Can also see more info in [the Slack thread](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1691263462006179?thread_ts=1691148709.875429&cid=C01QW9QSSSK)

**Comment by andef** [comment]
@terrytangyuan I am pretty sure the controller has not started when the patch is done. It works fine if you change to 3.4.8. But, I can update the script to restart the controller.

**Comment by terrytangyuan** [comment]
Potentially related commit https://github.com/argoproj/argo-workflows/commit/f7b307222cd4c5efeb9ee10ece1a4cc04f35085a

**Comment by terrytangyuan** [comment]
Full changelog here https://github.com/argoproj/argo-workflows/blob/master/CHANGELOG.md#v349-2023-07-20

**Comment by andef** [comment]
Updated the script to restart controller. Same results.

**Comment by sonbui00** [comment]
> Potentially related commit [f7b3072](https://github.com/argoproj/argo-workflows/commit/f7b307222cd4c5efeb9ee10ece1a4cc04f35085a)

Just test and confirm this. After move `wfc.UpdateConfig(ctx)` Throttler init without config from config map

**Comment by tooptoop4** [comment]
just wanted to mention that since upgrading to v3.4.9 we have seen 150 workflows move from pending to running (at the same time) even though parallelism at wfcontroller is 30 meaning I would never expect more than 30 should be running. @terrytangyuan can there be a 3.4.10 release today for this fix?

**Comment by terrytangyuan** [comment]
Yes we can release 3.4.10

**Comment by terrytangyuan** [comment]
Let's track in https://github.com/argoproj/argo-workflows/issues/11552
