### ISSUE TITLE
CLI: option to delete/list only workflows in 'pending' state

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#11555]
ie  want cli like:
`argo delete --pending`

to delete all workflows that are pending (ie before moved to running state)

**Comment by agilgur5** [comment]
Are you able to use `--field-selector` to achieve this?
Requires more typing, but is consistent [with k8s](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/)

**Comment by tooptoop4** [comment]
@agilgur5 do u know what the syntax would be?

**Comment by terrytangyuan** [comment]
Already linked above but here it is https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/

**Comment by agilgur5** [comment]
To be specific, it would be:
```sh
argo list --field-selector status.phase=Pending
```

**Comment by agilgur5** [comment]
This might also work:

```sh
argo list --status Pending
```

The `--status` flag is [not currently available for `delete`](https://github.com/argoproj/argo-workflows/blob/105031b88d45330a74777c6cd7410742827c3fe7/cmd/argo/commands/delete.go#L82), however.
`--field-selector` is available for both.

**Comment by tooptoop4** [comment]
if I'm not mistaken '--field-selector status.phase=Pending' would only filter **pods** that are pending (which would be from an already **running workflow**), whereas I need filter on **pending workflows** (ie where they have not started any **pod**)

**Comment by agilgur5** [comment]
The `argo` CLI operates on Workflows, not Pods. The Workflow CR has a `status` field (all do all k8s resources)

**Comment by spencercjh** [comment]
Trying to achieve what you want with the field selector mentioned above is not feasible because of the following issue: https://github.com/kubernetes/kubernetes/issues/53459

![image](https://github.com/argoproj/argo-workflows/assets/29922079/2bcd66a7-9b90-4842-8fe5-e2bcbe63f00c)

I think it's a good idea to support the `status` flag on the `argo delete` cmd like `argo list`.

**Comment by agilgur5** [comment]
Nice find! Thought `status.phase` would work as it's available on built-in resources, but [apparently not](https://github.com/kubernetes/kubernetes/issues/53459#issuecomment-434040642)

**Comment by agilgur5** [comment]
There's two PRs out that provide different options for this, but in the meantime, a label selector will work as a workaround as well:

```sh
argo list --selector workflows.argoproj.io/phase=Pending
```

**Comment by agilgur5** [comment]
Since #11577 was merged, latest will now have:

```sh
argo delete --status Pending
```

Thanks to @spencercjh 🙂 

We may end up not moving forward with #11557, will close this out as completed by #11577 if so

**Comment by agilgur5** [comment]
Closing this out as completed by #11577.

Thanks to @spencercjh and @Paritosh-Anand for their implementation work!
