### ISSUE TITLE
Why are all workflowtaskresults objects listed before deleting the workflowtaskresults object

### ISSUE THREAD

**Issue by cccfs** [argoproj/argo-workflows#11607]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When observing the long request in the kube-apiserver log, it was found that all workflowtaskresults objects were listed before the workflowtaskresults was deleted, which took up to 13s. I have 34,000 workflowtaskresults objects in my cluster. Is there any improvement

`
I0818 02:59:15.836968       1 trace.go:205] Trace[604122088]: "List etcd3" key:/argoproj.io/workflowtaskresults/argo-map,resourceVersion:,resourceVersionMatch:,limit:0,continue: (18-Aug-2023 02:59:02.626) (total time: 13210ms):
Trace[604122088]: [13.21006542s] [13.21006542s] END
I0818 02:59:15.844376       1 trace.go:205] Trace[41997032]: "Delete" url:/apis/argoproj.io/v1alpha1/namespaces/argo-map/workflowtaskresults,user-agent:workflow-controller/v0.0.0 (linux/amd64) kubernetes/$Format/argo-workflows/v3.4.9 argo-controller,audit-id:07d3e912-1902-4066-8bbf-2ed1282bc3ae,client:10.3.9.93,accept:application/json, */*,protocol:HTTP/2.0 (18-Aug-2023 02:59:02.626) (total time: 13217ms):
Trace[41997032]: [13.217758822s] [13.217758822s] END
I0818 02:59:16.231448       1 trace.go:205] Trace[1909717067]: "List etcd3" key:/argoproj.io/workflowtaskresults/argo-map,resourceVersion:,resourceVersionMatch:,limit:0,continue: (18-Aug-2023 02:59:02.662) (total time: 13568ms):
Trace[1909717067]: [13.568856088s] [13.568856088s] END
I0818 02:59:16.237932       1 trace.go:205] Trace[1067855512]: "Delete" url:/apis/argoproj.io/v1alpha1/namespaces/argo-map/workflowtaskresults,user-agent:workflow-controller/v0.0.0 (linux/amd64) kubernetes/$Format/argo-workflows/v3.4.9 argo-controller,audit-id:b96fbade-70de-4cde-a4a4-fc3c449f9c58,client:10.3.9.93,accept:application/json, */*,protocol:HTTP/2.0 (18-Aug-2023 02:59:02.662) (total time: 13575ms):
Trace[1067855512]: [13.575625916s] [13.575625916s] END
`

### Version

v3.4.9

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

n/a
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

n/a
```

**Comment by sarabala1979** [comment]
Need to look at the call flow.  I think the code is trying to get the list of taskset based on conditions to evaluate the phase and update the node status. 
here is some reference code:
https://github.com/argoproj/argo-workflows/blob/f5e31f8f36b32883087f783cb1227490bbe36bbd/workflow/controller/taskresult.go#L53C28-L53C46

**Comment by terrytangyuan** [comment]
I wonder why resource version is unset `resourceVersion:` from the logs, which results in the additional 13s. It shouldn't since it uses the indexer.

**Comment by terrytangyuan** [comment]
I have sent https://github.com/argoproj/argo-workflows/pull/11722 that potentially fixes this. Can you try the image tag `dev-task-result-perf` once the image pipelines finish? https://github.com/argoproj/argo-workflows/actions/runs/6041402545/job/16394292264?pr=11722
