### ISSUE TITLE
UI: non-existent Slack Workspace link on help page  Issue

### ISSUE THREAD

**Issue by Leeeuijooo** [argoproj/argo-workflows#11615]
# Summary

Looking into Argo Workflow, in the Help -> Contact section, the following deleted workspace (link: https://argoproj.slack.com) is provided.

https://github.com/argoproj/argo-workflows/blob/e46202a4c00f5c685a02eca9392ddfc1305ac9a0/ui/src/app/help/components/help.tsx#L28C12-L28C12

So How about changing the deprcated (https://argoproj.slack.com) link to https://slack.cncf.io/ ?

# Use Cases

Contact with CNCF(Argo workflows)

**Comment by terrytangyuan** [comment]
Would you like to update it to https://argoproj.github.io/community/join-slack/?

**Comment by Leeeuijooo** [comment]
Yes!! I want to update
Can I post a PR?🤣
