### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by vamshi1188** [argoproj/argo-workflows#11642]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have previous experience in Go  and Kubernetes.**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #10946**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: (async & sync) (IST )

**Comment by caelan-io** [comment]
Hi @vamshi1188 - welcome to the Argo community! Please let me know if you have questions about the issue you're taking on.

**Comment by vamshi1188** [comment]
hlo @caelan-io  am new to this project can you please guide me to setup this project locally

**Comment by caelan-io** [comment]
Sure, here's a step-by-step guide to set up the codebase locally for development: https://pipekit.io/blog/how-to-run-argo-workflows-codebase-locally

Also, we recommend using Nix to get started if you're not on macOS: 
Docs: https://argoproj.github.io/argo-workflows/running-nix/
Original PR for more info: https://github.com/argoproj/argo-workflows/pull/10999
