### ISSUE TITLE
Deprecated - Static files embed library 

### ISSUE THREAD

**Issue by sonbui00** [argoproj/argo-workflows#11654]
# Summary

From https://github.com/argoproj/argo-workflows/pull/11644 , lib for embed static files https://github.com/bouk/staticfiles is deprecated now. It should be replaced with Go standard library

# Use Cases
- maintainable code

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
As an example for anyone looking to take this on, Argo CD has a tiny `embed.go` file in the `ui/` directory with the [`go:embed` directive](https://github.com/argoproj/argo-cd/blob/24c080b5cbea6e3af547868e540caf553920dc73/ui/embed.go#L7)
