### ISSUE TITLE
Variables for top level wftemplate/cronwf name

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#11663]
if i have a cronwf or wftempl i can't seem to find variable for the top level object name of each of those? ie i want mutex but `{{workflow.name}}` becomes the generated name if submitted manually ie `mycron-123` vs `mycron-124` so its not effective as those names are unique. want to have variable of `mycron` dynamically in the mutex (without hardcoding `mycron`)

**Comment by agilgur5** [comment]
Related to #7611

**Comment by tooptoop4** [comment]
i wonder if these work: `{{workflow.labels.workflows.argoproj.io/workflow-template}}` or
`{{workflow.labels.workflows.argoproj.io/cron-workflow}}`
