### ISSUE TITLE
option to exclude cronworkflows or 1 wftemplate from parallelism limits?

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#11679]
I have 2 kinds of workloads:
1. regular scheduled cronworkflows 
2. bursty event driven workflows

I want to ensure event driven workflows can never have more than 24 in parallel AND I want to ensure that cronworkflows are never blocked/delayed/unable to run.

How can I achieve this? If I set global parallelism to 24 then the events may consume all slots leaving the crons unable to run

additionally would like 1 slot reserved to be able to run an administrative intervention type of workflow template at any time

**Comment by agilgur5** [comment]
You should be able to use semaphores to achieve this. See the [Synchronization](https://argoproj.github.io/argo-workflows/synchronization/) docs

**Comment by tooptoop4** [comment]
this is not meeting the goal, if i want to say 'abc' wf is never blocked, i shouldn't have to edit EVERYTHING ELSE EXCEPT 'abc' wf
