### ISSUE TITLE
UI - show history about completed runs in each cron workflow

### ISSUE THREAD

**Issue by juijeong8324** [argoproj/argo-workflows#11706]
# Summary

We can view completed cron-workflows in Workflow view. 
However, I suggest an UI enhancement to view the history about completed runs in each cron workflow.

<br>

**Example**
![image](https://github.com/argoproj/argo-workflows/assets/63052097/39809ea3-5296-4067-a7a2-c8e21c437cc5)
If You click a cron-workflow, 

![image](https://github.com/argoproj/argo-workflows/assets/63052097/888fee60-ee7d-4fc1-a130-584b5bde3674)
You can look history of completed runs about the cron-workflows.

<br>

# Use Cases

It is easy to view completed runs of each cron workflow.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
This would be great enhancement
