### ISSUE TITLE
Knative support for `argo-server` and `workflow-controller`

### ISSUE THREAD

**Issue by maidmaid** [argoproj/argo-workflows#11721]
# Summary

`argo-server` and `workflow-controller` are both installed as k8s deployment. It could be interesting to propose also a [knative](https://knative.dev/docs/) install for the scale-to-0 benefit.

# Use Cases

Knative supports the [scale-to-0](https://knative.dev/docs/serving/autoscaling/scale-to-zero/) but k8s deployments doesn't. When we are not running workflows, `argo-server` and `workflow-controller` could scale-to-0 to save resources and money.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
I don't think that would be officially supported as [the manifests](https://github.com/argoproj/argo-workflows/tree/master/manifests) here are pretty minimal and without external dependencies.

You can certainly deploy them yourself with Knative if you want though. Could also be a feature request to [`argo-helm`](https://github.com/argoproj/argo-helm) (which has different maintainers).
