### ISSUE TITLE
argo workflow with sso could not get logs

### ISSUE THREAD

**Issue by Rosyya** [argoproj/argo-workflows#11795]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

enabled sso and RBAC for argo workflow, when click logs to check logs from workflow, get 403 error, from server logs `grpc.code=PermissionDenied grpc.method=WorkflowLogs grpc.service=workflow.WorkflowService`
I attached read access to the following resources:
  - workflows
  - workflowtasksets
  - workflowtemplates
  - workflowtaskresults
  - workflowtaskresults/finalizers
  - workflowartifactgctasks
  - workflowtasksets/status
  - workflowartifactgctasks/status
  - pods
  - pods/log
what other permission needed?

### Version

v3.4.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
workflow->logs
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by liudongqing** [comment]
Hi, @Rosyya, I have a similar problem, could you please share how you fix it?
