### ISSUE TITLE
Feature Proposal: Concurrency policy for workflows 

### ISSUE THREAD

**Issue by TewWe** [argoproj/argo-workflows#1180]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
We have workflows which alter systems state in a manner, that parallal run of the same workflow template may cause inconsistency. Currently Argo controller is allowed to create any number of jobs using the same template, which is fine for many use cases, but not for all.

**What you expected to happen**:
I would advise having a `concurrencyPolicy` property in the workflow definition, similar to `CronJobs`:
https://cloud.google.com/kubernetes-engine/docs/how-to/cronjobs#specifying_a_concurrency_policy
At least `Allow` and `Forbid` should be used, `Allow` resulting in the current functionality, while `Forbid` eventually failing the second workflow which has the same `generateName`.

Also, if you may have a viable workaround for the situation, that would also be welcome. 

Thank you.

**Comment by chartinmarrel** [comment]
+1

**Comment by alexec** [comment]
Solved by #2550?

**Comment by jessesuen** [comment]
Yes I believe this will be solved by https://github.com/argoproj/argo/issues/2550. Please re-open if you disagree.
