### ISSUE TITLE
TestMergeWithArchivedWorkflows fail because actual data and expected data is dismatch.

### ISSUE THREAD

**Issue by sunyeongchoi** [argoproj/argo-workflows#11815]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

https://github.com/argoproj/argo-workflows/actions/runs/6166062084/job/16734921912

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
no need workflows data
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
@sunyeongchoi just for reference, if you're already making a PR for something (especially when it's small and a follow-up to another PR, especially your own PR (#11761 in this case)), you can totally skip making an issue and go straight to PR 🙂 .
Just may need to document the PR a bit more in the "Motivation" section.

Thanks for the fixes again!

**Comment by sunyeongchoi** [comment]
> @sunyeongchoi just for reference, if you're already making a PR for something (especially when it's small and a follow-up to another PR, especially your own PR (#11761 in this case)), you can totally skip making an issue and go straight to PR 🙂 .
> Just may need to document the PR a bit more in the "Motivation" section.
> 
> Thanks for the fixes again!

Thank you for your explain!!😄
