### ISSUE TITLE
Remove Snyk automated PRs -- dependabot handles this already

### ISSUE THREAD

**Issue by agilgur5** [argoproj/argo-workflows#11844]
# Summary

In the [previous Contributors meeting](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.k1l4irxjo6vc), we discussed several improvements to our dependency automation.

One of these that I proposed was to remove automated Snyk PRs.

###  Pros

- Dependabot already handles [security updates](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates), so we are duplicating tooling and duplicating PRs right now
  - We already have dependabot configured in several ways, including to align with DCO and PR title. Snyk fails both these checks so its automated PRs will currently _never_ pass CI without manual intervention. [Example Snyk PR failing checks](https://github.com/argoproj/argo-workflows/pull/11640/checks)
  - Old [comment](https://github.com/argoproj/argo-workflows/pull/10288#issuecomment-1427076641) from Alex C saying the same thing
- Snyk is also creating dependency update PRs that are not for any known security issues or CVEs, entirely duplicating dependabot
- Snyk is currently using individual tokens for some PRs, which are themselves not ideal for security. [Example Snyk PRs](https://github.com/argoproj/argo-workflows/pull/11640) [using individual tokens](https://github.com/argoproj/argo-workflows/pull/11598)
  - Not sure how to configure these either
  - [Some](https://github.com/argoproj/argo-workflows/pull/10798) do use the `snyk-bot` though, not sure when that occurs.
- Snyk sometimes gives inaccurate or buggy data in its automated PRs. [Example incorrect data](https://github.com/argoproj/argo-workflows/pull/11598#issuecomment-1696444872)
- Snyk does not preserve PR history or lineage well. Dependabot will try to rebase PRs and will say if it opened a new PR that supersedes an old PR. Snyk does not, and so I have [manually commented](https://github.com/argoproj/argo-workflows/pull/10798#issuecomment-1698227094) on several Snyk PRs to notate that they were superseded
  - Closing a PR or issue without a comment is summarily confusing. This is partly due to [how it is being used](https://github.com/argoproj/argo-workflows/pull/11640#issuecomment-1689390893) though
- Many Snyk PRs are summarily closed by maintainers anyway. [Exa](https://github.com/argoproj/argo-workflows/pull/11640#issuecomment-1689390893)[mples](https://github.com/argoproj/argo-workflows/pull/11475#issuecomment-1696314598)
  - This adds even more PR noise and confusion, especially as those are closes without comments.
- We still use Snyk for [scanning in CI](https://github.com/argoproj/argo-workflows/blob/f83ba7927849a39b8c7470205c038249d1e54d43/.github/workflows/snyk.yml) and do not plan to change that. This is just for Snyk's automated PRs.

### Cons

- I suppose Snyk could potentially raise different PRs from dependabot, but that is not necessarily a good thing
- @sarabala1979 mentioned that Snyk was a requirement for CNCF graduation
  - If I had to guess, this was that some form of dependency scanning was a requirement. We're not removing Snyk scanning, just automated PRs. We also already have automated PRs via dependabot, so there is no loss in capability either.
  - Anton (me) to ask @crenshaw-dev if he remembers anything about this requirement.
  
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
I agree we should stop those automated PRs. I believe only @sarabala1979, and I have automated PRs from Snyk. That can be disabled from Snyk from our Snyk account/project settings.

**Comment by agilgur5** [comment]
> * @sarabala1979 mentioned that Snyk was a requirement for CNCF graduation

I couldn't find anything myself about this. The official CNCF [graduation criteria](https://github.com/cncf/toc/blob/03f99c7abe0b058cd50cd7ab654859c1a4bb88d0/process/graduation_criteria.md#graduation-stage) do not mention this. They just mention some requirements about best practices and a published security audit. Nothing specific like using Snyk.

I did recall this [old issue](https://github.com/argoproj/argo-workflows/issues/8644) which mentions "CNCF security engagement", but unfortunately has no real details or links to that (I assume this was from one of the audits? not sure).

> * Anton (me) to ask @crenshaw-dev if he remembers anything about this requirement.

I asked @crenshaw-dev and @alexec about this if they recall anything. Got a response from @crenshaw-dev yesterday (he was OOO for a few weeks) who did not recall such a requirement and thought the same as me re: "some tool for dependency scanning, e.g. Snyk". We also have a very legitimate reason for this (see the whole issue etc) and are not reducing any of our scanning capabilities either, so our security posture does not change.

So I don't think we have any real reasons to _not_ move forward with this, IMO

**Comment by terrytangyuan** [comment]
I have updated my personal Snyk account settings to not automatically create PRs. The last PR created by Snyk bot https://github.com/argoproj/argo-workflows/pull/10798 was a while back so I think we should be fine now.

**Comment by agilgur5** [comment]
@sarabala1979 could you check your personal Snyk account? Once you've changed your settings, feel free to close out this issue.

**Comment by sarabala1979** [comment]
Done. Removed Snyk scaning
