### ISSUE TITLE
It would be helpful to correlate eventid and the triggered workflow in the logs

### ISSUE THREAD

**Issue by srinivin** [argoproj/argo-workflows#11885]
# Summary

Currently after the event source is successful after publishing an event, could notice the relevant log as below.
{"level":"info","ts":1695619583.7231805,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:558","msg":"Succeeded to publish an event","eventSourceName":"test-job-trigger","eventName":"triggerjob","eventSourceType":"sqs","eventID":"**34303263643338372d663534652d343436632d616162362d353431306634633835313063**"}

After the sensor detects and triggers the job, successfully, could see below log

{"level":"info","ts":1695619584.0422075,"logger":"argo-events.sensor","caller":"sensors/listener.go:417","msg":"Successfully processed trigger 'test-pipeline-trigger'","sensorName":"test-pipeline-sensor","triggerName":"test-pipeline-trigger","triggerType":"ArgoWorkflow","triggeredBy":["test-event-dep"],"triggeredByEvents":["**34303263643338372d663534652d343436632d616162362d353431306634633835313063**"]}

However the workflow which is triggered by the sensor, there isnt a way to correlate the workflow and the event id.
Ex:-
Below is one of the workflow logs, there is no way to identify for which event is this workflow associated with.

{"level":"info","msg":"Updated phase  -\u003e Running","namespace":"test-pipeline","time":"2023-09-25T04:30:57.743Z","workflow":"test-pipeline-zlkey-rpckj"}

What change needs making?

Guess logging should correlate the eventid and the triggered workflow

## Use Cases

When would you use this?

End to end tracing for monitoring. This helps to understand the end to end duration, if failures which exact event is impacted and i can trace back to upstream. There are lot more use cases especially in the area of monitoring and visibility

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Would you like to submit a PR to improve this?

**Comment by terrytangyuan** [comment]
master branch

**Comment by srinivin** [comment]
Thank you.

Please review PR :  [2825](https://github.com/argoproj/argo-events/pull/2825)

Please note that this is my first attempt working golang. Kindly help me fix if you see any issues or recommendations.
However i did the changes and tested in local machine and could see the logs as expected.

Ex:-

{"level":"info","ts":1695672049.1509082,"logger":"argo-events.sensor","caller":"argo-workflow/argo-workflow.go:241","msg":"Successfully submitted workflow 'test-pipeline-zlkey-45bjz'","sensorName":"test-pipeline-sensor","triggerName":"test-pipeline-trigger","triggerType":"ArgoWorkflow","triggeredBy":["test-event-dep"],"triggeredByEvents":["36386562343633642d356236392d346463342d383036642d363963663336663665633336"]}
{"level":"info","ts":1695672049.1509833,"logger":"argo-events.sensor","caller":"sensors/listener.go:423","msg":"Successfully processed trigger 'test-pipeline-trigger'","sensorName":"test-pipeline-sensor","triggerName":"test-pipeline-trigger","triggerType":"ArgoWorkflow","triggeredBy":["test-event-dep"],"triggeredByEvents":["36386562343633642d356236392d346463342d383036642d363963663336663665633336"]}

**Comment by terrytangyuan** [comment]
Thanks. Let's wait for maintainers of Argo Events to review. I am closing this issue for now since it's a specific request in Argo Events.

**Comment by srinivin** [comment]
@terrytangyuan  : I see the gated build associated with the PR is failing, could you please assist.
https://github.com/argoproj/argo-events/actions/runs/6304536989/job/17116095586?pr=2825

**Comment by terrytangyuan** [comment]
I'd suggest asking in your PR.
