### ISSUE TITLE
retry not working in argo workflow v3.5.0-rc2

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-workflows#11903]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

hit retry on a failed workflow. got this error

`{"code":6,"message":"Workflow already exists on cluster, use argo retry {name} instead"}: Workflow already exists on cluster, use argo retry {name} instead`

### Version

v3.5.0-rc2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}



❯ kubectl logs -n argo deploy/workflow-controller | grep searchapi-integration-tests
Found 3 pods, using pod/workflow-controller-5f46cd5bd9-bb244
...
time="2023-09-29T16:11:08.475Z" level=info msg="Queueing Failed workflow backend/searchapi-integration-tests-27-g44kp for delete in 51h42m52s due to TTL"
time="2023-09-29T16:11:08.714Z" level=info msg="Queueing Failed workflow backend/searchapi-integration-tests-27-vnxbx for delete in 52h59m5s due to TTL"
```
```


### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

N/A
```

**Comment by terrytangyuan** [comment]
Potentially bug introduced in https://github.com/argoproj/argo-workflows/pull/11409

**Comment by terrytangyuan** [comment]
cc @or-shachar

**Comment by terrytangyuan** [comment]
Never mind. It's unrelated to that PR. @rwong2888 Do you have reproducible steps? Looks like you are retrying an archived workflow but it still exists in the cluster?

**Comment by rwong2888** [comment]
It looks like it is an archived workflow. Are those not retriable anymore @terrytangyuan ?

Not sure how to reproduce... maybe have a workflow with exit 1 step and retry before and after archive time limit?

**Comment by terrytangyuan** [comment]
Are you using `argo archive retry`?

**Comment by terrytangyuan** [comment]
Ok my guess is that you hit the retry button in the UI. The problem is that UI is calling `argo archive retry` instead of `argo retry`.

**Comment by rwong2888** [comment]
Yes, I'm hitting the retry button on the UI

**Comment by rwong2888** [comment]
Maybe with the new unified view, it is not able to distinguish?

**Comment by rwong2888** [comment]
There may be a similar issue with resubmit as well

**Comment by terrytangyuan** [comment]
Yes exactly. We need to improve UI code. cc @toyamagu-2021 

@rwong2888 Can you try resubmit?

**Comment by rwong2888** [comment]
Retry works for me with my admin privileges, but I did see one of our devs have a resubmit issue (with lesser perms)

```
{"code":7,"message":"workflows.argoproj.io is forbidden: User \"system:serviceaccount:backend:backend\" cannot create resource \"workflows\" in API group \"argoproj.io\" in the namespace \"backend\""}: workflows.argoproj.io is forbidden: User "system:serviceaccount:backend:backend" cannot create resource "workflows" in API group "argoproj.io" in the namespace "backend"
```

**Comment by terrytangyuan** [comment]
That seems unrelated.

**Comment by rwong2888** [comment]
Should I open another ticket?

**Comment by terrytangyuan** [comment]
Sure

**Comment by terrytangyuan** [comment]
I'll submit a fix.

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/pull/11906
