### ISSUE TITLE
Multi Tenancy - Group workflow by Team/Project/ 

### ISSUE THREAD

**Issue by mozarik** [argoproj/argo-workflows#11941]
# Summary
This proposal is based on this discussion https://github.com/argoproj/argo-workflows/discussions/6904
We want to group Workflow by something like Team or Project example like what Azkaban (or Flyte) do 

Here the group
![image](https://github.com/argoproj/argo-workflows/assets/39885486/b9500249-e4e8-4b7c-8e1b-b7f025ff9bd5)

and inside that group is full flow and jobs (Workflow and templates in Argo Workflow terms)
![image](https://github.com/argoproj/argo-workflows/assets/39885486/798c569c-8490-4a7a-8081-7db362770102)

or more like what Flyte do 

https://docs.flyte.org/en/v1.0.0/concepts/projects.html#divedeep-projects 
https://docs.flyte.org/projects/cookbook/en/latest/getting_started/package_register.html#register-with-flytectl-register

## Use Cases

This can be usefull when there is a diffrent set workflow type let say `db-ingestion` workflow, `ml-team-a` workflow, `etl-workflow` etc...

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
#6904 mentions that you can filter by label. That would be the conventional way to do so in k8s

**Comment by mozarik** [comment]
> #6904 mentions that you can filter by label. That would be the conventional way to do so in k8s

I'm sorry if my proposal misleading. What I try to said. Can we make the UI more intuitive ? Like imagine if there is hundred of  labels and we as a person that just open the Argo UI. I like to see what's all project we currently have. Or i can just press CTRL+F and search in one page

**Comment by mozarik** [comment]
Hi @agilgur5 maybe we can close this one. I have an idea but i need to scratch the ideas. Its about making the UI pleasant about structured grouping
