### ISSUE TITLE
UI: Show full (long) name of workflow in list

### ISSUE THREAD

**Issue by mozarik** [argoproj/argo-workflows#11949]
# Summary
So let say that you want to search (CNTRL+F) for workflow with generated id like `-zxy123` in `long-long-long-long-long-long-workflow-name-zxy123` 

But cannot pin point which is the worklow that we looking for

## Use Cases

When I go to the UI what i see is `long-long-long-lon...` (i dont know what the minimum character to make it have `...`) when search `-zxy123` it found 1 but i cannot point which is which (imagine 20-30 long-long-long-lon...) 

![image](https://github.com/argoproj/argo-workflows/assets/39885486/d853eef4-57d3-464d-8e58-adaf60d3fc25)

And I also expect if I opened `Show Details` it will show full name of the workflow. But it doesnt
![image](https://github.com/argoproj/argo-workflows/assets/39885486/ee6f478e-a5cd-48d3-96da-46f4f1b64955)

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by mozarik** [comment]
I really like to contribute to Argo Workflow but currently i don't know React. hehe

**Comment by agilgur5** [comment]
> When I go to the UI what i see is `long-long-long-lon...` (i dont know what the minimum character to make it have `...`)

It depends on the width of your window; it's responsive.

There is no simple way to resolve long text issues. Only thing I can think of is to allow users to dynamically resize or remove some of the columns. That requires a pretty sizeable amount of code and library to do though (L).

> And I also expect if I opened `Show Details` it will show full name of the workflow. But it doesnt

That one's a lot easier to modify. Would just be a few lines to add [here](https://github.com/argoproj/argo-workflows/blob/05c6db12adfd581331f5ae5b0234b72c407e7760/ui/src/app/workflows/components/workflow-drawer/workflow-drawer.tsx#L37) in the `WorkflowDrawer` component.

This one's really simple even if you don't know much React if you want to give it a try 🙂 It is hacktoberfest after all!

**Comment by mozarik** [comment]
> This one's really simple even if you don't know much React if you want to give it a try 🙂 It is hacktoberfest after all!

I think its time to me to read https://argoproj.github.io/argo-workflows/CONTRIBUTING/ . let see what i can do about this issue

**Comment by devharsh2k4** [comment]
is it still available?

**Comment by agilgur5** [comment]
If there has been no PR in some time (in this case 9+ months), yes it is available. No need to ask.
