### ISSUE TITLE
BUG UI: pagination warning is not always shown on last page of workflows

### ISSUE THREAD

**Issue by Sebast1aan** [argoproj/argo-workflows#11968]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When limiting the number of records in the workflow page a warning is shown that 'Workflows cannot be globally sorted when paginated'. I get that warning on all pages, except for the last page:
![image](https://github.com/argoproj/argo-workflows/assets/22411346/d529d336-0939-4e1a-b455-ac6bd5793c32)

Only when the number of workflows to show on that page equals the page limit, the warning is shown:
![image](https://github.com/argoproj/argo-workflows/assets/22411346/fa30644d-5542-4a3f-a3a8-bb5a5c2bba93)

I suppose this piece of code in pagination-panel.tsx is causing the issue:
` {props.pagination.limit > 0 && props.pagination.limit <= props.numRecords ? (
                <>
                    <WarningIcon /> Workflows cannot be globally sorted when paginated
                </>
            )`
            
It seems sufficient to have following condition only:
`props.pagination.limit > 0`

If you agree I can open a PR to fix the code.

### Version

v3.4.10

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by terrytangyuan** [comment]
Sounds good. Feel free to submit a PR.

**Comment by agilgur5** [comment]
> It seems sufficient to have following condition only: `props.pagination.limit > 0`
> 
> If you agree I can open a PR to fix the code.

This is not quite correct. Per https://github.com/argoproj/argo-workflows/pull/11973#discussion_r1353099743, if you're on the first page and your pagination limit is 50 while you only have 10 total workflows, then the warning shouldn't show, as you already see all 10 total workflows.

**Comment by agilgur5** [comment]
Fixed the above in #11979
