### ISSUE TITLE
`Missing node type in status node. Cannot get workflow created with Argo <= 2.0` after workflow controller restarted

### ISSUE THREAD

**Issue by jeffreyrubi** [argoproj/argo-workflows#11991]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

What happened:
1. Workflow Controller POD experienced an `OOMKilled` by Kubernetes.
2. The ongoing workflow status node becomes emptied in the `type` field.
3. As a result, `argo watch` reported: 
      `Missing node type in status node. Cannot get workflow created with Argo <= 2.0`....

What to expected:
1. `argo watch` can trace the on-going workflow as expected.

How to repeat the issue:
1. Run a workflow and continue to watch it's status.
2. Kill the workflow controller pod.
3. See the captioned error pops out.

### Version

v3.3.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
A sample example long running workflow will do. Due to IP issue, cannot share the exact corporate workflow here.
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
> (2) The ongoing workflow status node becomes emptied in the "type" field.

The current logic only updates the field and never empties it, so I would recommend trying with a more up-to-date version of Argo.

I've never seen this error before despite seeing a variety of OOMs as well, so this seems very rare as well.

**Comment by tooptoop4** [comment]
https://github.com/argoproj/argo-workflows/blob/v3.5.11/cmd/argo/commands/common/get.go#L336

**Comment by agilgur5** [comment]
With no reproduction, no upvotes, and an old version of Argo, I'm going to close this as not planned at this time
