### ISSUE TITLE
Optimize the content of the list of archived workflows sent to front-end

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#12030]
# Summary

Currently, we retrieve the list of both live workflows and archived workflows where each workflow contains the entire workflow object, including spec, status, etc. Some of this information may not be needed for the workflow list view (they are only required for workflow details page), but they take up a lot of memory, which might overload the UI. 

We should only return the list of workflows with the required information from each workflow object. 

Related https://github.com/argoproj/argo-workflows/issues/12025

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
We do some server-side filtering on [the `fields`](https://github.com/argoproj/argo-workflows/blob/5d5c089167b9b1fd045619b8b06de4dbe798a554/ui/src/app/shared/services/workflows-service.ts#L44) already

> We should only return the list of workflows with the required information from each workflow object.

Since it is the same API used by everything else, this feature is for more server-side filtering that the UI could use?

**Comment by terrytangyuan** [comment]
Correct

**Comment by agilgur5** [comment]
So I didn't think there was much room to improve this (but I haven't looked _too_ closely), but I did discover a possible performance regression with this on the Archived Workflow side: https://github.com/argoproj/argo-workflows/pull/11121#discussion_r1469101802 -- all fields are getting selected there

**Comment by terrytangyuan** [comment]
Not needed anymore due to improvements in https://github.com/argoproj/argo-workflows/pull/13021

**Comment by agilgur5** [comment]
Actually, this was resolved in #12912 per the regression I noted [above](https://github.com/argoproj/argo-workflows/issues/12030#issuecomment-1914010248)
