### ISSUE TITLE
Clearly identify errors in resource manifest validation (e.g. by line number)

### ISSUE THREAD

**Issue by kivio** [argoproj/argo-workflows#1204]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
**What happened**:
When my template is wrong I get not too informal output which is ugly in long workflows
**What you expected to happen**:
Will be good if validation can display me as minimum line number where something is wrong, in best option also what's wrong.
**How to reproduce it (as minimally and precisely as possible)**:
This is example error i have:
```2019/02/01 11:47:41 Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Container.args of type []string.```
And in situation where i have 10 different containers with args is hard to recognize what happen.
Especialy if on first look everything looks good.

**Comment by alexec** [comment]
@kivio could you (or anyone else who thumbs up this ticket) give an example please?

**Comment by alexec** [comment]
OK. So this needs to be fixed in either `lint.go` (which does not "lint" anything :() or 'validate.go'.

**Comment by alexec** [comment]
I've done a cursory investigate into this and it is possible to get the [line number and character position](https://adrianhesketh.com/2017/03/18/getting-line-and-character-positions-from-gos-json-unmarshal-errors/) of JSON errors from `json.Unmarshal`. We use this is many places in the code, sometime when we get it we know which file we have, sometimes not. Sometimes we have the text of the section of the file (YAML with many manifests), but not the starting line number of the section we're examining.

None of this is complex, but there is a lot of it in different places, so I think we need to get specific as to where we want to return line number.

**Comment by kivio** [comment]
I don't have this file - my bad. 

But simplest example ever - even in simple example from main Argo repository. Put some unknown variables into code. 
Like I do - I have put "mountPath" into container definition. Which is invalid of course. But when you get this file for example from the internet and it has 10 "mountPath's" for a different reason - it will be a little hard to recognize which one is bad. 
```bash
argo lint image-builder.yaml
WARN[0000] image-builder.yaml failed to parse: error unmarshaling JSON: while decoding JSON: json: unknown field "mountPath"
FATA[0000] Invalid workflow/workflows found
```

In this example number of line will be very helpful.

**Comment by alexec** [comment]
After further research, this is easy enough for JSON, but not really possible for YAML.

**Comment by lordnynex** [comment]
@alexec Is it atleast possible to include the problematic param name in the error output? With a lot of parameters it is very difficult to debug these type mismatch errors.
