### ISSUE TITLE
New vulnerability detected in Node dependency axios

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#12085]
Master branch failed with:

```
 Issues with no direct upgrade or patch:
  ✗ Cross-site Request Forgery (CSRF) [High Severity][https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459] in axios@1.5.1
    introduced by swagger-ui-react@4.19.1 > swagger-client@3.23.1 > @swagger-api/apidom-reference@0.78.0 > axios@1.5.1
  No upgrade or patch available
```

https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459

There is a documented workaround that we can use or wait for a new axios patch.

**Comment by agilgur5** [comment]
This is pretty deep in `swagger-ui-react`s usage, so I don't think we'd be able to configure the workaround. Will probably have to wait for a patch

**Comment by terrytangyuan** [comment]
The issue in axios seems very active so I would expect a patch soon.

**Comment by terrytangyuan** [comment]
Bumped version in https://github.com/argoproj/argo-workflows/pull/12111

**Comment by agilgur5** [comment]
> The issue in axios

For reference: https://github.com/axios/axios/issues/6006, https://github.com/axios/axios/issues/6022
