### ISSUE TITLE
cronWorkflowResyncPeriod should be configurable similar to cronSyncPeriod

### ISSUE THREAD

**Issue by checkaayush** [argoproj/argo-workflows#12125]
# Summary

Cron Workflow resync period is hardcoded for now. Ideally, it should be configurable, similar to `cronSyncPeriod`.

## Use Cases

If we want to schedule a workflow run within the next 20 minutes, it isn't currently possible. Ideally, configuring this should be possible with an appropriate default, which can stay at 20 minutes.

Happy to raise a PR if that's a reasonable change without repercussions. :)

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
The [resync period](https://github.com/argoproj/argo-workflows/blob/4d062d1f24bf5168ce19687d0bfdd5d60761c193/workflow/cron/controller.go#L58) is an argument for the Informer that I don't believe is currently exposed by _any_ Informer in Argo. 

> If we want to schedule a workflow run within the next 20 minutes, it isn't currently possible

As far as I understand -- there are admittedly few docs on this and is commonly misunderstood; see https://github.com/kubernetes-client/java/issues/725#issuecomment-540352746 and [this thread](https://groups.google.com/g/kubernetes-sig-api-machinery/c/PbSCXdLDno0/m/hEG1YykvDQAJ) -- the resync period of an Informer is a pretty specific internal of Informers. It controls when the Informer should rebuild its entire cache, which is generally not necessary -- it's just "insurance" to make sure the cache stays consistent even when there are misconfigurations or other issues (caches are [notoriously](https://martinfowler.com/bliki/TwoHardThings.html) difficult).

So the "resync period" you're talking about seems unrelated to what you're looking for

**Comment by agilgur5** [comment]
Your issue seems to be more about a configuration with the Workflow queue or the `kube-apiserver`. Scheduling a Workflow run within the next 20 minutes should be possible. In my local dev env I can create a CronWorkflow that runs the next minute.

So I would guess there is something environment-specific going on with your set-up if you can't do that properly. Would need a lot more details to be able to reproduce that and diagnose it.

**Comment by agilgur5** [comment]
Closing as stale and invalid.
