### ISSUE TITLE
workflow label filter is slower on new version

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#12159]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

https://redact/workflows/auth?&label=workflows.argoproj.io%2Fcron-workflow%3Dmywf&limit=50  is slow, over 30 seconds

 but was less than 1 second with v3.4.11 in the archived-workflows or workflows pages

### Version

3.5.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
Sounds like a duplicate of #12025. If I had to guess, it's unrelated to the label filter and is just the list call being very slow per #12025
