### ISSUE TITLE
`argo submit --dry-run -o yaml` to support substituted yaml

### ISSUE THREAD

**Issue by govindKAG** [argoproj/argo-workflows#1217]
I know that argo workflows can be kubectl created directly but if they use things like parameters or loops you have to go through argo cli. I was wondering if there is some way to just render these yaml files with the cli or some other tool so that I can easily kubectl create them later.

**Comment by jessesuen** [comment]
No current way. Here are the flags which mutate the workflow spec before submission

```
      --entrypoint string       override entrypoint
      --generate-name string    override metadata.generateName
      --instanceid string       submit with a specific controller's instance id label
      --name string             override metadata.name
  -p, --parameter stringArray   pass an input parameter
      --priority int32          workflow priority
      --serviceaccount string   run all pods in the workflow using specified serviceaccount
```

I think what you are looking for is probably a `--dry-run` flag combined with `-o yaml`:
```
argo submit workflow.yaml -p foo=bar --dry-run -o yaml
```

I think `--dry-run` for this purpose is a reasonable request.

**Comment by govindKAG** [comment]
@jessesuen this is exactly what I am looking for.
