### ISSUE TITLE
Multi language support 

### ISSUE THREAD

**Issue by dayuange123** [argoproj/argo-workflows#12189]
# Summary

Multi language support 
Chinese support 

## Use Cases

When would you use this?
Next two months
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by LinuxSuRen** [comment]
Sure. I'd be happy on this.

**Comment by agilgur5** [comment]
Yea let's close this one out as duplicate since #10103 has more details. Can continue discussion there.
