### ISSUE TITLE
v3.5.1 Does not support windows 1809

### ISSUE THREAD

**Issue by rush2sk8** [argoproj/argo-workflows#12232]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I cannot pull `quay.io/argoproj/argoexec:v3.5.1-windows` onto a windows 1809 machine. It results with the following error: `a Windows version 10.0.20348-based image is incompatible with a 10.0.19045 host`. I also tried rebuilding the image on the 1809 machine however the build had failed. 

### Version

v3.5.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by rush2sk8** [comment]
I am trying to build the image with `make dist/argoexec` however it gives me the following error:

```bash
$ make dist/argoexec 
GIT_COMMIT=877c5523066e17687856fe3484c9b2d398e986f5 GIT_BRANCH=release-3.5.1 GIT_TAG=v3.5.1 GIT_TREE_STATE=dirty RELEASE_TAG=true DEV_BRANCH=false VERSION=v3.5.1
KUBECTX= DOCKER_DESKTOP=false K3D=false DOCKER_PUSH=false
RUN_MODE=local PROFILE=minimal AUTH_MODE=hybrid SECURE=false STATIC_FILES=true ALWAYS_OFFLOAD_NODE_STATUS=false UPPERIO_DB_DEBUG=0 LOG_LEVEL=debug NAMESPACED=trueCGO_ENABLED=0 go build -v -gcflags '' -ldflags '-X github.com/argoproj/argo-workflows/v3.version=v3.5.1 -X github.com/argoproj/argo-workflows/v3.buildDate=2023-11-20T17:15:27Z -X github.com/argoproj/argo-workflows/v3.gitCommit=877c5523066e17687856fe3484c9b2d398e986f5 -X github.com/argoproj/argo-workflows/v3.gitTreeState=dirty -X github.com/argoproj/argo-workflows/v3.gitTag=v3.5.1 -extldflags -static' -o dist/argoexec ./cmd/argoexec
workflow\executor\os-specific\signal_linux.go:1:1: expected 'package', found signal_darwin
make: *** [Makefile:237: dist/argoexec] Error 1
```

**Comment by jxlwqq** [comment]
argoexec not support windows server 2019 since **v.3.4.9**
