### ISSUE TITLE
I'd like to explore implementing this, has this already been triaged & accepted into the project? I was reading the contribution guide, and I see that features have to be accepted before they are implemented, hence I ask

### ISSUE THREAD

**Issue by Genericreqd** [argoproj/argo-workflows#12277]
I'd like to explore implementing this, has this already been triaged & accepted into the project? I was reading the contribution guide, and I see that features have to be accepted before they are implemented, hence I ask

_Originally posted by @raygervais in https://github.com/argoproj/argo-cd/issues/10283#issuecomment-1267492254_

**Comment by Joibel** [comment]
Really unsure what's going on here, but assuming this is a mistake by a bot, and closing.
