### ISSUE TITLE
Use of Workflow Informer in healthz liveness check causes Panics due to incorrect type

### ISSUE THREAD

**Issue by juliev0** [argoproj/argo-workflows#12326]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

It seems like [this](https://github.com/argoproj/argo-workflows/pull/11375/files) change for healthz to use the Informer may not work. The call to [NewWorkflowLister()](https://github.com/argoproj/argo-workflows/pull/11375/files#diff-f0ed633a056660787546e6e49537494271f83da09d0de7e29764d8e1dc6cf1b3R36) uses `wfc.wfInformer` and that Informer contains types of `*Unstructured`, but the call that's made to `List()` on the following line does a type assertion to type `*Workflow`. That results in this panic any time there's a Workflow that hasn't been reconciled:

```
time="2023-12-04T22:44:00.061Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=canary-1701729840
time="2023-12-04T22:44:00.061Z" level=info msg="Pod node canary-1701729840 initialized Pending" namespace=argo workflow=canary-1701729840
2023/12/04 22:44:00 http: panic serving 10.26.51.134:60098: interface conversion: interface {} is *unstructured.Unstructured, not *v1alpha1.Workflow
goroutine 611 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x212f620, 0xc0048f5500})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/argoproj/argo-workflows/v3/pkg/client/listers/workflow/v1alpha1.workflowNamespaceLister.List.func1({0x24193e0?, 0xc0006b2a70?})
	/go/src/github.com/argoproj/argo-workflows/pkg/client/listers/workflow/v1alpha1/workflow.go:68 +0xbe
k8s.io/client-go/tools/cache.ListAllByNamespace({0x27ccaa0, 0xc00003b320}, {0x0, 0x0}, {0x27c53f0, 0xc0059653c8}, 0xc000757378)
	/go/pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/listers.go:70 +0x4f3
github.com/argoproj/argo-workflows/v3/pkg/client/listers/workflow/v1alpha1.workflowNamespaceLister.List({{0x27ccaa0?, 0xc00003b320?}, {0x0?, 0xc00003b320?}}, {0x27c53f0?, 0xc0059653c8?})
	/go/src/github.com/argoproj/argo-workflows/pkg/client/listers/workflow/v1alpha1/workflow.go:67 +0x6f
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Healthz.func2({0xc00431b5e0?, 0x245e8fe?}, 0xc0005f8000)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/healthz.go:42 +0xc2
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Healthz(0xc0005f8000, {0x27bd4b0, 0xc0006c6460}, 0x558aa9?)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/healthz.go:52 +0xb5
net/http.HandlerFunc.ServeHTTP(0xc0080dac00?, {0x27bd4b0?, 0xc0006c6460?}, 0x40dcca?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x27bd4b0, 0xc0006c6460}, 0xc000e55d00)
	/usr/local/go/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0xc005141500?}, {0x27bd4b0, 0xc0006c6460}, 0xc000e55d00)
	/usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc000e5be60, {0x27beb58, 0xc000380510})
	/usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x5ed
``` 

### Version

3.4.14

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
See panic above
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

n/a
```

**Comment by juliev0** [comment]
Hi @cwdsuzhou. Would you be able to look at this?

**Comment by radusora** [comment]
Seeing the same behaviour in 3.5.2, works fine if reverting to 3.5.1

**Comment by juliev0** [comment]
> Seeing the same behaviour in 3.5.2, works fine if reverting to 3.5.1

Whoa, are you sure? The panic only happens if there happens to be an unreconciled Workflow at the time of the healthz check. I'm curious if it's possible that you just haven't hit that condition when running with 3.5.1. 

[This](https://github.com/argoproj/argo-workflows/blame/v3.5.1/pkg/client/listers/workflow/v1alpha1/workflow.go) is healthz.go for 3.5.1. It contains the same calls to:

```
lister := v1alpha1.NewWorkflowLister(wfc.wfInformer.GetIndexer())
list, err := lister.Workflows(wfc.managedNamespace).List(seletor)
```
and that underlying code hasn't changed in years.

**Comment by radusora** [comment]
> > Seeing the same behaviour in 3.5.2, works fine if reverting to 3.5.1
> 
> Whoa, are you sure? The panic only happens if there happens to be an unreconciled Workflow at the time of the healthz check. I'm curious if it's possible that you just haven't hit that condition when running with 3.5.1.

@juliev0 Maybe it was by chance! Basically I tried submitting a new workflow on a 3.5.2 instance, got the panic issue mentioned above despite multiple attempts to clean/re-submit, restarted controller etc. I ended up on this issue, and decided to revert to 3.5.1. After the revert it worked fine from the first attemp, but I also removed the workflow before the downgrade and re-submitted, so not entirely sure of the root cause.

**Comment by juliev0** [comment]
> > > Seeing the same behaviour in 3.5.2, works fine if reverting to 3.5.1
> > 
> > 
> > Whoa, are you sure? The panic only happens if there happens to be an unreconciled Workflow at the time of the healthz check. I'm curious if it's possible that you just haven't hit that condition when running with 3.5.1.
> 
> @juliev0 Maybe it was by chance! Basically I tried submitting a new workflow on a 3.5.2 instance, got the panic issue mentioned above despite multiple attempts to clean/re-submit, restarted controller etc. I ended up on this issue, and decided to revert to 3.5.1. After the revert it worked fine from the first attemp, but I also removed the workflow before the downgrade and re-submitted, so not entirely sure of the root cause.

Glad to hear that. Thanks for following up.
