### ISSUE TITLE
Support UpdateWorkflow API 

### ISSUE THREAD

**Issue by shuangkun** [argoproj/argo-workflows#12324]
# Summary

Support UpdateWorkflow API  to let user can correct workflow when it submited.

## Use Cases

My workflow is big and complex(2000+ pod). Sometimes, it work failed causing by uncontrollable factors, such as no stock for resource、pod OOM. But I don't want to submit  from the beginning. So I want a UpdateWorkflow API to update workflow template, such as labels、resource limits and correct it. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Beyond this issue**:

**Comment by agilgur5** [comment]
I'm not sure this makes a lot of sense. The `Workflow` resource should generally not be mutated by a user after submission.

Even retries, especially those with new parameters, seem to break fundamental properties of a `Workflow` resource, as I wrote in https://github.com/argoproj/argo-workflows/pull/9141#issuecomment-2077864002. A memoized resubmit matches the intent more correctly.

Same for this proposed "UpdateWorkflow" API; a memoized resubmit would handle this better. If you need to modify some pieces, we could potentially extend memoization to handle these scenarios.

cc @Joibel, who I have a feeling might agree with me on the above in terms of correctness and mutability / immutability
