### ISSUE TITLE
CronWorkflow execution is delayed 20 minutes when its reference WorkflowTemplate is installed after itself

### ISSUE THREAD

**Issue by dongyingbo** [argoproj/argo-workflows#12332]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

1. Install CronWorkflow which is scheduled to execute every 5 minutes
2. Install its reference WorkflowTemplate  

CronWorkflow is executed around 20 minutes later.

It is normal to package WorkflowTemplate and CronWorkflow in same chart to install them via "helm template . | kubectl apply -f -".
And helm template command does not promise order of custom resources.

### Version

v3.4.10

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-workflow-hello-world
spec:
  schedule: "*/5 * * * *"
  workflowSpec:
    arguments:
      parameters:
      - name: message
        value: "hello world"
    workflowTemplateRef:
      name: workflow-template-whalesay-template
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  templates:
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

### Logs from the workflow controller

```text
2023-12-08 17:15:00.012	
{"level":"info","msg":"Running cron-workflow-hello-world","namespace":"csi-iaas-credential-rotator","time":"2023-12-08T09:15:00.003Z","workflow":"cron-workflow-hello-world"}
2023-12-08 17:14:19.058	
{"cronWorkflow":"csi-iaas-credential-rotator/cron-workflow-hello-world","level":"info","msg":"CronWorkflow csi-iaas-credential-rotator/cron-workflow-hello-world added","time":"2023-12-08T09:14:19.058Z"}



2023-12-08 17:14:18.921	
{"cronWorkflow":"csi-iaas-credential-rotator/cron-workflow-hello-world","level":"info","msg":"Processing csi-iaas-credential-rotator/cron-workflow-hello-world","time":"2023-12-08T09:14:18.921Z"}
2023-12-08 16:55:45.816	
{"cronWorkflow":"csi-iaas-credential-rotator/cron-workflow-hello-world","error":"cannot validate Workflow: workflowtemplates.argoproj.io \"workflow-template-whalesay-template\" not found","level":"error","msg":"invalid cron workflow","time":"2023-12-08T08:55:45.816Z"}
2023-12-08 16:55:45.816	
{"conditionType":"SpecError","level":"error","msg":"cannot validate Workflow: workflowtemplates.argoproj.io \"workflow-template-whalesay-template\" not found","namespace":"csi-iaas-credential-rotator","time":"2023-12-08T08:55:45.816Z","workflow":"cron-workflow-hello-world"}
2023-12-08 16:55:45.788	
{"cronWorkflow":"csi-iaas-credential-rotator/cron-workflow-hello-world","level":"info","msg":"Processing csi-iaas-credential-rotator/cron-workflow-hello-world","time":"2023-12-08T08:55:45.788Z"}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by dongyingbo** [comment]
It is worse for Workflow which will fail to execute directly when its WorkflowTemplate is installed after it.

**Comment by Joibel** [comment]
An approach of just retrying invalid CronWorkflows by putting them immediately on the back of the queue doesn't seem particularly good for most invalid CronWorkflows, which shouldn't be retried at all. Humm, a tricky one.

**Comment by dongyingbo** [comment]
How about we add it back just for WorkflowTemplate not found like changing validate.go/ValidateCronWorkflow,
```
	err := ValidateWorkflow(wftmplGetter, cwftmplGetter, wf, ValidateOpts{})
	if err != nil {
		if k8sErrors.IsNotFound(err) {
			return err
		}
		return errors.Errorf(errors.CodeBadRequest, "cannot validate Workflow: %s", err)
	}
```
And changing controller.go/processNextCronItem,
```
	err = cronWorkflowOperationCtx.validateCronWorkflow()
	if err != nil {
		logCtx.WithError(err).Error("invalid cron workflow")
		if k8sErrors.IsNotFound(err) {
			cc.cronWfQueue.AddAfter(key, time.Second*30)
		}
		return true
	}
```

**Comment by dongyingbo** [comment]
It is worse when Workflow and WorkflowTemplate are package together.
See #10344

**Comment by Joibel** [comment]
I don't think the controller should do this.

If the template never appears then the workflow/cronworkflow will just keep the controller busy for no reason. As noted in #10344 the deployment mechanisms that can be used to deploy templates and workflows *can* order the deployments to fix this issue, and that is the correct fix.

**Comment by dongyingbo** [comment]
Hi @Joibel 
You are right. I just tried that after adding 
```
  annotations:
    "helm.sh/hook": post-install
```
to Workflow and CronWorkflow CRs they are rendered and installed after WorkflowTemplate as expected.
So I am closing it.

NOTE: it works for helm3 only but not helm2.
