### ISSUE TITLE
Expand Suspend to help Interact with other clusters

### ISSUE THREAD

**Issue by shuangkun** [argoproj/argo-workflows#12388]
# Summary

The workflow becomes more and more complex. In some scenarios the workflow need Interact with other clusters (such as SGE clusters、HSF clusters) to get intermediate data，but users don't want create a pod to wait in vain. So expand  "Argo Suspend" to help Interact with other clusters may be a idea. (The user don’t want to change the previous workflow template too much.)

We can expand  "Argo Suspend" to let user set some trigger to start next step of workflow. Maybe time、a flag file、a message etc.

## Use Cases

Someone has need Interact with other clusters (such as SGE clusters、HSF clusters) , want to let pod not wait in vaion and reduce costs.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Beyond this issue**:

**Comment by agilgur5** [comment]
> We can expand "Argo Suspend" to let user set some trigger to start next step of workflow. Maybe time、a flag file、a message etc

This is already possible -- the [Asynchronous Job Pattern](https://argoproj.github.io/argo-workflows/async-pattern/) is how this can be implemented. You can `resume` a Workflow via the CLI, the API, or the UI instead of polling.

**Comment by shuangkun** [comment]
> > We can expand "Argo Suspend" to let user set some trigger to start next step of workflow. Maybe time、a flag file、a message etc
> 
> This is already possible -- the [Asynchronous Job Pattern](https://argoproj.github.io/argo-workflows/async-pattern/) describes how to implement this. You can `resume` a Workflow via the CLI, the API, or the UI instead of polling.

Thanks. I will so some research about "Asynchronous Job Pattern".
