### ISSUE TITLE
quick start fails out of the box

### ISSUE THREAD

**Issue by cardoe** [argoproj/argo-workflows#12391]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Able to run the quick start CLI with success.

My environment was a macOS M2 machine running Docker Desktop with kind. The steps are straight from https://argoproj.github.io/argo-workflows/quick-start/

```bash
kind create cluster
# cluster created with 1.27.3
kubectl create namespace argo
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.5.2/install.yaml
kubectl patch deployment \
  argo-server \
  --namespace argo \
  --type='json' \
  -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/args", "value": [
  "server",
  "--auth-mode=server"
]}]'
```

At this point I ran:

```bash
argo submit -n argo --watch https://raw.githubusercontent.com/argoproj/argo-workflows/main/examples/hello-world.yaml
```

And the output was:

```
Name:                hello-world-g2csp
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Error
Message:             Error (exit code 1): pods "hello-world-g2csp" is forbidden: User "system:serviceaccount:argo:default" cannot patch resource "pods" in API group "" in the namespace "argo"
Conditions:
 PodRunning          False
 Completed           True
Created:             Wed Dec 20 10:25:35 -0600 (9 minutes ago)
Started:             Wed Dec 20 10:25:35 -0600 (9 minutes ago)
Finished:            Wed Dec 20 10:26:05 -0600 (9 minutes ago)
Duration:            30 seconds
Progress:            0/1
ResourcesDuration:   13s*(1 cpu),13s*(100Mi memory)

STEP                  TEMPLATE  PODNAME            DURATION  MESSAGE
 ⚠ hello-world-g2csp  whalesay  hello-world-g2csp  21s       Error (exit code 1): pods "hello-world-g2csp" is forbidden: User "system:serviceaccount:argo:default" cannot patch resource "pods" in API group "" in the namespace "argo"
```

### Version

v3.5.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

### Logs from the workflow controller

```text
time="2023-12-20T16:25:35.731Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:25:35.736Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=hello-world-g2csp
time="2023-12-20T16:25:35.736Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:25:35.736Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:25:35.736Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:25:35.736Z" level=info msg="Pod node hello-world-g2csp initialized Pending" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:25:35.745Z" level=info msg="Created pod: hello-world-g2csp (hello-world-g2csp)" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:25:35.746Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:25:35.746Z" level=info msg=reconcileAgentPod namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:25:35.752Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=2676 workflow=hello-world-g2csp
time="2023-12-20T16:25:45.751Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:25:45.752Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=hello-world-g2csp
time="2023-12-20T16:25:45.752Z" level=info msg="node changed" namespace=argo new.message=PodInitializing new.phase=Pending new.progress=0/1 nodeID=hello-world-g2csp old.message= old.phase=Pending old.progress=0/1 workflow=hello-world-g2csp
time="2023-12-20T16:25:45.752Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:25:45.752Z" level=info msg=reconcileAgentPod namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:25:45.765Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=2703 workflow=hello-world-g2csp
time="2023-12-20T16:25:55.768Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:25:55.768Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=hello-world-g2csp
time="2023-12-20T16:25:55.768Z" level=info msg="node unchanged" namespace=argo nodeID=hello-world-g2csp workflow=hello-world-g2csp
time="2023-12-20T16:25:55.769Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:25:55.769Z" level=info msg=reconcileAgentPod namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:26:05.933Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:26:05.933Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=hello-world-g2csp
time="2023-12-20T16:26:05.934Z" level=info msg="Pod failed: Error (exit code 1): pods \"hello-world-g2csp\" is forbidden: User \"system:serviceaccount:argo:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"argo\"" displayName=hello-world-g2csp namespace=argo pod=hello-world-g2csp templateName=whalesay workflow=hello-world-g2csp
time="2023-12-20T16:26:05.934Z" level=info msg="node changed" namespace=argo new.message="Error (exit code 1): pods \"hello-world-g2csp\" is forbidden: User \"system:serviceaccount:argo:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"argo\"" new.phase=Error new.progress=0/1 nodeID=hello-world-g2csp old.message=PodInitializing old.phase=Pending old.progress=0/1 workflow=hello-world-g2csp
time="2023-12-20T16:26:05.934Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:26:05.934Z" level=info msg=reconcileAgentPod namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:26:05.934Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:26:05.934Z" level=info msg="Updated message  -> Error (exit code 1): pods \"hello-world-g2csp\" is forbidden: User \"system:serviceaccount:argo:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"argo\"" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:26:05.934Z" level=info msg="Marking workflow completed" namespace=argo workflow=hello-world-g2csp
time="2023-12-20T16:26:05.941Z" level=info msg="cleaning up pod" action=deletePod key=argo/hello-world-g2csp-1340600742-agent/deletePod
time="2023-12-20T16:26:05.951Z" level=info msg="Workflow update successful" namespace=argo phase=Error resourceVersion=2745 workflow=hello-world-g2csp
time="2023-12-20T16:26:05.959Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/hello-world-g2csp/labelPodCompleted
```

### Logs from in your workflow's wait container

```text
time="2023-12-20T16:25:56.956Z" level=info msg="No output parameters"
time="2023-12-20T16:25:56.956Z" level=info msg="No output artifacts"
time="2023-12-20T16:25:56.967Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:argo:default\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"argo\""
time="2023-12-20T16:25:56.968Z" level=warning msg="Non-transient error: pods \"hello-world-g2csp\" is forbidden: User \"system:serviceaccount:argo:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"argo\""
time="2023-12-20T16:25:56.968Z" level=error msg="executor error: pods \"hello-world-g2csp\" is forbidden: User \"system:serviceaccount:argo:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"argo\""
time="2023-12-20T16:25:56.968Z" level=info msg="Alloc=7218 TotalAlloc=13045 Sys=24677 NumGC=4 Goroutines=8"
time="2023-12-20T16:25:56.969Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" error="workflowtaskresults.argoproj.io \"hello-world-g2csp\" is forbidden: User \"system:serviceaccount:argo:default\" cannot patch resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"argo\""
time="2023-12-20T16:25:56.969Z" level=warning msg="Non-transient error: pods \"hello-world-g2csp\" is forbidden: User \"system:serviceaccount:argo:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"argo\""
time="2023-12-20T16:25:56.969Z" level=error msg="executor error: pods \"hello-world-g2csp\" is forbidden: User \"system:serviceaccount:argo:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"argo\""
time="2023-12-20T16:25:56.970Z" level=fatal msg="pods \"hello-world-g2csp\" is forbidden: User \"system:serviceaccount:argo:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"argo\""
```

**Comment by cardoe** [comment]
I failed to mention that adding `--serviceaccount argo` to the `argo submit` made it work.

**Comment by terrytangyuan** [comment]
Would you like to submit a PR to help improve the docs?

**Comment by cardoe** [comment]
> Would you like to submit a PR to help improve the docs?

Would be glad to. I'm just not sure if that's what the maintainers want from the quick start. If it is then I'll happily update the docs and include a reference to the workflow RBAC for further reading and make a note that when a service account isn't specified then the default account is used which often doesn't have sufficient permissions.

**Comment by terrytangyuan** [comment]
Looks like the quick start and walk-through guides all use default service account which does not have the permission. We can probably just give default service-account enough permission https://github.com/argoproj/argo-workflows/tree/76f4d1f9ca53b8ac48965e12c15454e544936c49/manifests/quick-start/base

**Comment by agilgur5** [comment]
> Looks like the quick start and walk-through guides all use default service account which does not have the permission.

The `default` SA actually [has a `RoleBinding`](https://github.com/argoproj/argo-workflows/blob/76f4d1f9ca53b8ac48965e12c15454e544936c49/manifests/quick-start/base/executor-default-rolebinding.yaml#L11) to [the `executor` Role](https://github.com/argoproj/argo-workflows/blob/76f4d1f9ca53b8ac48965e12c15454e544936c49/manifests/quick-start/base/executor/emissary/executor-role.yaml#L4) and [both are included in the `kustomization.yaml`](https://github.com/argoproj/argo-workflows/blob/76f4d1f9ca53b8ac48965e12c15454e544936c49/manifests/quick-start/base/kustomization.yaml#L11) so the quick start should work with the `default` SA already.



> ```shell
> kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.5.2/install.yaml
> ```

I think the problem is that the Quick Start docs are referencing `install.yaml` instead of `quick-start-minimal.yaml`

**Comment by agilgur5** [comment]
@cardoe would you like to submit a PR to modify the docs to reference `quick-start-minimal.yaml` instead of `install.yaml`?

**Comment by cardoe** [comment]
Yep will do.

**Comment by rnathuji** [comment]
I found this issue after stumbling upon the same problem across our workflows when upgrading from `v3.5.0` to `v3.5.4` using the released manifest files. It seems like this issue was closed after a doc change to the quick start page, but the [installation docs](https://argo-workflows.readthedocs.io/en/latest/installation/) and [release pages](https://github.com/argoproj/argo-workflows/releases/tag/v3.5.4) seemingly suggest that one should be able to use `install.yaml` without issues:

>To install Argo Workflows, navigate to the [releases page](https://github.com/argoproj/argo-workflows/releases/latest) and find the release you wish to use (the latest full release is preferred). Scroll down to the Controller and Server section and execute the kubectl commands.

**Comment by agilgur5** [comment]
> It seems like this issue was closed after a doc change to the quick start page, but the [installation docs](https://argo-workflows.readthedocs.io/en/latest/installation/) and [release pages](https://github.com/argoproj/argo-workflows/releases/tag/v3.5.4) seemingly suggest that one should be able to use `install.yaml` without issue

Yes, this is specific to the quick start, which explicitly states it should not be used in production.

**Comment by rnathuji** [comment]
Yes, I see that the [quick start page](https://argo-workflows.readthedocs.io/en/latest/quick-start/) links to the install page:

> These instructions are intended to help you get started quickly. They are not suitable for production. For production installs, please refer to [the installation documentation](https://argo-workflows.readthedocs.io/en/latest/installation/).

:point_up: refers to the [release pages](https://github.com/argoproj/argo-workflows/releases/latest) which then tells users to run:

```bash
kubectl create namespace argo
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.5.4/install.yaml
```

In any case, perhaps it's user / reader error on my part :man_shrugging: . Given `quick-start-minimal.yaml` is not intended for production, and `install.yaml` doesn't work "out of the box" anymore, is there documentation for what users that were previously using `install.yaml` should do when updating to `v3.5.2` and beyond?

**Comment by agilgur5** [comment]
> and `install.yaml` doesn't work "out of the box" anymore, is there documentation for what users that were previously using `install.yaml` should do when updating to `v3.5.2` and beyond?

This wasn't listed as a regression, is there a regression in the manifests that you noticed for v3.5.2 vs an older version? You mention v3.5.0 as your prior, the only [changes](https://github.com/argoproj/argo-workflows/commits/v3.5.2/manifests) to the manifests between v3.5.0 and v3.5.2 were #11839 and #11947

**Comment by rnathuji** [comment]
Ah, yes, sorry, I wasn't clear about that :grimacing: . So, for better or worse, we have been using the release doc steps to deploy/update `argo` via `install.yaml` since `v3.3.9` or so. It's always worked fine without issues. However, when updating from `v3.5.0` to `3.5.4` workflows began failing with the message `cannot patch resource "pods" in API group ""`. I did the same diff check between the manifests and the only differences I saw were the image tags:

```patch
       - args:
         - server
         env: []
-        image: quay.io/argoproj/argocli:v3.5.0
+        image: quay.io/argoproj/argocli:v3.5.4
         name: argo-server
         ports:
         - containerPort: 2746
@@ -1323,7 +1323,7 @@
             fieldRef:
               apiVersion: v1
               fieldPath: metadata.name
-        image: quay.io/argoproj/workflow-controller:v3.5.0
+        image: quay.io/argoproj/workflow-controller:v3.5.4
         livenessProbe:
           failureThreshold: 3
           httpGet:
```

That's why we were so surprised to hit the problem. For now we've downgraded to the `https://github.com/argoproj/argo-workflows/releases/download/v3.5.1/install.yaml` manifest :man_shrugging: . Any thoughts / suggestions would be very much appreciated :pray: .

**Comment by rnathuji** [comment]
Thanks, @agilgur5! I will look more into the Workflow RBAC to see what changes might be needed for our workflows to work with `v3.5.4`.

Just to help clarify my understanding, is the reason why we're seeing existing workflows work when downgrading just the version tag to `v3.5.1` in the manifest because we've been historically lucking into some default behavior that no longer applies starting `v3.5.2`, and the newer versions are simply surfacing a latent RBAC issue on our end? For example, it's why the following works fine:

```bash
$ minikube start
$ kubectl create namespace argo
$ kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.5.1/install.yaml
$ argo submit --watch https://raw.githubusercontent.com/argoproj/argo-workflows/main/examples/hello-world.yaml
```

Output:

```
STEP                  TEMPLATE  PODNAME            DURATION  MESSAGE
 ✔ hello-world-45qtp  whalesay  hello-world-45qtp  18s
```

But the following will fail (as will versions `3.5.2` and `3.5.3`):

```bash
$ minikube start
$ kubectl create namespace argo
$ kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.5.4/install.yaml
$ argo submit --watch https://raw.githubusercontent.com/argoproj/argo-workflows/main/examples/hello-world.yaml
```

Output:

```
STEP                  TEMPLATE  PODNAME            DURATION  MESSAGE
 ⚠ hello-world-jdsk6  whalesay  hello-world-jdsk6  22s       Error (exit code 1): pods "hello-world-jdsk6" is forbidden: User "system:serviceaccount:default:default" cannot patch resource "pods" in API group "" in the namespace "default"
```

**Comment by agilgur5** [comment]
> For example, it's why the following works fine:

👀 That's an interesting reproduction.
I thought your prod cluster wasn't fresh, so could be that something else changed. If this is a fresh `minikube` cluster each time, then that suggests a change in the Executor is requiring that permission when it previously didn't. Or, more specifically, the simple `hello-world` example managed to work without any additional RBAC, but now that is required.

I'd need to look through the Executor diffs for 3.5.2 to see why that might happen. From a real quick glance, this might be from #11947 -- [this change to `wait.go`](https://github.com/argoproj/argo-workflows/pull/11947/files#diff-441608a808b9f5cea678c857407d03ee2a394dd62d926583fb5a242e6bb96374) ensure it properly reports results. If that's the case, it may be that some really short, simple steps were not recorded entirely correctly previously.
cc @Garett-MacGowan who probably knows this part of the codebase better than me at this point.

**Comment by Garett-MacGowan** [comment]
I only skimmed this, so im not sure if I'm missing something, but have you configured RBAC according to [this](https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/)?

 I can take a better look at this tomorrow.

**Comment by agilgur5** [comment]
> I only skimmed this, so im not sure if I'm missing something, but have you configured RBAC according to [this](https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/)?

I linked that [above](https://github.com/argoproj/argo-workflows/issues/12391#issuecomment-1945197499) -- but apparently it wasn't necessary for simple steps like `hello-world` prior to 3.5.2. #11947 had some Executor changes that seemed like they might've changed some of that logic. It might've been a long-standing bug that didn't have much user-facing impact that you ended up fixing or maybe there's a new request that isn't necessary for simpler steps? I'm not sure, hence why I tagged you.

> I can take a better look at this tomorrow.

Take your time!

**Comment by Garett-MacGowan** [comment]
@agilgur5 here's my take.

TaskResultReconciliation() which uses `workflowtaskresult`, for which we need RBAC, is now (necessarily) called before

```
if woc.wf.Labels[common.LabelKeyCompleted] == "true" { // abort now, we do not want to perform any more processing on a complete workflow because we could corrupt it
```

Before my PR, if the workflow completed quick enough, reconciliation wouldn't have a chance to run and therefore you would avoid the RBAC issue.

This is closely related to #11947 

The quickstart docs should probably mention the need for workflowtaskresult RBAC per https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/

**Comment by agilgur5** [comment]
> Before my PR, if the workflow completed quick enough, reconciliation wouldn't have a chance to run and therefore you would avoid the RBAC issue.

Thought that could be the case per above, thanks for confirming Garett!

> The quickstart docs should probably mention the need for workflowtaskresult RBAC per https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/

The PR that closed this issue, #12445 fixed the quickstart docs to actually use the `quick-start-*.yaml` at my suggestion [above](https://github.com/argoproj/argo-workflows/issues/12391#issuecomment-1867145536), which has the appropriate permissions.

But the Workflow RBAC page should be linked in the production [installation page](https://argo-workflows.readthedocs.io/en/latest/installation/) where it is apparently missing.
@rnathuji would you like to submit a PR to add a link to the Workflow RBAC page to the production installation page? Perhaps it could be made as the first bullet under "Additional installation considerations"

**Comment by Garett-MacGowan** [comment]
@agilgur5 ahh, yes, you're right. The real reason is [here](https://github.com/argoproj/argo-workflows/pull/11947/files#r1389825729). In this PR, we switched to always creating a task result (a placeholder, if no outputs exist) in order to track reconciliation status.

The implementation has changed slightly since this PR, but it's effectively doing the same thing.

**Comment by agilgur5** [comment]
Thanks for the context! Thought it might be something like that.

Re-wording, that would mean that previously, as `hello-world` had no outputs, it would made no task result and hence technically did not need the RBAC. That led to some race conditions however, so now it does require that. The docs have always stated this, so it was actually an undocumented technicality that simpler steps like `hello-world` didn't need the RBAC in the past.

**Comment by Garett-MacGowan** [comment]
> Thanks for the context! Thought it might be something like that.
> 
> Re-wording, that would mean that previously, as `hello-world` had no outputs, it would made no task result and hence technically did not need the RBAC. That led to some race conditions however, so now it does create a task result and therefore require the RBAC. The docs have always stated this, so it was actually an undocumented technicality that simpler steps like `hello-world` didn't need the RBAC in the past.

That's right.

**Comment by rnathuji** [comment]
@agilgur5 - Sure, I can spin up a doc PR.

Thanks all for taking a look and helping to clarify the reason behind the behavioral change that we observed. :tada:

**Comment by agilgur5** [comment]
See PR in #12680

**Comment by philippeflorent** [comment]
> I failed to mention that adding `--serviceaccount argo` to the `argo submit` made it work.

still gives me the same error 

`Error (exit code 64): workflowtaskresults.argoproj.io is forbidden: User "system:serviceaccount:argo:argo" cannot create resource "workflowtaskresults" in API group "argoproj.io" in the namespace "argo"
`

**Comment by philippeflorent** [comment]
I tired **argo** and **default** sa, none of them have enough permissions to submit the hello world example from the quickstart

**Comment by trondhindenes** [comment]
from what I can see it's because the quickstart yaml is missing proper namespace spec. Some resources are created in a hardcoded "argo" namespaces, while some resources (such as roles) are created without specifying a namespace, so they end up in whatever namespace the current kubectl context points to.
