### ISSUE TITLE
Backport doc build changes for versioned docs

### ISSUE THREAD

**Issue by jmeridth** [argoproj/argo-workflows#12414]
# Summary

Keep track of doc build changes that need to be backported to prior versions so they can show as versioned docs on readthedocs.io (once #12360 merges)

Setup changes that need to be backported:

- [.readthedocs.yaml](https://github.com/argoproj/argo-workflows/pull/12360/files#diff-cde814ef2f549dc093f5b8fc533b7e8f47e7b32a8081e0760e57d5c25a1139d9)
- [Makefile](https://github.com/argoproj/argo-workflows/pull/12360/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52)
- [mkdocs.yml](https://github.com/argoproj/argo-workflows/pull/12360/files#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2)
- [hack/check-mkdocs.sh](https://github.com/argoproj/argo-workflows/pull/12360/files#diff-5c6d522ef188e70337bce37f5e67c94b0e734e06a027d621d73509b23bd7880b)
- [docs/requirements.txt](https://github.com/argoproj/argo-workflows/blob/main/docs/requirements.txt)

We'd still want the URL changes also from #12360 but instead of `/latest/` suffix it'd be the semver (e.g., `/release-[major].[minor]/` suffix)

- [x] release-3.5 branch #12462 
  - https://argo-workflows.readthedocs.io/en/release-3.5/ is live
- [ ] release-3.4 branch #12473 
  - https://argo-workflows.readthedocs.io/en/release-3.4/ not generated yet

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by jmeridth** [comment]
@agilgur5 @terrytangyuan Working on the first PR for this.  The files mentioned in the description above make sense and confirming those on my forked project in readthedocs but I also realized we need to update the 461 files that still have github pages links in them.  This brings up a few questions:

1. For backporting we need to switch to readthedocs links but do we, for the backports, want to change to https://argo-workflows.readthedocs.io/en/[version] (e.g., https://argo-workflows.readthedocs.io/en/v3.5.2) or have all backports point to latest (e.g., https://argo-workflows.readthedocs.io/en/latest)?  I assume the version in the URL and we can point the version build in the readthedocs UI.
2. For the `stable` url we'll point it in the readthedocs URL at the latest stable version SHA.  That's how it is done.  You good with this? (as previously mentioned by @agilgur5 [here](https://github.com/argoproj/argo-workflows/pull/12362#discussion_r1433231832))
3. How far back do we want to go?
  - [ ] v3.5.2 - #12450
  - [ ] v3.5.1
  - [ ] v3.5.0
  - [ ] v3.4.14
  - [ ] v3.4.13
  - [ ] v3.4.12
  - [ ] v3.4.11
  - [ ] v3.4.10
  etc

**Comment by terrytangyuan** [comment]
v3.5.2 and v3.4.14 should be fine IMO

**Comment by terrytangyuan** [comment]
> [https://argo-workflows.readthedocs.io/en/[version]](https://argo-workflows.readthedocs.io/en/%5Bversion%5D) (e.g., https://argo-workflows.readthedocs.io/en/v3.5.2

This looks better

**Comment by jmeridth** [comment]
@terrytangyuan We will need to move the tag for each release to the HEAD of their perspective `release-*` branch.  Is this okay?

**Comment by agilgur5** [comment]
> v3.5.2 and v3.4.14 should be fine IMO

yea I was only gonna do latest patch of each minor as well. 

That's also what Argo CD currently has:
![Screenshot 2024-01-03 at 9 10 30 PM](https://github.com/argoproj/argo-workflows/assets/4970083/caebf170-9fd4-449d-bfa1-d5598ac5d89f)

> @terrytangyuan We will need to move the tag for each release to the HEAD of their perspective `release-*` branch.

I would suggest just changing the branch for the minor, i.e. `release-3.5`, to similarly [match Argo CD](https://github.com/argoproj/argo-cd/branches/all?query=release-):
![Screenshot 2024-01-03 at 9 11 55 PM](https://github.com/argoproj/argo-workflows/assets/4970083/10221d21-c570-4bbb-b52a-f5cb4989c572)
