### ISSUE TITLE
Add workflow prioritization docs

### ISSUE THREAD

**Issue by MenD32** [argoproj/argo-workflows#12437]
# Summary

Add workflow priority docs

## Use Cases

It seems from the workflow spec that you can assign a priority to a workflow, but there are no docs about it or an example.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by Joibel** [comment]
What more words would you like there to be? Would you be willing to contribute some more words to the [synchronization](../blob/main/docs/synchronization.md)?

Priority is documented quite simply under https://argo-workflows.readthedocs.io/en/latest/fields/#workflowspec, and the only thing I'm unsure is clear from that is that mutexes are priority aware - so they will be handed to the highest priority first.

**Comment by agilgur5** [comment]
Ah this will be addressed by #13393
