### ISSUE TITLE
support onExit on CronWorkflows

### ISSUE THREAD

**Issue by cnoyesuws** [argoproj/argo-workflows#12447]
# Summary

CronWorkflow does not support onExit as other types do

## Use Cases
slack or email on cron job failure

allcron.yaml:
   ✖ in "testjob-wf" (CronWorkflow): json: unknown field "onExit"

apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: testjob-wf
  namespace: argo
spec:
  onExit: exit_handler
...

supporting on exit will allow us to implement cron workflows in our k8 jobs

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by cnoyesuws** [comment]
Our goal is to be able to slack on cron job failure
If a Cronjob can trigger another type of workflow, point me to some documentation

**Comment by Joibel** [comment]
You can do this with `workflowTemplateRef`. If you create the content of your workflow as a workflow template then your cron jobs will just trigger this. [This](https://github.com/argoproj/argo-workflows/blob/main/examples/dag-inline-cronworkflow.yaml) example shows how you might go about this.

Creating the content of workflows as workflowTemplates is good practice, so I don't think we should do any code changes to support this.

**Comment by cnoyesuws** [comment]
Thanks

**Comment by agilgur5** [comment]
> ```yaml
> spec:
>   onExit: exit_handler
> ```

I'm pretty sure this should be:

```yaml
spec:
  workflowSpec:
    onExit: exit_handler
```

The `CronWorkflow` itself has no `onExit`, the Workflow it creates has an `onExit`
