### ISSUE TITLE
Frequent test failures caused by image download timeout

### ISSUE THREAD

**Issue by Garett-MacGowan** [argoproj/argo-workflows#12452]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

This is a development specific issue. When running the CI, tests frequently (intermittently) fail due to a timeout of the argoexec image download.

![image](https://github.com/argoproj/argo-workflows/assets/24864607/d4b074da-b61a-4bf2-bedd-82251f007ab7)

Here's an example [failed workflow](https://github.com/argoproj/argo-workflows/actions/runs/7402817441/job/20141539578?pr=12397)

This issue seems to be common & is being experienced by multiple users of the v4 action: https://github.com/actions/download-artifact/issues/249

### Potential Solutions

1) Wrap `actions/download-artifact@v4` in a retry action.
2) Downgrade to `actions/download-artifact@v3`
3) Wait for a bug fix for `actions/download-artifact@v4` (https://github.com/actions/download-artifact/issues/249)

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by Garett-MacGowan** [comment]
If someone provides some feedback here on the preferred solution, I can quickly implement & push.

**Comment by Garett-MacGowan** [comment]
@juliev0 FYI I am observing a failure rate much worse than ~1/3 at the moment.

**Comment by agilgur5** [comment]
Nice catch!

I would suggest we revert #12384 as it seems like most folks in that issue are doing. We'll want to add an ignore pattern to `dependabot.yml` for that too so that it doesn't get auto-updated.

Re: retry, we may want to add that anyway as it does still occasionally happen even on v3 (though ideally the action itself would have code to retry...), though it seems to be happening exponentially more with `actions/download-artifact@v4`, so revert would be top priority to fix this and retry would be a nice to have but not necessary, IMO

**Comment by Garett-MacGowan** [comment]
Looks like the [download action](https://github.com/actions/download-artifact/blob/f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110/src/download-artifact.ts#L63) [already implements a retry](https://github.com/actions/toolkit/blob/5430c5d84832076372990c7c27f900878ff66dc9/packages/artifact/src/internal/find/retry-options.ts#L14), so maybe something else is messed up with the new v4.

I think I'll just revert changes from #12384 and open a new ticket to upgrade to v4 once https://github.com/actions/download-artifact/issues/249 is resolved.

**Comment by agilgur5** [comment]
Sounds good. We will still want to add the `dependabot.yml` ignore temporarily until v4 is fixed

**Comment by Garett-MacGowan** [comment]
> Sounds good. We will still want to add the `dependabot.yml` ignore temporarily until v4 is fixed

Yep, I've got that in. Will push shortly.
