### ISSUE TITLE
RTD Docs: Fields Reference example links are broken

### ISSUE THREAD

**Issue by agilgur5** [argoproj/argo-workflows#12453]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

In the Fields Reference on RTD at https://argo-workflows.readthedocs.io/en/latest/fields/ all of the "Examples" dropdowns are currently not rendering markdown properly and are displaying raw text. See below screenshot:

![Screenshot 2024-01-03 at 11 19 35 PM](https://github.com/argoproj/argo-workflows/assets/4970083/a6eb0b8e-2401-4404-89a6-73d882a42fee)

As a result the list is not displaying correctly and you can't directly click the links either.

I'm actually not yet sure why this is happening, which is why I filed an issue instead of a PR currently

Regression from #12360, although again not entirely sure how/why, potentially due to `mkdocs` dep version changes?

### Version

https://argo-workflows.readthedocs.io/en/latest/fields/

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a this is specific to the docs
```

### Logs from the workflow controller

```text
n/a this is specific to the docs
```

### Logs from in your workflow's wait container

```text
n/a this is specific to the docs
```

**Comment by jmeridth** [comment]
It's the `<details>` sections for the examples.  I know that is a GitHub thing but don't know if it is through another extension in mkdocs.  Definitely a plugin/extension that went missing.  I'm looking into this.

**Comment by jmeridth** [comment]
Possibly related? https://github.com/squidfunk/mkdocs-material/issues/4084

**Comment by agilgur5** [comment]
We do [use `pymdownx.details`](https://github.com/argoproj/argo-workflows/blob/c71e1dc05a052778bed597f7c0f50b2ede4a7f32/mkdocs.yml#L34) which is mentioned in https://github.com/squidfunk/mkdocs-material/issues/4084#issuecomment-1173415244. It's included as part of `mkdocs-material`.

Although the [code](https://github.com/argoproj/argo-workflows/blob/9f114188fcffbf45a0b85c32924c2cb0f288bc4a/docs/fields.md?plain=1#L7-L9) you linked above actually doesn't use the syntax from `pymdownx.details`... 🤔 
I wonder if potentially it just happened to work in one version and then broke as it wasn't intended to be used like that anyway.

We'd want to use the `md_in_html` extension then and add the `markdown` attribute to all the `details` blocks. I do want to investigate a bit more before implementing that though

**Comment by agilgur5** [comment]
I figured it out.

`make docs` will create the correct docs, but `mkdocs build` won't. Specifically there's [a line](https://github.com/argoproj/argo-workflows/blob/main/Makefile#L730-L731) in the `Makefile`:
```sh
# fix the fields.md document
go run -tags fields ./hack parseexamples
```

That will end up running [`hack/parse_examples.go`](https://github.com/argoproj/argo-workflows/blob/c71e1dc05a052778bed597f7c0f50b2ede4a7f32/hack/parse_examples.go) which modifies the rendered output from `mkdocs`.

And that code is not currently running in [RTD's build](https://github.com/argoproj/argo-workflows/blob/c71e1dc05a052778bed597f7c0f50b2ede4a7f32/.readthedocs.yml).

It probably makes sense to have this work with a `mkdocs` extension instead of a custom hack, so I'm going to go ahead and modify it as such.

**Comment by jmeridth** [comment]
@agilgur5 nice catch.  agreed re: not using a hack.  Sorry I missed this.

**Comment by agilgur5** [comment]
I missed it during review too; I suppose that's one of the problem with hacks, they can be missed easily if you don't know about them 😅 

But good thing we are now removing a handful of hacks with these updates!
