### ISSUE TITLE
Retrying specific failed node does not work

### ISSUE THREAD

**Issue by mio4kon** [argoproj/argo-workflows#12543]
# Suggested Enhancement

Allow users to selectively retry specific failed nodes instead of retrying all failed nodes at once.

## Use Cases

I'm using Argo Workflow, and at times, I would like the option to retry a specific failed node, instead of retrying all failed nodes (similar to GitLab CI's capability). Even if the overall pipeline still ends up failing, there are specific tasks that I'd prefer to retry without consuming excessive resources retrying other nodes that may inevitably fail. I believe providing users with this level of flexibility is important.

For example, in the following pipeline, I might prefer to only rerun the failed nodes of _BB_, rather than retrying both _B_ and _C_ nodes.

![image](https://github.com/argoproj/argo-workflows/assets/8521943/7f8c3c1b-bb34-4893-ad03-6f8e29ea0342)

*--- updates by agilgur5 below---*
- `--node-field-selector` already exists and [can be used](https://github.com/argoproj/argo-workflows/issues/12543#issuecomment-1898832839) to specify nodes
- but there appears to be [a bug for failed nodes](https://github.com/argoproj/argo-workflows/issues/12543#issuecomment-1899798080), so re-labeled and re-titled this as a bug issue

**Comment by jswxstw** [comment]
If you do not care the failure of nodes B and C, why not use [continueOn](https://argo-workflows.readthedocs.io/en/latest/fields/#continueon) instead.

**Comment by agilgur5** [comment]
Retrying specific nodes is already possible, see #12005 for an example

**Comment by agilgur5** [comment]
> I alse want the argo-cli support Skip operation, which support skipping the specific failed nodes and modifying the outputs.

Please keep feature requests on-topic to 1 per issue.

The behavior you're asking for would not be supported though, nodes are only considered skipped if they have a conditional that skips them.
A "skip" operation also doesn't exist in other DAG orchestrators as far as I know either

**Comment by mio4kon** [comment]
> Retrying specific nodes is already possible, see #12005 for an example

There is a slight difference compared to what was mentioned earlier.

The retry of specific nodes here only supports specifying successful nodes, and it's not possible to specify failed nodes. --node-field-selector and --restart-successful must be used together.

**Comment by mio4kon** [comment]
> > I alse want the argo-cli support Skip operation, which support skipping the specific failed nodes and modifying the outputs.
> 
> Please keep feature requests on-topic to 1 per issue.
> 
> The behavior you're asking for would not be supported though, nodes are only considered skipped if they have a conditional that skips them. A "skip" operation also doesn't exist in other DAG orchestrators as far as I know either

@jswxstw The issue can be partially resolved by using [ A || A.failed ], but it is overly automated.  @agilgur5  In some scenarios, after a failure, manual confirmation may be needed to proceed with the subsequent steps. However, currently, it is unclear how to implement this workflow.

**Comment by jswxstw** [comment]
> The issue can be partially resolved by using [ A || A.failed ], but it is overly automated. @agilgur5 In some scenarios, after a failure, manual confirmation may be needed to proceed with the subsequent steps. However, currently, it is unclear how to implement this workflow.

You have set `continueOn Failed` to the B and C nodes, so you do not want to retry these steps when manual retrying, am I  understanding correctly?

**Comment by mio4kon** [comment]
> > The issue can be partially resolved by using [ A || A.failed ], but it is overly automated. @agilgur5 In some scenarios, after a failure, manual confirmation may be needed to proceed with the subsequent steps. However, currently, it is unclear how to implement this workflow.
> 
> You have set `continueOn Failed` to the B and C nodes, so you do not want to retry these steps when manual retrying, am I understanding correctly?

No, what I replied to is not the issue I raised. Instead, it's about the suggestion you mentioned to add a button for skipping failures. I believe the suggestion you made is also very useful for me, as we encounter similar scenarios on our end.

**Comment by agilgur5** [comment]
> [#12005 ](https://github.com/argoproj/argo-workflows/discussions/12005) the retry of specific nodes here only supports specifying successful nodes, and it's not possible to specify failed nodes.

The default behavior of `retry` is to only retry failed nodes.

> --node-field-selector and --restart-successful must be used together.

If you need to use them together, you can.

> There is a slight difference compared to what was mentioned earlier.

Sorry it's not clear to me what the difference is. Retrying specific nodes is possible (whether succeeded or failed). Is there something else missing that you would like?

**Comment by agilgur5** [comment]
> @jswxstw The issue can be partially resolved by using [ A || A.failed ], but it is overly automated.

Yes, this would be one of way of implementing it.

> about the suggestion you mentioned to add a button for skipping failures

Skipping a step is a semantically different Workflow. The currently available operations do not change the intent or conditionals of the Workflow, and they should not. Operations only modify the Workflow's `status`, they do not modify the Workflow spec itself, and should not do so.
So a "Skip" operation as proposed violates semantic intent and would not be accepted as a feature as such.

> @agilgur5 In some scenarios, after a failure, manual confirmation may be needed to proceed with the subsequent steps. However, currently, it is unclear how to implement this workflow.

That sounds like a 3rd, separate question from the other two. There's really too many topics here...

You can use a `suspend` template to require manual confirmation, so that too is already possible.

**Comment by mio4kon** [comment]
> > [#12005 ](https://github.com/argoproj/argo-workflows/discussions/12005) the retry of specific nodes here only supports specifying successful nodes, and it's not possible to specify failed nodes.
> 
> The default behavior of `retry` is to only retry failed nodes.
> 
> > --node-field-selector and --restart-successful must be used together.
> 
> If you need to use them together, you can.
> 
> > There is a slight difference compared to what was mentioned earlier.
> 
> Sorry it's not clear to me what the difference is. Retrying specific nodes is possible (whether succeeded or failed). Is there something else missing that you would like?

![image](https://github.com/argoproj/argo-workflows/assets/8521943/d1b187f4-43bc-40f3-9943-7d3c730cc6cf)

The pipeline in the image above does not currently allow for selective retries of specific nodes, such as the BB node.

**Comment by agilgur5** [comment]
> Using` --node-field-selector` alone does not actually take effect; it still retries all failed nodes.

Yea that sounds like a bug, afaik, `--node-field-selector` is supposed to be able to be used without `--restart-successful`. Strange that it hasn't been noticed earlier though, I wonder if there was a regression 🤔 

This issue was filed as a feature request though, a reproducible Workflow and set of commands / instructions would be helpful to test with.

> @agilgur5 Please help me review this PR 🙏 #12553

I'll take a look, thanks for checking the code

**Comment by mio4kon** [comment]
> > Using` --node-field-selector` alone does not actually take effect; it still retries all failed nodes.
> 
> Yea that sounds like a bug, afaik, `--node-field-selector` is supposed to be able to be used without `--restart-successful`. Strange that it hasn't been noticed earlier though, I wonder if there was a regression 🤔
> 
> This issue was filed as a feature request though, a reproducible Workflow and set of commands / instructions would be helpful to test with.
> 
> > @agilgur5 Please help me review this PR 🙏 #12553
> 
> I'll take a look, thanks for checking the code

hi，Is there still a problem with the PR corresponding to this issue? Can you reopen this issue? I think it's still a bit of a hassle to not be able to retry a single failed node😭

**Comment by mio4kon** [comment]
@agilgur5 Hi, are there any other issues with this pull request?

**Comment by mio4kon** [comment]
hi，Is there any follow-up plan for fixing this issue?
@agilgur5

**Comment by isubasinghe** [comment]
https://github.com/argoproj/argo-workflows/pull/13734 retry rewrite here

**Comment by tooptoop4** [comment]
@isubasinghe can this be re-opened? https://github.com/argoproj/argo-workflows/blob/0aa5e45bbd6118bb642833515aa04165c5d48748/workflow/util/util.go#L1405 is still present @mio4kon PR was not merged

**Comment by isubasinghe** [comment]
I wasn't sure if this was a bug or a feature, arguably it doesn't matter if it's a bug anymore? 
This has been the default behaviour for so long that, it effectively can be considered intentional. 

I think this is why some kind of specification is important about what argo does, it removes the ambiguity between "is this a feature" and "is this a bug". 

That is why #13734 does not attempt to correct this behaviour. 

I'm happy to reopen, I think #13734 will go into 3.7 anyway, so we could perhaps consider retries a breaking change in that release?  So perhaps this is fine @Joibel ?
