### ISSUE TITLE
Update outdated k8s go packages to 0.26+

### ISSUE THREAD

**Issue by Tomcli** [argoproj/argo-workflows#12565]
# Summary
There are list of go packages that are outdated and no longer provide security patches. We also want to make sure packages that shared with the KFP/KFP-Tekton deployment won't fall to behind as it will create a dependency issue.

List of Kubernetes client dependencies to update, ideally using 0.26+ as Kubernetes only provide security patches to the recent 4 major releases.
```
	k8s.io/api v0.24.3
	k8s.io/apimachinery v0.24.3
	k8s.io/cli-runtime v0.24.3
	k8s.io/client-go v0.24.3
        k8s.io/kubectl v0.24.3
```

List of dependencies that are nice to have, the grpc-gateway v1 no longer has security patches and openAPI v2 schema is out of support few years ago. 
```
	github.com/grpc-ecosystem/grpc-gateway v1.16.0
```

## Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by agilgur5** [comment]
Note that for Argo 3.4 and 3.5, we do need to support some older k8s versions per the [support matrix](https://argo-workflows.readthedocs.io/en/release-3.5/releases/#kubernetes-compatibility-matrix), so any deps have to allow for some version skew as well

**Comment by BabisK** [comment]
Would love to have the `grpc-gateway` updated to version 2. It breaks my build rigt now.

**Comment by terrytangyuan** [comment]
@Tomcli Is this something you want to work on?

**Comment by Tomcli** [comment]
Hi @terrytangyuan, I'm busy with grading KFP to the new golang and dependencies for the KF 1.9 release. I think for KF 1.9 our goal is first to upgrade Argo to 3.4. If anyone can take on this issue it will be great. Otherwise I can come back once I finished all the features/issues from KFP side.

**Comment by terrytangyuan** [comment]
No worries. As long as this is not blocking KFP upgrade. We can leave this here for anyone who has time to take.

**Comment by terrytangyuan** [comment]
Sounds good

**Comment by blkperl** [comment]
I've opened https://github.com/argoproj/argo-workflows/pull/12847 to get us back to a version with security updates.

**Comment by blkperl** [comment]
I've opened https://github.com/argoproj/argo-workflows/issues/12851 for the OpenAPI update as it seems like a large project

**Comment by blkperl** [comment]
Hey @Tomcli since https://github.com/argoproj/argo-workflows/pull/12847 is now merged and I've opened https://github.com/argoproj/argo-workflows/issues/12851 for the other issue. I'm going to close this as done. Thank you for reporting the issue.

**Comment by agilgur5** [comment]
> the grpc-gateway v1 no longer has security patches

We may want to split another issue for `grpc-gateway` as well, which also seems like it might be quite an undertaking per https://github.com/grpc-ecosystem/grpc-gateway/issues/1223 and [the migration guide](https://grpc-ecosystem.github.io/grpc-gateway/docs/development/grpc-gateway_v2_migration_guide/).

It also has been mentioned in Argo a few times if we should remove gRPC support altogether as it's a source of some harder to maintain things, like HTTP being codegen'd
