### ISSUE TITLE
Support both SSO and access token to authenticate the API 

### ISSUE THREAD

**Issue by polyedre** [argoproj/argo-workflows#12585]
# Summary

When Argo Workflows is configured in SSO mode, it seems that it is not possible to call the REST API using an Access token. Instead, users must use the "Bearer v2" and specify a JWT provided by the SSO service.

Can we support both authentication mechanisms?

## Use Cases

Some organisations may need SSO to authenticate the web interface, used mostly by humans. However, the API might be consumed by microservices deployed in a Kubernetes cluster. For these microservices, it is easier to create a ServiceAccount with a Secret token instead of relying on a Service account on the SSO provider. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by polyedre** [comment]
Thank you for pointing out the --auth-mode option. I did not realize that it could accept multiple values, as the documentation clearly states. My apologies for the inconvenience caused by my oversight.

**Comment by dellnoantechnp** [comment]
We use `Helm` install argo-workflows release, enable both `authMode` in `client` and `client`.
```yaml
...
authModes:   
  - client     <-- add
  - sso
...
```

Now, I can get the `ServiceAccount` token use down there command:
```shell
>_ kubectl get secret -n infrastructure argo-workflows-server-token-nxgpp -o jsonpath='{.data.token}' | base64 -d
```

Open the WebUI, paste the `Bearer <token>` like this:
<img width="980" alt="image" src="https://github.com/argoproj/argo-workflows/assets/11703403/d7e28d01-c8aa-461c-be92-807557389366">
Login ..


🎉 Finally, we can use `authMode=client` mode  in argo-workflows `API`, like this:
```shell
## Request:
>_ curl -s https://workflows.example.com/api/v1/workflows/workflows -H 'Authorization: Bearer NDZkZC1hN2N......' | jq

## Response: 
{"metadata":{"resourceVersion":"16892978"},"items":[{"metadata":{"name":"cicd-java-from-webhook-tx824","generateName":"cicd-java-from-webhook-","namespace":"workflows","uid":"e156d1c6-7f00-414c-a9bc-944618646580","resourceVersion":"16809226","generation":16,"creationTimestamp":"2024-04-18T10:49:28Z","labels":{"events.argoproj.io/action-timestamp":"1713437367842","events.argoproj.io/sensor":"cicd-sensor","event
```
