### ISSUE TITLE
Make argoexec-image returns error in Windows `expected 'package', found signal_darwin`

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#12603]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

`make start` `make argoexec image` used to work in windows with windows file system and devcontainer prior to 3.4.x

Now it returns
```
$ make dist/argoexec 
GIT_COMMIT=877c5523066e17687856fe3484c9b2d398e986f5 GIT_BRANCH=release-3.5.1 GIT_TAG=v3.5.1 GIT_TREE_STATE=dirty RELEASE_TAG=true DEV_BRANCH=false VERSION=v3.5.1
KUBECTX= DOCKER_DESKTOP=false K3D=false DOCKER_PUSH=false
RUN_MODE=local PROFILE=minimal AUTH_MODE=hybrid SECURE=false STATIC_FILES=true ALWAYS_OFFLOAD_NODE_STATUS=false UPPERIO_DB_DEBUG=0 LOG_LEVEL=debug NAMESPACED=trueCGO_ENABLED=0 go build -v -gcflags '' -ldflags '-X github.com/argoproj/argo-workflows/v3.version=v3.5.1 -X github.com/argoproj/argo-workflows/v3.buildDate=2024-01-01T17:15:27Z -X github.com/argoproj/argo-workflows/v3.gitCommit=877c5523066e17687856fe3484c9b2d398e986f5 -X github.com/argoproj/argo-workflows/v3.gitTreeState=dirty -X github.com/argoproj/argo-workflows/v3.gitTag=v3.5.1 -extldflags -static' -o dist/argoexec ./cmd/argoexec
workflow\executor\os-specific\signal_linux.go:1:1: expected 'package', found signal_darwin
make: *** [Makefile:237: dist/argoexec] Error 1
```

### Version

3.5.0+

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
.
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
Closing per https://github.com/argoproj/argo-workflows/pull/12604#issuecomment-1972763515

**Comment by agilgur5** [comment]
Apparently this is indeed duplicative of #9590 and a general error when symlinks are not enabled in `git`
