### ISSUE TITLE
Workflow in `Running` but `workflows.argoproj.io/completed` is `true` 

### ISSUE THREAD

**Issue by shuangkun** [argoproj/argo-workflows#12615]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

I want when I retry a workflow, if it retry success, it will be Running and the workflow continues processing.
But in this case, the workflow is stuck.
The issue is to record https://github.com/argoproj/argo-workflows/pull/12574

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

This problem is relatively difficult to reproduce. This situation can only occur if the user performs a retry during the last “Processing workflow”. This may occur when very large workflows and API Servers are under pressure.

This is difficult to reproduce in unit testing and e2e testing. But I designed a reasonable experiment to reproduce it and added it to the test for reference.

First, add the code to func "taskResultReconciliation". （I think this is possible, when the Wokflow is large and has complex outputs, processing the workflow may take more than 2s.）
```go
if woc.checkReconciliationComplete() {
	time.Sleep(time.Second*2)
}
```
Second,  run the test. Retry the failed workflow when "Processing workflow". The test is in https://github.com/argoproj/argo-workflows/pull/12574
```sh
make TestRetryStoppedButIncompleteWorkflow
```

Finally, you will get a workflow in Running status but its labelCompleted is true.
```
tianshuangkun@B-QGHAMD6M-2124 logs % kubectl get workflow -o yaml -w | grep workflows.argoproj.io/completed
    workflows.argoproj.io/completed: "false"
    workflows.argoproj.io/completed: "false"
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/completed: "true"
^C
tianshuangkun@B-QGHAMD6M-2124 logs % argo list
NAME                     STATUS    AGE   DURATION   PRIORITY
wf-retry-stopped-b57pd   Running   8s    5s         0
```
```


### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
Is this also a regression from #12402? Or a bug that has existed before?

**Comment by jswxstw** [comment]
Is `wf.Status.Fulfilled() && LabelKeyCompleted == "false"` equivalent to `Completing` phase?
Why not add the LabelKeyCompleted verification in workflow retry logic? Return errors.CodeBadRequest if workflow is in `Completing` phase.

**Comment by shuangkun** [comment]
> Is this also a regression from #12402? Or a bug that has existed before?

I think it is a bug that has existed before.

**Comment by shuangkun** [comment]
> Is `wf.Status.Fulfilled() && LabelKeyCompleted == "false"` equivalent to `Completing` phase? Why not add the LabelKeyCompleted verification in workflow retry logic? Return errors.CodeBadRequest if workflow is in `Completing` phase.

I think this method is simple for us, but not friendly enough for user. If the user sees workflow Failed but cannot retry, when can Retry be performed?

**Comment by jswxstw** [comment]
> > Is `wf.Status.Fulfilled() && LabelKeyCompleted == "false"` equivalent to `Completing` phase? Why not add the LabelKeyCompleted verification in workflow retry logic? Return errors.CodeBadRequest if workflow is in `Completing` phase.
> 
> I think this method is simple for us, but not friendly enough for user. If the user sees workflow Failed but cannot retry, when can Retry be performed?

Yes, the error may be confused for users since `LabelKeyCompleted` is not visible to users. 
Howerver, this issue is relatively sporadic, and the duration of the completing state is not very long(depends on the `DEFAULT_REQUEUE_TIME`). You might encounter this problem when you involves automatic retry of the entire workflow upon failure phase in your code. So, I think it may be a simpler workaround.

**Comment by jswxstw** [comment]
> > Is this also a regression from #12402? Or a bug that has existed before?
> 
> I think it is a bug that has existed before.

<img width="2440" alt="image" src="https://github.com/argoproj/argo-workflows/assets/18543532/da23b98c-eefd-45f3-a202-00e1f2152d62">

`LabelKeyCompleted ` will be marked "true" without checking if task result reconciliation is completed before #12402 .

**Comment by shuangkun** [comment]
> > > Is this also a regression from #12402? Or a bug that has existed before?
> > 
> > 
> > I think it is a bug that has existed before.
> 
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/18543532/302278013-da23b98c-eefd-45f3-a202-00e1f2152d62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzQ2ODEsIm5iZiI6MTcwNzEzNDM4MSwicGF0aCI6Ii8xODU0MzUzMi8zMDIyNzgwMTMtZGEyM2I5OGMtZWVmZC00NWYzLWEyMDItMDBlMWYyMTUyZDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDExNTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MDhkYmE2ZTRkZWE3ZWMzMjViMmRjNGNkNjY0YmZjNGVjOTRhYjY0ZjBhN2EyODExYWZlNjBjYzdhNGRmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5yADZwnhUJFNsFrLgOp4ch9h8JpA2m5g0h3aBpRXndw">
> `LabelKeyCompleted ` will be marked "true" without checking if task result reconciliation is completed before #12402 .

It stil need check daemon nodes.

**Comment by shuangkun** [comment]
> > > Is `wf.Status.Fulfilled() && LabelKeyCompleted == "false"` equivalent to `Completing` phase? Why not add the LabelKeyCompleted verification in workflow retry logic? Return errors.CodeBadRequest if workflow is in `Completing` phase.
> > 
> > 
> > I think this method is simple for us, but not friendly enough for user. If the user sees workflow Failed but cannot retry, when can Retry be performed?
> 
> Yes, the error may be confused for users since `LabelKeyCompleted` is not visible to users. Howerver, this issue is relatively sporadic, and the duration of the completing state is not very long(depends on the `DEFAULT_REQUEUE_TIME`). You might encounter this problem when you involves automatic retry of the entire workflow upon failure phase in your code. So, I think it may be a simpler workaround.

So if we can work it out, don't need let users face this error.  In large-scale debugging scenarios (8000+), this problem occurs almost frequently.

**Comment by jswxstw** [comment]
Is it possible to modify both the phase and LabelKeyCompleted simultaneously without adding an intermediate `Completing` state which might also confuse users.

**Comment by shuangkun** [comment]
> Is it possible to modify both the phase and LabelKeyCompleted simultaneously without adding an intermediate `Completing` state which might also confuse users.

I think we need to have a state to represent this stage. It is possible to add a state of Completing or just add an invisible label to represent Completing. See what other members have to say.
