### ISSUE TITLE
Outdated "Projects" list in README

### ISSUE THREAD

**Issue by franz-josef-kaiser** [argoproj/argo-workflows#12613]
# Summary

The [list of projects](https://github.com/argoproj/argo-workflows/tree/13444e663387e3b5b331c278cd9e79fc88968d7e#ecosystem) contains some projects that are effectively dead (DNS entry gone, depreciation notice in repo, etc.).

* [Openpanel](https://www.onepanel.ai/): DNS entry gone
* [Orchest](https://github.com/orchest/orchest/): no longer actively developed
* [Piper](https://github.com/rookout/piper): deprecated

Please understand, that I just stumbled upon your project, so I am not filing a PR for this.

**Comment by agilgur5** [comment]
Thanks for letting us know! Some older references can still be useful as examples, but a dead link certainly isn't.

> * [Piper](https://github.com/rookout/piper): deprecated

The README says it [moved](https://github.com/Rookout/piper/blob/440953e2dbf0a447531b31fad7827a4bdd9b103a/README.md?plain=1#L5) to a new location: https://github.com/quickube/piper. That has all the same `git` history, so effectively a fork in a different org.

Their README maybe shouldn't call it "deprecated", that might be a misnomer

> * [Openpanel](https://www.onepanel.ai/): DNS entry gone

Here's a link to their OSS repo(s): https://github.com/onepanelio/onepanel. Seems like it hasn't had development in a while, but we can at least update the link to a working one if not remove it

**Comment by terrytangyuan** [comment]
I don't think we want to monitor each project's activity so I'd leave this to the original PR authors to maintain. It doesn't hurt to keep them even when they are active since they adopted Argo Workflows and that's all we want to show here.
