### ISSUE TITLE
Added paging function for workflow execution history on CronWorkflow/WorkflowTemplate UI

### ISSUE THREAD

**Issue by panicboat** [argoproj/argo-workflows#12646]
# Summary

We need a paging feature in the execution history that is displayed on the CronWorkflow/WorkflowTemplate UI details page.
The solution is to limit the number of cases to be retrieved at a time, as argo-server will go OOM if the execution history is huge.
Ref: https://github.com/argoproj/argo-workflows/issues/12645

## Use Cases

When you want to check the details of a CronWorkflow/WorkflowTemplate that has a large execution history.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by agilgur5** [comment]
Let's consolidate this with #12645 as that is the root cause and a bug is higher priority
