### ISSUE TITLE
Support EKS Pod Identity to access AWS s3

### ISSUE THREAD

**Issue by csantanapr** [argoproj/argo-workflows#12650]
# Summary

Argo Workflow to support accessing AWS s3 using EKS Pod Identity , this is a additional way of assuming a IAM role than using IRSA. 

The change is a bump in the version of to the aws-sdk-go-v2 minimum packages credentials->v.1.16.0 and config->v1.25.0

These dependencies are already picked up in latest version of argoproj/pkg so the change is to update go.mod/go.sum to pickup the new version https://github.com/argoproj/argo-workflows/blob/main/go.mod#L16

## Use Cases

Instead of configuring service account with annotation (IRSA), now the configuration of associating an IAM role to a sepecific service account is done on the AWS API level nothing to be done in kubernetes API.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by agilgur5** [comment]
@csantanapr do you think you could add some docs on using EKS Pod Identity to https://argo-workflows.readthedocs.io/en/latest/configure-artifact-repository/#configuring-aws-s3? There's already a section on IRSA there, so this would fit in neatly

**Comment by csantanapr** [comment]
Yes I will add docs for Pod identity, the docs will give user option to use IRSA or Pod Identity

**Comment by rafilkmp3** [comment]
Can someone document how to use pod identity to store artifacts in S3 if the documentation is not up-to-date?

**Comment by agilgur5** [comment]
https://github.com/argoproj/argo-workflows/pull/12467 added EKS Pod Identity to the IRSA section
