### ISSUE TITLE
UI defaults to `undefined` namespace

### ISSUE THREAD

**Issue by sli720** [argoproj/argo-workflows#12658]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

I've installed latest Argo Workflows through the Helm chart and created a role, rolebinding, serviceaccount and secret (in the argo namespace) for accessing the UI with the token. The UI always defaults to an Undefined namespace and I always have to switch it to argo. I thought this should have been fixed with: https://github.com/argoproj/argo-workflows/pull/9008  or do I need to configure the default namespace somewhere? I couldn't find any option.

![Screenshot from 2024-02-11 10-47-43](https://github.com/argoproj/argo-workflows/assets/53348964/e647149d-daa2-46a3-82b0-29dd5d638516)

### Version

3.5.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Not related to workflows
```

### Logs from the workflow controller

```text
Not related to workflows
```

### Logs from in your workflow's wait container

```text
Not related to workflows
```

**Comment by agilgur5** [comment]
Could you provide more information regarding your configuration, for instance, your `workflow-controller-configmap.yaml`, your Server `args` and env vars, and the `Role` you created? I'm familiar with the Helm chart so the `values` and version of the Chart would suffice for me for the first two (the `Role` is custom though, so would need that).

I can't reproduce this and actually haven't ever seen this, particularly not persisted (as the UI saves your `namespace` to `localStorage`) so I'm not sure what's causing this to happen for you

**Comment by terrytangyuan** [comment]
Also check your service account to see if there's namespace associated with it in order to work with the fix https://github.com/argoproj/argo-workflows/pull/9008

**Comment by agilgur5** [comment]
> Also check your service account to see if there's namespace associated with it in order to work with the fix #9008

SAs are namespace-scoped, so an SA will always have a namespace. Not sure if you meant something else?

**Comment by terrytangyuan** [comment]
Yeah I think maybe there's a case where the namespace is not correctly/successfully obtained from the SA.

**Comment by JoKuebler** [comment]
I have the same issue. Some information on my configuration. Installed via Helm Chart aswell. I created two namespaces: argo-workflows-ctrl -> The controller runs here
argo-workflows -> Workflows run here

Within the argo-workflows namespace I created a SA which is used to log into the UI. The definition of this account looks like:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-developer
  namespace: argo-workflows
```

Does that help? Let me know if you need more info or if my setup might be the issue.

**Comment by JoKuebler** [comment]
Sure here is the configmap you asked for:

`apiVersion: v1
data:
  config: |
    metricsConfig:
      enabled: true
      path: /metrics
      port: 9090
      ignoreErrors: false
      secure: false
    nodeEvents:
      enabled: true
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config":"metricsConfig:\n  enabled: true\n  path: /metrics\n  port: 9090\n  ignoreErrors: false\n  secure: false\nnodeEvents:\n  enabled: true\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"workflow-controller","app.kubernetes.io/instance":"argo-workflows-installation","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argo-workflows-cm","app.kubernetes.io/part-of":"argo-workflows","helm.sh/chart":"argo-workflows-0.40.10"},"name":"argo-workflows-installation-workflow-controller-configmap","namespace":"argo-workflows-ctrl"}}
  creationTimestamp: "2024-02-14T14:41:58Z"
  labels:
    app.kubernetes.io/component: workflow-controller
    app.kubernetes.io/instance: argo-workflows-installation
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-workflows-cm
    app.kubernetes.io/part-of: argo-workflows
    helm.sh/chart: argo-workflows-0.40.10
  name: argo-workflows-installation-workflow-controller-configmap
  namespace: argo-workflows-ctrl
  resourceVersion: "499618279"
  uid: e0f037db-b886-4e7a-8810-e4ceb21baa41`

> You logged in with this SA's token in client auth mode? I don't see any annotations on the SA. Can you provide the Role and RoleBinding as well?

Yes, here is the deployed SA:

`apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"argo-workflows-installation"},"name":"argo-developer","namespace":"argo-workflows"}}
  creationTimestamp: "2024-02-14T14:41:58Z"
  labels:
    app.kubernetes.io/instance: argo-workflows-installation
  name: argo-developer
  namespace: argo-workflows
  resourceVersion: "494076059"
  uid: f2d06591-174e-47b2-8754-368ad17eecf0
secrets:
- name: argo-developer-token-hh664`

I'm using the "edit" role which is defined in the helm chart here: https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/templates/controller/workflow-aggregate-roles.yaml

`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-developer
subjects:
- kind: ServiceAccount
  name: argo-developer
  namespace: argo-workflows
roleRef:
  kind: ClusterRole
  name: argo-workflows-installation-edit  
  apiGroup: rbac.authorization.k8s.io`

**Comment by agilgur5** [comment]
Could you also provide the `args` and env vars to the Server? I had requested that previously too. Can provide your `Deployment` manifest

**Comment by JoKuebler** [comment]
Yes, here is the relevant part from my Deployment manifest:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 4dfab955c7d4a495fcf16422568fd612ae731c74a169f76065dbc99b78f14b20
    cni.projectcalico.org/podIP: 10.80.196.141/32
    cni.projectcalico.org/podIPs: 10.80.196.141/32
  creationTimestamp: "2024-02-21T12:39:29Z"
  generateName: argo-workflows-installation-server-54b8f89dfb-
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-workflows-installation
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-workflows-server
    app.kubernetes.io/part-of: argo-workflows
    app.kubernetes.io/version: v3.5.4
    helm.sh/chart: argo-workflows-0.40.10
    pod-template-hash: 54b8f89dfb
  name: argo-workflows-installation-server-54b8f89dfb-7sktk
  namespace: argo-workflows-ctrl
spec:
  containers:
  - args:
    - server
    - --configmap=argo-workflows-installation-workflow-controller-configmap
    - --secure=true
    - --loglevel
    - info
    - --gloglevel
    - "0"
    - --log-format
    - text
    env:
    - name: IN_CLUSTER
      value: "true"
    - name: ARGO_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: BASE_HREF
      value: /
    - name: FIRST_TIME_USER_MODAL
      value: "false"
    - name: FEEDBACK_MODAL
      value: "false"
    - name: NEW_VERSION_MODAL
      value: "false"
    image: quay.io/argoproj/argocli:v3.5.4
    imagePullPolicy: Always
    name: argo-server
```

**Comment by agilgur5** [comment]
Could you also provide the logs of your Server Pod(s)? I'm suspecting there's an error there

**Comment by koslowdavida** [comment]
Getting this as well.

**Comment by cmontemuino** [comment]
> Could you also provide the logs of your Server Pod(s)? I'm suspecting there's an error there

I'm also experiencing the same issue as @JoKuebler. 

These are the logs from a fresh install using KinD:

```shell
k -n argo logs deployment/argo-workflows-server -f
time="2024-06-04T14:44:37.602Z" level=info msg="not enabling pprof debug endpoints"
time="2024-06-04T14:44:37.603Z" level=info authModes="[server client]" baseHRef=/argowf/ managedNamespace= namespace=argo secure=false ssoNamespace=argo
time="2024-06-04T14:44:37.603Z" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argo-workflows.readthedocs.io/en/release-3.5/tls/"
time="2024-06-04T14:44:37.603Z" level=info msg="SSO disabled"
time="2024-06-04T14:44:37.609Z" level=info msg="Starting Argo Server" instanceID= version=v3.5.4
time="2024-06-04T14:44:37.609Z" level=info msg="Creating event controller" asyncDispatch=false operationQueueSize=16 workerCount=4
time="2024-06-04T14:44:37.612Z" level=info msg="GRPC Server Max Message Size, MaxGRPCMessageSize, is set" GRPC_MESSAGE_SIZE=104857600
time="2024-06-04T14:44:37.612Z" level=info msg="Argo Server started successfully on http://localhost:2746" url="http://localhost:2746"
time="2024-06-04T14:44:57.431Z" level=info duration="116.292µs" method=GET path=index.html size=494 status=0
time="2024-06-04T14:45:06.155Z" level=info duration="111.583µs" method=GET path=index.html size=0 status=304
time="2024-06-04T14:45:06.235Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=info.InfoService grpc.start_time="2024-06-04T14:45:06Z" grpc.time_ms=0.491 span.kind=server system=grpc
time="2024-06-04T14:45:06.235Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2024-06-04T14:45:06Z" grpc.time_ms=0.123 span.kind=server system=grpc
time="2024-06-04T14:45:06.235Z" level=info duration=2.987ms method=GET path=/api/v1/info size=70 status=0
time="2024-06-04T14:45:06.236Z" level=info duration=2.854292ms method=GET path=/api/v1/userinfo size=118 status=0
time="2024-06-04T14:45:06.302Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetVersion grpc.service=info.InfoService grpc.start_time="2024-06-04T14:45:06Z" grpc.time_ms=0.152 span.kind=server system=grpc
time="2024-06-04T14:45:06.311Z" level=info duration=8.868166ms method=GET path=/api/v1/version size=215 status=0
time="2024-06-04T14:45:08.859Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflowTemplates grpc.service=workflowtemplate.WorkflowTemplateService grpc.start_time="2024-06-04T14:45:08Z" grpc.time_ms=8.334 span.kind=server system=grpc
time="2024-06-04T14:45:08.859Z" level=info duration=9.86ms method=GET path=/api/v1/workflow-templates/undefined size=53 status=0
time="2024-06-04T14:45:08.859Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListCronWorkflows grpc.service=cronworkflow.CronWorkflowService grpc.start_time="2024-06-04T14:45:08Z" grpc.time_ms=6.292 span.kind=server system=grpc
time="2024-06-04T14:45:08.860Z" level=info duration=7.254166ms method=GET path=/api/v1/cron-workflows/undefined size=53 status=0
time="2024-06-04T14:45:08.861Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2024-06-04T14:45:08Z" grpc.time_ms=6.746 span.kind=server system=grpc
time="2024-06-04T14:45:08.861Z" level=info duration=9.1905ms method=GET path=/api/v1/workflows/undefined size=53 status=0
```

**Comment by agilgur5** [comment]
Hmm, after debugging https://github.com/argoproj/argo-workflows/discussions/13316#discussioncomment-9976614, I think this might be because #9008 relies on `claims.ServiceAccountNamespace` which [might be missing](https://github.com/argoproj/argo-workflows/blob/80866f9f4e5f8ba2ec004de63b2ba7e7c7effb7e/server/auth/serviceaccount/claims.go#L16) for certain login types. Need to investigate that more, but that one's fairly simple to check against the UI with

**Comment by agilgur5** [comment]
> Need to investigate that more, but that one's fairly simple to check against the UI with

For `--auth-mode=server`, no claims what-so-ever on the UserInfo page:
![Screenshot 2024-07-06 at 6 29 18 PM](https://github.com/argoproj/argo-workflows/assets/4970083/6c6420fe-cadc-49b6-abde-b30bf0ca4570)

That may explain `undefined`, although I'm surprised we haven't gotten this while testing, since the test instance defaults to this.

For `--auth-mode=client`, "Service Account" and "Service Account Namespace" are missing (only "Issuer" and "Subject" are present):
![Screenshot 2024-07-06 at 6 33 55 PM](https://github.com/argoproj/argo-workflows/assets/4970083/41a24906-4cd4-4b17-bb1b-809c42c93ca5)

For `client`, we can derive the SA name and namespace from the `subject`. For `server`, it should use the Server SA's name and namespace

**Comment by ahaessly** [comment]
Is there a work around for this issue? I'm currently using client auth mode.
More discussion in this slack thread: https://cloud-native.slack.com/archives/C01QW9QSSSK/p1720719356717919

**Comment by ahaessly** [comment]
Here is my deployment yaml:

[argo-server.yaml.txt](https://github.com/user-attachments/files/16184688/argo-server.yaml.txt)

**Comment by agilgur5** [comment]
> Is there a work around for this issue?

Per OP, the workaround is to manually set the namespace in the left-hand filters.
In your case though, you're not able to reach the Workflows List page to change the filters for some reason (still haven't quite figured out why). 

The other two workarounds are to change your URL to have the correct namespace instead of `undefined` or to similarly modify your `localStorage` `current_namespace` key to the namespace instead of `undefined`.

It being set to `undefined` seems to stem from around [this part of the UI code](https://github.com/argoproj/argo-workflows/blob/5aac5a8f61f4e8273d04509dffe7d80123ff67f5/ui/src/app/shared/utils.ts#L107), which I'd like to fix to return `default` instead, which the default. But fixing the claims to include the `serviceAccountNamespace` would be the root cause fix. Should probably have something soon for that.

> Here is my deployment yaml:

Thanks for your ultra small repro, hopefully I can repro with this. That suggests that my local env has additional config that makes me not hit this.

Btw, I removed most of the generated and default fields in this. Generally speaking, those are not useful and very distracting (they are substantially larger than the actual content), so please do not provide manifests with those to anyone; usually the raw manifest you input into your cluster is better than the output retrieved from the cluster. `--show-managed-fields false` will also remove part of that output.

**Comment by agilgur5** [comment]
> For `client`, we can derive the SA name and namespace from the `subject`. It would be more secure and less error-prone to pull from the SA itself though as a source of truth.

The token also has this information inside it. For example, here's [an SA token](https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc5dVprMUl0VHZkTXFpLWc4dVQwVkV1Y05UZ21XXzJvZjNuZi1iZkpfVW8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMuc2VydmljZS1hY2NvdW50LXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImplbmtpbnMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIyMGNjYzBjNS00NmNjLTQ3MjctYmUxMi1iZWY0ZTQ0ZTkxMjYiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6YXJnbzpqZW5raW5zIn0.QU__gnSIlI804GfNbfMkGDeVqQA32JAcfnOAFgrhTi7KM9FMohwHyTSq0Xuzh6p15L-TWD32_8YyIkExgqlfwcKbYM6UIL9XV6SW5Xail4qRab3IflLdxwkwKt8ukaj-pVSmk2YnQa0qSi3F3bK0uyexz4UbL3I94jmZ17Fng72aaE1851NDBz7Bh4h3KXJMeLzkcUMTsct0KhghE0OmHaek2LjcqySAoGpjJ9maDfEAuBMjBvceONnMhPw7JTOAxRrm9818hQH82xmZhaIbMWpticE-1yZYqzOjMME_qXGefHhCfFTv8RhC8o7LBxSkIomjmiGWXAHDVAhgpPOCpg) created with a long-lived Secret's payload:

```json
{
  "iss": "kubernetes/serviceaccount",
  "kubernetes.io/serviceaccount/namespace": "argo",
  "kubernetes.io/serviceaccount/secret.name": "jenkins.service-account-token",
  "kubernetes.io/serviceaccount/service-account.name": "jenkins",
  "kubernetes.io/serviceaccount/service-account.uid": "20ccc0c5-46cc-4727-be12-bef4e44e9126",
  "sub": "system:serviceaccount:argo:jenkins"
}
```

`kubernetes.io/serviceaccount/service-account.name` and `kubernetes.io/serviceaccount/service-account.uid` match the annotations on the k8s Secret.

And [one](https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc5dVprMUl0VHZkTXFpLWc4dVQwVkV1Y05UZ21XXzJvZjNuZi1iZkpfVW8ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzIwNzYzNjgyLCJpYXQiOjE3MjA3NjAwODIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJhcmdvIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMiLCJ1aWQiOiIyMGNjYzBjNS00NmNjLTQ3MjctYmUxMi1iZWY0ZTQ0ZTkxMjYifX0sIm5iZiI6MTcyMDc2MDA4Miwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFyZ286amVua2lucyJ9.k0SKX4yKga70R12ScI-mSpEWbwdRtlphxXB-drHNyxPyzz2fpur29ZzdcjE8-TlZE2fQrrV-MaqMBWqaD0TWsld0ILBYRYFOcIwuUOX8s611vqmpDejTT6oAroBEd4WSduP9WoxMsiN82EdDvDJeMpNpq8i-Nz8nYgfWe2VkqV_oYCenWKe9JC3QL1TOxdkqer2qgflGnIpTzSVf7y47vmdlqsS9GPbdXyCg4MdcyDnLgY2VoVQnymD22uTG3Ugp3dO3zhaS-puHMPDOa-_EbAn2MsqETrA8H8iKal-z4sx-R6MxN8fdBrrIkWZLZZD4i_EhBS5paFTNcXXq0-T90w) created from `kubectl create token` is a bit different: 

```json
{
  "aud": [
    "https://kubernetes.default.svc.cluster.local",
    "k3s"
  ],
  "exp": 1720763682,
  "iat": 1720760082,
  "iss": "https://kubernetes.default.svc.cluster.local",
  "kubernetes.io": {
    "namespace": "argo",
    "serviceaccount": {
      "name": "jenkins",
      "uid": "20ccc0c5-46cc-4727-be12-bef4e44e9126"
    }
  },
  "nbf": 1720760082,
  "sub": "system:serviceaccount:argo:jenkins"
}
```

**Comment by ahaessly** [comment]
I've tried removing and setting the namespace value in the local storage to the correct namespace. After logging in, if I try to go to the workflows or workflows templates page it resets the namespace in local storage to "undefined" and takes me back to the login page.

After switching to using a secret for the service account, I've had no problems with the UI.
