### ISSUE TITLE
port-forwarding to pod not working in quick start guide

### ISSUE THREAD

**Issue by AnaisUrlichs** [argoproj/argo-workflows#12665]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Following the quick start guide on kind cluster, whenever I try to port-forward to the UI and access it, I receive the following error message:
```
E0214 13:05:08.754012   18900 portforward.go:409] an error occurred forwarding 2746 -> 2746: error forwarding port 2746 to pod 81df1872f57a9acd034ef7e04f1f0740372d8f87896a2b798edc2c3686d552b9, uid : failed to execute portforward in network namespace "/var/run/netns/cni-516b7654-6e98-1e7b-e822-86c47258e243": read tcp4 127.0.0.1:37888->127.0.0.1:2746: read: connection reset by peer
Handling connection for 2746
E0214 13:05:08.761403   18900 portforward.go:347] error creating error stream for port 2746 -> 2746: EOF
error: lost connection to pod
```

https://argo-workflows.readthedocs.io/en/latest/quick-start/

Kind version:
```
kind version
kind v0.20.0 go1.20.5 darwin/arm64
```

```
❯ k get nodes
NAME                 STATUS   ROLES           AGE   VERSION
argo-control-plane   Ready    control-plane   14m   v1.27.3
```

### Version

v3.5.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Does not apply to a workflow, I am able to run the example workflow through the CLI
```

### Logs from the workflow controller

```text
Not applicable
```

### Logs from in your workflow's wait container

```text
Not applicable
```

**Comment by agilgur5** [comment]
Are your Argo Server pods all up & running fine?
i.e. `kubectl get pods` and `kubectl logs` on the Server pods

**Comment by agilgur5** [comment]
Hmm... are you running `kubectl port-forward` inside Docker or outside? Since Docker's network settings can affect that.
Although the error message seems to be from the Server, but worth checking.

The other thing I'd try is running a Pod in your cluster, `exec` into it, and `curl` the Server Pod to see how it responds. If you can get the HTML pages, JS, etc, the Server is working, suggesting the connection is the problem.

We use the manifests during our own testing and local dev env, but CI and I think most contributors use k3d (it's part of the devcontainer at least).

**Comment by agilgur5** [comment]
Could you also check your `kubectl` version?

**Comment by prateekatam** [comment]
@AnaisUrlichs were you able to fix this? I'm stuck at this now. Same logs on the argo-server pod.
