### ISSUE TITLE
SSO does not work with base_href other than /

### ISSUE THREAD

**Issue by aaron-arellano** [argoproj/argo-workflows#12660]
### Pre-requisites

- [X] I have double-checked my configuration
- [ ] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Enabling SSO for my deployment of argo server. 

Got SSO connection to work directly with Okta but noticed I was getting `400 Bad Request` responses from argo server because the set cookie was being filtered out by chrome. The message I was getting in the browser stated `this cookie was blocked because its path was not an exact match for a super directory of the request url's path`.

I noticed the cookie path followed the pattern `/{base_href}/oauth2` but the request url after the callback was `{argo_server_domain/oauth2/callback}`.
In my configuration  `{base_href}` was `argo-ui` so to resolve the issue I changed `{base_href}` back to `/` which enabled the cookie to get passed back to the argo server and succeeding my oauth flow.

![Screenshot 2024-02-12 at 12 06 06 PM](https://github.com/argoproj/argo-workflows/assets/52056643/bda7ba42-626f-41dd-ba20-dfe6fa9cf307)

![Screenshot 2024-02-12 at 12 09 26 PM](https://github.com/argoproj/argo-workflows/assets/52056643/758653ed-223b-4272-9422-a0c8fb241fa2)

Argo server SSO should be able to handle custom `{base_href}` values other than `/` so the cookie could get pass back to the argo server after redirecting from the OIDC provider.

### Version

v3.4.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
none
```

### Logs from the workflow controller

```text
none applicable, issue was on cookie rewrite and mismatch with `base_href`
```

### Logs from in your workflow's wait container

```text
none
```

**Comment by agilgur5** [comment]
> I noticed the cookie path followed the pattern `/{base_href}/oauth2` but the request url after the callback was `{argo_server_domain/oauth2/callback}`.

You can specify the [`sso.redirectUrl`](https://github.com/argoproj/argo-workflows/blob/66680f1c9bca8b47c40ce918b5d16714058647cb/docs/workflow-controller-configmap.yaml#L397) in your `workflow-controller-configmap`. Can add your `base_href` there

**Comment by agilgur5** [comment]
The default `redirectUrl` when not specified actually [takes into account `base_href` already](https://github.com/argoproj/argo-workflows/blob/66680f1c9bca8b47c40ce918b5d16714058647cb/server/auth/sso/sso.go#L388). Did you explicitly set it without your `base_href`?

**Comment by aaron-arellano** [comment]
this is not documented well at all. if this si the case I suggest documentation gets updated.

**Comment by agilgur5** [comment]
You're more than welcome to contribute to the documentation. To be clear, there is a single `workflow-controller-configmap.yaml` example that lists all of its possible config in entirety, and it is linked from [the SSO docs](https://argo-workflows.readthedocs.io/en/latest/argo-server-sso/#to-start-argo-server-with-sso).
