### ISSUE TITLE
Init container if no input artifacts needed

### ISSUE THREAD

**Issue by mweibel** [argoproj/argo-workflows#12728]
# Summary

We were wondering if the init container is needed if the workflow doesn't use input artifacts. Looking at the relevant code:
https://github.com/argoproj/argo-workflows/blob/61156f2eb2bafb795c8550233c11cb8a82c101e7/workflow/controller/workflowpod.go#L262..L265

It seems that the comment suggests it's not needed if no input artifacts are there. However there's no if guard around it. 

Looking at the change in this commit:
https://github.com/argoproj/argo-workflows/commit/62e0a8ce4e74d2e19f3a9c0fb5e52bd58a6b944b#diff-0cd2c830c5575d814bc0dccc445c0483f0ea0411b72862784714ed44c6806280L236

It seems that there initially was a guard but that got removed. Either the comment is outdated or the guard went missing while refactoring. 

Can anyone shed some light on this?

## Use Cases

When no input artifact is used, this would speed up deploying the actual container.

**Comment by Joibel** [comment]
That guard also created an init container if `woc.getContainerRuntimeExecutor() == common.ContainerRuntimeExecutorEmissary` which is the only executor these days.

#4925 added this, and documents why at https://github.com/argoproj/argo-workflows/blob/61156f2eb2bafb795c8550233c11cb8a82c101e7/workflow/executor/emissary/emissary.go#L26
```
The init container creates these files:
* `/var/run/argo/argoexec` The binary, copied from the `argoexec` image.
* `/var/run/argo/template` A JSON encoding of the template.
```
