### ISSUE TITLE
v3.5.5: Workflow does not complete even though Pod completed

### ISSUE THREAD

**Issue by panicboat** [argoproj/argo-workflows#12733]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Workflow is submitted and waits for a while, but does not finish.
Any Workflow looks the same.
When I check the status of the pod, it says Completed and the logs appear to be complete.
Also, even though the pod does not appear to be running in the UI, the logs can still be retrieved in the UI.
It appears that we can no longer track the status of the Pod.

![image](https://github.com/argoproj/argo-workflows/assets/4182311/666f6bff-d9af-44bf-ac77-61b937c5b801)
```console
01054855@CF0313 minikube % k get po -n develop-workflow                               
NAME                                                                READY   STATUS      RESTARTS   AGE
p3-deletion-policy-mask-or-delete-user-data-66xf6-main-2457154088   0/2     Completed   0          6h12m
shinkobetsu-check-expired-enrollments-1709510400-main-933938806     0/2     Completed   0          7h45m
wonderful-rhino-argosay-67614653                                    0/2     Completed   0          2m23s
01054855@CF0313 minikube % k logs -n develop-workflow wonderful-rhino-argosay-67614653
time="2024-03-04T07:43:36.342Z" level=info msg="capturing logs" argo=true
hello argo
time="2024-03-04T07:43:37.343Z" level=info msg="sub-process exited" argo=true error="<nil>"
```

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
metadata:
  name: wonderful-rhino
  namespace: develop-workflow
  labels:
    example: 'true'
spec:
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
```

### Logs from the workflow controller

```text
It's large, so I'm attaching it.
```

### Logs from in your workflow's wait container

```text
No resources found in argo namespace.
```

**Comment by panicboat** [comment]
[wonderful-rhino.log](https://github.com/argoproj/argo-workflows/files/14478890/wonderful-rhino.log)

**Comment by jswxstw** [comment]
> time="2024-03-04T07:43:46.402Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" namespace=develop-workflow workflow=wonderful-rhino

It seem like `wait` container has no access permission `TaskResult`, can you retrieve the log of `wait` container?
https://github.com/argoproj/argo-workflows/blob/7286d499a60e38e226365ac0300571963379e00c/workflow/executor/executor.go#L820-L828
> time="2024-03-04T07:43:46.402Z" level=info msg="pod reconciliation didn't complete, will retry" namespace=develop-workflow workflow=wonderful-rhino

`taskResultIncomplete` is always `false`, so `podReconciliation` shows it did not complete and is retrying indefinitely.
https://github.com/argoproj/argo-workflows/blob/7286d499a60e38e226365ac0300571963379e00c/workflow/controller/taskresult.go#L66-L73
@shuangkun It seems like a regression bug releated to #12537 .

**Comment by devcrops-official** [comment]
We were experiencing the same issue, we rollbacked to version `3.5.4`

**Comment by shuangkun** [comment]
Does the pod was set `common.AnnotationKeyReportOutputsCompleted, "true"`? @panicboat

**Comment by jswxstw** [comment]
I reproduced this bug by modify the `rbac` of `executor` as below:
```yaml
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - patch
```
logs of `wait` container:
```shell
time="2024-03-05T11:52:21.280Z" level=info msg="Starting Workflow Executor" version=untagged
time="2024-03-05T11:52:21.285Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2024-03-05T11:52:21.285Z" level=info msg="Executor initialized" deadline="2024-03-05 11:57:19 +0000 UTC" includeScriptOutput=false namespace=argo podName=wonderful-rhino templateName=argosay version="&Version{Version:untagged,BuildDate:2024-03-01T07:42:24Z,GitCommit:de0a271708cfa990e7232afdb83dbc8825933930,GitTag:untagged,GitTreeState:clean,GoVersion:go1.21.7,Compiler:gc,Platform:linux/amd64,}"
time="2024-03-05T11:52:21.290Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:argo:default\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"argo\""
time="2024-03-05T11:52:21.300Z" level=info msg="Starting deadline monitor"
time="2024-03-05T11:52:23.302Z" level=info msg="Main container completed" error="<nil>"
time="2024-03-05T11:52:23.302Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2024-03-05T11:52:23.302Z" level=info msg="No output parameters"
time="2024-03-05T11:52:23.302Z" level=info msg="No output artifacts"
time="2024-03-05T11:52:23.302Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: wonderful-rhino/wonderful-rhino/main.log"
time="2024-03-05T11:52:23.302Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2024-03-05T11:52:23.302Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=wonderful-rhino/wonderful-rhino/main.log path=/tmp/argo/outputs/logs/main.log
time="2024-03-05T11:52:23.312Z" level=info msg="Save artifact" artifactName=main-logs duration=9.81889ms error="<nil>" key=wonderful-rhino/wonderful-rhino/main.log
time="2024-03-05T11:52:23.312Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2024-03-05T11:52:23.312Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2024-03-05T11:52:23.313Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:argo:default\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"argo\""
time="2024-03-05T11:52:23.323Z" level=info msg="Alloc=6796 TotalAlloc=12606 Sys=20325 NumGC=5 Goroutines=10"
time="2024-03-05T11:52:23.325Z" level=warning msg="Non-transient error: workflowtaskresults.argoproj.io \"wonderful-rhino\" not found"
time="2024-03-05T11:52:23.325Z" level=error msg="executor error: workflowtaskresults.argoproj.io \"wonderful-rhino\" not found"
```
I think this issue may be `rbac` problem, rather than a regression bug, but need more information to confirm it.

**Comment by shuangkun** [comment]
Yes, we had the same idea, and I just reproduced it using this method.

**Comment by shuangkun** [comment]
> I reproduced this bug by modify the `rbac` of `executor` as below:
> 
> ```yaml
> rules:
> - apiGroups:
>   - argoproj.io
>   resources:
>   - workflowtaskresults
>   verbs:
>   - patch
> ```
> 
> logs of `wait` container:
> 
> ```shell
> time="2024-03-05T11:52:21.280Z" level=info msg="Starting Workflow Executor" version=untagged
> time="2024-03-05T11:52:21.285Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
> time="2024-03-05T11:52:21.285Z" level=info msg="Executor initialized" deadline="2024-03-05 11:57:19 +0000 UTC" includeScriptOutput=false namespace=argo podName=wonderful-rhino templateName=argosay version="&Version{Version:untagged,BuildDate:2024-03-01T07:42:24Z,GitCommit:de0a271708cfa990e7232afdb83dbc8825933930,GitTag:untagged,GitTreeState:clean,GoVersion:go1.21.7,Compiler:gc,Platform:linux/amd64,}"
> time="2024-03-05T11:52:21.290Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:argo:default\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"argo\""
> time="2024-03-05T11:52:21.300Z" level=info msg="Starting deadline monitor"
> time="2024-03-05T11:52:23.302Z" level=info msg="Main container completed" error="<nil>"
> time="2024-03-05T11:52:23.302Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
> time="2024-03-05T11:52:23.302Z" level=info msg="No output parameters"
> time="2024-03-05T11:52:23.302Z" level=info msg="No output artifacts"
> time="2024-03-05T11:52:23.302Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: wonderful-rhino/wonderful-rhino/main.log"
> time="2024-03-05T11:52:23.302Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
> time="2024-03-05T11:52:23.302Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=wonderful-rhino/wonderful-rhino/main.log path=/tmp/argo/outputs/logs/main.log
> time="2024-03-05T11:52:23.312Z" level=info msg="Save artifact" artifactName=main-logs duration=9.81889ms error="<nil>" key=wonderful-rhino/wonderful-rhino/main.log
> time="2024-03-05T11:52:23.312Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
> time="2024-03-05T11:52:23.312Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
> time="2024-03-05T11:52:23.313Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:argo:default\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"argo\""
> time="2024-03-05T11:52:23.323Z" level=info msg="Alloc=6796 TotalAlloc=12606 Sys=20325 NumGC=5 Goroutines=10"
> time="2024-03-05T11:52:23.325Z" level=warning msg="Non-transient error: workflowtaskresults.argoproj.io \"wonderful-rhino\" not found"
> time="2024-03-05T11:52:23.325Z" level=error msg="executor error: workflowtaskresults.argoproj.io \"wonderful-rhino\" not found"
> ```
> 
> I think this issue may be `rbac` problem, rather than a regression bug, but need more information to confirm it.

Yes, we had the same idea, and I just reproduced it using the method.

**Comment by panicboat** [comment]
My apologies, The environment at the time of the report has been reverted to v3.5.4, so it will take some time to confirm.

**Comment by panicboat** [comment]
The environment at the time of the report has reverted to v3.5.4.
Can I use data acquired in a different environment?
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: main
    workflows.argoproj.io/node-id: wonderful-rhino-67614653
    workflows.argoproj.io/node-name: wonderful-rhino(0)
    workflows.argoproj.io/outputs: '{"artifacts":[{"name":"main-logs","s3":{"key":"wonderful-rhino/wonderful-rhino-argosay-67614653/main.log"}}]}'
    workflows.argoproj.io/report-outputs-completed: "true"
```

```console
% kubectl logs wonderful-rhino-argosay-67614653 --container wait
time="2024-03-06T02:52:35.289Z" level=info msg="Starting Workflow Executor" version=v3.5.5
time="2024-03-06T02:52:35.291Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2024-03-06T02:52:35.291Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=default podName=wonderful-rhino-argosay-67614653 templateName=argosay version="&Version{Version:v3.5.5,BuildDate:2024-02-29T21:00:43Z,GitCommit:c80b2e91ebd7e7f604e88442f45ec630380effa0,GitTag:v3.5.5,GitTreeState:clean,GoVersion:go1.21.7,Compiler:gc,Platform:linux/arm64,}"
time="2024-03-06T02:52:35.294Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:default:argo\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"default\""
time="2024-03-06T02:52:35.301Z" level=info msg="Starting deadline monitor"
time="2024-03-06T02:52:46.308Z" level=info msg="Main container completed" error="<nil>"
time="2024-03-06T02:52:46.308Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2024-03-06T02:52:46.308Z" level=info msg="No output parameters"
time="2024-03-06T02:52:46.308Z" level=info msg="No output artifacts"
time="2024-03-06T02:52:46.309Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: wonderful-rhino/wonderful-rhino-argosay-67614653/main.log"
time="2024-03-06T02:52:46.314Z" level=info msg="Creating minio client using static credentials" endpoint=s3.amazonaws.com
time="2024-03-06T02:52:46.314Z" level=info msg="Saving file to s3" bucket=panicboat-sandbox-723535945756 endpoint=s3.amazonaws.com key=wonderful-rhino/wonderful-rhino-argosay-67614653/main.log path=/tmp/argo/outputs/logs/main.log
time="2024-03-06T02:52:46.508Z" level=info msg="Save artifact" artifactName=main-logs duration=198.899084ms error="<nil>" key=wonderful-rhino/wonderful-rhino-argosay-67614653/main.log
time="2024-03-06T02:52:46.508Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2024-03-06T02:52:46.508Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2024-03-06T02:52:46.510Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:default:argo\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"default\""
time="2024-03-06T02:52:46.522Z" level=info msg="Alloc=11144 TotalAlloc=17418 Sys=24421 NumGC=4 Goroutines=10"
time="2024-03-06T02:52:46.523Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" error="workflowtaskresults.argoproj.io \"wonderful-rhino-67614653\" is forbidden: User \"system:serviceaccount:default:argo\" cannot patch resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"default\""
time="2024-03-06T02:52:46.530Z" level=info msg="Deadline monitor stopped"
time="2024-03-06T02:52:46.530Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
```

**Comment by shuangkun** [comment]
Thanks. Does this workflow works well? I see the pod has label AnnotationKeyReportOutputsCompleted. Wait container only 
just missing create rbac should work well.

**Comment by panicboat** [comment]
This workflow was also not completed.

**Comment by jswxstw** [comment]
> Thanks. Does this workflow works well? I see the pod has label AnnotationKeyReportOutputsCompleted. Wait container only just missing create rbac should work well.

We were investigating in the wrong direction. The main issue was that the workflow example provided in the issue was not the actual one being executed.
This bug can be reproduced by the following workflow:
```yaml
metadata:
  name: wonderful-rhino
  labels:
    example: 'true'
spec:
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      retryStrategy:
        affinity: {}
        limit: 3
        retryPolicy: Always
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: argoproj/argosay:v2
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
```

**Comment by jswxstw** [comment]
@shuangkun `pod.name` does not equal to `nodeID` in `PodNameV2`.
https://github.com/argoproj/argo-workflows/blob/c80b2e91ebd7e7f604e88442f45ec630380effa0/workflow/controller/operator.go#L1131
https://github.com/argoproj/argo-workflows/blob/c80b2e91ebd7e7f604e88442f45ec630380effa0/workflow/controller/operator.go#L1388-L1396

**Comment by shuangkun** [comment]
Yes, I found and fixed this problem before.

**Comment by shuangkun** [comment]
> @shuangkun `pod.name` does not equal to `node.ID` in `PodNameV2`.
> 
> https://github.com/argoproj/argo-workflows/blob/c80b2e91ebd7e7f604e88442f45ec630380effa0/workflow/controller/operator.go#L1131
> 
> 
> https://github.com/argoproj/argo-workflows/blob/c80b2e91ebd7e7f604e88442f45ec630380effa0/workflow/controller/operator.go#L1388-L1396
> 
> Why release-v3.5.5 missed this line?
> 
> https://github.com/argoproj/argo-workflows/blob/e00abd1ded9e8f4787093b84f6cb26ee0870ec7c/workflow/controller/operator.go#L1394

Yes, I found and fixed this problem before.

**Comment by shuangkun** [comment]
@isubasinghe  Can you have a look for this?  I submitted a PR before, I find this line is right(podName -> nodeId) I https://github.com/argoproj/argo-workflows/blob/v3.5.5/pkg/apis/workflow/v1alpha1/workflow_types.go#L1943 , but this line is miss in 3.5.5. https://github.com/argoproj/argo-workflows/blob/e00abd1ded9e8f4787093b84f6cb26ee0870ec7c/workflow/controller/operator.go#L1394   Thanks.

**Comment by agilgur5** [comment]
Thanks for investigating @shuangkun and @jswxstw !

I ran a diff and, as suspected, there would've been a merge conflict on that line:
```diff
# git diff release-3.5 main -- workflow/controller/operator.go
# [...]
-               woc.log.Warn("workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/")
-               resultName := woc.nodeID(pod)
+               woc.log.Warn("workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/")
+               resultName := pod.GetName()
# [...]
```

So it probably got resolved incorrectly unfortunately. I also missed that when I was [checking Isitha's work](https://github.com/argoproj/argo-workflows/issues/11997#issuecomment-1970241749) -- that one's definitely a hard one to manually detect while parsing through large diffs.

@shuangkun could you file a PR to the `release-3.5` branch to fix this? I'm also wondering (as I did [on Slack](https://cloud-native.slack.com/archives/C0510EUH90V/p1709754537796109?thread_ts=1709512568.671069&cid=C0510EUH90V)) if a test should've caught that bug

**Comment by shuangkun** [comment]
> Thanks for investigating @shuangkun and @jswxstw !
> 
> I ran a diff and, as suspected, there would've been a merge conflict on that line as there were other changes around it:
> 
> ```diff
> # git diff release-3.5 main -- workflow/controller/operator.go
> # [...]
> -               woc.log.Warn("workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/")
> -               resultName := woc.nodeID(pod)
> +               woc.log.Warn("workflow uses legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/")
> +               resultName := pod.GetName()
> # [...]
> ```
> 
> So the merge conflict probably got resolved incorrectly unfortunately. I also missed that when I was [checking Isitha's work](https://github.com/argoproj/argo-workflows/issues/11997#issuecomment-1970241749) -- that one's definitely a hard one to manually detect while parsing through large diffs.
> 
> @shuangkun could you file a PR to the `release-3.5` branch to fix this? I'm also wondering (as I did [on Slack](https://cloud-native.slack.com/archives/C0510EUH90V/p1709754537796109?thread_ts=1709512568.671069&cid=C0510EUH90V)) if a test should've caught that bug

https://github.com/argoproj/argo-workflows/pull/12755/files  Thanks. I add a pr.  Do you mean we should add a test to prevent this from happening? If So, I can add a test.

**Comment by Guillermogsjc** [comment]
this really is solved by updating Role associated to serviceAccount that are linked to argo nodes with this https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/ (**requirement for >= v3.4**)

just adding this rule to the role linked to every single SA that is being used by argo workflows, fixes everything.

```
- apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
```

to all the roles being used, unlocks this "bug".

Regarding to documentation, it looks more than there is needed to specify the need of inclusion of this rule everywhere, more than rolling back code.

By the way, the default `argo-role` in `https://github.com/argoproj/argo-workflows/releases/download/${ARGO_VERSION}/install.yaml`, lacks too the rule.
     
 Probably a missalignment between doc, the default installation manifest, and this upgrade have been made from v3.4?

**Comment by shuangkun** [comment]
> Probably a missalignment between doc, the default installation manifest, and this upgrade have been made from

Yes, it is now possible to solve the problem by increasing permissions so that executors use workflowtasks instead of pod annotations to report output.

**Comment by jswxstw** [comment]
> By the way, the default `argo-role` in `https://github.com/argoproj/argo-workflows/releases/download/${ARGO_VERSION}/install.yaml`, lacks too the rule.

This rule is in `executor` role if use `namespace-install`.
However, this issue shows that `cluster-install` is used, so this rule is in `admin` clusterrole and there is a need to bind it.

**Comment by agilgur5** [comment]
> Regarding to documentation, it looks more than there is needed to specify the need of inclusion of this rule everywhere, more than rolling back code.

The PR doesn't roll back code, it fixes a merge conflict that was incorrectly resolved in 3.5.5. 

There were some small changes to the docs coming out of #12391, specifically #12445 and then #12680. I hope that is enough, but perhaps it needs to be referenced in other places too.
Per https://github.com/argoproj/argo-workflows/issues/12391#issuecomment-1946909175, the RBAC was always listed as needed in the docs, but prior to 3.5.2, some simple steps could bypass it. 

> > By the way, the default `argo-role` in `https://github.com/argoproj/argo-workflows/releases/download/${ARGO_VERSION}/install.yaml`, lacks too the rule.
> 
> This rule is in `executor` role if use `namespace-install`. However, this issue shows that `cluster-install` is used, so this rule is in `admin` clusterrole and there is a need to bind it.

I think there's a misunderstanding here, only the quick start manifests contain [a Role for](https://github.com/argoproj/argo-workflows/blob/20ece9cb6c4dfa1a6900a30d58304f32bf8e93b6/manifests/quick-start/base/executor/emissary/executor-role.yaml#L4) the Executor.
Neither the `cluster-install` (which is `install.yaml`) nor the `namespace-install` provide a Role for the Executor. That is up to the user to set-up for multiple reasons. The `workflowtaskresults` RBAC is the _minimum_ required, but more could be necessary depending on your use-case (e.g. creating a k8s resource). In the quick start, the Role is [bound](https://github.com/argoproj/argo-workflows/blob/20ece9cb6c4dfa1a6900a30d58304f32bf8e93b6/manifests/quick-start/base/executor-default-rolebinding.yaml#L11) to the `default` SA, but in a production install, `default` shouldn't be used and what SA a user uses is not known ahead of time by the manifests. (Note that the Helm charts, which can be configured, have an [optional Executor SA](https://github.com/argoproj/argo-helm/tree/argo-workflows-0.40.14/charts/argo-workflows#serviceaccount-for-workflow-spec))
The `argo-role` from the `cluster-install` is the Controller's Role, it [binds](https://github.com/argoproj/argo-workflows/blob/20ece9cb6c4dfa1a6900a30d58304f32bf8e93b6/manifests/cluster-install/workflow-controller-rbac/workflow-controller-rolebinding.yaml#L11) to the [`argo` SA](https://github.com/argoproj/argo-workflows/blob/20ece9cb6c4dfa1a6900a30d58304f32bf8e93b6/manifests/base/workflow-controller/workflow-controller-sa.yaml#L4).

**Comment by agilgur5** [comment]
> #12755. Thanks. I add a pr. Do you mean we should add a test to prevent this from happening? If So, I can add a test.

@shuangkun yes I meant adding a regression test, specifically checking that the `nodeID` is being used. Does `pod.GetName` instead of `nodeID` not cause other issues?

**Comment by agilgur5** [comment]
@shuangkun following up on the [above](https://github.com/argoproj/argo-workflows/issues/12733#issuecomment-1992732678) regarding tests
