### ISSUE TITLE
 Issue when validating Workflow with golang package

### ISSUE THREAD

**Issue by Jahadul-Rakib** [argoproj/argo-workflows#12731]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

**I want to validate a workflow from workflow struct and use a function from validate package,**
**Code:**
```go
import (
	"github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1"
	"github.com/argoproj/argo-workflows/v3/pkg/client/clientset/versioned/fake"
	"github.com/argoproj/argo-workflows/v3/workflow/templateresolution"
	"github.com/argoproj/argo-workflows/v3/workflow/validate"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

func (r *WorkFlow) ValidateWorkflow(workflow *v1alpha1.Workflow) error {
	var workFlowClientSet = fake.NewSimpleClientset()
	var wfTmplGetter = templateresolution.WrapWorkflowTemplateInterface(workFlowClientSet.ArgoprojV1alpha1().WorkflowTemplates(v1.NamespaceDefault))
	var cwfTmplGetter = templateresolution.WrapClusterWorkflowTemplateInterface(workFlowClientSet.ArgoprojV1alpha1().ClusterWorkflowTemplates())
	err := validate.ValidateWorkflow(wfTmplGetter, cwfTmplGetter, workflow, validate.ValidateOpts{})
	if err != nil {
		return err
	}
	return nil
}
```
**but when try to run this function then throw error.**
**Error:**
```
# k8s.io/client-go/transport/spdy
../../go/pkg/mod/k8s.io/client-go@v0.24.3/transport/spdy/spdy.go:46:25: assignment mismatch: 1 variable but spdy.NewRoundTripperWithConfig returns 2 values
# k8s.io/client-go/applyconfigurations/meta/v1
../../go/pkg/mod/k8s.io/client-go@v0.24.3/applyconfigurations/meta/v1/unstructured.go:64:38: cannot use doc (variable of type *"github.com/google/gnostic/openapiv2".Document) as *"github.com/google/gnostic-models/openapiv2".Document value in argument to proto.NewOpenAPIData
```

### Version

v.3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
`

`
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
> * [x] I can confirm the issue exists when I tested with `:latest`

> v.3.3.5

You checked that you were using `latest`, but v3.3.5 is an old, unsupported version.

**Comment by Jahadul-Rakib** [comment]
> > * [x]  I can confirm the issue exists when I tested with `:latest`
> 
> > v.3.3.5
> 
> You checked that you were using `latest`, but v3.3.5 is an old, unsupported version.
> 
> > but when try to run this function then throw error.
> 
> Also is this a run-time error? Not a build-time error?

in go package repository v3.5.5 is the latest, i also use this one. its run-time error

**Comment by agilgur5** [comment]
Looks like you solved it? Please add how you did so for other readers who may search the error and land here

**Comment by Jahadul-Rakib** [comment]
> Looks like you solved it? Please add how you did so for other readers who may search the error and land here

thank you for your kind response,
Basically, no issue in sdk. unexpectedly my ide upgrade `k8s.io/apimachinery v0.24.3` library version to upper version v0.29.0. which is not compatible with sdk version 3.5.5. when i downgrade sdk expected version `v0.24.3` then its fixed.
