### ISSUE TITLE
TestHTTPArtifactDriver_Load intermittently fails on the windows CI suite

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-workflows#12744]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

- https://github.com/argoproj/argo-workflows/actions/runs/8151810452/job/22280270235
- https://github.com/argoproj/argo-workflows/actions/runs/8160644079/job/22307673564
- https://github.com/argoproj/argo-workflows/actions/runs/8444739966/job/23130832000?pr=12847

```
--- FAIL: TestHTTPArtifactDriver_Load (0.00s)
    --- FAIL: TestHTTPArtifactDriver_Load/Found (0.00s)
        http_test.go:26: 
            	Error Trace:	D:/a/argo-workflows/argo-workflows/workflow/artifacts/http/http_test.go:26
            	Error:      	Received unexpected error:
            	            	open /tmp/found: The system cannot find the path specified.
            	Test:       	TestHTTPArtifactDriver_Load/Found
```

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
n/a
```

**Comment by blkperl** [comment]
Another failure: https://github.com/argoproj/argo-workflows/actions/runs/8444739966/job/23130832000?pr=12847

**Comment by agilgur5** [comment]
cc @mweibel who added the Windows unit tests in #12011. Also for reference, the unfinished #12071

**Comment by mweibel** [comment]
ah yeah, sorry about that - I didn't get to working on that in a while. I hope I can find some time soon for it. Will then also take a look at this failure.
