### ISSUE TITLE
local image build: support arm and amd64

### ISSUE THREAD

**Issue by heidongxianhua** [argoproj/argo-workflows#12750]
# Summary

What change needs making?
Now， if we build controller image, the imgae Architecture will be same as your machine, it can not use on arm and amd64 at the same time. so we want to change.
## Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by Joibel** [comment]
Are you asking for the ability to choose which single architecture to build for, or the ability to build multiple architectures into a single image with manifest?
Is this just for the docker images?
As a temporary workaround for building images you can set one or more platforms in the Makefile with
```
%-image:
	[ ! -e dist/$* ] || mv dist/$* .
	docker buildx build \
		--platform linux/amd64,linux/arm64 \
		--build-arg GIT_COMMIT=$(GIT_COMMIT) \
		--build-arg GIT_TAG=$(GIT_TAG) \
		--build-arg GIT_TREE_STATE=$(GIT_TREE_STATE) \
		-t $(IMAGE_NAMESPACE)/$*:$(VERSION) \
		--target $* \
		--load \
		 .
```
The critical changed line there being `--platform`.

We'd accept a PR for formalizing this if you want to do it, so long as it only built for the "same as your machine" in the default case. You could set an environment variable to override this behavior.

**Comment by heidongxianhua** [comment]
> Are you asking for the ability to choose which single architecture to build for, or the ability to build multiple architectures into a single image with manifest? Is this just for the docker images? As a temporary workaround for building images you can set one or more platforms in the Makefile with
> 
> ```makefile
> %-image:
> 	[ ! -e dist/$* ] || mv dist/$* .
> 	docker buildx build \
> 		--platform linux/amd64,linux/arm64 \
> 		--build-arg GIT_COMMIT=$(GIT_COMMIT) \
> 		--build-arg GIT_TAG=$(GIT_TAG) \
> 		--build-arg GIT_TREE_STATE=$(GIT_TREE_STATE) \
> 		-t $(IMAGE_NAMESPACE)/$*:$(VERSION) \
> 		--target $* \
> 		--load \
> 		 .
> ```
> 
> The critical changed line there being `--platform`.
> 
> We'd accept a PR for formalizing this if you want to do it, so long as it only built for the "same as your machine" in the default case. You could set an environment variable to override this behavior.

yeah, I have test it locally, when I add the arg `--platform linux/amd64,linux/arm64`, it will failed with error `ERROR: docker exporter does not currently support exporting manifest lists`, It seems that the limitation is combination of `--load` and multiple values to `--platform`. Eg.` --platform linux/arm64 --load` works fine. So I solve it according to https://github.com/docker/buildx/issues/59 to set `* enable "User containerd for pulling and storing images" in Settings > Features in development > Beta features`, it works but need more time to build images. And I will give a PR here.https://github.com/argoproj/argo-workflows/pull/12754
