### ISSUE TITLE
CLI: option to append timestamp prefix to workflow name when workflowtemplate is submitted

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#12777]
currently if u have deployed a workflowtemplate and then try to submit a run of it via the cli it will generate a workflow name with 5 random chars on the end of it. would like that it generates a workflow name with the timestamp in the name too. 2 benefits: easy to see from the name when it was submitted, less chance of a name collision from 10000s of runs

**Comment by tczhao** [comment]
make `generateName` configurable does sound like an awesome idea

**Comment by tooptoop4** [comment]
https://argo-workflows.readthedocs.io/en/latest/cli/argo_submit/ has option like --name

**Comment by agilgur5** [comment]
#7900 seems like a more generic option that would supersede this.
