### ISSUE TITLE
`look-up entrypoint/cmd for image` `unexpected status code 401 Unauthorized: Auth failed`

### ISSUE THREAD

**Issue by om3171991** [argoproj/argo-workflows#12786]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Hello,

We are getting a below error after upgrading to v3.5.5

```
failed to look-up entrypoint/cmd for image, you must either explicitly specify the command, or list the image's command in the index: https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary: unexpected status code 401 Unauthorized: Auth failed.
```

We have already gone through https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary and other alternative defined in previous threads & PRs. Nothing helped.

https://github.com/argoproj/argo-workflows/pull/8345

As per above PR, below doc is not clear as well : like which image ? Do we need to do for all image with which we are having issue etc

> ### Image Index
> If the emissary cannot determine which command to run, because you did not specify it in your workflow spec, then it will look it up in the **image index**. This is nothing more fancy than a [configuration item](workflow-controller-configmap.yaml).

We are using container type workflow with args defined in workflow spec and used images have defined both CMD & ENTRYPOINT.

If we define COMMAND with workflow, it works but our program logic breaks.

Please help.

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
NA
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by om3171991** [comment]
This is breaking our production workflows

**Comment by agilgur5** [comment]
Seems to be a duplicate of this [Slack thread](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1710230401615689?thread_ts=1710230401.615689&cid=C01QW9QSSSK)


> ```
> status code 401 Unauthorized: Auth failed.
> ```

This sounds like you may not have the proper `imagePullSecret` to your container image registry?

**Comment by illomi7** [comment]
Hi,
we encountered the same problem during the update on the new cluster.
We upgraded from an EKS cluster version 1.28 to EKS cluster version 1.31 and installed argo with the same spec as the old cluster.
After the installation we noticed that all workflows fail with the following error

> failed to look-up entrypoint/cmd for image \"<aws-acc-id>.dkr.ecr.eu-west-1.amazonaws.com/<image>:<tag>\", you must either explicitly specify the command, or list the image's command in the index: https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary: GET https://<aws-acc-id>.dkr.ecr.eu-west-1.amazonaws.com/v2/<image>/manifests/<tag>: unexpected status code 401 Unauthorized: Not Authorized

Does anyone have the same problem or has any suggestion?

**Comment by tooptoop4** [comment]
are u able to start a pod outside of argo with same image? did EKS 1.30 work?

**Comment by illomi7** [comment]
Yes everything except  the argo workflow is working but maybe i figured it out the issue.
Basically what i think is happenning is that argo cannot get the pull secret stored in the node by eks and so it cannot pull the private  image to determinate the entrypoint command.
So i try to put the `container.command:` field and now everythings work fine.
The workaround is a bit a problem becouse now i need to update all the workflow using the command value, anyone have the same problem?

**Comment by Prabhdeep-Singh24** [comment]
@illomi7 Can you describe your workaround a bit better? I am seeing this same issue in a new cluster I created about 2 weeks ago on AWS

**Comment by yuzhouliu9** [comment]
Encountered the exact same issue.
Workflow ran fine on v3.4.5. Then after upgrading to v3.5.12
```
failed to look-up entrypoint/cmd for image "<private_repo>", you must either explicitly specify the command, or list the image's command in the index: https://argo-workflows.readthedocs.io/en/release-3.5/workflow-executors/#emissary-emissary: GET <private_image>: unexpected status code 401 Unauthorized: Not Authorized
```

**Comment by Virviil** [comment]
Yep, it's crazy bug. One either should give to argo-workflows controller policies to read from ECR or explicitly specify command. 

Both solutions are not perfect

**Comment by fguendling** [comment]
Please upvote if you think this issue should be reopened. It causes redundancy in our case (we specify the command in an ENTRYPOINT instruction in our Dockerfile and then we have to do it again in the Argo Workflows container template). This is not optimal.

Thanks to everyone who contributed here. We managed to solve this issue, with the help of the answers here.
