### ISSUE TITLE
Support displaying line numbers in object-editor

### ISSUE THREAD

**Issue by ishivanshgoel** [argoproj/argo-workflows#12807]
# Summary
Adding support for displaying the line number would enhance the user experience, as it would aid in debugging

### What change needs making?
Needs to pass `on` instead of `off` as a value for `lineNumbers` key/just remove the `off` as be default it will be `on` in `SuspenseMonacoEditor`. 

### When would you use this?
<p>Useful for debugging</p>

Following is the reference to the codebase:
[`lineNumbers: 'off'`](https://github.com/argoproj/argo-workflows/blob/5b3909b9567a5c6fc4fef81ac0785cfddbffb291/ui/src/app/shared/components/object-editor.tsx#L124)

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by agilgur5** [comment]
Looking at the `git blame`, that line originates from #4470, which is the first commit that moved the UI into this repo (and Monaco appears to not have existed prior to that in https://github.com/argoproj/argo-ui/pull/53). So there's no rationale listed for why it's off.

Would you like to test removing that line, ensure everything still works, and submit a PR with screenshots?

**Comment by ishivanshgoel** [comment]
@agilgur5 sure, let me try. I would need sometime for setting up project locally for development, will refer to the contributing guide.
