### ISSUE TITLE
Add update flag in the create command

### ISSUE THREAD

**Issue by shuangkun** [argoproj/argo-workflows#12823]
# Summary

Add update flag in the create command.

## Use Cases

User want to use 1 command to create or update an resource(cron wf、workflow template、clusterworkflowtemplate). 

_edited by agilgur5_: Source https://github.com/argoproj/argo-workflows/pull/12803#pullrequestreview-1945224384

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by agilgur5** [comment]
> Add update flag in the create command.

I don't think this should be done. `create` and `update` are two separate `verbs` in k8s and CRUD conventions more generically. We should not be re-inventing the wheel and breaking existing conventions.

Not to mention `create --update` is actually longer to type than `update`, so I do not see any benefit in this, only cons.

> User want to use 1 command to create or update an resource

It sounds like you might be looking for `apply`, for example `kubectl apply`, which is a third, separate command

**Comment by jswxstw** [comment]
I believe that supporting version control for workflows and templates is crucial, rather than directly updating existing objects, which can be a risky operation.

**Comment by shuangkun** [comment]
> I believe that supporting version control for workflows and templates is crucial, rather than directly updating existing objects, which can be a risky operation.

The update action should still have many uses. If think the risk is high, can not use this API. Version control may be a more advanced use and requires more design.

**Comment by jswxstw** [comment]
> The update action should still have many uses.

Completely agree. In fact, we have implemented our own logic for updating workflows based on the Kubernetes client to enable intervention operations such as step skipping and parameter updates.

**Comment by agilgur5** [comment]
As I wrote [above](https://github.com/argoproj/argo-workflows/issues/12823#issuecomment-2010126196) and elsewhere, I can agree to an `apply` command, but `create --update` seems like a confusing anti-pattern to me
