### ISSUE TITLE
UI: Copy from workflow logs using Ctrl-C doesn't work on Linux & Windows

### ISSUE THREAD

**Issue by Joibel** [argoproj/argo-workflows#12947]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

This is a reproduction on firefox 124.0.2 on linux/gnome/wayland of a bug report from windows. I have reproduced it using other window managers and browsers on linux too. I have been informed this works fine on MacOS, which may be down to copy being Cmd+C rather than Ctrl-C there.

In pod logs in the user interface is it not possible to use Ctrl-C to copy the logs. This is demonstrated here:

https://drive.google.com/file/d/1PGk6Y7RRyvg4vppxuhpJUYcjubYf-A91/view?usp=drive_link

Right click copy works.

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Not relevant
```

### Logs from the workflow controller

```text
Not relevant
```

### Logs from in your workflow's wait container

```text
Not relevant
```

**Comment by agilgur5** [comment]
> I have been informed this works fine on MacOS, which may be down to copy being Cmd+C rather than Ctrl-C there.

Can confirm, works fine on my Mac

> Right click copy works.

This would suggest that `Ctrl` is being captured by something and not handled, since copying still works and `Cmd+C` works on Mac. I don't believe we have any such code in this part of the UI, so I would wonder if this might be upstream in [`xterm`](https://github.com/xtermjs/xterm.js)

**Comment by Adrien-D** [comment]
> > so I would wonder if this might be upstream in [`xterm`](https://github.com/xtermjs/xterm.js)
> 
> We're also on an older version of `xterm`, so probably first thing I would recommend is [upgrading it](https://github.com/xtermjs/xterm.js/releases)

An existing issue on this topic is still open on xterm project https://github.com/xtermjs/xterm.js/issues/2478 , and seems to be a desired behavior, so no real need of updating the lib.

I implemented [a workaround](https://github.com/xtermjs/xterm.js/issues/2478#issuecomment-1002371588). You can find the related Issue [here](https://github.com/argoproj/argo-ui/issues/557) and PR [here](https://github.com/argoproj/argo-ui/pull/558)
