### ISSUE TITLE
managed identity with server SSO

### ISSUE THREAD

**Issue by Universe07** [argoproj/argo-workflows#13030]
# Summary

I noticed that currently there's only client-secret solution for Argo Server SSO. Is there plans for enabling managed identity in Argo Server SSO?

## Use Cases

We are currently deprecating client secrets and we noticed that one client secret we are using is for Argo Server SSO. 

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
Can you elaborate on what you mean by "managed identity"? That's not a standardized term.

Azure appears to have a [managed identities](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview) feature that you might be referring to?
