### ISSUE TITLE
Option to disable writing k8s events at workflow level

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#13042]
# Summary

Environment variable/config to stop writing k8s events

## Use Cases

When would you use this? When i want to stop etcd filling up

These parts of the code are writing k8s events which end up being stored in etcd:
https://github.com/argoproj/argo-workflows/blob/0bfaea64b88a4b4f0b79c389f63ea2ce326a747e/workflow/controller/operator.go#L2339-L2344
https://github.com/argoproj/argo-workflows/blob/0bfaea64b88a4b4f0b79c389f63ea2ce326a747e/workflow/controller/operator.go#L783

With a lot of workflows being churned through these events add a lot of storage pressure to etcd. At the same time i have not found these events useful as i can always look at logs in the controller pod

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/blob/main/docs/workflow-controller-configmap.yaml#L36-L42

**Comment by terrytangyuan** [comment]
```
  # Whether or not to emit events on node completion. These can take a up a lot of space in
  # k8s (typically etcd) resulting in errors when trying to create new events:
  # "Unable to create audit event: etcdserver: mvcc: database space exceeded"
  # This config item allows you to disable this.
  # (since v2.9)
  nodeEvents: |
    enabled: true
```

**Comment by tooptoop4** [comment]
@terrytangyuan i already have that as false but it still sends events!!
