### ISSUE TITLE
GODEBUG should not be sent in pod create

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#13050]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

looking at k8s audit server logs for pod creation it shows many things, including below snippet
```yaml
         "command": [
            "argoexec",
            "wait",
            "--loglevel",
            "info",
            "--log-format",
            "text"
          ],
          "env": [
            {
              "name": "ARGO_POD_NAME",
              "valueFrom": {
                "fieldRef": {
                  "apiVersion": "v1",
                  "fieldPath": "metadata.name"
                }
              }
            },
            {
              "name": "ARGO_POD_UID",
              "valueFrom": {
                "fieldRef": {
                  "apiVersion": "v1",
                  "fieldPath": "metadata.uid"
                }
              }
            },
            {
              "name": "GODEBUG",
              "value": "x509ignoreCN=0"
            },
            {
              "name": "ARGO_WORKFLOW_NAME",
```

GODEBUG variable seems useless but consumes space in etcd

### Version

3.4.11

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
> GODEBUG variable seems useless but consumes space in etcd

It had a use-case in the past. I already removed it in https://github.com/argoproj/argo-workflows/pull/12610, it just hasn't been backported given that it's not a fix
