### ISSUE TITLE
Pagination in the workflow page is disabled

### ISSUE THREAD

**Issue by kangyanzhou** [argoproj/argo-workflows#13090]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

We have about 10k+ archived workflows in the dev database, and I'm trying to upgrade from v3.4.10 to v3.5.6.

After the upgrade the `next page` button in the workflow page is disabled with warning `Workflows cannot be globally sorted when paginated`. The only way for me to view more workflows is to choose a larger limit. Is there a new setting I need to apply in v3.5?

### Version

v3.5.6

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by kangyanzhou** [comment]
The argo server log has no error, although I can constantly see warnings regarding slow query.

**Comment by agilgur5** [comment]
Likely a duplicate of #11715, which should be resolved in 3.5.7, which I was hoping to release this weekend

**Comment by kangyanzhou** [comment]
> Likely a duplicate of #11715, which should be resolved in 3.5.7, which I was hoping to release this weekend

Thanks!

**Comment by agilgur5** [comment]
[v3.5.7](https://github.com/argoproj/argo-workflows/releases/tag/v3.5.7) is released, which contains a backport of #12912 / #13021 that fixed #11715.

Please try it out and let us know if it's fixed now.

**Comment by kangyanzhou** [comment]
Yes it's fixed now. Thanks!
