### ISSUE TITLE
Specify external artifacts repo with azure blob

### ISSUE THREAD

**Issue by patialashahi31** [argoproj/argo-workflows#13099]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

In current examples we can see [https://argo-workflows.readthedocs.io/en/latest/configure-artifact-repository/](url) that we can specify external artifact repo for s3 and gcs. I have configured azure as a default artifact repo
So the use case is to refer the other's storage account blob at the run time , while running the workflow. I have mine account secret keys but what info I need to access other storage account blob?

`                    accountKeySecret:
                      name: secret
                      key: key`

### Version

3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Example shouldn't be needed. Explained via docs
```

### Logs from the workflow controller

```text
NA
```

### Logs from in your workflow's wait container

```text
403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nERROR CODE: AuthenticationFailed
```

**Comment by Joibel** [comment]
Is this a request to document how to use Azure blob storage as a workflows artifact repository?
