### ISSUE TITLE
DOM text reinterpreted as HTML in `workflow-logs-viewer.tsx`

### ISSUE THREAD

**Issue by jessicacunha** [argoproj/argo-workflows#13103]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

DOM text is reinterpreted as HTML without escaping meta-characters.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by jessicacunha** [comment]
I`m working in this issue

**Comment by agilgur5** [comment]
I assume this is related to the other two CodeQL issues filed within the same few hours, #13105 and #13104. 

You didn't cite your sources here though nor list the specific line number. Please cite your sources and directly quote your sources. Also I'm not sure who organized these issues, but it would have made sense to notify organizations like Argo before filing issues, as well as list that they are part of an organized effort in the issues.
At least one of these has also been a very obvious false positive, which is a poor use of limited maintainer time.

I also don't see any line number in [`workflow-logs-viewer.tsx`](https://github.com/argoproj/argo-workflows/blob/f492ea3609297617a533f1905777bffa57731102/ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx) that would correspond to "DOM text reinterpreted as HTML" either, and with regard to "escaping meta-characters", React itself does this to prevent XSS, unless one uses [`dangerouslySetInnerHTML`](https://react.dev/reference/react-dom/components/common#dangerously-setting-the-inner-html), which Argo does not.
