### ISSUE TITLE
Possible clear-text logging of sensitive information in CLI `token.go`

### ISSUE THREAD

**Issue by makashu** [argoproj/argo-workflows#13105]
# Summary

What change needs making?
CodeQL flagged cmd/argo/commands/auth/token.go as printing Sensitive data returned by HTTP request headers flows to a logging call on line 21.

## Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by makashu** [comment]
I am working on this issue. Thanks!

**Comment by agilgur5** [comment]
> CodeQL flagged cmd/argo/commands/auth/token.go as printing Sensitive data returned by HTTP request headers flows to a logging call on line 21.

That's this line:
https://github.com/argoproj/argo-workflows/blob/f492ea3609297617a533f1905777bffa57731102/cmd/argo/commands/auth/token.go#L21

It does exactly what the command's help text says it does:
https://github.com/argoproj/argo-workflows/blob/f492ea3609297617a533f1905777bffa57731102/cmd/argo/commands/auth/token.go#L15

That's a false positive, it's literally intended to print out the token
