### ISSUE TITLE
Unable to run Controller locally on Arm mac M1

### ISSUE THREAD

**Issue by Adrien-D** [argoproj/argo-workflows#13112]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When running `make start UI=true` on devcontainer with vscode extension I get this error

![image](https://github.com/argoproj/argo-workflows/assets/4726647/b082520a-b296-430e-afa7-2577a8fac561)

Running those commands I get 

![image](https://github.com/argoproj/argo-workflows/assets/4726647/5079fe74-aed8-4513-acfc-9355c537e97f)

Looking at this line ```TARGET_PLATFORM := $(shell [ `uname -m` = arm64 ] && echo linux/arm64 || echo linux/amd64)``` it must be using `linux/amd64` as target platform which is wrong

### Version

v3.5.7

**Comment by agilgur5** [comment]
> Running those commands I get

Please use text instead of images -- text is [much more accessible](https://meta.stackoverflow.com/a/285557/3431180).

Typing it out:
```
$ uname -s
Linux
$ uname -m
aarch64
```
