### ISSUE TITLE
v3.5.7: namespaced install causes the server to complain about list+watch on cluster scoped workflows

### ISSUE THREAD

**Issue by Joibel** [argoproj/argo-workflows#13177]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

To reproduce install 3.5.7 namespaced 
`kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.5.7/namespace-install.yaml`

You will see
```
W0613 08:46:47.382693       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1alpha1.Workflow: workflows.argoproj.io is forbidden: User "system:serviceaccount:argo:argo-server" cannot list
 resource "workflows" in API group "argoproj.io" at the cluster scope                                                                                                                                                                          
E0613 08:46:47.382720       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Workflow: failed to list *v1alpha1.Workflow: workflows.argoproj.io is forbidden: User "system:servicea
ccount:argo:argo-server" cannot list resource "workflows" in API group "argoproj.io" at the cluster scope    
```

This does not happen with 3.5.6 namespaced installs.

I believe this is coming from #12736 / #13021 on lines https://github.com/argoproj/argo-workflows/blob/b28486cdc0a2174d68a0d0d04ba788847552b826/server/workflow/workflow_server.go#L73 and https://github.com/argoproj/argo-workflows/blob/b28486cdc0a2174d68a0d0d04ba788847552b826/server/workflow/workflow_server.go#L76

It feels like these should be namespaced when the server is running namespaced.

### Version

v3.5.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Not relevant.
```

### Logs from the workflow controller

```text
Not relevant. Server logs above.
```

### Logs from in your workflow's wait container

```text
Not relevant
```

**Comment by Joibel** [comment]
@jiachengxu, could you look at this and see if you can come up with a fix please?

**Comment by jiachengxu** [comment]
> @jiachengxu, could you look at this and see if you can come up with a fix please?

sure @Joibel could you assign this to me? I don't have permission to do that

**Comment by agilgur5** [comment]
> It feels like these should be namespaced when the server is running namespaced.

Yes, yes they should. 
This is the first time we've had an Informer/Reflector on the Server, so all the [namespacing logic that the Controller has](https://github.com/argoproj/argo-workflows/pull/11855/files#diff-a4744ebc7cedb1f62f2128e64c835508eb5707567072e207d9cc0879276b5b7aR1387) didn't exist there. Prior to it, all requests had a namespace, so that logic was limited in the Server.

Specifically, if the Server is in `--namespaced` mode, it should use [its own `namespace`](https://github.com/argoproj/argo-workflows/blob/0ca0c0f721c9bf05c63dea98168cfa87441656c7/cmd/argo/commands/server.go#L157), unless it also has a `--managed-namespace`, in which case it should use that. If unset, the ListWatch should be cluster-scope as it is now.
