### ISSUE TITLE
namespace in example `grafana-dashboard.json`

### ISSUE THREAD

**Issue by ivan-cai** [argoproj/argo-workflows#13186]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Argo Workflows metrics no kubernetes_namespace label, but the `kubernetes_namespace` is used in grafana-dashboard.json: https://github.com/argoproj/argo-workflows/blob/main/examples/grafana-dashboard.json#L159C20-L159C40
In this case, the namespace in the dashboard will cause confusion to users. 
I don't know if it's because it hasn't been developed yet or if the `kubernetes_namespace` was deleted on purpose.
If it hasn't been developed yet, we can develop it. If the `kubernetes_namespace` was deleted on purpose, we should be update grafana-dashboard.json.

metrics:
- argo_workflows_count (https://github.com/argoproj/argo-workflows/blob/main/workflow/metrics/util.go#L170)
- argo_workflows_operation_duration_seconds_bucket
- argo_workflows_queue_adds_count
- argo_workflows_queue_latency_sum
- argo_workflows_queue_latency_count
- log_messages

I have created 2 workflow CR，one is in default namespace, one is in another namespace, but count is 2 if I select default namespace，some confusion.
![image](https://github.com/argoproj/argo-workflows/assets/49785578/acf47de1-0e4c-43b3-9cc0-5c7567254d90)

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
no need
```

### Logs from the workflow controller

```text
no need
```

### Logs from in your workflow's wait container

```text
no need
```

**Comment by tico24** [comment]
The grafana json there hasn't been touched for ages and is very stale.

The most up to date dashboard is this: https://grafana.com/grafana/dashboards/20348-argo-workflows-metrics/ which is linked elsewhere in the argo docs.

However, your issue is actually that the `namespace` in the query refers to the namespace of the Workflow controller, not the running workflow. The updated dashboard tries to help clarify this by making the dropdown more explicit:
![image](https://github.com/argoproj/argo-workflows/assets/45351296/4ad21456-960f-463b-8029-4e1145bc4206)

**Comment by Joibel** [comment]
https://github.com/argoproj/argo-workflows/issues/12589 adds the namespace to some metrics, and would allow some of what you're after. Please comment on that issue regarding whether that fits your needs.

**Comment by ivan-cai** [comment]
@tico24 Thanks.  The WF Controller Namespace can help to monitor how many workflows each workflow controller processes, it is more meaningful.

**Comment by agilgur5** [comment]
Closing as it seems like all questions were answered here and the link to the non-example Grafana dashboard was given as well as links to other metrics issues.
