### ISSUE TITLE
Regression: ARGO_BASE_HREF doesn't work

### ISSUE THREAD

**Issue by rijos** [argoproj/argo-workflows#13199]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug

### What happened/what you expected to happen?

It seems the name change from BASE_HREF to ARGO_BASE_HREF breaks base href functionality. 

Here is my deployment:
![image](https://github.com/argoproj/argo-workflows/assets/23135242/c2e334a8-e8d7-4ed9-a73d-de961e1d54db)

Here is the html output:
![image](https://github.com/argoproj/argo-workflows/assets/23135242/d2390a72-ec08-4886-9f1f-f1723477ed56)

Server logs:
![image](https://github.com/argoproj/argo-workflows/assets/23135242/a7ca5a17-b94f-4e3a-ad93-d0bac93eb6b3)

### Version
v3.5.7

**Comment by agilgur5** [comment]
> It seems the name change from BASE_HREF to ARGO_BASE_HREF breaks base href functionality

Er, #12653 is not part of any stable release and its upgrade notes are for 3.6, which you aren't on.

> ### Version
> v3.5.7

> * [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.

And this should work on `:latest`. Are you sure you tested with `:latest` as the issue template requires?

> Here is my deployment:

Also please use text instead of images of code or logs; text is [substantially more accessible](https://meta.stackoverflow.com/a/285557/3431180)

**Comment by agilgur5** [comment]
It sounds like there might be a regression in the Helm chart though, as I wrote up https://github.com/argoproj/argo-helm/pull/2756 for forward-compat, but failed to read my own release notes 4 months later that the typo means it won't work. I'll fix that ASAP
