### ISSUE TITLE
3.5.6: Archive workflow sql syntax error with mariadb

### ISSUE THREAD

**Issue by spaced** [argoproj/argo-workflows#13202]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

since `v3.5.6` using mariadb can not list workflows because of [200f4d1e5](https://github.com/argoproj/argo-workflows/commit/200f4d1e5ffee0a57a9e7a9995b95da15230eb97) / #12912

exception
```
{"error":"rpc error: code = Internal desc = Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '\u003e\u003e'$.metadata.labels', '{}') as labels,coalesce(workflow-\u003e\u003e'$.metadata.annota...' at line 5","grpc.code":"Internal","grpc.method":"ListWorkflows","grpc.service":"workflow.WorkflowService","grpc.start_time":"2024-06-17T14:57:19Z","grpc.time_ms":6.307,"level":"error","msg":"finished unary call with code Internal","span.kind":"server","system":"grpc","time":"2024-06-17T14:57:19.890Z"}
{"duration":6836621,"level":"info","method":"GET","msg":"","path":"/api/v1/workflows","size":292,"status":500,"time":"2024-06-17T14:57:19.890Z"}
```
because json extract with `->` is not supported by mariadb (see also https://jira.mariadb.org/browse/MDEV-13594)
we should use `JSON_EXTRACT(field,path)`

### Version

v3.5.6

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
nope
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by agilgur5** [comment]
Thanks for filing an issue and giving instructions on how to resolve it!

This also got mentioned [twice](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1718138281377749) [on Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1718609984780119) earlier today and last week.

cc @jiachengxu it appears we might need to add a `case` for MariaDB since this specific syntax is different

**Comment by jiachengxu** [comment]
> cc @jiachengxu it appears we might need to add a case for MariaDB since this specific syntax is different compared to MySQL

@agilgur5 Thanks for tagging me. I just want to make sure that I understand the issue, [argo-workflows only supports MySQL and Postgres](https://github.com/argoproj/argo-workflows/blob/main/persist/sqldb/db_type.go#L13-L14), right? and this is more like a feature request?
