### ISSUE TITLE
Offload TaskResultStatus to db with Large workflow

### ISSUE THREAD

**Issue by shuangkun** [argoproj/argo-workflows#13213]
# Summary

Offload TaskResultStatus to db

## Use Cases

I have a large simulation experiment workflow with lot of pod. (2w-4w), Therefore, even though I have offloaded nodestatus to the db, this workflow cannot be updated in the end because the status is too large. So  I want to Offload TaskResultStatus to db when The workflow pod exceeds a certain threshold，such as 20000.

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
I guess this is superseded by #13783 since it already has more upvotes and discussion than this issue
