### ISSUE TITLE
UI: Add execution history to WorkflowTemplate & ClusterWorkflowTemplate details

### ISSUE THREAD

**Issue by panicboat** [argoproj/argo-workflows#13282]
# Summary

It would be useful to have the execution history as well as the details of the CronWorkflow.
It is a bit tedious to have to search through the workflow each time.

## Use Cases

Used to check the execution history of a specific WorkflowTemplate or ClusterWorkflowTemplate.

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
Basically #11706 but for WorkflowTemplates
