### ISSUE TITLE
Redirect is not working after login

### ISSUE THREAD

**Issue by ljyanesm** [argoproj/argo-workflows#13288]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When visiting a workflow in argo workflows on a session that needs authenticating (oauth), the user is correctly redirected to the login page, but, once logged-in, the original workflow that was intended to be visited is lost and the user ends up at the workflow list page.

I would expect that, after log in, the user is redirected to the original URL that initiated the auth flow.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
not applicable
```

### Logs from the workflow controller

```text
not applicable
```

### Logs from in your workflow's wait container

```text
not applicable
```

**Comment by Joibel** [comment]
What is your configuration? Does reading through #13031 help you?

**Comment by ljyanesm** [comment]
Sorry, yes this can be marked as a duplicate of #13031
