### ISSUE TITLE
Keycloak SSO: how to get token for automation?

### ISSUE THREAD

**Issue by omar-khaled-mahmoud** [argoproj/argo-workflows#13302]
Hello Team, Please support.

SSO works fine using GUI ( except the api/version error when logging in)
My team used to do automation with argo-workflow , after implementing SSO , I can't create TOKEN and use it in
```sh
curl https:/localhost:port-number/api/argoproj.io/v1alpha1/workflows/argo-workflows -H "Authorization: $ARGO_TOKEN"
```
- I have tried to create tokens using role,rolebinding, service account ... even retrieving tokens from keycloak .
- How this should be achieved?

Thanks!

**Comment by agilgur5** [comment]
### please follow instructions

This is a support question, not a bug report. Per the [issue creation screen](https://github.com/argoproj/argo-workflows/issues/new/choose), this should be asked in Discussions or on Slack. The fact that you did not fill out the issue template is an indication you're in the wrong place as well.
Please follow the instructions for all OSS repos you interact with.

 It is also helpful to include any error messages and your configuration when asking for help.

### `--auth-mode=sso --auth-mode=client`

> * I have tried to create tokens using role,rolebinding, service account .

This is the correct approach for automation, using ServiceAccounts.

You did not provide your config, but I'm guessing you only set `--auth-mode=sso`. If you want to use _both_ SSO _and_ client authentication, you need to set _both_: `--auth-mode=sso --auth-mode=client`

**Comment by agilgur5** [comment]
> ```shell
> https:/localhost:port-number/api/argoproj.io/v1alpha1/workflows/argo-workflows
> ```

This is also not the right URL for the Argo API, if that's what you're trying to use. Please see the [Access Token](https://argo-workflows.readthedocs.io/en/release-3.5/access-token/#token-usage-test) docs and the [API Reference](https://argo-workflows.readthedocs.io/en/release-3.5/swagger/) for how to use the API and all available URLs.

**Comment by omar-khaled-mahmoud** [comment]
Hello @agilgur5 ,

Thanks for your support, it was really helpful ,

is it okay to include multiple Auth modes at the same time ? When I tried both --auth-mode=sso --auth-mode=client , the SSO feature vanished from the GUI but the tokens are working fine

**Comment by agilgur5** [comment]
> is it okay to include multiple Auth modes at the same time ?

Yes, it wouldn't be allowed otherwise. `client` + `sso` is also explicitly mentioned in the [auth mode docs](https://argo-workflows.readthedocs.io/en/release-3.5/argo-server-auth-mode/). Also can personally confirm that I have used both together myself at my last job.

> When I tried both --auth-mode=sso --auth-mode=server , the SSO feature vanished from the GUI but the tokens are working fine

`--auth-mode=server` does not require login as it does not distinguish users, so the login page is skipped -- from a user perspective, it equates to _no_ authentication.
You should only ever use that mode if you have another layer of authentication or isolation in front of the Server.

**Comment by omar-khaled-mahmoud** [comment]
Hello @agilgur5
Thank you for your extraordinary support , everything is working now
