### ISSUE TITLE
role permission `pods/exec` no longer needed for `emissary` executor

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#13307]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Prior to v3.4.0, argo-workflow has [other executors](https://github.com/argoproj/argo-workflows/blob/release-3.3/docs/workflow-executors.md), e.g. `k8sapi`, `pns`...
`k8sapi` executor requires `pods/exec` to exec into pod and then signal action.

Since v3.4.0, argo-workflows only has [`emissary` executor](https://github.com/argoproj/argo-workflows/blob/release-3.4/docs/workflow-executors.md) which signals through argoexec in the main container, role `pods/exec` is no longer needed

### Version

from v3.4.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by tczhao** [comment]
not applicable,
controller signalling pod termination due timeout is done through exec
https://github.com/argoproj/argo-workflows/blob/a929c8f4dd03460d0f1e5ab2937dd2990a659d81/workflow/common/util.go#L62

**Comment by agilgur5** [comment]
Yep, as far as I understand that is the primary reason why Emissary has to run as a parent process to the `main` container as well, as otherwise you cannot be sure that the `main` container will respond to a kill/term signal.

It would be great if Emissary didn't have to do that, as signal handling is pretty error-prone, inconsistent, etc, but there doesn't seem to be a way around that in k8s (you can `delete` a Pod, but otherwise can't `kill` or `stop` or `terminate` it)

**Comment by agilgur5** [comment]
I've been thinking if it might be possible to reverse engineer it; e.g. by [marking the `Pod`'s status as `Terminating`](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination), causing the kubelet to act, or by directly requesting the kubelet to terminate a Pod somehow.
