### ISSUE TITLE
I'm using Argo-workflow auth mode=SSO , I'm using it along with Keycloak for single sign on . how to get token for automation?

### ISSUE THREAD

**Issue by omar-khaled-mahmoud** [argoproj/argo-workflows#13301]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

SSO works fine using GUI ( except the api/version error when logging in)

My team used to do automation with argo-workflow , after implementing SSO , I can't create TOKEN and use it in 

curl https://localhost:portnumber/api/argoproj.io/v1alpha1/workflows/argo-workflows -H "Authorization: $ARGO_TOKEN"

--I have tried to create tokens using role,rolebinding, service account ... even retrieving tokens from keycloak .

-- How this should be achieved?
 

### Version

v3.5.6

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
not related
```

### Logs from the workflow controller

```text
not related
```

### Logs from in your workflow's wait container

```text
not related
```

**Comment by agilgur5** [comment]
Duplicate of #13302
