### ISSUE TITLE
CLI support for `-l` / `--selector` option in `template list` command

### ISSUE THREAD

**Issue by menzenski** [argoproj/argo-workflows#13309]
# Summary

What change needs making?

It would be great to have argo CLI support for the `-l` / `--selector` option.

The argo CLI's `cron list` [method](https://argo-workflows.readthedocs.io/en/latest/cli/argo_cron_list/#options) supports a `-l` / `--selector` string that allows listing CronWorkflow resources by label:

```shell
$ argo cron list -l example.com/project=my-project
NAME   AGE   LAST RUN   NEXT RUN   SCHEDULE   TIMEZONE   SUSPENDED
```

The `list` [method](https://argo-workflows.readthedocs.io/en/latest/cli/argo_list/#options) supports the same CLI option:

```shell
argo list -l example.com/project=my-project
No workflows found
```

However, the `template list` CLI method does not support a `-l` / `--selector` flag, and errors if one is provided:

```shell
$ argo template list -l example.com/project=my-project
Error: unknown shorthand flag: 'l' in -l
Usage:
  argo template list [flags]

Flags:
  -A, --all-namespaces   Show workflows from all namespaces
  -h, --help             help for list
  -o, --output string    Output format. One of: wide|name

...
```

I can use kubectl to get WorkflowTemplates by selector, though:

```shell
$ kubectl get workflowtemplates  -l example.com/project=my-project
No resources found in default namespace.
```

~I searched for similar issues and found https://github.com/argoproj/argo-workflows/issues/3003, which I believe is related.~ *edited by agilgur5*: not quite, see [below comment](https://github.com/argoproj/argo-workflows/issues/13309#issuecomment-2211329043)

My argo CLI version:

```shell
$ argo version
argo: v3.5.5
  BuildDate: 2024-02-29T21:37:24Z
  GitCommit: c80b2e91ebd7e7f604e88442f45ec630380effa0
  GitTreeState: clean
  GitTag: v3.5.5
  GoVersion: go1.21.7
  Compiler: gc
  Platform: darwin/amd64
```

## Use Cases

When would you use this?

We use https://github.com/argoproj-labs/hera to generate WorkflowTemplates and CronWorkflows that use them. We generally have hundreds of CronWorkflows that each pass parameters to a WorkflowTemplate. We set `metadata.labels` consistently on all Argo Workflows resources and running `argo cron list -l example.com/project=my-project` is a very commonly run CLI command on my team today. It'd be really handy to be able to run the same command for templates (`argo template list -l example.com/project=my-project`) to easily switch between cron workflows that have a given label and the workflow templates that relate to them.

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
Sounds pretty reasonable. Do you want to implement it?

**Comment by agilgur5** [comment]
> I searched for similar issues and found #3003, which I believe is related.

No, that's for [`resource` templates](https://argo-workflows.readthedocs.io/en/latest/walk-through/kubernetes-resources/), which are actually entirely unrelated to the CLI.
