### ISSUE TITLE
Workflow is not getting deleted after adding ttlStrategy

### ISSUE THREAD

**Issue by madhur-lyric** [argoproj/argo-workflows#13331]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

I have configured the `ttlStrategy` in my Argo Workflow as follows:

```yaml
ttlStrategy:
    secondsAfterCompletion: 10
```

After the workflow completes, it is no longer shown when running the command:
```
kubectl get wf -n {namespace}
```

However, the workflow is still visible in the Argo UI and accessible through the Argo API. I would like the workflow to be completely deleted and not shown in the UI or API after the TTL expiration.

```
/argo-workflows/api/v1/workflows/{namespace}
```

### Version(s)

v3.5.8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
spec:
  ttlStrategy:
    secondsAfterCompletion: 10
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by Joibel** [comment]
Do you have [workflow archiving](https://argo-workflows.readthedocs.io/en/latest/workflow-archive/) enabled?

**Comment by madhur-lyric** [comment]
@Joibel Yes workflow archive is enabled

```
controller:
  persistence:
    archive: true
```

**Comment by Joibel** [comment]
With enabled archiving, the behaviour you see is what is expected.

The argo-server, which responds to the API and provides the workflows to the UI will provide workflows from both the cluster and the archive. This is not totally clear in the documentation which could do with updating to explain this.

**Comment by lost11n** [comment]
Did you check the retentionPolicy of workflow-controller?It's  a global setting ,has higher priority than "ttlStrategy" defined in workflow.For example, using default settings,argo will keep 10 completed workflow,even the time of ttlStrategy has expired.

`k -n argo describe cm workflow-controller`

Default values of  retentionPolicy:
```
retentionPolicy:
----
completed: 10
failed: 3
errored: 3
```
