### ISSUE TITLE
High severity vulnerability found in `jackc/pgx/v4`

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#13405]
# Summary

```
✗ High severity vulnerability found in github.com/jackc/pgx/v4
  Description: Uncaught Exception
  Info: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMJACKCPGXV4-7416900
  Introduced through: github.com/upper/db/v4/adapter/postgresql@4.7.0
  From: github.com/upper/db/v4/adapter/postgresql@4.7.0 > github.com/jackc/pgx/v4/stdlib@4.18.2 > github.com/jackc/pgx/v4@4.18.2

```
---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
@terrytangyuan this looks like a false positive, I mentioned it [on Slack](https://cloud-native.slack.com/archives/C0510EUH90V/p1721421729011109). Reported it to Snyk per the thread, but they have yet to respond 😕

**Comment by terrytangyuan** [comment]
Yep I saw that thread. We should still track it on GitHub.

**Comment by terrytangyuan** [comment]
Disabling this one in https://github.com/argoproj/argo-workflows/pull/13406

**Comment by agilgur5** [comment]
Snyk still hasn't responded to my ticket/email (almost 2 weeks now), but I double-checked and it appears they have revoked the advisory in their DB now: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMJACKCPGXV4-7416900

**Comment by agilgur5** [comment]
Got a response from Snyk on Aug 2nd saying they opened an investigation with their Security Team. Got a further response today saying it was actually a false positive upstream too, c.f. https://github.com/golang/vulndb/issues/2966.
Not clear why Snyk was behind that long though, I did ask for further details on that.

Should be all good to remove the ignore now though with multiple confirmations now

**Comment by terrytangyuan** [comment]
Cool I'll submit a PR to move the ignore
