### ISSUE TITLE
v3.3.7 to v3.5.4 missing workflow executor RBAC

### ISSUE THREAD

**Issue by Freddybob4244** [argoproj/argo-workflows#13428]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

We upgraded our devtest and sandbox envs between many versions to perform various regression tests in our environment so I am unsure where specifically this was missed.  We got everything working and eventually validated that we could use v3.5.4 for our production environment, and updated as such.

The problem was inadvertently introduced in part due to the amount of time that had passed between upgrades.  Moving from v3.3.7 to v3.5.4 seems to have missed installing/adding resources that are required - specifically the role binding `executor-default`, and its accompanying service account `default` and role `executor`.

While this wasn't causing any major headache, we did notice this logs being flooded in each workflow container while troubleshooting another issue:

`time="2024-08-02T15:39:53.392Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:argo:default\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"argo\""`

We are planning on adding the resources by hand on Monday, and I will follow up if that resolves the behavior we are seeing.  This is mainly intended as a report for the maintainers to know that important things might be missed depending on the upgrade path.

### Version(s)

v3.3.7, v3.5.4

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Not a workflow-level issue
```

### Logs from the workflow controller

```text
Not a workflow-level issue
```

### Logs from in your workflow's wait container

```text
Not a workflow-level issue
```

**Comment by agilgur5** [comment]
> Moving from v3.3.7 to v3.5.4 seems to have missed installing/adding resources that are required - specifically the role binding `executor-default`, and its accompanying service account `default` and role `executor`.

The [production installation methods](https://argo-workflows.readthedocs.io/en/release-3.5/installation/#production-installation) do not include an Executor SA by default as Argo cannot specify an SA on your Workflows for you and does not know what other RBAC you might need. There is instead a specific page about configuring [Workflow RBAC](https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/)

> "failed to patch task set, falling back to legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/"

This is the same link that your logs link to.

The quick-start installation, which is explicitly not meant for production, does have [an `executor` role](https://github.com/argoproj/argo-workflows/blob/b59d7c1cd3c0191cb9a2c6ec91af47da2f21520e/manifests/quick-start/base/executor/emissary/executor-role.yaml) which is bound to the [`default` SA](https://github.com/argoproj/argo-workflows/blob/b59d7c1cd3c0191cb9a2c6ec91af47da2f21520e/manifests/quick-start/base/executor-default-rolebinding.yaml#L11) via an `executor-default` RoleBinding.

> v3.5.4

You're also on an old patch version. Previously, the [quick-start docs](https://argo-workflows.readthedocs.io/en/release-3.5/quick-start/) did appear to not correctly use the quick-start manifests for some reason per #12391 and #12445.

So you appear to be on an old patch and perhaps following old directions for the quick-start install, and it sounds like you're using that for a production environment, which it is explicitly not intended for. Using the `default` SA and such is not recommended k8s practice.
