### ISSUE TITLE
Panic on unchecked cast: `interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *unstructured.Unstructured`

### ISSUE THREAD

**Issue by Daimanta** [argoproj/argo-workflows#13456]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

We have set up an argo eventsource in our kubernetes cluster. Regularly (but unpredictably), the eventsources crashes in a panic. The panic message is a consistent problem, namely that a cast of an interface is done without checking.

Here is an example of a panic stack trace:
```
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *unstructured.Unstructured

goroutine 159 [running]:
github.com/argoproj/argo-events/eventsources/sources/resource.passFilters(0xffffffffffffffff?, 0xffffffffffffffff?, {0x1?, 0x0?, 0x5b89900?}, 0x1?)
	/home/runner/work/argo-events/argo-events/eventsources/sources/resource/start.go:290 +0xa53
github.com/argoproj/argo-events/eventsources/sources/resource.(*EventListener).StartListening.func2(0xc001a59b60)
	/home/runner/work/argo-events/argo-events/eventsources/sources/resource/start.go:131 +0x6b
github.com/argoproj/argo-events/eventsources/sources/resource.(*EventListener).StartListening.func3()
	/home/runner/work/argo-events/argo-events/eventsources/sources/resource/start.go:178 +0x122
created by github.com/argoproj/argo-events/eventsources/sources/resource.(*EventListener).StartListening in goroutine 93
	/home/runner/work/argo-events/argo-events/eventsources/sources/resource/start.go:173 +0x8e8
```

Checking the start.go:290 we can see an unchecked cast. An `*unstructured.Unstructured` is expected but in this case a `cache.DeletedFinalStateUnknown` is provided.

This issue strongly looks like https://github.com/argoproj/argo-workflows/issues/1132 but happens in a different part of the codebase.

As a suggested approach: Check if the `event.Obj` is an `*unstructured.Unstructured`, if not return `false` in the `passFilters` function.

As we run a lot of workflows, it's very difficult to relate this error to any one specific workflow we execute, my apologies.

### Version(s)

v1.9.2

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Not related to a specific workflow.
```

### Logs from the workflow controller

```text
Not related to a specific workflow.
```

### Logs from in your workflow's wait container

```text
Not related to a specific workflow.
```

**Comment by agilgur5** [comment]
> the eventsources crashes in a panic

> github.com/argoproj/argo-events/eventsources/

> v1.9.2

This is the Argo Workflows repo, not Argo Events. You'll want to report this in the Argo Events repo: https://github.com/argoproj/argo-events

**Comment by agilgur5** [comment]
For reference, this was properly opened in https://github.com/argoproj/argo-events/issues/3238
