### ISSUE TITLE
tests: change `if assert` to `require` in remaining places

### ISSUE THREAD

**Issue by Joibel** [argoproj/argo-workflows#13465]
As suggested by @agilgur5:

Implement remaining `if assert.*` -> `require.*` changes as mentioned in [#13401 (comment)](https://github.com/argoproj/argo-workflows/pull/13401#discussion_r1696246571) etc

**Comment by djanjic** [comment]
Hello @Joibel, can I start working on this? It looks like a good task for newcomers.
