### ISSUE TITLE
Go SDK: `cannot use runtimeutil.PanicHandlers (variable of type []func(context.Context, interface{})) as []func(interface{}) value in argument to runtimeutil.HandleCrash`

### ISSUE THREAD

**Issue by keshmirian** [argoproj/argo-workflows#13485]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I'm using v3@v3.5.10 with Go 1.22.5 and I'm getting the following error:

```
# github.com/argoproj/argo-workflows/v3/workflow/metrics
../../../../go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.5.10/workflow/metrics/server.go:23:32: cannot use runtimeutil.PanicHandlers (variable of type []func(context.Context, interface{})) as []func(interface{}) value in argument to runtimeutil.HandleCrash
```

### Version(s)

v3.5.10

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Use the above configuration. Run Go program. Receive error.
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
n/a
```

**Comment by Joibel** [comment]
Please could you provide a link to a minimal reproduction. This description isn't enough to reproduce your issue.

It looks like you're not building with a matching version of the `k8s.io` packages to that in workflow's [go.mod](https://github.com/argoproj/argo-workflows/blob/dcd943618e4e85443c75944f5f2c333f07c89805/go.mod#L74), in particular apimachinery.
