### ISSUE TITLE
`https://github.com/Azure/go-autorest`  is deprecated update to latest sdk 

### ISSUE THREAD

**Issue by sudheermygapula** [argoproj/argo-workflows#13506]
# Summary

[What change needs making?]

(https://azure.microsoft.com/en-us/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/)

## Use Cases

 Avoid end-of-life technologies
---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
`go-autorest` is an indirect dependency, per the [`go.mod`](https://github.com/argoproj/argo-workflows/blob/ddbb3c7ad5b498d50514b3c1158ded56e333d75b/go.mod#L151). That means one of the direct deps pulls it in, but not Argo itself. If there's an update to one of those that would remove it, then we can do that

**Comment by agilgur5** [comment]
`go mod why https://github.com/Azure/go-autorest` is unfortunately not very helpful:
```
# https:/github.com/Azure/go-autorest/autorest
(main module does not need package https:/github.com/Azure/go-autorest/autorest)
```

This might be a case of https://github.com/golang/go/issues/27900#issuecomment-2280534247 where it's actually unused.

Looking at `go mod graph`, per https://github.com/golang/go/issues/27900#issuecomment-2301779055, shows a handful of relevant items:
```
github.com/chrismellard/docker-credential-acr-env@v0.0.0-20220327082430-c57b701bfc08 github.com/Azure/go-autorest/autorest@v0.11.8
github.com/chrismellard/docker-credential-acr-env@v0.0.0-20220327082430-c57b701bfc08 github.com/Azure/go-autorest/autorest/adal@v0.9.4
github.com/chrismellard/docker-credential-acr-env@v0.0.0-20220327082430-c57b701bfc08 github.com/Azure/go-autorest/autorest/azure/auth@v0.5.2
github.com/chrismellard/docker-credential-acr-env@v0.0.0-20220327082430-c57b701bfc08 github.com/Azure/go-autorest@v14.2.0+incompatible
github.com/chrismellard/docker-credential-acr-env@v0.0.0-20220327082430-c57b701bfc08 github.com/Azure/go-autorest/autorest/azure/cli@v0.4.1
github.com/chrismellard/docker-credential-acr-env@v0.0.0-20220327082430-c57b701bfc08 github.com/Azure/go-autorest/autorest/date@v0.3.0
github.com/chrismellard/docker-credential-acr-env@v0.0.0-20220327082430-c57b701bfc08 github.com/Azure/go-autorest/logger@v0.2.0
github.com/chrismellard/docker-credential-acr-env@v0.0.0-20220327082430-c57b701bfc08 github.com/Azure/go-autorest/tracing@v0.6.0

# [...]

github.com/google/go-containerregistry/pkg/authn/k8schain@v0.0.0-20220720195016-31786c6cbb82 github.com/Azure/go-autorest@v14.2.0+incompatible
github.com/google/go-containerregistry/pkg/authn/k8schain@v0.0.0-20220720195016-31786c6cbb82 github.com/Azure/go-autorest/autorest@v0.11.27
github.com/google/go-containerregistry/pkg/authn/k8schain@v0.0.0-20220720195016-31786c6cbb82 github.com/Azure/go-autorest/autorest/adal@v0.9.20
github.com/google/go-containerregistry/pkg/authn/k8schain@v0.0.0-20220720195016-31786c6cbb82 github.com/Azure/go-autorest/autorest/azure/auth@v0.5.11
github.com/google/go-containerregistry/pkg/authn/k8schain@v0.0.0-20220720195016-31786c6cbb82 github.com/Azure/go-autorest/autorest/azure/cli@v0.4.5
github.com/google/go-containerregistry/pkg/authn/k8schain@v0.0.0-20220720195016-31786c6cbb82 github.com/Azure/go-autorest/autorest/date@v0.3.0
github.com/google/go-containerregistry/pkg/authn/k8schain@v0.0.0-20220720195016-31786c6cbb82 github.com/Azure/go-autorest/logger@v0.2.1
github.com/google/go-containerregistry/pkg/authn/k8schain@v0.0.0-20220720195016-31786c6cbb82 github.com/Azure/go-autorest/tracing@v0.6.0

# [...]

k8s.io/client-go@v0.17.8 github.com/Azure/go-autorest/autorest@v0.9.0
k8s.io/client-go@v0.17.8 github.com/Azure/go-autorest/autorest/adal@v0.5.0
```

i.e. older versions of container registry packages and an older version of `client-go`, which I actually traced to being from `argoproj/pkg`: https://github.com/argoproj/pkg/blob/7dc18479d378b4f8888f0c8866ebe5a71f0452ef/go.mod#L24

**Comment by agilgur5** [comment]
Looks like `go-containerregistry` still has it as an indirect dep even in its `latest` version (which I tried upgrading to in the `go.mod` as well): https://github.com/google/go-containerregistry/blob/00f182b8d3070d2c0a0334657fd58a284778ef83/pkg/authn/k8schain/go.mod#L23

So I think this is solidly blocked by upstream and there's not much Argo can really do about it right now. We can re-open this issue at a later date once it is actionable

**Comment by gaganhr94** [comment]
Looks like this project `docker-credential-acr-env` is not maintained anymore. I've built https://github.com/gaganhr94/docker-credential-acr as a modern, maintained drop-in replacement for docker-credential-acr-env. It provides a good number of functionalities, and is built on the current Azure SDK (azidentity / azcontainerregistry) — eliminating the dependency on the end-of-life go-autorest stack entirely. Check it out and let me know if it matches your requirement.
