### ISSUE TITLE
Logout does not work in Microsoft Edge

### ISSUE THREAD

**Issue by piby180** [argoproj/argo-workflows#13561]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

If you logout from Argo UI and then refresh the homepage, you can still access all the workflows. This happens only in Microsoft Edge and not in Chrome. Unfortunately some colleagues at my company uses Edge for security reasons.

### Version(s)

v3.5.8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
The issue is not in workflows
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

Not applicable here
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded


Not applicable here
```

**Comment by Joibel** [comment]
Could you give some details as to your server login configuration, version of edge and how someone might reproduce this problem please?

**Comment by piby180** [comment]
1. My Edge version is Version 128.0.2739.63 (Offizielles Build) (64-Bit)
2. We use AWS Cognito to authenticate to the UI
3. If I start Edge in incognito and go to home page, I can't see the workflows without logging in 
4. Once I am logged in, when I log out from the UI, I can still go to the homepage and see the workflows.
5. After logging out, I can still see the cookies (see the screenshot below)

![image](https://github.com/user-attachments/assets/0b818c2f-8699-4c0d-b638-d57b88543ac3)

**Comment by piby180** [comment]
Here is our auth config in Argo helm chart

````
![image](https://github.com/user-attachments/assets/9488edfb-ed6e-4162-9600-f3150e62ceec)

````

**Comment by agilgur5** [comment]
> 1. After logging out, I can still see the cookies (see the screenshot below AFTER logging out)
> 1. If I remove the authorization cookie manually, I can't access workflows anymore. So, the authorization cookie is not being removed properly in Edge.

This seems like an Edge bug then, since `document.cookie` is supposed to work and has worked for like two decades at this point.

> Here is our auth config in Argo helm chart

This is no longer relevant given the above information on cookies, but for reference, you can have multiple auth modes, and this screenshot does not include that configuration. Also for code, logs, and config, please use text instead of screenshots, as they are [much more accessible](https://meta.stackoverflow.com/a/285557/3431180).

**Comment by agilgur5** [comment]
I installed Edge `Version 128.0.2739.67 (Official build) (x86_64)` (which is better than IE these days thankfully, but still lots of adware etc 😕 ) and could not reproduce this on a local build of `main`. The "Logout" button successfully deleted the cookie on Edge.

So this seems even more like some environment issue and not an Argo bug.
