### ISSUE TITLE
Release v3.6 release discussion

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#13625]
We can discuss any important items and issues for v3.6 release. 

The 3.6 milestone board is https://github.com/argoproj/argo-workflows/milestone/30

**Comment by terrytangyuan** [comment]
@Joibel Could you share the draft to the release blog here so that the community can also review it and provide comments?

**Comment by Joibel** [comment]
The release blog post is here: https://medium.com/@alan_76951/argo-workflows-3-6-aa037cd782be

It should end up in the argoproj medium project, so may then end up community editable. I'm also happy to apply feedback from here or Slack.

**Comment by agilgur5** [comment]
3.6.0-rc1 CHANGELOG for reference: https://github.com/argoproj/argo-workflows/pull/13617

**Comment by Joibel** [comment]
I'm generally not happy with how the blog post review thing works for everyone else (it's easier for me as the writer). It's not a good collaboration experience though. We should consider doing it as a google doc (or similar alternative) or PR next time.

I'd like to get a PR in with mostly the same content anyway as a new-features-in-3.6.md type file for the documentation as discussed to make that more discoverable.

The main problem with all of this is the possible options for content and formatting differ quite widely between the different publishing platforms. I was trying to get video snippets in for the UI elements as some of them are hard to understand from a description. I basically gave up after one.

* Medium does allow animated gifs up to 15Mb. Formatting for images is very restrictive, as are general formatting options.
* google doc is very flexible, but we'd have to restrict comments there to content really, as it's never the publishing platform.
* Github markdown has options for up to 10Mb files, but not as part of the committed file set, instead needing manual uploading. This is less satisfactory for review purposes.

So after fighting it for a bit I think I'd like to aim for:
* `feat` PRs having a description and media added as part of the review and some tooling to make the first pass of the blog from this. The PR author has the best context for promoting their feature.
* Settling on a video platform to pop things best presented as moving pictures to use that embeds in github markdown and medium well. (Anyone who has ideas, please add).
* Using something other than medium for the pre-publication blog post collab.

Having written all this, I should probably turn it into an issue if others agree.

**Comment by agilgur5** [comment]
> * Settling on a video platform

Argoproj has a YouTube channel. We can add them there either as public vids or unlisted and link from the blog post

> * Medium does allow animated gifs up to 15Mb

If you compress them, this might be enough as well. It'll be low res, but I'm not sure how many people would be clicking through the YT links if we added them anyway.

Also we do already link to the original PRs, which have more context as-is. I think that's fine too tbh. Only a small percentage of folks will click through.

> * google doc is very flexible, but we'd have to restrict comments there to content really, as it's never the publishing platform.

Sounds good enough to me.



> Having written all this, I should probably turn it into an issue if others agree.

Maybe a PR to the Releasing docs adding a new section for "Feature Releases" or "Minor Releases"?

**Comment by agilgur5** [comment]
> It should end up in the argoproj medium project, so may then end up community editable.

Hasn't ended up there yet so I still haven't been able to make edits; there's some formatting issues to correct and some feature edits I'd like to make.

>  I'm also happy to apply feedback from here or Slack.

Can we add a shout-out to all new Reviewer+ since the last feature post? i.e. to give credit to folks reviewing. Possibly all new Members too? I think it'd be good encouragement in general 🙂

**Comment by terrytangyuan** [comment]
You can import a story that's written in markdown. Although you'll need to perform some minor edits. 

https://danielle-honig.com/blogging/2024/02/08/markdown-to-medium.html

**Comment by kissycn** [comment]
Have plane to support global agent #7891

**Comment by kissycn** [comment]
We can discuss gobal agent #7891

**Comment by agilgur5** [comment]
@kissycn that is unrelated to 3.6, and given that it has no implementation, highly unlikely to be part of 3.6.
You can discuss it in its issue. Please do not spam other issues or repeatedly tag maintainers.

If you are interested in a feature, the best way to get it done is to contribute yourself -- this is open source after all -- and the second best way is to pay a vendor or developer to do it for you. Spamming issues and maintainers, especially with the intent of them doing something for you, is unwelcome and presumptuous. See also https://justinmayer.com/posts/any-updates/

**Comment by Joibel** [comment]
3.6.0 has been released

**Comment by shuangkun** [comment]
Could we add a v3.6 patch releases discussion？

**Comment by Joibel** [comment]
> Could we add a v3.6 patch releases discussion？

Done. #14259
