### ISSUE TITLE
API filter by workflow level arguments

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#13621]
Some workflows (mostly interested in archived ones) have same spec but just different arguments passed into the workflow. Would be good to have filter option in the ui. ie can search for workflows where plant argument = 'fern'

i know there is label search but often labels are not set for every possible argument, and i know the workflow json is available in argo_archived_workflows which has the arguments

**Comment by agilgur5** [comment]
This sounds like a really niche feature, as filtering by parameters isn't something most systems have.

I'm inclined to say this is a better use-case for plugins (#6945) than being a core feature as such.

> i know the workflow json is available in argo_archived_workflows which has the arguments

And the JSON filter is pretty inefficient too, per #13295 et al
