### ISSUE TITLE
Volumes screen cleanup

### ISSUE THREAD

**Issue by wokeGit** [argoproj/argo-workflows#137]
@rahuldhide please take a look.
I would propose cleanup for volumes screen.
![screen shot 2017-09-01 at 11 54 22](https://user-images.githubusercontent.com/13086525/29965244-3255526e-8f0d-11e7-89a0-37de35aa1025.png)
![screen shot 2017-09-01 at 11 54 54](https://user-images.githubusercontent.com/13086525/29965246-3358dc9e-8f0d-11e7-9c05-ea26e856d830.png)

**Comment by rahuldhide** [comment]
@wokeGit this screen requires some additional updates. I am working on a design proposal.

**Comment by alexmt** [comment]
@rahuldhide please describe which additional changes are required
