### ISSUE TITLE
daemon containers don't support retry strategy

### ISSUE THREAD

**Issue by MenD32** [argoproj/argo-workflows#13705]
# Summary

daemon containers should be able to retry in order to ensure the stability of the workflow

## Use Cases

- CICD unit testing pipelines - when testing features that rely on external services, I want the other services (that may be daemon containers) to be consistent
- "Rare resource" dependent workflows - for workflows that depend on "rare resources" (such as GPUs), they might have preemptive scheduling (like spot instances), so I'd like my workflow to wait for the resource to be available again

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by MenD32** [comment]
I'd also like to contribute to solve this issue

**Comment by MenD32** [comment]
after looking at the code, i think a better fix would be to amend retry policy because of the `createWorkflowPod` function, which is kinda huge.

the something like `retryPolicy: always`

**Comment by agilgur5** [comment]
This seems to duplicate https://github.com/argoproj/argo-workflows/issues/5833.

This also would have to handle the difference between the Controller intentionally killing it at the end vs it dying on its own
