### ISSUE TITLE
Deprecate or remove auto-generated Python sdk

### ISSUE THREAD

**Issue by reinvantveer** [argoproj/argo-workflows#13703]
# Summary

The auto-generated Python client library name(spaces) are ... failing to produce a good description here. 

Frankly, class names like `IoArgoprojWorkflowV1alpha1WorkflowTemplateCreateRequest` are just silly. Some sanitization would be in order, since auto-generated client libraries from OpenAPI tend to produce buggy code and names like this. At least drop the entire `IoArgoprojWorkflowV1alpha1` prefix? Or is there going to be a `IoArgoprojWorkflowV1alpha2WorkflowTemplateCreateRequest`? Can you spot the difference?

## Use Cases

When using the python sdk in your own deployment scripts.

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by Joibel** [comment]
I would suggest using [hera](https://github.com/argoproj-labs/hera) instead of the autogenerated SDK. It's well maintained and has less silly names.

We currently have no intention of improving the auto-generated library, and are aiming to deprecate and remove it in deference to hera.
