### ISSUE TITLE
support cancellation

### ISSUE THREAD

**Issue by chengjoey** [argoproj/argo-workflows#13717]
# Summary

support cancellation for workflow

## Use Cases

Cancel the running workflow. If the current user wants to cancel the executed workflow, they can only delete it, so that the current environment cannot be retained. It is expected that the user can choose to cancel the workflow.

What I thought of is to add a field `cancelled` in the spec. When it is `true`, kill all containers through the `wait` container

The controller injects the downward api volume into the `wait` container. When the user cancels the workflow, the controller injects values into the annotations (`workflows.argoproj.io/cancellation`) of the workflow pods. `wait` listens to specific files under the downward api path. When the file generates content, it calls `killContainers` to cancel all tasks.

draft pr #13708, test case can refer to e2e test `cancel_test`

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by Joibel** [comment]
There is already a [`ShutdownStrategy`](https://github.com/argoproj/argo-workflows/blob/734b5b6e9f18ebe385df3e41117e67a1e8764939/pkg/apis/workflow/v1alpha1/workflow_types.go#L535) so I'd suggest that we shouldn't add a new field, just add a new value to that.

What is the approach with exit handlers going to be?

**Comment by chengjoey** [comment]
> There is already a [`ShutdownStrategy`](https://github.com/argoproj/argo-workflows/blob/734b5b6e9f18ebe385df3e41117e67a1e8764939/pkg/apis/workflow/v1alpha1/workflow_types.go#L535) so I'd suggest that we shouldn't add a new field, just add a new value to that.

okay




> What is the approach with exit handlers going to be?

exit handlers by wait container `killContainers`

**Comment by Joibel** [comment]
> > What is the approach with exit handlers going to be?
> 
> exit handlers by wait container `killContainers`

I'm not sure what you're trying to say. My question wasn't well phrased, sorry.

I was trying to ask: Will exit-handlers be run in the case of a cancelled workflow? I think there are arguments for both options, and I wondered if you'd thought through the cases and come up with a suggestion. My inclination is to say they should run.

**Comment by chengjoey** [comment]
hi @Joibel , I got what you mean, I haven’t considered `exit-handlers` yet. I also tend to run `exit-handlers`. I haven’t added corresponding e2e tests in draft-pr. I will take this into consideration when it is fully implemented.
