### ISSUE TITLE
Configure `terminationGracePeriodSeconds` without `podSpecPatch`

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#13716]
See https://github.com/argoproj/argo-workflows/issues/13671#issuecomment-2390274374

**Comment by agilgur5** [comment]
Again, please fill out the issue template in full. It is there for a reason and not intended to be skipped, and active members of the community skipping it are showing poor role models to newer members (why should they fill it out if you don't? what's the point of a template then?).

It is also bad OSS practice and poor manners in general.

> See [#13671 (comment)](https://github.com/argoproj/argo-workflows/issues/13671#issuecomment-2390274374)

Not to mention that this description is simply insufficient. This does not give a rationale and lists a bunch of other unrelated things too. I see one relevant sentence, which itself does not explain the rationale:

> i see https://github.com/argoproj/argo-workflows/pull/4940 added terminationGracePeriodSeconds but it requires podSpecPatch which will slow things down
