### ISSUE TITLE
3.6.0-rc3 CLI: Do not print help output on submission error

### ISSUE THREAD

**Issue by jrussell9000** [argoproj/argo-workflows#13826]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

Previous versions (< 3.6) of the argo cli just output the error when a workflow submission failed. The current release candidate prints the error, followed by entire the help output.  It's a bit tedious to have to scroll back up through all of this each time there's an error. Not sure if this is a bug or a feature request...

### Version(s)

v3.6.0-rc3

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
argo submit 'ANYexampleworkflow.yaml'
```

### Logs from the workflow controller

```text
Not relevant to this issue.
```

### Logs from in your workflow's wait container

```text
Not relevant to this issue.
```

**Comment by agilgur5** [comment]
@MasonM can you take a look? This might be related to one of your CLI PRs or another recent CLI PR
