### ISSUE TITLE
failed to build argo 3.6.0 release

### ISSUE THREAD

**Issue by chenrui333** [argoproj/argo-workflows#13911]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  Bundling for production...
  Generating listers for workflow:v1alpha1 at github.com/argoproj/argo-workflows/v3/pkg/client/listers
  Generating informers for workflow:v1alpha1 at github.com/argoproj/argo-workflows/v3/pkg/client/informers
  # Force the timestamp to be up to date
  touch pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go
  # Delete the link
  [ -e ./v3 ] && rm -rf v3
  make: *** [Makefile:659: pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go] Error 1
  make: *** Waiting for unfinished jobs....
```

</details>

### Version(s)

v3.6.0

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
brew install -s https://raw.githubusercontent.com/Homebrew/homebrew-core/cefeab8b49d9b0ac97d63be136c251c744bbe1a3/Formula/a/argo.rb
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
n/a
```

----

relates to https://github.com/Homebrew/homebrew-core/pull/197750
full build log, https://github.com/Homebrew/homebrew-core/actions/runs/11875018496/job/33091776717?pr=197750

**Comment by MasonM** [comment]
It looks like https://github.com/Homebrew/homebrew-core/pull/197750 was merged. Is this still an issue?

**Comment by chenrui333** [comment]
yeah, looks like build parallelization issue. closing for now.
