### ISSUE TITLE
Update installing document using cURL in MacOS

### ISSUE THREAD

**Issue by htquanq** [argoproj/argo-workflows#13980]
# Summary

Update installing document using cURL in MacOS

## Problem
I got this error when I tried to install the Argo client on my MacBook. This happened when I used the bash script on the release page.

What happened:
```
bash /tmp/install_argo.sh
/tmp/install_argo.sh: line 3: conditional binary operator expected
```
Expected:
```
bash /tmp/install_argo.sh
Downloading binary...
argo: v3.6.2
  BuildDate: 2024-12-02T15:04:56Z
  GitCommit: 741ab0ef7b6432925e49882cb4294adccf5912ec
  GitTreeState: clean
  GitTag: v3.6.2
  GoVersion: go1.23.3
  Compiler: gc
  Platform: darwin/amd64
  ```
  
  More information:
  ```
bash --version
GNU bash, version 5.2.12(1)-release (aarch64-apple-darwin21.6.0)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by htquanq** [comment]
My PR: https://github.com/argoproj/argo-workflows/pull/13981

**Comment by chengjoey** [comment]
`hack/release-notes.md`'s bash script works well for me, could you check what the output is when you run `uname -s != "Darwin"` in your environment using bash (5.2.12)? 

I think relase-nodes.md is just a document, and if you want to install the cli, you can directly specify `ARGO_OS`=darwin. 

This issue should not be considered a feature.

**Comment by htquanq** [comment]
ah yes, sorry, this should not be considered as a feature. Thanks for the update.

It's Darwin on my machine, the problem is `uname -s` throws error when running bash script. 

PR has been merged. I think I will close this issue.
