### ISSUE TITLE
support cronWorkflowDefaults in controller

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#13994]
# Summary

What change needs making?

## Use Cases

When would you use this?

Similar to [workflowDefaults](https://argo-workflows.readthedocs.io/en/latest/default-workflow-specs/#setting-default-workflow-values)
having cronWorkflowDefaults allows us to configure cron [options ](https://argo-workflows.readthedocs.io/en/latest/cron-workflows/#cronworkflow-options)like `startingDeadlineSeconds`/`when` globally

---

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by shuangkun** [comment]
Similar to https://github.com/argoproj/argo-workflows/issues/12627
