### ISSUE TITLE
Metadata/Description for templates

### ISSUE THREAD

**Issue by ankitanallana** [argoproj/argo-workflows#1456]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature Request

A description/metadata field for templates would be helpful while writing template definitions. While YAML supports comments, a description field would be a convenient way to store/record some information about a template after a workflow has been submitted. Could be a single field or something like [`labels` ](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)

**Comment by alexec** [comment]
Duplicate of #2871.
