### ISSUE TITLE
Expose exit codes of pod/containers in template parameters

### ISSUE THREAD

**Issue by delwaterman** [argoproj/argo-workflows#1481]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
Expose exit codes of pod/containers in template parameters

It's fairly common to run "tests" of some type in workflows. For example, when using workflows to deploy code, you might have a step to check a CI Server to make sure that a build has passed all builds. This kind of test can fail for different reasons. It might fail because the tests failed, or it might fail because there is a network issue that prevents the pod from communicating with the ci server.

In cases like this, there might be different error paths depending on the exit code. It would be helpful to expose that exit code as an Argo variable. You would probably have to expose it as a map since a pod can have multiple containers:

`{{tasks.ci-test-check.exit_codes.main}}`

or 

`{{steps.ci-test-check.exit_codes.sidecar}}

**Comment by Downchuck** [comment]
I'd like to start with containers, e.g. step|task.[name].outputs.exitcode much as there are outputs.result.

**Comment by alexec** [comment]
I think this is fixed. Re-open if not.
