### ISSUE TITLE
Need to have the pod names to be same as the task names (or have them as part of name) in an Argo workflow

### ISSUE THREAD

**Issue by shivan10** [argoproj/argo-workflows#1489]
**Is this a BUG REPORT or FEATURE REQUEST?**:
   FEATURE REQUEST
**What happened**:
  Increasingly difficult to track/pinpoint the pods that failed because of the dynamic naming

**What you expected to happen**:
    Have user-defined task names to be part of the pod names 

**How to reproduce it (as minimally and precisely as possible)**:
    Run an Argo workflow

**Comment by Erik-Securenative** [comment]
+1 for now i am duplicating the workflows

**Comment by epa095** [comment]
You know you can add your own labels to the pods right? https://github.com/argoproj/argo/blob/38c4def7fb100e954757649553db8c04ea64f318/examples/pod-metadata.yaml#L30

**Comment by ptemmer** [comment]
+1

**Comment by alexec** [comment]
Fixed in v3.2.
