### ISSUE TITLE
Use SharedIndexInformer to get WorkflowTemplates

### ISSUE THREAD

**Issue by dtaniwaki** [argoproj/argo-workflows#1529]
Currently, WorkflowTemplates are taken by using the workflow clientset interface, which doesn't have a cache mechanism and querying many WorkflowTemplates will impact the performance.

https://github.com/argoproj/argo/blob/fc1ec1a51462c9a114417db801e3a9715d3dc6b4/workflow/templateresolution/context.go#L46

We should utilize `SharedIndexInformer` so we don't have to make too many requests.

**Comment by xianlubird** [comment]
Yep,  I have found this problem in the case of a large workflow, which will result in a higher apiServer load.

**Comment by dtaniwaki** [comment]
#1534 which addressed this issue has been merged.
