### ISSUE TITLE
Azure File storage support for Artifacts

### ISSUE THREAD

**Issue by Sharathmk99** [argoproj/argo-workflows#1540]
*FEATURE REQUEST**:

**What you expected to happen**:
How can i mount Azure File storage to store my artifacts?

If this is not possible to use Azure Files storage directly, is there any alternative to use Azure storage for artifacts.

Thanks!

**Comment by gatepoet** [comment]
As far as I know, If you want to put it on Azure File Storage you'd have to add a step at the end that uses the azureFile-mount and copy the artifacts there. However, you can use Minio as an S3 wrapper around Azure Blob storage (which is cheaper than file storage anyways) to use for artifact output

**Comment by sathyatvrcbe** [comment]
@gatepoet , Can you give more details on how to do this? Any pointers will be helpful.

**Comment by binnie268** [comment]
My team is also currently using Azure File Share. We would like to decrease the dependency on minio and use azure storage directly. Would be great to have argo workflow support azure file share and/or blob storage :), especially since we would like to use argo workflow for the long term.

**Comment by pmjacinto** [comment]
Is this still being considered? I see https://github.com/argoproj/argo-workflows/pull/3173 was abandoned in 2020.

We also use Azure Blob Storage so it would be good to have direct support for it (similar to S3 and GCS).

**Comment by Collinbrown95** [comment]
In light of the [deprecation of MinIO gateway](https://blog.min.io/deprecation-of-the-minio-gateway/), connecting directly to Azure Blob Storage may be desirable in a number of use cases.

@alexec would a PR for this feature be accepted?

**Comment by alexec** [comment]
Yes. Please. You could refresh this PR: https://github.com/argoproj/argo-workflows/pull/1565

**Comment by Transmitt0r** [comment]
> Does this support having azure blob storage as the default artifact repo? I can't seem to get it working

Same, when I try to use azure as defaultArtifactRepo, the configmap is empty except this exception:
```
apiVersion: v1
data:
  config: "containerRuntimeExecutor: emissary\nartifactRepository:\n  s3:\n    accessKeySecret:\n
    \     key: accesskey\n      name: \n    secretKeySecret:\n      key: secretkey\n
    \     name: \n    bucket: \n    endpoint: \n    insecure: false\n"
kind: ConfigMap
...
```

**Comment by agilgur5** [comment]
The above was followed up in #9595, where the latest version, 3.4, needed to be used.
