### ISSUE TITLE
controller.runWorker for wfc.throttler.Next(key) bug

### ISSUE THREAD

**Issue by dongchang-xu** [argoproj/argo-workflows#1554]
https://github.com/argoproj/argo/blob/master/workflow/controller/controller.go#L262

```
	if key, ok = wfc.throttler.Next(key); !ok {
		log.Warnf("Workflow %s processing has been postponed due to max parallelism limit", key)
		return true
	}
```
https://github.com/argoproj/argo/blob/master/workflow/controller/throttler.go#L65

```
	if t.parallelism < 1 || t.parallelism > len(t.inProgress) {
		next := t.pending.pop()
		t.inProgress[next.key] = true
		return next.key, true
	}
```

if the key returned by Next function is changed, the workflow value must change follow. but now the runWorker.processNextItem code use the old workflow value

**Comment by shadowdsp** [comment]
I am quite confused about these lines too. Is this a bug or something else?

**Comment by alexec** [comment]
Seen in the wild
