### ISSUE TITLE
DAG retry problem

### ISSUE THREAD

**Issue by joyme123** [argoproj/argo-workflows#1584]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
**What happened**:
I use argo for machine learning. A DAG workflow like this:
```
download data
          |
   split data
    /         \
train        |
     \        /
      predict
          |
      deploy
```
Sometimes the model is not good. So I want train it again with some parameters change in train task, But I have to run the all tasks again. is there any way to reuse `download data` and `split data` tasks。`retry` command can only retry `Failed/Error`  workflows. Now I can mark `train` task as failed and use retry to achieve this. Is there a more elegant way?

**What you expected to happen**:
I can restart a workflow at any task. even if I can submit a workflow to reuse any completed workflow to save time. I try to add a `--reuse` flag in `submit` command to reuse a completed workflow.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
2.2.1
```
- Kubernetes version :
```
1.9.0
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by alexec** [comment]
I think think this is solved by the new memoization feature.
