### ISSUE TITLE
Request: workflow-level logging

### ISSUE THREAD

**Issue by illeatmyhat** [argoproj/argo-workflows#1598]
At the moment we can log workflows using `kubectl logs -f -l workflows.argoproj.io/workflow=hello-world-xxx -c main`
However, each time a pipeline step finishes, the pod exits and logging ends.
We can use the same command for each pipeline step, but I think that this method is not convenient and also delivers messy logs.

It would be nice to be able to do `kubectl logs -f workflows/hello-world-xxx` and tail logs for the _entire_ pipeline run.

For parallel executions, copying the logging style of docker-compose (they use different colors for each container) should work pretty well.

I would be interested in getting involved with this, but I don't have any experience writing CRDs or Aggregated APIs

**Comment by alexec** [comment]
This has been implement in v2.7 .
