### ISSUE TITLE
Argo should provide a retry mechanism during errors

### ISSUE THREAD

**Issue by navinjoy** [argoproj/argo-workflows#1603]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
When Argo WF is executed and if there are any errors, currently there's no retry mechanism. It would help if argo retries the step/pod task and ensures its complete.

**What you expected to happen**:
When there is an error from the pod (not failed step), argo should retry that step/pod task

**How to reproduce it (as minimally and precisely as possible)**:
Running Argo WF and sometimes we see pod deleted for one of the step and that fails the next steps.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
2.3
$ argo version
```
- Kubernetes version :
```
1.12
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by jlpnetworx** [comment]
but that mechanism does exist - we use it extensively and there are 4 examples in the repo:

retry-container-to-completion.yaml
retry-container.yaml
retry-script.yaml
retry-with-steps.yaml
