### ISSUE TITLE
Incorrect URL in UI used for Logs when using BASE_HREF

### ISSUE THREAD

**Issue by ddseapy** [argoproj/argo-workflows#1671]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:

Trying to download logs through UI when using BASE_HREF does not prepend the provided value.
It should be `/${BASE_HREF}/api/workflows` but was `/api/workflows`.  Making a manual request to the former works as expected.

**What you expected to happen**:
Clicking the download link for the logs in the UI should download logs for the workflow.

**How to reproduce it (as minimally and precisely as possible)**:
Install argo with environment variable:
```yaml
    - name: BASE_HREF
      value: /argo/
```
Run a workflow and try and download the logs through the UI.
**Anything else we need to know?**:

**Environment**:
- Argo version: `v2.4.1`
- Kubernetes version : `v1.13.1`

**Comment by ddseapy** [comment]
This continues being an issue with `2.5.0-rc7`, except now it's `/artifacts-by-uid/` when it should be `/${BASE_HREF}/artifacts-by-uid/`

**Comment by ddseapy** [comment]
Same problem for `/workflow-templates`

**Comment by ddseapy** [comment]
fyi @alexec

**Comment by alexec** [comment]
I think this is fixed by https://github.com/argoproj/argo/pull/2130.

**Comment by alexec** [comment]
We'll probably do an rc8 tomorrow to test.

**Comment by ddseapy** [comment]
ah sorry i missed that hadn't gotten into rc7.  i'll verify it works then.  thanks!
