### ISSUE TITLE
Creating WorkflowTemplate on a cluster level so all namespace can use it

### ISSUE THREAD

**Issue by mehtadeepen** [argoproj/argo-workflows#1729]
**Is this a BUG REPORT or FEATURE REQUEST?**: feature

**What you expected to happen**:

Creating WorkflowTemplate on a cluster level so everyone can use it.

**Comment by XciD** [comment]
Could be a good feature, can I help ?

**Comment by alexec** [comment]
I think we'd need to introduce a new CRD (cf `RoleBinding` vs `ClusterRoleBinding`: `ClusterWorkflowTemplate`

@dtaniwaki FYI
