### ISSUE TITLE
Question: How to get kubernetes pods fields as Environment varibales

### ISSUE THREAD

**Issue by naiduasn** [argoproj/argo-workflows#1746]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Question
**What happened**:
I am trying to fetch the node name of current POD execution similar to below
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables

**What you expected to happen**:
i could not able to figure out a way to get this info during workflow execution

**Comment by simster7** [comment]
I don't think we currently expose this

**Comment by alexec** [comment]
This is possible, you can use env vars.
