### ISSUE TITLE
Update aws-sdk-go to support IRSA

### ISSUE THREAD

**Issue by dcherman** [argoproj/argo-workflows#1774]
In order to support [IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), the minimum version of the Go SDK needs to be 1.23.13 (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html).  It's currently [1.23.8](https://github.com/argoproj/pkg/blob/02a6aac40ac4cd23de448afe7a1ec0ba4b6d2b96/Gopkg.lock#L42).

The use case is rather than explicitly providing access key/secrets, we can instead allow a role to be used for access to S3 for artifact storage.  While that is technically supported right now, it requires the use of either kube2iam or kiam rather than the officially supported solution.

**Comment by sarabala1979** [comment]
we will update the dependency v1.25.35 next release.
