### ISSUE TITLE
Filter jobs by template name instead of template id

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-workflows#183]
Metrics page allows filter jobs by repo, labels and templates. Template filtering is not perfect right now: template filter tab loads all templates from all repos and branches, allow user to select several templates and then use template id to filter jobs.

Since from user perspective templates from different branches but with the same name are same. E.g. 'Argo CI' is the same template in branches 'master', 'feature1' etc. So instead of filtering by id UI should filter by template name.

Following changes are required:

- Load unique list of template names using /v1/templates API. List might be loaded using API `/v1/templates?fields=name&dedup=true` ( PR is pending https://github.com/argoproj/argo/pull/182 )

- Filter jobs using 'template_name' filter instead of  template id. Note: API allows to filter by multiple names: `https://dev.applatix.net/v1/services?template_name=Argo%20CI,Argo%20Release&limit=10&fields=name`

**Comment by wokeGit** [comment]
Working on it.
