### ISSUE TITLE
Support using argoexec image from private repository

### ISSUE THREAD

**Issue by dmayle** [argoproj/argo-workflows#1838]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
While developing changes to the argoexec image, I had to publish changes to a public repository, because the workflow controller doesn't support passing the name of an imagepullsecret via a command line arg

**What you expected to happen**:
I expect to be able to use a private repository

**How to reproduce it (as minimally and precisely as possible)**:
Change the workflow-controller deployment yaml to specify an argoexec image in a private respository, and all workflows will fail, being unable to pull that image.

**Anything else we need to know?**:
Nope

**Environment**:
- Argo version:
```
$ argo version
argo: v2.4.2
  BuildDate: 2019-10-21T18:39:29Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-10-15T19:18:23Z"
  compiler: gc
  gitCommit: c97fe5036ef3df2967d086711e6c0c405941e14b
  gitTreeState: clean
  gitVersion: v1.16.2
  goVersion: go1.12.10
  major: "1"
  minor: "16"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-08-19T11:05:50Z"
  compiler: gc
  gitCommit: 2d3c76f9091b6bec110a5e63777c332469e0cba2
  gitTreeState: clean
  gitVersion: v1.15.3
  goVersion: go1.12.9
  major: "1"
  minor: "15"
  platform: linux/amd64

```

**Other debugging information (if applicable)**:

**Comment by alexec** [comment]
I've just merged changes to master that allow you to run your own container locally and write e2e tests for it, does this help:

https://github.com/argoproj/argo/blob/master/test/e2e/README.md#to-update-the-executor

**Comment by alexec** [comment]
You should be able to set the `executor` configmap item. Please let me know if this does not work for you.
