### ISSUE TITLE
Add template name filter to jobs global search

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-workflows#184]
Add 'template' filter to  jobs global search. 

- Filter should allow to select one or multiple template names from dropdown multi-select.
- List of unique template names might be loaded using `/v1/templates?fields=name&dedup=true`

**Comment by wokeGit** [comment]
Working on it

**Comment by wokeGit** [comment]
@alexmt 
Filter is implemented. The only issue is that API doesn't support filter by multiple template name

https://dev.applatix.net/v1/services?task_only=true&limit=11&template_name=Argo%20CI,argo-checkout&fields=name,status,status_string,username,commit,repo,branch&search_fields=name,description,status_string,username,repo,branch

Above call returns only values for first template name.

**Comment by wokeGit** [comment]
@alexmt 
Update
I checked one more time and I was wrong. API works correct.
