### ISSUE TITLE
Label workflow-created PVC the same way as Pods

### ISSUE THREAD

**Issue by jamhed** [argoproj/argo-workflows#1887]
# Motivation

It's not easy to select workflow PVC with only ownerReference, and using naming ($workflow-name-$pvcname) convention is not reliable and differs from how pods and other objects are selected.

# Proposal

By labeling PVC the same way as Pods.

**Comment by jamhed** [comment]
https://github.com/jamhed/argo/commit/dd42981c7b2b25460a356ac482e879d3c0786575

**Comment by simster7** [comment]
Feel free to open a PR!

**Comment by jamhed** [comment]
@simster7 Is it okay for `Default - Argo CI` check to fail? I was unable to figure out the reason.
