### ISSUE TITLE
CLI image does not have a "cat" command for kubernetes usage

### ISSUE THREAD

**Issue by tandeday** [argoproj/argo-workflows#1914]
The CLI image only contains the argo command which does not have an option to do a wait forever, which the kubernetes agent in Jenkins needs to if it is to be used in a build pipeline.

Adding this (a cat or a busybox or similar) will allow us to use it directly.  Right now we curl the binary from our server and would rather use the native image.

**Comment by alexec** [comment]
Could you use `sleep 9999` too?

**Comment by m86194** [comment]
There is no "sleep" command in the image.  Why the bug->enchantment alteration?  It is a bug for anyone who needs to use this in a kubernetes based build.

**Comment by alexec** [comment]
You could build your own image if you need this. Building on a different base image would increase the threat surface of the CLI.

**Comment by alexec** [comment]
Won't fix.
