### ISSUE TITLE
Introduce exit handler vairable to be filled with the name and output of step failed

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#1994]
# Summary

Introduce exit handler vairable to be filled with the name and output of step failed

# Motivation

As suggested on Slack:

> Trying to write a "generic" exit-handler that can pull out the information about what task failed (maybe its stderr, or something like that) and give me a nice email/slack message 

# Proposal

Introduce exit handler vairable to be filled with the name and output of step failed

---
**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Due to the overwhelming interest in this PR, I took it over to make sure it is included in 2.5

**Comment by alexec** [comment]
@simster7 this is a new feature and therefore kind of a bit late for v2.5, lets push it to v2.5 and speak to @mukulikak about priority

**Comment by alexec** [comment]
@nmaludy  and everyone else - can you please review what @simster7 has done in the PR and see if it suites your needs. For example:

Is it enough information for your Slack messages? I'd suggest you might want to event write a workflow that demonstrates this.
