### ISSUE TITLE
Ability to only archive workflows in a certain state

### ISSUE THREAD

**Issue by danxmoran** [argoproj/argo-workflows#2000]
# Summary

Based on the community meeting and the example manifests [here](https://github.com/argoproj/argo/blob/master/manifests/quick-start/postgres/overlays/workflow-controller-configmap.yaml#L21), it sounds like workflows will be auto-archived if they enter any terminal state. I think it'd be more valuable to have a configurable list of workflow states that trigger the auto-archive.

# Motivation

My workflows generate ~large persistent volumes, with ownership set so the volumes get deleted when the workflow is deleted. It'd be ideal if I could configure the Argo server to:
1. Auto-archive workflows as they succeed
2. Auto-delete archived workflows (#2001)

That way volumes get cleaned up automatically in the happy path, but they're kept around for retries when things fail.

# Proposal

I'm not sure about the internals, but at the config level I'd expect to see something like this:
```yaml
persistence:
  archive:
    # Default: []
    # Alt default: [succeeded, failed]
    states: [succeeded]
```

---
**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
cc @alexec

**Comment by alexec** [comment]
I think this can be done using archive strategy.
