### ISSUE TITLE
Argo server should support controller instance ids

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-workflows#2004]
# Summary

The workflow controller has a feature in which it can be configured with an "instance ID", which means it only operates on workflows with a specific label. The purpose of this feature is to allow multiple controllers to run in the same cluster, but sharded with a specific purpose (testing vs. ML), using different artifact repositories, etc....

Since the Argo API server is so closely tied to the controller, even relying on the same config map, it is also required that the API server also be able to filter out workflows with an instance ID. Meaning it would only be displaying workflows with the server configured instance id.

Similarly, there probably needs to be a feature such that any create requests of workflows going through the Argo API server, may want to automatically fill in an instance ID with the one that the API server is configured with. Going further, it may also desired to **enforce** instance IDs at the Argo API server (i.e. do not allow workflows with alternative or empty instance ids from being created).

I also am unsure what impact this feature has on workflow archiving. We may need to have workflow controller instance ID as a column in the database.

**Comment by alexec** [comment]
We should also update e2e tests to use instance ID: #2005
