### ISSUE TITLE
Download artifacts using CLI

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#2061]
# Summary

It is not possible to download artifacts using the CLI. You have to use the UI or know where you're storing them. 

# Motivation

TBD

# Proposal

Provide the following CLI commands:

* `argo artifact list WORKFLOW -o wide|json|yaml` - should support output formats
* `argo artifact get WORKFLOW NODE_ID ARTIFACT_NAME` - should it just create the file? output to stdout?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by samath117** [comment]
Given that artifacts can be directories, passing a local path to copy the artifact to seems best.

**Comment by alexec** [comment]
Duplicate of #695.
