### ISSUE TITLE
Dogfood

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#2076]
# Summary

Automatically deploy the latest Argo Workflows in a way that forces us to use it is day-to-day basic.

# Motivation

So we feel the pain of problems.

# Proposal

Not sure. The challenge is that unlike Argo CD, we do not consume this ourselves.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by logicfox** [comment]
A possible option is to migrate CI from CircleCI to Argo workflows. If ArgoCD is running in a Kubernetes cluster, can't that cluster be re-used for running the CI workflows?

**Comment by alexec** [comment]
We've discussed using Argo Workflows as our CI, but that is actually what Argo CI, and don't developer that anymore. But we could revisit it.

I'd love to be running some ML workloads on it.
