### ISSUE TITLE
Restart Argo Server when config map changes

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#2090]
# Summary

The workflow controller listens to config map changes and reconfigures when it changes.

# Motivation

The Argo Server does not and would continue to read and write to the persistence etc if we do not restart.

# Proposal

Not sure.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@jessesuen @sarabala1979 thoughts on this?

**Comment by simster7** [comment]
As well as the `workflow-controller`, correct?

**Comment by alexec** [comment]
> As well as the `workflow-controller`, correct?

I believe the controller already re-configures itself.
