### ISSUE TITLE
More information on the CronWorkflow UI page

### ISSUE THREAD

**Issue by rmgpinto** [argoproj/argo-workflows#2099]
# Summary

Add more information on the CronWorkflow page to understand run status.

# Motivation

Get a faster indication of the status of CronWorkflow runs.

# Proposal

Add two items on each CronWorkflow on the UI:

- The last time the CronWorkflow ran
- A visual indication of the number of tasks that ran and if they were successful or not (like Airflow)

Thanks

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Thanks for the suggestion. Would you consider submitting a PR?

**Comment by xinbinhuang** [comment]
I think this one #3774 can also belong here.

**Comment by alexec** [comment]
I think this is fixed.
