### ISSUE TITLE
Support multi level nesting of workflow templates

### ISSUE THREAD

**Issue by saimadineni** [argoproj/argo-workflows#2175]
# Summary

Currently argo workflows support single level of nesting for argo workflow templates. It'd be great if multi level nesting of argo workflow templates is supported.

# Motivation

Currently we use Tidal heavily for orchestrating batch jobs. And, we are considering replacing argo workflows with Tidal. And, one of the main limitations for replacing Tidal is lack of multi level nesting across multiple workflow templates.

For example, I've three different workflows A, B and C.

Where a step in A depends on B and a step in B depends on C.

# Proposal

How do you think this should be implemented?

I don't have a recommendation for how this should be done.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
#2007 might fix this

**Comment by agilgur5** [comment]
> Currently argo workflows support single level of nesting for argo workflow templates. It'd be great if multi level nesting of argo workflow templates is supported.

I'm not sure since when this has been possible, but with `templateRef` you can do as much referencing of WorkflowTemplates as you want.
