### ISSUE TITLE
RFC: Custom, step-level, and usage metrics

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#2203]
Hello everyone, I wanted to provide an update on the status of step-level metrics and custom metrics (#1853). We decided that the original scope of the PR had to be rethought and reworked, so we have kicked it off the 2.5 release and are now working to make it a main feature of the 2.6 release. Furthermore, we are exploring integrating #1066 into this PR.

I would like this ticket to serve as a "request for comment"<sup>1</sup>. I will be updating this with the most recent ideas from us and the community<sup>2</sup> as the discussion progresses.

### Potential features:

1. Emit step-level metrics in the same style as workflow-level metrics (#1539)
1. Add ability to emit custom (i.e. metrics defined by a user within a pod) metrics with customizable metric suffix and metric labels (#1539)
1. Emit step-level and workflow-level usage cost approximations (#1066)
1. Save custom metrics to the workflow archive (#2144)
1. _Have other ideas? Please add a comment_

### Things to consider:

1. Consider the impact of high cardinality of metric labels, perhaps allowing the option to opt in/out of step-level metrics (https://github.com/argoproj/argo/pull/1853#issuecomment-583358471)
1. Consider how workflow TTL affects metrics ([slack discussion](https://argoproj.slack.com/archives/C8J6SGN12/p1580765908276200?thread_ts=1580750477.250500&cid=C8J6SGN12))
1. _Something else we should consider? Please add a comment_

### Implementation:

[RFC/Design Doc](https://docs.google.com/document/d/1uK9S8IVpFTKDma6yhQRMtd1N5jgbUzaM-f7aImUz2GA/edit?usp=sharing)

---
<sup>1</sup> Perhaps a bit of a misnomer, since we are asking the community to help guide its design as opposed to just comment on one that has been finished.
<sup>2</sup> A huge thanks to @ddseapy, @mark9white, @andrewgeller, and anyone else who has contributed their ideas and comments so far.

**Comment by dseapy** [comment]
A couple other questions,

* How (if at all) should this relate to the desire for within-step/real-time metrics? (ie. https://github.com/argoproj/argo/issues/1658)  Could work done here be re-used at all for that use-case, or would it be handled completely separately?
* For users that care primarily about custom workflow-level metrics as opposed to step-level metrics, does the solution work well for them as well?  I'm guessing it would, since step is more granular than workflow?

**Comment by simster7** [comment]
> How (if at all) should this relate to the desire for within-step/real-time metrics? (ie. #1658) Could work done here be re-used at all for that use-case, or would it be handled completely separately?

The implementation as it is currently is not friendly to real-time metrics because it depends on output artifacts, which are evaluated only once.

The way I'm currently thinking about it (and please correct me if I'm wrong) is that there are two different use cases in which metrics in Argo could be collected over time:

1. Collecting metrics about workflows that run multiple times. E.g.: “I run workflow XYZ multiple times a day, and I’m interested in how a metric of workflow XYZ changes over every subsequent execution”

2. Collecting information about individual workflows while they are executing. E.g.: “I am currently running workflow XYZ and I am interested to see how a particular metric is changing over time while it runs”

The current implementation is geared to solving use case 1 and will not work well (or at all) with use case 2. If both use cases are equally prevalent (as I would assume they would be), a rework of the implementation would be in order to fit both of their requirements.

> For users that care primarily about custom workflow-level metrics as opposed to step-level metrics, does the solution work well for them as well? I'm guessing it would, since step is more granular than workflow?

Currently yes, because metrics are exported from output artifacts. If a rework is necessary, then I'll make sure that this is true of the new implementation as well.

**Comment by simster7** [comment]
Updated issue with [RFC/Design Doc](https://docs.google.com/document/d/1uK9S8IVpFTKDma6yhQRMtd1N5jgbUzaM-f7aImUz2GA/edit?usp=sharing)
