### ISSUE TITLE
Dockerfile.dev doesn't build

### ISSUE THREAD

**Issue by lfdversluis** [argoproj/argo-workflows#2229]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
Running `docker build -f Dockerfile.dev . -t argodev --no-cache` doesn't work
**What you expected to happen**:
It building a docker image

**How to reproduce it (as minimally and precisely as possible)**:
Clone the latest repo and run `docker build -f Dockerfile.dev . -t argodev --no-cache`
**Anything else we need to know?**:

**Environment**:
- Argo version: latest commit `170abfa5`

**Logs**
```
Step 16/26 : COPY argoexec /usr/local/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder723807660/argoexec: no such file or directory
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
That is correct. You cannot build this directly. It must be invoked by one of the make targets. Eg ‘make executor-image’

**Comment by lfdversluis** [comment]
Alright, if it's intended I am closing this one.
