### ISSUE TITLE
Make workflow.parameters accessible as a JSON string

### ISSUE THREAD

**Issue by samath117** [argoproj/argo-workflows#2242]
# Summary

Just like how `inputs.parameters` gives all input parameters to a template as a JSON string, `workflow.parameters` should give access to all workflow parameters to the template as a JSON string.

# Motivation

I would like to write a general reporting template which records that a workflow was started, along with all of its parameters. As is, I need to know what all of the workflow parameters are to write this step, so I can't make it general.

# Proposal

How do you think this should be implemented?

Seems like it should be fairly straightforward given that `inputs.parameters` and `workflow.parameters.<NAME>` already exist.

---
**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by paulm-jones** [comment]
A question on this if I may please, @simster7. I am wondering If I have misunderstood the intention of the feature.

When I echo `workflow.parameters` within a task, I was expecting to get back a JSON string representing the entire parameter structure (its keys and values).

What I get is a JSON_-like_ list of objects with a `name` key representing the names of the arguments provided to the workflow, i.e.

#### input.yaml:
In my input, some variables are primitive strings, some are lists and some are maps.

```yaml
foo: 1
bar: 2
```
#### WorkflowTemplate:
```yaml
  arguments:
    parameters:
      - name: foo
      - name: bar
```

#### `echo {{workflow.parameters}}`
```json
[{name:foo},{name:bar}]
```

It looks like, from the test in the PR, that I should get the values too? I'm on argo 2.9.3 - can raise a new issue if you think it is worth investigating.
