### ISSUE TITLE
Archived Workflow Search and Views

### ISSUE THREAD

**Issue by srivathsanvc** [argoproj/argo-workflows#2321]
# Summary
Have the ability to search in the workflow history, for specific queries such as:

- Sort the workflows by start / finish time
- Filter by status (scheduled / completed / error etc.)
- View workflow details, such as links to logs, pod information etc.

# Motivation
ML workflows for training, batch inference etc. run on multiple triggers - timed (schedule) trigger, event trigger (arrival of a file, completion of another workflow, etc.). These workflows run 24x7, in an unattended manner.

Teams have a need to look back at the history of workflow runs for various reasons, such as:
- Why did a particular workflow fail?
- My model was trained over the weekend. Why? What triggered it?
- What data was produced as a result of the workflow run?
- Workflow runs in the last few days have been taking longer and longer. What is going on?

# Proposal
There should be a location in the Argo UI for previous workflow executions. This page should allow for various search capabilities within the list of prior workflows.

Clicking into a particular workflow should show a read-only view of the workflow with all the details that would normally be visible if the workflow was currently in progress. From here, a user can either clone the workflow, re-run the same workflow etc.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
I think we should probably treat this as an EPIC and break it up into about 5 smaller items.

**Comment by mark9white** [comment]
Note that it would also be useful to be able to find/filter by label.

**Comment by alexec** [comment]
This should be via the UI.

**Comment by alexec** [comment]
This needs to be for both live workflows and archived workflows.

**Comment by alexec** [comment]
Broken up into smaller issues.
