### ISSUE TITLE
Step restart on workflow retry

### ISSUE THREAD

**Issue by markterm** [argoproj/argo-workflows#2334]
# Summary

In the situation of a workflow termination then retry, we may want certain step groups to rerun from the beginning if they haven’t already succeeded.

# Motivation

If you have a stepgroup with a step that creates data and a node that consumes that data that need to run close to each other in time.

# Proposal

I’m thinking we could have a boolean flag in the spec against any ‘Steps’ nodes to enable this behavior. I will code this on approval of the concept.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by mark9white** [comment]
My specific suggested implementation in detail is:
- add RestartOnWorkflowRetry as a boolean to RetryStrategy
- In RetryWorkflow in util.go:
  - we iterate through wf.Status.Nodes finding any that are of Retry type and have RestartOnWorkflowRetry enabled
  - we recursively build a list of all children of these nodes
  - we skip all of those children in the deep copy of the workflow
