### ISSUE TITLE
Git artifact should support username input with ssh authentication

### ISSUE THREAD

**Issue by Mohjive** [argoproj/argo-workflows#2339]
# Summary
When cloning using ssh with git input artifact it should be possible to supply a custom username

# Motivation
Not all git servers are configured using the "git" user as is hardcoded in git artifact.

# Proposal
A solution would be to use username as defined by usernameSecret

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
I think this is fixed in `:latest`. Please let me know if not.
