### ISSUE TITLE
can't access web-ui

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-workflows#2354]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
I cannot access the workflows via the web-ui.

**What you expected to happen**:
1) install argo as directed in quick-start *on remote cluster*
2) kubectl -n argo port-forward deployment/argo-server 2746:2746
3) connect via localhost:2746
4) View workflows 

**How to reproduce it (as minimally and precisely as possible)**:
Do the above on a remote cluster.
Works on minikube, and I can see the grpc calls in the logs. Which I can't on a remote cluster. Makes me believe that grpc is not getting to the cluster. 
Also works if I start argo server locally and go to localhost:2746 

**Anything else we need to know?**:
error is http 503.

**Environment**:
- Argo version:
```
$ argo version 
argo: vv2.5.2+4b25e2a.dirty
  BuildDate: 2020-02-24T22:50:01Z
  GitCommit: 4b25e2ac1d495991261e97c86d211d658423ab7f
  GitTreeState: dirty
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64

2.6.0 on server
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2020-02-13T18:06:54Z"
  compiler: gc
  gitCommit: 06ad960bfd03b39c8310aaf92d1e7c12ce618213
  gitTreeState: clean
  gitVersion: v1.17.3
  goVersion: go1.13.8
  major: "1"
  minor: "17"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-08-19T11:05:50Z"
  compiler: gc
  gitCommit: 2d3c76f9091b6bec110a5e63777c332469e0cba2
  gitTreeState: clean
  gitVersion: v1.15.3
  goVersion: go1.12.9
  major: "1"
  minor: "15"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get <workflowname>
```
- executor logs:
```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Logs**

```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Do you see anything on your browser console? How about network tab?
