### ISSUE TITLE
Config value not taking special character

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo-workflows#236]
In v1.0.0 cannot use @ in the value of a config

**Comment by pratulw** [comment]
Tian can you check what would be needed for this.

**Comment by sytianhe** [comment]
I believe this is fixed in the master. Will cherry pick to 1.0

**Comment by wokeGit** [comment]
@sytianhe The commit that you mentioned is what you looking for. This change allows to use any sign in input. It's already on the master branch.
![screen shot 2017-09-21 at 15 15 26](https://user-images.githubusercontent.com/13086525/30697558-bd0aad14-9edf-11e7-971c-84bc928eaadb.png)

**Comment by sytianhe** [comment]
Thanks @wokeGit , I will cherry pick into branch/1.0

**Comment by alexmt** [comment]
Looks like fix is already in 1.0
