### ISSUE TITLE
Workflow archiving fails, difficult to diagnose why

### ISSUE THREAD

**Issue by danxmoran** [argoproj/argo-workflows#2382]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
Workflow archiving is enabled in my controller, but I've never seen a workflow be successfully archived. I just enabled debug logging and now I can see:
```
time="2020-03-06T17:22:48Z" level=debug msg="Archiving workflow" labels="map[workflows.argoproj.io/completed:true workflows.argoproj.io/cron-workflow:clinvar-ingest workflows.argoproj.io/phase:Succeeded]" uid=6c9910b9-52b3-448d-afbb-f1f509ceba78
time="2020-03-06T17:22:48Z" level=error msg="Failed to archive workflow" err="pq: current transaction is aborted, commands ignored until end of transaction block" namespace=clinvar workflow=clinvar-ingest-hvkkv
```

**What you expected to happen**:
I expected archiving to work as long as I set `archive: true` in the controller's `persistence` config, since that's all the documentation mentions. Short of that, I'd want some more error logging to help me diagnose what's wrong with my setup.

**How to reproduce it (as minimally and precisely as possible)**:
This is happening reliably in my team's environment. We're running Argo on GKE, against a Postgres 9.6 DB running in Google CloudSQL. We're connecting to the DB via a `cloudsql-proxy` deployment in the same cluster.

**Anything else we need to know?**:
We also have `nodeStatusOffLoad: true` set in our config. As far as I can tell that's been working fine, but we might not have run a big enough workflow to hit that functionality yet.

**Environment**:
- Argo version: 2.6.1
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2020-01-18T23:33:14Z"
  compiler: gc
  gitCommit: 2e808b7cb054ee242b68e62455323aa783991f03
  gitTreeState: clean
  gitVersion: v1.15.9
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-01-29T19:27:22Z"
  compiler: gc
  gitCommit: 2ccf2c797713077f4a3d0f87c4b4bae725362326
  gitTreeState: clean
  gitVersion: v1.15.8-gke.3
  goVersion: go1.12.12b4
  major: "1"
  minor: 15+
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
@alexec should take the first stab at this

**Comment by danxmoran** [comment]
One thing I'd suggest is changing [this log](https://github.com/argoproj/argo/blob/master/persist/sqldb/workflow_archive.go#L64) from debug-level to info-level. When I was first trying to diagnose the issue I saw the log statement but didn't notice the level, so I was convinced the controller wasn't even attempting to archive things.

I've updated my deployment to include `UPPERIO_DB_DEBUG=1` in the environment. Next time I see a failure, I'll see if anything useful shows up in the SQL logs.

**Comment by danxmoran** [comment]
Found it! `pq: relation "argo_archived_workflows_labels" does not exist` is the real error. It's triggered by a strange query that might be upper.io doing something:
```
2020/03/08 20:07:57
        Session ID:     00148
        Transaction ID: 00145
        Query:          SELECT "pg_attribute"."attname" AS "pkey" FROM "pg_index", "pg_class", "pg_attribute" WHERE (pg_class.oid = '"argo_archived_workflows_labels"'::regclass AND indrelid = pg_class.oid AND pg_attribute.attrelid = pg_class.oid AND pg_attribute.attnum = ANY(pg_index.indkey) AND indisprimary) ORDER BY "pkey" ASC
        Error:          pq: relation "argo_archived_workflows_labels" does not exist
        Time taken:     0.00236s
        Context:        context.Background
```
Then the following statement in the transaction fails:
```
2020/03/08 20:07:57
        Session ID:     00148
        Transaction ID: 00145
        Query:          INSERT INTO "argo_archived_workflows_labels" ("clustername", "name", "uid", "value") VALUES ($1, $2, $3, $4)
        Arguments:      []interface {}{"default", "workflows.argoproj.io/cron-workflow", "316b81a9-e004-45f7-902d-f64b78cc6221", "clinvar-ingest"}
        Error:          pq: current transaction is aborted, commands ignored until end of transaction block
        Time taken:     0.00124s
        Context:        context.Background
```
And the failure there is what's reported out in the logs.

**Comment by alexec** [comment]
It sounds like something went wrong when migrating your workflows. Look for a file named migrate.go to find the SQL to run to create this table.

**Comment by danxmoran** [comment]
Dropping all the tables (including `schema_history`) and rebooting the controller seems to have fixed the write-side of archiving. The UI still isn't showing any records, but I'll dig a bit to make sure nothing's misconfigured and open a separate issue if needed.

Thanks for the help!

**Comment by alexec** [comment]
Thank you @danxmoran . We'll keep an eye on this one.

**Comment by MrSaints** [comment]
I came across this some time around March. I believe it was around the time we upgraded fro 2.5.x to 2.6.x. It was the exact same problem as https://github.com/argoproj/argo/issues/2382#issuecomment-596247011. 

Running:

```sql
create table if not exists argo_archived_workflows_labels (
	clustername varchar(64) not null,
	uid varchar(128) not null,
    name varchar(317) not null,
    value varchar(63) not null,
    primary key (clustername, uid, name),
 	foreign key (clustername, uid) references argo_archived_workflows(clustername, uid) on delete cascade
)
```

Against our postgresql database fixed the issue.

**Comment by Talador12** [comment]
Not sure why, but I have this error too. We had our argo-server running over the weekend , and this came up. I have never interacted with any argo history postgres database, so not sure how to fix or proceed
