### ISSUE TITLE
v2.6.1: argo list --chunk-size truncation should apply after other filters

### ISSUE THREAD

**Issue by samath117** [argoproj/argo-workflows#2420]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.

Summary:

`argo list` takes multiple options which act like filters, like `--since [time]` or `--completed`. It also provides an option `--chunk-size` (default 500) which truncates the list. However, these two operations happen in the wrong order: First the list is truncated (sorted alphabetically), then the list is filtered. Since the purpose of `--chunk-size` is to limit the size of the output, these two should happen in the opposite order.

In my situation, I discovered this entirely by accident, and it took me a while to figure out what was going wrong. I exceeded 500 workflows in a namespace, and then `argo list` started silently dropping my workflows that were after the 500th alphabetically. I obviously eventually figured this out, but it was a really bad UX to have `argo list` just stop working on me.

A simpler alternative might be for `--chunk-size` to have a default of 0, so users like me don't accidentally stumble into this problem in this way.

I'm also not sure that `--chunk-size` is working the way it should -- I just get as output the first 500, not all of them in chunks. If I'm supposed to be using it differently, there should be better documentation on that.

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by changhc** [comment]
I'd like to take this ticket

**Comment by thundergolfer** [comment]
> I'm also not sure that --chunk-size is working the way it should -- I just get as output the first 500, not all of them in chunks. If I'm supposed to be using it differently, there should be better documentation on that.

I agree with this. Just upgraded to `2.6.1` from `2.4.something` and think it's not right that `--chunk-size` has changed behaviour to truncate the list. 

Is this issue changing things such that you have to use `--continue` to get it to return the full list? I would've thought that `--chunk-size` should keep it's old behaviour, or has `kubectl` itself changed the behaviour of its `--chunk-size` option? https://github.com/argoproj/argo/issues/2820
