### ISSUE TITLE
Add `Conditions` to workflow status

### ISSUE THREAD

**Issue by seaneagan** [argoproj/argo-workflows#2421]
# Summary

Add `Conditions` to workflow status.

# Motivation

From the [kubernetes api conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties):

> Some resources in the v1 API contain fields called phase, and associated message, reason, and other status fields. The pattern of using phase is deprecated. Newer API types should use conditions instead.

This would facilitate using e.g. `kubectl wait` to wait for workflows:

`kubectl wait --for=condition=complete workflow/myworkflow`

The `argo wait` command UI is very nice, not sure if it's possible to get any similar experience with `kubectl wait`. But where `kubectl wait` is handy, is if you are trying to wait on a data drive list of resources, some of which may be workflows, some jobs, or any other type of resource for certain conditions, which our team is looking to do.

# Proposal

Add a `Conditions` field to workflow status, which includes at least a `completed` or similar condition, and whatever other conditions may make sense. Deprecate the `phase` etc. fields in status which are superceded by `Conditions`.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
great idea! we put the status is a label currently, so you'd just need to figure out how to get that into the status

**Comment by NikeNano** [comment]
I would be happy to help out with this issue @seaneagan , will start to look at it. How do I assign my self to this issue @alexec?

**Comment by alexec** [comment]
Assigned!
