### ISSUE TITLE
Fix flakey test: `TestPendingRetryWorkflowWithRetryStrategy` 

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#2446]
This test is failing master builds. It looks like the test is flakey rather than incorrect.

This test was introduced in #2385.

**Comment by alexec** [comment]
@jamhed I think you introduced the test? Before we disable it, do you want to investigate? 

The first actually failing build appears to be the one after yours, but as that is UI only changes, it cannot be that one:

Failures

* https://circleci.com/gh/argoproj/argo/9235
* https://circleci.com/gh/argoproj/argo/9238

**Comment by alexec** [comment]
Argo builds have become unstable on master. As previously, Ive enabled "Require branches to be up to date before merging". The flakey  test is TestPendingRetryWorkflowWithRetryStrategy . 

@whynowy @sarabala1979 @simster7

**Comment by simster7** [comment]
I own this test, I’ll self assign.

**Comment by simster7** [comment]
@alexec The flakey-ness of this test is because of this line:

https://github.com/argoproj/argo/blob/32fc2f78212d031f99f1dfc5ad3a3642617ce7e7/test/e2e/fixtures/e2e_suite.go#L103-L104

From the sack trace:
```
...
            github.com/argoproj/argo/test/e2e/fixtures.(*E2ESuite).DeleteResources(0xc000a0c3f0, 0x1f282d2, 0x8)
            	/home/circleci/.go_workspace/src/github.com/argoproj/argo/test/e2e/fixtures/e2e_suite.go:104 +0x1699
...
```

**Comment by simster7** [comment]
The test passes reliably in my local machine. Thoughts?

**Comment by alexec** [comment]
> TODO - may make tests flakey

😂

**Comment by alexec** [comment]
That code is several weeks old and this test has only just started failing the exact commit the PR was merge at. 

But, that comment is clear about it, so leave it with me.

**Comment by simster7** [comment]
Test is currently being skipped
