### ISSUE TITLE
Show environment variables in Argo UI

### ISSUE THREAD

**Issue by theomessin** [argoproj/argo-workflows#2471]
# Proposal

Set environment variables should be shown in the containers tab of the UI.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Sounds like a great idea - would you like to submit a PR?

**Comment by theomessin** [comment]
@alexec I tried #2472

**Comment by ddseapy** [comment]
I think this feature would be very helpful.  I do have a couple questions wrt to security - mostly just want to make sure they are considered:

Do we expect sensitive data (ie. passwords) to be provided to containers via environment variables?  And if so, are we expecting those accessing the UI to be allowed visibility on those?

**Comment by theomessin** [comment]
@ddseapy that's a good point there. Someone from the Argo team should answer what we should expect. A quick and dirty fix to this is to filter any environment variable for which the name contains words such as `KEY`, `TOKEN`, `PASS`, etc. and censor the value in the UI.
