### ISSUE TITLE
UI enhancement for cluster scoped workflowtemplate

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#2480]
# Summary

What change you think needs making.

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

How do you think this should be implemented?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@sarabala1979 please close if done.

**Comment by sarabala1979** [comment]
#2525
