### ISSUE TITLE
FATA[0000] invalid configuration: no configuration has been provided

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-workflows#2492]
I downloaded three binaries from  https://github.com/argoproj/argo/releases
curl -sLO  https://github.com/argoproj/argo/releases/download/v2.7.0-rc1/argo-linux-amd64
curl -sLO  https://github.com/argoproj/argo/releases/download/v2.6.3/argo-linux-amd64
curl -sLO https://github.com/argoproj/argo/releases/download/v2.4.3/argo-linux-amd64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
argo/2.7.0-rc1$ ./argo-linux-amd64 list --kubeconfig ~/.kube/k8s-kubeconfig.yaml
FATA[0000] invalid configuration: no configuration has been provided 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
argo/2.6.3$ ./argo-linux-amd64 list --kubeconfig ~/.kube/k8s-kubeconfig.yaml
FATA[0000] invalid configuration: no configuration has been provided 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
argo/2.4.3$ ./argo-linux-amd64 list --kubeconfig ~/.kube/k8s-kubeconfig.yaml 
NAME   STATUS   AGE   DURATION   PRIORITY
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
out of these binaries only binary with v2.4.3   is working.

**Comment by ctext** [comment]
```
/argo$ find ./ -type f| xargs -n1 -I{} sh -c "echo {};{} --kubeconfig /home/wiki/.kube/k8s-kubeconfig.yaml list"                             
./2.5.0/argo-linux-amd64
NAME                     STATUS      AGE   DURATION   PRIORITY
fantastic-python-s9l4d   Succeeded   1h    4s         0
./2.5.1/argo-linux-amd64
NAME                     STATUS      AGE   DURATION   PRIORITY
fantastic-python-s9l4d   Succeeded   1h    4s         0
./2.5.2/argo-linux-amd64
NAME                     STATUS      AGE   DURATION   PRIORITY
fantastic-python-s9l4d   Succeeded   1h    4s         0
./2.4.3/argo-linux-amd64
NAME                     STATUS      AGE   DURATION   PRIORITY
fantastic-python-s9l4d   Succeeded   1h    4s         0
./2.6.0/argo-linux-amd64
NAME                     STATUS      AGE   DURATION   PRIORITY
fantastic-python-s9l4d   Succeeded   1h    4s         0
```
###With error
**./2.7.0/argo-linux-amd64**
FATA[0000] invalid configuration: no configuration has been provided
**./2.6.2/argo-linux-amd64**
FATA[0000] invalid configuration: no configuration has been provided
**./2.6.1/argo-linux-amd64**
FATA[0000] invalid configuration: no configuration has been provided
**./2.6.3/argo-linux-amd64**
FATA[0000] invalid configuration: no configuration has been provided

**Comment by alexec** [comment]
I Googled `invalid configuration: no configuration has been provided` and found many related to other projects, not Argo. I think this might be something with your set-up.

Can you try `kubectl get ns` and see what that returns?

**Comment by ctext** [comment]
@alexec i'm facing this error with the following version 
argo-linux-amd64  v2.7.0-rc1   
argo-linux-amd64  v2.6.2   
argo-linux-amd64  v2.6.1
argo-linux-amd64  v2.6.3

and i'm currently using v2.6.0  argo-linux-amd64 and its working fine
```
argo version
argo: v2.6.0
  BuildDate: 2020-02-28T23:32:26Z
  GitCommit: 5d3bdd56607eea962183a9e45009e3d08fafdf9b
  GitTreeState: clean
  GitTag: v2.6.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
i'm using debian 10. If few binaries are usable using --kubeconfig  flag , is it still possible there is some problem in my setup. I downloaded these binaries on another debian machine and got same results.

**Comment by ctext** [comment]
@alexec 
```
kubectl get ns
NAME              STATUS   AGE
argo              Active   37h
default           Active   38h
kube-node-lease   Active   38h
kube-public       Active   38h
kube-system       Active   38h
```

**Comment by alexec** [comment]
does it work without the flag?

**Comment by ctext** [comment]
I rechecked and all binaries are detecting config file  if k8-config-file is placed at ~/.kube/config  

But few are working if you manually specify config file location using --kubeconfig  flag

**Comment by ozankabak** [comment]
I have the same issue.

**Comment by alexec** [comment]
@sarabala1979 this is your area of expertise?

**Comment by ozankabak** [comment]
For anyone who may find it helpful: My current workaround is to use the `KUBECONFIG` environment variable instead of the `--kubeconfig` command-line argument. So I invoke the CLI via:
```
KUBECONFIG=/path/to/kubeconfig argo ...
```

**Comment by Madurad** [comment]
Hi, I'm also facing the same issue, when I try to attach my kubeconfig I get the following error now,

`argo version --kubeconfig /mnt/c/Users/madur/.kube/config`

error :
`FATA[0000] invalid configuration: [unable to read client-cert /mnt/c/Users/madur/.kube/C:\Users\madur\.minikube\profiles\minikube\client.crt for minikube due to open /mnt/c/Users/madur/.kube/C:\Users\madur\.minikube\profiles\minikube\client.crt: no such file or directory, unable to read client-key /mnt/c/Users/madur/.kube/C:\Users\madur\.minikube\profiles\minikube\client.key for minikube due to open /mnt/c/Users/madur/.kube/C:\Users\madur\.minikube\profiles\minikube\client.key: no such file or directory, unable to read certificate-authority /mnt/c/Users/madur/.kube/C:\Users\madur\.minikube\ca.crt for minikube due to open /mnt/c/Users/madur/.kube/C:\Users\madur\.minikube\ca.crt: no such file or directory]`

I tried the solution from @ozankabak but same output.

`FATA[0000] invalid configuration: no configuration has been provided`

**Comment by alexec** [comment]
Please make sure you have the latest version of the CLI.

**Comment by Madurad** [comment]
@alexcapras it worked for me the version: argo: v3.0.4, thanks a lot for the help 👍
