### ISSUE TITLE
Display the service templates that are associated with each commit

### ISSUE THREAD

**Issue by rahuldhide** [argoproj/argo-workflows#259]
UI needs to display the different template versions, that were used to run the workflows.
![commit2template](https://user-images.githubusercontent.com/30275450/30833634-b4b53792-a204-11e7-9c2f-5845bef5a160.png)

**Comment by wokeGit** [comment]
@rahuldhide the template list should contain only templates used at this commit earlier or all the templates available for this particular commit?
