### ISSUE TITLE
UI enhancement to add and update workflow Metadata

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#2652]
# Summary
UI can have UX based form to add and edit metadata fields (namespace, labels and annotation) in workflow submission page. This will help user to edit existing label/annotation and update the namespace. This support mainly helps the user to not mesh up the YAML format 

What change you think needs making.

![image](https://user-images.githubusercontent.com/33908564/78912453-78b55e80-7a3c-11ea-819e-0af5a9e76c59.png)

**Comment by alexec** [comment]
I think fixed in v3.
