### ISSUE TITLE
Submit workflow template console error

### ISSUE THREAD

**Issue by vrodomista** [argoproj/argo-workflows#2693]
Checklist:

 * [X ] I've included the version.
 * [x] I've included reproduction steps.
 * [X ] I've included the workflow YAML.
 * [X ] I've included the logs.
 
**What happened**:
When attempting to submit a workflow template directly from the workflow template's ui `submit` button, nothing happens and an error pops in console

**What you expected to happen**:
When I press submit workflow on the workflow template's page that it submits a workflow

**How to reproduce it (as minimally and precisely as possible)**:
It's a base install with a private image repo, besides that it's standard. 

**Anything else we need to know?**:

Workflows can submit just fine, cluster workflow templates don't work either (same issue) 

**Environment**:
- Argo version:
```
$ argo version
argo: v2.7.2
  BuildDate: 2020-04-10T19:25:22Z
  GitCommit: c52a65aa62426f5e874e1d3f1058af15c43eb35f
  GitTreeState: clean
  GitTag: v2.7.2
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-10-15T19:16:51Z"
  compiler: gc
  gitCommit: 20c265fef0741dd71a66480e35bd69f18351daea
  gitTreeState: clean
  gitVersion: v1.15.5
  goVersion: go1.12.10
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-11-13T11:13:49Z"
  compiler: gc
  gitCommit: b3cbbae08ec52a7fc73d334838e18d17e8512749
  gitTreeState: clean
  gitVersion: v1.16.3
  goVersion: go1.12.12
  major: "1"
  minor: "16"
  platform: linux/amd64
```

**Other Considerations

Console log:
When submit is clicked, console pops this:
```
Formik.tsx:834 Warning: An unhandled error was caught from submitForm() TypeError: e.props.validate is not a function
    at onSubmit (resource-submit.tsx:31)
    at Formik.tsx:860
    at Formik.tsx:1208
    at Formik.tsx:767
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Hey @vrodomista. Two questions: are you running `2.7.2` or directly off master? The code from the error does not exist in `2.7.2`. However, I fixed this bug in master yesterday via https://github.com/argoproj/argo/pull/2686, so if you're running off master just do a `git pull` and it should be fixed.

**Comment by vrodomista** [comment]
Hey @simster7 , I was installing on k8s via https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml. Behind a corporate vpn so the Images are on a private repository but that's the only change in the yaml. Besides that it's a standard install. Should I just update the image to a more recent sha?

**Comment by simster7** [comment]
Hi @vrodomista seems that the `stable` tag was pointing to a random commit -- I just moved it to point to `v2.7.2`. Can you try again?

**Comment by simster7** [comment]
You can always install a specific version directly too:

```
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v2.7.2/manifests/install.yaml
```

**Comment by vrodomista** [comment]
`kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v2.7.2/manifests/install.yaml` fixed my issue (after updating images on my private docker repo). Seems like it was just a bug of the random version I was on. 2.7.2 is working. Thanks @simster7
