### ISSUE TITLE
Report resource usage (e.g. CPU, memory) per step and workflow

### ISSUE THREAD

**Issue by edlee2121** [argoproj/argo-workflows#2728]
# Summary

Useful to provide a summary of the aggregate CPU and memory used by each step in the workflow, including the workflow overall.

# Motivation

This feature would be useful for estimating the cost of running a workflow and to optimize resource intensive steps in the workflow.

# Proposal

As each container/step finishes, record the resource usage in a DB.
When the workflow is archived, transfer the usage information to the archive.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
This was implemented in #2219 and released in v2.7.
