### ISSUE TITLE
CLI: Improve Unit testing

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#2738]
# Summary

What change you think needs making.

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

How do you think this should be implemented?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Also see #1935

**Comment by simster7** [comment]
> Follow the model used by Argo Rollouts.

This seems like a good place to start

**Comment by simster7** [comment]
Please also consider https://github.com/argoproj/argo/issues/2864 during this

**Comment by sarabala1979** [comment]
#3306
