### ISSUE TITLE
`withArtifacts` loop (fan-out)

### ISSUE THREAD

**Issue by ptitpoulpe** [argoproj/argo-workflows#2758]
# Summary

Add a withArtifacts field to tasks to handle loop over files in an artifact.

# Motivation

You have an archive, and you want to run a workflow over all files inside.

# Proposal

How do you think this should be implemented? No

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
It's not possible to do this natively in Argo Workflows. However, you can do this by having one step that unpacks the artifact and has an output parameters that is a list of the items. This is then used as an input to `withItems`.

**Comment by ptitpoulpe** [comment]
This proposal could resolve my request https://github.com/argoproj/argo/issues/3061

**Comment by xgourmandin** [comment]
Hi, 

I try to implement the solution proposed by alexec but I can't find the correct syntax to achieve it.
Can somebidy give me a little help please ?

**Comment by simster7** [comment]
Closed with `data` template

**Comment by bimtauer** [comment]
Hi @simster7 - will this be released with the 3.1 milestone and is there maybe a pre-release one could test this with? 
Currently with v2.12.9 "data" is still a unknown field. 

Also if you have a moment to explain: How does this new template relate to the other existing/ongoing solutions such as the proposed concept of [withArtifacts](https://github.com/argoproj/argo-workflows/pull/4948#issuecomment-767154659), and key-only artifacts and the [map-reduce example](https://github.com/argoproj/argo-workflows/blob/master/examples/map-reduce.yaml)? 
Is the `data` template meant to cover these use cases once and for all?
