### ISSUE TITLE
Support rollback in order 

### ISSUE THREAD

**Issue by k82cn** [argoproj/argo-workflows#2772]
# Summary & Motivation

We'd like to use Argo to deploy an application with several steps; so if any one of steps failed, we'd like to rollback the worklfow in revert order.

# Proposal

No proposal right now; but it's better to provide some plugins machinary to do that.

**Comment by alexec** [comment]
I think you need to raise this is the Argo CD repository?

**Comment by junneyang** [comment]
> I think you need to raise this is the Argo CD repository?

why, i think rollback should be supported in argo-workflow
