### ISSUE TITLE
argo list does not show workflows from all instances or accept --instanceid 

### ISSUE THREAD

**Issue by benabineri** [argoproj/argo-workflows#2780]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs. (N/A - can do if necessary.)
 
**What happened**:
We have deployed an argo 2.7.3 workflow controller with an instance ID in the configmap alongside a 2.3.0 controller.

`argo list` only shows workflows from the controller with no instance ID (2.3.0) and I can't work out how to get it to show the other workflows (see reproduction steps below.)

`kubectl get workflows` functions as expected.

**What you expected to happen**:

`argo list` could show all workflows, or support the `--instanceid` argument.

**How to reproduce it (as minimally and precisely as possible)**:

```
! ~ $ argo submit --instanceid 27 https://raw.githubusercontent.com/argoproj/argo/master/examples/hello-world.yaml
Name:                hello-world-c29t6
Namespace:           whatever-dev
ServiceAccount:      default
Status:              Pending
Created:             Wed Apr 22 16:18:05 +0100 (now)
! ~ $ argo submit https://raw.githubusercontent.com/argoproj/argo/master/examples/hello-world.yaml
Name:                hello-world-xbb22
Namespace:           whatever-dev
ServiceAccount:      default
Status:              Pending
Created:             Wed Apr 22 16:18:14 +0100 (now)
! ~ $ argo list | grep hello-world
hello-world-xbb22      Running     3s     3s         0
hello-world-mbg4n      Succeeded   1d     5s         0
hello-world-jpfbf      Succeeded   142d   18s        0
! ~ $ argo list --instanceid 27
Error: unknown flag: --instanceid
```

**Anything else we need to know?**:

**Environment**:
- Argo version: 2.7.3
```
$ argo version
```
- Kubernetes version :
```
v1.14.9-eks-502bfb
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Are you connecting to the Argo Server - if so you will not see any workflows that the server cannot see.

**Comment by benabineri** [comment]
I don't think so, I tried with that and get connection closed, but it's going through a k8s ingress so that might be something off in our setup:
```
! ~ $ argo --argo-server argo27.xyz.xyz.xyz:443 list
FATA[0000] rpc error: code = Unavailable desc = connection closed 
```

**Comment by alexec** [comment]
Ok  - we don't support #2764 yet for the CLI. This most likely means you're using the CLI in "classic" mode and there is a bug.
