### ISSUE TITLE
Expose Workflow.Spec.ServiceAccountName as global workflow.serviceAccountName

### ISSUE THREAD

**Issue by seddonm1** [argoproj/argo-workflows#2794]
# Summary

Similar to the `workflow.namespace` it would be useful to the expose the execution context `ServiceAccountName` as a global variable to allow passing this information to templates.

# Motivation

Because `ServiceAccountName` is used to control permissions it can be useful to add to logs or use for logic in child containers when debugging issues such as access control lists.

# Proposal

This is a very small change to expose `*wfv1.Workflow.Spec.ServiceAccountName` as `workflow.serviceAccountName` which has been built and tested and a PR can be submitted if this proposal is accepted.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Feel free to submit a PR

**Comment by simster7** [comment]
Closed in #2794
