### ISSUE TITLE
Allow parameter evaluation on-the-fly with `valueFrom.evaluate` field

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#2802]
# Summary

Add a field `valueFrom.evaluate` that will run the expression through our evaluator after parameter substitution.

# Motivation

Seeing the example in #2801, a Python image is booted up just to add one to a counter on each iteration. This is obviously a waste of resources as it would be easily done by the controller's evaluator.

# Proposal

I'll implement this by running the field through the evaluator after parameter substitution.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by agilgur5** [comment]
I believe this was implemented in #4987 with `valueFrom.expression`.
