### ISSUE TITLE
Aggregate resource duration to step group and workflow level

### ISSUE THREAD

**Issue by salanki** [argoproj/argo-workflows#2843]
# Summary

Calculate and display total workflow resource duration.
# Motivation

The implementation in #2219 gives great visibility to resource demand at individual pod level. Being able to see total resource usage of a workflow in the workflow list in the UI would make the usefulness a magnitude higher. 

# Proposal

The logic of the implementation should be pretty straightforward, sum up all Pod metrics for the workflow. It would be nice to have metrics on step group level as well, and that would work in the same fashion (summarize all pods executed in that step).

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Interested in submitting a PR for this?

**Comment by alexec** [comment]
Resource duration is already aggregate to workflow level. It would be great if you want to write the code to aggregate to DAG/step-group level.

**Comment by salanki** [comment]
So it exists but not displayed in the Web UI then?

**Comment by alexec** [comment]
It is displayed under the "summary" tab in the workflow view.
