### ISSUE TITLE
Fix flakey TestWorkflowRetryNoPersistence

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#2850]
# Summary

This test is flakey because it is using banned image `whalesay` rather than `cowsay:v1`

# Motivation

This should have failed validation in fact. Not sure why it did not.

Can we also find out why this test is a special case? I can't see why this test has a conditional on persistence - it should work fine without it.

# Proposal

* Change image to cowsay.
* Determine why this test case is a special - and hopefully make it non-special.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@mark9white would you like to own this?

**Comment by mark9white** [comment]
Sure, I'll take a look.

**Comment by mark9white** [comment]
It has the conditional on persistence because it needs to read and modify the nodes. I am creating a PR which modifies it to run both in the persistence and non-persistence suites.
