### ISSUE TITLE
Redirect deep-links to workflows redirect to workflows in archive

### ISSUE THREAD

**Issue by logicfox** [argoproj/argo-workflows#2890]
# Summary

If workflow archiving is enabled, can we have deep-links to workflows redirect to the archived workflows?

# Motivation

We use Slack notifications where we deep-link to the workflow. If a workflow is archived, the deep-links fails. The end-user is presented with a blank page without the workflow chart.

# Proposal

How do you think this should be implemented?

Look up workflow by name. If not present, fall back to archives. If neither exist, show error. This is also fine if an alternate page is available in the UI which can take a workflow name (and namespace) as a parameter and looks up in both the active workflows and archived workflows and renders it on screen.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by austinpray-mixpanel** [comment]
We are experiencing some pain around links from our internal users 404ing pretty quickly. @alexec said he'd be interested in a PR, so gonna take a look at implementing this 🔜

**Comment by jmeridth** [comment]
Is this solved by https://github.com/argoproj/argo-workflows/pull/7854 being merged today?  Still waiting on release but curious if so.

**Comment by alexec** [comment]
This is a feature, not a fix. We typcially don't backport features.

**Comment by caelan-io** [comment]
Closed by #7854
