### ISSUE TITLE
Build Workflow dynamically while calling other servers

### ISSUE THREAD

**Issue by merlintang** [argoproj/argo-workflows#2900]
# Summary
Argo controller need the ability to talk with another server

# Motivation
For the workflow template, we would like to store it like a DB, and this template would be easier to manage. As a result, we hope Argo can talk with the DB to get the template information, then build a workflow. Similarly, we would like Argo to talk with our server to check user information in the workflow Yaml. however, these have to be done via outside the certification server. As a result, we hope Argo can provide the hook to other servers while keeping the framework safe and clean. 

# Proposal

How do you think this should be implemented?
Hope to learn advice from you. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
See #2847

**Comment by merlintang** [comment]
@alexec thanks Alex, I would like to see how to do it.

**Comment by agilgur5** [comment]
This can be done by dynamically creating Workflows with the [Workflow-of-Workflows pattern](https://argo-workflows.readthedocs.io/en/release-3.5/workflow-of-workflows/)
