### ISSUE TITLE
Auto generate CLI docs

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#2922]

**Comment by terrytangyuan** [comment]
@simster7 @alexec cobra supports the autogeneration of docs. I can help with this too if needed. Would markdown files be okay?

**Comment by alexec** [comment]
This will be closed by #3369

**Comment by alexec** [comment]
What might be good too is autogeneration of Swagger markdown.

**Comment by alexec** [comment]
https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

**Comment by terrytangyuan** [comment]
Oh cool didn't know that it's already being worked on. 

> What might be good too is autogeneration of Swagger markdown

Do you mean generating markdown from `api/openapi-spec/swagger.json`? Any suggested tools?

**Comment by alexec** [comment]
I actually figured it out:
https://argoproj.github.io/argo/swagger

**Comment by terrytangyuan** [comment]
Nice that looks great!
