### ISSUE TITLE
Workflow list pagination by date completed

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#2926]
# Summary

Paginate workflow lists served by the Argo Server by date completed.

# Motivation

We want to improve performance and scalability by paginating Workflow list queries. To do so, we recently started using K8s API pagination. Problematically for us, K8s API pagination does not support ordering (https://github.com/kubernetes/kubernetes/issues/80602#issuecomment-525762631), leaving us with chunks that are not only unsorted within them, but also across the global list of Workflows.

This is undesirable and a breaking change. Currently, we return sorted Workflow lists to users and returning a virtually randomized Workflow ordering is obviously problematic.

# Proposal

To remedy this, we can paginate Workflows by date completed. Using field selectors, we can leverage the existing K8s API pagination and select Workflows by date completed. We can then sort Workflows within each page on the client-side.

This pagination UX could either be a "Calendar View" as opposed to a list view, or simply have the client keep requesting Workflows for a subsequent day until a list (say, 10 Workflows) is filled. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
See #2938

**Comment by agilgur5** [comment]
> We can then sort Workflows within each page on the client-side.

Noting here that server-side sorting should be possible after #12736

**Comment by agilgur5** [comment]
Per #2896's description, #2895 was opened for sorting, and this issue was closed after _displaying_ the date, but not sorting it
