### ISSUE TITLE
Add Prometheus collection metrics error options

### ISSUE THREAD

**Issue by gethinzhang** [argoproj/argo-workflows#2985]
# Summary

the default behavior of [prometheus golang http error handling](https://github.com/prometheus/client_golang/blob/ce2dae2878aa27d655eaea61569c4d3775252f4e/prometheus/promhttp/http.go#L180) is show a error message in metrics server. These errors including same metrics name or tags

But in argo, workflow is usually submitted by users, if they submit a identical metrics, which would cause whole metrics server panic.

So I provided a option to turn on these error handling 

# Motivation

added 
```
meticsConfig: {
   IgnoreError: true
}
```
to workflow control configmap

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
> But in argo, workflow is usually submitted by users, if they submit a identical metrics, which would cause whole metrics server panic.

What would be the behavior of this when `IgnoreError: true`? Would both identical metrics be shown? Would the new metric be ignored?

**Comment by gethinzhang** [comment]
> > But in argo, workflow is usually submitted by users, if they submit a identical metrics, which would cause whole metrics server panic.
> 
> What would be the behavior of this when `IgnoreError: true`? Would both identical metrics be shown? Would the new metric be ignored?

as shown in code, promhttp would print a error in comment but skip the follow duplications.
