### ISSUE TITLE
Trigger Argo workflows from different events

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo-workflows#304]
1. AWS SNS ->Publish against a test topic. Then AWS Lambda subscribing to the same SNS topic and triggering Argo workflow 

2. Google pubsub->Publish against a test topic. Then Google function subscribing to the same SNS topic and triggering Argo workflow 

3. Upload a file to S3 -> AWS Lambda listening to S3 event and triggering Argo workflow

What should we do when we get large volume of such event triggers?

**Comment by edlee2121** [comment]
Based on discussions with Jesse, the initial step may be to just configure a Lambda/Google function to invoke an argo workflow.
