### ISSUE TITLE
Store Workflow History with Parameters in DB

### ISSUE THREAD

**Issue by ericandrewmeadows** [argoproj/argo-workflows#3050]
# Summary

Storing the workflow history, with parameters used, will allow for CI/CD to build changes since the last successful build, potentially speeding up the build times.  We used to have this feature in Jenkins, saving us a lot!

# Motivation

By only building diffs, not the entire change history, you could then resubmit old Workflows, but also get changes since the last successful build with given parameters.

# Proposal

Postgres/MySQL DB backing, storing the Workflow-level parameters, along with the Workflow version.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sarabala1979** [comment]
Is it not supported currently? All workflow-level parameters will be applied in Workflow resource while creating. Workflow Controller will same the created resource. you can resubmit the workflow with the old parameters(which is saved in workflow resource) or you can pass new values.

I think this feature should be supported already.

**Comment by ericandrewmeadows** [comment]
From what I can tell, no.  On 2.8, I do not have a SQL instance.  I am not trying to resubmit a workflow for whom their TTL has not expired, I may or may not have the TTL expired, but I only want to get the Git differences between the commit.  I have the Workflows labeled with the Git commit short hash to be able to do this, but I do not know how to retrieve previous information automatically.  In Jenkins, I could see the entire history of success/failures for a given branch, and obtain the commit ids.  I added this to add in that functionality.  For context, I trigger Workflows using webhooks from GitHub to Argo Events.

**Comment by ericandrewmeadows** [comment]
@sarabala1979 - I will begin to look at this again shortly to see if we can close this one out.  My apologies - I have not had time to work on building out the shareable CI/CD interfaces that allow for building diffs between last and current builds - a pattern I was using in Jenkins.  Again, hopefully I can jump on this soon after the existing PR I was working on in the Workflows Catalog repo.

**Comment by alexec** [comment]
This is fixed by workflow archive.
