### ISSUE TITLE
Add command to run Workflow from CronWorkflow

### ISSUE THREAD

**Issue by jaygorrell** [argoproj/argo-workflows#3054]
# Summary

I'd like to have the ability to kick off a `Workflow` from a deployed `CronWorkflow`. This is similar to the `CronJob` counterpart: `kubectl create job --from=cronjob/cronjobname jobname`

# Motivation

Primarily for debugging, but in my case, we deploy `CronJob` (and soon `CronWorkflow`) resources through CI and give engineers the ability to run a `Job` from an existing `CronJob` without giving permissions to just run any arbitrary `Job`. It has been a good feature to have and I'd love to see it in Argo.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sarabala1979** [comment]
This feature is already implemented on v2.7.
```
argo submit --from cronworkflow/cronworkflowname
```

**Comment by jaygorrell** [comment]
Ah! I missed this, thank you!
