### ISSUE TITLE
Add -o short option for argocli get command

### ISSUE THREAD

**Issue by ljk662** [argoproj/argo-workflows#3090]
# Summary

What change you think needs making.

I want a status message that is small enough to pull out and send in a slack attachment. Some of the general info template/pod-name is not needed for a quick summary report. 

Please give examples of your use case, e.g. when would you use this.

When I want a short summary to glance at for recurring jobs. 

How do you think this should be implemented?

It's a pretty simple enhancement. A few additional if conditions to check for `short` where we check for `if getArgs.output == "wide"`.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by ljk662** [comment]
@alexec I've already implemented this on my fork (It was a good first issue :) ) . Since it seems this is something you are interested in I will make the PR now

**Comment by sanoojm** [comment]
@alexec  Since there is no update on this for a while, i will work on this as a part of hacktoberfest.

**Comment by sanoojm** [comment]
@alexec What would be an ideal output for -o short? Kubectl "get" option generally gives "Name, Status, Age". Will that suffice here?

**Comment by sanoojm** [comment]
Is this a desirable output?

> $ ./dist/argo get whalesay-dt5sj -o short
> STEP               TEMPLATE  PODNAME         DURATION  MESSAGE
>  ✔ whalesay-dt5sj  whalesay  whalesay-dt5sj  3m          
> $
