### ISSUE TITLE
Cron Workflow Run Now

### ISSUE THREAD

**Issue by felixgao** [argoproj/argo-workflows#3112]
# Summary

Allow Cron Workflow to run at any arbitrary time with a button trigger

# Motivation

Even though the Cron is suppose to run on a schedule. The Kubernete dashboard's cronjob supports a way to trigger the job as needed. 

# Proposal

Add a date picker and run button to the cron tab so a default `DS` value could be passed into the cron workflow to enable run on the given workflow at any arbitrary time.

**Comment by alexec** [comment]
@simster7

**Comment by simster7** [comment]
This is already supported with

```
$ argo submit --from cronwf/my-cron-wf-name
```

See:
```
$ argo submit --help
...
--from kind/name               Submit from an existing kind/name E.g., --from=cronwf/hello-world-cwf
```

**Comment by marov** [comment]
Would be nice to have an option in the UI

**Comment by simster7** [comment]
> Would be nice to have an option in the UI

Agreed
