### ISSUE TITLE
Be able to set result text when resuming a workflow

### ISSUE THREAD

**Issue by markterm** [argoproj/argo-workflows#3132]
# Summary

Ability to set result text against a node when doing a resume via API or CLI

# Motivation

If the result of a resume may affect execution of future nodes.

# Proposal

#3133 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by agilgur5** [comment]
Per https://github.com/argoproj/argo-workflows/pull/3133#issuecomment-651860118, this was implemented with #3277
