### ISSUE TITLE
Support Extension Fields

### ISSUE THREAD

**Issue by shadiramadan** [argoproj/argo-workflows#3150]
# Summary

docker-compose has the concept of extension fields: https://docs.docker.com/compose/compose-file/#extension-fields

These are YAML fields that start with `x-` and are ignored when validating if they should exist or not.  Argo should support a similar mechanism to be able to reduce duplicate configuration via YAML anchors.

# Motivation

I currently use YAML anchors in my argo workflows when I have duplicate configuration or inputs to many templates.  Right now I apply the anchor in the spot where I first use the duplicate configuration.

I would prefer to be able to pull this configuration out to a custom key.

# Proposal

Similar to the docker-compose solution- keys beginning with `x-` should simply be ignored by argo validations when submitting workflows.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Interesting request, I'll bring this up with the team

**Comment by alexec** [comment]
Closing issue. I don't support docker-compose (who does these days?).
