### ISSUE TITLE
[UI] Perform batch action on workflows

### ISSUE THREAD

**Issue by hadim** [argoproj/argo-workflows#3185]
In the same spirit as in https://github.com/kubernetes/dashboard/issues/5239, it would be nice to be able to select multiple workflows and perform batch action on it from the web UI.

**Comment by alexec** [comment]
Would you like to propose what use cases you need? Even submit a PR?

**Comment by hadim** [comment]
The use case is simply to be able to delete multiple workflows at the same time without deleting them one by one.

It's not really a blocking feature for me but more an enhancement. I'll have a look whenever I have some time.

**Comment by simster7** [comment]
@rbreeze Would you like to own?

**Comment by rbreeze** [comment]
Sure!

**Comment by rbreeze** [comment]
@hadim Is an interface like this, with checkboxes on the left, what you had in mind?
<img width="1052" alt="Screen Shot 2020-06-08 at 9 46 42 AM" src="https://user-images.githubusercontent.com/6250584/84057753-f9c1a100-a96c-11ea-82fb-26faeac2456b.png">

**Comment by hadim** [comment]
That's exactly the idea :-)
