### ISSUE TITLE
Simplify platform boot and refactor LB creation

### ISSUE THREAD

**Issue by abhinavdas** [argoproj/argo-workflows#319]
Currently, an ELB is created as part of argo platform install. For GKE, we would have to make this work with google load balancer and then we would have to do the same with Azure. Instead, we could remove the creation of ELB (or any other load balancer) from platform start to a workflow. The only connection it needs is the nodeport of the ingress controller deployment so that the load balancer points to the ingress controller and the ingress controller then forwards this to the deployment. To make this more general, I propose we do the following:

1. Do not create ingress controller as part of core argo install.
2. Do not create ELB as part of platform install
3. Argo platform should provide a way of allocating nodeports for internal routes for deployments. These nodeports should not change for the life of the deployment.
4. Use workflows for the following:
a. Creating an ingress controller. This will show up as a regular application
b. Creating an ELB/Google LB/Azure LB, etc (takes nodeports as input)

Then platform boot will be simpler and the job of creating LB etc will be simply a new workflow.

From a UI/axops standpoint, I think the following changes are required:
- Allocate and show nodeports for internal routes of deployments
- Show a menu with workflows for creating load balancers linking to the deployment's nodeport(s)

From a yaml perspective, we would need to define workflows that operate on an object. This object could be specified as an input but it would be nice if a subset of workflows appears on the menu for deployments that need an LB.

**Comment by abhinavdas** [comment]
For argo on user cluster, we have decided to remove platform post boot. All that is required is to create the templates which can be moved to axops-bootstrap pod.

**Comment by shrinandj** [comment]
Fixed in 54ecd71.
