### ISSUE TITLE
Allow cron schedules to be overridden in the CLI

### ISSUE THREAD

**Issue by samath117** [argoproj/argo-workflows#3194]
# Summary

The CLI for `argo cron create` should allow the option to override the default `schedule`.

# Motivation

If I want to change the schedule for a CronWorkflow, I currently have to edit the CronWorkflow file itself. This is annoying if I want to repeatedly change it when my needs change.

# Proposal

A new `-s, --schedule` option in `argo cron create` should allow for editing of the schedule, in much the same way that `argo submit -p` works to override/define workflow parameters. Additionally, if the schedule is left out of the file, `argo cron create` could still work properly if this option is invoked (again, the same as with workflow parameters).

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@simster7 do you want to own?

**Comment by simster7** [comment]
Sure
