### ISSUE TITLE
Strategy based Archive the workflows

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#3222]
# Summary
Current Workflow Archive feature is controller level enable and disable for all workflow executing on the controller.  Here a few proposals

1. Having label/annotation in the workflow which will indicate defer the Archive for this workflow
2. Having Archive Strategy in the controller configuration
```
     archiveStrategy: 
           policy: always, archiveIfLabelPresent, deferIfLabelPresent 
           label: workflows.argoproj.io/archive-strategy
```

**Comment by mac9416** [comment]
What does _defer_ mean in this context? Does it mean the workflow will be archived not-yet but eventually? If eventually, how is the exact archival time determined?

**Comment by sarabala1979** [comment]
The current Archive feature will archive the workflow once it completed. you can configure the retention duration in configuration how long you want to keep the archived workflow in DB. But It is a global flag to enable archive or disable for all workflows.  This enhancement gives flexibility to the user to chose which workflow needs to be archived based on policy and label.
