### ISSUE TITLE
[UI] Hide not authorized buttons in the menu

### ISSUE THREAD

**Issue by hadim** [argoproj/argo-workflows#3237]
According to the k8s role attached to a token, you might have access to a certain section in the UI menu. When clicking on it you get a HTTP 403 error:

```
HTTP 403
{
  "error": "clusterworkflowtemplates.argoproj.io is forbidden: User \"system:serviceaccount:argo:argo-server\" cannot list resource \"clusterworkflowtemplates\" in API group \"argoproj.io\" at the cluster scope",
  "code": 7,
  "message": "clusterworkflowtemplates.argoproj.io is forbidden: User \"system:serviceaccount:argo:argo-server\" cannot list resource \"clusterworkflowtemplates\" in API group \"argoproj.io\" at the cluster scope"
}
```

It would be nice to actually hide those buttons so users cannot click on it. 

That being said I am not sure how easy is to check for token associated permissions without making a call for each of the button in the menu. So maybe it will imply to add a new endpoint on the server-side.

**Comment by simster7** [comment]
Maybe this could be a job for the `/info` endpoint? @alexec

**Comment by alexec** [comment]
probably a new endpoint would be needed

**Comment by alexec** [comment]
Maybe a forbidden error should not stop the whole UI working.

**Comment by agilgur5** [comment]
Going to close this out as duplicate of #7088 (et al) as that one is more specific and has (much) more up votes (though this one did of course come first).
