### ISSUE TITLE
A more scalable way of getting pod status in K8sApiExecutor

### ISSUE THREAD

**Issue by sfc-gh-pkrishnamurthy** [argoproj/argo-workflows#3265]
# Summary

k8sApiExecutor uses getPods to get container status. https://github.com/argoproj/argo/blob/56694abe27267c1cb855064b44bc7c32d61ca66c/workflow/executor/k8sapi/client.go#L69 
This approach can have issues when the api-server is rate limited as in the case of EKS
This enhancement proposal is to seek advice/discuss a more scalable approach using a watch API

# Motivation

I run argo workflows v2.7.6  on EKS. Security constraints in my org forces me to use the K8sApi executor and not [docker, kubelet]
I am constantly  hitting issues like this

```
time="2020-06-20T01:55:40Z" level=warning msg="Failed to get pod 'repeat-kill-coordinator-ddgmt-504426767': Get https://172.20.0.1:443/api/v1/namespaces/test/pods/repeat-kill-coordinator-ddgmt-504426767: dial tcp 172.20.0.1:443: connect: connection refused"
time="2020-06-20T01:55:40Z" level=warning msg="Failed to get pod 'repeat-kill-coordinator-ddgmt-504426767': Get https://172.20.0.1:443/api/v1/namespaces/test/pods/repeat-kill-coordinator-ddgmt-504426767: dial tcp 172.20.0.1:443: connect: connection refused"
time="2020-06-20T01:55:40Z" level=error msg="Failed to kill sidecars: Get https://172.20.0.1:443/api/v1/namespaces/test/repeat-kill-coordinator-ddgmt-504426767: dial tcp 172.20.0.1:443: connect: connection refused"
```
in the wait container, causing the step to never complete and the workflow to never complete.
Another side-effect of this issue is ; Stop failing to stop the workflow.

argoexec wait --help
shows a request-timeout flag but the connection retries does not seem to be configurable

I fully acknowledge there are many factors in play here
* Rate limiting at the API-server 
* We run a service-mesh. with no container ordering wait usually comes up before istio-proxy and I use a podSpecPatch to have wait container curl istio endpoint and then sleep before starting 
  the wait

# Proposal

Is using a event based approach like using `NewSharedIndexInformer` a more scalable approach ?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sfc-gh-pkrishnamurthy** [comment]
I removed istio-proxy out of the picture by annotating all templates with
traffic.sidecar.istio.io/excludeOutboundIPRanges: "172.20.0.1/32"
Once I do that , all the connection refused errors cahanged into i/o time out
time="2020-06-23T16:14:22Z" level=warning msg="Failed to get pod 'for-loop-sd6zv-2540214372': Get https://172.20.0.1:443/api/v1/namespaces/serviceresilience/pods/for-loop-sd6zv-2540214372: dial tcp 172.20.0.1:443: i/o timeout"
time="2020-06-23T16:14:52Z" level=warning msg="Failed to get pod 'for-loop-sd6zv-2540214372': Get https://172.20.0.1:443/api/v1/namespaces/serviceresilience/pods/for-loop-sd6zv-2540214372: dial tcp 172.20.0.1:443: i/o timeout"
time="2020-06-23T16:15:22Z" level=warning msg="Failed to get pod 'for-loop-sd6zv-2540214372': Get https://172.20.0.1:443/api/v1/namespaces/serviceresilience/pods/for-loop-sd6zv-2540214372: dial tcp 172.20.0.1:443: i/o timeout"
time="2020-06-23T16:15:52Z" level=warning msg="Failed to get pod 'for-loop-sd6zv-2540214372': Get https://172.20.0.1:443/api/v1/namespaces/serviceresilience/pods/for-loop-sd6zv-2540214372: dial tcp 172.20.0.1:443: i/o timeout"
time="2020-06-23T16:16:22Z" level=warning msg="Failed to get pod 'for-loop-sd6zv-2540214372': Get https://172.20.0.1:443/api/v1/namespaces/serviceresilience/pods/for-loop-sd6zv-2540214372: dial tcp 172.20.0.1:443: i/o timeout"
And during that period of i/o timeout, I see huge latency spike in api-servers' response time and the verb is get pods.
Point being, by using the k8sApiExecutor, we can bombard the api-server if enough  concurrent steps are running across workflows and an event based implementation would be more scalable .

**Comment by alexec** [comment]
This should be greatly improved in v3.0. If not, v3.1 introduced the Emissary Executor and you should just use that.
