### ISSUE TITLE
Argo Workflow Status RUNNING but no pods running?

### ISSUE THREAD

**Issue by fabio-rigato** [argoproj/argo-workflows#3287]
Hey guys,

I am just upgraded Argo from **v2.2.1** to **v2.8.2** and I'm facing a really weird issue.

A lot of Argo Workflows have status=Running but there are not step/pod running.

The argo-server log has many of these:
`time="2020-06-22T05:00:26Z" level=error msg="finished streaming call with code Unknown" error="context canceled" grpc.code=Unknown grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-06-22T05:00:22Z" grpc.time_ms=4178.316 span.kind=server system=grpc`

Does anyone have the same issue?

Best Regards
Fabio

**Comment by simster7** [comment]
Can you post the full CRD of one of the workflows? You can get it by doing `kubectl get wf <WF_NAME> -o yaml`

**Comment by sarabala1979** [comment]
Can you check the controller log? is there any error or panic?

**Comment by fabio-rigato** [comment]
Hey @simster7 and @sarabala1979 thanks for asking. I had to roll back to 2.2.1 version because ~60 was stuck but I still have the logs in GCP Stackdriver. I checked the logs and there are not any panic but a lot of error like the following:

`The argo-server log has many of these:
time="2020-06-22T05:00:26Z" level=error msg="finished streaming call with code Unknown" error="context canceled" grpc.code=Unknown grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-06-22T05:00:22Z" grpc.time_ms=4178.316 span.kind=server system=grpc`

@simster7 I'll share with you the full CRD of one of them privately on slack.

let me know if you need any more information, we can schedule a call and i can share with you my screen and debug together if you will need.

All the best
Fabio

**Comment by sarabala1979** [comment]
I am triaging  an issue with @fabio-rigato

**Comment by alexec** [comment]
Discussed with user and fixed.
