### ISSUE TITLE
Expose internal queue metrics via Prometheus

### ISSUE THREAD

**Issue by dcherman** [argoproj/argo-workflows#3366]
# Summary

Right now, we have metrics around how long operations are taking, custom metrics, etc., however very little visibility into the internals of Argo to determine how long any given item is sitting in the workqueue, the depth of the workqueue, etc.

All of these metrics seem to be readily available since we're using the work queue from client-go, we just need to expose them.

https://godoc.org/k8s.io/client-go/util/workqueue#MetricsProvider

# Motivation

Additional visibility into the state of the queues in Argo for help debugging performance issues that might indicate the need to change resource requests/limits, parallelism, etc..

# Proposal

Expose the metrics already provided by https://godoc.org/k8s.io/client-go/util/workqueue#MetricsProvider for each of the internal work queues

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
I'll look into this one, good suggestion
