### ISSUE TITLE
Argo's pod drop older logs after completed

### ISSUE THREAD

**Issue by Techyuvi** [argoproj/argo-workflows#3413]
Hi team I have one pipeline which running on argo. it contains seven pods which handle different part of pipeline. one of among pod which take around 6 to 7 hours to complete if I see logs of this pod it truncate older logs and replace it with new logs. to verify this I look other pod's logs which take around 1 to 2 hours, and I am able to see all logs. 
So, how can I get all my logs for that longer running pod. is possible to tune size in argo pod so that I can get all logs or have to save logs in files?

**Comment by alexec** [comment]
I don't have much time to look into this today I'm afraid. There isn't anything special about how Argo runs pods. It maybe your underlying Kubernetes is dropping them. We have all our logs written to Splunk for posterity.

**Comment by sarabala1979** [comment]
Argo is using log API from k8s.  can you try `kubectl logs <podname>`? if both are same result then you need to check in your cluster config. Have you enabled logrotate on your cluster?
https://vividcode.io/enable-log-rotation-in-kubernetes-cluster/
https://kubernetes.io/docs/concepts/cluster-administration/logging/

**Comment by Techyuvi** [comment]
> Argo is using log API from k8s. can you try `kubectl logs <podname>`? if both are same result then you need to check in your cluster config. Have you enabled logrotate on your cluster?
> https://vividcode.io/enable-log-rotation-in-kubernetes-cluster/
> https://kubernetes.io/docs/concepts/cluster-administration/logging/

Thanks for replay I will check my configuration for this one and will let you know.
