### ISSUE TITLE
`onStart` handler

### ISSUE THREAD

**Issue by hadim** [argoproj/argo-workflows#3428]
Unless I am missing it I don't see any `onStart` handler similar to the `onExit` handler (https://github.com/argoproj/argo/tree/master/examples#exit-handlers).

**Comment by simster7** [comment]
Why not simply have a step run before the desired step? The utility of the `onExit` handler is that it runs regardless of whether a step fails or not, the utility of which is irrelevant on an `onStart` handler

**Comment by simster7** [comment]
Why not simply have a step run before the desired step? The utility of the `onExit` handler is that it runs regardless of whether a step fails or not, the utility of which is irrelevant on an `onStart` handler

**Comment by hadim** [comment]
Yes, we could do that but having an `onStart` handler would allow a better separation of concerns without requiring us to patch our workflows.

**Comment by hadim** [comment]
The use case is to trigger Slack notifications at the start and end of a workflow.

**Comment by hadim** [comment]
Another use case: we would like as a `workflowDefaults`. It's convenient with a handler since you can add a `onExit` template that is not related to your "business DAG". Without an `onStart` handler, you must add an extra node manually to your "business DAG".

**Comment by alexec** [comment]
Fixed by hooks in v3.3
