### ISSUE TITLE
Support Git single-branch mode for performance

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#3462]
# Summary

Update the code to allow `git clone -b my-branch --depth 1 my-repo` as this is the fastest way to check out a branch.

# Motivation

We want to checkout large Git repos faster.

# Proposal

See #373

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by TimothyGu** [comment]
This would indeed be very useful for us.

Also, I believe the proposal is #3373.

**Comment by alexec** [comment]
@TimothyGu would you like to submit a PR to fix?

**Comment by TimothyGu** [comment]
@alexec What's wrong with #3373? Or is it the case that the code is fine, but you'd rather get someone else to champion it?

For what it's worth, we eventually just used the Git CLI for this. Our workflow already had Git available in the container anyway, so it wasn't a huge hassle.

```sh
# To shallow clone a branch:
git clone -b my-branch --depth 1 $REPO_URL
```
```sh
# To shallow clone a commit:
git init $REPO_NAME
cd $REPO_NAME
git remote add origin $REPO_URL
git fetch --depth=1 origin $COMMIT_HASH
git checkout $COMMIT_HASH
```

**Comment by alexec** [comment]
> get someone else to champion it?

Essentially yes. I don't have the bandwidth to fix this, but if you do have time, you could rebase and test that PR and then submit it. That would be a great way to get it completed.

**Comment by prichrd** [comment]
@alexec, I have submitted an initial draft.
- I only validated it through unit tests for the moment.
- I still need to figure out some issues running argo-workflows locally (getting OOMs, secrets not mounted, etc.). Once this is done I will do one last end-to-end run of tests and will be highly confident of the solution.
