### ISSUE TITLE
Set workflow parameters in UI

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#3498]
# Summary

When creating a workflow from a template, I'd like to be able to set the parameters.

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

How do you think this should be implemented?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
This was already possible: https://github.com/argoproj/argo/pull/2030

What happened? Should I re-implement?

**Comment by alexec** [comment]
@simster7 I think I should probably fix this, as I broke it.

**Comment by alexec** [comment]
Available for testing in [v2.10.0-rc1](https://github.com/argoproj/argo/releases/tag/v2.11.0-rc1).
