### ISSUE TITLE
API Server: `archived-workflows` endpoint permission denied

### ISSUE THREAD

**Issue by hadim** [argoproj/argo-workflows#3502]
Using Argo 2.9.3.

I can access Archived Workflows from the UI at https://cluster-url.com/archived-workflows but I cannot from the API directly at https://cluster-url.com/api/v1/archived-workflows

In both cases, I am using the same token and same service account.

The error is:

```
{"error":"permission denied","code":7,"message":"permission denied"}
```

**Comment by alexec** [comment]
Could you please attach the curl request you're using? Please makes sure you have the `Authorization: Beaer TOKEN` header.

**Comment by hadim** [comment]
I'm doing it in Python but here is the equivalent request in curl:

```
curl -X GET -H "authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpXXXXXXXXXXXXXXXXXXXXXXZmJmMzUtMzIyOS00ODk3LWI2ODItYzA1ZDZlMTgzYWVmIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFyZ286YXJnby1yZW1vdGUifQ.Uc_WiMH2vh7C2lvyxtpbQli3SVNe-XU3QcsWfYzgP2LINo7DXXXXXXXXXXXXXXXXXXXXXXXXvMA2IU-WQL8VUckRgADhi8QJpMWVvVjwb3onlrCGAyyCRRKmwcdvaT9dcXYoBQ2WcWUaT3VtUxNtgR5TWIEM7aFHhKz6-hTnOYR2N3ql4SjpQsHEEYqgk4ccvPiFcNbF0vwhFKCmXagKp9knXpaImeja9CWmkL0OzvXk87W0j_b6A" http://cluster-url/api/v1/archived-workflows
```

Note that in this curl command replacing `http://cluster-url/api/v1/archived-workflows` by `http://cluster-url/api/v1/archivedworkflows/<NAMESPACE>` works well.

**Comment by alexec** [comment]
capitalise "Authorization"?

**Comment by hadim** [comment]
Nope, it does not work. As I said, other endpoints work. Only the `archived-workflows` does not work. So token, header and URLs are all fine. I tried to see if there was a role I was missing in the service account but I can't find any ArchivedWorkflow object.

**Comment by alexec** [comment]
You're getting a 403 rather than a 401, so I your token is fine. You can only read archived workflows if you would have permission to read the workflows themselves. If you are using namespace scope role and rolebinding, then try adding  namespace to the URL (you can find out the exact URL query parameter in the web console when using the UI).

**Comment by hadim** [comment]
Got it!

As specified in the API file namespace does not go to the URL in the params request:

```python
params = {}
params["listOptions.fieldSelector"] = "metadata.namespace=argo"
```

Using this field selector makes the request to work and returned the list of workflows.

Thank you @alexec
