### ISSUE TITLE
Retry logic fails for wf with Omitted nodes

### ISSUE THREAD

**Issue by kristofarkas** [argoproj/argo-workflows#3524]
**What happened**:

Tried to retry a failed workflow, but it failed with this log:

```
$ argo -n namespace retry my-wf
FATA[0000] Workflow cannot be retried with node my-wf.my-future-task in Omitted phase 
```

**What you expected to happen**:

The workflow to start again, with failed steps running.

**Anything else we need to know?**:

Looking at this switch statement https://github.com/argoproj/argo/blob/23760119d4664f0825536d368b65cdde356e0ff3/workflow/util/util.go#L625-L630 shouldn't it have a separate case for Omitted phase?

**Environment**:

- Argo version:
```
v2.9.3
```
- Kubernetes version :
```
1.15 EKS
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Thanks for this will work on a fix
