### ISSUE TITLE
scrollbars broken in new editor

### ISSUE THREAD

**Issue by foobarbecue** [argoproj/argo-workflows#3542]
Checklist:

 * [X] I've included the version.
 * [ N/A] I've included reproduction steps.
 * [ N/A ] I've included the workflow YAML.
 * [ N/A ] I've included the logs.

 Scrollbar behavior in the new editor is very weird. Testing on d07a0e7 .

![argo-scrollbar](https://user-images.githubusercontent.com/854789/88113131-10f7cf00-cb66-11ea-8a1b-724b90fac244.gif)

**Environment**:

Chrome 83.0.4103.116 64 bit

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
You appear to be able to scroll about, so I'll mark as "workaround".

**Comment by foobarbecue** [comment]
Yep, it's not a showstopper, just an annoyance.

**Comment by alexec** [comment]
@rbreeze did you fix this?

**Comment by rbreeze** [comment]
@alexec Tested on Firefox and Chrome/Brave, and cannot reproduce after #3560 - so I believe yes this is fixed. 

@foobarbecue Which browser / OS are you using?

**Comment by foobarbecue** [comment]
Chrome Version 84.0.4147.89 (Official Build) (64-bit) on Win 10. Looks good to me!
