### ISSUE TITLE
Watch does not have an event for terminated workloads

### ISSUE THREAD

**Issue by edw013** [argoproj/argo-workflows#3544]
# Summary

When creating a Watch using the argo go client, the event channel does not receive an event when a workload is terminated and will just hang open.

# Motivation

I would like to do some cleanup when a workload finishes and I have no idea when a terminated workload is terminated. That being said, it does seem like the channel does close by itself after a while, but is there any way to make this more prompt?

# Proposal

When a workload is terminated, an event should be generated which sets the workload status to terminated or something. I understand that there's a bit of an issue here because the workload status doesn't exist at all anymore, but something along these lines would be great.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by jessesuen** [comment]
The argo-go client is a wrapper around the kubernetes native watch API, and should get exactly the same events of that. Can you confirm that the native k8s watch is receiving the event, but the argo go client is not?

**Comment by alexec** [comment]
Can I request more information:

* What version of Argo CLI are you using?
* Are you using Argo Server?
*. What exact command do you execute to terminate your workflow?
* What happens when your run `kubectl get -w wf my-my`?
