### ISSUE TITLE
ttlStrategy not working with a specific configuration

### ISSUE THREAD

**Issue by aviklai** [argoproj/argo-workflows#3551]
Hi,

Is there any limit on each of the options in the ttl strategy?
https://github.com/argoproj/argo/blob/master/examples/gc-ttl.yaml

I am trying to configure the following ttl strategy:
ttlStrategy:
    secondsAfterCompletion: 86400
    secondsAfterSuccess: 86400   
    secondsAfterFailure: 604800

My goal is to save failed workflows for 7 days for investigation and delete the completed once.
When I set the above values, the completed workflows are not deleted after a day (86400 seconds).
However, if I set all the above values to 86400, the ttl strategy works - meaning, the workflows are deleted after 24 hours.

Is there any limit on the above values?
What may be the reason that the above configuration doesn't work?

I am using argo version 2.9.3

**Comment by simster7** [comment]
Completion means either Success or Failure. When you say

> When I set the above values, the completed workflows are not deleted after a day (86400 seconds)

Do you mean the failed workflows or the successful workflows?

From looking at the code, if a Workflow is Failed and `secondsAfterFailure: 604800` is set, it should respect that time only for failed Workflows.

**Comment by aviklai** [comment]
Hi,
I mean the successful workflows are not deleted when I set secondsAfterFailure to 604800 .

**Comment by simster7** [comment]
I'll take a look and try to reproduce

**Comment by aviklai** [comment]
@simster7 Thanks!

**Comment by simster7** [comment]
@aviklai 

I am so far unable to reproduce with this Workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gc-ttl-
spec:
  ttlStrategy:
    secondsAfterCompletion: 5 
    secondsAfterSuccess: 5
    secondsAfterFailure: 604800
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

See
```
$ argo submit examples/gc-ttl.yaml
Name:                ttl
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Wed Jul 22 09:58:32 -0700 (now)

$ date && kubectl get wf
Wed Jul 22 09:58:36 PDT 2020
NAME   STATUS    AGE
ttl    Running   4s

$ date && kubectl get wf
Wed Jul 22 09:58:38 PDT 2020
NAME   STATUS      AGE
ttl    Succeeded   6s

$ date && kubectl get wf
Wed Jul 22 09:58:42 PDT 2020
NAME   STATUS      AGE
ttl    Succeeded   10s

$ date && kubectl get wf
Wed Jul 22 09:58:44 PDT 2020
No resources found in argo namespace.
```

Do you see anything that I'm missing? Are you sure that the Workflows not getting deleted have `Succeeded` as their status?

**Comment by aviklai** [comment]
@simster7 Yes - I am sure they are succeeded.
Is there any log I should check that will tell me that there is a problem?
I can try setting this again and check.

Also - just to make sure - in your example, if the workflow fails, it still won't be deleted after 5 seconds but only after 604800 seconds, right?
https://github.com/argoproj/argo/blob/3d50f9852b481692235a3f075c4c0966e6404104/workflow/ttlcontroller/ttlcontroller.go#L218

**Comment by simster7** [comment]
You can check the logs of the `workflow-controller` deployment. That's where the logs of the file you linked are sent.

Something like `kubectl logs deploy/workflow-controller` should work.

> Also - just to make sure - in your example, if the workflow fails, it still won't be deleted after 5 seconds but only after 604800 seconds, right?

Yup, seems to be the case:

```
$ date && kubectl get wf
Wed Jul 22 11:33:06 PDT 2020
NAME   STATUS   AGE
ttl    Failed   22s
```

**Comment by aviklai** [comment]
@simster7 Great - thanks.
I will check again and update here.

**Comment by aviklai** [comment]
@simster7 I checked and the workflows are not deleted.
I set the ttl strategy as I posted in the question and I have many successful workflows that are 2 days old and not deleted yet.
I have checked the logs in the workflow controller and I don't see the following log for these workflows:

https://github.com/argoproj/argo/blob/3d50f9852b481692235a3f075c4c0966e6404104/workflow/ttlcontroller/ttlcontroller.go#L176

**Comment by simster7** [comment]
Thanks for getting back to me @aviklai. It's hard to diagnose the problem without more information, can I ask for

* The K8s object of one of the Successful workflows that has not been deleted? You can get it by running `kubectl get wf <NAME> -o yaml`. (If it contains private information and you'd rather share it privately, you can send it to me on the Argo slack `@simon`).

* Also helpful would be if you shared the `workflow-controller` logs around the time where you would expect the TTL deletion to take place.

* Can you check if the following lines are present on your `workflow-controller` logs? Should be close to the beginning

```
 controller | time="2020-07-27T08:24:15-07:00" level=info msg="Starting workflow TTL controller (resync 20m0s)"
...
 controller | time="2020-07-27T08:24:15-07:00" level=info msg="Started workflow TTL worker"
```

**Comment by aviklai** [comment]
@simster7 Hi,

I checked now and all the workflows were deleted. 
I do see in the logs that they were deleted very late.
For example, look at the following part of the log:

`set expire at 2020-07-24 22:49:45 +0000 UTC (-62h43m17.062470846s from now)`
Which means it was deleted with a delay of 62 hours, right?
I will send you the screenshots on slack. Thanks!

**Comment by simster7** [comment]
@aviklai and I chatted offline, we think the issue might be related to the environment. Will leave issue open for now in case other users experience the same issue

**Comment by mgoodness** [comment]
I'm also having issues with ttlStrategy in v2.9.4. It seems like workflow GC just stops until I delete the workflow-controller pod. Then it will work for a while before failing again.

**Comment by ediezh** [comment]
I'm facing the same issue after upgraded to v2.11.0. 

controller configmap sets the workflowDefaults as below.

```
workflowDefaults:
  metadata:
    annotations:
      argo: workflows
  spec:
    activeDeadlineSeconds: 86400
    ttlStrategy:
      secondsAfterCompletion: 7200
      secondsAfterSuccess: 7200
```

The workflows don't have ttl configured. But I still have workflows 15d old.
```
> argo list -n argo
...
brainscan-v3-dag-6q79l     Succeeded   15d   1h         0
brainscan-v3-dag-8zqzb     Failed      15d   4m         0
brainscan-v3-dag-j864w     Failed      15d   4m         0
brainscan-v3-dag-cvzkg     Failed      15d   4m         0
brainscan-v3-dag-q4jgg     Succeeded   15d   1h         0
brainscan-v3-dag-x4csx     Succeeded   15d   1h         0
```

**Comment by alexec** [comment]
@sarabala1979 is this related to any of your fixes?

workaround

```
argo delete --older ..
```

**Comment by ediezh** [comment]
I'm also getting in the controller logs sometimes(every hour or so)
```
W1007 23:28:30.418554       1 reflector.go:328] pkg/mod/k8s.io/client-go@v0.17.8/tools/cache/reflector.go:105: watch of *unstructured.Unstructured ended with: too old resource version: 84775754 (84838471)
```

**Comment by abirdZendesk** [comment]
We're seeing the same issue after upgrading from v2.8.1 to v2.11.3

**Comment by alexec** [comment]
We have had a problem with a bug in EKS. That produces this behaviour.

**Comment by alexec** [comment]
I've seen a few reports of this now. @sarabala1979 could you own please?

**Comment by sarabala1979** [comment]
I will take a look

**Comment by sarabala1979** [comment]
@abirdZendesk  I am not able to reproduce this issue but I would like to collect log to understand the problem . I have built eng build with extra loggings. Can you deploy it and collect the log?
```sarabala1979/workflow-controller:latest``

**Comment by sarabala1979** [comment]
@abirdZendesk are you still facing this issue? I didn't hear any update from your side.

**Comment by aviklai** [comment]
@sarabala1979 yes but I am still on version 2.9.3

**Comment by sarabala1979** [comment]
Can you try it on 2.11.8?

**Comment by alexec** [comment]
@sarabala1979 a little note here. Default workflow TTL do not apply to the ttl controller.

**Comment by alexec** [comment]
> @sarabala1979 a little note here. Default workflow TTL do not apply to the ttl controller.
Ignore me, I think I am wrong.

**Comment by aviklai** [comment]
@sarabala1979 I can't for now because our production works with 2.9.3.
I will try to upgrade and let you know.

**Comment by aviklai** [comment]
@sarabala1979 After upgrading to version 2.12.2, I am still seeing workflows deleted late (for example, a day after they were supposed to be deleted).

**Comment by alexec** [comment]
@aviklai this is a bug in v2.12, and is related to #4798.

**Comment by sarabala1979** [comment]
@aviklai Can you try on 2.12.3 which includes the above TTL changes?

**Comment by aviklai** [comment]
@sarabala1979 Sure - I updated to the new version.
I will update when I have the results.

**Comment by girishrao** [comment]
@aviklai Did upgrading to 2.12.3 resolve this issue for you? Thanks.

**Comment by aviklai** [comment]
@girishrao Hi, yes - I think so.
I am on 2.12.3 and so far I didn't encounter this issue again.
