### ISSUE TITLE
Migrate Argo CLI to homebrew-core

### ISSUE THREAD

**Issue by crunchtime-ali** [argoproj/argo-workflows#3567]
# Summary

Migrate the Argo CLI (and ArgoCD) Homebrew formulas from the custom Homebrew tap to `homebrew-core`

# Motivation

It makes Argo CLI even easier to install on macOS plus the big Homebrew community will co-author necessary changes (e.g. compile for Apple Silicon). Updates will be automated with a GitHub Action

# Proposal

It is already implemented and merged in homebrew-core: https://github.com/Homebrew/homebrew-core/pull/58259
Argo itself just needs a small documentation change which can be found here https://github.com/argoproj/argo/pull/3568
The `homebrew-tap` repo needs a `tap_migrations.json` so present users will be switched to the official repo. This change can be fouund here: https://github.com/argoproj/homebrew-tap/pull/15

# Other related PRs:
https://github.com/argoproj/argo-cd/pull/3979

---

**Message from the maintainers**:

**Comment by crunchtime-ali** [comment]
I can close this issue because https://github.com/argoproj/argo/pull/3568 has been merged.

**Comment by alexec** [comment]
Available for testing in [v2.10.0-rc1](https://github.com/argoproj/argo/releases/tag/v2.11.0-rc1).
