### ISSUE TITLE
If step is in pending state, step timeout(active deadline seconds) is not working

### ISSUE THREAD

**Issue by mehtadeepen** [argoproj/argo-workflows#3572]
**What happened**:

If step is in pending state, step timeout(active deadline seconds) is not working

**What you expected to happen**:

Step should timeout.

**Comment by sarabala1979** [comment]
#3571

**Comment by sarabala1979** [comment]
Currently, Argo support doesn't have a step level timeout. I think this is an enhancement

**Comment by alexec** [comment]
We might call this `pendingTimeout` because we want to wait for a node to move out of pending state.

`activeDeadlineSeconds` is simply carried forward to the pod spec, the meaning is not the same as the workflow level `activeDeadlineSeconds`.

**Comment by mehtadeepen** [comment]
Also, In my opinion this is a BUG not enhancement.

In argo examples --> https://github.com/argoproj/argo/blob/master/examples/timeouts-step.yaml …. It clearly states its a step timeout. Argo controller should honor it even if step is in pending state, Its controller’s internal implementation which should take care of it.

**Comment by alexec** [comment]
If `maxDuration` includes pending state, then this does not need to change. 

We will discus at stand-up about solution.

**Comment by hadim** [comment]
Indeed I myself got confused too. An option for maximum pending duration would be nice to have. See also https://github.com/argoproj/argo/issues/3445

**Comment by wenijinew** [comment]
> 

Do we have this parameter pendingTimeout? When pod is pending, I won't waste much time.

![image](https://user-images.githubusercontent.com/1829658/198221458-dba95b9e-7927-44e8-8615-43d301d9d124.png)

**Comment by hadim** [comment]
@wenijinew for the record I have opened https://github.com/argoproj/argo-workflows/issues/10341 that is similar to what you are asking.

**Comment by tooptoop4** [comment]
+1 @hadim that feature could help prevent https://github.com/argoproj/argo-workflows/issues/10441
