### ISSUE TITLE
Can we streamline of all different time units that we have as part of workflow spec ?

### ISSUE THREAD

**Issue by mehtadeepen** [argoproj/argo-workflows#3574]
# Summary

For Example: timeout is seconds while maxDuration is in minutes or hours or seconds. 

It would be nice if all different time units are seconds.

# Motivation

We parametrize timeout for workflows. We take seconds for timeout, if I want to set same time for maxDuration it requires conversion.

# Proposal

Change all timeunit to seconds or just make it consistent :D

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Max duration is default seconds.

```
maxDuration: 3
```

is equivalent to

```
maxDuration: 3s
```

**Comment by mehtadeepen** [comment]
@simster7 Thanks for that info. Can we parametrize activedeadlineSeconds, macDuration values ? Should i create new enhancement story for it?

I want to pass those values using input/workflow parameters.

**Comment by simster7** [comment]
You should certainly be able to parametrize

**Comment by mehtadeepen** [comment]
I definitely sure about `activedeadlineSeconds ` it is not. I will check for maxDuration.

**Comment by simster7** [comment]
> I definitely sure about activedeadlineSeconds it is not. 

I'll look into this. Is this at the Workflow-level or the template-level

**Comment by simster7** [comment]
Have confirmed that `activeDeadlineSeconds` is an `int` field and therefore cannot be parametrized. Will look into potentially allowing parametrization

**Comment by alexec** [comment]
I think we should have a new type `Duration` that can be int or string and converts into a duration. We might be able to re-purpose `TTL` for this.

**Comment by alexec** [comment]
Marking with "investigate" so that it gets pick up in next planning session.

**Comment by simster7** [comment]
Closed in favor of https://github.com/argoproj/argo/issues/3646
