### ISSUE TITLE
Step level (global timeout) which supersedes even max duration for retry

### ISSUE THREAD

**Issue by mehtadeepen** [argoproj/argo-workflows#3575]
Step level (global timeout) which supersedes even max duration for retry. 

I want to step to be killed irrespective retry, active deadline seconds or pending state - within a specific timeout.

Templates:

* DAG
* Steps
* Script
* Container
* Suspend

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Could you provide an example workflow that has this issue?

**Comment by mehtadeepen** [comment]
@simster7 Here is the scenario ... 

Step with retry count set to 5 and timeout set to 10 mins.

I have step timeout configured to 10 mins. 

For some reason, Step failed at 8th minute. As retry is configured it will rerun that step and it will again fail at 8th minutes. 

My expectation --> As step timeout is set to 10 minutes, irrespective of retries it should just kill itself at 10min. On above scenario during first retry after 2 mins have passed it should kill it self.  

It would be nice if we have something like Global step timeout which supersedes retry and retry's max Duration.

Does it make sense?

**Comment by alexec** [comment]
We hypothesis that `maxDuration` already does this, but we need to test this hypothesis.

**Comment by alexec** [comment]
@mehtadeepen will test to see if setting `activeDeadlineSeconds` and `maxDuration` to the same value works for him.

**Comment by jessesuen** [comment]
Duping this to https://github.com/argoproj/argo/issues/3572
