### ISSUE TITLE
Proposal: Support retention period for workflow memoization

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#3593]
# Summary

Support retention period for workflow memoization.

# Motivation

Currently the memorization cache uses configmap and it will be problematic when the number of workflows gets large. It's hard to maintain them manually (infra needs to add additional logic to support this and they are often lack of domain knowledge on specific applications). Another use case is that users might only want to utilize the cache when it's created recently, e.g. for time series modelling applications the data freshness needs to be considered.

# Proposal

The controller checks the creation time for the memoization cache and cleans/recreates them based on a specified time.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
We intentionally shipped the memoization without this feature in order to see how it is used and shaped by the community. We certainly expected this to be an enhancement request and it would be great if the community adds to the discussion here with their use cases and expectations.
