### ISSUE TITLE
UI: Hard to see child dependencies with complicated workflows

### ISSUE THREAD

**Issue by meurig** [argoproj/argo-workflows#3595]
# Summary

I understand that the graph has been rewritten to render an order of magnitude faster, and that's great! but is it possible to get the old graph back, either via a config flag or a ui toggle on the graph?

# Motivation

The current graph render doesn't line up parent and child nodes well. If I have 5 parents each with 20 children, it's very hard to trace a child back to it's parent. The old graph renderer did a much better job of this.

# Proposal

How do you think this should be implemented?

A config flag that says "use old graph renderer" would do the job. A better fix might be to spread the parent nodes out to be above the middle of their child nodes, instead of clumped them together in the middle.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Can you provide a screenshot to show what you mean?

We have also recently merged a feature to auto-collapse the children of nodes, which might make this simpler. Take a look:

https://github.com/argoproj/argo/pull/3526#issuecomment-662150920

**Comment by meurig** [comment]
I'm having some trouble posting screenshots this evening, but I'll try and get a before and after shot up tomorrow so you can see what I'm talking about.

Collapsing nodes might be a good alternative - is there an imagine up somewhere with this change in? I'm currently running 2.10.0-rc3.

**Comment by meurig** [comment]
Please find attached screenshots of the same workflow on v2.10.0-rc3 and v2.8.2.

![argo2](https://user-images.githubusercontent.com/507747/88683095-575fa780-d0eb-11ea-8b67-86e3aa082d44.png)
![argo3](https://user-images.githubusercontent.com/507747/88683098-59296b00-d0eb-11ea-9a3a-1ec3565a0df4.png)

Hopefully it's clear from these shots that the horizontal positioning of nodes in the fourth row (and other layout changes) make a big difference to the readability of the graph.

**Comment by simster7** [comment]
Hi @meurig. Yes, it's certainly very clear what you mean now, thank you for providing the screenshots.

I'll look into this and see if I can find a fix.

One thing that would help me immensely is if you could send me the Workflow object for the Workflow in that screenshot. You can get it by running `kubectl get wf <NAME> -o yaml`. If you'd rather send it to me privately, you can send it to me on our Argo slack (`@simon`)

**Comment by meurig** [comment]
Hi @simster7 ,

I can't share that exact workflow, but please find attached an example workflow that I've put together to produce a similarly complicated output

[argo_wacky_workflow.zip](https://github.com/argoproj/argo/files/4991153/argo_wacky_workflow.zip)

Please note it won't match those screenshots exactly!

I hope this helps,

Meurig

**Comment by simster7** [comment]
This will do perfectly fine! Thank you

**Comment by simster7** [comment]
#3884 has more examples of this issue

**Comment by simster7** [comment]
@meurig take a look 🙂 https://share.getcloudapp.com/d5uEj7bZ

**Comment by meurig** [comment]
Looks great! Thanks @simster7

**Comment by simster7** [comment]
This is out on 2.11, by the way

**Comment by meurig** [comment]
And it's working great, thanks again! @simster7  🥇
