### ISSUE TITLE
Proposal: Support CopyFile in k8sapi executor

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#3678]
# Summary

Implement `CopyFile` in k8sapi executor that's compliant with the `ContainerRuntimeExecutor` interface.

# Motivation

This is currently not implemented and artifacts passing does not work unless using `emptyDir` as a workaround. See https://github.com/argoproj/argo/issues/3252 for related discussions.

# Proposal

We can implement this using `k8s.io/client-go/rest` and `k8s.io/client-go/tools/remotecommand` to execute a command that copies file from k8s pod to local path (mounted to artifact storage).

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by merlintang** [comment]
+1

**Comment by jessesuen** [comment]
The challenge is that K8s copy (kubectl cp) API (which is a convenience around and exec cat | tar -gz to stdout) only works when a container is running. So I don't think that this is possible.

**Comment by terrytangyuan** [comment]
Note: This is blocked by https://github.com/kubernetes/kubectl/issues/454. Once `kubectl cp` works on completed pods we can revisit this issue and pick up https://github.com/argoproj/argo-workflows/pull/3687 again.

**Comment by alexec** [comment]
I think the solution to this today is to use the Emissary executor.
