### ISSUE TITLE
v2.9.4: `argo server` shows `Built without static files`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#3692]
## Summary 

Should be able to run `argo server` and see UI, but instead saw "Built without static files".

## Diagnostics

```
version="{v2.9.4+20d2ace.dirty 2020-07-25T08:30:49Z 20d2ace3d5344db68ce1bc2a250bbb1ba9862613 v2.9.4 dirty go1.14.5 gc darwin/amd64}"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tantonescu** [comment]
Looks like it was fixed in 2.9.5

**Comment by simster7** [comment]
<img width="950" alt="image" src="https://user-images.githubusercontent.com/614838/89659398-b4debb80-d884-11ea-881e-d1b00d2f5cd7.png">

**Comment by simster7** [comment]
This is from the Github release page?

**Comment by alexec** [comment]
Good news.

**Comment by dtaniwaki** [comment]
I installed v2.9.5 from homebrew, but it still has this error.

```
$ argo version
argo: v2.9.5+5759a0e.dirty
  BuildDate: 2020-08-07T20:49:00Z
  GitCommit: 5759a0e198d333fa8c3e0aeee433d93808c0dc72
  GitTreeState: dirty
  GitTag: v2.9.5
  GoVersion: go1.14.6
  Compiler: gc
  Platform: darwin/amd64
```

**Comment by alexec** [comment]
This is a duplicate of #3769
