### ISSUE TITLE
argo get returns steps in the wrong order for a workflow

### ISSUE THREAD

**Issue by aakarshgupta97** [argoproj/argo-workflows#3693]
## Summary 

What happened/what you expected to happen?
Step A in my workflow calls steps B, C, D & E in that order. Steps C & D will only run if a certain workflow parameter is set to `True`. When I set the parameter to `False` and call `argo get {workflow_name}` : 

**I SEE:**

├---✔ B (B)                                                                                
     |     |   ├-✔ B1 (B1)      some_container_name  10m       
     |     |   ├-✔ B2 (B2)     some_container_name  13m       
     |     |   └-✔ B3 (B3)     some_container_name   8m        
     |    ├---✔ E (E)            some_container_name  19s       
     |    ├---○ C                 when 'False == True' evaluated false
     |    └---○ D  		 when 'False == True' evaluated false

**I EXPECT TO SEE:**

├---✔ B (B)                                                                                
     |     |   ├-✔ B1 (B1)      some_container_name  10m       
     |     |   ├-✔ B2 (B2)     some_container_name  13m       
     |     |   └-✔ B3 (B3)     some_container_name   8m               
     |    ├---○ C                 when 'False == True' evaluated false
     |    ├---○ D  		 when 'False == True' evaluated false
     |    └---✔ E (E)            some_container_name  19s

## Diagnostics

What version of Argo Workflows are you running?
Using argo version v2.4.2
apiVersion: argoproj.io/v1alpha1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Can you attach a Workflow YAML to reproduce?
