### ISSUE TITLE
I want to refer "id", "startedAt", "finishedAt" in Step Template

### ISSUE THREAD

**Issue by sh-tatsuno** [argoproj/argo-workflows#3708]
# Summary

I would like to use like "steps.example.id", "steps.example.startedAt" and "steps.example.finishedAt"

# Use Cases

In our team, we try to send results from argo to slack channels for monitoring.

In this case, we want to include "what task(dag) is success, retry or failure" or the direct link to the result of the web UI in notifications.

e.g.

(color will be green if success)

```
Job: {workflow.name}
Task: [{task_id}](https://sample-argo.com/workflows/{namespace}/{workflow.name}?tab=workflow&nodeId={node.id})
Status: success
duration: XX sec
startedAt: 2020-08-10T12:00:00Z
finishedAt: 2020-08-10T12:30:00Z
```

So, I want to refer these valuables and pass to the slack callback task.

I have not created PR yet, but if I change, I assume to do below.
https://github.com/sh-tatsuno/argo/commit/a73041924d6d366de05af2b90d9aa2796ea1cdec

**Comment by simster7** [comment]
The enhancement and your proposed PR look good. Would you like to open a PR? Three things:

* Don't use `t0`, you can just inline `time.Time{}` directly.
* Add the new fields to our `docs/variables.md` doc
* Make sure this also works for tasks: add test cases for `tasks.<NAME>.startedAt`.

**Comment by sh-tatsuno** [comment]
I appreciate your check! I 'll prepare it!

**Comment by sh-tatsuno** [comment]
@simster7 
I have one elementary question.

How to create test yaml (with status item) from argo yaml file like below?
https://github.com/argoproj/argo/pull/3716/files#diff-e4eb711bf6f337f8e68f5f20ea0df29eR1879

I try to extract it from the completed pod or the web UI but cannot find the way.

**Comment by simster7** [comment]
Hmm this type of test is a bit more complicated and probably not necessary for a change like yours.

On further check, it seems like the test you've already included is sufficient because `tasks.` variables are generated using the same function as `steps.`

**Comment by sh-tatsuno** [comment]
OK! So, in this PR, I add the validation in an existed test substitute for additional tests.

(Not necessary but anyway, I would like to know how to create the test yaml for my future contribution. If I can try it, I am willing to create the procedure in docs)

**Comment by simster7** [comment]
Closed by #3724

**Comment by Bobgy** [comment]
I tried latest release of argo, I couldn't figure out how to get `id` there though.
Any thoughts? Should I open a new issue.

**Comment by Bobgy** [comment]
I found this can be worked around by exposing a parameter from the step I want to know pod name by `{{pod.name}}`, then referring to that parameter in the step that wants to consume the id.
