### ISSUE TITLE
Investigate writing back to the informer

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#3719]
# Summary

What change needs making?

# Use Cases

See https://github.com/argoproj/argo/pull/3684#issue-464115275

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
@alexec Should I unassign myself given #3852?

**Comment by alexec** [comment]
Sure. Low priority today mind you.

**Comment by gzb1128** [comment]
@alexec @simster7 Sir, please have a look at this issue #12352. Writing back to informer causes the `delta data` sync between `Update` and `write back to informer` to disappear. I'd like to get more suggestions from the community.
