### ISSUE TITLE
argo lint accept templates from stdin

### ISSUE THREAD

**Issue by brabster** [argoproj/argo-workflows#3728]
# Summary

argo lint accepts templates from stdin

# Use Cases

When I use helm to deploy a template, I would like to lint the template after it has been through Helm's value interpolation and any post-processors I've defined. Tested with 2.9.4

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Care to submit a PR for this?

**Comment by brabster** [comment]
I would love to @simster7 but I don't know Go and I don't have the time to learn it right now. If it's still here when I get round to it then...

**Comment by alexec** [comment]
Can you do this?

```bash
argo lint /dev/stdin < examples/hello-world.yaml
```

**Comment by alexec** [comment]
I've actually started on a PR for this: #3734

**Comment by arckey** [comment]
@alexec I'll be happy to submit a PR for this feature, and also for #4981  if you want.

**Comment by arckey** [comment]
@alexec we can close this I guess
