### ISSUE TITLE
argo lint to handle cron & templates automatically

### ISSUE THREAD

**Issue by brabster** [argoproj/argo-workflows#3730]
# Summary

argo lint detects the type of manifest and automatically applies correct linting

# Use Cases

When using Helm to deploy templates, it concatenates the templates together into one manifest including cron and workflow templates. I'd like to validate all types. Tested with 2.9.4

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by agilgur5** [comment]
This may have been fixed by #10059

**Comment by agilgur5** [comment]
Ah I misread the specificity of the issue, that `argo lint` handles all and doesn't need `argo cron lint` or `argo template lint`.

That was completed in #5224
