### ISSUE TITLE
UI: Add toggle button for CronWorkflow

### ISSUE THREAD

**Issue by xinbinhuang** [argoproj/argo-workflows#3774]
# Summary

Add a toggle button for CronWorkFlow in the UI

# Use Cases

When would you use this?

Suspend/Resume a cron workflow from the UI, and monitor what workflows are currently active

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
We think we might already have an issue for this.

@sarabala1979 to find the issue and mark this as duplicate.

This would be a great first issue / community contribution.

**Comment by sarabala1979** [comment]
This is a different issue. #1975. User is asking to see the workflows which are triggered by cron-workflow.

**Comment by yaman-694** [comment]
i want to solve this issue please assign

**Comment by terrytangyuan** [comment]
Feel free to submit a PR directly. I don’t think it’s necessary to be assigned.

**Comment by agilgur5** [comment]
> Suspend/Resume a cron workflow from the UI, and monitor what workflows are currently active

I think this ended up getting duplicated by #4264, which was completed in #4446

> User is asking to see the workflows which are triggered by cron-workflow.

I don't think the issue description was asking for this, but that was the topic of #11706, which was completed by #11811.

Closing this out as such
