### ISSUE TITLE
Argo Workflows Training 201: Automation - 10th Feb 2021

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#3790]
2 hours of advance hands-on training in integrating with and automating Argo Workflows.

You must be comfortable using bash and curl. We will not be covering basic terminal skills.

* The five different automation options
* Under the hood
* Kubernetes API automation
* Argo Server API automation
* Access tokens
* Hands-on exercises

To sign-up please complete this form: https://forms.gle/MoXgfjW6tiDSRc2z8

![image](https://user-images.githubusercontent.com/1142830/90284950-be899580-de27-11ea-8f9b-55aef840bbdf.png)
![image](https://user-images.githubusercontent.com/1142830/90284976-ccd7b180-de27-11ea-9f8e-ff7c04bea444.png)

**Comment by alexec** [comment]
Slides: https://docs.google.com/presentation/d/16XNk33fmMXvAZq7S5mCt0UrvFTtYcfBps-XUOAEv8MM/edit?usp=sharing

**Comment by nabilm** [comment]
Perfect , do we know what time will be the event ?

**Comment by alexec** [comment]
For 10am PST:

https://intuit.zoom.us/j/98908002342?pwd=VDhjdlN5VUZSTmxGOHRjNUZCaktEZz09&from=addon

**Comment by anggao** [comment]
I think you mean `10th Feb 2021` 😄

**Comment by alexec** [comment]
Video now available https://youtu.be/gqfDJi7m7ng
