### ISSUE TITLE
2.10.0 Release Marked Dirty

### ISSUE THREAD

**Issue by jamesgunnfiveai** [argoproj/argo-workflows#3815]
## Summary 

After following the release note instructions for downloading the 2.10.0 client and adding to /usr/local/bin, when running `argo version`, the tree state is marked as dirty.

## Diagnostics

```
argo version
argo: v2.10.0+195c6d8.dirty
  BuildDate: 2020-08-18T23:05:49Z
  GitCommit: 195c6d8310a70b07043b9df5c988d5a62dafe00d
  GitTreeState: dirty
  GitTag: v2.10.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Will be fixe in v2.10.1.
