### ISSUE TITLE
Issue in visualizing yaml in MD in metrics docs

### ISSUE THREAD

**Issue by pacospace** [argoproj/argo-workflows#3841]
## Summary 

Error in argo metrics docs to visualize correctly the yaml: https://argoproj.github.io/argo/metrics/

Missing  `...` after line 122 in https://github.com/argoproj/argo/blob/master/docs/metrics.md

**Comment by alexec** [comment]
Would you like to submit a PR?

**Comment by pacospace** [comment]
Yes sure, I can :)
