### ISSUE TITLE
Improve Links feature

### ISSUE THREAD

**Issue by posquit0** [argoproj/argo-workflows#3898]
# Summary

- #2443
- Support `${status.startedAt}` and `${status.finishedAt}` as substitutable variables in `links`.
  - Links just support `${metadata.name}`, `${metadata.namespace}` variables now.

# Use Cases

- For example, administrators can provide a link to Log Dashboard within the time window.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Sounds like a good idea. This feature is UI only. Would you be interested in submitting a PR?

**Comment by mruoss** [comment]
Has this been released yet? I still don't see these two variables being replaced in my links...
