### ISSUE TITLE
Pod did not output any logs

### ISSUE THREAD

**Issue by foobarbecue** [argoproj/argo-workflows#3916]
## Summary 

UI always flashes "Pod did not output any logs." before showing logs.

This should actually say something like "Attempting to load logs." unless there is a way to determine definitively that there are actually no logs.

## Diagnostics

2.10.0

**Comment by alexec** [comment]
Would you like to submit a PR to fix?

**Comment by foobarbecue** [comment]
Perhaps eventually, but I don't have time in the next couple of weeks. I also realize that there is actually a state where it shows "waiting for data" sometimes. So I'm guessing this might be somewhat subtle.
