### ISSUE TITLE
Tolerate deleted resources

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#3918]
# Summary

When a pod or node is deleted due to what ever reason, the workflow always error (see #3751). There is strong evidence that this is not what what users want by default.

Work-arounds:

- `rebumitPendingPods: true` a per-template setting (must therefore be set on all templates - no global default). This only works for deletion.
- `retry: {limit:1}` - again - per-template setting. 

Options

- Per-workflow (which can them be configured globally) versions of `resubmitPendingPods`.

# Use Cases

Argo Workflows has a challenge in that it tries to reliably execute workflows on fundamentally unreliably architecture.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I might be wrong about this.

**Comment by ebr** [comment]
I was just about to open an issue about this. We're running into this bug with a `pod deleted` failure mode. I'm also interested in finding out *why* the pod is being deleted (this is not an infrastructure issue, AND the workflow node does complete successfully!)

Some possibly relevant K8s events:
```
0s    Normal   WorkflowRunning   Workflow   Workflow Running
0s    Normal   NoPods   PodDisruptionBudget   No matching pods found
0s    Normal   ExternalProvisioning   PersistentVolumeClaim   waiting for a volume to be created, either by external provisioner "aws.io/aws-efs" or manually created by system administrator
0s    Normal   Provisioning   PersistentVolumeClaim   External provisioner is provisioning volume for claim "argo/test-pipeline-kggd7-shared-volume"
0s    Normal   ExternalProvisioning   PersistentVolumeClaim   waiting for a volume to be created, either by external provisioner "aws.io/aws-efs" or manually created by system administrator
0s    Normal   Scheduled   Pod   Successfully assigned argo/test-pipeline-kggd7-3136871819 to ip-192-168-55-123.us-east-1.compute.internal
0s    Normal   ProvisioningSucceeded   PersistentVolumeClaim   Successfully provisioned volume pvc-b3b16866-4eb9-47b9-bbb4-ccb8360f9836
0s    Warning   NoControllers   PodDisruptionBudget   found no controllers for pod "test-pipeline-kggd7-3136871819"
0s    Warning   CalculateExpectedPodCountFailed   PodDisruptionBudget   Failed to calculate the number of expected pods: found no controllers for pod "test-pipeline-kggd7-3136871819"
0s    Normal   Pulled   Pod   Container image "argoproj/argoexec:v2.9.3" already present on machine
0s    Normal   Created   Pod   Created container wait
0s    Normal   Started   Pod   Started container wait
0s    Normal   Pulled   Pod   Container image "<redacted>" already present on machine
0s    Normal   Created   Pod   Created container main
0s    Normal   Started   Pod   Started container main
0s    Warning   NoControllers   PodDisruptionBudget   found no controllers for pod "test-pipeline-kggd7-3136871819"
0s    Warning   CalculateExpectedPodCountFailed   PodDisruptionBudget   Failed to calculate the number of expected pods: found no controllers for pod "test-pipeline-kggd7-3136871819"
<..... warnings repeated 5 times .....>
0s    Normal   WorkflowNodeSucceeded   Workflow   Succeeded node test-pipeline-kggd7[0].generate-work-units
0s    Normal   WorkflowNodeSucceeded   Workflow   Succeeded node test-pipeline-kggd7[0]
0s    Warning   NoControllers   PodDisruptionBudget   found no controllers for pod "test-pipeline-kggd7-3889253965"
0s    Warning   CalculateExpectedPodCountFailed   PodDisruptionBudget   Failed to calculate the number of expected pods: found no controllers for pod "test-pipeline-kggd7-3889253965"
<..... warnings repeated 5 times .....> 
0s    Warning   WorkflowNodeFailed   Workflow   Failed node test-pipeline-kggd7[0]: child 'test-pipeline-kggd7-3136871819' failed
0s    Warning   WorkflowNodeFailed   Workflow   Failed node test-pipeline-kggd7: child 'test-pipeline-kggd7-3136871819' failed
0s    Warning   WorkflowFailed   Workflow   child 'test-pipeline-kggd7-3136871819' failed

```

The important events to highlight:
```
0s    Normal   Scheduled   Pod   Successfully assigned argo/test-pipeline-kggd7-3136871819
0s    Normal   WorkflowNodeSucceeded   Workflow   Succeeded node test-pipeline-kggd7[0].generate-work-units
0s    Normal   WorkflowNodeSucceeded   Workflow   Succeeded node test-pipeline-kggd7[0]
0s    Warning   WorkflowNodeFailed   Workflow   Failed node test-pipeline-kggd7[0]: child 'test-pipeline-kggd7-3136871819' failed
0s    Warning   WorkflowNodeFailed   Workflow   Failed node test-pipeline-kggd7: child 'test-pipeline-kggd7-3136871819' failed
0s    Warning   WorkflowFailed   Workflow   child 'test-pipeline-kggd7-3136871819' failed
```

The `test-pipeline-kggd7-3136871819` pod however does produce expected outputs, AND the subsequent steps get started before the workflow fails due to `pod deleted`, leaving the workflow in a `Failed` state, but with a bunch of active pods.

I'm not sure if the `PodDisruptionBudget` has to do anything with it, but we implemented it as a workaround for this issue in case of nodes being deleted by `cluster-autoscaler` when resource consumption was low.

(PS: This seems like the right issue to comment on, but I can open another issue for my specific problem).

**Comment by alexec** [comment]
@sarabala1979 @jessesuen note the `CalculateExpectedPodCountFailed` error, also https://github.com/elastic/cloud-on-k8s/issues/1703#issuecomment-531744403.

@ebr can you please change the PDB from a percentage to a fixed amount (e.g. 999)

**Comment by ebr** [comment]
I had:
```
podDisruptionBudget:
    maxUnavailable: 0
```

Changing it to
```
  podDisruptionBudget:
    minAvailable: 99999
```

fixed the `CalculateExpectedPodCountFailed` warnings - so thanks (not sure if this was affecting anything else).

The `pod deleted` issue still persists though
