### ISSUE TITLE
Add `--selector` and other useful flags to `argo {stop,terminate,resume,etc.}`

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#3931]
# Summary

Add `--selector` and other useful flags to `argo {stop,terminate,resume,etc.}`

# Use Cases

You can list certain workflows with `argo list --selector ...`, you should be able to stop the same list of workflows

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by neel229** [comment]
Can you elaborate it. I am new to golang, I have worked with the flag package and I am looking forward to contributing towards this issue.

**Comment by hanjunlee** [comment]
@simster7 If nobody takes this issue, can I try it as my first contribution?

**Comment by simster7** [comment]
Feel free to do so!

**Comment by neel229** [comment]
> @simster7 If nobody takes this issue, can I try it as my first contribution?

I would also like to do so. Is there any way we can collaborate on this as I am also new to Golang.

**Comment by rajneeshbajaj** [comment]
I can also assist, please let me know.

**Comment by hanjunlee** [comment]
@neel229 @rajneeshbajaj  I'll create a PR where we can work together first and let you know.

**Comment by hanjunlee** [comment]
I've created the draft to work (#3962). I'm planning to add options (`--selector`, `--field-selector`) to these commands: 

* stop 
* terminate 
* resume
* retry 

Please comment if you have any questions.

@simster7 One question, how could I add a unit test for codes of command?

**Comment by simster7** [comment]
We're refactoring our CLI testing code right now, but for now you can add them under `test/e2e/cli_test.go`

**Comment by dratler** [comment]
is it still open ?
