### ISSUE TITLE
Usability: fill the parameters with default value when "resubmit failed"

### ISSUE THREAD

**Issue by francis-ax** [argoproj/argo-workflows#396]
When user  resubmit failed workflow, the UI won't pre-fill the parameters with default value and data.  For better usability, I suggest that argo fill the parameters with default value when "resubmit failed"

![image](https://user-images.githubusercontent.com/29876185/31854326-bc2934f4-b6c9-11e7-92ee-5a02a98f4832.png)

**Comment by alexmt** [comment]
Resubmit Failed functionality has been temporary disabled. Looks like we forgot to hide Resubmit Failed from timeline page, this is fixed now.
