### ISSUE TITLE
workflows label field bricks argo using localstorage

### ISSUE THREAD

**Issue by foobarbecue** [argoproj/argo-workflows#3966]
## Summary 

I decided to try the "LABELS" field in the workflow list view of the web UI. I thought it might take a wildcard so I tried searching with an * . This bricked the argo workflow list page -- I would get Bad Request, and no amount of refreshing helped. I tried clearing the cache and everything before thinking of going into my localstorage in dev tools and deleting the offending info there.

![image](https://user-images.githubusercontent.com/854789/92517989-824e1880-f1cc-11ea-8d2d-5468dab57b3e.png)

![image](https://user-images.githubusercontent.com/854789/92518040-972aac00-f1cc-11ea-81a6-911d421055d4.png)

I suggest one a solution might be that the error page, instead of just having "refresh," has a button that clears local storage. Or maybe the refresh link just clears any dangerous localstorage.

## Diagnostics

2.10.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Related to #3322?

**Comment by simster7** [comment]
> Related to #3322?

Don't think so. I'll add this to the UI Epic.

**Comment by simster7** [comment]
I was able to reproduce. I think the solution here is just to remove labels from being saved in local storage. It doesn't make sense to me for this behavior to be saved, as it would pagination limit or even phase.
