### ISSUE TITLE
Update Published Go Packages

### ISSUE THREAD

**Issue by dtzar** [argoproj/argo-workflows#3991]
# Summary

Update published Golang packages on pkg.go.dev

# Use Cases

When would you use this?

`go get` naturally tries to pull from the published pkg.go.dev source and this source has not been [updated since February 2020](https://pkg.go.dev/mod/github.com/argoproj/argo@v0.0.0-20200909173032-f930c0296c41?tab=versions).  This makes pinning to a newer version more challenging.  Ideally there would be a corresponding published packaged at least for every release on the repo.

Minor nit: the website also believes 0.4.7 is the "latest" version.

**Comment by alexec** [comment]
The reason that this happens is that we migrated to Gomodules, and Gomodules broken this. 

See #3192

**Comment by alexec** [comment]
Work-around: https://github.com/argoproj/argo/issues/2602#issuecomment-636097428

**Comment by alexec** [comment]
@dtzar do you know how to fix this please?

**Comment by alexec** [comment]
Should be fixed now? https://pkg.go.dev/github.com/argoproj/argo-workflows/v3
