### ISSUE TITLE
Old version of kubectl 1.15, latest stable is 1.19.1

### ISSUE THREAD

**Issue by ricochet** [argoproj/argo-workflows#3996]
## Summary 

The Dockerfile for argo is pulling in [1.15 of kubectl](https://github.com/argoproj/argo/blob/a37d0a729c206040463d41e88e09814c1bf622dd/Dockerfile#L53). Given the comment in the Dockerfile, I expected this to be 1.19.1 or at least 1.18.8.

The Kubernetes project maintains release branches for the most recent three minor releases (1.19, 1.18, 1.17).
Kubernetes 1.19 and newer receive approximately 1 year of patch support.
Kubernetes 1.18 and older received approximately 9 months of patch support.
kubectl is supported within one minor version (older or newer) of kube-apiserver.

Example: kube-apiserver is at 1.18, then kubectl is supported at 1.19, 1.18, and 1.17

Given the above, argo should likely remain on one minor less (1.18) than the current stable (1.19). This allows support for all three active releases of k8s.

## Diagnostics

I reviewed the master branch and latest release branch of argo.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
It would be good to upgrade this dependency. Would you like to submit a PR with the fix?
