### ISSUE TITLE
UI: Cron workflows filter not working as expected

### ISSUE THREAD

**Issue by helmus** [argoproj/argo-workflows#4019]
## Summary 

when I click “Cron Workflows”, the app navigates  to
 https://argo.curation-ppd-usw2.iks.a.intuit.com/cron-workflows/undefined
The search field is empty and no cron workflows are listed.
When I click the X in the empty search field, the search fields remains empty but the url changes to: https://argo.curation-ppd-usw2.iks.a.intuit.com/cron-workflows/
And now all cron workflows are listed.
If you navigate to https://argo.curation-ppd-usw2.iks.a.intuit.com/cron-workflows/  directly, it will redirect to https://argo.curation-ppd-usw2.iks.a.intuit.com/cron-workflows/undefined

## Diagnostics

v2.10.0-rc1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Does this only happen for cron workflows?

**Comment by helmus** [comment]
Looks like it is actually happening for every view that has a filter

**Comment by alexec** [comment]
I feared as much
