### ISSUE TITLE
Allow configuring executor resources per pod

### ISSUE THREAD

**Issue by dseapy** [argoproj/argo-workflows#4029]
# Summary

Currently executor resources is configured in the workflow controller configmap globally.  Configuring it per pod would be nice.  Maybe this can already be done with podSpecPatch, not sure.

# Use Cases

Some steps have huge artifacts, while others not so much.  Currently tuning resources on the executor globally for the worst case, which wastes resources on the cluster.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
yes, You can set init/wait for container resource quota using `podSpecPatch`

**Comment by dseapy** [comment]
Will do, thanks!
