### ISSUE TITLE
Kafka artifact

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4052]
# Summary

In might be neat to have an artifact:

* Input artifact read from a Kafka topic.
* Output artifact written to Kafka topic.

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by ramanNarasimhan77** [comment]
I have a use case which requires batching `n` no of records from kafka. 
This is not supported currently with `Argo Events` and `Argo Workflow` integration ( `Argo Events` does not support batch consumption)

If the proposed `Kafka input artifact` can support batch consumption from and batch uploads to Kafka, then this feature would make my use case easy to implement.


## Use Case : ML Model Batch Inference from Kafka

I have to read data from a kafka topic in batches; say 1 batch reads `n` records.
The records are then sent to a ML model serving endpoint via REST/gRPC and the resulting prediction has to be saved into another topic

## Current Implementation Using Argo Workflows (Work in Progress)

I have containerised 
a) a kafka consumer that reads `n` records and then writes a file (if n records are not available, it would read whatever is available and timeout in say 1min)
b) a kafka producer that reads the file, invokes model with batch input and then writes back the data to topic

I am currently trying to implement this using a CronWorkflow that runs every 2min. 
So every 2min, a workflow would run that would have step1 that uses the kafka consumer and step2 that uses the kafka producer image

**Comment by book987** [comment]
Once supported, it might be used for archiving container logs  
Currently we save logs to artifact location after main container completed.  
But I think users want to use more Kafka ability like routing log to Kafka in realtime.  
Worth for consideration? 🤔

**Comment by signaleleven** [comment]
I'd love the ability of pushing artifacts to kafka.
Especially because I use argo events to react to messages on kafka topics, and this would allow us to shift all kafka related logic to Argo (events for reading, workflows for writing) and keep our jobs purely business, no infra.

**Comment by alexec** [comment]
This is now a use case supported by Argo Dataflow.
