### ISSUE TITLE
ImagePullSecrets is not dispatched from WorkflowTemplate object to Workflow object

### ISSUE THREAD

**Issue by mel1nn** [argoproj/argo-workflows#4057]
Hi,

I have a problem concerning the imagePullSecrets field defined in a WorkfowTemplate object.
I set it in the spec of the WorkflowTemplate but it is not dispatched to the generated Workflow. 
Is it a bug or not ?

Thanks

**Comment by simster7** [comment]
Can you provide a sample workflow to reproduce this?

**Comment by mel1nn** [comment]
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: notify-gerrit-workflow-template
  namespace: argo
spec:
  entrypoint: notify-gerrit-template
  imagePullSecrets:
  - name: "private-repo-secret"
  arguments:
    parameters:
    - name: revision
    - name: commit_id
    - name: status
    - name: vote
    - name: auth
  templates:
  - name: notify-gerrit-template
    container:
      image: <image_from_my_private_repo>
      env:
      - name: CHANGE_ID
        value: "{{ arguments.parameters.commit_id }}"
      - name: REVISION_ID
        value: "{{ arguments.parameters.revision }}"
      - name: MESSAGE
        value: "{{ arguments.parameters.status }}"
      - name: VERIFIED
        value: "{{ arguments.parameters.vote }}"
      - name: AUTH
        value: "{{ arguments.parameters.auth }}"
      command: [sh, -c]
      args: [
        "/bin/bash /notify.sh"
      ]

**Comment by alexec** [comment]
@sarabala1979 another example?

**Comment by sarabala1979** [comment]
What version of argo are you using?

**Comment by mel1nn** [comment]
The latest one. Installed with https://raw.githubusercontent.com/argoproj/argo/master/manifests/namespace-install.yaml.

**Comment by sarabala1979** [comment]
found bug in code. fixing it

**Comment by sarabala1979** [comment]
`imagePullSecrets:` is passed from workflowtemplate to the pod correctly.  can you check your create pod `kubectl get pods <> -o yaml`

```
  imagePullSecrets:
  - name: private-repo-secret

```

**Comment by mel1nn** [comment]
By restarting the workflow-controller pod, it works ! Thanks
