### ISSUE TITLE
`argo-server` default replicas should be 2 for high-availability

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4072]
# Summary

This is 1 by default, but this is never correct for any non-dev system.  Should be 2.

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by jessesuen** [comment]
Will do this in our own environments. Not necessary to distribute.
