### ISSUE TITLE
POD OOM but workflow succeeded

### ISSUE THREAD

**Issue by howshit** [argoproj/argo-workflows#4080]
Hi there,

I've define a argo workflow with several templates, and every template will run in a separate pod, where a npm script will be executed.

We are encountering OOM issue in one of the npm script, and the npm process exit with status 134(Aborted), but the container exit with status 0, and the pod is in Completed status, the workflow is in Succeeded status, which is kind of inconsistent(I think the pod and the workflow should be in Failed or Error status)

and If we set the memory limit smaller than the OOM threshold of the npm script, with pod will be in OOMKilled status, but the workflow is still in Succeeded status.

are there any possibilities to make the status consistent(the container exit with 134, the pod and the workflow are in error or failed status).

Best regards,
Felix

**Comment by sarabala1979** [comment]
Workflow is relay on pod status. If pod status is completed, workflow assumes containers are executed successfully and makes step success.
Can you provide your pod spec which failed on OOM ?

Can you provide sample workflow yaml?

**Comment by alexec** [comment]
This sounds correct behaviour to me. We only care about the containers exit code. Not any subprocess.

If you are running a script, try setting some shell options like this:

```yaml
command: [bash, -eux, -o, pipefail]
```

**Comment by howshit** [comment]
Hi alexec, thanks for the reply, I think there's something wrong with node alpine image, when I remove the alpine, the exit code is correct, and hence the argo workflow will fail as expected.
