### ISSUE TITLE
Some 2.11.0 URLs redirect unhelpfully

### ISSUE THREAD

**Issue by brabster** [argoproj/argo-workflows#4084]
## Summary 

I upgraded from 2.9/4 to 2.11.0. I selected an old URL from my browser autosuggest (localhost:2746/cron-workflows) and it was redirected to localhost:2746/cron-workflows/undefined, and showed no Cron Workflows.

Same issue affects localhost:2746/workflow-templates

## Diagnostics

Argo v 2.11.0

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Maybe fixed by Fixes #4019 (#4021)

**Comment by alexec** [comment]
@brabster to understand the cause of this issue, can you please tell me:

* Are you using a namespace of cluster scope install?
* What happens if you open the page in "private browsing" mode?
* What is in `localStorage.getItem("current_namespace")` return.
* What happens if you clear local storage?

You should be able to work around this by:

* Changing the URL.
* Entering and clearing the namespace control.

**Comment by brabster** [comment]
Hi Alex.

Yep, we can work around it easily thanks.

- Are you using a namespace of cluster scope install?
    - I install to the `argo` namespace - if that's what you mean?
- What happens if you open the page in "private browsing" mode?
    - Same thing happens
- What is in localStorage.getItem("current_namespace") return
    - `null`
- What happens if you clear local storage?
    - there's nothing in local storage to clear

**Comment by alexec** [comment]
> Are you using a namespace of cluster scope instal

Do you run the server using `--namespaced`?

**Comment by brabster** [comment]
I'm just using the install manifest as-is https://raw.githubusercontent.com/argoproj/argo/v2.11.0/manifests/install.yaml, so not using the `--namespaced` flag as far as I can tell

**Comment by alexec** [comment]
You can try `argoproj/argocli:latest` to see if the fix works for you.

**Comment by alexec** [comment]
Fixed AFAIK.

**Comment by posquit0** [comment]
Same issue for `workflow-template` page in v2.11.

**Comment by brabster** [comment]
Issue still present in v2.11.3
