### ISSUE TITLE
Deprecate and remove `--pod-workers`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4090]
# Summary

In #4064 when a pod is delete we skip the pod workflows and directly queue the workflow. The pod workflows don't do very much and create many additional Goroutines. Lets remove them completely. 

# Use Cases

Tech debt.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@JPZ13 I'm pretty sure this issue is needed to implement multi-cluster, so I labelled it as such.

This will simplify the code-base.

**Comment by JPZ13** [comment]
> @JPZ13 I'm pretty sure this issue is needed to implement multi-cluster, so I labelled it as such.
> 
> This will simplify the code-base.

Thanks for the heads up! @isubasinghe if you have a minute today, could you look into it?

**Comment by isubasinghe** [comment]
I am looking into this now
