### ISSUE TITLE
UI: Implement `strict` checks for TypeScript

### ISSUE THREAD

**Issue by dcherman** [argoproj/argo-workflows#4164]
# Summary

We should consider enabling the strict type checks in tsconfig to help with code quality / eliminate bugs.  This will also involve refactoring a non-trivial amount of code that's in violation of those rules already.

https://www.typescriptlang.org/tsconfig#strict

# Use Cases

This will help catch errors via stricter type checking at compile time.  For example, there are a lot of places where properties are accessed that are potentially null/undefined without first checking if they're actually defined.  Enabling these strict checks helps to eliminate that entire class of bugs.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
I'll add this to the UI Epic I'm working on!

**Comment by simster7** [comment]
Just turned it on and there are 323 errors that need to be fixed 🙂. This will probably be a lower priority for us, so we would welcome a community contribution for this if you're inclined to it

**Comment by dcherman** [comment]
@simster7 Sure, I'm game :). I'll likely do this over multiple pull requests, turning on the individual strict options to make them easier to review.  Final PR will hopefully just be turning on `strict` and removing the individual options with no code changes needed.

**Comment by simster7** [comment]
Woo, thanks! Many PRs are fine

**Comment by alexec** [comment]
I think this is done.
