### ISSUE TITLE
Helm Deployment Example

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo-workflows#418]
We need a Helm relicaset example for demos

1. You can try either persistent MongoDB cluster Helm chart https://github.com/kubernetes/charts/tree/master/stable/mongodb-replicaset
or
2. http://blog.kubernetes.io/2016/09/creating-postgresql-cluster-using-helm.html

**Comment by francis-ax** [comment]
we have another issue tracking this work

**Comment by ml10** [comment]
I did a quick search for replicaset in the issues, but I wasn't not able to find the other issue tracking this work. Would it be possible to link to it in a comment here?
