### ISSUE TITLE
I'm pretty sure the workflow queue is not being used correctly

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4250]
## Summary 

We have a `workqueue.RateLimiter` in the controller, but we invoke `AddAfter` on it, which I'm pretty sure bypasses the rate-limiting, making it an ordinary `DelayingQueue` with no. rate-limiting characteristics.

@jessesuen @alexmt 
 
I think we should fix this, remove the pod worker (to make it simpler) and then configure a rate limiter with what ever values we want.

**Comment by sarabala1979** [comment]
`workqueue.RateLimiter` queue is implemented on top of delayqueue.  I think ratelimit will apply for only active items.  
AddAfter will put into some timer functionality to add to the queue.

https://github.com/kubernetes/client-go/blob/master/util/workqueue/rate_limiting_queue.go

**Comment by alexec** [comment]
I played around with this, and I don’t think there is any benefit to using it, but no detriment either.
