### ISSUE TITLE
localhost:2746/cron-workflows redirects to localhost:2746/cron-workflows/undefined

### ISSUE THREAD

**Issue by brabster** [argoproj/argo-workflows#4265]
## Summary 

(effectively re-opening #4084, not fixed in 2.11.3)

I upgraded from 2.11.0 to 2.11.3. I selected an old URL from my browser autosuggest (localhost:2746/cron-workflows) and it was redirected to localhost:2746/cron-workflows/undefined, and showed no Cron Workflows.

Same issue affects localhost:2746/workflow-templates

## Diagnostics

Argo v 2.11.3

Are you using a namespace of cluster scope install?
- I install to the argo namespace - if that's what you mean?
What happens if you open the page in "private browsing" mode?
- Same thing happens
What is in localStorage.getItem("current_namespace") return
- null
What happens if you clear local storage?
- there's nothing in local storage to clear

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I've not observed this myself, but I will check again.

**Comment by brabster** [comment]
If I go to `localhost:2746/cron-workflows`, should I see all cron workflows regardless of namespace? Just tried it in a different browser that doesn't have any history, same result.

**Comment by GaruGaru** [comment]
I've performed a migration from argo wf 2.8 to 2.11.3 and I'm experiencing the same issue.
Both the workflow templates and cron workflows when visited redirect to `/workflow-templates/undefined` and `/cron-workflows/undefined`.

The issue is still present after browser storage cleanup / incognito mode.

```
localStorage.getItem("current_namespace")
"undefined"
```

**Comment by alexec** [comment]
ok, to repro you must not have trailing-slash, e.g. http://localhost:2746/cron-workflows

**Comment by alexec** [comment]
Ok. I've investigated, and the work-around is it change your URLs with a trailing slash. 

Would you be interested in investing a fix?
