### ISSUE TITLE
Old namespaces are not cleaned up in UI

### ISSUE THREAD

**Issue by brabster** [argoproj/argo-workflows#4266]
## Summary 

I see namespaces in the UI namespace dropdown that are no longer present on the cluster. I do not expect to see namespaces that no longer exist in the cluster.

![image](https://user-images.githubusercontent.com/38702/95846096-eec7b480-0d42-11eb-9209-0f107721e2d9.png)

```
$> kubectl get ns
NAME              STATUS   AGE
argo              Active   175d
default           Active   179d
kube-node-lease   Active   179d
kube-public       Active   179d
kube-system       Active   179d
release           Active   122d
```

## Diagnostics

What Kubernetes provider are you using? default (docker?)

What version of Argo Workflows are you running? 2.11.3, as installed from the release manifest

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Interesting. The UI has no way to determine if a namespace has been deleted. But we could expire unused namespaces. Would you like to investigate and see if you can come up with a solution?

**Comment by brabster** [comment]
If I get chance I would love to! Certainly not a big deal

**Comment by alexec** [comment]
This dropdown allows to enter garbage namespace names (e.g. "!"). We should fix that.
