### ISSUE TITLE
Document cron workflow behaviour on daylight saving time change

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4290]
# Summary

What happens?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
If you use timezone, we do take DST into account.

**Comment by alexec** [comment]
Would anyone like to update the docs?

**Comment by knabben** [comment]
@alexec can I get this one?

**Comment by alexec** [comment]
Please.
