### ISSUE TITLE
[Proposal] Implement CRI executor 

### ISSUE THREAD

**Issue by cy-zheng** [argoproj/argo-workflows#4312]
# Summary

As an argo workflow user, I hope argo could support CRI executor, which could control container lifecycle via [cri api](https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1alpha2/api.proto). 

There are some shortcomings in current 4 executors:

1. docker executor doesn't support other cri backend like containerd/crio/kata.
2. kubelet/k8sapi executor have some bugs to kill container, see #4289 .
3. pns executor retrieve the mapping between containerId and pid from /proc/{pid}/cgroup, but the record format varies between different cri backend. So there could be other compatibility issue when deploy argo workflow to different cri runtime. see #4302

CRI executor could also share pid namespace with main container, that could make it access main container's rootfs and collect artifacts more easier. 

CRI is a unified standard for k8s to standardize container runtime. Following this standard to design executor will reduce many compatibility issues.

# Use Cases

1. run argo workflow on different cri runtime.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I believe this is fixed using the Emissary Executor.
