### ISSUE TITLE
[UI] Error message does not get reset when valid argo workflow template is submitted after invalid template

### ISSUE THREAD

**Issue by nirav24** [argoproj/argo-workflows#4324]
## Summary 

I tried to edit workflow template with bad indented workflow and got error message. Then, I fix indentation and saved workflow successfully. The error message was still shown. I had to refresh the page to get rid of the error message.

### Screenshots

<img width="1010" alt="Screen Shot 2020-10-19 at 2 35 26 PM" src="https://user-images.githubusercontent.com/16739632/96497888-54231600-1219-11eb-9e23-983a9fef66e5.png">

<img width="1020" alt="Screen Shot 2020-10-19 at 2 35 34 PM" src="https://user-images.githubusercontent.com/16739632/96497903-5a18f700-1219-11eb-8504-565372883a09.png">

<img width="1015" alt="Screen Shot 2020-10-19 at 2 35 39 PM" src="https://user-images.githubusercontent.com/16739632/96497923-600ed800-1219-11eb-90eb-60fcf8ac9aac.png">

## Diagnostics

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 

v2.7.6

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I don't think you're running v2.7.6. This editor is newer than that. 
Can you try with `argocli:latest?`

**Comment by nirav24** [comment]
> I don't think you're running v2.7.6. This editor is newer than that.
> Can you try with `argocli:latest?`

`argocli:latest` doesn't have this bug. I double check my version. I was using v2.7.6.
