### ISSUE TITLE
Namespace filter not being cleared

### ISSUE THREAD

**Issue by andyleap** [argoproj/argo-workflows#4348]
## Summary 

What happened/what you expected to happen?

What happened:
1. Open argo ui
2. Enter namespace and hit enter
3. Clear namespace with x
4. Reload UI (or any other kind of navigation away from and back to argo root
5. Namespace from step 2 is back

Expected:
Step 5 would show workflows from all namespaces.

## Diagnostics

What Kubernetes provider are you using? GKE

What version of Argo Workflows are you running? 2.11.5

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Is this still a problem in v2.12 please?

**Comment by thundergolfer** [comment]
We're using `v2.12.3` and I still observe this issue, but with the URL being populated with a workflow ID. I took a video of the behaviour, but can't upload as it contains private info. Step-wise, the behaviour is: 

1. Go to Argo UI. Url is `<BASE_URL>/workflows/foo-bar-workflow-jlc54`
2. Navigate to "Archived Workflows" tab, and URL is populated as `<BASE_URL>/archived-workflows/foo-bar-workflow-jlc54?minStartedAt=...` so "no archived workflows" show up.
3. Remove everything from that URL after `archived-workflows/` and correctly see all the archived workflows.
4. Navigate back to main workflows tab, and URL is back to `<BASE_URL>/workflows/foo-bar-workflow-jlc54` so "No workflows" show up.

**Comment by alexec** [comment]
can you try with `:latest`?

**Comment by alexec** [comment]
Assumed fixed in v3
