### ISSUE TITLE
Automatically redirect to requested URL after successful SSO login

### ISSUE THREAD

**Issue by yonirab** [argoproj/argo-workflows#4370]
# Summary

Our users use SSO to authenticate and login to Argo UI (we are v2.9.3).
We provide users with a direct link to their workflow status in the UI (e.g. under `/workflows/default/some-workflow-id`).
If user is currently not logged in, he gets redirected to the `/login` route (which is OK).
However, after logging in, he is directed to the `/workflows` route, instead of the route he originally requested (e.g. `/workflows/default/some-workflow-id`).
We would like to see the user automatically redirected to the route he originally requested after successful SSO login.

# Use Cases

When would you use this?
Every time a user accesses the Argo UI with a direct link to his workflow's status 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
@yonirab I completed #4495 to implement this feature. Could I build a development image for you and ask you to test it to see if it works in your set up? We are also doing internal testing as well. The only catch is that the image would be off of latest `v2.12` and not `v2.9.3` which you said you are using.

Could you help us with this?

**Comment by yonirab** [comment]
Hi Simon,
I am all tied up at the moment so I can't promise I can find the time for this. But if you tell me how to install the dev image then if I find the time I'll try to give it a shot.
This is an important feature for us.
Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
