### ISSUE TITLE
semaphore limit leads to far lower number of conccurent workflows than expected

### ISSUE THREAD

**Issue by nmandery** [argoproj/argo-workflows#4377]
## Summary 

Using a semaphore to limit the concurrent workflow executions leads to a far lower number of concurrent executions. I started 100 instances of a workflow limited to 6 concurrent executions using a semaphore. This was more-or-less taken from the argo examples. Interestingly in the beginning argo executed 6 Worflows in parallel, but after that dropped the number of concurrent executions of the workflow.

I logged the executions using a script and gnuplot and got this graph of concurrent executions over time:

![output](https://user-images.githubusercontent.com/140716/97180967-0bc8a280-179b-11eb-9da8-31e608ac030f.png)

The repetition of this test resulted in similar chart.

## Diagnostics

What Kubernetes provider are you using? 

```
$ k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

What version of Argo Workflows are you running? 

argo 2.11.5

Configmap used for semaphore:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  workflow: "6"
```

Workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: synchronization-wf-level-
spec:
  entrypoint: whalesay
  synchronization:
    semaphore:
      configMapKeyRef:
        name: my-config
        key: workflow
  templates:
    - name: whalesay
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["hello world"]
        imagePullPolicy: "IfNotPresent"

```

Logs  - these are just the last few lines, as I got 1.2Mb of logs for this. In case you need more to investigate this, I can provide more

```
time="2020-10-26T13:42:31Z" level=info msg="Processing workflow" namespace=gzs-default workflow=synchronization-wf-level-hpg6g
time="2020-10-26T13:42:31Z" level=info msg="Updating node synchronization-wf-level-hpg6g message: ContainerCreating"
time="2020-10-26T13:42:31Z" level=info msg="Skipped pod synchronization-wf-level-hpg6g (synchronization-wf-level-hpg6g) creation: already exists" namespace=gzs-default podPhase=Pending workflow=synchronization-wf-level-hpg6g
time="2020-10-26T13:42:31Z" level=info msg="Workflow update successful" namespace=gzs-default phase=Running resourceVersion=52456084 workflow=synchronization-wf-level-hpg6g
time="2020-10-26T13:42:32Z" level=info msg="Processing workflow" namespace=gzs-default workflow=synchronization-wf-level-hpg6g
time="2020-10-26T13:42:32Z" level=info msg="Updating node synchronization-wf-level-hpg6g status Pending -> Running"
time="2020-10-26T13:42:32Z" level=info msg="Workflow update successful" namespace=gzs-default phase=Running resourceVersion=52456099 workflow=synchronization-wf-level-hpg6g
time="2020-10-26T13:42:33Z" level=info msg="Processing workflow" namespace=gzs-default workflow=synchronization-wf-level-hpg6g
time="2020-10-26T13:42:33Z" level=info msg="Setting node synchronization-wf-level-hpg6g outputs"
time="2020-10-26T13:42:33Z" level=info msg="Updating node synchronization-wf-level-hpg6g status Running -> Succeeded"
time="2020-10-26T13:42:33Z" level=info msg="Updated phase Running -> Succeeded" namespace=gzs-default workflow=synchronization-wf-level-hpg6g
time="2020-10-26T13:42:33Z" level=info msg="Marking workflow completed" namespace=gzs-default workflow=synchronization-wf-level-hpg6g
time="2020-10-26T13:42:33Z" level=info msg="Checking daemoned children of " namespace=gzs-default workflow=synchronization-wf-level-hpg6g
time="2020-10-26T13:42:33Z" level=info msg="Lock has been released by gzs-default/synchronization-wf-level-hpg6g. Available locks: 6" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-26T13:42:33Z" level=info msg="gzs-default/synchronization-wf-level-hpg6g released a lock from gzs-default/ConfigMap/my-config/workflow"
time="2020-10-26T13:42:33Z" level=info msg="Released all acquired locks" key=synchronization-wf-level-hpg6g
time="2020-10-26T13:42:33Z" level=info msg="Workflow update successful" namespace=gzs-default phase=Succeeded resourceVersion=52456104 workflow=synchronization-wf-level-hpg6g
time="2020-10-26T13:42:33Z" level=info msg="gzs-default/synchronization-wf-level-hpg6g released a lock from gzs-default/ConfigMap/my-config/workflow"
time="2020-10-26T13:42:33Z" level=info msg="Found Workflow gzs-default/synchronization-wf-level-hpg6g set expire at 2020-10-26 13:52:33 +0000 UTC (9m59.791764994s from now)"
time="2020-10-26T13:42:33Z" level=info msg="Queueing workflow gzs-default/synchronization-wf-level-hpg6g for delete in 9m59.791764994s"
time="2020-10-26T13:42:33Z" level=info msg="Found Workflow gzs-default/synchronization-wf-level-hpg6g set expire at 2020-10-26 13:52:33 +0000 UTC (9m59.791189794s from now)"
time="2020-10-26T13:42:33Z" level=info msg="Queueing workflow gzs-default/synchronization-wf-level-hpg6g for delete in 9m59.791189794s"
time="2020-10-26T13:42:34Z" level=info msg="gzs-default/ConfigMap/my-config/workflow acquired by gzs-default/synchronization-wf-level-rfv88 " semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-26T13:42:34Z" level=info msg="Processing workflow" namespace=gzs-default workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:34Z" level=info msg="Updated phase  -> Running" namespace=gzs-default workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:34Z" level=info msg="Pod node synchronization-wf-level-rfv88 initialized Pending" namespace=gzs-default workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:34Z" level=info msg="Created pod: synchronization-wf-level-rfv88 (synchronization-wf-level-rfv88)" namespace=gzs-default workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:34Z" level=info msg="Workflow update successful" namespace=gzs-default phase=Running resourceVersion=52456118 workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:34Z" level=info msg="Delete pod for gc successfully" namespace=gzs-default pod=synchronization-wf-level-hpg6g
time="2020-10-26T13:42:35Z" level=info msg="Processing workflow" namespace=gzs-default workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:35Z" level=info msg="Updating node synchronization-wf-level-rfv88 message: ContainerCreating"
time="2020-10-26T13:42:35Z" level=info msg="Skipped pod synchronization-wf-level-rfv88 (synchronization-wf-level-rfv88) creation: already exists" namespace=gzs-default podPhase=Pending workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:35Z" level=info msg="Workflow update successful" namespace=gzs-default phase=Running resourceVersion=52456128 workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:36Z" level=info msg="Processing workflow" namespace=gzs-default workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:36Z" level=info msg="Updating node synchronization-wf-level-rfv88 status Pending -> Running"
time="2020-10-26T13:42:36Z" level=info msg="Workflow update successful" namespace=gzs-default phase=Running resourceVersion=52456142 workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:37Z" level=info msg="Processing workflow" namespace=gzs-default workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:37Z" level=info msg="Setting node synchronization-wf-level-rfv88 outputs"
time="2020-10-26T13:42:37Z" level=info msg="Updating node synchronization-wf-level-rfv88 status Running -> Succeeded"
time="2020-10-26T13:42:37Z" level=info msg="Updated phase Running -> Succeeded" namespace=gzs-default workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:37Z" level=info msg="Marking workflow completed" namespace=gzs-default workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:37Z" level=info msg="Checking daemoned children of " namespace=gzs-default workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:37Z" level=info msg="Lock has been released by gzs-default/synchronization-wf-level-rfv88. Available locks: 6" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-26T13:42:37Z" level=info msg="gzs-default/synchronization-wf-level-rfv88 released a lock from gzs-default/ConfigMap/my-config/workflow"
time="2020-10-26T13:42:37Z" level=info msg="Released all acquired locks" key=synchronization-wf-level-rfv88
time="2020-10-26T13:42:37Z" level=info msg="Workflow update successful" namespace=gzs-default phase=Succeeded resourceVersion=52456147 workflow=synchronization-wf-level-rfv88
time="2020-10-26T13:42:37Z" level=info msg="Found Workflow gzs-default/synchronization-wf-level-rfv88 set expire at 2020-10-26 13:52:37 +0000 UTC (9m59.698888772s from now)"
time="2020-10-26T13:42:37Z" level=info msg="Queueing workflow gzs-default/synchronization-wf-level-rfv88 for delete in 9m59.698888772s"
time="2020-10-26T13:42:37Z" level=info msg="gzs-default/synchronization-wf-level-rfv88 released a lock from gzs-default/ConfigMap/my-config/workflow"
time="2020-10-26T13:42:37Z" level=info msg="Found Workflow gzs-default/synchronization-wf-level-rfv88 set expire at 2020-10-26 13:52:37 +0000 UTC (9m59.698308465s from now)"
time="2020-10-26T13:42:37Z" level=info msg="Queueing workflow gzs-default/synchronization-wf-level-rfv88 for delete in 9m59.698308465s"
time="2020-10-26T13:42:38Z" level=info msg="Delete pod for gc successfully" namespace=gzs-default pod=synchronization-wf-level-rfv88

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@nmandery can you provide last 5 minutes logs? I didn’t see any workflows are in pending state and waiting for semaphore in log. Are you seeing ‘Pending’ workflows on your namespace?

**Comment by nmandery** [comment]
@sarabala1979 All workflows are successfuly finished, so there is no issue with the lock not being released. It is just that I expected that argo continously handles 4-6 workflows at once, and not just one like in the second half of the graph I posted.

The complete log is available [here](https://gist.github.com/nmandery/9b691e131f0cd8198b1ee17d0ebe9d15)

**Comment by nmandery** [comment]
Here is another plot of the same data. The pending workflows get all handled as expected until all reach the "finished" status. But the whole batch only has concurrency in the beginning, after that it is just sequential processing of the workflows one by one. I hoped to achieve a higher throughput, but I currently do not understand the cause for this behavior.

![output](https://user-images.githubusercontent.com/140716/97188830-3c610a00-17a4-11eb-8771-5761129d977d.png)

I observed the load on k8s-master during this. The api-server was arround 25-30% CPU usage, etcd occasionally at 30%, otherwise the system was idling. So I assume high load on master is not the cause for this.

**Comment by sarabala1979** [comment]
Do you have  any `parallelism` set in `workflow-controller-configmap`?

**Comment by nmandery** [comment]
@sarabala1979 That was a good hint. `parellelism` was still set to 3 in `workflowDefaults` - my fault that I missed this. I did re-run my test after removing `parallelism` completely and this was the result:  

![output](https://user-images.githubusercontent.com/140716/97193949-dc6d6200-17a9-11eb-9332-0a3c5a07fae5.png)

While the number of concurrent workflows is far better, the throughput is still degrading over the batch of 100 workflows.

**Comment by sarabala1979** [comment]
Let me try to reproduce locally. How do you generate the above graph? is there any tool?

**Comment by fwfichtner** [comment]
[gnuplot](http://www.gnuplot.info/) I think

**Comment by nmandery** [comment]
@sarabala1979 It is less a tool, more a hack. I will provide it later today.

**Comment by nmandery** [comment]
Here is how to create the Chart:

Just run `record-argo-sync.py` to log the running and pending workflows, after that use gnuplot to render the chart:

```
python record-argo-sync.py
gnuplot plot.gnuplot
```

This will generate a PNG file in the working directory.

The sources for the two script:

**record-argo-sync.py**:

```python
import subprocess
import time

out="wf.dat"
try:
    print("logging to %s. press Ctrl-C to exit" % (out,))
    with open(out, "w") as fh:
        while True:
            wf_lines = [l for l in subprocess.check_output(["argo", "list"]).splitlines() if "synchronization-wf-level-" in l ]
            pending = len([l for l in wf_lines if "Pending" in l])
            running = len([l for l in wf_lines if "Running" in l])
            msg = "%d;%d;%d" % (int(time.time()), running, pending)

            fh.write(msg + "\n")
            fh.flush()
            print(msg)
            time.sleep(1)

except:
    print("exiting")
    pass
```

**plot.gnuplot**:

```
set terminal pngcairo enhanced font 'Verdana,10'
set size ratio 0.5
set title "n concurrent running workflows"
set output "output.png"
set xdata time
set datafile separator ";"
set timefmt "%s"
set format x "%H:%M"
set grid
plot "wf.dat" using 1:2 title "Running" with lines, "wf.dat" using 1:3 title "Pending" with lines;
```

**Comment by sarabala1979** [comment]
I am able to reproduce kind this issue and found some edge case for acquiring released locks. Is it possible to try my dev build on your environment and provide the details `sarabala1979/workflow-controller:latest`?

**Comment by nmandery** [comment]
Thank you for the quick implementation. I just tested the `sarabala1979/workflow-controller:latest` image and these where the observations:

Running the 100 instances of the same workflow as before:

![output short-wf](https://user-images.githubusercontent.com/140716/97254798-74516700-180f-11eb-99db-d8b777befb61.png)

While the concurrency ist still not optimal, the peaks are gone and the curve seems to be more homogenous. Thinking about that my example workflow is propably bad as the container is very short lived and most time is spend in creating and destroying the instance, I created a new workflow with a longer run-time, which is a bit closer to the workflow where we originally observed the phenomenon:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: synchronization-wf-level-
spec:
  entrypoint: sleep
  synchronization:
    semaphore:
      configMapKeyRef:
        name: my-config
        key: workflow
  templates:
    - name: sleep
      container:
        image: alpine:latest
        command: [sleep, 10]
        imagePullPolicy: "IfNotPresent"
```

While there is still some slight degradation, the level of concurrency is now much better:

![output](https://user-images.githubusercontent.com/140716/97255155-4587c080-1810-11eb-8e7b-08d8cc50d967.png)

To cross-check I went back to the former `argoproj/workflow-controller:v2.11.5` workflow controller and re-ran the last test:

![output](https://user-images.githubusercontent.com/140716/97256570-a795f500-1813-11eb-8e32-6bb8efbe05bd.png)

So your fix greatly improved argo for us - Thank you!

Is there any schedule when this fix will be included in an argo release?

**Comment by sarabala1979** [comment]
Thanks for, detailed response.  This fix will get released soon on v2.11.7 (mostly tomorrow)

**Comment by nmandery** [comment]
After some more testing I am afraid the issue still persists. Just the severity of the effects are changing from batch to batch. This also can be seen in the good, although with degrading concurrency, run in my last comment. In other repeated runs I sometimes got only 1-2 concurrent workflows again while still using the same dev-build of the workflow-controller

Looking at an extract (see the grep) of the debug-level logs, I wondered about the released locks and the newly enqueued workflows:

```
$ egrep -i "(Available Locks|Enqueue)" log
```
```
time="2020-10-27T10:04:01Z" level=info msg="Lock has been released by gzs-default/synchronization-wf-level-rl4p2. Available locks: 1" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:01Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-sczrh" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:02Z" level=info msg="Lock has been released by gzs-default/synchronization-wf-level-h5vqg. Available locks: 1" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:02Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-v4b4z" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:02Z" level=info msg="Lock has been released by gzs-default/synchronization-wf-level-tg95j. Available locks: 2" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:02Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-v4b4z" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:02Z" level=info msg="Lock has been released by gzs-default/synchronization-wf-level-dxzxc. Available locks: 3" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:02Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-v4b4z" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:02Z" level=info msg="Lock has been released by gzs-default/synchronization-wf-level-jxwlp. Available locks: 4" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:02Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-v4b4z" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:02Z" level=info msg="Lock has been released by gzs-default/synchronization-wf-level-sv774. Available locks: 5" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:02Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-v4b4z" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:03Z" level=info msg="Lock has been released by gzs-default/synchronization-wf-level-v4b4z. Available locks: 5" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:03Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-4qjvz" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:34Z" level=info msg="Lock has been released by gzs-default/synchronization-wf-level-sczrh. Available locks: 5" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:34Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-gwl7w" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:38Z" level=info msg="Lock has been released by gzs-default/synchronization-wf-level-4qjvz. Available locks: 5" semaphore=gzs-default/ConfigMap/my-config/workflow
time="2020-10-27T10:04:38Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-8xdmg" semaphore=gzs-default/ConfigMap/my-config/workflow
```

My limited understanding of this: 

* In the first two log lines a lock becomes available and immediately "gzs-default/synchronization-wf-level-sczrh" aquires it again. Everything as expected - great 
* In line 3 and 4 the same happens again and "gzs-default/synchronization-wf-level-v4b4z" gets enqueued
* In 5 and 6 "gzs-default/synchronization-wf-level-v4b4z" gets enqueued **again**

Now one key in [lockHolder](https://github.com/argoproj/argo/blob/0416aba50d13baabfa0f677b744a9c47ff8d8426/workflow/sync/semaphore.go#L18) gets set twice with the first overwritting the second. In the result there [is only one semaphore being released here](https://github.com/argoproj/argo/blob/0416aba50d13baabfa0f677b744a9c47ff8d8426/workflow/sync/semaphore.go#L88).

The code scheduling the next workflow after a lock has been released expects a [1:1 relation of released locks to new workflows](https://github.com/argoproj/argo/blob/0416aba50d13baabfa0f677b744a9c47ff8d8426/workflow/sync/semaphore.go#L91), and that seems to be the leak where the usable semaphores are lost.

The same happens a few times in the log extract above.

I hope I am not completely wrong with this assumption

**Comment by sarabala1979** [comment]
@nmandery Thanks for the detailed analysis. I am refactoring the enqueue workflow logic to avoid losing locks.  I am building dev image to try it out.  I will let you know once I am done. Thanks for helping us to verify  the fix.

**Comment by sarabala1979** [comment]
@nmandery Did you get a chance to try the latest build?

**Comment by nmandery** [comment]
@sarabala1979 I must have missed that you did a new release. I just did a few test runs with roughly similar results, this was one of them:

![output](https://user-images.githubusercontent.com/140716/97667910-33608900-1a81-11eb-95f0-93abff202342.png)

So your fix did indeed help, argo seems not to be able to re-use all locks over the complete batch of the 100 workflows. But the graph shows that there are still periods where the number of concurrently running workflows is lower than it could be. Looking at the graph above, there are degradations at 6:16, looking at the collected workflow-controlllers debug logs reveals this:

```
$ grep "Enqueue the workflow" log_2 | sort | uniq -c --repeated | grep "6:16"
      2 time="2020-10-30T06:16:29Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-wwq4t" semaphore=gzs-default/ConfigMap/my-config/workflow
      2 time="2020-10-30T06:16:29Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-zhbld" semaphore=gzs-default/ConfigMap/my-config/workflow
      2 time="2020-10-30T06:16:31Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-h48mb" semaphore=gzs-default/ConfigMap/my-config/workflow
      2 time="2020-10-30T06:16:31Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-m8gms" semaphore=gzs-default/ConfigMap/my-config/workflow
      2 time="2020-10-30T06:16:31Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-mjtn7" semaphore=gzs-default/ConfigMap/my-config/workflow
      2 time="2020-10-30T06:16:31Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-wwq4t" semaphore=gzs-default/ConfigMap/my-config/workflow
      3 time="2020-10-30T06:16:39Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-6wwxw" semaphore=gzs-default/ConfigMap/my-config/workflow
      2 time="2020-10-30T06:16:39Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-jqbmt" semaphore=gzs-default/ConfigMap/my-config/workflow
      3 time="2020-10-30T06:16:39Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-ljhnf" semaphore=gzs-default/ConfigMap/my-config/workflow
      3 time="2020-10-30T06:16:39Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-m8gms" semaphore=gzs-default/ConfigMap/my-config/workflow
      2 time="2020-10-30T06:16:53Z" level=debug msg="Enqueue the workflow gzs-default/synchronization-wf-level-8cngn" semaphore=gzs-default/ConfigMap/my-config/workflow

```

The first number is how often the line appeared in the logfile. So the same workflow occasionally gets enqueued more than once in the same second.  I am just showing an extract from the "06:16" timestamp here, it actually happens more often. 

Looking at the first half of the chart in "Minute:Second" - resolution, the degradations can be clearly correlated to the occurances of the multi-enqueueings:

![output](https://user-images.githubusercontent.com/140716/97670044-b4218400-1a85-11eb-8767-f202cc921a75.png)

Is there any possibility to directly `pop()` from `pending`-Queue in the `PriorityQueue.release` method? Multiple workflows finishing at the same time all seem to iterate `pending` from the beginning, as the `pop()` happens sometime later.

But anyways, the last PR is definately an improvement. Thank you for the work.

**Comment by sarabala1979** [comment]
Thanks for your response which helps us to make sure the fix is working. A semaphore has the functionality to hold the workflow priority place for acquiring locks that's why we can't pop before acquiring locks.  WorkerQueue has de-dup functionality even the same workflow queued multiple times, it will take replace the object in the first position. 
you can see a small duration of degradation because workflow round trip to acquire the locks but it will use all available locks.

**Comment by nmandery** [comment]
Thanks for the explanation @sarabala1979 . I guess we will switch out production workflows to this new implementation once it gets released. I will then try to keep an eye on its how it behaves with longer running workflows.
