### ISSUE TITLE
workflow-controller pod doesn't expose any ports but replies to /metrics on 8080

### ISSUE THREAD

**Issue by agniveshadhikari** [argoproj/argo-workflows#4390]
## Summary 

1. `workflow-controller` pod doesn't expose any ports but replies to `/metrics` on `8080`
2. `workflow-controller-metrics` service doesn't respond to `/metrics`

As a result, this is breaking prometheus' service discovery based scraping.

## Diagnostics

What Kubernetes provider are you using? 
Azure Kubernetes Service

What version of Argo Workflows are you running? 
2.11.0

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Not sure what the issue is here. Can you clarify what your ideal fix would be and why?

**Comment by agniveshadhikari** [comment]
I'd expect `svc/workflow-controller-metrics` to serve the metrics on `/metrics` endpoint. Right now, the metrics are not served from either a discoverable port, or a discoverable service.

**Comment by alexec** [comment]
@agniveshadhikari do you have an idea of the correct YAML for the service? Can you share anything about the Prometheus auto-discovery?
