### ISSUE TITLE
Forgot/reset/confirm reset pages design is broken

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-workflows#44]
After login page redesign forgot/reset and confirm reset pages look strange:

<img width="407" alt="screen shot 2017-08-25 at 9 37 13 pm" src="https://user-images.githubusercontent.com/426437/29738659-cd8ddc90-89dd-11e7-8bb0-eaeb112f0e9e.png">

We need to prepare new design and update pages accordingly.

**Comment by alexmt** [comment]
@rahuldhide can you please take a look?

**Comment by rahuldhide** [comment]
I have updated the screen designs based on the Argo design guidelines. 
![forgot2](https://user-images.githubusercontent.com/30275450/29806168-a555f444-8c42-11e7-9c94-4b43adce9c2f.png)
![createaccount](https://user-images.githubusercontent.com/30275450/29806170-a557c6ac-8c42-11e7-9428-c085a4392c69.png)
![forgot3](https://user-images.githubusercontent.com/30275450/29806171-a558a89c-8c42-11e7-94c1-812b4e84bae9.png)
![forgot4](https://user-images.githubusercontent.com/30275450/29806172-a559cd26-8c42-11e7-97aa-acd664d97b94.png)
![forgot1](https://user-images.githubusercontent.com/30275450/29806169-a5564e58-8c42-11e7-9c85-f17300b0b43d.png)

**Comment by wokeGit** [comment]
There is one more screen: https://dev.applatix.net/setup/signup/faketoken
Do we still need it? I created new account and this screen is not used during process of creation. I'm not sure but it looks like death code.

**Comment by alexmt** [comment]
@wokeGit  It is not dead code. This screen is required for group invitation: go to invite new user screen and check 'Mailing group' checkbox. Please apply new design to this screen as well

**Comment by rahuldhide** [comment]
@wokeGit From the design perspective, we can reuse the 'Welcome- Create Account Password' screen for this requirement. We just need to update the panel title to- Create your Argo account.
![createaccount](https://user-images.githubusercontent.com/30275450/29835481-ff5efc92-8ca6-11e7-84d5-cc6e7713b499.png)

**Comment by wokeGit** [comment]
There is one more screen not available on the mocukps. I updated styles for that as well.
![screen shot 2017-08-30 at 10 27 49](https://user-images.githubusercontent.com/13086525/29862846-03182120-8d6e-11e7-9715-22f72bfb2629.png)
@rahuldhide Do we need any update for messages for that screen?

All the screens are updated and ready to merge:
https://github.com/argoproj/argo/pull/83
