### ISSUE TITLE
Accept `rest.Config` to argo's API client instead of `clientcmd.ClientConfig`

### ISSUE THREAD

**Issue by mweibel** [argoproj/argo-workflows#4422]
# Summary

See [diff](https://github.com/argoproj/argo/compare/master...helio:argo-apiclient-config?expand=1) for a proposed change. 
`rest.Config` is the standard way to connect to kubernetes and IMO should also be the way argo API client connects. 
`newArgoKubeClient` anyway just converts to a `rest.Config`, therefore it could also just accept a REST config directly. 

I marked the `ClientConfigSupplier` as deprecated but we can also leave it as is, I don't mind much. 

What are your thoughts about this change? Happy to provide additional changes or discuss alternatives 👍 

Another case I see there but is less grave: accept a `context.Context` instead of creating a new background context in `newArgoKubeClient`. This way the caller can decide what kind of context is being supplied and is also the standard way of working with Go APIs meanwhile. 

# Use Cases

We use argo's clientset to connect (similar to [the example](https://github.com/argoproj/argo/blob/master/examples/example-golang/main.go)) and submit workflows. To read logs we figured it's easiest to use the apiclient which already handles much of the logic we'd need anyway. As clientset APIs usually accept a `rest.Config` and the apiclient requires a `ClientConfig` we had to generate a `ClientConfig` based on the `rest.Config`. It's not much code, but it's unnecessary code:

```go
func getArgoAPIClient(cfg *rest.Config) (context.Context, apiclient.Client, error) {
	return apiclient.NewClientFromOpts(apiclient.Opts{
		ClientConfigSupplier: func() clientcmd.ClientConfig {
			loadingRules := &clientcmd.ClientConfigLoadingRules{}
			configOverrides := &clientcmd.ConfigOverrides{
				ClusterInfo: api.Cluster{
					Server:                   fmt.Sprintf("https://%s", cfg.Host),
					CertificateAuthorityData: cfg.TLSClientConfig.CAData,
				},
				AuthInfo: api.AuthInfo{
					ClientCertificateData: cfg.TLSClientConfig.CertData,
					ClientKeyData:         cfg.TLSClientConfig.KeyData,
					AuthProvider:          cfg.AuthProvider.DeepCopy(),
				},
			}
			return clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides)
		},
	})
}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by jessesuen** [comment]
> rest.Config is the standard way to connect to kubernetes and IMO should also be the way argo API client connects.
newArgoKubeClient anyway just converts to a rest.Config, therefore it could also just accept a REST config directly.

I agree it would be a cleaner interface.

> Another case I see there but is less grave: accept a context.Context instead of creating a new background context in newArgoKubeClient.

I agree. a main program should create a context and pass it to the libraries.

Would you like to submit a PR?

**Comment by mweibel** [comment]
Great to hear! 

Yes, I'll submit a PR 👍

**Comment by alexec** [comment]
Just a thought - any reason not to use the client directly? The benefit of `newArgoKubeClient` is that it wraps up server behaviour in the CLI. But you could use the generated code directly and that takes `rest.Config`.

**Comment by mweibel** [comment]
@alexec sorry for replying a bit late.

using the client directly - I wanted to avoid writing the [necessary code for reading argo workflow logs](https://github.com/argoproj/argo/blob/master/util/logs/workflow-logger.go#L40) again. I'm not sure if this code over there is considered public and can be used without breaking. If I use the argo api client that's somewhat more guaranteed - I hope, at least ;) 
Not sure if there's a better option though?

**Comment by alexec** [comment]
Only code in the `pkg` directory is considered public (Golang convention). That said, if it works for you - go for it.

To logs workflow pods, simply log any pod in the namespaces with the `workflows.argoproj.io/workflow: my-wf`. You'll need to watch for creation.
