### ISSUE TITLE
Docs doesn't  tell user differences between  workflow Stop and Terminate behaviors

### ISSUE THREAD

**Issue by bklaubos** [argoproj/argo-workflows#4454]
## Summary 
I expect  CLI docs to tell end user differences between `argo terminate` and `argo stop`  intentions and its expected behavior. I found none.

## Diagnostics

What Kubernetes provider are you using? 
AWS
What version of Argo Workflows are you running? 
2.16

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Feel free to submit a PR

**Comment by bklaubos** [comment]
I logged this bug because as end user, I don't know the difference between stop vs terminate workflow.  Are they the same?. If not, what are the expected behaviours.

**Comment by alexec** [comment]
They seem to be related to "shutdown strategy". 

* `Terminate` do not run any more node nodes in the workflow.
* `Stop` do not run any more nodes -  except exit handlers.

I'm not clear what happens to running nodes.

**Comment by simster7** [comment]
>  I'm not clear what happens to running nodes.

In both cases running nodes are stopped.

`Terminate` stops the workflow immediately, while `Stop` stops the workflow _but allows all exit handlers to run_.

**Comment by knabben** [comment]
What about adding these notes to the Cobra helper? I can help with this ticket.

https://github.com/argoproj/argo/blob/master/cmd/argo/commands/terminate.go#L16
https://github.com/argoproj/argo/blob/master/cmd/argo/commands/stop.go#L27

**Comment by simster7** [comment]
Sure, that would be great. I would also find a place in the docs to add the same information

**Comment by antoinetran** [comment]
> `Terminate` stops the workflow immediately, while `Stop` stops the workflow _but allows all exit handlers to run_.

@simster7 I was confused and thought terminate was stop and delete the pods. I think "Force stop" instead of "Terminate" would be better.
