### ISSUE TITLE
Cannot access artifacts for an archived workflow from the UI

### ISSUE THREAD

**Issue by sylock** [argoproj/argo-workflows#4463]
## Summary 

I click on the summary of a finished workflow. I get the list of all artifacts. When I click on one of them to download the artifact, I get a permission denied. See the screenshots below.

![2020-11-05_11h04_32](https://user-images.githubusercontent.com/2362405/98228747-4d0a4080-1f59-11eb-84fa-1beddc1d38e0.png)
![2020-11-05_11h04_47](https://user-images.githubusercontent.com/2362405/98228755-4f6c9a80-1f59-11eb-89c7-faa99769bf53.png)

## Diagnostics
* Openshift 4.5
* Argo 2.10.0
* The artifacts are stored on a S3. I checked and the artifacts are saved there correctly. 
* There is no error in the workflow logs.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you please try with `:v2.11.7`?

**Comment by sylock** [comment]
I tried with the updated version but I still get the same. I'm sure there is a permission not set correctly somewhere, but I don't find where.

**Updated version**
![2020-11-09_10h55_43](https://user-images.githubusercontent.com/2362405/98526712-5f96b980-227a-11eb-8692-b5428945c94d.png)

**The same issue**
![2020-11-09_10h56_11](https://user-images.githubusercontent.com/2362405/98526731-66bdc780-227a-11eb-9071-00745ee9fd4e.png)

**Comment by sylock** [comment]
I have another issue with the current installation and it is probably related. It seems I have some persistance problems. The history of runs of workflow (timeline page) is not persistant. Whil I'm logged in I can see the runs. If I log out and come back, I don't get the history back. But as you can see, accessing directly to the archive URL works. I don't see any issues in logs. Is it a problem with the postgres?

**Comment by alexec** [comment]
> I have another issue with the current installation and it is probably related. It seems I have some persistance problems. The history of runs of workflow (timeline page) is not persistant. Whil I'm logged in I can see the runs. If I log out and come back, I don't get the history back. But as you can see, accessing directly to the archive URL works. I don't see any issues in logs. Is it a problem with the postgres?

I think this is probably a UI bug. Can you check what the page URL shows?

**Comment by alexec** [comment]
This issue I fixed was introduced in v2.11 and fixed in v2.11.7. I don't, therefore, think this is the issue I thought it was. I think there is something else going on.

Can you confirm you can access the artifact directly from you artifact repository?

**Comment by sylock** [comment]
Hi Alex. Multiple things to say :)

After upgrading to 2.11.7 I lost the archived workflow. So I rerun one.
**I must bring your attention** that I'm using PNS containerRuntimeExecutor on an Openshift (and not raw Kubernetes).

1) Artifact
- What do you mean by the URL? My screenshot where you see "no such file or directory" is from that artifact URL.
- Note that it seems that between 2.10.0 and 2.11.7 the error message has changed (before it was permission denied)
- I checked with the API to remove any ambiguity with the UI. So if I try to list the archived workflow, I get no result ...
![2020-11-13_12h03_14](https://user-images.githubusercontent.com/2362405/99065889-5ffbc100-25a8-11eb-9a92-de5378b10e81.png)
- But if I query with the UID of the workflow I can find it!
![2020-11-13_12h05_10](https://user-images.githubusercontent.com/2362405/99066072-b0731e80-25a8-11eb-85b6-7e7ea107cc01.png)
- For your information I configured a S3 Repository:
![2020-11-13_12h01_03](https://user-images.githubusercontent.com/2362405/99065631-f976a300-25a7-11eb-963a-c2ff5aae4068.png)
- From the S3 repository: the artifact folder is there (check the screenshot)
![2020-11-13_12h23_20](https://user-images.githubusercontent.com/2362405/99067462-0f399780-25ab-11eb-9981-5d0bdfff8fe1.png)
- But If I go deeper in the subdirectories of the workflow folder, they are all empty ...
![2020-11-13_12h26_38](https://user-images.githubusercontent.com/2362405/99067783-8e2ed000-25ab-11eb-90ac-68dd07636915.png)
Just one example of one subdirectory but they are all the same: empty
![2020-11-13_12h26_11](https://user-images.githubusercontent.com/2362405/99067791-9129c080-25ab-11eb-937a-2bf495b3af18.png)

2) Lack of archived history
Just after running my workflow, I still loose the history. I checked with the REST API to remove any ambiguity about the UI:
![2020-11-13_12h03_14](https://user-images.githubusercontent.com/2362405/99067889-c3d3b900-25ab-11eb-8b8c-b3f76c64932f.png)

But if I query the archived workflow by UID I can find it in the history.
![2020-11-13_12h05_10](https://user-images.githubusercontent.com/2362405/99067853-b28aac80-25ab-11eb-9461-8682ffbd0a73.png)

**Comment by alexec** [comment]
Can you please attach your argo-server logs?

**Comment by sylock** [comment]
[argo-server-766f9c855c-r8trt.log](https://github.com/argoproj/argo/files/5554157/argo-server-766f9c855c-r8trt.log)
[argo-server-766f9c855c-shxld.log](https://github.com/argoproj/argo/files/5554159/argo-server-766f9c855c-shxld.log)

**Comment by alexec** [comment]
The logs show the following

* Running v2.11.7
* Several panics due to incorrect URL (hand crafted?): `http: panic serving 10.131.0.1:34530: runtime error: index out of range [3] with length 3`
* Successful download of artifact for archived workflow: `time="2020-11-13T10:30:47Z" level=info msg="Download artifact" artifactName=main-logs nodeId=quick-start-tutorial-dev-gl49d-1107067512 uid=c10d2205-f19b-4f6d-bda0-3fd664141f49`

I don't see any evidence of the `open /tmp` issue in these logs. Can you please try again?

Your screenshot shows an attempt to list workflows using `api/v1/archived-workflows/`. This is not a valid endpoint. You must either append the UID (to get a single archived workflow), or remove the trailing slash (to list workflows).

**Comment by sylock** [comment]
First about the archived listing.

Targeting the right API endpoint (without the trailing slash), I get 3 objects:
```
{
    "metadata": {},
    "items": [
        {
            "metadata": {
                "name": "quick-start-tutorial-dev-fmzg8",
                "namespace": "quickstart-nmi",
                "uid": "83adc3b5-3690-4b32-b408-b672fab31378",
                "creationTimestamp": "2020-11-18T15:31:31Z"
            },
            "spec": {
                "arguments": {}
            },
            "status": {
                "phase": "Succeeded",
                "startedAt": "2020-11-18T15:31:31Z",
                "finishedAt": "2020-11-18T15:32:48Z"
            }
        },
        {
            "metadata": {
                "name": "quick-start-tutorial-dev-762dn",
                "namespace": "quickstart-nmi",
                "uid": "ed109520-34d4-4b5d-ae6d-3a509c5cbc40",
                "creationTimestamp": "2020-11-13T10:32:37Z"
            },
            "spec": {
                "arguments": {}
            },
            "status": {
                "phase": "Succeeded",
                "startedAt": "2020-11-13T10:32:37Z",
                "finishedAt": "2020-11-13T10:34:03Z"
            }
        },
        {
            "metadata": {
                "name": "quick-start-tutorial-dev-gl49d",
                "namespace": "quickstart-nmi",
                "uid": "c10d2205-f19b-4f6d-bda0-3fd664141f49",
                "creationTimestamp": "2020-11-13T10:17:48Z"
            },
            "spec": {
                "arguments": {}
            },
            "status": {
                "phase": "Succeeded",
                "startedAt": "2020-11-13T10:17:48Z",
                "finishedAt": "2020-11-13T10:20:15Z"
            }
        }
    ]
}
```
But from the UI I see only one:
![2020-11-18_16h34_42](https://user-images.githubusercontent.com/2362405/99551422-21a53e00-29bc-11eb-903d-e0e54dcbd812.png)

**Comment by sylock** [comment]
I deleted the 2 pods of the argo-workflow to get fresh logs. The last job I run is 83adc3b5-3690-4b32-b408-b672fab31378.
[argo-server-766f9c855c-jm9c5.log](https://github.com/argoproj/argo/files/5561117/argo-server-766f9c855c-jm9c5.log)

Even without seing them from the Timeline page of the UI, I can directly access it from the url:
https://resilience-argo.<domain>/archived-workflows/quickstart-nmi/83adc3b5-3690-4b32-b408-b672fab31378?tab=summary

From there I still get the same result when I try to access artifacts.
![2020-11-18_16h43_08](https://user-images.githubusercontent.com/2362405/99552381-3cc47d80-29bd-11eb-8724-7de29b9fee7e.png)

About the http panic, I don't know where it's coming from and what is this IP. I'm working on it.

**Comment by alexec** [comment]
I can't see filters in the new screenshot. This page filters by date by default. Can you check the actual HTTP request made in your browser console?

Next steps - can we get on a Zoom?

If not, can I get you to provide the full YAML for the `argo-server` pod? I want to check that `/tmp` is mounted.

**Comment by sylock** [comment]
I Alex,

Thank you for you help. I found a solution for both problems. Indeed, there was no volume monted on /tmp of the argo-server pods. It was not an issue when I tried it on a raw kubernetes. But on openshift with the PNS engine, it did throw my issue.

I can suggest to check and log at the boot of argo-server when PNS is used and argo-server has no volume monted on /tmp, as a request for improvement for further similar troubleshooting ;)

Thank you,

**Comment by alexec** [comment]
That's odd. The installation manifests do mount /tmp.

**Comment by sylock** [comment]
It's true. Indeed, I took the work (manifest) of a collegue and port it to openshift 4. He flatten the manifest into one file and I see there are differences between the upstream manifest and what I have.
I need to change that. So one question : what is the best way to use your manifest "out of the box" while bringing the modifications needed for my environment. Of course I could fork the repo and change it. But it will be difficult later on for the lifecycle since I would need to merge it at each sync. What do you think? Do you have an advice/best practice?

**Comment by clementlecorre** [comment]
hi,
I also have systematic errors when I want to download artefacts. 

Ui error: I have error 500
`open /tmp/artifact390645041: no such file or directory`

argo-server: I see no error
`time="2020-11-25T10:55:45Z" level=info msg="Download artifact" artifactName=main-logs`

argo v.2.11.7
eks 1.16

**Comment by alexec** [comment]
> hat is the best way to use your manifest "out of the box"

We use Kustomize.
