### ISSUE TITLE
Trigger event source from UI

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4474]
I'd like to be able to click on an event source and trigger it manually.

**Comment by sarabala1979** [comment]
@alexec This feature will applicable only webhook and Calendar event sources.  Do we need this feature?

**Comment by alexec** [comment]
I think we should get evidence for the need for this feature. Maybe ask in #argo-events?

**Comment by tvalasek** [comment]
We use webhooks only. I'm not sure how we would benefit from it. Hitting Eventsource API externally with JSON payload or trigger from UI does not give us any added value. Speaking for ourselves :-)
