### ISSUE TITLE
How can I update pod request memory and restart it when Pod OOMKilled

### ISSUE THREAD

**Issue by zen-xu** [argoproj/argo-workflows#4493]
# Use Cases

When would you use this?

It's hard to guess how much memory need for our tasks to run. So we want if the pod is OOMKilled, argo can scale up its memory and restart it automaticly.

**Comment by alexec** [comment]
Alternative #3106

**Comment by alexec** [comment]
There was a request to retry any failed workflow pod using different parameters (e.g. resource requests/limits).

#3106 is about helping identify these prior to execution.

**Comment by zen-xu** [comment]
Thanks @alexec 

Is there a convenient way to get pod message?

<img src="https://user-images.githubusercontent.com/38552291/98656071-3447c380-237b-11eb-907c-01c98267df79.png" width="40%" height="40%">

**Comment by therc** [comment]
I agree with @zen-xu 

We have the same issue. In our case, we could use input file size as a rule of thumb to set memory limits, but even then, there are some workloads where memory usage depends to a great extent on the contents (entropy, even) of the files. I am not able to distinguish authentic failures (the job returning exit code 1) from the kernel killing our pods, so the risk is that we might end up retrying something that will fail at any memory size. Exposing the message would go a long way. Would a PR be accepted if I wrote one?

**Comment by sarabala1979** [comment]
@therc more welcome to create PR. There is a hacky workaround. you can have a pre-step to determine the resource for the processing step and pass it as `podSpecPatch` on `processing step`

**Comment by therc** [comment]
@sarabala1979 I use podSpecPatch to set a higher limit when retrying. What I need to avoid is re-running a graph node that didn't run out of memory. Some of these workloads use GPUs, so doing all this useless extra work can get expensive quickly. Both the code and the data in a given workflow are very experimental and thus have a high degree of variability, so we'd probably want more than one retry.

Ideally, I'd create retry nodes with

`when: "({{tasks.previous.status}} == Failed) && (tasks.previous.message == OOMKilled)"`

or just the second boolean, since that would imply a Failed status.

**Comment by sarabala1979** [comment]
@simster7 was exploring previously adding condition base `retrystrategy` select the `node` and other properties. 
Simon: can you provide your thought?

**Comment by terrytangyuan** [comment]
I recently added a retry policy to allow retry only on transient errors in https://github.com/argoproj/argo-workflows/pull/4999. You can also specify a regular expression that captures any additional errors that can be seen as transient and retryable (based on the node messages like the OOMKilled that you are interested), see TRANSIENT_ERROR_PATTERN in https://github.com/argoproj/argo-workflows/blob/master/docs/environment-variables.md. 

Is this what you need?

**Comment by therc** [comment]
That's close. Is the retry counter exposed to the templates? Say you want
the first retry to use twice as much memory as the original attempt. We
don't want to rerun with the same resources if there was an OOM error.

**Comment by terrytangyuan** [comment]
Yes, you should be able to use the variable "retries" in https://github.com/argoproj/argo-workflows/blob/master/docs/variables.md#containerscript-templates

**Comment by therc** [comment]
Great! I'll give that a try tomorrow. Thank you so much.

**Comment by tczhao** [comment]
@terrytangyuan On a slightly different topic, I think we'd better add an example or extend the documentation to let users know there's OnTransientError retry policy.

**Comment by terrytangyuan** [comment]
> @terrytangyuan On a slightly different topic, I think we'd better add an example or extend the documentation to let users know there's OnTransientError retry policy.

Definitely. Just documented this in https://github.com/argoproj/argo-workflows/pull/5196.

**Comment by therc** [comment]
> Yes, you should be able to use the variable "retries" in https://github.com/argoproj/argo-workflows/blob/master/docs/variables.md#containerscript-templates

Maybe I'm doing something stupid, but I can't get "retries" and "podSpecPatch" to play nice.
https://github.com/argoproj/argo-workflows/issues/5219
