### ISSUE TITLE
No argo, argoexec, argo-workflow binary in latest argocli docker images

### ISSUE THREAD

**Issue by davidgibbons** [argoproj/argo-workflows#4541]
## Summary 
The update in #4519 attempts to variables the os, but as the variable doesn't exist in the 3 images that actually copy over the binaries, it doesn't copy over anything, leading to building a docker image with no binaries in it.

This basically makes all new installs or anything that pulls the latest container fail.

## Diagnostics

```
> docker run -i -t  argoproj/argocli:latest                                                                                                                                                          
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"argo\": executable file not found in $PATH": unknown.

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@terrytangyuan could you take a look by any chance? Thank you.

**Comment by alexec** [comment]
@simster7 @sarabala1979 I imagine this would block  v2.12.0-rc3

**Comment by terrytangyuan** [comment]
Thanks for the catch! @davidgibbons Looks like the PR is already merged. Thanks for the quick fix.
