### ISSUE TITLE
Wait for the sidecar container finish during Workflow run

### ISSUE THREAD

**Issue by andreyvelich** [argoproj/argo-workflows#4545]
# Summary

Hi Everyone!

Is it possible to define Workflow when wait container waits until all sidecar pod’s containers are finished ?
Maybe specify some flag to the Workflow controller.

As I can see [here](https://github.com/argoproj/argo/blob/master/cmd/argoexec/commands/wait.go#L33), wait container kills all Pod's containers that are not main or wait.

I want to use Argo workflow in my custom CRD which injects additional sidecar container to the created pod and runs the script after main pod's container is finished.
So my sidecar container should not be killed after the main container is complete.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
> I want to use Argo workflow in my custom CRD which injects additional sidecar container to the created pod and runs the script after main pod's container is finished.
@andreyvelich 
Just curious, how you do inject sidecar containers on a created pod?

**Comment by andreyvelich** [comment]
> > I want to use Argo workflow in my custom CRD which injects additional sidecar container to the created pod and runs the script after main pod's container is finished.
> 
> @andreyvelich
> Just curious, how you do inject sidecar containers on a created pod?

@sarabala1979 I am using [MutatingAdmissionWebhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook) to mutate additional container to the necessary Pods in namespace that has required label.
Once Pod is created in this namespace, controller checks if mutation is required.
If it is required, controller adds another container to this Pod.

/cc @gaocegege @johnugeorge

**Comment by alexec** [comment]
Killing sidecars like this is by design. I don't think we can fix it. The emissary executor does not kill sidecars like this, the controller does it when it sees the wait container has exited. Could you try that? You need v3.1

**Comment by andreyvelich** [comment]
Thank you for this information @alexec!
To define Emissary runtime executor I just need to define appropriate label, like in this example: https://github.com/argoproj/argo-workflows/blob/master/examples/container-set-template/workspace-workflow.yaml#L7 ?

**Comment by terrytangyuan** [comment]
@andreyvelich Good to see you around here! Normally you don't have to specify the label in the workflow unless your controller is configured to support multiple types of executors and you want to use a specific executor for that particular workflow. You can just configure your executor in the controller's configmap: https://github.com/argoproj/argo-workflows/blob/ec4c662c952328015c4ed0eb0a04579f5aac891e/docs/workflow-controller-configmap.yaml#L107-L110

**Comment by andreyvelich** [comment]
Thank you for the clarification @terrytangyuan!
I will try this out.
