### ISSUE TITLE
"clearer" flags name for Argo CLI

### ISSUE THREAD

**Issue by xakraz** [argoproj/argo-workflows#4552]
# Summary

I would like to update cli flags to remove ambiguity and confusion between "target" (Kubernetes API server or Argo API server)

# Use Cases

Since, we already have flags like `--argo-server` and `--kubeconfig` I would like to spread this kind of prefixes to remove ambiguity.

```
--server   -> --kube-api-server
--user     -> --kube-user
--username -> --argo-user
--token    -> --argo-token
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
We can't really change these now.
