### ISSUE TITLE
Improve docs around inputs and arguments

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4556]
New Relic highlighted that it is hard to understand these concepts.

**Comment by kennytrytek** [comment]
Hi Alex. I'd be interested in taking this one on, as I also found it initially very difficult to reason about the nuances of inputs. Do you have any more context about any specific concepts New Relic found hard to grasp, or should I just do an overview of the existing documentation and see where there are opportunities to update or add clarifying documentation?

The [Beginner section](https://argoproj.github.io/argo/workflow-concepts/) of the user guide seems like a section that could have a page specific to the different types of inputs and outputs maybe highlighting parts of some existing examples?

**Comment by alexec** [comment]
That'd be great - do you want to submit a PR with some new docs?

**Comment by kennytrytek** [comment]
Docs PR merged; this can be closed unless there was more work to do?
