### ISSUE TITLE
The 2.12.0-rc2 binaries aren't compressed

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-workflows#4568]
The [release page](https://github.com/argoproj/argo/releases/tag/v2.12.0-rc2) has instructions for compressed binaries, but they aren't actually compressed.

So either the assets or the instructions should be updated.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Fixed
