### ISSUE TITLE
Provide way to override the notification setting for manually submitted job

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-workflows#46]
Currently UI uses same predefined notification settings for all manually submitted jobs: notify submitter of success or failure. UI show allow user to change notification settings. 

The use case:
Developer manually run job which is supposed to build/test release candidate and wish to notify manager about result. Automatic notification would improve use experience.

**Comment by rahuldhide** [comment]
Here is the design proposal for this use case-
![jobnotification](https://user-images.githubusercontent.com/30275450/30146318-2da6c58e-934c-11e7-83a3-0cedbdd51bf4.png)

@saradhis @mukulikak @pratulw @edlee2121 Although we are giving these comprehensive options in the job creation process, users may not want to tweak these every time. We need these event based rules in the personal notification settings or in the global notification options.

**Comment by wokeGit** [comment]
@rahuldhide Does "Set Up Job Notifications" step set the same notification rules for each submitted template? Ie. user selected 3 templates in "Select templates to create jobs" step, then skip to "Review workflow parameters" and then "Set Up Job Notifications". Selected notification rules will be set for each of selected template. Do I understand it correct?

**Comment by wokeGit** [comment]
Working on it

**Comment by wokeGit** [comment]
@rahuldhide 
- Is it full list of job events? ['on_change', 'on_cron', 'on_failure', 'on_pull_request', 'on_pull_request_merge', 'on_push', 'on_start', 'on_success']
- Argo users and groups should show side panel with argo users, the same as on the notification rules panel?
![screen shot 2017-10-05 at 14 25 51](https://user-images.githubusercontent.com/13086525/31227180-2e25d704-a9d9-11e7-8392-44fceeaf0b81.png)
or it should be dropdown list with predefined values like: submitter, committer, author?
- Slack Channels - it should be a input or side panel, the same as on the notification rules panel?
![screen shot 2017-10-05 at 14 28 41](https://user-images.githubusercontent.com/13086525/31227268-8440ea20-a9d9-11e7-876e-88ae73021275.png)
- is it possible to remove all the notifications rules? I mean the job doesn't have any notification rule?
