### ISSUE TITLE
[Feature request] Step-level exit handler information

### ISSUE THREAD

**Issue by matt-carr** [argoproj/argo-workflows#4621]
# Summary

Step-level exit handlers should include context regarding the step they are attached to.

Support:
https://github.com/argoproj/argo/issues/4138
https://github.com/argoproj/argo/issues/3348

# Use Cases

Given https://github.com/argoproj/argo/blob/master/examples/exit-handler-step-level.yaml

I would want information populated by the step completion to be available (e.g. anything from https://argoproj.github.io/argo/variables/#steps-templates)

So that I can do things like report incremental workflow status

For example: pretend I have a long-running workflow with e.g. 20 steps and an application that would like to monitor the workflow - I'd like to use exit handlers attached to every step that can make an API request/post to a message queue/etc to the application with information about the step that just completed.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by whynowy** [comment]
You can use `ResourceEventSource` from Argo Events to do it.

**Comment by matt-carr** [comment]
Sure, that works for statuses, but afaik there's no insight into outputs/exit status/etc

**Comment by seanmarpo** [comment]
Similar to @matt-carr, was surprised this didn't work since there was a specific example for adding an exit handler to individual steps. I would have expected the exit handler to have access to the current step's context. Thanks for raising this

**Comment by sarabala1979** [comment]
#5455 will resolve this use-case

**Comment by matt-carr** [comment]
😍 watching eagerly

**Comment by Atharex** [comment]
Nice feature +1 Is it already available in Argo 3.0.7?

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/commit/c59f59ad0e7609cf8b87d6733f73efa9ccf44484 is the relevant commit so looks like it's only available in 3.1.
