### ISSUE TITLE
Complex CronWorkflow Schedules are not working properly

### ISSUE THREAD

**Issue by claas-fridtjof-lisowski** [argoproj/argo-workflows#4637]
## Summary 

We use a CronWorkflow with this schedule:

```
schedule: 0 10 10,27 * */2,*/3,*/4,*/5
```

Argo ignores the day of the month and triggers the workflow as soon as the day of the week matches.

Expected trigger schema in words:

```
“At 10:00 on day-of-month 10 and 27 if it's on every 2nd day-of-week, every 3rd day-of-week, every 4th day-of-week, and every 5th day-of-week.”
```
From [https://crontab.guru/#0_10_10,27_*_*/2,*/3,*/4,*/5](https://crontab.guru/#0_10_10,27_*_*/2,*/3,*/4,*/5)

Kubernetes CronJob is handling it as expected, Argo CronWorkflow does not.

## Diagnostics

AKS, Kubernetes v1.17.13
Argo v2.11.7 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
May I suggest you open an issue with https://github.com/robfig/cron?

**Comment by claas-fridtjof-lisowski** [comment]
Sure, I will do that.

**Comment by claas-fridtjof-lisowski** [comment]
That's the issue https://github.com/robfig/cron/issues/358

**Comment by simster7** [comment]
@claas-fridtjof-lisowski 

I just investigated and K8s uses the same cron library we use, so I don't understand why the schedule would work on K8s CronJob but not on CronWorkflow. Can you take a look? Would it have something to do with `timezone`, as that is the only significant difference between us and k8s in terms of scheduling.

**Comment by simster7** [comment]
The use version `v1.1.0` and we use version `v3.0.1`... that might be the difference. Not sure if I would feel comfortable going down to version `v1.1.0` to match K8s though
