### ISSUE TITLE
Doc: Need to specify the concurrency model for `WithSequence` loop 

### ISSUE THREAD

**Issue by bklaubos** [argoproj/argo-workflows#4657]
##  Need to specify the concurrency model for `WithSequence` loop 
`WithSequence ` loop  concurrency behaviour is currently not documented clearly as parallel or sequential.
The other thing  unclear: How are the `outputs.Parameters` or `outputs.Artifacts` of an item in the sequence related to each other.
Is each output independent or they are aggregated as one single output?

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Expanded steps, i.e.`withItems`, `withParam`, and `withSequence` are launched in parallel with non-deterministic ordering. 

Expanded steps do not currently provide a way to access the aggregated output artifacts. Parameters can be accessed.

See #934

**Comment by alexec** [comment]
Would you like to submit a PR to update the docs?

**Comment by bklaubos** [comment]
No concept of `waitGroup` for `Items`???

**Comment by SleepyBrett** [comment]
Hey guys, this is still a problem. What is the reasoning behind not allowing these to run without parallelism?
