### ISSUE TITLE
Move shared UI V3 components to `argo-ui`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4685]
# Summary

Move the shared UI component to argo-ui.

# Use Cases

This will make it easier to reuse those components.

@dcherman @alexmt I think we should go over this list and make a determination:

Simple UI components (e.g. wrap a form input or add some feature to it):

ui/src/app/shared/components/button.tsx
ui/src/app/shared/components/chat-button.tsx
ui/src/app/shared/components/checkbox-list.tsx
ui/src/app/shared/components/data-loader-dropdown.tsx
ui/src/app/shared/components/drop-down-button.tsx
ui/src/app/shared/components/icon.ts
ui/src/app/shared/components/icons.ts
ui/src/app/shared/components/link-button.tsx
ui/src/app/shared/components/loading.tsx
ui/src/app/shared/components/notice.tsx
ui/src/app/shared/components/nudge.tsx
ui/src/app/shared/components/number-input.tsx
ui/src/app/shared/components/text-input.tsx
ui/src/app/shared/components/filter-drop-down.tsx
ui/src/app/shared/components/toggle-button.tsx
ui/src/app/shared/components/upload-button.tsx
ui/src/app/shared/components/tags-input/tags-input.tsx

Complex UI components:

ui/src/app/shared/components/editors/key-value-editor.tsx
ui/src/app/shared/components/editors/labels-and-annotations-editor.tsx
ui/src/app/shared/components/editors/metadata-editor.tsx
ui/src/app/shared/components/error-notice.tsx
ui/src/app/shared/components/object-editor/object-editor.tsx
ui/src/app/shared/components/object-parser.ts
ui/src/app/shared/components/resource-editor/resource-editor.tsx
ui/src/app/shared/components/zero-state.tsx

Fast SVG DAG rendering panel:

ui/src/app/shared/components/graph/coffman-graham-sorter.ts
ui/src/app/shared/components/graph/dfs-sorter.ts
ui/src/app/shared/components/graph/fast-layout.ts
ui/src/app/shared/components/graph/graph-panel.scss
ui/src/app/shared/components/graph/graph-panel.tsx
ui/src/app/shared/components/graph/icon.tsx
ui/src/app/shared/components/graph/label.tsx
ui/src/app/shared/components/graph/layout.ts
ui/src/app/shared/components/graph/pretty-layout.ts
ui/src/app/shared/components/graph/types.ts

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by agilgur5** [comment]
I think most of these were not moved (although a few might have been). They won't be moved these days per https://github.com/argoproj/argo-ui/issues/453
