### ISSUE TITLE
Make sure all examples and features work out of the box with non-Docker executors

### ISSUE THREAD

**Issue by Ark-kun** [argoproj/argo-workflows#4690]
Kubernetes is planning to deprecate Docker: https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

Previously Argo had some issues with artifact/parameter passing on non-Docker executors. Our clients have reported some issues when running the artifact passing examples on OpenShift.

Let's make sure all examples can run on non-Docker executors without changes.

**Comment by alexec** [comment]
It is not possible for all executors to support all examples, so this is not actually possible. However, we do need to think about how ultimately people won't be running Docker and how we support Docker uses cases.

**Comment by Ark-kun** [comment]
>It is not possible for all executors to support all examples, so this is not actually possible.

Perhaps we can have a document describing the limitations.

Hopefully the core Argo features (e.g. Artifact passing) can be supported with all executors.

**Comment by alexec** [comment]
@Ark-kun my favourite executor is the `pns`. This is both secure and flexible. If you `runAsNonRoot` it requires you to use the "empty dir" pattern if your output artifacts are not on a mounted volume.  References:

https://argoproj.github.io/argo/workflow-executors/

**Comment by alexec** [comment]
Side note, checkout CRI-O: https://cri-o.io/

**Comment by Bobgy** [comment]
> @Ark-kun my favourite executor is the `pns`. This is both secure and flexible. If you `runAsNonRoot` it requires you to use the "empty dir" pattern if your output artifacts are not on a mounted volume. References:
> 
> https://argoproj.github.io/argo/workflow-executors/

Thanks for the suggestion.
@Ark-kun I think we should switch KFP to `pns` by default and start validating stableness via e2e tests.

**Comment by Ark-kun** [comment]
> @Ark-kun I think we should switch KFP to `pns` by default and start validating stableness via e2e tests.

The main issue holding that back is https://github.com/argoproj/argo/issues/2679 . Making Argo auto-mount volumes (e.g. `emptyDir`) under output artifacts would solve this.

**Comment by alexec** [comment]
All examples now run using emissary. I think this can be closed.
