### ISSUE TITLE
Argo UI: Unknown error

### ISSUE THREAD

**Issue by tvalasek** [argoproj/argo-workflows#4714]
## Summary 

When using the UI I randomly get:

```
Unknown error. Open your browser error console for more information.:  Reload 8s`
```
Reload button is dead.

Browser error console shows:

```
2:2746/api/v1/workflow-events/test-argo-2-12?listOptions.fieldSelector=metadata.name=create-6w7w2:1 GET http://internal-XXXXXXXXXXXXXXX.us-west-2.elb.amazonaws.com:2746/api/v1/workflow-events/test-argo-2-12?listOptions.fieldSelector=metadata.name=create-6w7w2 net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
```

## Diagnostics

What Kubernetes provider are you using? 

`AWS EKS v1.15.12-eks-31566f`

What version of Argo Workflows are you running? 

`v2.12.0-rc5`

OS and browser details:

Vivaldi | 3.4.2066.106 (Stable channel) (x86_64)
-- | --
Revision | 9faa7da6e287d30fe3948ac5d9d62aefe7977da5
OS | macOS Version 10.15.7 (Build 19H15)
JavaScript | V8 8.6.395.25

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Do you have an ingress or proxy in front of your server? If so, please check its configuration wrt to keep-alives.

**Comment by tvalasek** [comment]
i can do. i have a question though - something in this release that would trigger this behaviour? I'm using v2.9.5 in exactly same setup and that works just fine.

**Comment by alexec** [comment]
Can you try `:latest` and see if you have the same problem?

**Comment by tvalasek** [comment]
ehm, with `:latest` I can't even get the `workflow-controller` pod running
```
kg po -n argo
NAME                                   READY   STATUS             RESTARTS   AGE
argo-server-698f5b9777-p8npw           1/1     Running            0          6m45s
workflow-controller-8457b7bf64-phnrz   1/1     Running            0          4h5m
workflow-controller-ffd5db46d-l76lb    0/1     CrashLoopBackOff   1          9s
```
no obvious reason, no logs :(

**Comment by alexec** [comment]
ah - I should have just said - just run the argocli, not the controller (which is broken)

**Comment by tvalasek** [comment]
tried following setup

```
argocli:latest
argoexec:v2.12.0-rc5
workflow-controller:v2.12.0-rc5
```

Still receiving same error. I tried Chrome as well (just in case), same thing

**Comment by alexec** [comment]
If you reload the page it goes away?

**Comment by tvalasek** [comment]
yes
