### ISSUE TITLE
Unsuccessful HTTP response: workflows.argoproj.io is forbidden: User "system:serviceaccount:argo:argo-server" cannot list resource "workflows" in API group "argoproj.io" in the namespace

### ISSUE THREAD

**Issue by mimicode** [argoproj/argo-workflows#4746]
## Summary 

Unsuccessful HTTP response: workflows.argoproj.io is forbidden: User "system:serviceaccount:argo:argo-server" cannot list resource "workflows" in API group "argoproj.io" in the namespace

**Comment by alexec** [comment]
As per the error message  - the RBAC role and rolebinding you have set-up do not grant argo-server service account the "list workflows" permission. You need to correct this.

**Comment by Guchin** [comment]
Hi, the same happened to me what specific roles the rgo-server service account needs and how I can configured them ? Thanks

**Comment by alexec** [comment]
@Guchin examples can be found in the installation manifests.
