### ISSUE TITLE
Embeddable UI widgets

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4769]
Create a set of widgets to allow users to embed them into their apps.

* Animated workflow graph.
* Workflow status and progress badges.

Themeable?

**Comment by justinmchase** [comment]
I am looking for this, was this implemented or why was this closed?

**Comment by agilgur5** [comment]
Yes these were implemented in Argo v3. In the UI, you can create widgets at the `/widgets` route.

The docs mention it but are unfortunately not detailed: https://argo-workflows.readthedocs.io/en/release-3.5/widgets/
