### ISSUE TITLE
v2.12: `pod deleted` + `re-apply` error  = errored workflow

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4798]
## Summary 

In v2.12, we can get a `pod deleted` error under high load. I believe this is caused by factors interplaying:

1. The workflow completes successfully.
2. A pod is then deleted during clean-up, we'll get a re-queue of the workflow.
3. On the next reconciliation the informer returns the same (and now out of date) workflow as the last reconciliation.
4. The pod has been deleted, so the reconciliation marks the pod as `Error: pod deleted`. The workflow is marked as errored
5. Update fails due to resource version check.
6. Re-apply overwrites the previously successful workflow with an error workflow.
7. If pod GC strategy is on-success, then the TTL controller will error.

Causes:

* `reapplyUpdate` will happily overwrite a completed workflow or node. 
* v2.12 added indexers. I _think_ when any of these errors, the workflow update is lost
* I _think_ that `DEFAULT_REQUEUE_TIME` should be longer, up to 10s.

Solution

* Modify `reapplyUpdate` to check to see it is overwriting a successful workflow or any successful nodes. Error out. This will prevent any future cases of succeeded workflows being marked as error.
* Modify the indexers so that they can never return errors. This will prevent conflict error.
* I don't think that the grace period for recently created pods is needed after these changes. Mark it with at `TODO` to remove.

Relates to #4795, #4634, #4794

**Comment by simster7** [comment]
Fix for this is out on https://github.com/argoproj/argo/releases/tag/v2.12.3
