### ISSUE TITLE
minor day-zero bug: pods not cleaned-up with `PodGCOnSuccess`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4799]
## Summary 

Once a workflow is complete, all of its pods should be deleted on labeled as complete. If the pod-gc is on success, and the pod fails, it is not labeled.

I think this impact is small otherwise we'd have heard about it.

**Comment by terrytangyuan** [comment]
I think this is no longer an issue and we've covered most of the cases in e2e tests: https://github.com/argoproj/argo-workflows/blob/master/test/e2e/pod_cleanup_test.go

Let me know if I've missed anything else and I can help look into it.
