### ISSUE TITLE
Wait container stuck in running state with Dynatrace enabled in the cluster

### ISSUE THREAD

**Issue by amal-kumar** [argoproj/argo-workflows#4845]
We have upgraded the Argo Version (i.e. v.2.12.1) as suggested by Alex in the below bug

_Originally posted by @amal-kumar in https://github.com/argoproj/argo/issues/4678#issuecomment-742027363_

But still we are getting the same issue i.e. wait container is getting stuck. 

Only after disabling the dynatrace on the cluster we were able to resolve this. 

How is dynatrace causing this issue and has this been analysed before? Because I can see the similar issue was raised earlier also. reference : https://github.com/argoproj/argo/issues/1382#issuecomment-499951098

**Comment by alexec** [comment]
I'd suggest trying v2.12.3 as this has some performance fixes in it. If not, it is likely to be a set-up issue. Does Dynatrace using mutating web hooks?

**Comment by amal-kumar** [comment]
Hi @alexec , we will analyse the upgrade to v2.12.3 .

Meanwhile, on the dynatrace issue, it is possible for you (or, someone from your team) can join a call with our Dynatrace team to debug this further?

**Comment by jackstuart92** [comment]
Hi @alexec,

Dynatrace uses mutating webhoks yes.

Under the hood, extensible admission uses a set of plugins called admission controllers, one of which fires a mutating webhook to a Dynatrace service. The mutating webhook, defined by the OneAgent Operator, tells our service that a pod is about to start, and asks if anything should be changed. If your custom resource-definition targets the pod’s namespace, OneAgent will be injected before it starts. If not, the pod will remain as is.

source: https://www.dynatrace.com/news/blog/address-kubernetes-observability-configuration-chaos-with-unparalleled-automation/

**Comment by alexec** [comment]
We've seen other mutating webhooks tend to edit and break resources. See #4126. You'll need to speak to Dynatrace for information about how they impact workflows.

**Comment by jackstuart92** [comment]
Thanks for this. Dynatrace are asking for the events from the Argo pods from just after you start to when you shut them down to better understand what is going on here.

**Comment by saubaner** [comment]
@jackstuart92 According to the Dynatrace documentation, it also supports Pod runtime injection as well as Container build-time injection which does not use mutating webhooks. Worth a try?

**Comment by mreider** [comment]
FYI the issue reported to Dynatrace support looks less about the mutating webhook and more about injection via OneAgent DaemonSet. These are separate injection strategies. The webhook is unnecessary if the DaemonSet is installed on the node, which in this case it was. Support case is being diagnosed.
