### ISSUE TITLE
Suspending a workflow does nothing

### ISSUE THREAD

**Issue by DrissiReda** [argoproj/argo-workflows#4876]
Deployed argo version v2.12.2 on kubernetes in pns mode.

Everything works fine, I just am unable to suspend any workflow. Clicking on suspend does nothing, the workflow is still displayed as running.

The only difference is in UI, the suspend button is greyed out and I can press resume, but pressing resume changes nothing again, the workflow just keeps running.

**Comment by alexec** [comment]
I think the workflow should only suspend the when the next node starts.

@simster7 ?

**Comment by simster7** [comment]
> I think the workflow should only suspend the when the next node starts.

This is correct... nodes already running are not (and cannot) be suspended
