### ISSUE TITLE
Namespaced Argo raises "Forbidden" error in the UI on initial load

### ISSUE THREAD

**Issue by tumido** [argoproj/argo-workflows#4885]
## Summary 

UI raises "Forbidden" notifications on the first load due to the context switching in the namespaced installs. Solved in `argocli:ui-v3`, but still affects current latest release (2.12.4), therefore I'm raising it as an issue.

## Diagnostics

1. Argo is deployed as a `--namespaced` and Argo UI is accessible without authentication.
2. User loads the `<argo_host>/` root endpoint
3. User is redirected by the front end server to `<argo_host>/workflows`
4. User is redirected by the front end server to `<argo_host>/workflows/<namespace>`

The steps no. 3. mounts and renders the [`WorkflowList`](https://github.com/argoproj/argo/blob/v2.12.4/ui/src/app/workflows/components/workflows-list/workflows-list.tsx) component, which also mounts the [`WorkflowFilters`](https://github.com/argoproj/argo/blob/v2.12.4/ui/src/app/workflows/components/workflow-filters/workflow-filters.tsx). These filters are fetching `CronWorkflow`s [here](https://github.com/argoproj/argo/blob/f97bef5d00361f3d1cbb8574f7f6adf632673008/ui/src/app/workflows/components/workflow-filters/workflow-filters.tsx#L67) and `WorkflowTemplates` [here](https://github.com/argoproj/argo/blob/f97bef5d00361f3d1cbb8574f7f6adf632673008/ui/src/app/workflows/components/workflow-filters/workflow-filters.tsx#L60) . Since this is happening on the  `<argo_host>/workflows` page, the `props.namespace` is undefined, therefore the call results in a cluster scoped listing of the resources on the backend:

```
time="2021-01-14T14:41:11.234Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = cronworkflows.argoproj.io is forbidden: User \"system:serviceaccount:opendatahub:argo-server\" cannot list resource \"cronworkflows\" in API group \"argoproj.io\" at the cluster scope" grpc.code=PermissionDenied grpc.method=ListCronWorkflows grpc.service=cronworkflow.CronWorkflowService grpc.start_time="2021-01-14T14:41:11Z" grpc.time_ms=2.719 span.kind=server system=grpc
time="2021-01-14T14:41:11.234Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = workflowtemplates.argoproj.io is forbidden: User \"system:serviceaccount:opendatahub:argo-server\" cannot list resource \"workflowtemplates\" in API group \"argoproj.io\" at the cluster scope" grpc.code=PermissionDenied grpc.method=ListWorkflowTemplates grpc.service=workflowtemplate.WorkflowTemplateService grpc.start_time="2021-01-14T14:41:11Z" grpc.time_ms=2.796 span.kind=server system=grpc
time="2021-01-14T14:41:11.331Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = workflows.argoproj.io is forbidden: User \"system:serviceaccount:opendatahub:argo-server\" cannot list resource \"workflows\" in API group \"argoproj.io\" at the cluster scope" grpc.code=PermissionDenied grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-01-14T14:41:11Z" grpc.time_ms=1.722 span.kind=server system=grpc
```

This returns forbidden to the UI:

![image](https://user-images.githubusercontent.com/7453394/104708620-3da83000-571e-11eb-9fe5-7946601a3c0a.png)

And in the end raises following notifications in the UI:

![image](https://user-images.githubusercontent.com/7453394/104735888-765a0080-5742-11eb-86c8-c36dddc87b85.png)

Then the user gets redirected to the `<argo_server>/workflows/<namespace>` and everything behaves as it should, yet the notifications are carried over and they still appear on the page.

This issue is solved by the UI rewrite in https://github.com/argoproj/argo/pull/4470 (container image `argocli:ui-v3`), however since the fix is targeted for ~`2.13.*`~ `3.0`, this issue might be still relevant for current `2.12.*` branch. 

What Kubernetes provider are you using? Openshift

What version of Argo Workflows are you running? 2.12.4

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
There will not be a v2.13. v2.12 will be LTS. However, if this is fixed in v3.0, then I'm not sure it is worthwhile fixing?

**Comment by tumido** [comment]
Oh... Well, if v2.12 is a LTS I'd say it should be considered for fixing in the LTS branch. :slightly_smiling_face: I'll leave it up to you.

I think it's a slight annoyance but it's rather a cosmetic bug than anything else.

**Comment by alexec** [comment]
Could you try on `argoproj/argocli:latest`? You will be able to run the v3.0 UI with v2.12 controller safely.

**Comment by tumido** [comment]
Yes, that is a possible workaround which works just fine in my dev env (similar to running `argocli:ui-v3`). However it's not viable in our anything-else-than-dev envs (we would be running mismatched version containers) + it does not actually solve the issue for the 2.12 branch.

Overall, I'd say this is more of an cosmetic issue than anything else. :slightly_smiling_face: It depends if you want to invest your time into fixing it. If not, feel free to close this issue and do something more fun :+1:

**Comment by alexec** [comment]
Let's keep this issue and decide based on 👍 if we fix it. You're welcome to submit a PR for the release-2.12 branch of course.

**Comment by vumdao** [comment]
I got this issue in v3.1.1

```
 Unsuccessful HTTP response: workflows.argoproj.io is forbidden: User "system:serviceaccount:argo:jenkins" cannot list resource "workflows" in API group "argoproj.io" in the namespace "undefined"
```

![image](https://user-images.githubusercontent.com/37215642/124374620-04ad4900-dcc7-11eb-8731-f94cbf453384.png)

**Comment by shengzhou1216** [comment]
same issue for v3.1.6

**Comment by nicon89** [comment]
Same issue in v3.1.10.

**Comment by DomineCore** [comment]
Same issue in v3.2.5.
<img width="1520" alt="image" src="https://github.com/argoproj/argo-workflows/assets/50765823/1d5b46b4-ddb7-4458-be7a-0d9b19811d91">
