### ISSUE TITLE
Rate-limiting pod creation

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#4888]
Creating 1000s of pods floods and overloads Kubernetes. We should be able to control the rate at which we create resources (and therefore pods).

**Comment by alexec** [comment]
You can use parallelism to limit the number of running pods, which could achieve the same effect.

That has limitations:

* Doesn't allow you to run all the pods.
* Only controller per workflow, not per namespace or cluster.

**Comment by deepk2u** [comment]
@alexec We want to rate-limit the number of pods created so that there is less load on the underlying k8s cluster.

for example, if the parallelism is set to 1000, it should execute 50 pods in one go and then 50 next time.

**Comment by tooptoop4** [comment]
did u solve @deepk2u ?
