### ISSUE TITLE
UI: Conditionally Hide Cluster Workflow Template when running --namespaced

### ISSUE THREAD

**Issue by igaskin** [argoproj/argo-workflows#4891]
# Summary

By design the argo-server is able to run within the scope of a single namespace.  Although the api server starts successfully, the UI still displays the Cluster Workflow Templates Icon when the server is running with the `--namespaced` flag, which will permanently display an error.  This tab should be conditionally hidden or shown based on the scope the argo-server is running in.

![Screen Shot 2021-01-15 at 12 14 27 PM](https://user-images.githubusercontent.com/5673097/104774486-9df19e80-572b-11eb-8e80-a936356669a8.png)

# Use Cases

When running argo workflows in a multi-tenant kubernetes cluster

Related Issue:
https://github.com/argoproj/argo/issues/2664
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tczhao** [comment]
fixed in #5729
