### ISSUE TITLE
[UI] heeboo.css not loaded on Safari

### ISSUE THREAD

**Issue by TaylorHere** [argoproj/argo-workflows#4899]
## Summary 
heeboo.css not loaded on Safari
that makes UI looks ugly
` Did not parse stylesheet at 'http://xxxxx.com/assets/styles/heebo.css' because non CSS MIME types are not allowed in strict mode. `

## Diagnostics

Alilibaba Cloud

2.14.4

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
See #4739 and #4730 .

Please try `argoproj/argocli:latest`
