### ISSUE TITLE
Argo not Update task status immediately and lead to pod deleted

### ISSUE THREAD

**Issue by fredkan** [argoproj/argo-workflows#4928]
## Summary 
When task got the terminating signal, argo does not update node status immediately.

Argo waits about 2minutes to update node status which make the dependency confusion；

Issue: When the above situation happens，the terminated task is recreated and the dependency task is also starting.

```
2021-01-16T13:11:20.206674118Z	time="2021-01-16T13:11:20Z" level=info msg="Updating node node1(0) (pod-68-2320995120) status Running -> Succeeded"
2021-01-16T13:09:33.453177377Z	shutting down, got signal: Terminated
```

**Comment by fredkan** [comment]
@xianlubird  any comments?

**Comment by alexec** [comment]
Can you please add reproduction steps?

**Comment by fredkan** [comment]
unfortunatly, it is hard to reproduce.
we submit hundreds of tasks, and sometimes meet one case.

**Comment by alexec** [comment]
I’ve also noticed this. Unreliable. Will investigate.
