### ISSUE TITLE
Support filtering workflows by status

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-workflows#496]
Kubernetes allows to filter CRD only by labels, so currently it is impossible to filter workflows by status. In order to support filtering workflow CRD controller could set 'status' label for each workflow and update it when workflow status changes.

**Comment by jessesuen** [comment]
Commit bfa62af adds a label `phase` to the workflow label, which can be used by CLI to filter by phase. Phase will be one of: `Running`, `Succeeded`, `Failed`, `Error`
