### ISSUE TITLE
Metrics are missing

### ISSUE THREAD

**Issue by tomgoren** [argoproj/argo-workflows#4965]
## Summary 

The team implemented some great new metrics but they were not included in the latest releases.

e.g.: https://github.com/argoproj/argo/commit/45c792a59052db20da74713b29bdcd1145fc6748 not in v2.12.6

See: https://github.com/argoproj/argo/tree/v2.12.6/workflow/metrics vs. https://github.com/argoproj/argo/tree/45c792a59052db20da74713b29bdcd1145fc6748/workflow/metrics

Thanks!
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
@alexec Should we back port this?

**Comment by alexec** [comment]
It's quite a big change. @tomgoren thanks for all your help on this in December. Is there a particular metric you're after? It might be easy to cherry-pick one selectively

**Comment by tomgoren** [comment]
Nothing urgent! I think they would each be informative in their own way. `k8s_request_total` would probably be the most useful at the moment, seeing as in EKS information about the control plane is limited.

That said, I think this is only a "bug" so long as [the docs](https://github.com/argoproj/argo/blob/master/docs/metrics.md#default-controller-metrics) include info about metrics that aren't yet available (and also it would a bummer if they were forgotten about!).

Thank you!

**Comment by alexec** [comment]
I think this is backported to v2.12 today by @simster7

**Comment by tomgoren** [comment]
I saw a metrics related patch introduced in 2.12.7, but not https://github.com/argoproj/argo/commit/45c792a59052db20da74713b29bdcd1145fc6748. Thank you!

**Comment by alexec** [comment]
Looks like #4751 (#4952) was but not #4811.

**Comment by alexec** [comment]
@simster7 if we do v2.11.8 then we should add #4811.

**Comment by tomgoren** [comment]
I think that for us this is no longer relevant as we've been on latest/3 based releases for a while. Feel free to close @alexec
