### ISSUE TITLE
UI: Two identical filter buttons that do different things

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-workflows#4969]
## Summary 

What happened/what you expected to happen?

There are two adjacent filter widgets.

1. Visit https://workflows.apps.argoproj.io/event-flow/argo?showWorkflows=true&expanded=true
![image](https://user-images.githubusercontent.com/2119212/106249301-32eea000-61e0-11eb-8537-8cb1dc52bd33.png)

## Expected results

* either use different icons or merge the functionality (as done in argo-cd)
* Don't label something `-`, it's really unhelpful

## Diagnostics

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
@alexec I have a foggy memory, did we agree to revert this to the merged filter? One with both NodeStatus and NodeType?

**Comment by alexec** [comment]
I think we talked about how this wasn't a great usability and it might be nice to have a single filter widget, so I think we all agree.

I'd think we should have a single button and it opens a much larger and easier to use set of boxes.

And `-` is weird.

@simster7 do you want to own, or shall I?

**Comment by simster7** [comment]
@alexec I'll own. I had already made this change, not sure why it didn't make it

**Comment by alexec** [comment]
Make it big and easy to use please!
