### ISSUE TITLE
horizontal/vertical buttons have different dimensions and are a poor UX

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-workflows#4973]
## Summary 

What happened/what you expected to happen?

## Steps

1. visit https://workflows.apps.argoproj.io/workflows/argo/coinflip-1611945900?tab=workflow
2. click the ➡️  or ⬇️  (repeatedly)

https://user-images.githubusercontent.com/2119212/106315567-690c3e00-6239-11eb-9233-ec5e9fa00e54.mov

Expected results: As with the bug about yaml/json, don't use a button like this. Two buttons side by side that show depressed state would probably be better (just like the argocd views).

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by jsoref** [comment]
I do not like bots

**Comment by alexec** [comment]
That does look odd, but I think it is annoyance.

**Comment by jsoref** [comment]
Helpwanted

**Comment by jsoref** [comment]
I don't like 🤖
