### ISSUE TITLE
showWorkflows Buttons / text aren't aligned

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-workflows#4975]
## Summary 

What happened/what you expected to happen?

https://workflows.apps.argoproj.io/event-flow/argo?showWorkflows=true&selectedNode=argo/Sensor/log&tab=events

https://user-images.githubusercontent.com/2119212/106316570-f8662100-623a-11eb-8efa-faf81e15b462.mov

## Diagnostics

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
thank you - @jsoref - would you like to submit a PR to help fix some of these issues?

**Comment by jsoref** [comment]
I think for the time being I'm going to skip the UI items I've filed recently. I'm going to work on some of the CI items. If no one picks them up, I might circle back in the summer.

**Comment by jsoref** [comment]
Not a fan of the bot.

**Comment by jsoref** [comment]
Help wanted

**Comment by jsoref** [comment]
I don't like 🤖

**Comment by JacobCarrell** [comment]
Do you have an issue with the buttons not having padding between them as well? Or is that the norm for this application?

**Comment by jsoref** [comment]
I'd expect padding between the buttons, yes.
