### ISSUE TITLE
When linting workflows any other manifest type fails the lint instead of being ignored

### ISSUE THREAD

**Issue by rkrmr33** [argoproj/argo-workflows#4981]
## Summary 

What happened/what you expected to happen?

When I use the argo cli command: `argo lint ./my-manifests` I expected it to ignore other manifest types (workflow-templates, cron-workflow, etc...), because it says in the log: 
```
...
WARN[2021-01-31T08:54:56.071Z] WorkflowTemplate 'workflow-template1' is not of kind Workflow. Ignoring...
...
```

But instead of ignoring the workflow-template it then outputs:
```
ERRO[2021-01-31T08:54:56.071Z] Error in file /workspaces/playground/argo/manifests/workflow-template.yaml: there was nothing to validate 
FATA[2021-01-31T08:54:56.071Z] Errors encountered in validation
```
What version of Argo Workflows are you running? 
v2.12.6

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
would you like to submit a PR to fix?

**Comment by arckey** [comment]
@alexec I'll be happy to continue from where you left off with: https://github.com/argoproj/argo/pull/3734/files, if that's ok :)

**Comment by alexec** [comment]
please go for it!
