### ISSUE TITLE
Default annotations for workflow pods

### ISSUE THREAD

**Issue by dylanhellems** [argoproj/argo-workflows#4985]
# Summary

It would be useful to have the ability to set default annotations for all pods in a workflow via the default workflow spec. Perhaps pods in a workflow could inherit the annotations on the workflow itself? Or another configuration option could be added for this purpose.

# Use Cases

We use kube2iam for AWS access which includes our s3 artifact repository. Unless I'm missing something, it seems like every template needs to have an annotation individually applied to it so that it can archive logs. I'd like to be able to apply a default annotation to all workflow pods via the default workflow spec, which would save every workflow definitions from needing to know about that role.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
would you like to submit a PR to add this feature?

**Comment by dylanhellems** [comment]
I can look into it when I have time; it's really more of a nice to have than a necessity.

**Comment by dylanhellems** [comment]
PR up: https://github.com/argoproj/argo/pull/5031
