### ISSUE TITLE
CronWorkflowServiceApi#create_cron_workflow returns malformed CronWorkflowStatus

### ISSUE THREAD

**Issue by xenteros** [argoproj/argo-workflows#5018]
## Summary 

When I create CronWorkflow with a client generated based on swagger.json I receive a response which isn't compliant to the OpenAPI spec.

The response contains CronWorkflowStatus which has 3 mandatory fields but they are nulls.

## Diagnostics

What Kubernetes provider are you using? 
AWS EKS
What version of Argo Workflows are you running? 
2.12.6

## Possible solution

Remove status from the response of CreateCronWorkflow endpoint. I don't really understand why would it make sense to attach it there as there can't be any active jobs yet nor lastScheduledTime.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Can you please include a sample response?
