### ISSUE TITLE
Support for multi lock or semaphores

### ISSUE THREAD

**Issue by rmgpinto** [argoproj/argo-workflows#5022]
# Summary

Support for multi lock or semaphores

# Use Cases

We have a case where we have multiple data pipelines pulling from  different data sources and a pipeline compiling data models at the end.
Some of these pipelines can run different strategies (full at 1 am, incremental pulls every 10 mins or they can be triggered on-demand). Let's call them `A` and `B`.
Let's call the other pipeline `C`.

To avoid full and incremental to run a the same time, we could have a semaphore `A` with value 1 and avoid pipelines of type A to run simultaneously. The same can be applied for `B`.
However, to avoid running `C` while `A` or `B` are running, we need support for two concurrent semaphores: `A` and `B` with value 1.

The above could also be achieved with support for multiple locks.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by macpoint** [comment]
Has this been already implemented?

**Comment by tooptoop4** [comment]
@rmgpinto how did u solve?

**Comment by tooptoop4** [comment]
@rmgpinto why did u close this? its still an issue

**Comment by agilgur5** [comment]
Re-opening as this is quite popular with a few related issues and discussions (such as #9382, #11859, etc)

**Comment by agilgur5** [comment]
I ended up looking into this as part of https://github.com/argoproj/argo-workflows/issues/11859#issuecomment-1742249506 and don't think it would be that hard to support multi-semaphore, so assigned to myself for now
