### ISSUE TITLE
Share checksum for each release archive

### ISSUE THREAD

**Issue by poltro90** [argoproj/argo-workflows#5034]
# Summary

Since the official way to install an Argo release is done by downloading, extracting, and executing an archive downloaded from GitHub, it'd be useful to include the archive checksum for each platform, so to be able to verify integrity before extracting and executing the install.

# Use Cases

This is useful on the first install of Argo on each personal or remote machine, but also within automation when spinning up brand new environments: in order to guarantee the correctness of the environment, and make sure it has not been tampered, you want to check all the installed packages (Argo included) for correctness.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Would this just be sha256sum of the binaries?

**Comment by simster7** [comment]
I can add this to the release process

**Comment by alexec** [comment]
This should probably be similar to the brew  formula.
