### ISSUE TITLE
Slack invite link is broken again

### ISSUE THREAD

**Issue by rory-lamendola** [argoproj/argo-workflows#5044]
## Summary 

When using the:
1. slack invite link in the readme
2. submitting an issue -> chat on slack

I get an Invitation expired error.
![image](https://user-images.githubusercontent.com/29575390/107241280-13c5ee80-69e8-11eb-95ca-d521fa74f1ef.png)

I see this has been an ongoing [issue](https://github.com/argoproj/argo/issues/3711)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Will update the link

**Comment by simster7** [comment]
@rory-lamendola The link is working as-is for me (I used `https://argoproj.github.io/community/join-slack`): 
<img width="562" alt="image" src="https://user-images.githubusercontent.com/614838/107251606-5fc56300-69e9-11eb-8dc3-3823bdad4517.png">

What link did you use?

**Comment by rory-lamendola** [comment]
it's working now, was the same link though.  weird.  thank you!

**Comment by lowc1012** [comment]
Hi, this link is no longer active.  https://argoproj.github.io/community/join-slack
Someone can invite me with a new link?
Thanks!

**Comment by alexec** [comment]
@alexmt maybe this link could last longer?

**Comment by simster7** [comment]
Cronjob to update?

**Comment by alexmt** [comment]
Link is updated. For some reason, slack no longer allow shared links that last longer than 1 month

**Comment by alexec** [comment]
thank you!
