### ISSUE TITLE
Termination grace period is multiplied by time.Second erronously

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5046]
```
err = WaitForTermination(ctx, c, containerID, terminationGracePeriodDuration*time.Second)
```

@tczhao

**Comment by tczhao** [comment]
Sorry, I don't understand what the issue is. Do you mean that the terminationGracePeriodDuration should embed the time.Second information
Could you point me in the right direction?

**Comment by tczhao** [comment]
It is working like this at the moment
```
seconds := 10 // from godoc time example
fmt.Print(time.Duration(seconds)*time.Second) // prints 10s
```

```
terminationGracePeriodDuration := time.Duration(int64 terminationGracePeriodSecond)
terminationGracePeriodDuration * time.second
```

The terminationGracePeriodDuration is a multiplier factor
(A Duration represents the elapsed time between two instants as an int64 nanosecond count)

I think we are using it correctly

**Comment by alexec** [comment]
What about my example?

```
terminationGracePeriodDuration:=10*time.Second

println(terminationGracePeriodDuration*time.Second)
```

**Comment by alexec** [comment]
Should terminationGracePeriodDuration be `int` not `time.Second`

**Comment by tczhao** [comment]
Yes, your example does produce a very big number

but in our case, we are casting it using time.Duration instead of time.Second

```
// GetTerminationGracePeriodDuration returns the terminationGracePeriodSeconds of podSpec in Time.Duration format
func (we *WorkflowExecutor) GetTerminationGracePeriodDuration(ctx context.Context) (time.Duration, error) {
	pod, err := we.getPod(ctx)
	if err != nil {
		return time.Duration(0), err
	}
	terminationGracePeriodDuration := time.Duration(*pod.Spec.TerminationGracePeriodSeconds)
	return terminationGracePeriodDuration, nil
}
```
*pod.Spec.TerminationGracePeriodSeconds is int64

**Comment by alexec** [comment]
To be clear, `time.Second` is specifically defined as ` 1000 * Millisecond`.

It NEVER makes sense to multiple `time.Duration` by `time.Second`

This is the fix to the code:

```golang
terminationGracePeriodDuration := *pod.Spec.TerminationGracePeriodSeconds * time.Second
```

**Comment by tczhao** [comment]
ok, I get your points now.
This definitely makes more sense
