### ISSUE TITLE
Stop & Terminate not working on recursive workflow 

### ISSUE THREAD

**Issue by Smeuh** [argoproj/argo-workflows#5052]
Hello,

The stop and Terminate do not work on a recursive workflow, even with the demo recursion coinflip.

## Summary 

What happened/what you expected to happen?

I launched the coinflip workflow, waited until the first flip was done and then clicked on "stop" or "terminate".

What happened => the workflow finished as normal.
What I expected => the workflow stop with the stop or terminate message.

## Diagnostics

What Kubernetes provider are you using? 
Bare Metal
What version of Argo Workflows are you running? 
V2.12.8

The workflow that reproduce the issue is the coinflip recursion available here : https://argoproj.github.io/argo/examples/#recursion

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Will take a look

**Comment by simster7** [comment]
So the workflow does eventually end, but it takes a while because we still allow pod creation. I opened a PR to fix this

**Comment by Smeuh** [comment]
Ok thank you for your quick answer.
