### ISSUE TITLE
Token-Refresh not implemented in argo-server?

### ISSUE THREAD

**Issue by boehb-efs** [argoproj/argo-workflows#5053]
## Summary 

In a sso-environment the token is not refreshed (especially irksome, when one tries to define an extensive Workflow).

Instead of refreshing the token after expiration, one runs into an Unauthorized-Error and is redirected to the login-page...

## Diagnostics

Kubernetes-Environment: Azure Kubernetes Service, Kubernetes-Version: 1.15.10
Argo-Version: 2.11.7 (via helm) with --auth-mode=sso

Logs from argo-server via:
```
kubectl logs -n argo $(kubectl get pods -l app=argo-server -n argo -o name) --tail 50 | grep expired
```

Output:
```
time="2021-02-09T13:01:41Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = failed to verify id_token oidc: token is expired (Token Expiry: 2021-02-09 12:57:07 +0000 UTC)" grpc.code=Unauthenticated grpc.method=GetVersion grpc.service=info.InfoService grpc.start_time="2021-02-09T13:01:41Z" grpc.time_ms=0.19 span.kind=server system=grpc
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
How often are you asked to log back in?

**Comment by boehb-efs** [comment]
Our jwt-Token is valid for 15 minutes, extending the expiration-time is not really an option I would like to take...

**Comment by alexec** [comment]
In v2.12, when we log you in, we issue you your own JWE. That change came in f7e85f04b11fd65e45b9408d5413be3bbb95e5cb:

   feat(server): Make Argo Server issue own JWE for SSO. Fixes #4027 & #3873 (#4095)

That JWE has an expiry time of 10h.

You should not be logged out for 10h. Are you logged out before that?

**Comment by boehb-efs** [comment]
Upgrading my local installation to 2.12.5 seems to do the trick. Works like a charm :-)

**Comment by thesuperzapper** [comment]
@alexec I think the current approach is not optimal, and we can make it better by supporting refresh tokens (even while using our JWT).

1. Right now, argo-server is unaware of a user having their access revoked until after their session expires (which is a big security risk), refresh tokens prevent this by allowing us to set shorter token lifetimes and simply extend them as the user remains active.
2. Right now, users are forced to re-auth at least once every `sessionExpiry`, which is unessesaray as we can transparently re-verify their access (as long as the OIDC provider supports refresh tokens) in near perpetuity 

__If you want to read more about how refresh tokens work in OIDC, here are some materials:__
- https://oauth.net/2/grant-types/refresh-token/
    - https://www.rfc-editor.org/rfc/rfc6749#section-1.5
    - https://www.oauth.com/oauth2-servers/access-tokens/refreshing-access-tokens/
    - https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/
- You can also look at the app [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) which already supports token refreshing
