### ISSUE TITLE
Leaving the workflow UI opened in a tab drains a lot of cpu (google chrome)

### ISSUE THREAD

**Issue by therealarty** [argoproj/argo-workflows#5064]
## Summary 

Whenever I leave a google chrome tab opened with an argo-workflow opened, it ends up using a LOT of CPU (even if I don't interact with it).
I used the chrome task manager to ensure it is the argo-workflow page and inspected the UI. It seems there are regularly new rasterizers...

## Diagnostics

What Kubernetes provider are you using? 
We are running Argo on AWS EKS

What version of Argo Workflows are you running? 
argo: 2.8.2+8a151ae.dirty

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
> 2.8.2+8a151ae.dirty

We made a TON of UI performance improvements since 2.8.2. Try upgrading?

**Comment by therealarty** [comment]
I'll let you know !
