### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by khaled** [argoproj/argo-workflows#5068]
## Summary 

What happened/what you expected to happen?

The "Docs" link at https://argoproj.github.io/projects/argo is broken - it should be taking you to https://argoproj.github.io/argo-workflows/

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@alexmt did you manage to fix this please?

**Comment by simster7** [comment]
https://github.com/argoproj/argo-site/pull/43

**Comment by simster7** [comment]
Please approve @alexec

**Comment by agilgur5** [comment]
Broken link was fixed in https://github.com/argoproj/argo-site/pull/42.
No redirect was added from the old link though, which just 404s now
