### ISSUE TITLE
"Learn more" links in UI broken

### ISSUE THREAD

**Issue by austinpray-mixpanel** [argoproj/argo-workflows#5071]
## Summary 

In the single workflow view I noticed some broken links:

- https://argoproj.github.io/argo/workflow-pod-security-context/
- https://argoproj.github.io/argo/cost-optimisation/

![image](https://user-images.githubusercontent.com/71290498/107560169-a3af9800-6ba2-11eb-830b-844506ef2364.png)

This is related to the repo migration afaik. using https://argoproj.github.io/argo-workflows/cost-optimisation/

Similar issue as https://github.com/argoproj/argo-workflows/issues/5068

It's probably worth setting up redirects so people running previous versions get to the right place without having to update.

## Diagnostics

What version of Argo Workflows are you running? 

2.12.8

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Should be fixed by #5070

**Comment by simster7** [comment]
Merged
