### ISSUE TITLE
UI namespace filter state is sticky between reports and workflows view

### ISSUE THREAD

**Issue by austinpray-mixpanel** [argoproj/argo-workflows#5075]
## Summary 

1. Enter a namespace into the namespace filter on reports page
2. Clear it out with the "x" button

Expected: the namespace is cleared out.
Actual: the namespace sticks around and persists across reports view and workflows view

https://user-images.githubusercontent.com/71290498/107568794-1c1b5680-6bad-11eb-8ccf-bcaef2e4cbf2.mp4

## Diagnostics

What Kubernetes provider are you using? GKE

What version of Argo Workflows are you running? 2.12.8

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by austinpray-mixpanel** [comment]
Related: clicking the workflows link in the side nav restores the namespace filter

https://user-images.githubusercontent.com/71290498/107571568-b0d38380-6bb0-11eb-892b-ec45559d1b08.mov

**Comment by alexec** [comment]
can you try v3.0.0-rc1?

**Comment by chrisjwhiteley** [comment]
I am also impacted by this. Will try latest v3.0.0-rc3 to see if it fixes the issue.

**Comment by tszngai** [comment]
Also affected by this. And v3.0.0-rc1 is not supported by helm install yet

**Comment by alexec** [comment]
I think it is the case that the code for no workspace set (i.e. show all clusters) gets confused with undefined workspace. Would anyone like to investigate this?

**Comment by alexec** [comment]
Would anyone like to submit a PR to fix this?

**Comment by tczhao** [comment]
Did some tests on 2.12.5, 3.0.0, 3.1.1 and master, 
This is fixed since version 3.0
