### ISSUE TITLE
Notification boxes are hidden by page toolbar

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-workflows#51]
Steps to reproduce:

1. Navigate to timeline -> commits and launch any job

Expected result:

Notification message should be shown

Actual result:

Notification box is hidden by page toolbar

**Comment by wokeGit** [comment]
Notification looks bad, boxes doesn't fit after redesign.
![screen shot 2017-08-28 at 13 37 00](https://user-images.githubusercontent.com/13086525/29771836-135124fc-8bf6-11e7-804d-9d030deeda57.png)
@rahuldhide please propose new designs for notification boxes.

**Comment by wokeGit** [comment]
Will be done after merge: https://github.com/argoproj/argo/pull/82
