### ISSUE TITLE
Managed Namespace installation

### ISSUE THREAD

**Issue by dzirg44** [argoproj/argo-workflows#5107]
## Summary 
Hi!
I installed  `argo-workflows` and noticed that i have to setup 2 almost similar roles one for installation namespace , second for target namespace. I think maybe it will be better if we have separated roles?
```yaml
{
          name    = "workflow-controller"
          image   = "argoproj/workflow-controller:v2.12.8"
          command = ["workflow-controller"]
          args = [
            "--configmap",
            "workflow-controller-configmap",
            "--executor-image",
            "argoproj/argoexec:v2.12.8",
            "--namespaced",
            "--managed-namespace",
            "gitops"
          ]
}
```
when I run workflow with this configuration I expect that I have to give a role with 
```yaml
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
```
and nothing more
but in my logs i have a message like
```
workflows.argoproj.io is forbidden: User "system:serviceaccount:argo-workflow:argo" cannot list resource "workflows" in API group "argoproj.io" in the namespace "argo-workflow"
```
which means that I still have to give permissions to the installation namespace
## Diagnostics

What Kubernetes provider are you using? - aws eks 1.18

What version of Argo Workflows are you running? - latest release v2.12.8

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This looks like standard Kubernetes RBAC, nothing Argo specific, but maybe check:

* You have a service account in each namespace.
* You have a role in each namespace.
* You have a role binding in each namespace.
* You've configured the service account correctly.

You can also use `kubect auth can-i` to test this.

**Comment by dzirg44** [comment]
thank you for the response. Now I am trying to create a really isolated environment, it will take maybe one week and will write about my experience.

**Comment by alexec** [comment]
Awesome, are you going to write a blog post? We could re-post it?

**Comment by dzirg44** [comment]
Yes, sure. I will inform you. I can write here or to the slack channel.

**Comment by weisjohn** [comment]
> Yes, sure. I will inform you. I can write here or to the slack channel.

Anything ever materialize here?

**Comment by dzirg44** [comment]
@weisjohn  yes, I didn't forget about it. Now we are testing.
