### ISSUE TITLE
Handle idle timeouts more gracefully

### ISSUE THREAD

**Issue by pires** [argoproj/argo-workflows#5124]
## Summary 

Refs #4524 (closed issue without a supposed fix that never landed?) cc @dcherman 

>When you're using an ingress controller that has an idle timeout configured, it's possible that there are no events that occur within that period of time which results in the UI throwing an error since the workflow-events stream is closed. In the case of my cluster, I use ingress-nginx which has a default idle timeout of 60s.
>
>Since it's expected that these streams are very long lived connections, we should consider one of the following:
>
>Send a piece of data periodically if none has been sent. This is not optimal imo since we'd need to filter this out on the client, and it still may not solve the problem if the user configures an idle timeout shorter than the interval that we sent data.
>
>Retry the connection on the front-end at least once. If the connection is successfully re-established, then it's a candidate to retry again if/when the error occurs. If the connection fails to be re-established, throw our existing error since that might indicate a loss of network connectivity or problems with the argo-server pod.
>
>In both cases, we should also provide a nicer way to retry when this occurs rather than reloading the page.

## Diagnostics

What Kubernetes provider are you using?

Private, Kubernetes 1.19

What version of Argo Workflows are you running? 

v3.0.0-rc1 but also verified on 2.12.8.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by pires** [comment]
This bug is not a blocker but truly annoying as things that are working and showing progress disappear from the screen for ~10s, show up and disappear again, rinse and repeat.

**Comment by alexec** [comment]
I think @dcherman is fixing this as we speak.

**Comment by pires** [comment]
Cool! Is it still expected to land on v3.0.0?

**Comment by alexec** [comment]
I hope so.

**Comment by dcherman** [comment]
This should be fixed in master, forgot to add a ref to this issue in the commit.

https://github.com/argoproj/argo-workflows/pull/5101
