### ISSUE TITLE
Argo-workflows or argo-cd should change its project name

### ISSUE THREAD

**Issue by sylock** [argoproj/argo-workflows#5127]
# Summary

I understand the huge refactoring it would need and I guess there is little chance that this idea could be implemented, but in regards of the long term project emancipation, I think it would be the best to do.

argo-workflows and argo-cd are two separated applications though they share things. When searching for "argo" on search engines results are a mix of both argo-workflows and argo-cd and it makes things difficult for newcomers to find its way. Even later, when you need to find some piece of information, you always get ambiguous results.
When you have both argo-cd and argo-workflows installed on a same kubernetes cluster you get ambigous objects : you have a mix of argo objects instanciated, some related to argo-cd, some related to argo-workflows.
It is also about identity : when I talk about argo at work, most of people know argo-cd but are not aware of argo-workflows and it creates a lot of ambiguities in the talks. My talk must always start by a disambiguation introduction.

Things would be much more clear if the 2 projects were more differentiated and would get a strong separated identity:
* different name for the products
* different blog for both of them

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Not fixable.
