### ISSUE TITLE
Look into tests failing when using exec spec

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5130]
@simster7 @sarabala1979 this change has produced some unexpected test failures. Key to the change, is we use ExecSpec for ALL workflows, not just when needed.

So I believe we have bugs in these areas when using exec spec (e.g. templates):

* `TestRealtimeWorkflowMetricWithGlobalParameters` and related test failures points at `metrics and custom metrics
* `TestResourceTemplateStopAndTerminate` and `TestWorkflowRetry ` points at stopping and terminating workflows

@simster7 and @sarabala1979 - would you want to look into these yourselves?

_Originally posted by @alexec in https://github.com/argoproj/argo-workflows/issues/5112#issuecomment-780079601_

**Comment by sarabala1979** [comment]
I tried multiple times locally. couldn't reproduce. I will go through the code the see any corner case.

**Comment by alexec** [comment]
Don't invest too much time until users are reporting issues.
