### ISSUE TITLE
Confusing expression and templating system

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5142]
Argo Workflows uses multiple templating and expression languages:

Templating syntax:

* `fasttemplate` is used when converting a template into an executable template. E.g. to expand parameters: `{{inputs.parameters.foo}}`

Expression syntax:

* `govaluate` is used for `when`: only - this project appears to be abandoned: e.g. 'when: {{tasks.A.status}} != Succeeded'
* `expr` is used event expressions and `depends`: e.g. `depends: should-execute-2.Succeeded || should-not-execute`

I think we'll want to introduce some 1st-class scripting support. 

Golang libraries seem to have a habit of getting abandoned. 

We're very inconsistent with the expression environment we use for evaluation.

What to do about this?

**Comment by agilgur5** [comment]
See #9529 and #7831 for current plans on templating standardization
