### ISSUE TITLE
Archive logs for sidecar containers

### ISSUE THREAD

**Issue by dseapy** [argoproj/argo-workflows#5152]
# Summary

Main container logs are archived, but sidecar container logs are often needed for debugging.  Having the wait container store sidecar logs on s3 as well and downloadable through UI would be helpful.

# Use Cases

It is common for pods in our workflows to have grpc server sidecars that the main container calls out to for help when processing files on disk using mirrored volume mounts.  For times when these grpc servers throw an error, having the logs available would be helpful.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Would you like to submit a PR for this?

**Comment by dseapy** [comment]
Thought you might ask :)  As soon as I find a bit of time I will be happy to, yes.  Hopefully in the next few weeks.

**Comment by khobbs-ccri** [comment]
I'll add myself as an interested party to this one.
