### ISSUE TITLE
unknown time zone

### ISSUE THREAD

**Issue by bryanisgreat** [argoproj/argo-workflows#5181]
## Summary 

v3.0.0-rc2 regresssion from this https://github.com/argoproj/argo-workflows/pull/5057 causing LoadLocation to not find timezone by name.  

This issue is **not** present in v3.0.0-rc1

## Diagnostics

EKS 1.17

v3.0.0-rc2

```
time="2021-02-23T18:17:17.550Z" level=error msg="could not run outstanding Workflow" cronWorkflow=prod/foobar error="invalid timezone 'America/Los_Angeles': unknown time zone America/Los_Angeles"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
that's odd:

```
COPY --from=workflow-controller-build /usr/share/zoneinfo /usr/share/
```

I wonder what happenid.

**Comment by bryanisgreat** [comment]
yeah, seems like that should work...  It's possible that is not the cause, but it is quite suspect since it's behaving like the zoneinfo is missing.

**Comment by alexec** [comment]
https://stackoverflow.com/questions/59094236/error-unknown-time-zone-america-los-angeles-in-time-loadlocation
