### ISSUE TITLE
UI: Back / History Behavior is broken in Workflow Details View

### ISSUE THREAD

**Issue by dcherman** [argoproj/argo-workflows#5186]
## Summary 

When navigating in the UI, the back button should always bring you back to (and render) the previous URL.  This seems to be broken in several cases.

## Diagnostics

- Go to https://workflows.apps.argoproj.io/
- Click on any workflow
- Click the `logs` button
- Click the `back` button on your browser
- Note that the URL has changed, but the state of the app is now wrong

I noticed the same thing happen when looking at the different panes for an individual node, or the different representations of a Workflow that you can click on in the top right

![image](https://user-images.githubusercontent.com/976608/108947191-fa4eb480-762d-11eb-9290-598d1ea8ca0b.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Taking a look

**Comment by simster7** [comment]
Found problem, working on fix
