### ISSUE TITLE
Workflows page workflow checkbox cannot multi-select 

### ISSUE THREAD

**Issue by process0** [argoproj/argo-workflows#5210]
## Summary 

On the workflows page, when attempting to click the checkbox next to each workflow to perform a multi operation, clicking the checkbox will redirect to the specific workflow of the checkbox.

![image](https://user-images.githubusercontent.com/29227206/109201188-87e5ed80-776f-11eb-8aad-a67520356b97.png)

## Diagnostics

Running Argo v3.0.0-rc3, Firefox 78.8.0esr

**Comment by alexec** [comment]
@simster7 ?

**Comment by simster7** [comment]
Odd... working on a fix

**Comment by alexec** [comment]
maybe something with event bubbling?
