### ISSUE TITLE
Argo dag failFast option not working Argo version: 2.12.3

### ISSUE THREAD

**Issue by swathi59** [argoproj/argo-workflows#5223]
Argo dag failFast option not working
Argo version: **2.12.3** 

**Steps to Reproduce**
Execute following example: https://github.com/argoproj/argo-workflows/blob/master/examples/dag-disable-failFast.yaml
Set failFast to true.

**Actual Behaviour**
All steps in the pipeline are scheduled and executed even though one step failed.
**Expected Behaviour**
If one of the steps in the pipeline fails other steps should not be scheduled, only the ones which are currently running should be finished.
![1](https://user-images.githubusercontent.com/16645741/109296465-5562f000-7856-11eb-90ca-7f3dac5799e0.png)
![2](https://user-images.githubusercontent.com/16645741/109296469-572cb380-7856-11eb-937f-72a3d8bafc97.png)

**Comment by simster7** [comment]
> Argo version: 2.12.3

The UI from your screenshot is not the one from v2.12. Are you still using `argo-ui`? If so, that has been deprecated. Please see the getting started to use the new UI.

I'll take a look at `failFast` meanwhile.

**Comment by simster7** [comment]
I was able to reproduce... looking into it

**Comment by swathi59** [comment]
Thank you Simon

**Comment by simster7** [comment]
See #5398 for further discussion
