### ISSUE TITLE
Support profiles from AWS shared credentials file for artifacts

### ISSUE THREAD

**Issue by rpledger** [argoproj/argo-workflows#5229]
# Summary
Add ability to specify non-default AWS credentials profile in a shared credentials file for s3 artifacts. Add a field to [S3ClientOptions](https://github.com/argoproj/pkg/blob/master/s3/s3.go#L48) and the s3 [ArtifactDriver](https://github.com/argoproj/argo-workflows/blob/master/workflow/artifacts/s3/s3.go#L21) to specify a profile name. Use this name to specify the profile to load for the AWS session's config.

# Use Cases
IAM roles cannot be used to delegate access between an AWS GovCloud (US) account and a standard AWS account. To support artifacts from multiple buckets in which IAM roles cannot be used for access, instead use profiles from a shared credentials file to specify multiple accessKey/secret credentials.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
I think if you set this to true https://github.com/argoproj/argo-workflows/blob/master/docs/workflow-controller-configmap.yaml#L105 it should then use the aws sdk's default provider chain which would pick any auth method in the order the aws sdk defines which would also then allow you to use the AWS_PROFILE env var to set the profile from the shared config file.

**Comment by zachaller** [comment]
With that set to true the order of provider chain should follow this https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-precedence and any ENV the SDK supports the workflow would support.

**Comment by rpledger** [comment]
Thanks @zachaller ! Where would the `AWS_PROFILE` env var be set? In a specific pod? Or maybe that step's `container.env`? The reason I'm asking is because in our scenario, the profile could be different each time based on an argo param from a previous step.

**Comment by zachaller** [comment]
I think you could try podSpecPatch within the executor sidecar container https://github.com/argoproj/argo-workflows/blob/9319c074e742c5d9cb97d6c5bbbf076afe886f76/examples/pod-spec-patch.yaml#L13

**Comment by rpledger** [comment]
Ah cool, I'll try that out. Thanks @zachaller

**Comment by rpledger** [comment]
Tried this out and got it working today!

Here's what I did to get this working:
1. Set `useSDKCreds: true` for the s3 input artifact
2. Mounted the shared credentials file as a secret, for example at `/s3Creds/credentials`
3. Used `podSpecPatch` to set `AWS_PROFILE` and `AWS_SHARED_CREDENTIALS_FILE` as ENVs in the init container

```
podSpecPatch: '{"initContainers":[{"name":"init", "env":[{"name": "AWS_SHARED_CREDENTIALS_FILE", "value": "/mainctrfs/s3Creds/credentials", "valueFrom": null}, {"name": "AWS_PROFILE", "value": "<profile-name>", "valueFrom": null}]}]}'
```

Thanks @zachaller !

**Comment by zachaller** [comment]
Awesome nice to see that it worked. I thought the theory was sound but thank you for reporting back that in practice it dose work.

**Comment by rpledger** [comment]
No longer needed due to work around with podSpecPatch
