### ISSUE TITLE
Error message on bad flags chops off a character

### ISSUE THREAD

**Issue by max-sixty** [argoproj/argo-workflows#5241]
## Summary 

Narrow but hopefully still helpful (feel free to close if not)

With a typo in this command:
```
argo submit -log workflows/test.yaml
```

The error message refers to `og`, and `NAME1=VALUE2`:

```
FATA[2021-02-27T17:01:02.736Z] expected labels of the form: NAME1=VALUE2,NAME2=VALUE2. Received: og: unexpected label spec: og
```

This had me searching in my workflow file for `og` strings!

If this is because of a command-line plugin, also feel free to close

## Diagnostics

What version of Argo Workflows are you running? 

```
argo: latest+7379053.dirty
  BuildDate: 2021-02-17T02:30:14Z
  GitCommit: 737905345d70ba1ebd566ce1230e4f971993dfd0
  GitTreeState: dirty
  GitTag: v2.12.9
  GoVersion: go1.15.8
  Compiler: gc
  Platform: darwin/amd64
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
I think the issue is that the CLI thought you passed a `-l`, which is a shorthand for `--labels` and expects labels. Your command is interpreted as `argo submit workflows/test.yaml -l og` which would give you the same output as follows:

```
FATA[2021-02-27T21:39:08.381Z] expected labels of the form: NAME1=VALUE2,NAME2=VALUE2. Received: og: unexpected label spec: og
```

**Comment by sarabala1979** [comment]
it has to be `argo submit --log examples/hello-world.yaml `

**Comment by max-sixty** [comment]
Thanks @terrytangyuan ; that makes sense. Closing.
