### ISSUE TITLE
Wait container not actually waiting for main container

### ISSUE THREAD

**Issue by worms** [argoproj/argo-workflows#5252]
## Summary 

About 5% of the time we are seeing the wait container thinking that the main container has exited when it actually hasn't.

## Diagnostics

What Kubernetes provider are you using? 
AWS EKS

What version of Argo Workflows are you running? 
V3 rc2

We are using the docker executor.

As can be seen in this truncated log the wait container starts then stops within 1 second.
The main container starts at roughly the same time the wait container ends.
The main container takes 20s to run. All the while the wait container has already thought it exited.
Because the wait container doesn't actually wait for the main container to finish its work there are parameters and artifacts that have not yet been written to the appropriate files for the wait container to pickup.

```
Status:             Failed
Containers:
  wait:
    Container ID:  docker://09aef6fedeeb54341f46d9fa3111d7d75439d2fe61e1b5fbd699310a3193c3cd
...
    State:      Terminated
      Reason:   Error
      Message:  Error: No such container:path: 86d5f6a01c0160460c2666adbe6fc2e2cdcfa4e76458f6f654b01e516289a0e0:/path/to/some/file
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
      Exit Code:    1
      Started:      Mon, 01 Mar 2021 21:11:29 -0500
      Finished:     Mon, 01 Mar 2021 21:11:30 -0500
    Ready:          False
    Restart Count:  0
...
  main:
    Container ID:   docker://86d5f6a01c0160460c2666adbe6fc2e2cdcfa4e76458f6f654b01e516289a0e0
...
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 01 Mar 2021 21:11:30 -0500
      Finished:     Mon, 01 Mar 2021 21:11:50 -0500
    Ready:          False
    Restart Count:  0
```

Here are some logs from the wait and main container:
```
time="2021-03-02T02:11:29.905Z" level=info msg="Starting Workflow Executor" version="{latest+ea3439c.dirty 2021-02-16T17:36:06Z ea3439c91c9fd0c2a57db0d8a5ccf2b9fb2454a3 v3.0.0-rc2 dirty go1.15.7 gc linux/amd64}"
time="2021-03-02T02:11:29.908Z" level=info msg="Creating a docker executor"
...
time="2021-03-02T02:11:29.909Z" level=info msg="Starting deadline monitor"
time="2021-03-02T02:11:29.940Z" level=info msg="mapped container name \"main\" to container ID \"86d5f6a01c0160460c2666adbe6fc2e2cdcfa4e76458f6f654b01e516289a0e0\""
time="2021-03-02T02:11:29.940Z" level=info msg="mapped container name \"wait\" to container ID \"09aef6fedeeb54341f46d9fa3111d7d75439d2fe61e1b5fbd699310a3193c3cd\""
time="2021-03-02T02:11:29.940Z" level=info msg="mapped container name \"POD\" to container ID \"b5310c19614deb9c591c0ca80312f8985a0ce2459eba31ecfc60640ace7144ae\""
time="2021-03-02T02:11:29.940Z" level=info msg="docker wait 86d5f6a01c0160460c2666adbe6fc2e2cdcfa4e76458f6f654b01e516289a0e0"
time="2021-03-02T02:11:29.966Z" level=info msg="Main container completed"
time="2021-03-02T02:11:29.966Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2021-03-02T02:11:29.966Z" level=info msg="Capturing script exit code"
time="2021-03-02T02:11:30.153Z" level=info msg="Saving logs"
time="2021-03-02T02:11:30.153Z" level=info msg="[docker logs 86d5f6a01c0160460c2666adbe6fc2e2cdcfa4e76458f6f654b01e516289a0e0]"
```
According to the logs above the main container completed at 11:29.966. Kubernetes disagrees as seen above.

Here is some logging from inside our main container using python logging:
(note, the very first thing we do in the code is time.sleep(10) to make it more likely to hit this issue)
```
2021-03-02 02:11:40,764 - root - DEBUG - Sleeping for 10s completed
...
2021-03-02 02:11:40,774 - root - DEBUG - complete. Sleeping for 10s
2021-03-02 02:11:50,784 - root - DEBUG - exiting after sleep
```

The code in this container is very simple. There are no conditionals. It does a bit of math, writes to files, then exits normally.

Things we have checked:
- verified that the container IDs that have been used match those that were checked for by docker wait ....
- verified that running this main container manually and doing docker wait... works successfully (made a script and validated running between 1 and 40 concurrently)

Random pieces of information that may or may not be useful:
- We have only seen this issue inside a withSequence. We do a bunch of preprocessing with long running and short running containers and they all work fine. Only when we get to the withSequence steps of our workflow do we see these issues.
- We have verified at a different part of our workflow using a completely different container that actually takes a long time to run (in essence video encoding) that we often get truncated files written as artifacts. We believe that in that case the main container manages to write a little bit before the wait container grabs the files as artifacts. The above is a simpler case of this but we can provide some details of those cases as well. 
- We have seen these issues when using main containers that run python code (not inline), shell scripts (inline and not inline), and a direct executable (some c++ code).
- 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you test `argoproj/argoexec:dev-docker` please?

**Comment by worms** [comment]
So far it looks like it works. I have run more jobs than I usually have to before it has had issues in the past.
I will run a few more and let you know.

Is it worthwhile to debug output the result of docker wait? That would have told me straight away perhaps?

**Comment by worms** [comment]
It looks to have resolved the issue!

**Comment by alexec** [comment]
@worms can I please ask you to re-run your tests?

**Comment by worms** [comment]
Yes sir. Running now.

**Comment by worms** [comment]
OK. It looks good from this end with the latest stuff on this branch as of 1 hour ago :)

**Comment by worms** [comment]
Incase this is helpful I got this error this morning on one of our workflows using the build I validated 18 hours prior from the dev-docker branch:

exit code 1: Error; failed to wait for main container to complete: timed out waiting for the condition: Error: No such object: 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26; ; verify serviceaccount ian-wormsbecker:default has necessary privileges

 wait:
    Container ID:  docker://2b8562951745252f96b45d128590e88291d9b0cfcf5db9af67ff13270bc65d84
...
    State:          Terminated
      Reason:       Error
      Message:      failed to wait for main container to complete: timed out waiting for the condition: Error: No such object: 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26
      Exit Code:    1
      Started:      Wed, 03 Mar 2021 08:59:18 -0500
      Finished:     Wed, 03 Mar 2021 08:59:50 -0500
    Ready:          False
    Restart Count:  0


  main:
    Container ID:   docker://25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26
...
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 03 Mar 2021 09:00:45 -0500
      Finished:     Wed, 03 Mar 2021 09:00:45 -0500
    Ready:          False
    Restart Count:  0
   

Here are the logs of all containers:

time="2021-03-03T13:59:18.372Z" level=info msg="Starting Workflow Executor" executorType= version="{latest+e44d0df.dirty 2021-03-02T19:26:01Z e44d0df5e43e2b402726277f755573984deeda20 latest dirty go1.15.7 gc linux/amd64}"
time="2021-03-03T13:59:18.379Z" level=info msg="Creating a docker executor"
time="2021-03-03T13:59:18.379Z" level=info msg="Executor (version: latest+e44d0df.dirty, build_date: 2021-03-02T19:26:01Z) initialized (pod: ian-wormsbecker/ofl-ftfkr-3412419998) with template:REDACTED"
time="2021-03-03T13:59:18.379Z" level=info msg="Starting annotations monitor"
time="2021-03-03T13:59:18.380Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:18.380Z" level=info msg="Starting deadline monitor"
time="2021-03-03T13:59:18.409Z" level=info msg="mapped container name \"wait\" to container ID \"2b8562951745252f96b45d128590e88291d9b0cfcf5db9af67ff13270bc65d84\""
time="2021-03-03T13:59:18.409Z" level=info msg="mapped container name \"POD\" to container ID \"2ddd2e4bda63733c6713f7a86da8aa5c8157e6b0bcd54ecf6fdd6c3c094773e4\""
time="2021-03-03T13:59:19.409Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:20.436Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:21.465Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:22.503Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:23.531Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:24.557Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:25.588Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:26.617Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:27.645Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:28.673Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:29.700Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:30.729Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:31.779Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:32.810Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:33.838Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:34.865Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:35.890Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:36.927Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:37.953Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:37.980Z" level=info msg="docker inspect 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26 --format={{.State.ExitCode}}"
time="2021-03-03T13:59:38.021Z" level=error msg="`docker inspect 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26 --format={{.State.ExitCode}}` failed: Error: No such object: 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26\n"
time="2021-03-03T13:59:39.323Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:39.351Z" level=info msg="docker inspect 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26 --format={{.State.ExitCode}}"
time="2021-03-03T13:59:39.406Z" level=error msg="`docker inspect 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26 --format={{.State.ExitCode}}` failed: Error: No such object: 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26\n"
time="2021-03-03T13:59:41.759Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:41.785Z" level=info msg="docker inspect 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26 --format={{.State.ExitCode}}"
time="2021-03-03T13:59:41.843Z" level=error msg="`docker inspect 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26 --format={{.State.ExitCode}}` failed: Error: No such object: 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26\n"
time="2021-03-03T13:59:45.254Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:45.282Z" level=info msg="docker inspect 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26 --format={{.State.ExitCode}}"
time="2021-03-03T13:59:45.367Z" level=error msg="`docker inspect 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26 --format={{.State.ExitCode}}` failed: Error: No such object: 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26\n"
time="2021-03-03T13:59:50.360Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}} --filter=label=io.kubernetes.pod.namespace=ian-wormsbecker --filter=label=io.kubernetes.pod.name=ofl-ftfkr-3412419998"
time="2021-03-03T13:59:50.385Z" level=info msg="docker inspect 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26 --format={{.State.ExitCode}}"
time="2021-03-03T13:59:50.442Z" level=error msg="`docker inspect 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26 --format={{.State.ExitCode}}` failed: Error: No such object: 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26\n"
time="2021-03-03T13:59:50.442Z" level=error msg="executor error: failed to wait for main container to complete: timed out waiting for the condition: Error: No such object: 25b3266e708faace9243d6b8bf15dc4c93ae490991b2f91797acae5a23d03b26"
time="2021-03-03T13:59:50.442Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2021-03-03T13:59:50.442Z" level=info msg="Capturing script exit code"
time="2021-03-03T13:59:50.442Z" level=error msg="executor error: container does not exist"
time="2021-03-03T13:59:50.442Z" level=info msg="Alloc=4930 TotalAlloc=10305 Sys=74065 NumGC=4 Goroutines=8"
time="2021-03-03T13:59:50.442Z" level=fatal msg="container does not exist"
<logs for main container that ran and completed as expected>

**Comment by vaibhav-k** [comment]
This issue also happens when the GKE node pool is using `Container-Optimized OS with Containerd (cos_containerd)`. Switching the container image back to `Container-optimized OS with docker` fixed the issue for us!

**Comment by sacreman** [comment]
> Container-optimized OS with docker

Same issue for us

**Comment by Bobgy** [comment]
I'm still seeing the same error message from time to time (like 5%) with argo v3.1.1, but I'm not sure if it's the same root cause.

Clarification: I'm using Kubernetes 1.18 with Container-optimized OS with docker nodes. So it's not the same issue as the last two comments.

**Comment by Bobgy** [comment]
For what it's worth, I'm observing that metrics-server and gke-metrics-agent are OOMing on my nodes after running a lot of pipelines.
Still investigating

**Comment by Bobgy** [comment]
I think despite what the root cause is, argo's call of the command is problematic, because even if there may be a failure in `docker cp`, exit code will be overwritten by the second command `gzip > xxxx` which always succeeds. Therefore, argo is missing root cause error message here.

```
sh -c docker cp -a 0494f392c91a41d7f4cf878f9ced4c56f3a030b4b64fb7b3f1f6828db982a9eb:/tmp/outputs/Output/data - | gzip  > /tmp/argo/outputs/artifacts/training-op-Output.tgz
```

**Comment by Bobgy** [comment]
I created a separate issue for my report: https://github.com/argoproj/argo-workflows/issues/6352

**Comment by pietermarsman** [comment]
I got a similar issue where the wait container was waiting for the main container before that was possible. Adding the logs here for future reference.

```
time="2021-12-30T21:26:49.212Z" level=info msg="docker wait acdc846ed1e8f3331f58d6076850b61b6c921506ed2a634f30ebf653f448687e"
time="2021-12-30T21:26:49.212Z" level=info msg="Starting deadline monitor"
time="2021-12-30T21:26:49.237Z" level=error msg="`docker wait acdc846ed1e8f3331f58d6076850b61b6c921506ed2a634f30ebf653f448687e` failed: Error response from daemon: No such container: acdc846ed1e8f3331f58d6076850b61b6c921506ed2a634f30ebf653f448687e\n"
time="2021-12-30T21:26:49.237Z" level=warning msg="Failed to wait for container id 'acdc846ed1e8f3331f58d6076850b61b6c921506ed2a634f30ebf653f448687e': Error response from daemon: No such container: acdc846ed1e8f3331f58d6076850b61b6c921506ed2a634f30ebf653f448687e"
```

The issue was resolved by @vaibhav-k  tip to use `Container-optimized OS with docker`.

Actually, I'm using terraform for deployment and adding this solved the issue: 


resource "google_container_node_pool" "pool" {
  ...
  node_config {
    ...
    image_type = "COS"
 }
}
