### ISSUE TITLE
UI: `All` regression in Workflow Archive view

### ISSUE THREAD

**Issue by dcherman** [argoproj/argo-workflows#5260]
## Summary 

All archived workflows should be shown when `All` is selected in the dropdown on the workflow archive page. Instead, it seems like only 10 are shown (which is the default).

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
What version is this on? Can't seem to be able to reproduce

**Comment by dcherman** [comment]
I was trying this on what's in master, but it's entirely possible I was using an unsupported combination of services as well (I was running the UI in master while port-forwarding to an older version of Argo that's running in our cluster).

**Comment by simster7** [comment]
Gtocha. Yeah I was not able to reproduce... if you see this bug again feel free to ping this and I'll reopen

**Comment by simster7** [comment]
One thing that is annoying is that we don't save the pagination preference... will fix that
