### ISSUE TITLE
UI - show completed runs aggregated for a cron workflow

### ISSUE THREAD

**Issue by saranyaeu2987** [argoproj/argo-workflows#5273]
# Summary

Currently, completed runs of a cron workflow is available in Workflow view, but that is along with other workflows or cron workflows.
Suggesting an UI enhancement to view the completed runs cron workflow either in /cron-workflows/argo or /workflows/argo

# Use Cases

Easy viewing of completed workflows of a cron  workflow

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tczhao** [comment]
Hi @saranyaeu2987 ,
I wonder if this is what you are after
![image](https://user-images.githubusercontent.com/20961507/153757450-e57cccfb-2213-4a92-9dca-0ad9a8320ba3.png)

**Comment by saranyaelumalai-okta** [comment]
Yes!!. Thanks.

**Comment by agilgur5** [comment]
Closing as this was answered above. See also #11706 as a similar, but different enhancement request (in Workflow View as opposed to Workflow List)
