### ISSUE TITLE
Show cron schedule in UI

### ISSUE THREAD

**Issue by saranyaeu2987** [argoproj/argo-workflows#5274]
# Summary
In addition to https://github.com/argoproj/argo-workflows/issues/3649, it would be nice to show the cron schedule information for a workflow run in UI either as a new column or in show details (attached image)

![image](https://user-images.githubusercontent.com/19850718/109826835-d0cef380-7c00-11eb-90f2-7d32516f36d2.png)

# Use Cases

Easy identification of scheduled date time for which cron workflow had run

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Would you like to submit a PR?

**Comment by saranyaeu2987** [comment]
sure

**Comment by alexec** [comment]
This was fixed in #5088.
