### ISSUE TITLE
Golang fundamental flaw bug - V3.0.0-rc4

### ISSUE THREAD

**Issue by everton-nasc** [argoproj/argo-workflows#5285]
Reopening regression issue. Last issue ref: https://github.com/argoproj/argo-workflows/issues/5192

Hey @alexec 
The issue still happening on version `3.0.0.-rc4`
<img width="473" alt="Screen Shot 2021-03-03 at 4 40 07 PM" src="https://user-images.githubusercontent.com/58737540/109886111-35ac3d00-7c45-11eb-8fe4-406de4017ec1.png">
<img width="1292" alt="Screen Shot 2021-03-03 at 4 37 49 PM" src="https://user-images.githubusercontent.com/58737540/109886114-36dd6a00-7c45-11eb-8df5-806d1a35758d.png">

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
fix(controller): Work-around Golang bug. Fixes #5192 (#5230)

**Comment by alexec** [comment]
Must have been missed somehow. https://github.com/argoproj/argo-workflows/releases

**Comment by alexec** [comment]
@simster7 can I ask this goes in rc5 please?

**Comment by simster7** [comment]
Yes, sorry. I must have inadvertently skipped it in rc4. I can get a new release out today? @alexec

**Comment by alexec** [comment]
No hurry. Next week is ok.
