### ISSUE TITLE
API /v1/templates does not support simultaneous repo/branch filtering and searching

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-workflows#53]
Steps to reproduce:

1. Click global search box and search for any template name.
1. On global search results page apply branch filter

Expected result:

Templates should be shown only from specified branch

Actual result:

All templates from specified branch are shown and search text is ignored.

**Comment by sandeepbhojwani** [comment]
UI currently uses repo_branch field to apply the branch filter. Please use branch field instead.

**Comment by alexmt** [comment]
repo_branch is used by UI need to filter by multiple repo/branches . Field branch does not allow such filtering.
