### ISSUE TITLE
argo doesn't work in openshift clusters 

### ISSUE THREAD

**Issue by dongwangdw** [argoproj/argo-workflows#5306]
## Summary 

I deployed hello-world demo.
But I it got stuck for long in stage of pod creating.
I describe the pods and I got as below:
```
 Warning  FailedMount  48m (x189 over 17h)    kubelet  Unable to attach or mount volumes: unmounted volumes=[docker-sock], unattached volumes=[podmetadata docker-sock my-minio-cred default-token-jgg76]: timed out waiting for the condition
```

## Diagnostics

What Kubernetes provider are you using? 
OCP 4.6.19

What version of Argo Workflows are you running? 
2.12.9

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```
Just the hello-world demo in ocp

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```
```
time="2021-03-04T09:12:44.061Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-ldtts
time="2021-03-04T09:12:44.061Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=hello-world-ldtts
time="2021-03-04T09:12:44.062Z" level=info msg="Pod node hello-world-ldtts initialized Pending" namespace=argo workflow=hello-world-ldtts
time="2021-03-04T09:12:44.121Z" level=info msg="Created pod: hello-world-ldtts (hello-world-ldtts)" namespace=argo workflow=hello-world-ldtts
time="2021-03-04T09:12:44.136Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=8737051 workflow=hello-world-ldtts
time="2021-03-04T09:12:54.122Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-ldtts
time="2021-03-04T09:12:54.135Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=8737209 workflow=hello-world-ldtts
time="2021-03-04T09:13:04.136Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-ldtts
time="2021-03-04T09:17:37.833Z" level=info msg="Performing periodic workflow GC"
time="2021-03-04T09:22:37.833Z" level=info msg="Performing periodic workflow GC"
time="2021-03-04T09:27:37.833Z" level=info msg="Performing periodic workflow GC"
time="2021-03-04T09:32:37.833Z" level=info msg="Performing periodic workflow GC"
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by dongwangdw** [comment]
This issue shoule related to #826.
And I also tried the test here. It worked for me run a test pod with hostPath.
Any hints for this?

**Comment by alexec** [comment]
try using PNS executor

**Comment by dongwangdw** [comment]
> try using PNS executor

Sorry，I am new to this project. 
Is there a link/doc for this?

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/blob/master/docs/workflow-executors.md

**Comment by dongwangdw** [comment]
@alexec Thanks. I will try this.

**Comment by henrik-koren** [comment]
I try to run with the pns executor the same issues 
`Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    9m26s                 default-scheduler  Successfully assigned argocd/sparkly-bear to tkg01-workers-8s68h-75fcdc9cb6-kstrh
  Warning  FailedMount  7m23s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[docker-sock], unattached volumes=[default-token-htwxr podmetadata docker-sock my-minio-cred]: timed out waiting for the condition
  Warning  FailedMount  2m51s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[docker-sock], unattached volumes=[my-minio-cred default-token-htwxr podmetadata docker-sock]: timed out waiting for the condition
  Warning  FailedMount  72s (x12 over 9m26s)  kubelet            MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
  Warning  FailedMount  33s (x2 over 5m7s)    kubelet            Unable to attach or mount volumes: unmounted volumes=[docker-sock], unattached volumes=[podmetadata docker-sock my-minio-cred default-token-htwxr]: timed out waiting for the condition
`

**Comment by dongwangdw** [comment]
@alexec This works for me. Thanks.
@henrik-koren I think you only should setup `containerRuntimeExecutor`, `containerRuntimeExecutors` has a label which will only work for the matched scenario. This is my understand.

I will close this. Since my issue resolved.
