### ISSUE TITLE
container set next steps: save all pod logs to artifact storage, not just main

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5316]
Currently, if you want to capture logs, we only capture the main container.

**Comment by mostaphaRoudsari** [comment]
Hi, @alexec, Have there been any updates on this one? ContainerSets are great for grouping small tasks but they are really hard to debug if something goes wrong and without access to the logs except for the main one.

**Comment by isubasinghe** [comment]
Can you point me to the functionality that is missing for Container Sets that is present for other workflow kinds? Thanks.

**Comment by alexec** [comment]
This is capture to S3.

**Comment by agilgur5** [comment]
> This is capture to S3.

I.e. `archiveLogs: true`

**Comment by agilgur5** [comment]
I think this was completed in #8491
