### ISSUE TITLE
Argo UI- Column names and data are not aligned 

### ISSUE THREAD

**Issue by ppapasani1** [argoproj/argo-workflows#5323]
## Summary 

Argo UI- Column names and data are not aligned

## Diagnostics

What Kubernetes provider are you using?  
On-prem

What version of Argo Workflows are you running? 
V3.0.0-rc4
![image](https://user-images.githubusercontent.com/37124509/110287778-eabf5c00-7f9b-11eb-857d-eb0777306235.png)

**Comment by simster7** [comment]
Yup, it is indeed annoying. I'm already working on a fix for this.
