### ISSUE TITLE
SSO - Keycloak

### ISSUE THREAD

**Issue by marct83** [argoproj/argo-workflows#5332]
Having some trouble setting up SSO with Keycloak. Followed the docs. I have the client created in the Keycloak realm. Secrets created. Config map updated. Server using the --auth-mode sso arg. When I try the SSO Login I get this error:

failed to exchange token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Code not valid"}

**Comment by iven** [comment]
I set up SSO with self-hosted SSO provider, and got the same error.

By default, Argo tries to auto-detect your AuthType, at first it tries to use `InHeader`, if any error occurs, it tries `InParams`. Some provider doesn't support this feature, and make your code invalid at your first try. So when you make the second try, the server returns `invalid_grant` error.

Maybe it's the same reason for Keycloak.

**Comment by Stevenyu1982** [comment]
my keycloak setup seems work, but i am getting this error

time="2021-05-19T05:45:45.738Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2021-05-19T05:45:45Z" grpc.time_ms=0.051 span.kind=server system=grpc

**Comment by r-nagaraj** [comment]
Hi All, 
I am also getting the same error.  Please help me to solve the same.

time="2022-03-08T10:38:18.204Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2022-03-08T10:38:18Z" grpc.time_ms=0.066 span.kind=server system=grpc

Thanks,

**Comment by rmalenko** [comment]
The same error
