### ISSUE TITLE
Argo Workflows resource naming

### ISSUE THREAD

**Issue by groodt** [argoproj/argo-workflows#5333]
# Summary

The ship may have already sailed, but I think that the names of the Kubernetes resources may be confusing to beginners. I even find them confusing myself, and I've been a user for a while now! 😂 

There is:
`Workflow`
`Template`
`Step`
`Workflow Template`

The concepts make sense after using them for a while, but they aren't immediately obvious and I think the concept of a "template" is overloaded which causes confusion.

Have we considered a rethink as part of Argo 3.0, since 3.0 is a "breaking" change to some degree anyway?

I would propose the following at a minimum:
`Workflow` - remains the same. Directly "submittable", but also represents an individual "run" of a "Workflow Template" (or CronWorkflowTemplate.
`Workflow Template` - remains the same. A definition of a Workflow that resides within the cluster and be referenced and submitted.
**`Template` -> `StepTemplate`** I think this is the confusing one. A reusable element within a Workflow that can be referenced as a step or task to run as part of a larger workflow. I think the prefix of "Step" helps to clarify that these templates are "internal" to a Workflow and represent some reusable step or task that can be orchestrated as part of a larger Workflow.
`Step` - remains the same.

I'm sure there may be other suggestions to clarify the naming of the various concepts and improve consistency.

**Comment by alexec** [comment]
This is confusing, but I think we are stuck with it. Would you like to help improve the docs for this?

**Comment by groodt** [comment]
> This is confusing, but I think we are stuck with it. Would you like to help improve the docs for this?

I'm not sure this is truly solvable with documentation. The documentation is clear in my opinion, but it expects somebody to read all of it. I think it's confusing even during conversations with people who have read the documentation. It's not always clear when somebody says "template", which "template" they are talking about. Yes, sometimes context helps to clarify this, or the speaker can try to be helpful and be more clear, but it is clumsy to have conversations about these abstractions when a few of the terms overlap.
