### ISSUE TITLE
Istio sidecar not terminated when main container completes

### ISSUE THREAD

**Issue by hadesy** [argoproj/argo-workflows#5337]
## Summary 

I enable Istio automatic injection for argo worker pods, but after the main container completed, the serving sidecar was not terminated, and left the pipeline stuck in a running state.

I expected the sidecar to get terminated after the main container completed.

## Diagnostics

What Kubernetes provider are you using? 

- ACK 1.18.8

What version of Argo Workflows are you running? 

- v3.0.0-rc5

I think it's related to  https://github.com/argoproj/argo-workflows/commit/2ff4db115daa4e801da10938ecdb9e27d5810b35
https://github.com/argoproj/argo-workflows/blob/814944cb86c220102b5d4d60c399b82901919e82/workflow/executor/executor.go#L1083

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you please say why?

> I think it's related to 2ff4db1

**Comment by hadesy** [comment]
fixed
