### ISSUE TITLE
init container stuck listing directory from S3

### ISSUE THREAD

**Issue by worms** [argoproj/argo-workflows#5352]
## Summary 

We are using 3.0.0 rc6. We are finding that often the init container seems to stop pulling down artifacts from S3. We see this log line and then nothing further for hours. The directory in question in S3 has 20 files in it, the largest is a few megabytes. Any suggestions on other data to acquire or look at?

time="2021-03-10T14:21:21.079Z" level=info msg="Downloading artifact: segment-files"
time="2021-03-10T14:21:21.079Z" level=info msg="S3 Load path: /argo/inputs/artifacts/segment-files.tmp, key: argos-scratch/c29d8e95-a8b7-45c1-ab66-5aa070ae290c/optimized/"
time="2021-03-10T14:21:21.079Z" level=info msg="Creating minio client s3.amazonaws.com using static credentials"
time="2021-03-10T14:21:21.079Z" level=info msg="Getting from s3 (endpoint: s3.amazonaws.com, bucket: scratch-space, key: argos-scratch/c29d8e95-a8b7-45c1-ab66-5aa070ae290c/optimized/) to /argo/inputs/artifacts/segment-files.tmp"
time="2021-03-10T14:21:21.170Z" level=info msg="Getting directory from s3 (endpoint: s3.amazonaws.com, bucket: scratch-space, key: argos-scratch/c29d8e95-a8b7-45c1-ab66-5aa070ae290c/optimized/) to /argo/inputs/artifacts/segment-files.tmp"
time="2021-03-10T14:21:21.170Z" level=info msg="Listing directory from s3 (endpoint: s3.amazonaws.com, bucket: scratch-space, key: argos-scratch/c29d8e95-a8b7-45c1-ab66-5aa070ae290c/optimized/)"

I also noticed in the vendored s3 code the following:

>-------listOpts := minio.ListObjectsOptions{
>------->-------//Prefix:    keyPrefix,
>------->-------Recursive: true,
>-------}

Perhaps the Prefix line should NOT be commented?

## Diagnostics

What Kubernetes provider are you using? 
EKS

What version of Argo Workflows are you running? 
3.0.0 rc6

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by worms** [comment]
Awesome. If you have a branch pushed I can build and test for you :)

**Comment by simster7** [comment]
> Awesome. If you have a branch pushed I can build and test for you :)

Thanks! This would be great... I'm building a dev image for you
