### ISSUE TITLE
cronworkflow with concurrencypolicy: "Replace"

### ISSUE THREAD

**Issue by yuvarajpalaniappan** [argoproj/argo-workflows#5354]
I was trying to apply cmd "argo cron create " for second time with with concurrencypolicy: "Replace" , it was throwing error "AlreadyExist"
Scenario: I was automating argo workflow yaml with application code using gitlab. Consider there is change in cronworkflow yaml and application code, there is already cronworkflow is created in environment. i am changing cronworkflow yaml and i am applying using "argo cron create " for second time it again with concurrencypolicy: "Replace". Its throwing an error "AlreadyExist" instead of replacing old one. How to handle these Scenario on applying cronworkflow in argo environment second time whether i need to delete old cronworkflow/existing cronworkflow using "argo cron delete" and apply it again using "argo cron create".
Could you please anyone help it. Please let me know any additional information

**Comment by simster7** [comment]
You cannot use `argo cron create` to create a cron workflow that already exists. Either edit it with `kubectl edit cwf <CRON_WORKFLOW_NAME>` or delete it and re create it `argo cron delete <CRON_WORKFLOW_NAME> && argo cron create`

**Comment by yuvarajpalaniappan** [comment]
@simster7 Deleting cronworkflow deletes corresponding workflow associated  with it. Not able to understand use of functionality concurrencypolicy: "Replace", will not replace cronworkflow.

**Comment by simster7** [comment]
You can see what concurrency policy does [in the cron workflow doc](https://github.com/argoproj/argo-workflows/blob/master/docs/cron-workflows.md#cronworkflow-options). In short, it affects Workflows spawned by the Cron Workflow, not the Cron Workflow itself.

In general, you don't want to update your Cron Workflow object often, but if you want to automate Cron Workflow YAML with CI/CD, you might want to consider having [Argo CD](https://argoproj.github.io/argo-cd/) manage your Cronworkflow objects. You can also use `kubectl` from the CI/CD pipeline, you'll probably have to set up a valid KUBECONFIG in your pipeline to do so.

**Comment by yuvarajpalaniappan** [comment]
@simster7 is there reason we should not  update your Cron Workflow object often? is there is a negative impact?
