### ISSUE TITLE
Pending pod not stopped by Argo on Stop

### ISSUE THREAD

**Issue by XciD** [argoproj/argo-workflows#5355]
## Summary 

What happened/what you expected to happen?

We have a workflow that spawn a pod. The workflow is being interrupted but the pod was still not on Running on kubernetes API. The workflow stops but the pod is still running (until grace period I suppose)

Some events timeline:
```
15:23:58.802 - wait/pod-log     - level=info msg="Starting Workflow Executor" version=v2.11.8
15:23:59.908 - argo-controller  - Deleting Pending pod namespace/pod-2245639993 as part of workflow shutdown with strategy: Stop
15:24:00.000 - argo-controller  - node namespace/pod-2245639993 phase Pending -> Failed
15:24:00.474 - wait/pod-log     - Starting annotations monitor
15:24:00.474 - wait/pod-log     - main container started with container ID: id
15:24:00.477 - wait/pod-log     - docker wait id"
15:24:00.477 - wait/pod-log     - Starting deadline monitor"
15:24:04.133 - main/pod-log     - Pod kill himself without receiving any signal...
```

What you expected to happen:
- The main container should have received a signal to shutdown or pod should have been annotated to be killed.

This is a difficult to reproduce bug, We didnt found a way to reproduce it everytime...

## Diagnostics

What Kubernetes provider are you using? 
- Vanilla kubernetes with kubeadm

What version of Argo Workflows are you running? 
- v2.11.8

Thanks you

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
> v2.11.8

We've made some fixes to this recently. Could I ask you to try if this issue exists on `v2.12.10` (latest)?
