### ISSUE TITLE
[Proposal] Support resubmit/retry on archived workflows

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#5405]
# Summary

What change needs making?

Support resubmit/retry on archived workflows.

# Use Cases

When would you use this?

Currently `argo retry/resubmit` only supports workflows resources that currently exist in the cluster. For clusters where workflows are GC-ed immediately after they are completed, it's not possible to retry/resubmit a workflow. There are workaound for this, e.g. saving the workflow resource manually either as a plain YAML or into archived workflow before we GC it, and then do a `kubectl create` before we use `argo retry/resubmit`. It would be better and less hacky if we have a CLI for this.

# API/Implementation Discussion

We can implement this in one of the following ways:
1. `argo retry/resubmit wf-name --from-archive`
2. `argo archive retry/resubmit`
3. `argo retry/resubmit --source=location-to-saved-wf.yaml`

Tasks
- [x] #7906
- [x] #7907
- [x] #7908
- [x] #7909
- [x] #7910
- [ ] #7911

Any preference?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
We should also provide this feature in the UI.

**Comment by dpadhiar** [comment]
I will take this issue

**Comment by terrytangyuan** [comment]
Wow this got popular. 👍🏻 @dpadhiar assigned to you.
