### ISSUE TITLE
[Proposal] GC for workflow memoization cache

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#5406]
# Summary

What change needs making?

Support GC mechanism for workflow memoization cache.

# Use Cases

When would you use this?

My original proposal in https://github.com/argoproj/argo-workflows/issues/3593 actually includes this but I think it was closed with a focus on the freshness/usability of the cache with the new `maxAge` field. The original proposal also contains another important feature: when the number of configmaps get big, it **requires manual maintenance** to delete the outdated ones and often it's hard to figure out which ones can be considered outdated without domain knowledge from users who submitted the workflows.

I wonder if we could leverage `maxAge` for this and allow automatic GC of configmaps that are older than `maxAge`. It should be straightforward to support this.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
@simster7 What do you think about reusing `maxAge` for this? Any suggestions would be appreciated.

**Comment by simster7** [comment]
Overall I agree that some GC on the config maps could be useful. 

> I wonder if we could leverage maxAge for this and allow automatic GC of configmaps that are older than maxAge. It should be straightforward to support this.

Could you explain a bit more what the implementation proposal would be here?

**Comment by simster7** [comment]
Not sure it's trivial to just use `maxAge`. I can see the case where if the controller gets a cache entry that is too old due to the `maxAge` field of the workflow, it _could_ be deleted by the controller at that point. However, that doesn't consider that other workflows (some who have not even been created yet) could have `maxAge`s with higher value or no `maxAge` set.

If you mean introducing a `maxAge` to the cache entries in the config maps, who would determine that value? The writer to the cache? What if other subsequent workflows have higher `maxAge`s?

When we designed `maxAge` we purposefully left it as a template field with the intention of allowing templates to decide if a cache entry is too old for them or not, not for a cache entry to decide if its too old for all possible templates.

**Comment by simster7** [comment]
What are your thoughts?

**Comment by terrytangyuan** [comment]
Thanks! With the original design decision on `maxAge` in mind, it makes sense to keep `maxAge` as is and keep it for workflow authors to decide whether to consider a cache as fresh/usable. What if:
1. We record the timestamp when the cache is hit last time.
2. Introduce a field in cache entry (e.g. `gcAfterNotHitDuration`) that represents how long we can keep the cache if it's not been hit for a specified duration. This way we can respect the workflow authors' knowledge to decide this duration and use the last hit timestamp to decide whether the cache is still useful/being used.
3. If multiple workflows have the same cache entry but with different `gcAfterNotHitDuration`, we respect the workflow spec that's processed first. For example, if the first processed workflow decided to gc the relevant cache, we add that cache to deletion queue. Workflows that are processed later can still use the cache if it's not deleted yet AND its age does not exceed `maxAge` yet.

**Comment by simster7** [comment]
> Perhaps gcAfterNotHitDuration can be more generalized to a cache.gcStrategy so it can be extended later based on different strategies.

I think I like this better... regardless, it should be added on a per ConfigMap basis. Ie, different ConfigMaps (caches) should be able to have different strategies.

It seems like we'll need to add an extra controller to monitor the ConfigMaps no?

**Comment by terrytangyuan** [comment]
Yes an extra controller for ConfigMaps seems to be the most straightforward since it's independent of reconciliation of pods/workflows. Are there any concerns or suggestions in this direction?
