### ISSUE TITLE
Handle panics in Goroutines

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5411]
When a Goroutine panics, I believe it just dies silently. 

Add this logging to Goroutines:

```golang
defer runtimeutil.HandleCrash(runtimeutil.PanicHandlers...)
```

**Comment by alexec** [comment]
https://blog.golang.org/defer-panic-and-recover

**Comment by alexec** [comment]
@sarabala1979 would you like to own?

**Comment by sarabala1979** [comment]
I will take it
