### ISSUE TITLE
Standard installation and example workflow produces panic: runtime error

### ISSUE THREAD

**Issue by wdma** [argoproj/argo-workflows#5422]
## Summary 

I am running the standard argo workflow installation (https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/install.yaml). When running the following command:
```
argo submit -n argo --watch https://github.com/argoproj/argo-workflows/blob/master/examples/volumes-pvc.yaml --serviceaccount argo
```
I am getting this error:
```
go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x15fde4e]

goroutine 1 [running]:
github.com/argoproj/argo-workflows/v3/workflow/common.SplitWorkflowYAMLFile(0xc000a68000, 0x1d1bd, 0x1fe00, 0x2599d01, 0xc00020bc00, 0xc00000e010, 0x1, 0x1, 0x34b5780)
        /Users/sbeharyutk/go/src/github.com/argoproj/argo-workflows/workflow/common/parse.go:103 +0x29e
github.com/argoproj/argo-workflows/v3/cmd/argo/commands.unmarshalWorkflows(0xc000a68000, 0x1d1bd, 0x1fe00, 0xc0008d2101, 0x1, 0x1, 0x0)
        /Users/sbeharyutk/go/src/github.com/argoproj/argo-workflows/cmd/argo/commands/submit.go:250 +0xdf
github.com/argoproj/argo-workflows/v3/cmd/argo/commands.submitWorkflowsFromFile(0x351bc40, 0xc0005ceae0, 0x35675e0, 0xc00031cb70, 0x7ffe91668711, 0x4, 0xc00034b080, 0x1, 0x6, 0xc0005e95e0, ...)
        /Users/sbeharyutk/go/src/github.com/argoproj/argo-workflows/cmd/argo/commands/submit.go:118 +0x16a
github.com/argoproj/argo-workflows/v3/cmd/argo/commands.NewSubmitCommand.func1(0xc000211600, 0xc00034b080, 0x1, 0x6)
        /Users/sbeharyutk/go/src/github.com/argoproj/argo-workflows/cmd/argo/commands/submit.go:86 +0x29a
github.com/spf13/cobra.(*Command).execute(0xc000211600, 0xc00034afc0, 0x6, 0x6, 0xc000211600, 0xc00034afc0)
        /Users/sbeharyutk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000657340, 0xc000070750, 0xc000717f50, 0x40576f)
        /Users/sbeharyutk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/sbeharyutk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /Users/sbeharyutk/go/src/github.com/argoproj/argo-workflows/cmd/argo/main.go:14 +0x2b
```

This result is the same regardless of the RBAC used.

## Diagnostics

What Kubernetes provider are you using?  Calico

What version of Argo Workflows are you running? https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/install.yaml

There are no logs produced (the container is not generated)

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Try using the raw URL, rather than submitting the page, which I think would be HTML:

https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/volumes-pvc.yaml

**Comment by wdma** [comment]
D'oh!    Ok.  Now I am back to something I understand, but still am experiencing a problem.  

This manifest produces the following error when using the Kubernetes admin account 

![image](https://user-images.githubusercontent.com/8416524/111392356-c5fa7100-868c-11eb-950d-8150d202187e.png)

When using the workflow-role RBAC recommended with the Quickstart manifest, the error looks like this:

![image](https://user-images.githubusercontent.com/8416524/111392469-0a860c80-868d-11eb-8d65-5de5041bace5.png)

**Comment by alexec** [comment]
You can use `kubectl auth can-i` to check your permissions. You should make sure your SA (which should probably not be `argo` as that is the workflow controller's SA) has the correct permissions:

https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start/base/workflow-role.yaml

**Comment by alexec** [comment]
https://blog.argoproj.io/demystifying-argo-workflowss-kubernetes-rbac-7a1406d446fc

**Comment by wdma** [comment]
Thank you! That does help me understand the reason for the workflow-role! 

However, I think it does not explain the error when running as the kubernetes admin.  I think that role should be able to submit the yaml(?)  I am looking for an example of an ephemeral volume and this seems to be the correct model.

**Comment by terrytangyuan** [comment]
> ```
> kubernetes error: a container name must be specified for pod (main, wait)
> ```
Not sure what command you are running but you need to specify the container name if there are multiple containers in the pod, e.g. `-c main` for main container.

**Comment by wdma** [comment]
I think I am making progress.  One last question:  Can you tell me what serviceaccount I should be using?

Thank you!!!

You should make sure your SA (which should probably not be argo as that is the workflow controller's SA) has the correct permissions
