### ISSUE TITLE
3.0 RC7 - Archived workflows never make it to the database

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5428]
## Summary 

What happened/what you expected to happen?
- Set up a (in my case) Postgres database and set up the ```persistence: |``` section of the configmap according to the documentation.
- The workflow controller logs happily state that it has connected to the database and that workflows are being archived, and you can see the archived workflows in the UI however:
- Workflows are not being pushed to the database. When I restart the workflow controller, all my archived workflows are lost.

I have tried a few combinations of disabling migration, disabling SSL etc, but this doesn't address the issue.

## Diagnostics

What Kubernetes provider are you using? EKS 1.19

What version of Argo Workflows are you running? 3.0.0 RC7

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
By "see in the user interface" do you mean under the archived workflows tab?

**Comment by alexec** [comment]
They cannot appear in that tab if they are not in your database. Can you list the table names in your database and check the table name? It should `argo_archived_workflows` or similar.

**Comment by tim-sendible** [comment]
My database was brand new for RC7. It (still) contains no tables.

**Comment by tim-sendible** [comment]
My apologies. It looks like there's something funky going on with my posgres instance. It turns out the table is there, and hidden, and now restarting the Workflow pods persists the data afterall. Sorry for wasting your time.
