### ISSUE TITLE
Adding a link to a pod, can't get the pod name from variable

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5429]
## Summary 

What happened/what you expected to happen?

Using the example in the configmap:
```# Adds a button next to the pod.  E.g. linking to you logging facility but for the pod only.
    - name: Example Pod Link
      scope: pod
      url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
```

``` ${metadata.name} ``` does not get translated into an actual name, it just remains as it is. My resulting URL is something like:
``` https://logging-facility?namespace=test&podName=${metadata.name}&startedAt….```

## Diagnostics

What Kubernetes provider are you using? EKS 1.19

What version of Argo Workflows are you running? 3.0.0 RC7 (also occurs in RC6)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
This has been fixed in [`v3.0.0-rc9`](https://github.com/argoproj/argo-workflows/releases/tag/v3.0.0-rc9)
