### ISSUE TITLE
Implement Agent

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5439]
Write the code for the agent:

* Controller creating agent on-demand.
* Controller deleting agent when workflow completes.
* Controller adding task to task-set when needed.
* Controller removing completed tasks from the task-set at the end of reconciliation (after updating workflow).
* Agent executing task in sequence.

Out of scope for MVP:

* Throttling task creation.
* Limiting tasks in-flight.
* Scaling task execution (i.e. parallel tasks).

**Comment by sarabala1979** [comment]
### **Agent Design:**

![image](https://user-images.githubusercontent.com/33908564/114126895-29ec1000-98ae-11eb-976c-6ffea009b95c.png)

TaskSet CRD: https://github.com/argoproj/argo-workflows/pull/5628


### **Resposibility:** 

| Controller  https://github.com/argoproj/argo-workflows/issues/5544 (Bala)| Agent (Simon) |
| ------------- | ------------- |
| Controller will create TaskSet (Name= workflowName) and Agent Pod (Name= workflowName) in workflow's namespace when controller first sees HTTP template (Agent supported template types) in step/task execution | Agent will monitor the TaskSet informer with specific TaskSet object (name/label)|
| Controller will monitor the TaskSet state changes and queue the workflow for the process. The controller will reconcile the TastSet change and update the Workflow node status once a particular task is completed. | Agent will execute the task sequentially from tasks list |
| Controller will upset/patch new HTTP templates into tasklist in TaskSet.  | Agent will create  TaskStatus with NodeID.| 
|Controller will delete the agent pod and TaskSet once the workflow completes. | TaskStatus contains output(Parameters and Result), Phase, and message for the task. |  

Out of scope for MVP:
1. Clearing the completed Task and TaskResult from TaskSet Object
2. Compress and Decompress TaskResult if  TaskSet Object size > 1 MB

Question:
1. Do we need to support retryStrategy if the HTTP template fails?
2. Do we need to support Resouce Quota for Agent Pod?
3. Do we need to support Secrete mount on Agent Pod?

**Comment by bklaubos** [comment]
What is the rationale and usecase scenarios for this enhancement?

**Comment by Bobgy** [comment]
Open Questions:
* do we support third party implementation of agents & custom task specs as another way for integration? (refer to Tekton custom tasks)
* can this architecture work when multiple agents (both 1st party and 3rd party agents) watch the same taskset and work on different tasks?

I feel that these can be useful future directions, curious about your thoughts

**Comment by sarabala1979** [comment]
>can this architecture work when multiple agents (both 1st party and 3rd party agents) watch the same taskset and work on different tasks?
Yes, the Current design can support this. But for the MVP of this feature release, will support the default agent (argoexec). Please raise the enhancement issue with your usecase.

**Comment by sarabala1979** [comment]
@Bobgy I merged http template PR to master. Can you try with `latest`?

**Comment by Bobgy** [comment]
Sorry the message slipped through the cracks. Let me try 3.2 and get back to you.

Cc @capri-xiyue
