### ISSUE TITLE
Date Picker element on Archived Workflows tab hides behind the background

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5443]
## Summary 

If you navigate to the Archived Workflows tab and try to change the date, you will see that the date picker elements are not brought to the foreground when interacting with them.

Workaround: Change the dates by manually adjusting the URL in the browser's address bar.

## Diagnostics

What Kubernetes provider are you using? EKS 1.1.9

What version of Argo Workflows are you running? 3.0.0 RC7

Browsers: Chrome 89, Firefox 86 - MacOS 11.2.3

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Screenshot?

**Comment by simster7** [comment]
Able to reproduce... working on a fix

**Comment by simster7** [comment]
This has been fixed in [`v3.0.0-rc9`](https://github.com/argoproj/argo-workflows/releases/tag/v3.0.0-rc9)
