### ISSUE TITLE
Support session tokens to access S3 buckets

### ISSUE THREAD

**Issue by arl7** [argoproj/argo-workflows#5446]
# Summary
Argo-workflows should support session token in addition to access key and secret access key to access a bucket.

This issue was already raised some time back: [https://github.com/argoproj/argo-workflows/issues/1749](https://github.com/argoproj/argo-workflows/issues/1749) but it got closed because of no response from the original poster of the request.

What change needs making?

# Use Cases

When would you use this?
This is usefule in the case when users have access to only temporary credentials instead of permanent ones. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Would you like to submit a PR to add this?

**Comment by arl7** [comment]
Sorry for late reply. Still working on this

**Comment by JacobHenner** [comment]
Linking duplicate: https://github.com/argoproj/argo-workflows/issues/1039

For reference, a similar feature was added to Argo Events in August: https://github.com/argoproj/argo-events/pull/2092/files

@arl7 are you still working on this? If not, I'd be interested in giving it a shot.

**Comment by hittingray** [comment]
Hey @JacobHenner and @arl7, are either of you working on this? I just had a quick stab today and it doesn't seem too difficult. If neither of you are, I'll get around to a PR sometime soon.

**Comment by JacobHenner** [comment]
> Hey @JacobHenner and @arl7, are either of you working on this? I just had a quick stab today and it doesn't seem too difficult. If neither of you are, I'll get around to a PR sometime soon.

No, go ahead 🙂
