### ISSUE TITLE
CLI: Support `update` for CronWorkflows, WorkflowTemplates, and ClusterWorkflowTemplates

### ISSUE THREAD

**Issue by sunil-b** [argoproj/argo-workflows#5464]
# Summary

Currently Argo CLI doesn't support updating CronWorkflows, WorkflowTemplates and ClusterWorkflowTemplates. If we want to change any of these resources, we have to delete first and then recreate them. The other way to update these resource would be via kubectl, which doesn't support overriding parameters.

Workflows depending on templates within above resources would have to deal with failures during the delete and recreate process. The chance of failure increases with the increase in workflow count in a cluster.

Looks like we already have REST APIs to update these resources. Ex: `PUT /api/v1/cron-workflows/{namespace}/{name}`. It would be nice to expose the same via CLI.

# Use Cases

Workflow templates, Cron workflows etc. change from time to time. There might be changes in steps, arguments etc. Exposing update operation in Argo CLI would help improving the experience.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
@simster7 Looks like #5465 is closed since it goes stale. Are you still planning to finish it? Let me know and If not, I can help pick up from what's left.

One user just requested this feature yesterday ([Slack thread](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1620235308455100)). The use case is to update a `WorkflowTemplate` without deleting it without validation which `kubectl` does not offer.

**Comment by simster7** [comment]
@yakout Can't remember why, but it seems like this was de-prioritized. The community should feel free to take this on

**Comment by makzzz1986** [comment]
It is quite important for us, I hope this ticket won't be closed. Our issue is that we need to update the image tag during CI. The `latest` tag is not the proper sometimes. I think we are going to use `kubectl` for now, but it is quite awkward, like: `kubectl patch workflowtemplates test-template --type "json" -p '[{"op": "replace", "path": "/spec/arguments/parameters/0/value", "value": "myimage:1234"}]'`

**Comment by alexec** [comment]
Anyone in the community is welcome to submit a PR to add this feature.
