### ISSUE TITLE
Argo- v3.0.0-rc8 has issues with argo server

### ISSUE THREAD

**Issue by chittu11** [argoproj/argo-workflows#5466]
We have upgraded argo to v3.0.0-rc8 in our environment but argo UI is not picking up, its failing with the below error. we had to run the server with older version(v3.0.0-rc6). this version has any known issues with argo server?

upto argo 3.0.0-rc6 argo server is working fine but in the newer version its not picking up.

`Error: INFO[2021-03-18T19:57:44.786Z]authModes="[server]" baseHRef=/ managedNamespace= namespace=default secure=true
FATA[2021-03-18T19:57:44.786Z] open argo-server.crt: no such file or directory `

Appreciate any pointers with this regrads.

Thank you
Chittu

**Comment by sbose78** [comment]
Could you share more information on your distribution of Kubernetes you are using?

**Comment by ad22** [comment]
This does not have anything to do with the Kubernetes distribution. https://github.com/argoproj/argo-workflows/issues/2764, https://github.com/argoproj/argo-workflows/pull/2766 broke a LOT of things, and even worse, left everything undocumented. 

1. Running argo-server locally results in it not being able to find a self signed cert that it now requires. Instructions should say, generate a cert via openssl. However, even generating a cert with openssl causes my browser to reject loading the UI.. HSTS header is sent by default I imagine, and no way to turn it off?

2. Running argo-server via the provided quick start manifests on Kubernetes now fails cert validation in the UI - x509 errors. go 1.15 requires a cert with SAN's unless turned off via an env var. 

I downgraded to rc6.. I recommend reverting the entire feature.

**Comment by simster7** [comment]
The only difference in `rc7`+ is that TLS is enabled by default. You can disable it by running `argo server --secure=false`.

I agree that this needs better documentation.

**Comment by alexec** [comment]
Under no circumstances will TLS support will be removed if anyone is worried. However, it sounds like it doesn’t work out of the box with the CLI anymore because it is on. So we need to solve that. 

@simster7 perhaps we should default TLS on only if the .crt is found?

**Comment by simster7** [comment]
> @simster7 perhaps we should default TLS on only if the .crt is found?

I believe that we should have TLS on regardless and require user action (e.g. adding the flag) to turn it off (based on ToB feedback, the user should be aware that they are running in insecure mode).

**Comment by sbose78** [comment]
Generally, I like the "secure by default, non-secure as an opt-in" approach.

**Comment by sbose78** [comment]
( I apologize for my ignorance )

Is generating / shipping self signed certificates an option?

**Comment by alexec** [comment]
I think the problem here is when you run as `argo server` locally, e.g on your MacBook. The files do not exist as they are only bundled with the image, not the binary.

This creates unneeded friction for desktop users as they must either: `--secure-false`,  `env ARGO_SECURE=false`, or create their own .crt/.key using `openssl`. 

If you're running `argo server` on your desktop, it does not need to be secure. The HTTP requests are not leaving the host.

So lets run insecure by default on desktop.

How do we know we are on a desktop not in a Docker container?

**Comment by alexec** [comment]
The more I think about this, the more I think we should detect the .crt and base default secure on that.

* If the file is not found. We default to insecure. This works for desktop. If a bug appears, in Kubernetes the readiness check is HTTPS and will fail, so we are protected.
* If the file is found, we default to secure.
* If there is a permission error reading the file, then we should error.

**Comment by simster7** [comment]
This is now fixed in [`v3.0.0`](https://github.com/argoproj/argo-workflows/releases/tag/v3.0.0)

**Comment by aido93** [comment]
@simster Thank you for your comment. I spent 2 hours for changing "--secure false" to "--secure=false"
