### ISSUE TITLE
You have to delete sample workflow twice to submit a workflow via the ui

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5493]
## Summary 

1. Go to the workflows tab in the UI
2. Click 'Submit new workflow'
3. Click 'Edit using full workflow options'
4. Select all on the sample workflow yaml and press delete

issue:
The sample is not deleted.

Workaround:

1. Perform the steps above
2. Select all on the sample workflow a second time and press delete.

This time the sample is removed.

This is an issue because if you're running on autopilot, you end up pasting your required workflow into the box, but the past doesn't 'stick' and you end up running the sample workflow.

This occurs in both Chrome and Firefox (v86 and 89 respectively) on a Mac.

## Diagnostics

What Kubernetes provider are you using? EKS 1.19

What version of Argo Workflows are you running? 3.0 rc8

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you please try `argoproj/argocli:dev-ui`?

**Comment by tim-sendible** [comment]
@alexec I'm not having much luck with that build. I briefly got errors like "failed to load version information" and I briefly saw a certificate error, but now just getting completely blank pages. Same in incognito or a browser I don't commonly use. No shouty things in the server logs though.

I can't get to the point of re-creating the issue to prove that it is fixed.

**Comment by alexec** [comment]
Ah. New version of the CLI default to `--secure=true` can you try with `--secure=false`?

**Comment by tim-sendible** [comment]
Sorry @alexec, with that flag set, the server's readiness probe fails. I can start hacking away at the readiness probe too if really necessary?

**Comment by alexec** [comment]
ah - temporarily remove the readiness check?

**Comment by tim-sendible** [comment]
So I removed the readiness check, and disabled backend-protocol: HTTPS in my ingress.

I got the same blank page after doing all that.
