### ISSUE TITLE
Label choices aren't remembered

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5496]
## Summary 

1. Go to /workflows and choose a valid label and namespace. Filter your results by this label.
2. Click onto the archived workflows tab
3. Click back to /workflows

**issue:**
The namespace is retained, but the selected label is not.

This also occurs on the /archived-workflows view.

## Diagnostics

What Kubernetes provider are you using? EKS 1.19

What version of Argo Workflows are you running? 3.0 rc8

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
This has been fixed in [`v3.0.0-rc9`](https://github.com/argoproj/argo-workflows/releases/tag/v3.0.0-rc9)
