### ISSUE TITLE
Internal Server error... write: broken pipe

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5508]
## Summary 

I'll be honest, this is a tough one to reproduce. After 24-48 hours of running, our argo-servers start throwing logs with this repeated over and over again:

```
time="2021-03-25T10:01:09.560Z" level=error msg="finished unary call with code Unknown" error="write tcp 172.21.3.115:50542->172.21.2.20:5432: write: broken pipe" grpc.code=Unknown grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-03-25T10:01:0
```

From a UI perspective, no users can see any workflows, they just see this error at the top of the screen:
![image](https://user-images.githubusercontent.com/69461449/112455893-0d9a9000-8d52-11eb-889f-7b06c0338d86.png)

The only fix we have found is to kill the argo-server pods and let them recreate themselves.

## Diagnostics

What Kubernetes provider are you using? EKS-1.19

What version of Argo Workflows are you running? 3.0 rc9

We are using SSO to gihub (via argocd)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tim-sendible** [comment]
This just happened again. The server pods had been up for 25h

**Comment by alexec** [comment]
Are you able to indicate what the two IPs are?

**Comment by alexec** [comment]
Postgres?

**Comment by tim-sendible** [comment]
hmm that would have been helpful wouldn't it?

Definitely not postgres, that's hosted externally to the cluster. I imagine it's just the other pods in the argo namespace (we run 2 servers and one controller). Next time it dies I'll trace the IPs.

**Comment by tim-sendible** [comment]
Ah, you might be right to a degree...

So we use EKS and use an RDS Postgres db. To access the postgres DB, the pod gets allocated a secondary IP address - that's probably the one with :5432 on it. Summarised here: https://aws.amazon.com/blogs/containers/introducing-security-groups-for-pods/

So it's likely that both IP addresses are for the pod that's complaining. But I will confirm next time it happens.

**Comment by alexec** [comment]
So we're probably getting disconnected and not reconnected. No other users have complained about this, and this code is >= 1y6m old. I expect it *maybe* something specific with your set-up. Do you know if RDS drops connections?

**Comment by tim-sendible** [comment]
It's not something I'm aware of but I will increase monitoring and get back to you.

**Comment by tim-sendible** [comment]
Your assumption was correct. RDS was helpfully disconnecting. I believe I have addressed this now, even if I haven't, the database is at fault, not argo-workflows. Thanks.

**Comment by ammggm** [comment]
> Your assumption was correct. RDS was helpfully disconnecting. I believe I have addressed this now, even if I haven't, the database is at fault, not argo-workflows. Thanks.

Quick question what did you change on your DB side to fix this?

**Comment by afilipchik** [comment]
@alexec We are expiriencing a similar issue. Our connection to Postgres is routed via service mesh and looks like the connection is periodically killed. 

I know that a lot of postgres drivers can re-establish a connection, any reason it is not happening in our case. The error is: ```broken pipe```
