### ISSUE TITLE
failed to save outputs: fork/exec /usr/local/bin/docker: exec format error

### ISSUE THREAD

**Issue by xybuty** [argoproj/argo-workflows#5509]
## Summary 

What happened/what you expected to happen?
The issue was occured when I use Kubeflow pipeline ,but I haven't got helpful information in KFP information.
And the pod logs seem to be relationship with argo ,so I look forward to help here.
## Diagnostics

What Kubernetes provider are you using? 
v1.19.4
What version of Argo Workflows are you running? 
argo-v2.30
```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} ```
This is my task's yaml, it very simple
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sequential-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.1.2, pipelines.kubeflow.org/pipeline_compilation_time: '2021-03-24T15:50:01.671188',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A pipeline with two sequential
      steps.", "name": "Sequential pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.1.2}
spec:
  entrypoint: sequential-pipeline
  templates:
  - name: echo
    container:
      args: [echo "$0", '{{inputs.parameters.write-output}}']
      command: [sh, -c]
      image: library/bash:4.4.23
    inputs:
      parameters:
      - {name: write-output}
  - name: sequential-pipeline
    dag:
      tasks:
      - name: echo
        template: echo
        dependencies: [write]
        arguments:
          parameters:
          - {name: write-output, value: '{{tasks.write.outputs.parameters.write-output}}'}
      - {name: write, template: write}
  - name: write
    container:
      args: [echo "$0" >> "$1", good evening, /results.txt]
      command: [sh, -c]
      image: library/bash:4.4.23
    outputs:
      parameters:
      - name: write-output
        valueFrom: {path: /results.txt}
      artifacts:
      - {name: write-output, path: /results.txt}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
```


```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```
![image](https://user-images.githubusercontent.com/44302306/112457668-f03be500-8d96-11eb-9177-3246629f3abc.png)
```
time="2021-03-25T17:53:49Z" level=error msg="executor error: fork/exec /usr/local/bin/docker: exec format error\ngithub.com/argoproj/argo/errors.Wrap\n\t/go/src/github.com/argoproj/argo/errors/errors.go:88\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/go/src/github.com/argoproj/argo/errors/errors.go:71\ngithub.com/argoproj/argo/workflow/common.RunCommand\n\t/go/src/github.com/argoproj/argo/workflow/common/util.go:397\ngithub.com/argoproj/argo/workflow/executor/docker.(*DockerExecutor).Wait\n\t/go/src/github.com/argoproj/argo/workflow/executor/docker/docker.go:95\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).Wait\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:867\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:32\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/spf13/cobra/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/spf13/cobra/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/spf13/cobra/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"
```


---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
v2.3 is not supported anymore. Can you please upgrade and try again.

**Comment by xybuty** [comment]
> v2.3 is not supported anymore. Can you please upgrade and try again.

May I ask the version correspondence between argo and pipeline?

**Comment by terrytangyuan** [comment]
> > v2.3 is not supported anymore. Can you please upgrade and try again.
> 
> 
> 
> May I ask the version correspondence between argo and pipeline?

This would be a question to ask the maintainers of KFP instead.
