### ISSUE TITLE
`TestRetriesVariableInPodSpecPatch` broken on `master`?

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5526]
@dinever ?

**Comment by dinever** [comment]
Let me see

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/actions/workflows/ci-build.yaml?query=branch%3Amaster

**Comment by dinever** [comment]
Hi @alexec, could you point me to a build in which `TestRetriesVariableInPodSpecPatch` fails? I checked several builds and the case seems to have passed. Thanks!

**Comment by alexec** [comment]
Maybe it is flakey. Lets just monitor for now.
