### ISSUE TITLE
make codegen failed

### ISSUE THREAD

**Issue by lowc1012** [argoproj/argo-workflows#5532]
## Summary 
Hello, I am new here. I would like to join and contribute to this awesome project but I don't know much about development in GO.

I watched the contributor workshop [vedio](https://www.youtube.com/watch?v=zZv0lNCDG9w) and followed instructions. I have a problem with "make codegen" command locally.

<img width="1172" alt="IMG" src="https://user-images.githubusercontent.com/52355146/112752600-642ff480-9006-11eb-98f0-7c790fd0e02e.png">

Then, I retried "make codegen", it succeeded.
I am not sure if there is something wrong with my environment or a bug.

<img width="748" alt="IMG2" src="https://user-images.githubusercontent.com/52355146/112753936-62692f80-900c-11eb-81f0-e9888ff0e57b.png">

## Diagnostics

tag: release-3.0
macOS Mojave 10.14.6
go version go1.15.10 darwin/amd64
libprotoc 3.6.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you ask for help in #argo-dev please?
