### ISSUE TITLE
Error to access UI using port-forward

### ISSUE THREAD

**Issue by danilorsilva** [argoproj/argo-workflows#5539]
## Summary 

Error when i try to access UI using port-forward

## Diagnostics

What Kubernetes provider are you using?

GKE 1.18.15

What version of Argo Workflows are you running? 

Latest - Using namespaced installation

LOG:

When i try to access:

```
https://localhost:2746

Service Unavailable: connection error: desc = "transport: authentication handshake failed: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0"
```

```
http://localhost:2746

Do not work
```

**Comment by alexec** [comment]
try starting using `--secure=false`

**Comment by danilorsilva** [comment]
Thanks @alexec 

I need to set --secure=false, --auth-mode=server and change de readness probe from https to http.

**Comment by alexec** [comment]
` Service Unavailable: connection error: desc = "transport: authentication handshake failed: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0"`

**Comment by alexec** [comment]
https://github.com/jaegertracing/jaeger/issues/2435

**Comment by alexec** [comment]
https://github.com/golang/go/issues/39568#issuecomment-671424481
