### ISSUE TITLE
Allow us to customize the sso logout timer

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5545]
# Summary

If you have SSO set up, you get logged out after 24 hours (possibly before, but I do sleep somtimes!). This is frustrating for our end users who are used to tools of this nature remembering their credentials for a long time after logging in.

However, I appreciate that some companies will have security requirements that mandate that users are logged out more frequently.

An option in the workflow controller configmap (under sso:) to choose the timeout time would be ideal. An option to never expire would also be useful.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This is possible already in >= 2.12:

https://github.com/argoproj/argo-workflows/commit/4bacbc121ae028557b7f0718f02fbb25e8e63850

But it is not documented, would you like to add it? 

@arghya88 FYI

**Comment by tim-sendible** [comment]
oh nice. Yes, I'll document that.

**Comment by alexec** [comment]
Closing.
