### ISSUE TITLE
Widgets help link goes to the wrong url

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5547]
## Summary 

1. Go to a running workflow
2. Click the 'share' button
3. Scroll down to "Widgets not loading? Check for solutions in the docs."
4. The link goes to https://argoproj.github.io/argo/widgets

As you don't have a global redirect in place, this doesn't link to the new repo name

## Diagnostics

What Kubernetes provider are you using? EKS 1.19

What version of Argo Workflows are you running? 3.0rc9

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This is a small fix, would you like to contribute? It would just be a search and replace of `argoproj.github.io/argo/` for ` argoproj.github.io/argo-workflows`.
