### ISSUE TITLE
Allow for epoch time in links

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5557]
# Summary

I want to be able to add a link on the workflows screen along these lines:
`https://randomtool.mycompany.biz/wibble?start=${status.startedAt}&end=${status.endedAt}&workflow=${metadata.name}`

However, I need the date format to be in unix epoch (because this is what the tool accepts), not standard date format.

Being able to do something like this would be ideal:
`https://randomtool.mycompany.biz/wibble?start=${status.startedAt | unixEpoch}&end=${status.endedAt | unixEpoch}&workflow=${metadata.name}`

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Seems like sprig [supports](https://masterminds.github.io/sprig/date.html) these types of functions. I'll make sure you're able to use them with [expression variables](https://github.com/argoproj/argo-workflows/blob/master/docs/variables.md#expression). Note, however, that expression variables are a v3.1 feature

**Comment by andrewgeller** [comment]
I just ran into this as well trying to link into Grafana which seems like a common use case. Unfortunately, it seems Grafana's query parameter date parsing is still limited to what was done for this issue https://github.com/grafana/grafana/issues/787 and it only parses https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/services/TimeSrv.ts#L85.
