### ISSUE TITLE
Adding an annotation to a cron via ui also adds a label with the same name

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5558]
## Summary 

1. Add a cron workflow
2. Go to the Workflow Metadata tab of that cron workflow in the ui
3. Enter an annotation name and value  eg  `test: issue` and hit enter

issue: both the annotations and the labels fields are populated. The manifest is updated to reflect this.

## Diagnostics

What Kubernetes provider are you using? EKS 1.19

What version of Argo Workflows are you running?  3.0 (GA)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I was unable to reproduce this issue.

**Comment by tim-sendible** [comment]
Agreed. This does seem to have fixed itself in 3.0.1
