### ISSUE TITLE
Can't kubectl get a pod that wasn't created by argo-workflows

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5566]
## Summary 

1. Manually deploy a pod to your cluster (I'll use a deployment so that we get a random pod name):  `kubectl create deployment nginx --image=nginx -n ci`
2. Create a simple workflow to get the pod and determine the name:

```yaml
metadata:
  generateName: wibble-
  namespace: ci
spec:
  entrypoint: main
  templates:
    - name: main
      resource:
        action: get
        manifest: |
          apiVersion: v1
          kind: Pod
          metadata:
            labels:
              app: nginx
            namespace: ci
      outputs:
        parameters:
        - name: pod_name
          valueFrom:
            jsonPath: '{.metadata.name}'
```

When you run this, it fails...
`level=error msg="`[kubectl get Pod./ -o jsonpath={.metadata.name} -n ci]` stderr:\nerror: arguments in resource/name form must have a single resource and name\n"`

It seems that it's appending `./` to `get Pod`, which causes kubectl to cry.

It also seems to be ignoring my label selector.

This doesn't work for the scenario I need this for, but If I were to use workflows to create the deployment, then everything works as expected... so it's something to do with the `get` command here.

## Diagnostics

What Kubernetes provider are you using? EKS 1.19

What version of Argo Workflows are you running? 3.0(GA)

Paste a workflow that reproduces the bug, including status:
```yaml
metadata:
  name: wibble-hmqhx
  generateName: wibble-
  namespace: ci
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/ci/workflows/wibble-hmqhx
  uid: 844ae194-1ff6-4738-b06d-d1c263ee4b56
  resourceVersion: '37298024'
  generation: 3
  creationTimestamp: '2021-04-01T07:43:35Z'
  labels:
    workflows.argoproj.io/completed: 'true'
    workflows.argoproj.io/creator: Cgg2OTQ2MTQ0ORIGZ2l0aHVi
    workflows.argoproj.io/phase: Failed
    workflows.argoproj.io/workflow-archiving-status: Archived
  managedFields:
    - manager: argo
      operation: Update
      apiVersion: argoproj.io/v1alpha1
      time: '2021-04-01T07:43:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:workflows.argoproj.io/creator': {}
        'f:spec':
          .: {}
          'f:arguments': {}
          'f:entrypoint': {}
          'f:templates': {}
        'f:status': {}
    - manager: workflow-controller
      operation: Update
      apiVersion: argoproj.io/v1alpha1
      time: '2021-04-01T07:43:45Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            'f:workflows.argoproj.io/completed': {}
            'f:workflows.argoproj.io/phase': {}
            'f:workflows.argoproj.io/workflow-archiving-status': {}
        'f:spec':
          'f:activeDeadlineSeconds': {}
          'f:nodeSelector': {}
          'f:podGC': {}
          'f:retryStrategy': {}
          'f:serviceAccountName': {}
          'f:ttlStrategy': {}
          'f:volumeClaimGC': {}
        'f:status':
          'f:artifactRepositoryRef': {}
          'f:conditions': {}
          'f:finishedAt': {}
          'f:message': {}
          'f:nodes': {}
          'f:phase': {}
          'f:progress': {}
          'f:resourcesDuration': {}
          'f:startedAt': {}
spec:
  templates:
    - name: main
      inputs: {}
      outputs:
        parameters:
          - name: pod_name
            valueFrom:
              jsonPath: '{.metadata.name}'
      metadata: {}
      resource:
        action: get
        manifest: |
          apiVersion: v1
          kind: Pod
          metadata:
            labels:
              app: nginx
            namespace: ci
  entrypoint: main
  arguments: {}
  serviceAccountName: argo-workflows
  nodeSelector:
    eks.amazonaws.com/nodegroup: spot-nodes
  ttlStrategy:
    secondsAfterCompletion: 3600
  activeDeadlineSeconds: 3600
  podGC:
    strategy: OnWorkflowCompletion
  volumeClaimGC:
    strategy: OnWorkflowCompletion
  retryStrategy:
    limit: 3
    retryPolicy: OnError
status:
  phase: Failed
  startedAt: '2021-04-01T07:43:35Z'
  finishedAt: '2021-04-01T07:43:45Z'
  progress: 1/1
  message: 'Error (exit code 1): exit status 1'
  nodes:
    wibble-hmqhx:
      id: wibble-hmqhx
      name: wibble-hmqhx
      displayName: wibble-hmqhx
      type: Retry
      templateName: main
      templateScope: local/wibble-hmqhx
      phase: Failed
      message: 'Error (exit code 1): exit status 1'
      startedAt: '2021-04-01T07:43:35Z'
      finishedAt: '2021-04-01T07:43:45Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 0
      children:
        - wibble-hmqhx-3458419164
    wibble-hmqhx-3458419164:
      id: wibble-hmqhx-3458419164
      name: wibble-hmqhx(0)
      displayName: wibble-hmqhx(0)
      type: Pod
      templateName: main
      templateScope: local/wibble-hmqhx
      phase: Failed
      message: 'Error (exit code 1): exit status 1'
      startedAt: '2021-04-01T07:43:35Z'
      finishedAt: '2021-04-01T07:43:37Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 0
  conditions:
    - type: PodRunning
      status: 'False'
    - type: Completed
      status: 'True'
  resourcesDuration:
    cpu: 0
    memory: 0
  artifactRepositoryRef:
    default: true

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
The `./` you are seeing is just that the way we log that can be certainly improved. For example, here's a successful one if we just try to match with a specific pod name instead:

`time="2021-04-01T13:15:31.129Z" level=info msg="[kubectl get Pod./nginx-f89759699-pt7cf -o jsonpath={.metadata.name} -n argo]"
time="2021-04-01T13:15:31.244Z" level=info msg="Saved output parameter: pod_name, value: nginx-f89759699-pt7cf"`

So the main issue here seems to be that the label selector is not effective.

**Comment by terrytangyuan** [comment]
Looks like `kubectl get -f` only supports identifying resources by name? From their help doc:

```
# List a pod identified by type and name specified in "pod.yaml" in JSON output format.
kubectl get -f pod.yaml -o json
```

```
kubectl get -f pod.yaml -o json
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "labels": {
            "app": "nginx",
        },
        "namespace": "argo"
    }
}
```
which doesn't return the actual json object for the pod.

**Comment by terrytangyuan** [comment]
We can perhaps try support this by locating the pod name using the labels first (e.g. `kubectl get pods -l app=nginx -n argo -o jsonpath='{.items[*].metadata.name}'`) before we try to save the resource parameters or at least improve the error message. 

In the meantime, it's probably easier to use a script template that contains `kubectl` commands directly so you can manipulate the output in a more flexible way.

**Comment by tim-sendible** [comment]
Yeah, I have a workaround using a kubectl container at the moment, but I thought it was an interesting use case that doesn't seem to be handled.

**Comment by terrytangyuan** [comment]
> Yeah, I have a workaround using a kubectl container at the moment, but I thought it was an interesting use case that doesn't seem to be handled.

Actually the resource template is only supposed to operate on a single resource so I don't think it makes sense to support label selectors that might return multiple objects (which we may also need to provide meaningful error messages).

**Comment by tim-sendible** [comment]
Commenting to confirm that this is still an issue.

**Comment by terrytangyuan** [comment]
As I mentioned previously, currently resource template is only designed to work with a single resource. In other words, getting a list of pods via label selector is not supported.

**Comment by tim-sendible** [comment]
I understand. I was prodding the stalebot because at a minimum the docs need to reflect this.

**Comment by terrytangyuan** [comment]
That makes sense. Sent https://github.com/argoproj/argo-workflows/pull/6125 to reflect this.
