### ISSUE TITLE
archive workflow got duplicate entry error

### ISSUE THREAD

**Issue by book987** [argoproj/argo-workflows#5567]
## Summary 

There were some workflows already archived but still labeled archive-status pending. After that every resync period the controller archiving these workflows got duplicate entry error from db. 

I don't know why these workflows' labels didn't changed ( maybe some delete/restart workflow-controller operations cause this ). But the duplicate entry issue is controller [doesn't cleanup before insert](https://github.com/argoproj/argo-workflows/blob/master/persist/sqldb/workflow_archive.go#L113) into `argo_archived_workflows_labels`, it should acts like previous, [cleanup existing archived workflow before insert](https://github.com/argoproj/argo-workflows/blob/master/persist/sqldb/workflow_archive.go#L86) into `argo_archived_workflows`

## Diagnostics

What version of Argo Workflows are you running? 
v3.0.0

logs, with environment variable `UPPERIO_DB_DEBUG=1`:
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/17219814/113278338-664ec780-9314-11eb-9998-fd20c36a4b64.png">

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by book987** [comment]
similar with #2427, it leads to a fix which clean up archived workflow before insert

**Comment by alexec** [comment]
We should already tolerate duplicate entries to prevent this exact issue. If archiving happens, but there is a duplicate entry, the work should get marked as archived. 

Did the workflows stay in pending state?

**Comment by alexec** [comment]
I've just reviewed the code, and I was wrong.
