### ISSUE TITLE
Port forwarding not connecting to the server

### ISSUE THREAD

**Issue by mhensley-cls** [argoproj/argo-workflows#5572]
## Summary 

Port Forwarding to fresh server install not working.

## Diagnostics

What Kubernetes provider are you using? 

`On Prem - v1.20.2`

What version of Argo Workflows are you running?  `argoproj/argocli:v3.0.0`

```yaml
kubectl -n argo port-forward deployment/argo-server 2746:2746
Forwarding from 127.0.0.1:2746 -> 2746
Forwarding from [::1]:2746 -> 2746
Handling connection for 2746
Handling connection for 2746


## When attempting to connect to a different port on my laptop
kubectl -n argo port-forward deployment/argo-server 3006:2746
Forwarding from 127.0.0.1:3006 -> 2746
Forwarding from [::1]:3006 -> 2746
Handling connection for 3006
Handling connection for 3006
```

Port forwarding works for other deployments /services.

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

###
### No issues running workflows
###
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Yup! We're aware of this issue. Working on it right now.

Workaround is to use `--secure=false` when starting `argo server` and connecting via HTTP. You might have to also change your readiness checks.

**Comment by mhensley-cls** [comment]
Ahh, thanks @simster7 . I scanned over #5539 and didn't make the connection that `argo server --secure=false` was the temp workaround for the time being. (coffee hasn't kicked in yet)

![image](https://user-images.githubusercontent.com/76120104/113310841-a727eb80-92d6-11eb-92b2-0f49f220fb84.png)

**Comment by alexec** [comment]
Can be closed.

**Comment by simster7** [comment]
@mhensley-cls Are you able to test a potential fix for this issue? If so, try: `argoproj/argocli:dev-ensure-certs-fixed`. You will probably have to “Proceed Anyway” when your browser complains about self-signed certs.
