### ISSUE TITLE
Issue installing Argo v3.0.0

### ISSUE THREAD

**Issue by Atharex** [argoproj/argo-workflows#5573]
## Summary 

What happened/what you expected to happen?
Wanted to try Argo v3.0.0 installation, but I get a Service Unavailable error.

## Diagnostics

What Kubernetes provider are you using? 
Local kubeadm installation v1.19.7

What version of Argo Workflows are you running? 
v3.0.0

I've followed the standard install instructions

```
kubectl create namespace argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/v3.0.0/manifests/install.yaml 
kubectl port-forward svc/argo-server -n argo 2746:2746
```

Then I get the following error on `https://localhost:2746`
![argo-error-1](https://user-images.githubusercontent.com/2872241/113309961-fdf9e900-9307-11eb-9834-8802bf75f74b.png)

And if I move to the tab for Workflows, I get a different error message, mentioning a certificate problem:
![argo-error-2](https://user-images.githubusercontent.com/2872241/113310271-57faae80-9308-11eb-9506-263262dbd7e8.png)

 
Am I missing some certificate configuration during installation?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This is fixed in v3.0.1

**Comment by Atharex** [comment]
Ok, will wait for v3.0.1 then :+1:

**Comment by Atharex** [comment]
#5572 was slightly faster posting about this issue. Can confirm the workaround mentioned there works!
![argo-works](https://user-images.githubusercontent.com/2872241/113311780-f1769000-9309-11eb-893b-fe468b27f1f8.png)
