### ISSUE TITLE
ARGO_SECURE is not taken into account

### ISSUE THREAD

**Issue by sylock** [argoproj/argo-workflows#5607]
## Summary 

When trying to disable the TLS functionnality of argo server, the documentation says you have 2 options:
* pass an argument --secure=false
* set an environment variable ARGO_SECURE=false

Since argo v3.0.0 the defaults is to enable TLS by default. I can revert to plain text using --secure=false but setting the ARGO_SECURE environement variable has absolutely no effect.

## Diagnostics
```
$ oc version
Client Version: 4.7.2
Server Version: 4.5.5
Kubernetes Version: v1.18.3+08c38ef
```
```
argo v3.0.1 (manifest and image)
```
To reproduce: set the environement variable ARGO_SECURE=false to the deployment and check the log of the server POD. You'll see that secure option is still to "true".

## Expected behavior
ARGO_SECURE environement variable is taken into account and set the secure option accordingly.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
workaround: `--secure=false`
