### ISSUE TITLE
Documentation says argo server does not enable TLS by default - not true anymore since v3.0.0

### ISSUE THREAD

**Issue by sylock** [argoproj/argo-workflows#5608]
# Summary

In the documentation it is said that argo server is plain text by default: https://argoproj.github.io/argo-workflows/tls/#plain-text
This is not the case anymore since v3.0.0

# Expected

Inform the argo users that
* this behavior has changed since v3.0.0 and TLS is enabled by default
* explain how to revert to TLS disabled with:
  *  --secure=false
  * env ARGO_SECURE=false - but not working currently, see #5607
  * changing the readinessProbe/httpGet/scheme to HTTP
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Would you like to submit a PR to correct this.
