### ISSUE TITLE
Documentation should have a version selector

### ISSUE THREAD

**Issue by sylock** [argoproj/argo-workflows#5609]
# Summary

There are more and more differences of behavior and options between the versions of argo. Like a lot of other projects, it would be of great help if the documentation would have a list selector with the available versions of argo. And thus loading the documentation related to the chosen version (for example, selecting v3.0.0 would show me the doc about the key-only artifact, but selecting the v2.12.7 would not).
I'm talking about the documentation here: https://argoproj.github.io/argo-workflows

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sujaykulkarn** [comment]
Hi @alexec, @sylock I am interested to contribute to this issue, I want to know the approach to support this enhancement. Thanks

**Comment by abrennan89** [comment]
I think ya'll are using Mkdocs, which has a feature for this already: https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/

**Comment by agilgur5** [comment]
This has been completed as part of #11390. Marking this as duplicate since that issue has a ton more details
