### ISSUE TITLE
Outdated links in Argo blog tutorial

### ISSUE THREAD

**Issue by simonbonnefoy** [argoproj/argo-workflows#5623]
# Summary

Several links seem to be outdated in the [Argo tutorial](https://admiralty.io/blog/2019/01/17/running-argo-workflows-across-multiple-kubernetes-clusters)m or the config seems not to be working. Here is how I replaced them in order to get everything to work.

# Use Cases
Replace:
* [Argo installation](https://raw.githubusercontent.com/argoproj/argo/v2.2.1/manifests/install.yaml) by [Argo installation](https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/install.yaml)
* [Admiralty service account](https://raw.githubusercontent.com/admiraltyio/multicluster-scheduler/master/config/samples/argo-workflows/_service-account.yaml) by [Admiralty service account](https://raw.githubusercontent.com/admiraltyio/admiralty/master/examples/argo-workflows/_service-account.yaml)
* [Admiralty examples argo folder](https://raw.githubusercontent.com/admiraltyio/multicluster-scheduler/master/config/samples/argo-workflows/blog-scenario-a-singlecluster.yaml) by [Admiralty example argo folder](https://raw.githubusercontent.com/admiraltyio/admiralty/master/examples/argo-workflows/blog-scenario-a-singlecluster.yaml) for all the examples.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Should probably contact the author of that blog post or file an issue to https://github.com/admiraltyio/admiralty instead?

**Comment by alexec** [comment]
We can't fix this. As @terrytangyuan , you must speak to Admiralty.

**Comment by simonbonnefoy** [comment]
Sorry for that! I was tired and post it on Argo instead of Admiralty repo.
Sorry!
