### ISSUE TITLE
Workflow controller v3 fails to start on OpenShift 3.11

### ISSUE THREAD

**Issue by tobisinghania** [argoproj/argo-workflows#5638]
## Summary 

When tying to upgrade to Argo workflows 3, startup of the workflow controller on OpenShift 3.11 failes, because the underlying api for leader election is not available.

A configuration for disabling leader election might mitigate the situation.

## Diagnostics

What Kubernetes provider are you using? 

OpenShift 3.11 which is running on Kubernetes 1.11

What version of Argo Workflows are you running? 

v3.0.1

The issue can be reproduced by running the default [namespace install manifest](https://github.com/argoproj/argo-workflows/blob/v3.0.1/manifests/namespace-install.yaml)

```
E0409 12:01:04.539406       1 leaderelection.go:329] error initially creating leader election record: the server could not find the requested resource (post leases.coordination.k8s.io)
time="2021-04-09T12:01:09.671Z" level=info msg="Get leases 404"
time="2021-04-09T12:01:09.672Z" level=info msg="Create leases 404"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you please run `kubectl api-resources|grep leases` and attach the result?

**Comment by alexec** [comment]
Can you also Google "OpenShift coordination API" / speak to your OpenShift contacts and ask for their advice or documentation of this feature.

Once you've confirm if they do not support this API, then you'll have confirmed that OpenShift that Leader Election/HA is not supported on v3.

If that is the case, can you please submit a PR to support a `LEADER_ELECTION_IDENTITY=off` configuration option? Code changes will need to be made here:

https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/controller.go#L225

**Comment by tobisinghania** [comment]
The `grep` command returns nothing and indeed it seems that the required kubernetes coordination.k8s.io api was introduced in 1.14.
In the 1.14 change log I found this `The Lease API type in the coordination.k8s.io API group is promoted to v1`

OpenShift 3.11 is using Kubernetes 1.11, so it makes sense this is not working.

[https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md)

Thanks for pointing out where this can be fixed....I'll try on the weekend if I'm able to get things set up.

**Comment by alexec** [comment]
Thank you for helping!

**Comment by vbarbaresi** [comment]
I'm trying this fix to run Argo Workflows v3 on a cluster running in version < 1.14
I set the environment variable

I found out 2 issues:

- It still tries to start leading and will fails to get leases. It seems this cause the controller to never be in a processing state
```
time="2021-04-21T12:35:38.543Z" level=info msg="Manager initialized successfully"
I0421 12:35:38.543556       1 leaderelection.go:243] attempting to acquire leader lease  mynamespace/workflow-controller...
time="2021-04-21T12:35:38.545Z" level=info msg="Get leases 404"
time="2021-04-21T12:35:38.547Z" level=info msg="Create leases 404"
E0421 12:35:38.547373       1 leaderelection.go:329] error initially creating leader election record: the server could not find the requested resource (post leases.coordination.k8s.io)
time="2021-04-21T12:35:49.334Z" level=info msg="Get leases 404"
time="2021-04-21T12:35:49.336Z" level=info msg="Create leases 404"
E0421 12:35:49.336784       1 leaderelection.go:329] error initially creating leader election record: the server could not find the requested resource (post leases.coordination.k8s.io)
```
I think when the leader election is disabled, we shouldn't try to start leading:
https://github.com/argoproj/argo-workflows/blob/e3d1d1e822c01e2765bab2d57d9537849cd0f720/workflow/controller/controller.go#L229

- The liveness probe fails because the metric server is not started
So the workflow-controller is killed every minute and ends up in CrashLoopBackOff state
I think this comes from issue https://github.com/argoproj/argo-workflows/issues/5525
I saw the issue wasn't cherry-picked in v3.0.2 so it may explain that
It's probably a consequence of the first issue anyway

**Comment by joyciep** [comment]
I also encountered the same issue as @vbarbaresi in Openshift 3.11 (Argo v3.0.2). 

```
time="2021-04-22T08:23:06.630Z" level=info msg="Get leases 404"
time="2021-04-22T08:23:06.631Z" level=info msg="Create leases 404"
E0422 08:23:06.631986       1 leaderelection.go:329] error initially creating leader election record: the server could not find the requested resource (post leases.coordination.k8s.io)
```

**Comment by alexec** [comment]
@sarabala1979 didn't this get fixed?

**Comment by joyciep** [comment]
Any updates on this?

**Comment by alexec** [comment]
I think you need to set LEADER_ELECTION_IDENTITY=off.

**Comment by joyciep** [comment]
> I think you need to set LEADER_ELECTION_IDENTITY=off.

I already set `LEADER_ELECTION_IDENTITY` to `off` and `LEADER_ELECTION_DISABLE` to `true` and I still encountered the same error.

**Comment by vbarbaresi** [comment]
I tested with the `latest` image this time, and setting `LEADER_ELECTION_DISABLE=true` worked for me this time
I previously tested on `v3.0.2` but `LEADER_ELECTION_DISABLE` wasn't released on this version

**Comment by alexec** [comment]
We should backport the fix.

**Comment by alexec** [comment]
@sarabala1979 this did not appear to get back-ported to v3.0.2 - can you please make sure it makes it into v3.0.3. Commits are:

e3d1d1e822c01e2765bab2d57d9537849cd0f720
4c3b0ac530acaac22abb453df3de09e8c74068fb

**Comment by alexec** [comment]
@lucastheisen would you like to supply the updated manifests needed to run it in a PR?

**Comment by lucastheisen** [comment]
@alexec I would...  As soon as I figure it out.  We are stuck on the `lease` thing.  Any chance you could explain a little about what leases add, why needed and if you understand the implication of allowing namespace `admin` role to have the required permissions for creating the role/binding?  Our research seems to indicate that granting the perms shouldn't be bad, but we might be missing some detail here...

**Comment by alexec** [comment]
Leases are used for controller HA. If v3.0.3 you can disable them by setting `LEADER_ELECTION_DISABLE=true`

**Comment by lucastheisen** [comment]
Was just about to say:

> 3.0.3 is _not yet released_, right?

Looks like you released it 29 minutes ago...  Ill give that a go.

**Comment by lucastheisen** [comment]
Looks like `events` results in a similar permissions conundrum.  Investigating, but is events also something that can be tuned out?  If i understand correctly its a _new feature of 3.0_, but is it _integral_ (required for the old functionality to continue to work) or standalone (only required for the [`workfloweventbinding`](https://github.com/argoproj/argo-workflows/blob/master/manifests/namespace-install.yaml#L77-L110)?  Can we leave off `workfloweventbinding`?

**Comment by alexec** [comment]
`events` is a v2.x feature, and the provided manifests should already have the requisite RBAC.
