### ISSUE TITLE
SSO over Gitlab with RBAC: Groups not fetched

### ISSUE THREAD

**Issue by mruoss** [argoproj/argo-workflows#5642]
## Summary 

I have successfully configured SSO over Gitlab. On Gitlab there is no scope `groups`. However, according to the [docs](https://docs.gitlab.com/ee/integration/openid_connect_provider.html#shared-information) they are part of the `openid ` scope:

> The claims sub, sub_legacy, email and email_verified are included in the ID token, all other claims are available from the /oauth/userinfo endpoint used by OIDC clients.

Looking at the profile page in Argo, Argo seems to fail to fetch email, email_verified and groups. The latter is especially annoying because I can't configure RBAC roles based on it.

I'm not sure this is a bug or enhancement. If I understand the Gitlab doc correctly, this is common OIDC behaviour. But I could not say...

## Diagnostics

What Kubernetes provider are you using? 

GKE 

What version of Argo Workflows are you running? 

3.0.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Because `groups` is not part of the OIDC standard, they are disabled by default. You must enable them in the config map:

https://github.com/argoproj/argo-workflows/blob/master/docs/workflow-controller-configmap.yaml#L288

**Comment by mruoss** [comment]
If I do that, Gitlab returns an error (malformed scopes) during auth.

**Comment by domderen** [comment]
Hey, I'm running into the same issue, is there any workaround to figure out gitlab groups?

**Comment by mruoss** [comment]
Hi @domderen 
We have an argoCD DEX server that does SSO over Gitlab. For argo-workflows we ended up configuring SSO over that dex server instead of going directly to Gitlab. So the chain now is argo-workflows => argoCD DEX => Gitlab.

**Comment by domderen** [comment]
Hey @mruoss,

Thanks for your comment! I was hoping to avoid installing ArgoCD at the moment, as I don't have a need for it for the time being, but I guess it might be easier solution for now. Or I can just set up a DEX server. Anyways, thanks for the suggestion.

**Comment by mruoss** [comment]
In my opinion this ticket was closed prematurely (what do you think, @alexec?) But yeah, maybe you can get it working with a DEX server. For, us argoCD was already in place.
