### ISSUE TITLE
Timezone for CronWorkflow not working for all expected zones

### ISSUE THREAD

**Issue by endzyme** [argoproj/argo-workflows#5653]
## Summary

Timezone settings for CronWorkflows don't appear to work for all expected timezones. I have set a timezone of `Europe/Dublin` and the controller does not actually start the job. There are some log messages that it is processing the job but nothing appears to start. When I changed to `America/New_York` or `Europe/Paris` it appears to work. I have also tested with `Etc/GMT-1` and `Europe/Amsterdam` and same results, no worky.

## Diagnostics
What version of Argo Workflows are you running?
`v3.0.1`

I will provide logs if needed. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@simster7 ?

**Comment by simster7** [comment]
Will take a look

**Comment by alexec** [comment]
@endzyme can you please confirm if this worked in v2.12?

**Comment by alexec** [comment]
Related?

fix(controller): Fix timezone support. Fixes #5181 (#5182)

**Comment by endzyme** [comment]
> @endzyme can you please confirm if this worked in v2.12?

It did, but I'll try to spin something up this coming week to provide proof. I saw your note on the related Dockerfile change. It's likely related but I haven't fully dug into why some timezones would work and others would not.

**Comment by alexec** [comment]
```
time="2021-04-19T15:33:18.696Z" level=error msg="could not schedule CronWorkflow" cronWorkflow=argo/test-cron-wf-basic error="provided bad location Europe/Dublin: unknown time zone Europe/Dublin"
```

**Comment by alexec** [comment]
```
time="2021-04-19T15:34:45.881Z" level=error msg="could not schedule CronWorkflow" cronWorkflow=argo/test-cron-wf-basic error="provided bad location America/New_York: unknown time zone America/New_York"
```

**Comment by alexec** [comment]
https://medium.com/@mhcbinder/using-local-time-in-a-golang-docker-container-built-from-scratch-2900af02fbaf
https://stackoverflow.com/questions/47794740/gos-time-doesnt-work-under-the-docker-image-from-scratch
