### ISSUE TITLE
Manifest editor not working as expected

### ISSUE THREAD

**Issue by dinever** [argoproj/argo-workflows#5690]
## Summary 

What happened/what you expected to happen?

I'm running the latest master branch. When opening up a manifest editor. I'm expecting to see the YAML view initially.

However, the current behavior is:

1. Editor shows JSON view by default
2. On the first click, still shows JSON view, but a different highlighting
3. On the second click, shows YAML view now but broken highlighting

![editor](https://user-images.githubusercontent.com/1311594/115102159-31975e80-9f17-11eb-8174-d536a613e97d.gif)

## Diagnostics

The chrome console didn't show any error messages. I might be able to look into it later.

---
Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I think we should consider getting rid of the JSON editor:

1. It is complex and buggy.
2. I don't think it is useful to most users.

**Comment by alexec** [comment]
If we decide to do this:

1. Delete `api/jsonschema/schema.json`.
2. Remove `json` from `new MonacoWebpackPlugin({"languages":["json","yaml"]})` is ui/src/app/webpack.config.js.
3. Remove `lang` and `<ToggleButton/>` from `<ObjectEditor/>` (ui/src/app/shared/components/object-editor/object-editor.tsx)

See also #5613
