### ISSUE TITLE
Argo CLI lint command flag --kinds is broken

### ISSUE THREAD

**Issue by boonware** [argoproj/argo-workflows#5709]
## Summary 

Follopwing the documentation at https://argoproj.github.io/argo-workflows/cli/argo_lint/ is should be possible to use the `--kinds` flag with the Argo CLI `lint` command. Argo lint `--kinds` flag is broken.

## Diagnostics

Argo CLI version `2.12.11` (latest)

```sh
argo lint --kinds=workflows /dir-containing-workflows
```

```
Error: unknown flag: --kinds
Usage:
  argo lint FILE... [flags]

Flags:
  -h, --help     help for lint
      --strict   perform strict workflow validation (default true)
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
`--kind` is not yet supported in `2.12.11`. It's currently in master branch (relevant commit: https://github.com/argoproj/argo-workflows/commit/ea26a964b7dffed2fe147db69ccce5c5f542c308) so you'll have to use the version from master.
