### ISSUE TITLE
bug: Unable to switch to different namespace in Argo UI

### ISSUE THREAD

**Issue by ppapasani1** [argoproj/argo-workflows#5732]
## Summary 

What happened/what you expected to happen?

## Diagnostics

What Kubernetes provider are you using?  on-premise cluster

What version of Argo Workflows are you running? Argo v3.0.1

We have workflows running in different namespaces and there is no way to directly switch to a different namespace from UI, the namespace field is hardcoded to `default`. Should this be a drop-down with a list of namespaces?

![namespace_filter](https://user-images.githubusercontent.com/37124509/115614937-263f8c80-a2a3-11eb-8429-8e27023545ed.PNG)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
As a work-around, change the URL. Also, please try v3.0.2.

**Comment by ppapasani1** [comment]
@alexec . Yes we are going with the workaround. Even the issue exits in v3.0.2

![Screen Shot 2021-04-21 at 5 43 53 PM](https://user-images.githubusercontent.com/37124509/115639453-76c9e080-a2c9-11eb-85be-c832804dd514.png)

**Comment by alexec** [comment]
Maybe fixed by #5729

**Comment by Radolumbo** [comment]
Are you sure you aren't running the server in namespaced mode? I.E. the server has the --namespaced flag in its deployment definition? I was just testing this behavior recently, and without the --namespaced flag, that field behaves as an input.

**Comment by ppapasani1** [comment]
Yes, I have the --namespaced flag. Removing --namespaced flag allowed to edit the namespace field. Thanks. @Radolumbo

**Comment by Radolumbo** [comment]
Yep, no worries! In general, "namespaced" mode necessarily means that Workflows will only run in a single namespace for the corresponding server. A major use for this being that it allows you to have a separate server running in each namespace with isolation. If you want one server/controller that runs workflows in many namespaces, leave out "--namespaced".
