### ISSUE TITLE
workflows' manifests/base/crd missing crd from argo-events

### ISSUE THREAD

**Issue by paulvvuong** [argoproj/argo-workflows#5753]
## Summary 

In the Argo UI, when clicking on `Event Sources` or `Sensors` icon, error message will appear if the CRDs from `argo-events/manifests/base/crds/` have not been installed.

## Diagnostics

I am using AWS EKS, running v1.19 kubernetes

I just completed a fresh install of Argo Workflows v3.0.2

In the UI, these are sample error messages:
```html
Unsuccessful HTTP response: the server could not find the requested resource (get eventsources.argoproj.io)
```
```html
 Unsuccessful HTTP response: the server could not find the requested resource (get sensors.argoproj.io)
```

From the Argo server  kubelogs, these are sample error messages:
```yaml
time="2021-04-25T17:46:22.504Z" level=info msg="finished unary call with code NotFound" error="rpc error: code = NotFound desc = the server could not find the requested resource (get eventsources.argoproj.io)" grpc.code=NotFound grpc.method=ListEventSources grpc.service=eventsource.EventSourceService grpc.start_time="2021-04-25T17:46:22Z" grpc.time_ms=2.474 span.kind=server system=grpc
```
```yaml
time="2021-04-25T17:48:04.981Z" level=info msg="finished unary call with code NotFound" error="rpc error: code = NotFound desc = the server could not find the requested resource (get sensors.argoproj.io)" grpc.code=NotFound grpc.method=ListSensors grpc.service=sensor.SensorService grpc.start_time="2021-04-25T17:48:04Z" grpc.time_ms=4.163 span.kind=server system=grpc
```

Once the CRDs from argo-events are installed, the above errors goes away. [https://github.com/argoproj/argo-events/tree/master/manifests/base/crds](https://github.com/argoproj/argo-events/tree/master/manifests/base/crds)

**Comment by alexec** [comment]
You need to install these from the argo-events repository.

**Comment by alexec** [comment]
https://argoproj.github.io/argo-events/quick_start/
