### ISSUE TITLE
[FEATURE REQUEST] Multi arch support

### ISSUE THREAD

**Issue by ionutz89** [argoproj/argo-workflows#5755]
# Summary

It will be great to have docker images built as multi arch-like `amd64/arm64`. I want to use the docker containers on hardware with arm64 like RPI 4 for example.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
They are?

**Comment by ionutz89** [comment]
If you have cluster k8s on RPI 4, it will be very good to have this. I have to rebuild the image to make it compatible with arm64. Maybe a github action with a build kit will be very useful for more people. I can see the potential of this project.

**Comment by alexec** [comment]
Sorry. I mean to say we already build multi arch images of the executor. Do you need the controller too? If, would you like to submit a PR to add the build?

**Comment by ionutz89** [comment]
You are right. I had did not see clearly for the workflow it is on arm64. Apologies for inconvenience

**Comment by marcstreeter** [comment]
I actually would be willing to look into helping here, I think if at all possible it would be great to have this work 100% in RPi (and arm in general).  Could we keep this task open for those (including myself) who'd like this work to continue?

**Comment by alejoGT1202** [comment]
Hello, I've a cluster with ARM and AMD arch. nodes. Argo works as expected when an AMD arch. node is requested. However, when an ARM node is required it doesn't work and the error message I'm getting is related that it's trying to run an AMD built image in a ARM architecture. The image that is being pulled in the init container is `argo-workflow-exec:3.3.2-debian-10-r0` which is built for AMD arch, as can be seen [here](https://hub.docker.com/layers/argo-workflow-exec/bitnami/argo-workflow-exec/3.3.2-debian-10-r0/images/sha256-e1f578a01da6ba3a6c7fee0a2bb5d66b63ecbc4d9b7995913ee0a2c6d74a857f?context=explore) I was wondering if there is I way I can specify that the `argo-workflow-exec` image I want to use is built for ARM. 

Thanks for the help.
