### ISSUE TITLE
Can't scroll on the workflow summary screen

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5757]
## Summary 

Got to a running workflow (or an archived workflow if you're feeling fancy). Go to the summary screen. Attempt to scroll down.

User cannot scroll down. This only started happening from 3.0.2, 3.0.1 was fine.

## Diagnostics

Firefox 87.0 (mac)
Chrome 90 (windows)

What Kubernetes provider are you using? EKS 1.19

What version of Argo Workflows are you running? 3.0.2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I think this was fixed on latest?

**Comment by everton-nasc** [comment]
Same error on version `3.0.2` and `latest`.

Here's the image:
![Screen Shot 2021-04-29 at 4 55 03 PM](https://user-images.githubusercontent.com/58737540/116628525-8d48eb00-a90c-11eb-9b75-d68af0c91a32.png)

**Comment by dinever** [comment]
Hi, this is fixed in #5743. Will be included in the next release. Thanks!

**Comment by alexec** [comment]
This is fixed, but needs to be released in v3.0.4
