### ISSUE TITLE
Can the resume function only target a node,not target a workflow

### ISSUE THREAD

**Issue by anankun** [argoproj/argo-workflows#5763]
# Summary
Current implementation of resume targets workflow. When I have two nodes both suspend template, I just  want only one node resume to go on, other node is still suspend. Like this:

# Use Cases
![image](https://user-images.githubusercontent.com/13867253/116382331-60cb9b00-a848-11eb-9c09-b876732e9c70.png)
I have two paths both suspend, when I click resume, both of them are resume. I just want D or E to resume instead of workflow.

**Comment by alexec** [comment]
This would be a nice enhancement to the UI.

**Comment by alexec** [comment]
@anankun would you like to submit a PR to fix this?

**Comment by anankun** [comment]
> @anankun would you like to submit a PR to fix this?

Sorry，I'm beginner in go , not good at go and ts. Maybe after a while
