### ISSUE TITLE
executor error: entry not found

### ISSUE THREAD

**Issue by digibank-rons** [argoproj/argo-workflows#5764]
## Summary 

We are ruuning many repos through our Argo workflows CI and dozens work perfectly fine, just one repo produces the error -
"executor error: entry not found" in it's init container of the first step before it should fetch code

We are running on argo workflows 3.0.2 but this happened on 2.12.11 too

Workflow - 

kind: Pod
apiVersion: v1
metadata:
  name: workflow-ci-cheque-9900469pdt9x-2130972909
  namespace: argo-events
  selfLink: >-
    /api/v1/namespaces/argo-events/pods/workflow-ci-cheque-9900469pdt9x-2130972909
  uid: 16788094-03fa-485a-a329-56a2b0be9e8f
  resourceVersion: '194979934'
  creationTimestamp: '2021-04-28T12:46:59Z'
  labels:
    app: app
    workflows.argoproj.io/completed: 'true'
    workflows.argoproj.io/workflow: workflow-ci-cheque-9900469pdt9x
  annotations:
    kubernetes.io/psp: eks.privileged
    workflows.argoproj.io/execution: '{"deadline":"2021-04-28T13:16:59Z"}'
    workflows.argoproj.io/node-name: 'workflow-ci-cheque-9900469pdt9x[0].build-test-publish'
    workflows.argoproj.io/template: >-
      {"name":"build-test-publish","inputs":{"parameters":[{"name":"repo","value":"https://github.com/c/c.git"},{"name":"revision","value":"feature-test"},{"name":"image_repository","value":"ghcr.io/c/c"},{"name":"image_tag","value":"0.1.0-feature-test-9900469"},{"name":"buildcntr","value":"ghcr.io/digibank-il/gradle-14-allure-cli-ecr-login:latest"},{"name":"skip_tests","value":"false"},{"name":"gradle_cache_server_address","value":"gradle-cache.fdb-test.net"}],"artifacts":[{"name":"code","path":"/mnt/builddir/code","git":{"repo":"https://github.com/c/c.git","revision":"feature-test","usernameSecret":{"name":"github-rons","key":"username"},"passwordSecret":{"name":"github-rons","key":"password"}}}]},"outputs":{"parameters":[{"name":"tests_passed","valueFrom":{"path":"/tmp/tests.passed"},"globalName":"tests_passed"},{"name":"allure_report_generated","valueFrom":{"path":"/tmp/allureReport.generated"},"globalName":"allure_report_generated"}]},"metadata":{"labels":{"app":"app"}},"script":{"name":"","image":"ghcr.io/digibank-il/gradle-14-allure-cli-ecr-login:latest","command":["bash"],"workingDir":"/mnt/builddir/code","env":[{"name":"REPO","value":"https://github.com/c/c.git"},{"name":"DOCKER_HUB_USER","valueFrom":{"secretKeyRef":{"name":"fdb-docker-hub-secret","key":"username"}}},{"name":"DOCKER_HUB_PASS","valueFrom":{"secretKeyRef":{"name":"fdb-docker-hub-secret","key":"password"}}},{"name":"GITHUB_PACK_USER","valueFrom":{"secretKeyRef":{"name":"fdb-pack-secret","key":"uname"}}},{"name":"GITHUB_PACK_PASS","valueFrom":{"secretKeyRef":{"name":"fdb-pack-secret","key":"pass"}}}],"resources":{},"volumeMounts":[{"name":"builddir","mountPath":"/mnt/builddir"}],"source":"set
      -e\necho true \u003e /tmp/tests.passed\necho false \u003e
      /tmp/allureReport.generated\nsed -i
      's/gradle-cache\\.[a-z0-9-]*\\.[a-z0-9-]*/gradle-cache.fdb-test.net/g'
      settings.gradle.kts\necho \"############ gradle build
      ###############\"\ngradle build --build-cache -x check\nif ( ! false
      )\nthen\n  echo \"############ gradle check ###############\"\n  (gradle
      check --build-cache \u0026\u0026 echo true \u003e /tmp/tests.passed) ||
      echo false \u003e /tmp/tests.passed\n  echo \"############ gradle
      AllureReport ###############\"\n  (gradle AllureReport --build-cache
      \u0026\u0026 echo true \u003e /tmp/allureReport.generated) || echo false
      \u003e /tmp/allureReport.generated\nfi\nif ( $(cat /tmp/tests.passed) =
      'true' )\nthen\n  if (grep '^include' settings.gradle.kts \u003e\u003e
      /dev/null)\n  then\n    echo \"# Multi container project #\"\n   
      JIB_VERSION_FLAG=\"-Pversion=0.1.0-feature-test-9900469\"\n  else\n   
      echo \"# Single container project #\"\n   
      JIB_VERSION_FLAG=\"-Djib.to.image=ghcr.io/c/c:0.1.0-feature-test-9900469\"\n 
      fi\n  echo \"############ gradle jib ###############\"\n  gradle jib
      --build-cache $JIB_VERSION_FLAG \\\n   
      -Djib.to.auth.username=\"${GITHUB_PACK_USER}\"\\\n   
      -Djib.to.auth.password=\"${GITHUB_PACK_PASS}\"\\\n   
      -Djib.from.auth.username=\"${DOCKER_HUB_USER}\"\\\n   
      -Djib.from.auth.password=\"${DOCKER_HUB_PASS}\"\\\n   
      -Djib.container.labels=org.opencontainers.image.source=\"${REPO%.git}\"\nfi\n"}}
  ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      kind: Workflow
      name: workflow-ci-cheque-9900469pdt9x
      uid: 30e8470b-3352-44d1-9d27-681447da98c0
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2021-04-28T12:47:13Z'
    - manager: workflow-controller
      operation: Update
      apiVersion: v1
      time: '2021-04-28T12:47:23Z'
spec:
  volumes:
    - name: podmetadata
      downwardAPI:
        items:
          - path: annotations
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
        defaultMode: 420
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket
    - name: builddir
      persistentVolumeClaim:
        claimName: workflow-ci-cheque-9900469pdt9x-builddir
    - name: github-rons
      secret:
        secretName: github-rons
        items:
          - key: username
            path: username
          - key: password
            path: password
        defaultMode: 420
    - name: input-artifacts
      emptyDir: {}
    - name: argo-staging
      emptyDir: {}
    - name: default-token-9zkvc
      secret:
        secretName: default-token-9zkvc
        defaultMode: 420
  initContainers:
    - name: init
      image: 'argoproj/argoexec:v3.0.2'
      command:
        - argoexec
        - init
        - '--loglevel'
        - info
      env:
        - name: ARGO_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: GODEBUG
          value: x509ignoreCN=0
      resources: {}
      volumeMounts:
        - name: podmetadata
          mountPath: /argo/podmetadata
        - name: github-rons
          readOnly: true
          mountPath: /argo/secret/github-rons
        - name: input-artifacts
          mountPath: /argo/inputs/artifacts
        - name: builddir
          mountPath: /mainctrfs/mnt/builddir
        - name: argo-staging
          mountPath: /argo/staging
        - name: default-token-9zkvc
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  containers:
    - name: wait
      image: 'argoproj/argoexec:v3.0.2'
      command:
        - argoexec
        - wait
        - '--loglevel'
        - info
      env:
        - name: ARGO_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: GODEBUG
          value: x509ignoreCN=0
        - name: ARGO_CONTAINER_NAME
          value: wait
      resources: {}
      volumeMounts:
        - name: podmetadata
          mountPath: /argo/podmetadata
        - name: docker-sock
          readOnly: true
          mountPath: /var/run/docker.sock
        - name: github-rons
          readOnly: true
          mountPath: /argo/secret/github-rons
        - name: builddir
          mountPath: /mainctrfs/mnt/builddir
        - name: argo-staging
          mountPath: /mainctrfs/argo/staging
        - name: default-token-9zkvc
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
    - name: main
      image: 'ghcr.io/digibank-il/gradle-14-allure-cli-ecr-login:latest'
      command:
        - bash
      args:
        - /argo/staging/script
      workingDir: /mnt/builddir/code
      env:
        - name: REPO
          value: 'https://github.com/c/c.git'
        - name: DOCKER_HUB_USER
          valueFrom:
            secretKeyRef:
              name: fdb-docker-hub-secret
              key: username
        - name: DOCKER_HUB_PASS
          valueFrom:
            secretKeyRef:
              name: fdb-docker-hub-secret
              key: password
        - name: GITHUB_PACK_USER
          valueFrom:
            secretKeyRef:
              name: fdb-pack-secret
              key: uname
        - name: GITHUB_PACK_PASS
          valueFrom:
            secretKeyRef:
              name: fdb-pack-secret
              key: pass
        - name: ARGO_CONTAINER_NAME
          value: main
      resources: {}
      volumeMounts:
        - name: builddir
          mountPath: /mnt/builddir
        - name: argo-staging
          mountPath: /argo/staging
        - name: default-token-9zkvc
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  activeDeadlineSeconds: 1799
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: ip-172-31-11-212.eu-west-1.compute.internal
  securityContext: {}
  imagePullSecrets:
    - name: ghcr-secret
    - name: fdb-dockerhub-pullsecret
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
status:
  phase: Failed
  conditions:
    - type: Initialized
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-04-28T12:47:05Z'
      reason: ContainersNotInitialized
      message: 'containers with incomplete status: [init]'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-04-28T12:47:05Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [wait main]'
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-04-28T12:47:05Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [wait main]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-04-28T12:47:05Z'
  hostIP: 172.31.11.212
  podIP: 172.31.11.86
  podIPs:
    - ip: 172.31.11.86
  startTime: '2021-04-28T12:47:05Z'
  initContainerStatuses:
    - name: init
      state:
        terminated:
          exitCode: 1
          reason: Error
          message: entry not found
          startedAt: '2021-04-28T12:47:11Z'
          finishedAt: '2021-04-28T12:47:12Z'
          containerID: >-
            docker://e1f6ca364c846ebb210ad4307276c998d91b694de9ec65c2dac9acce50e9013e
      lastState: {}
      ready: false
      restartCount: 0
      image: 'argoproj/argoexec:v3.0.2'
      imageID: >-
        docker-pullable://argoproj/argoexec@sha256:49b15b9d2f2ab5712ec05b931b8eba45b0d0d1289706b0ab22937eaff983cd01
      containerID: >-
        docker://e1f6ca364c846ebb210ad4307276c998d91b694de9ec65c2dac9acce50e9013e
  containerStatuses:
    - name: main
      state:
        waiting:
          reason: PodInitializing
      lastState: {}
      ready: false
      restartCount: 0
      image: 'ghcr.io/digibank-il/gradle-14-allure-cli-ecr-login:latest'
      imageID: ''
      started: false
    - name: wait
      state:
        waiting:
          reason: PodInitializing
      lastState: {}
      ready: false
      restartCount: 0
      image: 'argoproj/argoexec:v3.0.2'
      imageID: ''
      started: false
  qosClass: BestEffort

There are no relevant logs in controller log

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you please confirm if the container status is also `entry not found`? This can be found using `kubectl get pod  -ojson`.
