### ISSUE TITLE
Make links in README file open in a new tab

### ISSUE THREAD

**Issue by ghoubrial** [argoproj/argo-workflows#5765]
# Summary

Links in the README file opens in the same tab. It would be better if we could make it open in a new tab instead.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you please send me a like to the document you mean?

**Comment by ghoubrial** [comment]
@alexec Seems like it is all the links in README e.g., "Cloud Native Computing Foundation (CNCF)", 5-min demonstration video, "Read what people said in our latest survey", "Access the demo environment", etc.

**Comment by alexec** [comment]
do you mean on this page?

https://github.com/argoproj/argo-workflows

we don't control that (Github do)

**Comment by ghoubrial** [comment]
Yep!

**Comment by ghoubrial** [comment]
My bad, we can't do this in markdown as discussed in https://github.com/mojombo/github-flavored-markdown/issues/28
