### ISSUE TITLE
"artifact-repositories not found" error from the workflow-controller

### ISSUE THREAD

**Issue by vbarbaresi** [argoproj/argo-workflows#5769]
I’m getting a new error on workflow-controller `latest` image:
It happens right after a workflow is processed
```
time="2021-04-28T09:40:03.025Z" level=info msg="Processing workflow" namespace=mynamespace workflow=myjob-m4fwj
time="2021-04-28T09:40:03.057Z" level=info msg="Get configmaps 404"
time="2021-04-28T09:40:03.057Z" level=error msg="Non-transient error: configmaps \"artifact-repositories\" not found"
time="2021-04-28T09:40:03.058Z" level=info msg="resolved artifact repository" artifactRepositoryRef=default-artifact-repository
```

I didn’t configure any artifact repository, I’m using a very simple configmap from the [default manifests](https://github.com/argoproj/argo-workflows/blob/master/manifests/base/workflow-controller/workflow-controller-configmap.yaml).
I don't have a configmap `artifact-repositories` but I think there isn't any in the default setup.

Going back to `v3.0.2 ` the error disappears. I still see  _Get configmaps 404_ but no error follows.

I would expect no error in logs when using the default installation

**Comment by terrytangyuan** [comment]
This is due to the additional logging added to transient errors in https://github.com/argoproj/argo-workflows/pull/5501. 

The error can be ignored and should have no impact. It would definitely be better if it can be removed though.

**Comment by alexec** [comment]
we should not log anything at error level that is not an error - so this should be changed to warn level

@copierrj could I please ask you to send a PR to change the log level?

**Comment by lowc1012** [comment]
@alexec  Hi, Could I take over this issue?
