### ISSUE TITLE
Unable to generate workflow from workflowtemplate using API

### ISSUE THREAD

**Issue by msbecker** [argoproj/argo-workflows#5800]
I am running Argo workflows in an Azure Kubernetes Service cluster, with Kubernetes v1.19.1 and the default AKS kubenet network  The container runtime is set to k8sapi as newest versions of AKS no longer use Docker.
I am running Argo v3.0.2.

I am using the quickstart deployment to set up Argo workflows. https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/quick-start-postgres.yaml

I am able to create a workflow with the API using curl to submit the JSON. https://argoproj.github.io/argo-workflows/rest-examples/

I am able to submit a workflow via automation using the API. https://argoproj.github.io/argo-workflows/submit-workflow-via-automation/

I am able to create a workflowtemplate, view the template's YAML in the UI, and run a workflow from it using the UI. I can call the API with curl to return the workflowtemplate and event bindings I am using. However, if I try to use that same workflowtemplate to generate a workflow using the API, nothing happens. https://argoproj.github.io/argo-workflows/events/ 
I have double-checked the permissions of the service account I am using and it has the proper permissions -- using an SA without those permissions returns an error. I have even used the cluster admin account with no success.

**Comment by dinever** [comment]
Hi @msbecker, did API return 200 status? Could you post the Argo Server logs if you have them?

```
kubectl logs deploy/argo-server -n argo
```

**Comment by msbecker** [comment]
API returns empty response, just two curly braces -- {} No success or error codes. 

I create a service account and rolebinding. Role has Role has list permissions on workfloweventbindings; list, update, create and get on workflows; and get, list on workflow templates. 

I run curl both with and without the discriminator:

curl https://<ipaddress>:2746/api/v1/events/argo/ \
  -H "Authorization: $ARGO_TOKEN" \
  -d '{"message": "hello"}'

curl https://<ipaddress>:2746/api/v1/events/argo/my-discriminator \
  -H "Authorization: $ARGO_TOKEN" \
  -d '{"message": "hello"}'

I tailed the argo server logs as I was using curl. Logs are below.

time="2021-05-04T15:27:10.909Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2021-05-04T15:27:10Z" grpc.time_ms=9.885 span.kind=server system=grpc
time="2021-05-04T15:27:35.149Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2021-05-04T15:27:35Z" grpc.time_ms=8.191 span.kind=server system=grpc
time="2021-05-04T15:27:53.584Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2021-05-04T15:27:53Z" grpc.time_ms=10.228 span.kind=server system=grpc
time="2021-05-04T15:28:30.536Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ReceiveEvent grpc.service=event.EventService grpc.start_time="2021-05-04T15:28:30Z" grpc.time_ms=8.273 span.kind=server system=grpc

**Comment by dinever** [comment]
Thanks @msbecker!

I suspect this is due to the `WorkflowEventBinding` mismatch which raises no error, will need to look into this more.

**Comment by msbecker** [comment]
I've double-checked, and the event binding references the workflowtemplate I'm using. There is only one workflowtemplage and one event binding in my test environment. Not sure where there would be a mismatch.
