### ISSUE TITLE
support k8s `nodeName` for scheduling

### ISSUE THREAD

**Issue by henrywangx** [argoproj/argo-workflows#5821]
# Summary

argo-workflow at present only support node-selector. But If we also support `nodeName`, the k8s's scheduler will just ignore this pod, will accelerate the pod's creation.

# Use Cases

Run large scale pods on virtual kubelet. In that case, we know the virtual-kubelet's node name. And we don't need the scheduler. We wanna reduce the pressure of scheduler.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by agilgur5** [comment]
This can probably be worked around with `podSpecPatch`

**Comment by agilgur5** [comment]
Closing this per above workaround and https://github.com/argoproj/argo-workflows/pull/13575#issuecomment-2337530767
