### ISSUE TITLE
Maintain a constant url for a workflow regardless of its lifecycle

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#5824]
# Summary

When a workflow is created, you can view it in the UI by going to `https://server/workflows/namespace/name`  but as soon as it’s archived, that url no longer works and you have to use `https://server/archived-workflows/uid`.

It would be much more useful if a workflow had a fixed URL regardless of whether it was archived or not, even if that's a url that simply 301 redirects to the correct current URL.

# Use Cases

One of our uses of Argo Workflows is as a CI tool, triggered by github PRs. We send the URL to github when the workflow starts so that the end user (developer) can click the 'details' link in github to be taken directly to the workflow that is performing the CI at the time.

Unfortunately, once archived, that url is useless to the developer and they have to go hunting in the archived workflows tab to find the same workflow. This is jarring for the developer and often leads to wasted time asking others for help.

This request was born out of this discussion: https://cloud-native.slack.com/archives/C01QW9QSSSK/p1619784572271800

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tim-sendible** [comment]
The mentioned PR doesn't fix this issue. I still have 2 URLS, which doesn't translate well to thinks like github pull request decorations.

**Comment by isubasinghe** [comment]
I think it is better if we display a list of available links if there is no workflow to be found. This is because workflow **names** can be duplicated in the archived storage layer.  This addresses your use case while being a non-breaking change.

**Comment by isubasinghe** [comment]
Does that sound like an acceptable solution @tim-sendible ?

**Comment by tim-sendible** [comment]
We have hacked around the issue using a custom container: https://github.com/sendible-labs/argo-workflows-url-finder 

It's not clear what you mean by "a list of available links", so I'm afraid I can't answer your question.

**Comment by isubasinghe** [comment]
Sorry my bad, I shall elaborate: a list of links to archived workflows that have the name you desire to examine. 
So if you want to look at "xyz" and it has been archived a list of links to archived workflows that have the name "xyz" will be displayed instead of the normal error message: ![error message](https://user-images.githubusercontent.com/1142830/152437655-c0ebd4c4-03d1-4234-914e-6272e7870e0f.png)

**Comment by tim-sendible** [comment]
Presumably though, in the case of only one returned value, you could just 302 redirect the user?

**Comment by isubasinghe** [comment]
Yeah I'd be happy to add that functionality as well.

**Comment by tim-sendible** [comment]
Cool, then yes, what you describe is effectively the solution we are after. Thanks.

**Comment by isubasinghe** [comment]
Sweet, no worries!

**Comment by alexec** [comment]
This could be improved in the following ways:

* If the /workflow/my-ns/my-name link is not found, redirect to /workflow-archive/my-ns?metadata.name=my-name&deep=true.
* In /workflow-archive, if deep=true, and only one archive workflow has that name (common case) then redirect to that one workflow.

**Comment by caelan-io** [comment]
I believe this is closed by #7854. 

@tim-sendible let us know if not the case and we can re-open this issue!

**Comment by tim-sendible** [comment]
Yes, I think it probably will fix the issue. Do you know what version it'll go into @caelan-io ?

**Comment by caelan-io** [comment]
Awesome! It sounds like a v3.4 is getting ready for release in late July/ early August so we'll see if it can get it into that version.

**Comment by tim-sendible** [comment]
Just to confirm, I tested and it's working in 3.4-rc2
