### ISSUE TITLE
link to SSO docs when login fails: "token not valid for running mode"

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5832]
Many users are confused by this error. This means they have not configured `--auth-mode` correctly.

We could enhance this error message with more help.

**Comment by Stevenyu1982** [comment]
do we have any update on this?

**Comment by alexec** [comment]
No. Would you like to submit a PR to link to the help page?

**Comment by Stevenyu1982** [comment]
@alexec  I am also facing this error, and looking for helps now :(

**Comment by maxisam** [comment]
I have the same issue. 
https://argoproj.github.io/argo-workflows/argo-server-sso/#sso-rbac

If I add `groups` as example code, it doesn't work and throw the error message. If I remove it, it works as expected
