### ISSUE TITLE
CLI: Support input from device files (e.g., /dev/stdin)

### ISSUE THREAD

**Issue by kevinhwang** [argoproj/argo-workflows#5838]
# Summary

Disable (or provide a flag to disable) file extension checking for CLI commands requiring input files, **OR** modify CLI to interpret `-` when a file is expected to mean "read input from stdin" (a common convention).

# Use Cases

When piping things around between programs. E.g., using Kustomize to build your templates alongside your other K8s manifests:

```
$ argo template lint <(kustomize build)
WARN[2021-05-05T14:02:50.551Z] ignoring file with unknown extension: /dev/fd/63 
✖ found nothing to lint in the specified paths, failing...
```

```
$ kustomize build | argo template lint /dev/stdin
WARN[2021-05-05T14:02:50.551Z] ignoring file with unknown extension: /dev/stdin
✖ found nothing to lint in the specified paths, failing...
```

In both cases the cli refuses to process the device files because their file names lack a `.yaml` extension, but this is a super useful way to `argo submit` or `argo template create` or `argo lint`, etc.

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This error comes from lint.go#L142. Is that switch it should be easy to add `/dev/stdin` and `/dev/fd/*' as supported options. Would you like to submit a PR?

**Comment by kevinhwang** [comment]
@alexec Sure thing, opened #5851.
