### ISSUE TITLE
Unable to clone empty repository

### ISSUE THREAD

**Issue by paveq** [argoproj/argo-workflows#5857]
## Summary 

When cloning empty repo via input artifacts there's an error:

`executor error: remote repository is empty`

It should be possible to clone empty repositories. This comes up especially if a workflow is used to create new repositories through eg. Bitbucket API, and then committing to those.

**Comment by alexec** [comment]
Would you like to investigate and raise a PR to fix?

**Comment by paveq** [comment]
It seems design issue in Go-Git: https://github.com/go-git/go-git/issues/118

There's one example how to work around this in https://github.com/jmalloc/grit/pull/80/files

I'll see if I have time to raise this as PR.
