### ISSUE TITLE
Problem implementing the "quick start" guide for version 3.0.1.

### ISSUE THREAD

**Issue by amitm02** [argoproj/argo-workflows#5859]
## Summary 

What happened/what you expected to happen?

Problem with the quick start for version 3.0.1 under GCP K8S.

I can get this to work:
```
helm repo add argo https://argoproj.github.io/argo-helm
helm install argo argo/argo -n argo --create-namespace --set minio.install=true
kubectl -n argo port-forward deployment/argo-server 2746:2746
```
after I can see the UI via 127.0.0.1:2746

But if i try:
```
kubectl create namespace argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/v3.0.1/manifests/quick-start-postgres.yaml
kubectl create clusterrolebinding XXXX-cluster-admin-binding --clusterrole=cluster-admin --user=XXXX@digitalowl.com
kubectl -n argo port-forward deployment/argo-server 2746:2746
```

I can not log into the UI via 127.0.0.1:2746.
All I get is "ERR_EMPTY_RESPONSE".
argo-server logs:
```
time="2021-04-12T08:19:20.980Z" level=info authModes="[server client]" baseHRef=/ managedNamespace=argo namespace=argo secure=true
time="2021-04-12T08:19:20.980Z" level=info msg="config map" name=workflow-controller-configmap
time="2021-04-12T08:19:20.980Z" level=info msg="SSO disabled"
time="2021-04-12T08:19:20.994Z" level=info msg="Starting Argo Server" instanceID= version=v3.0.1
time="2021-04-12T08:19:20.994Z" level=info msg="Creating DB session"
time="2021-04-12T08:19:21.016Z" level=info msg="Node status offloading config" ttl=5m0s
time="2021-04-12T08:19:21.016Z" level=info msg="Creating event controller" operationQueueSize=16 workerCount=4
time="2021-04-12T08:19:21.024Z" level=info msg="Argo Server started successfully on https://localhost:2746"
```

**Comment by anhdle14** [comment]
I recently tried to install the v3.0.1 on Docker-for-Mac and got `ERR_EMPTY_RESPONSE`. This post has been miss interpreted but the bug is there.

Current environment:

- Big Sur (11.3.1 Intel)
- Docker (20.10.6)
- Test both on Kubernetes and Kind.
- Steps to reproduce:
  ```bash
  $ kubectl create namespace argo
  $ kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/v3.0.6/manifests/install.yaml
  $ kubectl -n argo edit svc/argo-server
  # Edit ClusterIP to LoadBalancer 
  ```

--> When try to access localhost:2746. This is the response: 

<img width="604" alt="Screen Shot 0003-05-25 at 22 00 39" src="https://user-images.githubusercontent.com/9645992/119502219-a8403b00-bda4-11eb-9f3a-7762e40b0d6e.png">

**Comment by alexec** [comment]
Since v3.0, we listen on a TLS socket, you must use HTTPS in your URL.https://localhost:2746

**Comment by johnson-prabu** [comment]
> Since v3.0, we listen on a TLS socket, you must use HTTPS in your URL.https://localhost:2746

How to map this with Ambassador?

**Comment by rainfd** [comment]
> Since v3.0, we listen on a TLS socket, you must use HTTPS in your URL.https://localhost:2746

@alexec  Can you highlight HTTPS on the Quick Start doc? We stuck on this problem for couple hours.

**Comment by chenbodeng719** [comment]
I think it should point out that access website by https is a must.
