### ISSUE TITLE
Repeated Log while Streaming from a failed container 

### ISSUE THREAD

**Issue by CaptainFreak** [argoproj/argo-workflows#5865]
## Summary 

When streaming logs from a failed container, the message event with logs keep coming. Logs repeat and stream does not gets closed. What's weird is, The argo server UI somehow does not get impacted with, It properly gets just the proper no. of message events and logs and stream closes from either UI or server, don't know.

Use following NodeJS code to reproduce:
```javascript
var EventSource = require("eventsource");

var es = new EventSource("http://<argo-server>:2746/api/v1/workflows/<namespace>/<name>/<pod>/log?logOptions.container=main&logOptions.follow=true");

es.addEventListener("message", async function (e) {
  var logs = e.data;
  console.log(logs);
});
```

## Diagnostics

What version of Argo Workflows are you running? 
v2.11.8

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This is a very old version. Can you please try in v3.0 which has many improvement to the UI.

**Comment by CaptainFreak** [comment]
Hi, @alexec Yes, tried right now on v3.0.7

Same behavior.

**Comment by CaptainFreak** [comment]
You can even try in Chrome Dev tools console

```
es = new EventSource('https://localhost:2746/api/v1/workflows/argo/test-sd4ts/log?logOptions.container=main&logOptions.follow=true&podName=test-sd4ts-1871486904')

es.onmessage(e => console.log(e))
```

Just replace the above with your own URL.

You will see in the network tab, that Eventsource fires another HTTP connection once the previous one is closed by the server.

How Argo server UI makes sure that only one connection should be done?

**Comment by CaptainFreak** [comment]
So basically maybe not a problem at all from the Argo server, just now sure why requests keep getting fired from EventSource.

and not sure how to detect completion of the first request and prevent it from sending further more.

**Comment by CaptainFreak** [comment]
Does Argo server send something which says the stream is closed? If not, will have to use something like this

```
var isOpenOnce = false;
  es.onopen = function () {
    if (isOpenOnce) {
      es.close();
    } else {
      console.log("Connection to server opened.");
      isOpenOnce = true;
    }
  };
```

**Comment by alexec** [comment]
EventSources in browsers lack decent recovery options. E.g. won't tell you why they failed. Badly design IMHO. If there is no user impact, I'm not sure it is worth the time investigating this.
