### ISSUE TITLE
Please fix the Argo Server homepage

### ISSUE THREAD

**Issue by lausser** [argoproj/argo-workflows#5866]
## Summary 

I followed the instructions on https://argoproj.github.io/argo-workflows/argo-server/ where you write "This will start a server on port 2746 which you can view at http://localhost:2746"
After two days of desperate reinstalling and searching, i found that it must be https instead of http.

## Diagnostics

Running on k3s and applied https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/quick-start-minimal.yaml
Version is argoproj/argocli:v3.0.2

```yaml
kubectl -n argo apply -f https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/quick-start-minimal.yaml
kubectl -n argo port-forward svc/argo-server 2746:2746
curl http://127.0.0.1:2746  -> empty response if at all

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Try HTTPS

**Comment by lausser** [comment]
I just got aware that the web page is part of this repository. Here the url is ok:
```
docs/quick-start.md:kubectl -n argo port-forward deployment/argo-server 2746:2746
docs/quick-start.md:This will serve the user interface on https://localhost:2746
```
here it's not
```
docs/argo-server.md:kubectl -n argo port-forward svc/argo-server 2746:2746
docs/argo-server.md:Then visit: http://127.0.0.1:2746
```
grep -r localhost:2746 docs/ shows a lot more such urls, some with http, some with https. Can you confirm that https is the deault in the latest releases? I would then make a pull request.
