### ISSUE TITLE
UI: Make the external log / Splunk link open(able) on new tab

### ISSUE THREAD

**Issue by szab100** [argoproj/argo-workflows#5937]
# Summary
When looking at a workflow, we often need to check its logs in Splunk (or other ext. log aggregator). However, it is very annoying that 1) clicking that button navigates off the Argo UI to the log system and/or 2) we cannot right-click / 'open on new tab'. This is especially important when using lower podGC strategies (like delete after completion => no way to check its logs anytime after finished, other than from the external logging system).

Please make that button open the link on a new tab by default OR make it a simple link that the user can explicitly open in new tab or window.

# Use Cases
Explained above, it is a very common, everyday use-case when browsing the Argo UI and doing any troubleshooting.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by basanthjenuhb** [comment]
It used to work before,
Somehow it doesn't work in V3
