### ISSUE TITLE
pods don't have annotations from workflowDefaults.podMetadata when using workflow template

### ISSUE THREAD

**Issue by dkimdon** [argoproj/argo-workflows#5942]
## Summary 

When I configure an annotation in the controller's workflowDefaults like this:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  workflowDefaults: |
    spec:
      podMetadata:
        annotations:
          some.key: value
```

 I expect to see the annotation on all workflow pods.  Specifically, if I submit a workflow from a workflow template then I expect to see the annotation on the associated pod(s).  However, I do not see the annotation in this case.

If I submit the workflow directly then I do see the annotation.

## Diagnostics

What Kubernetes provider are you using? 

Docker Desktop and kops (have seen the problem on both).

What version of Argo Workflows are you running? 

3.0.3

## Detailed Reproduction Steps

Install  argo workflows and configure workflowDefaults to include an annotation in the podMetadata:

```
$ kubens argo
$ curl https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/install.yaml > install.yaml
$ kubectl apply -f install.yaml
. . .
$ cat workflow-controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  workflowDefaults: |
    spec:
      podMetadata:
        annotations:
          some.key: value
$ kubectl apply -f workflow-controller-configmap.yaml
configmap/workflow-controller-configmap configured
$
```

Run a workflow (not from a workflow template) and see that the annotation is on the pod as expected:
```
$ cat hello-world-workflow.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-workflow-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
$ kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
argo-server-596fc7b784-k2rfn           1/1     Running   2          32m
workflow-controller-7c568955d7-vnqxm   1/1     Running   0          63s
C02YL00WJG5M:bug dkimdon$ argo submit hello-world-workflow.yaml
Name:                hello-world-workflow-2jmsn
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Tue May 18 14:33:03 -0700 (now)
Progress:
C02YL00WJG5M:bug dkimdon$ kubectl describe pod hello-world-workflow-2jmsn
Name:         hello-world-workflow-2jmsn
. . .
Annotations:  some.key: value
              workflows.argoproj.io/node-name: hello-world-workflow-2jmsn
              workflows.argoproj.io/outputs: {"exitCode":"0"}
              workflows.argoproj.io/template:
                {"name":"whalesay","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"docker/whalesay:latest","command":["cowsay"],"ar...
Status:       Succeeded
. . .
$
```
**The above pod has the expected annotation. (some.key: value)**

Run a workflow from a workflow template.  See that the expected annotation is not on the pod:
```
$ kubectl apply -f hello-world-workflow-template.yaml
workflowtemplate.argoproj.io/hello-world-workflow-template created
$ argo submit --from workflowtemplate/hello-world-workflow-template
Name:                hello-world-workflow-template-gznjx
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Tue May 18 14:34:51 -0700 (now)
Progress:
$ kubectl describe pod hello-world-workflow-template-gznjx
Name:         hello-world-workflow-template-gznjx
Namespace:    argo
Priority:     0
Node:         docker-desktop/192.168.65.4
Start Time:   Tue, 18 May 2021 14:34:51 -0700
Labels:       workflows.argoproj.io/completed=true
              workflows.argoproj.io/workflow=hello-world-workflow-template-gznjx
Annotations:  workflows.argoproj.io/node-name: hello-world-workflow-template-gznjx
              workflows.argoproj.io/outputs: {"exitCode":"0"}
              workflows.argoproj.io/template:
                {"name":"whalesay","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"docker/whalesay:latest","command":["cowsay"],"ar...
Status:       Succeeded
. . . 
$
```

**The above pod does not have the expected annotation.**

```

Workflow controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep hello
time="2021-05-18T21:33:03.758Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-workflow-2jmsn
time="2021-05-18T21:33:03.760Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=hello-world-workflow-2jmsn
time="2021-05-18T21:33:03.761Z" level=info msg="Pod node hello-world-workflow-2jmsn initialized Pending" namespace=argo workflow=hello-world-workflow-2jmsn
time="2021-05-18T21:33:03.781Z" level=info msg="Created pod: hello-world-workflow-2jmsn (hello-world-workflow-2jmsn)" namespace=argo workflow=hello-world-workflow-2jmsn
time="2021-05-18T21:33:03.803Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=3217074 workflow=hello-world-workflow-2jmsn
time="2021-05-18T21:33:13.759Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-workflow-2jmsn
time="2021-05-18T21:33:13.760Z" level=info msg="Setting node hello-world-workflow-2jmsn outputs" namespace=argo workflow=hello-world-workflow-2jmsn
time="2021-05-18T21:33:13.761Z" level=info msg="Updating node hello-world-workflow-2jmsn status Pending -> Succeeded" namespace=argo workflow=hello-world-workflow-2jmsn
time="2021-05-18T21:33:13.761Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=hello-world-workflow-2jmsn
time="2021-05-18T21:33:13.761Z" level=info msg="Marking workflow completed" namespace=argo workflow=hello-world-workflow-2jmsn
time="2021-05-18T21:33:13.761Z" level=info msg="Checking daemoned children of " namespace=argo workflow=hello-world-workflow-2jmsn
time="2021-05-18T21:33:13.774Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=3217106 workflow=hello-world-workflow-2jmsn
time="2021-05-18T21:33:13.780Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/hello-world-workflow-2jmsn/labelPodCompleted
time="2021-05-18T21:34:51.158Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-workflow-template-gznjx
time="2021-05-18T21:34:51.161Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=hello-world-workflow-template-gznjx
time="2021-05-18T21:34:51.174Z" level=info msg="Pod node hello-world-workflow-template-gznjx initialized Pending" namespace=argo workflow=hello-world-workflow-template-gznjx
time="2021-05-18T21:34:51.184Z" level=info msg="Created pod: hello-world-workflow-template-gznjx (hello-world-workflow-template-gznjx)" namespace=argo workflow=hello-world-workflow-template-gznjx
time="2021-05-18T21:34:51.196Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=3217302 workflow=hello-world-workflow-template-gznjx
time="2021-05-18T21:35:01.186Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-workflow-template-gznjx
time="2021-05-18T21:35:01.186Z" level=info msg="Setting node hello-world-workflow-template-gznjx outputs" namespace=argo workflow=hello-world-workflow-template-gznjx
time="2021-05-18T21:35:01.186Z" level=info msg="Updating node hello-world-workflow-template-gznjx status Pending -> Succeeded" namespace=argo workflow=hello-world-workflow-template-gznjx
time="2021-05-18T21:35:01.187Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=hello-world-workflow-template-gznjx
time="2021-05-18T21:35:01.187Z" level=info msg="Marking workflow completed" namespace=argo workflow=hello-world-workflow-template-gznjx
time="2021-05-18T21:35:01.187Z" level=info msg="Checking daemoned children of " namespace=argo workflow=hello-world-workflow-template-gznjx
time="2021-05-18T21:35:01.195Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=3217336 workflow=hello-world-workflow-template-gznjx
time="2021-05-18T21:35:01.201Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/hello-world-workflow-template-gznjx/labelPodCompleted
$
```

---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I think this feature is only in v3.1? @sarabala1979

**Comment by dkimdon** [comment]
Thanks for the quick response.

That would be great to see it in 3.1. For now I am adding the annotations directly to the workflow templates.

If it helps, I just tested 3.1.0-rc5 and I am observing the same behavior (annotation not present):
```
$ curl -L https://github.com/argoproj/argo-workflows/releases/download/v3.1.0-rc5/install.yaml > install.yaml
$ cat workflow-controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  workflowDefaults: |
    spec:
      podMetadata:
        annotations:
          some.key: value
$ kubectl apply -f workflow-controller-configmap.yaml
$ argo submit --from workflowtemplate/hello-world-workflow-template
$ kubectl describe pod  hello-world-workflow-template-8574b
Name:         hello-world-workflow-template-8574b
Namespace:    argo
Priority:     0
Node:         docker-desktop/192.168.65.4
Start Time:   Tue, 18 May 2021 15:57:02 -0700
Labels:       workflows.argoproj.io/completed=true
              workflows.argoproj.io/workflow=hello-world-workflow-template-8574b
Annotations:  workflows.argoproj.io/node-name: hello-world-workflow-template-8574b
              workflows.argoproj.io/template:
                {"name":"whalesay","inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"docker/whalesay:latest","command":["cowsay"],"ar...
Status:       Succeeded
. . . 
```

**Comment by sappier** [comment]
Pods are missing metadata set in the WorkflowTemplate.spec.podMetadata as described in https://argoproj.github.io/argo-workflows/fields/#workflowtemplatespec.
There are no specified annotations and labels in a pod after submitting a workflow from the workflow template:
```
# This template demonstrates how pod annotations and labels may be set at the workflow level for all pods
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wftmpl-pod-metadata
spec:
  entrypoint: hello-hello-hello
  
  podMetadata:
    annotations:
        iam.amazonaws.com/role: role-arn
    labels:
        app: whalesay
        tier: demo

  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello1"

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

**Comment by alexrosenfeld10** [comment]
@alexec would this same issue also cause problems with using `podSpecPatch` as well?
