### ISSUE TITLE
Wait container polling time interval configuration to get main container state

### ISSUE THREAD

**Issue by vcarluer** [argoproj/argo-workflows#5943]
# Summary

Add a configuration for the wait container argoproj/argoexec to setup the main container state polling time interval.

I have tried the RESOURCE_STATE_CHECK_INTERVAL used in https://github.com/argoproj/argo-workflows/blob/2b87409431bb778a4264296bea2fd4173d00651d/workflow/executor/resource.go
Tested with argoproj/argoexec latest and v3.1.0-rc5 and k8sapi executor.

The environment variable is well setup on the wait container but it seams it does not change the polling time interval I want: it always takes approximately 4-5 seconds to check the finished state of the main container. For instance:
time="2021-05-18T21:45:09.918Z" level=info msg="Watch pods 200"                                                                                                                      │
│ time="2021-05-18T21:45:14.309Z" level=info msg="Main container completed"

So a Workflow which should take 10 seconds take 1 minute.

# Use Cases

With main containers with a runtime duration less than 5 seconds

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Please attach your complete workflow.

**Comment by vcarluer** [comment]
Hello,

please find attached one of our [workflow.]


[github_workflow.txt](https://github.com/argoproj/argo-workflows/files/6555627/github_workflow.txt)

**Comment by terrytangyuan** [comment]
I am not sure if I understand your question here. `RESOURCE_STATE_CHECK_INTERVAL` is for configuring the interval in main container/executor. This is only for resource type steps and there's no wait container since main container is used to watch the status of the resource instead.

**Comment by vcarluer** [comment]
I have a wait container running in each pod running argoprog/argoexec watching the main execution. Maybe I missed an option to disable this behavior ans use only the main?

**Comment by terrytangyuan** [comment]
Then you are not using resource type steps which is what `RESOURCE_STATE_CHECK_INTERVAL` can be used for. A minimal and reproducible example YAML would help here to illustrate your use case.

**Comment by vcarluer** [comment]
I think that the sample Diamond have this behavior too. I would need to rerun it tomorrow to confirm. https://github.com/argoproj/argo-workflows/blob/master/examples/dag-diamond.yaml

**Comment by terrytangyuan** [comment]
Well `dag-diamond.yaml` does not use resource type templates. It only contains container templates so `RESOURCE_STATE_CHECK_INTERVAL` won't work for them.

**Comment by vcarluer** [comment]
Yes it is obviously not the good parameter but I can I lower the time of the wait container which seams to check the main container execution status? I didn't found any, this is why I have opened an enhancement request.

**Comment by terrytangyuan** [comment]
The 5 seconds is hard-coded in the current version. I've submitted https://github.com/argoproj/argo-workflows/pull/6088 to make it configurable.

**Comment by vcarluer** [comment]
Yes exactly, thank you very much!
