### ISSUE TITLE
Generating C# code from the Open API spec results in code that fails desrialize

### ISSUE THREAD

**Issue by lucastheisen** [argoproj/argo-workflows#5947]
## Summary 

Generating C# API from the [Open API spec](https://github.com/argoproj/argo-workflows/blob/master/api/openapi-spec/swagger.json) results in code that fails to deserialize results because certain `DateTime` values are occasionally `null`.

```
fail: Example.ArgoCommands.ArgoListCommand[0]
      Failed with Exception
      Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.DateTime'. Path 'items[5].spec.volumeClaimTemplates[0].metadata.creationTimestamp', line 3043, position 39.
       ---> System.InvalidCastException: Null object cannot be converted to a value type.
         at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
         --- End of inner exception stack trace ---
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
```

## Diagnostics

What Kubernetes provider are you using? 

OpenShift 4.7

What version of Argo Workflows are you running? 

Argo 3.0.4

As this is more of a serialization issue, its easiest to just show an example of a real workflow spec where this occurs.  We don't specify meta information like `creationTimestamp` in our spec anyway, its added automatically.  So this is one example:
```yaml
      volumeClaimTemplates:
      - metadata:
          creationTimestamp: null
          name: workdir-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 64Gi
          storageClassName: basic
        status: {}
```

We have also seen this in:

```yaml
  status:
    conditions:
    - status: "True"
      type: Completed
    estimatedDuration: 117
    finishedAt: "2021-05-14T13:57:12Z"
    message: 'runtime error: invalid memory address or nil pointer dereference'
    nodes:
      migration-wft-bkznt:
        children:
        - migration-wft-bkznt-51186898
        displayName: migration-wft-bkznt
        estimatedDuration: 117
        finishedAt: null
        id: migration-wft-bkznt
        message: Workflow operation error
        name: migration-wft-bkznt
        phase: Error
        startedAt: "2021-05-14T13:57:12Z"
        templateName: migration
        templateScope: local/
        type: Steps
```

Our current workaround is to post process the generated code with commands like:

```bash
sed -i \
  's/public DateTime FinishedAt/public DateTime? FinishedAt/g' \
  "./src/${PACKAGE_NAME}/Model/IoArgoprojWorkflowV1alpha1NodeStatus.cs"
```

But this is definitely a hack.  Is there a way to mark these status related date fields `nullable` so that they will deserialize properly?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I think we do something similar for Java. Maybe check out that SDK?

**Comment by lucastheisen** [comment]
@alexec i am having trouble following the [java sdk generation](https://github.com/argoproj-labs/argo-client-java/blob/master/Makefile), so i have a few questions if you have time to answer them.

Specifically, there are some _seemingly_ arbitrary choices for name qualifiers to strip:

```makefile
curl https://raw.githubusercontent.com/argoproj/argo/$(VERSION)/api/openapi-spec/swagger.json \
  | sed 's/io.argoproj.workflow.v1alpha1.//' \
  | sed 's/io.k8s.api.core.v1.//' \
  | sed 's/io.k8s.apimachinery.pkg.apis.meta.v1.//'  \
  > swagger.json
```

Which leaves some argo names shortened (ie: [`Workflow`](https://github.com/argoproj-labs/argo-client-java/blob/master/src/main/java/io/argoproj/workflow/models/Workflow.java)) while others remain long (ie: [`IoArgoprojEventsV1alpha1EventSource`](https://github.com/argoproj-labs/argo-client-java/blob/master/src/main/java/io/argoproj/workflow/models/IoArgoprojEventsV1alpha1EventSource.java).  Is this desirable?  Was the failure to strip event classes an oversight?

It also does some restructuring to [put the client out as a top level package (`--invoker-package io.argoproj.workflow`)](https://github.com/argoproj-labs/argo-client-java/blob/master/Makefile#L16).  Again this appears to be convenience, but could easily lead to clients generated for other languages to differ in uncomfortable/surprising ways.

In order to integrate with the [kubernetes `GenericClient`](https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/GenericClient.cs) (which seems like an intended path) the top level model objects must extend from `IKubernetesObject`. I assume this was never added because its an external API, and maybe there is some simple config to tell the generated to add that as a parent class. But my solution is to leverage the `partial class` nature of the model objects with more _after the fact monky patching_:

```bash
>&2 echo "add the IKubernetesObject interface to model object to work with k8s.GenericClient"
cat > "./src/${PACKAGE_NAME}/Model/AddIKubernetesObject.cs" <<EOF
namespace ${PACKAGE_NAME}.Model
{
    using k8s;
    public partial class IoArgoprojWorkflowV1alpha1CronWorkflow : IKubernetesObject
    {
    }
    public partial class IoArgoprojWorkflowV1alpha1CronWorkflowList : IKubernetesObject
    {
    }
    public partial class IoArgoprojWorkflowV1alpha1Workflow : IKubernetesObject
    {
    }
    public partial class IoArgoprojWorkflowV1alpha1WorkflowList : IKubernetesObject
    {
    }
    public partial class IoArgoprojWorkflowV1alpha1WorkflowEventBinding : IKubernetesObject
    {
    }
    public partial class IoArgoprojWorkflowV1alpha1WorkflowEventBindingList : IKubernetesObject
    {
    }
    public partial class IoArgoprojWorkflowV1alpha1WorkflowTemplate : IKubernetesObject
    {
    }
    public partial class IoArgoprojWorkflowV1alpha1WorkflowTemplateList : IKubernetesObject
    {
    }
}
EOF
```

This feels wrong, is there a better way?

Finally, back to the original point of date values, the java code switches to `joda` which has a [constructor which accepts `null` and turns that into current date](https://www.joda.org/joda-time/apidocs/index.html)

> **Parameters:**
> instant - the datetime object, null means now

So to mimic this, i _could_ create a new Time datatype that accepts `null` during de-serialization, but this will just result in lies like: `finishedAt: <now>` when in reality it is `finishedAt: null` which could surface as harmful bugs, right?  I think it would make more sense to mark the fields nullable, wouldn't it?  Then the generation could would (in theory) generate the proper `DateTime?` in C#.  It could conscientiously be limited to those datetime values which actually allow `null` (if there are any that don't), but I definitely don't have the depth of knowledge to determine which would be which other than experimentally.

**Comment by alexec** [comment]
> Is this desirable? Was the failure to strip event classes an oversight?

No, I don't think it is desirable. It should be fixed, this is a new feature which is probably why it was overlooked.

I wonder if this could be better fixed in the generation of the swagger? Have you taken a look at how this works today?

I'm not much of an expert on this I'm afraid?

**Comment by lucastheisen** [comment]
> I wonder if this could be better fixed in the generation of the swagger?

If it does get fixed in the swagger generation, it would ensure all generated code has common _feel_, so yeah, this would be ideal.

> Have you taken a look at how this works today?

I have not.  Right now i am still trying to figure out the code generation side.  Cant get [`nullable`](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#schemaNullable) to work, tried:

```bash
sed \
  's/^\(.*\"io.k8s.apimachinery.pkg.apis.meta.v1.Time\"\).*/\1: {"nullable": true,/g' \
  src/argo-workflows-${ARGO_VERSION}/api/openapi-spec/swagger.json" \
  > /tmp/customized_swagger.json
```

but failed: 

```console
--- src/argo-workflows-3.0.4/api/openapi-spec/swagger.json      2021-05-14 04:40:59.000000000 +0000
+++ /tmp/customized_swagger.json        2021-05-21 15:04:29.815840000 +0000
@@ -11996,7 +11996,7 @@
         }
       }
     },
-    "io.k8s.apimachinery.pkg.apis.meta.v1.Time": {
+    "io.k8s.apimachinery.pkg.apis.meta.v1.Time": {"nullable": true,
       "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
       "type": "string",
       "format": "date-time"

Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 4
Errors:
        -attribute definitions.io.k8s.apimachinery.pkg.apis.meta.v1.Time.nullable is unexpected
Warnings:
        -attribute definitions.io.k8s.apimachinery.pkg.apis.meta.v1.Time.nullable is unexpected
```

So had to settle for the `--import-mappings` generator option:

```bash
  --import-mappings io.k8s.apimachinery.pkg.apis.meta.v1.Time=System.DateTime? \
```

From a deserialization side this will prevent any of the `null` date time values from failing to deserialize, but it will also allow for creation of (_possibly_) invalid request objects since it was applied to all time objects.  However i think this is the best I can do here.

**Comment by RothAndrew** [comment]
I just ran into this as well. In my case it threw an exception when it tried to serialize the Workflow's `status.startedAt` property. It makes sense that startAt would be null if I Just submitted a new workflow. Will explore @lucastheisen 's workaround of using `--import-mappings`
