### ISSUE TITLE
Support Github Hooks

### ISSUE THREAD

**Issue by iterion** [argoproj/argo-workflows#595]
It would really nice if we could support Github hooks as a trigger for builds. If this is something that the Argo project plans to implement I'd love to try to work on it.

**Comment by alexmt** [comment]
Hello @iterion. Yes, we are planning to add Github webhooks support.  Argo is supposed to solve multiple use cases, so we decided to create a separate project which uses Argo workflow engine as a building block and provides CI related features. The first version will be available early next week. I will post an update here once it is ready.

**Comment by bhack** [comment]
You can follow https://github.com/argoproj/argo-ci

**Comment by alexmt** [comment]
Sorry for the delay. It took more time to get first 'argo-ci' version. As @bhack mention please check https://github.com/argoproj/argo-ci README for installation instructions.
