### ISSUE TITLE
Add x86_64_linux bottle on linuxbrew-core

### ISSUE THREAD

**Issue by sestegra** [argoproj/argo-workflows#5965]
# Summary

`x86_64_linux` bottle isn't defined on [linuxbrew-core](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/argo.rb)

# Use Cases

- Install `argo` on Linux with `brew` command line without compiling

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I did not know brew worked on Linux.

We update as follows:

```
brew bump-formula-pr argo --version 2.11.5
```

The formula is here:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/argo.rb

Would you like to submit a PR to change it?

**Comment by sestegra** [comment]
PR https://github.com/Homebrew/linuxbrew-core/pull/23282

**Comment by sestegra** [comment]
PR done, waiting for merge

**Comment by sestegra** [comment]
PR merged
