### ISSUE TITLE
Archived workflows : no logs available in the Argo UI

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#5966]
## Summary 

What happened/what you expected to happen?

After a workflow is archived, I can see it in the list , I can see the dag but I have an error when I see the logs

I expect to be able to see the logs of an archived workflow

This happens for error and success

Here is a short video

https://user-images.githubusercontent.com/11044877/119147011-7bf68880-ba4b-11eb-88b9-f288902b044e.mov

The full error (which is not very helpful to me, but I hope will be helpful to the dev :))

```
Cannot read property 'findIndex' of undefined
 Reload this page to try again.

Stack Trace
TypeError: Cannot read property 'findIndex' of undefined
    at e.hasArtifactLogs (https://argo.xxx/main.9f418ae91ad79ef83583.js:584:189706)
    at e.getContainerLogsFromArtifact (https://argo.xxx/main.9f418ae91ad79ef83583.js:584:188640)
    at o (https://argo.xxx/main.9f418ae91ad79ef83583.js:584:188988)
    at e.getContainerLogs (https://argo.xxx/main.9f418ae91ad79ef83583.js:584:189036)
    at https://argo.xxx/main.9f418ae91ad79ef83583.js:225:75233
    at fa (https://argo.xxx/main.9f418ae91ad79ef83583.js:516:75256)
    at https://argo.xxx/main.9f418ae91ad79ef83583.js:516:85195
    at Wa (https://argo.xxx/main.9f418ae91ad79ef83583.js:516:82976)
    at Ga (https://argo.xxxmain.9f418ae91ad79ef83583.js:516:90679)
    at Os (https://argo.xxx/main.9f418ae91ad79ef83583.js:516:97823)
Component Stack

    in Unknown
    in div
    in div
    in div
    in Unknown
    in div
    in div
    in div
    in Unknown
    in t
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in div
    in Unknown
    in t
    in t
    in Unknown
    in t
```

## Diagnostics

based on the error message that mentionned getContainerLogsFromArtifact and hasArtifactLogs, I suppose I have someting to do with artifacts

I just added the persistence to do archives, as mentionned in https://github.com/argoproj/argo-workflows/blob/master/docs/workflow-archive.md

so if there is something to do with artifacts for archives, what is it ?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by kulinskyvs** [comment]
I'm facing the same issue with 3.0.2 version

**Comment by alexec** [comment]
This is a small bug in line 225 of `workflow-service.ts`:

```
    private hasArtifactLogs(workflow: Workflow, nodeId: string, container: string) {
        const node = workflow.status.nodes[nodeId];

        if (!node || !node.outputs) {
            return false;
        }

        return node.outputs.artifacts.findIndex(a => a.name === `${container}-logs`) !== -1;
    }
```

@dcherman (original author) @kulinskyvs @christopheblin would you be interested in submitting a PR to fix this?

**Comment by dcherman** [comment]
Sure, fix incoming.  That said, the original bug makes it sound like there were supposed to have been archived logs for this, meaning that the `artifacts` property should have existed.  Even with the bug here fixed, this function would have returned `false`.

**Comment by dcherman** [comment]
Sure, fix incoming.  That said, the original bug makes it sound like there were supposed to have been archived logs for this, meaning that the `artifacts` property should have existed.  Even with the bug here fixed, this function would have returned `false`.

**Comment by christopheblin** [comment]
@alexec @dcherman

does this fix will displays the logs ?

or does something need to be done at the artifact repository level ?

**Comment by tim-sendible** [comment]
Using 3.1-rc6, I cannot see any logs using the UI. I just get "artifact not found".
No errors in the server or controller logs... in fact all the logs I can see suggest that the artifacts have uploaded successfully.

**Comment by dcherman** [comment]
There is likely some other issue here as well - the bug that I patched was legit, but as I mentioned, it would have returned `false` even with my patch which indicates that the workflow has no archived logs (and actually since it threw an exception here, indicates no artifacts at all).

I'd probably re-open this or maybe file another bug for that.  As for some debugging steps, I think one of the first things that I'd do is check the server/controller logs as @tim-sendible mentioned.  Since it sounds like in at least that case it says it was successfully uploaded, I would maybe check the artifact repository itself to determine whether or not the artifacts were actually uploaded - if they were, then that'd suggest that maybe the controller is failing to annotate the workflow with the results of that.

**Comment by tim-sendible** [comment]
If it helps, I have confirmed that the artifact logs are definitely uploaded. Here's how I proved it:

- Install v3.1-rc6 and run a workflow. When completed look at the archived logs (user just gets the error "artifact not found")
- Downgrade to v3.0.4, view that completed workflow in the UI and look at the archived logs.

**Comment by tim-sendible** [comment]
Happy to raise a new bug if that helps keep things clean?

**Comment by alexec** [comment]
This bug is closed. Please raise a new bug for other issue.

**Comment by christopheblin** [comment]
@tim-sendible could you please mention this bug if you open a new one so I can watch it

@alexec you closed the bug but you did not provide any answer for 

> so if there is something to do with artifacts for archives, what is it ?

Is it needed ? why the persistence db is not  used as a storage for the logs ? 

Should I also open another bug for the doc (but I do not know what to use as descritpion beside this bug...) ?
