### ISSUE TITLE
Workflow marked success even when a step failed

### ISSUE THREAD

**Issue by tszngai** [argoproj/argo-workflows#5972]
## Summary 

What happened/what you expected to happen?

As shown in the screenshot below, the workflow was marked green (success) even when a step failed. What I would expect is that any failed step would fail the whole workflow (given that `continueOn` is not used). This seems to be a race condition issue. Sometimes it does fail the whole workflow but sometimes it does not.

![image](https://user-images.githubusercontent.com/41026708/119181266-3378a400-ba26-11eb-9b9c-91bcafe4ef5c.png)

## Diagnostics

What Kubernetes provider are you using?

EKS

What version of Argo Workflows are you running?

v2.12.5

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

K8SAPI

Did this work in a previous version? I.e. is it a regression?

Never tried

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
You're using an unsupported version. Please try v2.12.11 or v3.0.4.
