### ISSUE TITLE
GKE Containerd images and GKE >1.19

### ISSUE THREAD

**Issue by thiago4int** [argoproj/argo-workflows#5976]
# Summary

Sooner or later, Google will force users to adopt containerd as a runtime and discontinue Ubuntu images with Docker runtime. No cluster created with version 1.19 is guaranteed to continue operating Argo Workflow. It would be interesting to have a fix or some guide for Google users.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sdmcclain** [comment]
I recently installed Argo into a new GKE cluster and hit a snag (workflows hanging in Running state) before stumbling on this issue. I updated the Image type to `Ubuntu with Docker (ubuntu)` and things are running smoothly (thanks @thiago4int ). 

It might be worth putting a note in the docs to bring this to new users' attention when creating GKE clusters.

**Comment by max-sixty** [comment]
Does this mean that "Container-Optimized OS from Google" isn't supported? We've been running Argo on that without any issues for a year now.

**Comment by thiago4int** [comment]
@max-sixty Container-Optimized OS with Containerd won work for me

**Comment by brews** [comment]
@max-sixty it works, but there can be a few key snags. I've seen workflows stick around in the Running state long after they've completed on GKE 1.19 with Argo Workflows configured for the Docker executor, like sdmcclain is describing.

**Comment by juanchristensen** [comment]
I've been running Argo Workflows in production on GKE with container optimized OS for ~1 year, the key is changing the executor to PNS or equivalent (the Docker executor does fail)

**Comment by alexec** [comment]
See #5434

**Comment by mattnworb** [comment]
> Does this mean that "Container-Optimized OS from Google" isn't supported? We've been running Argo on that without any issues for a year now.

just want to point out that this is not the same thing as containerd, there are both "Container-Optimized OS with Docker" (`cos`) and "Container-Optimized OS with Containerd" (`cos_containerd`) images: https://cloud.google.com/kubernetes-engine/docs/concepts/node-images#available_node_images

**Comment by alexec** [comment]
Work-around: use PNS executor

**Comment by alexec** [comment]
I think we have a solution.
