### ISSUE TITLE
fatal error: concurrent map read and map write when workflow reaches large amount of nodes

### ISSUE THREAD

**Issue by amitm02** [argoproj/argo-workflows#5979]
Once an Argo workflow get large (Fan out to ~3551 nodes), the Argo controller (V3.1-rc5) crashes with 
"fatal error: concurrent map read and map write"
[controller-crash.txt](https://github.com/argoproj/argo-workflows/files/6530205/controller-crash.txt)

Postgres and Minio pods seem fine.
if relevant, pod strategy was set to:
```
podGC:
  strategy: OnPodSuccess
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gyanprakash48** [comment]
hello @alexec  i am still getting this error on v3.4.3 . Do i need to set any config parameter to fix this , I am using 
podGC:
      strategy: OnPodCompletion
======================================
fatal error: concurrent map read and map write

goroutine 9610 [running]:
runtime.throw({0x21904f7?, 0x1e40460?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc009aa7260 sp=0xc009aa7230 pc=0x438351
runtime.mapaccess2(0xc025141970?, 0xc01e999c00?, 0xc009aa72d8?)
        /usr/local/go/src/runtime/map.go:476 +0x205 fp=0xc009aa72a0 sp=0xc009aa7260 pc=0x40ed85
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).applyExecutionControl(0xc025141970, 0xc01e999c00, 0xc000959fd0?)
        /go/src/github.com/argoproj/argo-workflows/workflow/controller/exec_control.go:23 +0xbc fp=0xc009aa7f60 sp=0xc009aa72a0 pc=0x1bd47dc
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation.func2(0xc0267b1f20?)
        /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1090 +0x97 fp=0xc009aa7fc8 sp=0xc009aa7f60 pc=0x1be49d7
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation.func3()
        /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1092 +0x2a fp=0xc009aa7fe0 sp=0xc009aa7fc8 pc=0x1be490a
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc009aa7fe8 sp=0xc009aa7fe0 pc=0x46b021
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation
        /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1087 +0x215
