### ISSUE TITLE
Archived workflows : no logs without artifact repo ?

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#5996]
## Summary 

This issue is a followup to #5966 that has been closed to say that argo ui does not fail to display logs when there is no artifacts

however, the documentation https://argoproj.github.io/argo-workflows/workflow-archive/ only says that you need to enable database to have archives, not that you also have to configure an artifact repository (and let's say that archives without logs are a bit useless)

## Questions

1. is the artifact repo really needed for logs archives ? if yes, amend the documentation (I can submit a PR for this)

2. is it possible to only use the db (either as a full blown artifact repository or just to store logs) ?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
The workflow archive is only for archiving workflows, not logs. It's a different thing, you need an artifact repository for your logs.

**Comment by christopheblin** [comment]
@alexec 

PR for the documentation : https://github.com/argoproj/argo-workflows/pull/6005

what about using the database to store the logs  of the pods ? 

I was thinking about something like tjis in the configmap :

    archive: true
    logs: true


my understanding is that artefacts are required to save specific data (like a specific file in a container) not to save all the outputs of all the pods... (even if the output of a pod CAN be an artifact in some cases)

can you elaborate a bit on this question plz ?

**Comment by alexec** [comment]
For logs, you can save them as an artifact. Most enterprises simply dump all logs into Splunk or similar.

**Comment by christopheblin** [comment]
@alexec

I configured a minio artifact repository (gateway to azure blob)

When I submit a workflow, I do not have the error anymore BUT  I still do not see the logs

![Capture d’écran 2021-05-26 à 09 54 52](https://user-images.githubusercontent.com/11044877/119623440-75c82980-be08-11eb-9a89-43c9ac2ce1a4.png)

So I suppose that when you said

> For logs, you can save them as an artifact.

Then, I must do something in order to archive the logs in order to see them in the UI

I tried to add archiveLogs:true in the template (figured out from https://github.com/argoproj/argo-workflows/blob/master/examples/archive-location.yaml)

    archiveLocation:
        archiveLogs: true

however, I then have the error

`Pod failed: Error (exit code 1): key unsupported: cannot get key for artifact location, because it is invalid" displayName=hello-world-m8t54 namespace=staging-argo pod=hello-world-m8t54 templateName=whalesay workflow=hello-world-m8t54`

**Any help appreciated in order to understand what I should do to "automatically" archive the logs of a pod to the default artifact repository**

Here is the workflow template submitted:
```

metadata:
  name: hello-world
spec:
  templates:
    - name: whalesay
      container:
        name: ''
        image: 'docker/whalesay:latest'
        command:
          - cowsay
        args:
          - hello world
  entrypoint: whalesay
  serviceAccountName: argo
  ttlStrategy:
    secondsAfterSuccess: 30
    secondsAfterFailure: 3600
```

And the logs of the controller (you can see that the artifact repository is detected, note that I removed non important messages)

```
time="2021-05-26T07:50:04.343Z" level=info msg="Processing workflow" namespace=staging-argo workflow=hello-world-jg8r2
time="2021-05-26T07:50:04.355Z" level=info msg="Get workflowtemplates 200"
time="2021-05-26T07:50:04.376Z" level=info msg="Get workflowtemplates 200"
time="2021-05-26T07:50:04.383Z" level=info msg="Get configmaps 404"
time="2021-05-26T07:50:04.383Z" level=warning msg="Non-transient error: configmaps \"artifact-repositories\" not found"
time="2021-05-26T07:50:04.383Z" level=info msg="resolved artifact repository" artifactRepositoryRef=default-artifact-repository
time="2021-05-26T07:50:04.383Z" level=info msg="Updated phase  -> Running" namespace=staging-argo workflow=hello-world-jg8r2
time="2021-05-26T07:50:04.392Z" level=info msg="Create events 201"
time="2021-05-26T07:50:04.397Z" level=info msg="Pod node hello-world-jg8r2 initialized Pending" namespace=staging-argo workflow=hello-world-jg8r2
time="2021-05-26T07:50:04.419Z" level=info msg="Create pods 201"
time="2021-05-26T07:50:04.420Z" level=info msg="Created pod: hello-world-jg8r2 (hello-world-jg8r2)" namespace=staging-argo workflow=hello-world-jg8r2
time="2021-05-26T07:50:04.430Z" level=info msg="Update workflows 200"
time="2021-05-26T07:50:04.464Z" level=info msg="Workflow update successful" namespace=staging-argo phase=Running resourceVersion=410713492 workflow=hello-world-jg8r2
time="2021-05-26T07:50:14.421Z" level=info msg="Processing workflow" namespace=staging-argo workflow=hello-world-jg8r2
time="2021-05-26T07:50:14.422Z" level=info msg="Updating node hello-world-jg8r2 message: ContainerCreating" namespace=staging-argo workflow=hello-world-jg8r2
time="2021-05-26T07:50:14.432Z" level=info msg="Update workflows 200"
time="2021-05-26T07:50:14.432Z" level=info msg="Workflow update successful" namespace=staging-argo phase=Running resourceVersion=410713982 workflow=hello-world-jg8r2
time="2021-05-26T07:50:34.411Z" level=info msg="Processing workflow" namespace=staging-argo workflow=hello-world-jg8r2
time="2021-05-26T07:50:34.412Z" level=info msg="Updating node hello-world-jg8r2 exit code 0" namespace=staging-argo workflow=hello-world-jg8r2
time="2021-05-26T07:50:34.412Z" level=info msg="Updating node hello-world-jg8r2 status Pending -> Succeeded" namespace=staging-argo workflow=hello-world-jg8r2
time="2021-05-26T07:50:34.412Z" level=info msg="Updated phase Running -> Succeeded" namespace=staging-argo workflow=hello-world-jg8r2
time="2021-05-26T07:50:34.412Z" level=info msg="Marking workflow completed" namespace=staging-argo workflow=hello-world-jg8r2
time="2021-05-26T07:50:34.412Z" level=info msg="Marking workflow as pending archiving" namespace=staging-argo workflow=hello-world-jg8r2
time="2021-05-26T07:50:34.412Z" level=info msg="Checking daemoned children of " namespace=staging-argo workflow=hello-world-jg8r2
time="2021-05-26T07:50:34.427Z" level=info msg="Create events 201"
time="2021-05-26T07:50:34.429Z" level=info msg="Update workflows 200"
time="2021-05-26T07:50:34.429Z" level=info msg="Workflow update successful" namespace=staging-argo phase=Succeeded resourceVersion=410714415 workflow=hello-world-jg8r2
time="2021-05-26T07:50:34.433Z" level=info msg="archiving workflow" namespace=staging-argo uid=19582363-d25c-454c-832a-81b3dfd1c355 workflow=hello-world-jg8r2
time="2021-05-26T07:50:34.437Z" level=info msg="Create events 201"
time="2021-05-26T07:50:34.439Z" level=info msg="cleaning up pod" action=labelPodCompleted key=staging-argo/hello-world-jg8r2/labelPodCompleted
time="2021-05-26T07:50:34.444Z" level=info msg="Create events 201"
time="2021-05-26T07:50:34.449Z" level=info msg="Patch pods 200"
time="2021-05-26T07:50:34.528Z" level=info msg="Patch workflows 200"
time="2021-05-26T07:50:34.529Z" level=info msg="archiving workflow" namespace=staging-argo uid=19582363-d25c-454c-832a-81b3dfd1c355 workflow=hello-world-jg8r2
time="2021-05-26T07:50:34.530Z" level=info msg="Queueing Succeeded workflow staging-argo/hello-world-jg8r2 for delete in 30s"
time="2021-05-26T07:50:34.531Z" level=info msg="Queueing Succeeded workflow staging-argo/hello-world-jg8r2 for delete in 30s"
time="2021-05-26T07:50:34.594Z" level=info msg="Patch workflows 200"
time="2021-05-26T07:51:05.000Z" level=info msg="Deleting TTL expired workflow 'staging-argo/hello-world-jg8r2'"
time="2021-05-26T07:51:05.025Z" level=info msg="Delete workflows 200"
time="2021-05-26T07:51:05.025Z" level=info msg="Successfully deleted 'staging-argo/hello-world-jg8r2'"

```

**Comment by christopheblin** [comment]
note that I am aware that I can use "pipe-tee" into a file + declare an ouput artifact (obviously, like a "normal" artifact)

however, I do not like the idea to change all my templates to do that just for the "sake" of archives, so I am looking to an "automatic" approach

if you are interested into the pipe-tee approach, have a look at https://github.com/argoproj/argo-workflows/blob/4e450e250168e6b4d51a126b784e90b11a0162bc/test/e2e/expectedfailures/output-artifact-not-optional.yaml

**Comment by alexec** [comment]
I think you may have found a bug. Can you please attach the version you're using?

**Comment by christopheblin** [comment]
I am using docker.io/argoproj/workflow-controller:latest from this morning in my TZ :)

how can I see version ? I tried to use logs/describe of argo-server and workflow-controller pods, but I cannot see a version there ...

**Comment by christopheblin** [comment]
The correct way to have automatic logs is to use the configmap (either controller CM or a new artifact-repositories CM), see https://github.com/argoproj/argo-workflows/issues/5983#issuecomment-849010919

@alexec unless you suspect another problem, you can close this issue (and thank you for the support 👍 )
