### ISSUE TITLE
TestResourceTemplateStopAndTerminate test failing on master

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6008]
```
    --- FAIL: TestCLISuite/TestNodeSuspendResume (66.86s)
    --- FAIL: TestCLISuite/TestResourceTemplateStopAndTerminate (7.45s)
        --- FAIL: TestCLISuite/TestResourceTemplateStopAndTerminate/ResourceTemplateStop (2.90s)
        --- FAIL: TestCLISuite/TestResourceTemplateStopAndTerminate/ResourceTemplateTerminate (4.46s)
```

**Comment by alexec** [comment]
Probably caused by #5951. @wreed4 can you tell me if you'll be able to look into this in the next couple of hours? If not, I'll have to revert your PR to prevent problems for other users.

**Comment by alexec** [comment]
failing builds:

https://github.com/argoproj/argo-workflows/actions/workflows/ci-build.yaml?query=branch%3Amaster

**Comment by alexec** [comment]
```
    --- FAIL: TestCLISuite/TestResourceTemplateStopAndTerminate (6.53s)
        --- FAIL: TestCLISuite/TestResourceTemplateStopAndTerminate/ResourceTemplateStop (3.20s)
        --- FAIL: TestCLISuite/TestResourceTemplateStopAndTerminate/ResourceTemplateTerminate (3.21s)
```

**Comment by alexec** [comment]
```
Error (exit code 1): The resource has been deleted while its status was still being checked. Will not be retried: the server could not find the requested resource
```

**Comment by alexec** [comment]
OK. The real cause is:

Yuan Tang* Today 08:26 fix(executor): Fix compatibility issue with k8s>=1.21 when selfLink is no longer populated (#5992)

@terrytangyuan

**Comment by alexec** [comment]
Calculated URL is wrong:

```
apis/argoproj.io/v1alpha1/namespaces/argo/Workflow/hello-world-zwmhk apis/argoproj.io/v1alpha1/namespaces/argo/workflows/hello-world-zwmhk
```

**Comment by alexec** [comment]
@terrytangyuan the URL is wrong in your PR. It was not picked up by the CI because `test-cli` pulls the image from hub.docker, and `test-executor` does not have a test for this (which it probably should).

I will revert you commit because turning kind into resource is non-trivial.

**Comment by terrytangyuan** [comment]
Thanks for the note. I'll look into that separately with additional tests later.

> It was not picked up by the CI because test-cli pulls the image from hub.docker

Are we doing this because pulling from hub.docker significantly reduces the build time? It would be great if we could catch this in PR builds.

**Comment by alexec** [comment]
> Are we doing this because pulling from hub.docker significantly reduces the build time? It would be great if we could catch this in PR builds.

Yes. Saves about 4m per build.
