### ISSUE TITLE
Workflow loop creates all pods at the same time if pods are in pending state

### ISSUE THREAD

**Issue by jopfeffe** [argoproj/argo-workflows#6034]
## Summary 

This Bug was already described as part of #5811. 

When a workflow containing a loop is started and there are pending pods due to resource limits all pods are created at the same time. 

If “parallelism” is set low enough to fit the available resource limits pods are only created if others are finished. I would expect the same behavior for pending state pods to avoid flooding the cluster in case of a huge number of loop items.

## Diagnostics

What Kubernetes provider are you using? 
Rancher

What version of Argo Workflows are you running? 
3.0.4

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
K8sapi

Did this work in a previous version? I.e. is it a regression?
not sure

Check out pevious ticket for Workflow YAML + logs.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I think you're saying that if we have a loop, and pods are creating in the pending state, we should not create other pods until those first pods are complete?

I'm not sure this is possible, the Kubernetes API returns the new pod, and it will be in pending, but we may not know why it is in pending. 

Parallelism is the right solution for limiting the number of running pods.

**Comment by jopfeffe** [comment]
Yes, that's correct. But wouldn't it be correct to also limit the number of parallel pending pods? 

Example:
A loop containing 10 pods is executed. Due to cpu limit only one pod can be executed at a time. But parallelism is set to two. Now all pods are generated at the same time. 
When now the limit in the cluster is increased so that based on the cpu limit 10 pods will fit, wouldn't these pods be executed at the same time now even if parallelism is set to two?

I might be wrong about that - hadn't the chance to test it.

**Comment by alexec** [comment]
I'm not clear what you are saying on this. Could you please attach an example of your workflow?

**Comment by jopfeffe** [comment]
Hi alexec, i just had a look. Unfortunately I couldn't test it fully but I think I might have been wrong. All items of the loop are in fact still displayed at the same time in the Argo UI. However this might be not a problem as the corresponding pods are not created. So I don't think that all steps are executed at the same time as soon sufficient resources are available.

I basically thought that every pending step in the UI represents a pod in the cluster and now K8s is caring whether it gets processed or not. Hence why I thought that Argo has no control anymore to ensure parallelism.

If you can confirm that his is wrong I think this ticket can be closed.
