### ISSUE TITLE
Empty response from argo-server load balancer

### ISSUE THREAD

**Issue by saranyaeu2987** [argoproj/argo-workflows#6038]
## Summary 

exposed argo-server (in AWS EKS) as a class load balancer. curl to load balancer resulted in curl: (52) Empty reply from server. No errors reported in logs

## Diagnostics

EKS K8S version: 1.19
argo workflows: 3.0.3
Did this work in a previous version? 2.11. yes

**`curl http://internal-aadaef732edc04a9c8c4c6194dc26118-1332003381.us-east-1.elb.amazonaws.com:2746 -v`**

> *   Trying 10.207.194.26...
> * TCP_NODELAY set
> * Connected to internal-aadaef732edc04a9c8c4c6194dc26118-1332003381.us-east-1.elb.amazonaws.com (10.207.194.26) port 2746 (#0)
> > GET / HTTP/1.1
> > Host: internal-aadaef732edc04a9c8c4c6194dc26118-1332003381.us-east-1.elb.amazonaws.com:2746
> > User-Agent: curl/7.64.1
> > Accept: */*
> > 
> * Empty reply from server
> * Connection #0 to host internal-aadaef732edc04a9c8c4c6194dc26118-1332003381.us-east-1.elb.amazonaws.com left intact
> curl: (52) Empty reply from server
> * Closing connection 0
> 

**`kubectl describe service argo-server    `**  

> Name:                     argo-server
> Namespace:                argo
> Labels:                   <none>
> Annotations:              kubectl.kubernetes.io/last-applied-configuration:
>                             {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-internal":"true"},"name":"arg...
>                           service.beta.kubernetes.io/aws-load-balancer-internal: true
> Selector:                 app=argo-server
> Type:                     LoadBalancer
> IP:                       172.20.51.81
> LoadBalancer Ingress:     internal-aadaef732edc04a9c8c4c6194dc26118-1332003381.us-east-1.elb.amazonaws.com
> Port:                     web  2746/TCP
> TargetPort:               2746/TCP
> NodePort:                 web  30950/TCP
> Endpoints:                10.207.204.128:2746
> Session Affinity:         None
> External Traffic Policy:  Cluster
> Events:
>   Type    Reason                Age   From                Message
>   ----    ------                ----  ----                -------
>   Normal  EnsuringLoadBalancer  10m   service-controller  Ensuring load balancer
>   Normal  EnsuredLoadBalancer   10m   service-controller  Ensured load balancer

**`kubectl get pods    `**                              

> NAME                                   READY   STATUS    RESTARTS   AGE
> argo-server-5587c577c5-qrhck           1/1     Running   2          17m
> minio-6d5bcb69f7-vf5kh                 1/1     Running   0          17m
> postgres-6d48bcb556-9vgzh              1/1     Running   0          17m
> workflow-controller-85c4bf49cd-nk9qx   1/1     Running   2          17m

**`kubectl get svc argo-server -n argo -o yaml `**

> apiVersion: v1
> kind: Service
> metadata:
>   annotations:
>     kubectl.kubernetes.io/last-applied-configuration: |
>       {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-internal":"true"},"name":"argo-server","namespace":"argo"},"spec":{"ports":[{"name":"web","port":2746,"targetPort":2746}],"selector":{"app":"argo-server"},"type":"LoadBalancer"}}
>     service.beta.kubernetes.io/aws-load-balancer-internal: "true"
>   creationTimestamp: "2021-05-27T18:46:26Z"
>   finalizers:
>   - service.kubernetes.io/load-balancer-cleanup
>   managedFields:
>   - apiVersion: v1
>     fieldsType: FieldsV1
>     manager: kubectl
>     operation: Update
>     time: "2021-05-27T18:46:26Z"
>   - apiVersion: v1
>     fieldsType: FieldsV1
>     fieldsV1:
>       f:metadata:
>         f:finalizers:
>           .: {}
>           v:"service.kubernetes.io/load-balancer-cleanup": {}
>       f:status:
>         f:loadBalancer:
>           f:ingress: {}
>     manager: kube-controller-manager
>     operation: Update
>     time: "2021-05-27T18:46:29Z"
>   name: argo-server
>   namespace: argo
>   resourceVersion: "73546565"
>   selfLink: /api/v1/namespaces/argo/services/argo-server
>   uid: adaef732-edc0-4a9c-8c4c-6194dc26118e
> spec:
>   clusterIP: 172.20.51.81
>   externalTrafficPolicy: Cluster
>   ports:
>   - name: web
>     nodePort: 30950
>     port: 2746
>     protocol: TCP
>     targetPort: 2746
>   selector:
>     app: argo-server
>   sessionAffinity: None
>   type: LoadBalancer
> status:
>   loadBalancer:
>     ingress:
>     - hostname: internal-aadaef732edc04a9c8c4c6194dc26118-1332003381.us-east-1.elb.amazonaws.com

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Please check  https://argoproj.github.io/argo-workflows/faq/

**Comment by saranyaeu2987** [comment]
Understood. TLS resolved the issue
