### ISSUE TITLE
UI: Make logs searchable

### ISSUE THREAD

**Issue by cscetbon** [argoproj/argo-workflows#6059]
Summary

When looking at a workflow, we often need to check its logs and look through them. Unfortunately, the way they're displayed in the browser doesn't make them searchable using the search function or browsers like Safari or Chrome. We end up with copy/pasting logs to another place and search through them and it's overcomplex.
There should be a way to look through logs without such a complexity.

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This seems like a good idea.

**Comment by alexec** [comment]
![image](https://user-images.githubusercontent.com/1142830/120406811-9ad50480-c300-11eb-8f51-3e0ca3ccb984.png)

**Comment by cscetbon** [comment]
Thanks @alexec, you're fast !
