### ISSUE TITLE
In the workflows screen of Argo UI, add a 'select/deselect all' button.

### ISSUE THREAD

**Issue by amitm02** [argoproj/argo-workflows#6069]
# Summary

In the workflows screen of Argo UI, add a 'select/deselect all' button.
<img width="1670" alt="suggest" src="https://user-images.githubusercontent.com/1888927/120483636-f95eb900-c3ba-11eb-8b3c-baea8ffee23c.png">

# Use Cases

If one want to clean all workflows, it can get tedious to mark the workflows one by one in order to delete them 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This is a good idea. Would you like to submit a PR?

**Comment by amitm02** [comment]
Unfortunately, not a React or Go developer.  : (
My contribution to the Argo project will be limited to QA and surfacing needs and issues when it comes to using Argo in real life.
