### ISSUE TITLE
when an input artifact does not exist, the error message is cryptic

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#6070]
## Summary 

create a template that is using an S3 input artifact (cf https://github.com/argoproj/argo-workflows/blob/master/examples/input-artifact-s3.yaml)

if you specify a wrong artifact, the error is "The specified key does not exist."

I suspect this error directly comes from the S3 library (maybe directly from S3 server, I do not know exactly)

This is not very user friendly or helpful

Moreover, the controller logs are also not very useful about this error :

```
time="2021-06-02T08:54:15.181Z" level=info msg="Processing workflow" namespace=staging-argo workflow=dataset-v2-7w5lf
time="2021-06-02T08:54:15.182Z" level=info msg="Pod failed: Error (exit code 1): The specified key does not exist." displayName=config namespace=staging-argo pod=dataset-v2-7w5lf-3546387270 templateName=dataset-v2-config workflow=dataset-v2-7w5lf
time="2021-06-02T08:54:15.182Z" level=info msg="Updating node dataset-v2-7w5lf-3546387270 status Pending -> Error" namespace=staging-argo workflow=dataset-v2-7w5lf
time="2021-06-02T08:54:15.182Z" level=info msg="Updating node dataset-v2-7w5lf-3546387270 message: Error (exit code 1): The specified key does not exist." namespace=staging-argo workflow=dataset-v2-7w5lf
```

in my case, the name of the artifact is generated from the workflow inputs (it is not a constant) so it took a bit of time to analyze why this error was popping up

An error like "Cannot retrieve artifact <artifact_name> : the specified key does not exist" would have tremendeously reduced the debug time

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by shuker85** [comment]
:+1:
