### ISSUE TITLE
API Authentication with SSO

### ISSUE THREAD

**Issue by giordyb** [argoproj/argo-workflows#6078]
## Summary 

Hi,

I have Argo Workflow 3.0.7 working with the SSO authentication configured (authenticating against a Keycloak server), I am able to login, access the web interface and launch workflows with a user in the Keycloak realm.

I am now trying to do the same thing via API but unfortunately when I try to pass the token that I get from Keycloak in the API request I get the following error: ""token not valid for running mode"

I am requesting the token from Keycloak via this url: https://keycloak/auth/realms/realm/protocol/openid-connect/token 

Is there a different token that I need to request from Keycloak? 

Thanks,

Giordano
## Diagnostics

What Kubernetes provider are you using? 

Kubernetes 1.19.7 on AKS

What version of Argo Workflows are you running? 

3.0.7

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

Did this work in a previous version? I.e. is it a regression?

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

```
Paste the logs from your workflow's wait container:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
You should not use SSO token for API access. Please using client auth-mode with an aceoss token. You can find out how to do this is in the docs.

**Comment by giordyb** [comment]
Hi @alexec that's exactly what I am doing right now. 
If the external auth is not supported for the APIs then the issue can be closed.

thanks,

Giordano
