### ISSUE TITLE
error converting YAML to JSON: yaml: line 103: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by ninoamine** [argoproj/argo-workflows#6080]
## Summary 

When applying argo workflow manifest I get this error:
error converting YAML to JSON: yaml: line 103: mapping values are not allowed in this context
## Diagnostics

kubectl version:
Client Version: v1.20.0", 
Server Version: "v1.18.8"

Argo Workflow version:
Stable

**Comment by shuker85** [comment]
Can you post your workflow pls?

**Comment by sarabala1979** [comment]
try to lint your workflow. http://www.yamllint.com/
