### ISSUE TITLE
Workflow hangs

### ISSUE THREAD

**Issue by fire** [argoproj/argo-workflows#6117]
## Summary 

When I submit argo a workflow it doesn't complete. `submit -n argo --watch argo-dag.yml`

https://github.com/V-Sekai/workflow-maroon-steel-cat

I am surveying github workflows.

## Diagnostics

What Kubernetes provider are you using? 

k3d

What version of Argo Workflows are you running? 

argo: v3.0.7

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

Kubelet? I'm not sure.

Did this work in a previous version? I.e. is it a regression?

This has never worked for me.

```bash
# Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:
# See logs https://github.com/V-Sekai/workflow-maroon-steel-cat/runs/2788510304
# https://raw.githubusercontent.com/V-Sekai/workflow-maroon-steel-cat/main/argo-dag.yml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:
  - name: sleep
    container:
      image: fedora:34
      command: [sleep, "10"]
  - name: diamond
    dag:
      tasks:
      - name: A
        template: sleep
      - name: B
        dependencies: [A]
        template: sleep
      - name: C
        dependencies: [A]
        template: sleep
      - name: D
        dependencies: [B, C]
        template: sleep
```

```bash
# I don't know how to get these logs.
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

Here's a copy of the logs.

[logs_76.zip](https://github.com/argoproj/argo-workflows/files/6627383/logs_76.zip)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you try with `argoproj/argoexec:latest`?

**Comment by fire** [comment]
How do I enable that?

**Comment by fire** [comment]
It probably is a different problem then. https://github.com/V-Sekai/workflow-maroon-steel-cat/runs/2788738856?check_suite_focus=true

**Comment by sarabala1979** [comment]
@fire can you provide `pod yaml`  `kubectl get pods dag-diamond-pbrg9-3037433362 -o yaml`
`kubectl logs dag-diamond-pbrg9-3037433362 wait`

**Comment by sarabala1979** [comment]
@fire can you import `argoproj/argoexec:latest` before you submit the workflow?
`k3d image import argoproj/argoexec:latest`

**Comment by fire** [comment]
I can change it to `argo submit -n argo argo-dag.yml` without watch.

However, I'd need to a command to find the exact pod and then it's logs. I'm not as skilled at k8s.

**Comment by sarabala1979** [comment]
Get all workflow pods `kubectl get pods  | grep <wfname>`

**Comment by fire** [comment]
You can see the pod isn't starting https://github.com/V-Sekai/workflow-maroon-steel-cat/runs/2789192437?check_suite_focus=true

**Comment by fire** [comment]
I can recreate this with k3d and docker on Windows.

**Comment by fire** [comment]
I am trying https://github.com/argoproj/argo-workflows/issues/5243#issuecomment-792993742.

**Comment by fire** [comment]
Thanks. It works now!

Please document using `k8sapi`.

https://github.com/V-Sekai/workflow-maroon-steel-cat/runs/2789308315?check_suite_focus=true
