### ISSUE TITLE
failure when waiting a sub-workflow 

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#6118]
## Summary 

I have a workflow that launches another workflow

While it waits for the end, I have an error

The error happens after many "tries" (I'd say around 58 calls succeeded before this failure, see attached logs.txt)

```
time="2021-06-10T08:28:54.662Z" level=info msg="Waiting for resource workflow.argoproj.io/coverage-ddr8q in namespace production-argo resulted in retryable error: Neither success condition nor the failure condition has been matched. Retrying..."
time="2021-06-10T08:29:29.645Z" level=warning msg="Non-transient error: Get \"https://10.2.0.1:443/apis/argoproj.io/v1alpha1/namespaces/production-argo/workflows/coverage-ddr8q?timeout=32s\": dial tcp 10.2.0.1:443: i/o timeout"
time="2021-06-10T08:29:29.645Z" level=warning msg="Waiting for resource workflow.argoproj.io/coverage-ddr8q in namespace production-argo resulted in non-retryable error: Get \"https://10.2.0.1:443/apis/argoproj.io/v1alpha1/namespaces/production-argo/workflows/coverage-ddr8q?timeout=32s\": dial tcp 10.2.0.1:443: i/o timeout"
time="2021-06-10T08:29:29.645Z" level=warning msg="Waiting for resource workflow.argoproj.io/coverage-ddr8q resulted in error Get \"https://10.2.0.1:443/apis/argoproj.io/v1alpha1/namespaces/production-argo/workflows/coverage-ddr8q?timeout=32s\": dial tcp 10.2.0.1:443: i/o timeout"
time="2021-06-10T08:29:29.646Z" level=error msg="executor error: Get \"https://10.2.0.1:443/apis/argoproj.io/v1alpha1/namespaces/production-argo/workflows/coverage-ddr8q?timeout=32s\": dial tcp 10.2.0.1:443: i/o timeout"
time="2021-06-10T08:29:29.646Z" level=fatal msg="Get \"https://10.2.0.1:443/apis/argoproj.io/v1alpha1/namespaces/production-argo/workflows/coverage-ddr8q?timeout=32s\": dial tcp 10.2.0.1:443: i/o timeout"
```

In the controller logs, I only see
```
time="2021-06-10T08:29:32.789Z" level=info msg="Get leases 200"
time="2021-06-10T08:29:32.796Z" level=info msg="Update leases 200"
time="2021-06-10T08:29:37.041Z" level=info msg="Processing workflow" namespace=production-argo workflow=coverage-with-datasets-qqxz4
time="2021-06-10T08:29:37.041Z" level=info msg="Processing workflow" namespace=production-argo workflow=coverage-ddr8q
time="2021-06-10T08:29:37.042Z" level=info msg="Pod failed: Error (exit code 1): Get \"https://10.2.0.1:443/apis/argoproj.io/v1alpha1/namespaces/production-argo/workflows/coverage-ddr8q?timeout=32s\": dial tcp 10.2.0.1:443: i/o timeout" displayName=execute-coverage namespace=production-argo pod=coverage-with-datasets-qqxz4-3823387678 templateName=coverage-with-datasets-execute-coverage workflow=coverage-with-datasets-qqxz4
time="2021-06-10T08:29:37.042Z" level=info msg="Updating node coverage-with-datasets-qqxz4-3823387678 exit code 1" namespace=production-argo workflow=coverage-with-datasets-qqxz4
time="2021-06-10T08:29:37.042Z" level=info msg="Updating node coverage-with-datasets-qqxz4-3823387678 status Running -> Failed" namespace=production-argo workflow=coverage-with-datasets-qqxz4
```

Do you have any idea to what I can look for ?

the number of pods launched by argo is not so high (around 30) and the cluster did not have any noticeable troubles while the workflow was running ...

full logs : [logs.txt](https://github.com/argoproj/argo-workflows/files/6629806/logs.txt)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I/o timeout should be considered transient. 

@terrytangyuan would you be interested in looking into this?

**Comment by alexec** [comment]
@christopheblin do you know want version this by is in? Do you know if it is a regression?

**Comment by christopheblin** [comment]
this is in 3.1.0-rc12

no idea if this is a regression

**Comment by terrytangyuan** [comment]
I'll look into this. `i/o timeout` should have been retried but looks like it didn't.

**Comment by terrytangyuan** [comment]
Submitted https://github.com/argoproj/argo-workflows/pull/6134 to fix this. `"i/o timeout"` is already covered in transient errors so the problem should be that we are not checking all the errors from `checkResourceState()`.

**Comment by gyanprakash48** [comment]
@christopheblin  did you find solution for this , i am facing same situation , getting below error  

time="2023-01-12T11:56:09.557Z" level=info msg="Get workflows 200"
time="2023-01-12T11:56:09.563Z" level=info msg="failure condition '{status.phase in [Error Failed]}' evaluated false"
time="2023-01-12T11:56:09.565Z" level=info msg="success condition '{status.phase == [Succeeded]}' evaluated false"
time="2023-01-12T11:56:09.565Z" level=info msg="0/1 success conditions matched"
time="2023-01-12T11:56:09.565Z" level=info msg="Waiting for resource workflow.argoproj.io/uss-bytesoup-generator-m52pg in namespace argo resulted in retryable error: Neither success condition nor the failure condition has been matched. Retrying..."
time="2023-01-12T11:56:14.578Z" level=info msg="Get workflows 200"
time="2023-01-12T11:56:14.593Z" level=info msg="failure condition '{status.phase in [Error Failed]}' evaluated false"
time="2023-01-12T11:56:14.595Z" level=info msg="success condition '{status.phase == [Succeeded]}' evaluated false"
time="2023-01-12T11:56:14.595Z" level=info msg="0/1 success conditions matched"
time="2023-01-12T11:56:14.595Z" level=info msg="Waiting for resource workflow.argoproj.io/uss-bytesoup-generator-m52pg in namespace argo resulted in retryable error: Neither success condition nor the failure condition has been matched. Retrying..."
time="2023-01-12T11:56:21.688Z" level=info msg="Transient error: Get \"https://172.16.0.1:443/apis/argoproj.io/v1alpha1/namespaces/argo/workflows/uss-bytesoup-generator-m52pg\": unexpected EOF"
time="2023-01-12T11:56:21.688Z" level=info msg="Waiting for resource workflow.argoproj.io/uss-bytesoup-generator-m52pg in namespace argo resulted in retryable error: Get \"https://172.16.0.1:443/apis/argoproj.io/v1alpha1/namespaces/argo/workflows/uss-bytesoup-generator-m52pg\": unexpected EOF"
time="2023-01-12T11:56:36.719Z" level=warning msg="Non-transient error: Get \"https://172.16.0.1:443/apis/argoproj.io/v1alpha1/namespaces/argo/workflows/uss-bytesoup-generator-m52pg\": dial tcp 172.16.0.1:443: connect: connection refused"
time="2023-01-12T11:56:36.719Z" level=warning msg="Waiting for resource workflow.argoproj.io/uss-bytesoup-generator-m52pg in namespace argo resulted in non-retryable error: Get \"https://172.16.0.1:443/apis/argoproj.io/v1alpha1/namespaces/argo/workflows/uss-bytesoup-generator-m52pg\": dial tcp 172.16.0.1:443: connect: connection refused"
time="2023-01-12T11:56:36.719Z" level=warning msg="Waiting for resource workflow.argoproj.io/uss-bytesoup-generator-m52pg resulted in error Get \"https://172.16.0.1:443/apis/argoproj.io/v1alpha1/namespaces/argo/workflows/uss-bytesoup-generator-m52pg\": dial tcp 172.16.0.1:443: connect: connection refused"
time="2023-01-12T11:56:36.719Z" level=error msg="executor error: Get \"https://172.16.0.1:443/apis/argoproj.io/v1alpha1/namespaces/argo/workflows/uss-bytesoup-generator-m52pg\": dial tcp 172.16.0.1:443: connect: connection refused"
time="2023-01-12T11:56:36.719Z" level=fatal msg="Get \"https://172.16.0.1:443/apis/argoproj.io/v1alpha1/namespaces/argo/workflows/uss-bytesoup-generator-m52pg\": dial tcp 172.16.0.1:443: connect: connection refused"
time="2023-01-12T11:56:37.507Z" level=info msg="sub-process exited" argo=true error="<nil>"
