### ISSUE TITLE
Resubmit an archived workflow from UI does not keep labels

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#6129]
## Summary 

From an archived workflow, click on "Resubmit" in the UI

The created workflow do not have the appropriate labels

/!\ the bug happens only for archived workflows (when you resubmit a "normal" workflow, the labels are kept)

Be cautious, some labels should not be copied (like workflows.argoproj.io or workflows.argoproj.io/phase)

however, the labels placed manually by the user should be duplicated

rational : labels are used to search workflows, so if they do not have labels they do not appear in search results anymore ...

I am not sure to consider bug or enhancement ...

root cause : when you resubmit an archived workflow, the UI is different from a normal workflow (in archive, you use a YAML where the labels are not preloaded whereas in normal it is just asking a confirmation)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
It’s pretty clear there’s a bug on this line:

https://github.com/argoproj/argo-workflows/blob/db95dbfa1edd4a31b1fbd6adbb8e47ca8f2ac428/ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx#L228

You can see that neither labels or annotations are copied. 

Would you like to submit a PR to fix?

**Comment by christopheblin** [comment]
@alexec I did my best to provide the PR, I hope it will be enough :)

**Comment by agilgur5** [comment]
> /reopen

This is no longer needed per https://github.com/argoproj/argo-workflows/pull/6184#issuecomment-2436430942
