### ISSUE TITLE
Workflow did not retry get workflowtemplates when the server was busy

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-workflows#6163]
## Summary 

The K8s api server responded with "the server has received too many requests and has asked us to try again later" and the Workflow did not retry again later.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 

EKS

What version of Argo Workflows are you running? 

v2.12.9

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

PNS

Did this work in a previous version? I.e. is it a regression?

not sure

Are you pasting thousands of log lines? That's too much information. 

```
argo get task-environment-config-update-g995c
Name:                task-environment-config-update-g995c
Namespace:           polaris-system
ServiceAccount:      task-environment-config-update
Status:              Failed
Message:             invalid spec: templates.main.steps[0].create-newrelic-secret the server has received too many requests and has asked us to try again later (get workflowtemplates.argoproj.io resource-create-template)
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Thanks. https://github.com/argoproj/argo-workflows/pull/6178 should fix this.
