### ISSUE TITLE
YAML to Python transpiler

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6164]
It would be awesome to be able to convert YAML into Python.

@terrytangyuan

**Comment by terrytangyuan** [comment]
This could be interesting but I am not sure what use cases there are (Python to YAML is useful but probably not the other way around). Do you have anything in mind?

**Comment by alexec** [comment]
The goal is to help users get started using Python, by having some Python (I.e Couler) examples.

In Argo Dataflow, all YAML examples are writing in Python and the build script runs the transpiler to create the YAML examples.

So maybe a better way of achieving the goal would be to add versions of common examples in Python. 

@terrytangyuan would you be interested in helping doing this?

**Comment by terrytangyuan** [comment]
Are you suggesting that we add Python examples in this repo? Here are some things to consider:
1. Currently there's still feature parity between Couler and Argo Workflows. Some features are not available in Couler yet so there isn't straightforward 1-to-1 mapping between YAML and Python examples.
2. Writing a transpiler may not be trivial when the example gets more complicated.
3. Couler is still under active development. If the Python examples are located in this repo, they may get outdated very easily. 

Instead, perhaps for now we can add a link to Couler's examples in the Argo Workflows' docs and then leave the actual examples in Couler's repo to avoid duplicate maintenance efforts?

**Comment by alexec** [comment]
I think links would be fine. Perhaps we could add the link in the description annotation?

**Comment by terrytangyuan** [comment]
Sounds good. I'll add some links to the annotations.
