### ISSUE TITLE
plz add pagination.

### ISSUE THREAD

**Issue by Nash-x9** [argoproj/argo-workflows#6171]
# Summary

thk u for your awesome project ,Plz add pagination,Now I use api to show my workflows, isn't so hard to use without pagination.

# Use Cases

Show my workflows.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I think we do have pagination on the workflow list page if that's the page you mean?

**Comment by Nash-x9** [comment]
> I think we do have pagination on the workflow list page if that's the page you mean?

How do I start page numbers on a specific page?

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/blob/master/api/openapi-spec/swagger.json#L2564

You must use `limit` and `continue`. It is not possible to jump directly to a page.
