### ISSUE TITLE
Implement WatchEvents for argoKubeWorkflowServiceClient

### ISSUE THREAD

**Issue by wwwaldo** [argoproj/argo-workflows#6173]
# Summary

Right now WatchEvents is implemented for the Argo API Server client. The Argo Kube client doesn't seem to implement it, see [here](https://github.com/argoproj/argo-workflows/blob/master/pkg/apiclient/argo-kube-workflow-service-client.go#L46):

```
func (c *argoKubeWorkflowServiceClient) WatchEvents(context.Context, 
*workflowpkg.WatchEventsRequest, ...grpc.CallOption) (workflowpkg.WorkflowService_WatchEventsClient, error)
{return nil, errors.New("not implemented")}
```

 That means that a client can't stream the workflow WatchEvents endpoint using kube auth.

# Use Cases

We're writing a Go client that interacts with the Argo API. The client is deployed to the cloud in a separate cluster from the Argo server and must interact with Argo over the public internet. The Go client already interacts with the k8s API directly using a kubeconfig for auth, so it'd be nice to also be able to auth to Argo using the same method (rather than exposing Argo to the public internet).

We're using the WatchEvents endpoint because we'd like the client to be aware of Workflow Node events ex. here https://argoproj.github.io/argo-workflows/workflow-events/. It seems like the Workflows UI does something similar with Node events here https://github.com/argoproj/argo-workflows/pull/3726

Just wanted to say, have been playing around with Argo while now and a really big fan of the project! Excellent work :)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Would you like to submit a PR to fix this?

**Comment by karenin-overseas** [comment]
> Would you like to submit a PR to fix this?

Yes, I will see what I can do :)
