### ISSUE TITLE
PDB unit test and example are different

### ISSUE THREAD

**Issue by ddseapy** [argoproj/argo-workflows#6177]
Unit test for PDB and example are different:

https://github.com/argoproj/argo-workflows/pull/3914/files

https://github.com/argoproj/argo-workflows/blame/master/workflow/controller/operator_test.go#L3249

https://github.com/argoproj/argo-workflows/blob/4f847e099ec2a2fef12e98af36b2e4995f8ba3e4/workflow/controller/operator_test.go

is it ok to use "100%", or is there an issue with that?  That's what we were using previously on 2.9.x, and are upgrading to latest 3.1.x, just want to make sure it's still ok.

Thanks!

**Comment by alexec** [comment]
@sarabala1979 i seem to recall that this was wrong in the examples and was corrected.
@ddseapy cpuld I ask you to test and tell us which is correct. This is vanilla PBD with same syntax etc.

**Comment by ddseapy** [comment]
we get errors trying to set a number, but we use the java sdk.

this doesn't complain:
```java
new IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec().minAvailable("100%")
```
this doesn't:
```java
new IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec().minAvailable("99999")
```
![pdb](https://user-images.githubusercontent.com/5047750/122586991-500afa80-d02b-11eb-8fa8-c6057745a3e9.png)

i assume that means that percent is correct?  If you want me to verify the pdb is taking affect I can definitely do that and post back here, but might be a bit before I can.

**Comment by sarabala1979** [comment]
@ddseapy  PDB with % will work only for predefined no of pods like Deployments, ReplicaSet, StatefulSets.  As we know workflow pods are more dynamic. We had an issue with our prod env '%' didn't hold the workflows pods when the distribution happens. If we define the whole number(no pods), PDB will do its job for that no of pods.   Based on this observation, the example updated with max number `9999` instead of `%`.

UnitTest just wants to make sure functionality is working fine like when the workflow has PDB, the controller should create a PDB resource and Delete it. 
Would you like to submit PR with the `whole number` unit test? I am very happy to review it. 

Reference: https://kubernetes.io/docs/tasks/run-application/configure-pdb/

**Comment by sarabala1979** [comment]
@ddseapy Can we close this issue?

**Comment by ddseapy** [comment]
i can put up an MR but I need to get it working first. it seems to me that both the example and unit test are not correct from what i'm seeing.

The example has a string that's a number (`"9999"` vs `9999`), which causes the error I screenshot and doesn't match the documentation (https://kubernetes.io/docs/tasks/run-application/configure-pdb/).

The unit test is valid, but sounds like it's not recommended since it doesn't work for pods correctly.

Separately the java sdk only accepts strings, which lines up with the unit test but should instead support a number since it sounds like we should not use percent strings.

Does that make sense.  If so I can throw up MRs for this (example and unit test) and java sdk.  Just been pulled away for a bit, but expect this week I can get it done.

**Comment by sarabala1979** [comment]
@ddseapy Let me look the UI Error, Are you able to submit the workflow using CLI>

**Comment by ddseapy** [comment]
no i cannot.  if I argo submit the example currently on master (https://github.com/argoproj/argo-workflows/blob/bae2188961125a07eb822c301c9a71e61cc7676b/examples/default-pdb-support.yaml), I get the following error:

```
Status:              Failed
Message:             Unable to create PDB resource for workflow, default-pdb-support-w65fw error: PodDisruptionBudget.policy "default-pdb-support-w65fw" is invalid: spec.minAvailable: Invalid value: intstr.IntOrString{Type:1, IntVal:0, StrVal:"9999"}: a valid percent string must be a numeric string followed by an ending '%' (e.g. '1%',  or '93%', regex used for validation is '[0-9]+%')
```

I believe the example became incorrect in this commit:
https://github.com/argoproj/argo-workflows/commit/fcf4e9929a411a7c6083e67c1c37e9c798e4c7d9#diff-8d68111090ad6c799cf2910f0f3bda4d2ed3457654bb111a3c43054142877cbeL10

**Comment by sarabala1979** [comment]
which version of CLI are you using? Please upgrade to latest.
`argo version`
I am able to submit the workflow

```
argo submit https://raw.githubusercontent.com/argoproj/argo-workflows/bae2188961125a07eb822c301c9a71e61cc7676b/examples/default-pdb-support.yaml
Name:                default-pdb-support-rjcft
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Tue Jun 22 11:01:25 -0700 (now)
Progress:            
```

**Comment by ddseapy** [comment]
i'm using 
argo: v3.1.0-rc14
  BuildDate: 2021-06-10T19:08:51Z
  GitCommit: d385e6107ab8d4ea4826bd6972608f8fbc86fbe5
  GitTreeState: clean
  GitTag: v3.1.0-rc14
  GoVersion: go1.15.7
  Compiler: gc
  Platform: linux/amd64

i can update to 3.1.0.

the error is in the workflow:
 argo list
NAME                        STATUS   AGE   DURATION   PRIORITY
default-pdb-support-l5t7n   Failed   1m    0s         0

kubectl describe wf shows the message.

**Comment by ddseapy** [comment]
are you seeing the workflow succeed?

**Comment by sarabala1979** [comment]
Got it, I can see the error in message. Found the issue in example, for number we shouldn't use "

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: default-pdb-support-

spec:
  entrypoint: pdbcreate
  serviceAccountName: default
  podDisruptionBudget:
    minAvailable: 9999   # Provide arbitrary big number if you don't know how many pods workflow creates
  templates:
  - name: pdbcreate
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["sleep 10"]
```

**Comment by sarabala1979** [comment]
Would you like to submit the PR for this changes?

**Comment by ddseapy** [comment]
if changing the example, it will not match the openapi spec (https://github.com/argoproj/argo-workflows/pull/4831) which it presumably why it was changed to a string: https://github.com/argoproj/argo-workflows/commit/fcf4e9929a411a7c6083e67c1c37e9c798e4c7d9#diff-8d68111090ad6c799cf2910f0f3bda4d2ed3457654bb111a3c43054142877cbeL10

is that something that is desired?

maybe a PR that updates openapi version & therefore support schema for int OR string (and thus fix clients) to allow int seems like the best long-term solution?

**Comment by ddseapy** [comment]
looking at https://github.com/argoproj/argo-workflows/issues/4817#issuecomment-778855785

**Comment by sarabala1979** [comment]
>  if changing the example, it will not match the openapi spec (#4831) which it presumably why it was changed to a string: 
    fcf4e99#diff-8d68111090ad6c799cf2910f0f3bda4d2ed3457654bb111a3c43054142877cbeL10 
    is that something that is desired?
@alexec or @jessesuen Can you comments it?
PDB Create API call has validation for int and string fields.  My recommendation is OpenAPI should have int and string.

**Comment by alexec** [comment]
I'm not clear on what the problem here is.

**Comment by ddseapy** [comment]
To summarize the situation:

When specifying a `minAvailable` in a Workflow `podDisruptionBudget`, an integer value should be used.

Reference: https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors:
```
You can use a PDB with pods controlled by another type of controller, by an "operator", or bare pods, but with these restrictions:

only .spec.minAvailable can be used, not .spec.maxUnavailable.
only an integer value can be used with .spec.minAvailable, not a percentage.
```

However, according to the openapi-spec the only valid value for `minAvailable` is a string.

Reference:
* https://github.com/argoproj/argo-workflows/blob/82ba80165ea288878908d67f1fcc524565d8608f/api/openapi-spec/swagger.json#L12518
* https://github.com/argoproj/argo-workflows/blob/82ba80165ea288878908d67f1fcc524565d8608f/api/openapi-spec/swagger.json#L12184

This makes it impossible for clients generated from the schema to declare workflows with podDisruptionBudgets that abide by the restrictions imposed by kubernetes.

Reference:
https://github.com/argoproj/argo-workflows/issues/6177#issuecomment-864132369

It also makes it so that yaml that abides by the schema to result in one of the following:

1. failed workflows

Reference:
```bash
argo submit https://raw.githubusercontent.com/argoproj/argo-workflows/bae2188961125a07eb822c301c9a71e61cc7676b/examples/default-pdb-support.yaml
```
2. workflows that don't abide by kubernetes restrictions, making PDB ineffective:

Reference:
https://github.com/argoproj/argo-workflows/blob/82ba80165ea288878908d67f1fcc524565d8608f/workflow/controller/operator_test.go

---

Because of this, it would seem that updating to swagger v3.1 which apparently supports both string and int types is the correct solution.  After updating the swagger.json for `IntOrString`, then examples/tests/clients could be updated to conform to the new swagger.json.

Reference:
https://github.com/argoproj/argo-workflows/issues/4817#issuecomment-778855785

**Comment by alexec** [comment]
Thank you for a detailed answer to my question. Is upgrading to v3.1 a solution?

**Comment by ddseapy** [comment]
yes, however not sure how easy it will be (https://github.com/go-swagger/go-swagger/issues/1122#issuecomment-575968499)

**Comment by ddseapy** [comment]
Given that it looks to be too involved to update to v3.1 given go-swagger only supports v2.0, for now we are going to set `minAvailable` as an integer under the controller's `workflowDefaults`, since currently we want all workflows to be run with PDBs.  

This avoids the issue of needing to set it as an integer in each workflow, and is feasible in the timeline we have on our project.

I'll put up a PR to change the example to help others who might try and run it using yaml directly.

**Comment by ddseapy** [comment]
> Given that it looks to be too involved to update to v3.1 given go-swagger only supports v2.0, for now we are going to set `minAvailable` as an integer under the controller's `workflowDefaults`, since currently we want all workflows to be run with PDBs.
> 
> This avoids the issue of needing to set it as an integer in each workflow, and is feasible in the timeline we have on our project.
> 
> I'll put up a PR to change the example to help others who might try and run it using yaml directly, even though it will not match the swagger.json (which I'm guessing is ok?)

well, it looks like the unit testing checks if example matches the schema.  so i guess i'm not sure what is best to do.  going to close ticket for now.  The error message from the workflow is pretty clear the problem, so users declaring raw yaml should be able to figure that bit out.  It's a bit trickier if using a client based on the swagger.json, but not sure there is a great solution to that one other than migrating to something like https://github.com/getkin/kin-openapi (but even that looks like it supports 3.0 instead of 3.1).
