### ISSUE TITLE
Affinity at the DAG Task or Workflow Step Level

### ISSUE THREAD

**Issue by ad22** [argoproj/argo-workflows#6180]
# Summary

Support affinity spec in DAGTask and WorkflowStep
# Use Cases

We currently use a workflow which spawns a 100+ task parameterized DAG based on various common templates. It is often required that individual steps in the DAG have independent nodeAffinity and/or PodAffinity requirements. None of the current methods (Workflow level or Template level affinity) satisfy this use case.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
We can achieve this enhance using `podSpecPatch`.  Each Step/Task can parameterize `podSpecPatch` `nodeAffinity and/or PodAffinity` value to `template`

**Comment by sarabala1979** [comment]
@ad22 https://github.com/argoproj/argo-workflows/blob/master/examples/pod-spec-from-previous-step.yaml

**Comment by ad22** [comment]
@sarabala1979 Great! Didn't think of that. Thank you.
