### ISSUE TITLE
Argo workflows with keda and celery workers

### ISSUE THREAD

**Issue by aviklai** [argoproj/argo-workflows#6181]
# Summary
Hi,

I wanted to suggest an enhancement that was already implemented in Apache Airflow:
https://www.astronomer.io/blog/the-keda-autoscaler
https://airflow.apache.org/docs/helm-chart/stable/keda.html
The basic idea here is to spin up pods with celery workers that pull tasks from a queue and the execution environment is retained between multiple consequent tasks.

Currently, in Argo workflows, if we have thousands of tasks - each task is executed in it's own pod and it takes time to spin up the pod for each of these tasks.
If we could use keda with celery workers, we could decrease the overhead of starting a new pod for each task.

What change needs making?

Add pod autoscaling with keda and celery workers

When would you use this?

When you have a large number of tasks that don't require new isolated execution environment and when we want to significantly decrease the overall execution time.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
Argo Controller has already implemented a Queue and workers pattern to process the workflow at scale.  Recent Argo workflow has introduced few features to avoid POD creation for light-weighted task `containerSet` and `data-template`.
v3.2 will have Agent implementation which will process the multiple task in one pod

**Comment by alexec** [comment]
I think this is https://github.com/argoproj-labs/argo-dataflow

**Comment by aviklai** [comment]
@sarabala1979 @alexec thanks - I will take a look at both of these.
