### ISSUE TITLE
3.0.8 images were not pushed to docker hub

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#6195]
## Summary 

What happened/what you expected to happen?
https://hub.docker.com/r/argoproj/workflow-controller/tags?page=1&ordering=last_updated&name=3.0.8

This should return the workflow-controller for 3.0.8

https://hub.docker.com/r/argoproj/argocli/tags?page=1&ordering=last_updated&name=3.0.8

This should return the CLI.

The manifests are still referencing docker hub.. I thought I'd better check because argocd moved to quay recently.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by orrymr** [comment]
Same thing for argoexec: https://hub.docker.com/r/argoproj/argoexec/tags?page=1&ordering=last_updated&name=3.0.8

**Comment by sarabala1979** [comment]
I will take a look

**Comment by sarabala1979** [comment]
@tim-sendible @orrymr Pushed to Docker hub. Can you try it now?

**Comment by orrymr** [comment]
Thanks @sarabala1979 :) - v3.0.8 pods are running now

**Comment by MichielDeMey** [comment]
Looks like it's the same issue on the Quay.io registry?
Can't seem to find the v3.0.8 tag.
