### ISSUE TITLE
Cannot run workflows after #6022

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#6198]
## Summary 

What happened/what you expected to happen?

#6022 May have broken master. I cannot run workflows there that I can run on `HEAD^`. Always fails with error `Error (exit code 2): open /argo/podmetadata/annotations: no such file or directory`

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

```
Name:                ingest-pipeline-cdw-m6xsh
Namespace:           argo
ServiceAccount:      default
Status:              Error
Conditions:
 PodRunning          False
 Completed           True
Created:             Wed Jun 23 13:04:56 -0400 (1 second ago)
Started:             Wed Jun 23 13:04:56 -0400 (1 second ago)
Finished:            Wed Jun 23 13:04:57 -0400 (now)
Duration:            1 second
Progress:            1/1
ResourcesDuration:   0s*(1 cpu),0s*(100Mi memory)

STEP                          TEMPLATE     PODNAME                               DURATION  MESSAGE
 ⚠ ingest-pipeline-cdw-m6xsh  ingest-task
 ├─⚠ sent                     sentinel     ingest-pipeline-cdw-m6xsh-1606206776  1s        Error (exit code 2): open /argo/podmetadata/annotations: no such file or directory

This workflow does not have security context set. You can run your workflow pods more securely by setting it.
Learn more at https://argoproj.github.io/argo-workflows/workflow-pod-security-context/
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
CI is passing on `master`, so I wonder if you need to have matched tags?

**Comment by simster7** [comment]
> so I wonder if you need to have matched tags?

Likely, I'll make sure this is the issue.

**Comment by simster7** [comment]
> Likely, I'll make sure this is the issue.

This was correct. This is a non-issue.
