### ISSUE TITLE
archiveLogs should work for failed steps

### ISSUE THREAD

**Issue by steve-marmalade** [argoproj/argo-workflows#6201]
## Summary 

I think this is a continuation of #3105  

When `archiveLogs=True`, an Output `main-logs` is created for steps that finish successfully. However, no such Output is created for steps that fail, and it is often exactly these steps whose logs we want to read for help in debugging.

## Diagnostics

What Kubernetes provider are you using? **GKE**

What version of Argo Workflows are you running? **3.1**

What executor are you running? **Emissary**

Did this work in a previous version? I.e. is it a regression? **I don't think so**

![Screen Shot 2021-06-23 at 2 01 25 PM](https://user-images.githubusercontent.com/85196623/123146085-82ea2f80-d42b-11eb-97d2-54ddc23b3698.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you please try with the PNS executor so we can confirm if it an emissary bug, or more general.

**Comment by sarabala1979** [comment]
@steve-marmalade can you  try with PNS executor?
