### ISSUE TITLE
All workflows fail on EKS 1.20 - ERROR opening annotation file from /argo/podmetadata/annotations

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#6210]
## Summary 

I upgrade to EKS 1.20.
Now when running a workflows with the emissary executor, I get the following:

```
init time="2021-06-24T11:59:25.250Z" level=info msg="Starting Workflow Executor" executorType=emissary version=v3.1.0
init time="2021-06-24T11:59:25.251Z" level=error msg="ERROR opening annotation file from /argo/podmetadata/annotations"
init panic: open /argo/podmetadata/annotations: no such file or directory
init goroutine 1 [running]:
init github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.checkErr(0x2463880, 0xc00020e7b0)
init     /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/root.go:136 +0xf4
init github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.initExecutor(0x203000)
init     /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/root.go:101 +0x57a
init github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.loadArtifacts(0x24b22a0, 0xc00005e018, 0x0, 0x0)
init     /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/init.go:27 +0x65
init github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.NewInitCommand.func1(0xc0000e1b80, 0xc000525060, 0x0, 0x2)
init     /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/init.go:17 +0x3d
init github.com/spf13/cobra.(*Command).execute(0xc0000e1b80, 0xc000525040, 0x2, 0x2, 0xc0000e1b80, 0xc000525040)
init     /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
init github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e1080, 0x2258fc8, 0xc00051c0c8, 0xc000893f48)
init     /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
init github.com/spf13/cobra.(*Command).Execute(...)
init     /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
init main.main()
init     /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/main.go:15 +0x2b
```

The pod then dies.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? EKS 1.20

What version of Argo Workflows are you running? 3.1.0

What executor are you running? Emissary

Did this work in a previous version? I.e. is it a regression? Worked in EKS 1.19 with workflows 3.1.0

Are you pasting thousands of log lines? That's too much information. 

```bash
# Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:
kubectl get wf -o yaml ${workflow}

# Logs from the workflow controller:
Nothing super out of the ordinary. I did spot this that pops up every few seconds, but it might have been there all along and I hadn't noticed:
`time="2021-06-24T12:02:01.893Z" level=info msg=healthz age=5m0s err="<nil>" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=`

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tim-sendible** [comment]
I'm actually seeing the same error with the Docker executor:

```
wait time="2021-06-24T12:04:21.483Z" level=info msg="Starting Workflow Executor" executorType=docker version=v3.1.0
wait time="2021-06-24T12:04:21.484Z" level=error msg="ERROR opening annotation file from /argo/podmetadata/annotations"
wait panic: open /argo/podmetadata/annotations: no such file or directory
wait goroutine 1 [running]:
wait github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.checkErr(0x2463880, 0xc00027c780)
wait     /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/root.go:136 +0xf4
wait github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.initExecutor(0x1e7b180)
wait     /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/root.go:101 +0x57a
wait github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.waitContainer(0x24b22a0, 0xc00005e018, 0x0, 0x0)
wait     /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/wait.go:28 +0x6c
wait github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.NewWaitCommand.func1(0xc0001d02c0, 0xc0004f3520, 0x0, 0x2)
wait     /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/wait.go:18 +0x3d
wait github.com/spf13/cobra.(*Command).execute(0xc0001d02c0, 0xc0004f3500, 0x2, 0x2, 0xc0001d02c0, 0xc0004f3500)
wait     /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
wait github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e1080, 0x2258fc8, 0xc000138ef8, 0xc00079ff48)
wait     /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
wait github.com/spf13/cobra.(*Command).Execute(...)
wait     /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
wait main.main()
wait     /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/main.go:15 +0x2b
```

**Comment by tim-sendible** [comment]
This fails on even the most basic workflow (like the one that is pre-loaded in the UI)

**Comment by tim-sendible** [comment]
I can't see where/how that particular volume is mounted, it's not in the manifests on here.

I double-checked that EKS 1.20 can still mount downwardAPI info (by running `kubectl apply -f https://k8s.io/examples/pods/inject/dapi-volume.yaml`) and it can.

My assumption therefore is that this directory used to automount somehow and now doesn't?

**Comment by terrytangyuan** [comment]
Related/duplicate to https://github.com/argoproj/argo-workflows/issues/6198?

**Comment by alexec** [comment]
I don’t think you’re running v3.1. I think you’re running latest. Can you please confirm?

**Comment by tim-sendible** [comment]
I was 100% definitely running v3.0.1. I promise!

We use argocd to deploy it, so I have the git record of everyting pointing at the correct manifest. I've reverted to 3.0.8 for now as I was completely stuck.

**Comment by sarabala1979** [comment]
The workflow controller and Argoexec version mismatch is causing this issue.

**Comment by alexec** [comment]
Are you importing manifests pinned to the tag? If so, please double check. They changed in v3.1 and now include latest. It is possible that there’s a mistake in the manifests. The code change that would underly your issue is only intended to be in v3.2

**Comment by sarabala1979** [comment]
> I was 100% definitely running v3.0.1. I promise!
are you using v3.0.1 or v3.1.0? 
Can you provide workflow controller log?

**Comment by tim-sendible** [comment]
3.1.0 - that was a typo.

I am not importing manifests with anything pinned, no. The workflow manifests worked prior to the k8s version upgrade.. that's the only change.

As I said above, it fails on even the simplest manifest like the one you get in the UI by default.

**Comment by tomgoren** [comment]
@tim-sendible could it be that you were using the v3.1.0 workflow-controller, but were specifying `latest` for the executor? We had a similar issue and solved it by pinning the executor. I believe this was the case in several other issue where a similar phenomena was reported (https://github.com/argoproj/argo-workflows/issues/6194, https://github.com/argoproj/argo-workflows/issues/6198).

@alexec - is this maybe related to https://github.com/argoproj/argo-workflows/commit/cecc379ce23e708479e4253bbbf14f7907272c9c#diff-d942970af9b2fbf6d874472ca3ffecede393f0d268c53b16dc449a0bb070aced
?

**Comment by tim-sendible** [comment]
I pin the version of the executor in the config map too. So unlikely I think... unless there's some other way to define the executor tag?

**Comment by alexec** [comment]
I think it is the controller that is running the wrong version.

**Comment by tim-sendible** [comment]
I can't see how that's the case otherwise downgrading (changing the manifest tag number in kustomize) wouldn't work. 

I will recreate the installation again tomorrow to prove this though.

**Comment by alexec** [comment]
Please note this breaking changing in v3.1:

https://github.com/argoproj/argo-workflows/blob/master/docs/upgrading.md#3fff791e4-build-automatically-add-manifests-to-v-tags-5880

**Comment by alexec** [comment]
Link: #6219

**Comment by tim-sendible** [comment]
@alexec You were correct, I got tripped up by that change. I expect we'll see a lot more of this.

Apologies for wasting everyone's time.
