### ISSUE TITLE
Argo 3.1.0 manifests don't have 3.1.0 image

### ISSUE THREAD

**Issue by max-sixty** [argoproj/argo-workflows#6219]
## Summary 

Currently the Argo 3.1.0 manifests contain `latest`

https://github.com/argoproj/argo-workflows/blob/v3.1.0/manifests/base/argo-server/argo-server-deployment.yaml#L17

They used to link to the images, which allowed for very elegant upgrades:

https://github.com/argoproj/argo-workflows/blob/v3.0.8/manifests/base/argo-server/argo-server-deployment.yaml#L17

## Diagnostics

Props to the very clear version number on the webpage!
<img width="137" alt="image" src="https://user-images.githubusercontent.com/5635139/123342503-bea4f800-d504-11eb-9a02-8811a3aefd20.png">

My usual thanks and appreciation for such a great library, and well-run project!

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
You are correct. As of v3.1, the manifests no longer contain the tags. You should use manifests attached to the release page.

This is documented in the upgrading guide. 

@jessesuen @sarabala1979 lets. monitor this - if many users get caught out - then we should plan to fix this.

**Comment by max-sixty** [comment]
Got it. Grabbing from the releases was a very small change and worked great. Thanks!
