### ISSUE TITLE
Failed to establish pod watch when containerRuntimeExecutor is set to k8sapi

### ISSUE THREAD

**Issue by axsaucedo** [argoproj/argo-workflows#6235]
#### What happened/what you expected to happen?

When running in KIND (Kubernetes in Docker) it does't work, only works on environments with docker enabled kubernetes clusters. This can be reproduced with kind locally - the instructions are below.

### Steps to reproduce

First create kind cluster:
```
kind create cluster --name newcluster
```
Now install stable argo
```
kubectl create namespace argo || echo "namespace already created"
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml
kubectl rollout status -n argo deployment/argo-server
kubectl rollout status -n argo deployment/workflow-controller
```
Then configure clusterrole
```
kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=default:default
```
Configure the k8sapi in the configmap
```
kubectl apply -n argo -f - << END
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  containerRuntimeExecutor: k8sapi
END
```
Run argo hello-world
```
argo submit -n argo --watch https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/hello-world.yaml
```
See error
```
STEP                  TEMPLATE  PODNAME            DURATION  MESSAGE
 hello-world-sbr56  whalesay  hello-world-sbr56  1m        Error (exit code 1): failed to wait for main container to complete: timed out waiting for the condition: failed to establish pod watch: unknown (get pods)
```

#### What Kubernetes provider are you using? 
* KIND version: kind v0.6.1 go1.13.4 linux/amd64

#### Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-12-04T07:23:47Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

#### What version of Argo Workflows are you running? 
Stable - v3.0.3

#### What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
k8sapi (but also tried with kubelet and pns and same results)

#### Did this work in a previous version? I.e. is it a regression?
Tested with v2.12.11 and was able to reproduce

#### Are you pasting thousands of log lines? That's too much information. 

The logs in the controller basically just repeat this error ie failed to establish pod watch: unknown (get pods)

**Comment by terrytangyuan** [comment]
Could you try with Argo 3.1.0? The error message would be more intuitive after https://github.com/argoproj/argo-workflows/pull/5372 gets merged.

**Comment by terrytangyuan** [comment]
Also looks like you configured the cluster role for default account in default namespace.

**Comment by axsaucedo** [comment]
@terrytangyuan thank you for your comment, it seems you are correct - I was able to resolve it by configuring the RBAC correctly, thanks!
