### ISSUE TITLE
"long" time between steps

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#6262]
## Summary 

I try to optimize the duration of my workflows

Currently, I have something like half the duration of my workflows which are not inside pods (which are generally short-lived).

These are the "blanks" between the pods I have :

![Capture d’écran 2021-07-01 à 15 23 16](https://user-images.githubusercontent.com/11044877/124131640-4ac49b80-da80-11eb-81cd-0848e1e332f1.png)

The duration of each step : 8 / 3 / 9 / 14 / 10 / 5 / 15 / 8 / 15 / 15 / 4 / 10 / 6 / 11 => 133s
The duration of the workflow : start=22h22m11s, finish=22h26m52s => 281s

I suppose these blanks are not due to argo directly but mostly to k8s (retrieving logs, deleting the pod, starting the next pod, ???)

I've tried changing the executor but k8sapi, pnc and emissary are all more or less equivalent in my case

I also searched in the doc to find something about performance but nothing there ... (I only find things about scalability and HA)

Can I find an explanation about these "blanks" ? Somewhere to look in the logs ?  Is there any tips or tricks to improve this area ?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
How busy is you k8s server? Argo workflow will depend on Pod informer notification to schedule next step/pod. If k8s take a few seconds to update, the next pod will take few seconds delay.

**Comment by christopheblin** [comment]
@sarabala1979 thanks for the quicck answer :)

what metric exactly do you need (CPU / RAM) ?

here is the `k top node` output just before I run the wf

![Capture d’écran 2021-07-01 à 16 30 50](https://user-images.githubusercontent.com/11044877/124141467-bd864480-da89-11eb-93ea-f35a23aa1a03.png)

As you can see, this is pretty "normal" and there is no problem

If you have any kubectl command to run to have a deeper insight in the "Pod informer", please let me know

I also have the problem on shorter wf 

4 steps :  12 + 30 + 8 + 3 = 53s, wf duration 9h50m03s -> 9h51m23s => 80s

**Comment by christopheblin** [comment]
Here are additional infos for a 3 step wf

```
k get pods -o name | grep rt-coverage | xargs -n 1 -I{} kubectl get {} -o jsonpath="{.metadata.name}{','}{range .status.conditions[*]}{.type}{','}{.lastTransitionTime}{'\n'}{end}" 

rt-coverage-gbsz2-1241035201,Initialized,2021-07-01T15:52:54Z
Ready,2021-07-01T15:53:03Z
ContainersReady,2021-07-01T15:53:03Z
PodScheduled,2021-07-01T15:52:54Z

rt-coverage-gbsz2-1342292650,Initialized,2021-07-01T15:52:24Z
Ready,2021-07-01T15:52:44Z
ContainersReady,2021-07-01T15:52:44Z
PodScheduled,2021-07-01T15:52:24Z

rt-coverage-gbsz2-2987741140,Initialized,2021-07-01T15:53:17Z
Ready,2021-07-01T15:53:22Z
ContainersReady,2021-07-01T15:53:22Z
PodScheduled,2021-07-01T15:53:17Z
```

duration : 20 / 13 / 9

all pods have scheduled -> init = 0s and ready -> containersready = 0s

however
* first pod : init to ready = 9s 
* second pod : init to ready = 20s
* third pod : init to ready = 5s

**Comment by sarabala1979** [comment]
The pod life cycle totally depends on your k8s.  you play with imagepullpolicy.

**Comment by christopheblin** [comment]
@sarabala1979

I understand that the part inside the pod is my responsibility.

What I'd like to know is what argo is doing and how much time it is supposed to take (or where I can find data about this).

pod/main ended -> pod/wait detection -> .... -> next pod created on k8s

for ex : when are logs uploaded to s3 : by wait container ? by argo-controlller ? synchronously or asynchronously before starting next pod ? etc...

another ex : outputs, artifacts ?
 
between initialized and ready in my pods, the image pull is not the problem (it takes 300ms for argo and 1s for mine based on the events I can see "Container image "argoproj/argoexec:v3.1.0-rc12" already present on machine" and "Successfully pulled image "xxx" in X.XXXs")

so I can provide more information, but really my question is more about what is happening inside argo and how I can "see/time" it

**Comment by sarabala1979** [comment]
>for ex : when are logs uploaded to s3 : by wait container ? by argo-controlller ? synchronously or asynchronously before starting next pod ? etc...

Wait container will upload logs/artifacts/outputs once the main container completes.

Argo will create pods based on Step or DAG configuration. If the step or task configured parallel, Argo will create all pods at the same time. Pods schedule is up to the K8s scheduler.

**Comment by sheepdragon** [comment]
![image](https://user-images.githubusercontent.com/4659052/125370032-246ffb80-e3b0-11eb-8024-d9bdc6aa0a4c.png)
me too

**Comment by pevers** [comment]
Any ideas or updates on this @christopheblin ?

I'm now looking into optimizing an Argo workflow where pod creation takes 10 seconds for every step. It adds a lot of overhead to the whole flow (which only takes 20 seconds).

**Comment by tooptoop4** [comment]
did u solve @pevers ?

**Comment by pevers** [comment]
> did u solve @pevers ?

@tooptoop4 I decreased the `DEFAULT_REQUEUE_TIME` in the environment variables. Overview of all settings can be found here: https://github.com/argoproj/argo-workflows/blob/master/docs/environment-variables.md

That helped a lot, but it will also put a larger strain on your cluster.

**Comment by tooptoop4** [comment]
@pevers by larger strain do u mean just the wfcontroller needs more cpu?
did u also change WAIT_CONTAINER_STATUS_CHECK_INTERVAL, RESOURCE_STATE_CHECK_INTERVAL, ARGO_PROGRESS_FILE_TICK_DURATION, ARGO_TERMINATION_GRACE_PERIOD_SECONDS, RECENTLY_STARTED_POD_DURATION, PodGCGracePeriodSeconds, PodGCDeleteDelayDuration ?

I raised https://github.com/argoproj/argo-workflows/pull/9729 too
