### ISSUE TITLE
Cannot Install Argo CLI for 'not in gzip format'

### ISSUE THREAD

**Issue by Manheim94** [argoproj/argo-workflows#6275]
## Summary 

I follow the argo cli install instructions on 
https://github.com/argoproj/argo-workflows/releases/tag/v3.1.1
The error happens during the unzip step:
➜  /tmp gunzip argo-darwin-amd64.gz
gunzip: argo-darwin-amd64.gz: not in gzip format

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

Did this work in a previous version? I.e. is it a regression?

Are you pasting thousands of log lines? That's too much information. 

```bash
# Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:
kubectl get wf -o yaml ${workflow}

# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
Change the url from https://github.com/argoproj/argo to https://github.com/argoproj/argo-workflows

I will update the release notes

**Comment by sarabala1979** [comment]
updated  release notes

**Comment by joakimwar** [comment]
I'm pretty sure I was looking at the updated version. I ended up doing `brew install argo`. I think that worked for me, but I have a different problem now, so I'm not quite sure ¯\\_(ツ)_/¯
