### ISSUE TITLE
workflow validator runs into unknown field hostnetwork

### ISSUE THREAD

**Issue by prasunsultania** [argoproj/argo-workflows#6279]
## Summary 
hostPID field is not available in argo workflow cron and hostNetwork runs into error.   

What happened/what you expected to happen?
Since, hostNetwork and hostPID fields are supported by native Kubernetes pods and cronjobs, it should be supported in argo cron workflows.

Before we start, around 2/3 of issues can be fixed by one of the following:

* Have you double-checked your configuration? Maybe 30% of issues are wrong configuration.  
* `Yes`
* Have you tested to see if it is fixed in the latest version? Maybe 20% of issues are fixed by this.
* `Yes, in 3.1.1 with Kubernetes 1.21.1`
* Have you tried using the PNS executer instead of Docker? Maybe 50% of artifact related issues are fixed by this.
* `This issue shouldn't be related to executor`

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
1.20.7

What version of Argo Workflows are you running? 
3.0.4

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
k8sapi

Did this work in a previous version? I.e. is it a regression?
No

Are you pasting thousands of log lines? That's too much information. 

```bash
# Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:
# This workflow syncs machine's date & time
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: sync-time-
  namespace: deploy
spec:
  schedule: "55 4 * * 1"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: sync-time
    dnsPolicy: ClusterFirstWithHostNet
    serviceAccountName: argo-workflow-deploy
    templates:
    - name: sync-time
      daemon: true
      container:
        image: ubuntu
        command: ["sh", "-c"]
        args: [
          "mkdir -p /host/tmp2;
          cp /tmp/time-update.sh /host/tmp2/;
          chown root /host/tmp2/time-update.sh;
          chmod +x /host/tmp2/time-update.sh;
          chroot /host sh -c /tmp2/time-update.sh;"
        ]
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        stdin: true
        securityContext:
          privileged: true
        volumeMounts:
          - name: host-root-volume
            mountPath: /host
            readOnly: false
          - name: time-sync
            mountPath: /tmp
      volumes:
        - name: host-root-volume
          hostPath:
            path: /
        - name: time-sync
          configMap:
            name: time-sync
      hostNetwork: true
      hostPID: true
```

# Output on running command
```
$ argo cron create argo/sync-time.yaml 
2021/07/05 04:53:50 Failed to parse workflow template: json: unknown field "hostNetwork"
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
The error is correct. `hostNetwork` is a field on the `workflowSpec`, not on the template. Outdent your YAML.

**Comment by prasunsultania** [comment]
`hostNetwork` worked, although still errors for `hostPID`, but, I am able to get my use case without `hostPID`
