### ISSUE TITLE
Argo Server GET fields param `status.nodes.<node-id>` does not return nodes

### ISSUE THREAD

**Issue by AntoineDao** [argoproj/argo-workflows#6284]
## Summary 

What happened/what you expected to happen?

We use the argo server API to request updates on workflows and update our reporting system outside of the argo environment. This is to reduce the load on the argo server overall.

To do this we make api requests using this URL pattern `/v1/workflows/<namespace>/<workflow-id>?fields=status.nodes.<node-id>`. This used to work until we upgraded to `v3.1.0-rc14` and the response from the server now doesn't include the `status.nodes` keys when a Workflow is large enough to be zipped.

It still works if we make a request to `/v1/workflows/<namespace>/<workflow-id>?fields=status.nodes`.

I'm 90% sure this bug was introduced in #6004 

This section of code is designed to check that the `status.nodes` keys is excluded from the request to reduce the load on the server:
https://github.com/argoproj/argo-workflows/blob/c9246d3d4c162e0f7fe76f2ee37c55bdbfa4b0c6/server/workflow/workflow_server.go#L107-L111

However the `matches` function in the `WillExclude` function returns `true` if a value in `fields` query start with `status.nodes.`:
https://github.com/argoproj/argo-workflows/blob/c9246d3d4c162e0f7fe76f2ee37c55bdbfa4b0c6/util/fields/fields.go#L50-L68

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
- GKE

What version of Argo Workflows are you running? 
- `v3.1.0-rc14` 
- 
What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
- Emissary

Did this work in a previous version? I.e. is it a regression?
- Yes

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Did you have a fix in mind?

**Comment by AntoineDao** [comment]
Late reply sorry. Yes I think I do, I'll aim to have it proposed in a PR by sometime next week 😄
