### ISSUE TITLE
archived logs not stored in minio, event in wait containerlogs print success saved

### ISSUE THREAD

**Issue by ZhengJuCn** [argoproj/argo-workflows#6287]
archived logs not stored in minio, event in wait containerlogs print success saved

What happened/what you expected to happen?
main log store in minio

## Diagnostics

in wait container logs , i can see main.log has successfully saved, but in minio nothing stored,

1. wait container logs

time="2021-07-02T07:04:45.918Z" level=info msg="Creating minio client minio.argo:9000 using static credentials"
time="2021-07-02T07:04:45.918Z" level=info msg="Saving from /tmp/argo/outputs/logs/main.log to s3 (endpoint: minio.argo:9000, bucket: my-bucket, key: a559c0a0-db03-11eb-a189-8
e5f65b6e3b4/a559c0a0-db03-11eb-a189-8e5f65b6e3b4-2215799357/main.log)"
time="2021-07-02T07:04:46.050Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}}|{{.CreatedAt}} --filter=lab
el=io.kubernetes.pod.namespace=h986 --filter=label=io.kubernetes.pod.name=a559c0a0-db03-11eb-a189-8e5f65b6e3b4-2215799357"
time="2021-07-02T07:04:46.063Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2021-07-02T07:04:46.063Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"

2. workflow-controller configmap

data:                                                                                                                                                                                                   
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: my-bucket
      endpoint: minio.argo:9000
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey

**Comment by tooptoop4** [comment]
@ZhengJuCn how did u solve?
