### ISSUE TITLE
Binaries download broken due to redirect

### ISSUE THREAD

**Issue by Guillermogsjc** [argoproj/argo-workflows#6288]
This is probably a Github issue, but status is ok ...

`curl -sLO https://github.com/argoproj/argo/releases/download/v3.1.0-rc12/argo-linux-amd64.gz` will download an empty file. This broke every single pipeline from multiple IPs and zones

**Comment by book987** [comment]
try `https://github.com/argoproj/argo-workflows/releases...`, replace /argo/ with /argo-workflows/, this should work

**Comment by Guillermogsjc** [comment]
Ok great, just copied it from https://github.com/argoproj/argo-workflows/releases, but now it is corrected. Great it works that way.

Thanks.

**Comment by Guillermogsjc** [comment]
Do not close it , as this for example does not work:

``curl -sLO curl -sLO https://github.com/argoproj/argo-workflows/releases/download/v3.0.1/argo-linux-amd64.gz``` will throw an empty file .





```

**Comment by tczhao** [comment]
> Do not close it , as this for example does not work:
> 
> * `curl -sLO https://github.com/argoproj/argo-workflows/releases/download/v3.0.1/argo-linux-amd64.gz` will throw an empty file .
> * `curl -sLO https://github.com/argoproj/argo/releases/download/v3.0.1/argo-linux-amd64.gz` does not work neither.

Hmm, the first command works fine for me, got a 40M gz file.
Can you please try again

**Comment by Guillermogsjc** [comment]
Yep, now it works. This morning it was giving a 4 kb file.

**Comment by mattyb** [comment]
Was this repo renaming intentional? Was there notice somewhere we could watch in the future?

**Comment by sarabala1979** [comment]
URL redirection was changed recently to point the `ARGOCON21` landing page. Please release `argo-workflows` for workflow relate URLs

**Comment by RafalSkolasinski** [comment]
On related note, we observe a lot of installation failures on our side when installing argo (workflows) using following manifests
```
https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml
```

A lot of our scripts and CI pipelines got broken by renaming of the repository. Could a proper redirect be put in place?

**Comment by alexec** [comment]
This can’t be fixed I’m afraid as we do now control the redirection.

**Comment by RafalSkolasinski** [comment]
Can there be an archived repo present under the old location `github.com/argoproj/argo` with a notice at the top that new repo is under `github.com/argoproj/argo-workflows`?

**Comment by agilgur5** [comment]
I'm not sure when this changed, but, for posterity, https://github.com/argoproj/argo does redirect to https://github.com/argoproj/argo-workflows these days and has for at least 2 years
