### ISSUE TITLE
Is there a hook for enter for template?

### ISSUE THREAD

**Issue by uxth** [argoproj/argo-workflows#6313]
# Summary
Is there a hook for enter for templates?

# Use Cases
We have scenario like this:
When a step is initiated or started, we will need the workflow to call some webhooks to notify my system that this step has started.
When a step is finished, we will need the workflow to call some other webhooks to notify my system that this step has ended.

https://github.com/argoproj/argo-workflows/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go
in this file, I found there is an exit event for the step to achieve the ending event callback.
but there is no event for enter.

Could you help here, how I can achieve this scenario?

Best

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
HTTP Template feature can be enhanced to support this lifecycle hook.  MVP of HTTP template targeted on v3.2

**Comment by uxth** [comment]
Hi @sarabala1979 thank you for the reply, could you give an example how to do it plz?

**Comment by sarabala1979** [comment]
Currently, the HTTP template feature is under development. I will release it on v3.2.  To support  workflow lifecycle hook, We need further deveployment

**Comment by uxth** [comment]
is it possible to leverage the lifecycle in kubernetes?

**Comment by uxth** [comment]
or is there any way to implement this feature on the entry point?

**Comment by sarabala1979** [comment]
yes Controller will emit the k8s event for every status change.

**Comment by uxth** [comment]
could you help me to point it out how to do this every status change event?

**Comment by alexec** [comment]
I think this fixed in v3.3
