### ISSUE TITLE
how to login through client

### ISSUE THREAD

**Issue by hellobiek** [argoproj/argo-workflows#6319]
I have deploy a argo service, and argo-server runing client in mode

argo-server log is belows：
```
level=info authModes="[client]" baseHRef=/ managedNamespace= namespace=argo secure=true
```

but when in the UI mode, I can not using it,  please see the following picture.

![IMG_4507](https://user-images.githubusercontent.com/2854520/125192396-364f8280-e27a-11eb-862b-e4b2d7c63935.JPG)

so, follow the message  I run the command `argo auth token`

but the command run failed again!

![IMG_4509](https://user-images.githubusercontent.com/2854520/125192626-706d5400-e27b-11eb-97a8-455345301e7e.JPG)

so, can you show more details for how to use argo?

thank you very much!!!!!

**Comment by hellobiek** [comment]
I have get the right info from [o](https://argoproj.github.io/argo-workflows/access-token/ ​), so drop this problem

**Comment by sarabala1979** [comment]
@hellobiek Still are you having this issue?

**Comment by hellobiek** [comment]
no thanks! close it
