### ISSUE TITLE
Allow specifying Semaphore limits with parameters/numbers rather than just config map references

### ISSUE THREAD

**Issue by moshewe** [argoproj/argo-workflows#6338]
# Summary

Allow specifying semaphore value by explicit number/parameter

# Use Cases

1. When using workflow generators, be them obscure scripts or `couler`, it's easier to encode the semaphore limits directly into the workflow definitions.
2. The semaphore value for a parallel operation might be decided in a prior step in the workflow, so outputting it as a parameter and using it as the semaphore value would make perfect sense. E.g. I want to perform a map-reduce and the amount of parallel maps should be no more than 10% of number of mappable items.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by agilgur5** [comment]
This is superseded by #11890 which describes this with a concrete example and also has some commentary from me on it on why this changes the model -- it can cause issues with semaphores shared between Workflows.

For a semaphore that is only used in a single Workflow, you can already achieve this with [the `parallelism` field](https://argo-workflows.readthedocs.io/en/latest/synchronization/#workflow-level-parallelism)
