### ISSUE TITLE
Release v3.1.1 using latest containers

### ISSUE THREAD

**Issue by elocke** [argoproj/argo-workflows#6343]
## Summary 

It appears that the v3.1.1 manifests in `/manifests` are using the `:latest` containers. I expect them to be `:v3.1.1` like prior releases.

## Diagnostics

What Kubernetes provider are you using? EKS
What version of Argo Workflows are you running? `v3.1.1`
Did this work in a previous version? I.e. is it a regression? Yes

**Comment by kzzalews** [comment]
Manifests were specifying proper Docker images up to version v3.0.8 of Argo Workflows. With version v3.1.0, specific version tags were changed to `latest`. It seems that these changes used to be done manually.

**Comment by sarabala1979** [comment]
@elocke I am working v3.1.2 release today which will overwrite your PR.

**Comment by kzzalews** [comment]
@sarabala1979, thanks for info! I'm closing my PR.

**Comment by kzzalews** [comment]
@sarabala1979 Tag 3.1.2 still doesn't specify proper Docker image versions inf YAMLs. See: https://github.com/argoproj/argo-workflows/blob/v3.1.2/manifests/install.yaml

**Comment by alexec** [comment]
Please read https://github.com/argoproj/argo-workflows/blob/master/docs/upgrading.md.
