### ISSUE TITLE
`io.k8s.apimachinery.pkg.util.intstr.IntOrString` is defined as string

### ISSUE THREAD

**Issue by uxth** [argoproj/argo-workflows#6349]
## Summary 

in this swagger.json file https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/openapi-spec/swagger.json

the io.k8s.apimachinery.pkg.util.intstr.IntOrString is defined as string

which make it unable to accept int

Is this a bug or by design?

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

Did this work in a previous version? I.e. is it a regression?

Are you pasting thousands of log lines? That's too much information. 

```bash
# Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:
kubectl get wf -o yaml ${workflow}

# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
See #6060. This cannot be fixed I'm afraid.
