### ISSUE TITLE
Not able to start argo ui (argo-workflows) with minikube

### ISSUE THREAD

**Issue by deepaksinghvi** [argoproj/argo-workflows#6362]
## Summary 
Not able to start argo ui (argo-workflows) with minikube
Running the following commands:
```
minikube start
kubectl create ns argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/namespace-install.yaml
kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=argo:default --namespace=argo
kubectl -n argo port-forward svc/argo-server 2746:2746
```
Expected that your should be running locally but after starting it getting errors as follows
 Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

What happened/what you expected to happen?
Able to start argo ui at
http://localhost:2746 or
https://localhost:2746

Before we start, around 2/3 of issues can be fixed by one of the following:

* Have you double-checked your configuration? Maybe 30% of issues are wrong configuration.
* Have you tested to see if it is fixed in the latest version? Maybe 20% of issues are fixed by this.
* Have you tried using the PNS executer instead of Docker? Maybe 50% of artifact related issues are fixed by this.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
minikube
What version of Argo Workflows are you running? 
v3.0.3 (stable)
What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Docker
Did this work in a previous version? I.e. is it a regression?
Using first time on local machine with version 3.0.3
Are you pasting thousands of log lines? That's too much information. 
No
```bash
# Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:
kubectl get wf -o yaml ${workflow}

# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
Can you check argo server pod log?

**Comment by deepaksinghvi** [comment]
![image](https://user-images.githubusercontent.com/1555248/126462515-9b7152dd-4119-4255-8138-7568f36f8cd3.png)

**Comment by deepaksinghvi** [comment]
Argo Server Log

```
time="2021-07-21T08:55:08.758Z" level=info authModes="[server]" baseHRef=/ managedNamespace= namespace=argo secure=true
time="2021-07-21T08:55:08.758Z" level=warning msg="You are running without client authentication. Learn how to enable client authentication: https://argoproj.github.io/argo-workflows/argo-server-auth-mode/"
time="2021-07-21T08:55:08.758Z" level=info msg="config map" name=workflow-controller-configmap
time="2021-07-21T08:55:08.758Z" level=info msg="SSO disabled"
time="2021-07-21T08:55:08.771Z" level=info msg="Starting Argo Server" instanceID= version=v3.0.8
time="2021-07-21T08:55:08.772Z" level=info msg="Creating event controller" operationQueueSize=16 workerCount=4
time="2021-07-21T08:55:08.791Z" level=info msg="Argo Server started successfully on https://localhost:2746"
time="2021-07-21T09:00:08.415Z" level=info msg="Alloc=7953 TotalAlloc=20866 Sys=73553 NumGC=7 Goroutines=92"
time="2021-07-21T09:05:08.075Z" level=info msg="Alloc=10408 TotalAlloc=27842 Sys=73553 NumGC=9 Goroutines=92"
```

**Comment by jceb** [comment]
I received the same error. Changing to https -> https://localhost:2746/ solved the problem for me.
