### ISSUE TITLE
Link to join Slack channel is not working

### ISSUE THREAD

**Issue by domderen** [argoproj/argo-workflows#6363]
## Summary 

Hey, I tried joining Argo Slack channel, but the link that is available on your website and in this Github project is not working. Is the Slack channel still available? The link I'm using: https://argoproj.github.io/community/join-slack

<img width="1680" alt="Zrzut ekranu 2021-07-18 o 22 37 07" src="https://user-images.githubusercontent.com/2360738/126081444-11031e53-8be5-4a10-80c2-2ce4a891b5ea.png">

**Comment by tczhao** [comment]
I think that page definitely has some issues.
Also argo is now on cncf slack,
you can join by https://slack.cncf.io/ then #argo-workflows channel

**Comment by sarabala1979** [comment]
@tczhao Do you like to submit the PR for this?

**Comment by tczhao** [comment]
I think it's related to this PR https://github.com/argoproj/argo-site/pull/58
Let's ask the original author first?

Hi @todaywasawesome, do you have any plan to add the slack page in the near future?

**Comment by domderen** [comment]
Awesome, thanks @tczhao !

**Comment by tczhao** [comment]
seems fixed https://github.com/argoproj/argo-site/pull/62
can close the issue now

**Comment by domderen** [comment]
Yeah looks like it's working now, thanks!
