### ISSUE TITLE
CLI install guide for Darwin/MacOS incorrect

### ISSUE THREAD

**Issue by Ben-Epstein** [argoproj/argo-workflows#6364]
In the releases, the gz url is https://github.com/argoproj/argo/releases/download/v3.1.2/argo-darwin-amd64.gz
See https://github.com/argoproj/argo-workflows/releases/tag/v3.1.2

It needs to be https://github.com/argoproj/argo-workflows/releases/download/v3.1.2/argo-darwin-amd64.gz

**Comment by tczhao** [comment]
Good finding.

I think it's because https://github.com/argoproj/argo-workflows/commit/0a16a5210f44dcbc81410f69bc3c79d3a933b540 didn't get picked when doing the 3.1.2 release

**Comment by sarabala1979** [comment]
yes, I updated the release note
