### ISSUE TITLE
v3.2.4 Daemon step in running state, but dependents don't start

### ISSUE THREAD

**Issue by atombender** [argoproj/argo-workflows#6379]
On `latest`, my workflow consistently gets stuck while progressing on a daemon step that has successfully started. Works fine on 3.1.2.

* [Workflow controller log](https://gist.github.com/atombender/a6235070181a77a091070afa8f548c9b)
* [Output of `kubectl describe pod` for stuck pod](https://gist.github.com/atombender/c704ff3e82f6c3c32baea7dddbdded2f)
* [Workflow YAML](https://gist.github.com/atombender/82d78abef7ca94ce620d0b4e91d36057) (slightly censored)

Eventually, it fails with "Pod was active on the node longer than the specified deadline", and the workflow fails.

**Comment by alexec** [comment]
Related? #6237

**Comment by alexec** [comment]
Is this still a problem please?

**Comment by atombender** [comment]
We're still on 3.1.2 due to this bug. Have there been any improvements related to this?

**Comment by sarabala1979** [comment]
@atombender Can you try v3.1.12?

**Comment by atombender** [comment]
We tried the latest version (v3.2.0), and encountering same problem as before. It stops at a fairly early stage, while waiting for some daemon steps. The daemons start, but Argo never continues with the next steps.

[Workflow controller log](https://github.com/argoproj/argo-workflows/files/7336371/workflow-controller.log). The workflow is called `test-stargate-bqtxw`.

**Comment by jccarte** [comment]
I seem to still be hitting this issue in 3.2.4.  I have a templateRef in a workflow that points to a template that has multiple steps. In 3.1.X (up to 3.1.15) this workflow runs fine and the dependant steps start and finish. In 3.2.4 the dependant step is never started.

workflow:
...
  templates:
  - name: main
    dag:
      tasks:
        - name: run-tests
          when: "{{tasks.load-manifest.outputs.parameters.has-tests}} == true"
          templateRef:
            name: run-tests
            template: main

run-tests workflowtemplate:
templates:
  - name: main
    inputs:
      parameters:
       ...
    steps:
      - - name: postgres
          template: postgres
          when: "{{inputs.parameters.postgres}} == true"
      - - name: run-tests
          template: run-tests
          arguments:
          ....

**Comment by jdolce** [comment]
@sarabala1979 my example above still doesn't work in 3.2.5

**Comment by jdolce** [comment]
@sarabala1979 the example here - https://github.com/argoproj/argo-workflows/issues/6379#issuecomment-953925549 still does not work in 3.2.5

**Comment by alexec** [comment]
Should be fixed on `latest` and will be on v3.2.7
