### ISSUE TITLE
Add UI capabilities to control specific nodes in the workflow

### ISSUE THREAD

**Issue by basanthjenuhb** [argoproj/argo-workflows#6382]
# Summary

- This is regarding adding more capability in the UI regarding step workflows and dag workflows
- May a times, we have requirement to override and instance of a workflow
- This overriding could be of the form
    - allow selecting parameters manually at different nodes
    - Being able to hold/pause a specific node in the workflow
    - Release a node at will
    - Rerun a node with different parameters
    - Rerun dependent nodes (In dag) at will
    - Cancel dependent nodes at will
    - Mark a node as completed succesfull even though it failed and vice versa
- This enables a more friendly usage from the UI and would make it easier for debugging, retries etc.
- This also helps in manually fixing one of workflow instances
- Currently, to achieve the same, we have to edit the workflow itself which might not be desirable.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by qiyin777** [comment]
”Rerun a node with different parameters“ This could be super helpful.
