### ISSUE TITLE
UI: Selection in the log viewer is immediately unselected

### ISSUE THREAD

**Issue by atombender** [argoproj/argo-workflows#6384]
When trying to select text in the log viewer for a running pod, the selection immediately disappears. [Here](https://user-images.githubusercontent.com/50314/126376000-16590f17-a2e4-49b7-a362-ce999048078b.mp4) is a video. 

It also appears that the log viewer isn't a real text box with the full content, as it's not possible to workaround this problem by doing a "select all" of the entire web page to get the contents.

Version 3.1.2.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Is this still a problem please?

**Comment by alexec** [comment]
@sarabala1979 example

**Comment by atombender** [comment]
It's a problem in 3.1.2, which is what we are using. Has there been a fix released? It'd be nice to know before I bother our ops team with an upgrade request.

**Comment by alexec** [comment]
So you want to be able to select all the text from the logs?

**Comment by atombender** [comment]
You can't select text if log entries are being written, and you can't scroll after selecting text, and you certainly can't select the whole thing.

**Comment by alexec** [comment]
What about adding a button like "Copy logs to clipboard"?

**Comment by atombender** [comment]
That seems like a hack. I don't always want to copy the whole thing. I just want selection to work, instead of being broken.

**Comment by alexec** [comment]
A hack. A cheap hack. Which is a good. Rather than a complex bullet proof fix.

**Comment by atombender** [comment]
I dunno, I prefer to fix bugs rather than working around them. And in Argo, I select single words or lines much more often than I select everything.

**Comment by alexec** [comment]
Sure. This bug has few up-votes, so I don't see it getting prioritised. Just wondering if there was a cheap fix which could be expedited. Doesn't sound like it is the case.

**Comment by kennytrytek** [comment]
One workaround is to use the artifact logs instead of the log viewer. I typically do this whenever I need to search for text or copy/paste segments out that don't fit in the viewport.
