### ISSUE TITLE
Invalid value for `active`, must not be `None` when trying to list cron workflows

### ISSUE THREAD

**Issue by lloyd-dotmodus** [argoproj/argo-workflows#6399]
## Summary 

What happened/what you expected to happen?
- When listing Cron Workflows through the latest Argo API (https://pypi.org/project/argo-workflows/) the following error occurs: Invalid value for `active`, must not be `None`

I seems to be related to this issue logged previously: https://github.com/argoproj/argo-workflows/issues/4510
That seemed to have been closed because it was stale though, there was no solution in the comments. Seems to be a known issue but I could not find an answer that solved it.

I did comment there as well.

Here is the codeblock in question:

```
# Get Cron Workflows
cron_worfklow_data = {}
cron_workflows = None
try:
    cron_workflows = cron_workflow_api.list_cron_workflows('argo')
except ApiException as api_err:
    LOGGER.error("The following error was raised when "
                 "attempting to list

```
                   
And here is the stacktrace:

> File "/Users/lloydmckeen/.pyenv/versions/insights-ui/lib/python3.8/site-packages/argo/workflows/client/models/v1alpha1_cron_workflow_status.py", line 83, in active
    raise ValueError("Invalid value for `active`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `active`, must not be `None`

> response body: b'{"metadata":{"resourceVersion":"34021376"},"items":[{"metadata":{"name":"ai-windtunnl-connector-template-cron","namespace":"argo","uid":"36882892-a33e-4850-af9b-530226aa1b34","resourceVersion":"33995265","generation":4,"creationTimestamp":"2021-07-21T15:58:56Z","labels":{"workflows.argoproj.io/creator":"system-serviceaccount-argo-argo-server"},"managedFields":[{"manager":"argo","operation":"Update","apiVersion":"argoproj.io/v1alpha1","time":"2021-07-21T15:59:49Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:workflows.argoproj.io/creator":{}}},"f:spec":{".":{},"f:schedule":{},"f:suspend":{},"f:workflowSpec":{".":{},"f:arguments":{".":{},"f:parameters":{}},"f:workflowTemplateRef":{".":{},"f:name":{}}}},"f:status":{".":{},"f:active":{},"f:conditions":{},"f:lastScheduledTime":{}}}}]},"spec":{"workflowSpec":{"arguments":{"parameters":[{"name":"connector_id","value":"6"}]},"workflowTemplateRef":{"name":"ai-windtunnl-connector-template"}},"schedule":"0 12 * * *","suspend":true},"status":{"active":null,"lastScheduledTime":null,"conditions":null}}]}'
*** ValueError: Invalid value for `active`, must not be `None`

## Diagnostics

What Kubernetes provider are you using? 
K8's on GCP

What version of Argo Workflows are you running? 

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Docker/K8SAPI/

Did this work in a previous version? I.e. is it a regression?
Hasn't worked before

argo-workflows~=5.0.0

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by lloyd-dotmodus** [comment]
Also I'm using the same API calls for workflows and worflow_templates respectively and they work fine just above this code:

i.e
`workflows = workflow_api.list_workflows('argo')
``workflow_templates = workflow_template_api.list_workflow_templates('argo')`

**Comment by cccdy** [comment]
> ## Summary
> What happened/what you expected to happen?
> 
> * When listing Cron Workflows through the latest Argo API (https://pypi.org/project/argo-workflows/) the following error occurs: Invalid value for `active`, must not be `None`
> 
> I seems to be related to this issue logged previously: #4510
> That seemed to have been closed because it was stale though, there was no solution in the comments. Seems to be a known issue but I could not find an answer that solved it.
> 
> I did comment there as well.
> 
> Here is the codeblock in question:
> 
> ```
> # Get Cron Workflows
> cron_worfklow_data = {}
> cron_workflows = None
> try:
>     cron_workflows = cron_workflow_api.list_cron_workflows('argo')
> except ApiException as api_err:
>     LOGGER.error("The following error was raised when "
>                  "attempting to list
> ```
> 
> And here is the stacktrace:
> 
> > File "/Users/lloydmckeen/.pyenv/versions/insights-ui/lib/python3.8/site-packages/argo/workflows/client/models/v1alpha1_cron_workflow_status.py", line 83, in active
> > raise ValueError("Invalid value for `active`, must not be `None`")  # noqa: E501
> > ValueError: Invalid value for `active`, must not be `None`
> 
> > response body: b'{"metadata":{"resourceVersion":"34021376"},"items":[{"metadata":{"name":"ai-windtunnl-connector-template-cron","namespace":"argo","uid":"36882892-a33e-4850-af9b-530226aa1b34","resourceVersion":"33995265","generation":4,"creationTimestamp":"2021-07-21T15:58:56Z","labels":{"workflows.argoproj.io/creator":"system-serviceaccount-argo-argo-server"},"managedFields":[{"manager":"argo","operation":"Update","apiVersion":"argoproj.io/v1alpha1","time":"2021-07-21T15:59:49Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:workflows.argoproj.io/creator":{}}},"f:spec":{".":{},"f:schedule":{},"f:suspend":{},"f:workflowSpec":{".":{},"f:arguments":{".":{},"f:parameters":{}},"f:workflowTemplateRef":{".":{},"f:name":{}}}},"f:status":{".":{},"f:active":{},"f:conditions":{},"f:lastScheduledTime":{}}}}]},"spec":{"workflowSpec":{"arguments":{"parameters":[{"name":"connector_id","value":"6"}]},"workflowTemplateRef":{"name":"ai-windtunnl-connector-template"}},"schedule":"0 12 * * *","suspend":true},"status":{"active":null,"lastScheduledTime":null,"conditions":null}}]}'
> > *** ValueError: Invalid value for `active`, must not be `None`
> 
> ## Diagnostics
> What Kubernetes provider are you using?
> K8's on GCP
> 
> What version of Argo Workflows are you running?
> 
> What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
> Docker/K8SAPI/
> 
> Did this work in a previous version? I.e. is it a regression?
> Hasn't worked before
> 
> argo-workflows~=5.0.0
> 
> **Message from the maintainers**:
> 
> Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

When creating cron workflow according to the api client, the same exception occurs['ValueError: Invalid value for active, must not be None']
So i want to confirm whether it is solved, or some insight. Big thx~

**Comment by cccdy** [comment]
> > ## Summary
> > What happened/what you expected to happen?
> > 
> > * When listing Cron Workflows through the latest Argo API (https://pypi.org/project/argo-workflows/) the following error occurs: Invalid value for `active`, must not be `None`
> > 
> > I seems to be related to this issue logged previously: #4510
> > That seemed to have been closed because it was stale though, there was no solution in the comments. Seems to be a known issue but I could not find an answer that solved it.
> > I did comment there as well.
> > Here is the codeblock in question:
> > ```
> > # Get Cron Workflows
> > cron_worfklow_data = {}
> > cron_workflows = None
> > try:
> >     cron_workflows = cron_workflow_api.list_cron_workflows('argo')
> > except ApiException as api_err:
> >     LOGGER.error("The following error was raised when "
> >                  "attempting to list
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And here is the stacktrace:
> > > File "/Users/lloydmckeen/.pyenv/versions/insights-ui/lib/python3.8/site-packages/argo/workflows/client/models/v1alpha1_cron_workflow_status.py", line 83, in active
> > > raise ValueError("Invalid value for `active`, must not be `None`")  # noqa: E501
> > > ValueError: Invalid value for `active`, must not be `None`
> > 
> > 
> > > response body: b'{"metadata":{"resourceVersion":"34021376"},"items":[{"metadata":{"name":"ai-windtunnl-connector-template-cron","namespace":"argo","uid":"36882892-a33e-4850-af9b-530226aa1b34","resourceVersion":"33995265","generation":4,"creationTimestamp":"2021-07-21T15:58:56Z","labels":{"workflows.argoproj.io/creator":"system-serviceaccount-argo-argo-server"},"managedFields":[{"manager":"argo","operation":"Update","apiVersion":"argoproj.io/v1alpha1","time":"2021-07-21T15:59:49Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:workflows.argoproj.io/creator":{}}},"f:spec":{".":{},"f:schedule":{},"f:suspend":{},"f:workflowSpec":{".":{},"f:arguments":{".":{},"f:parameters":{}},"f:workflowTemplateRef":{".":{},"f:name":{}}}},"f:status":{".":{},"f:active":{},"f:conditions":{},"f:lastScheduledTime":{}}}}]},"spec":{"workflowSpec":{"arguments":{"parameters":[{"name":"connector_id","value":"6"}]},"workflowTemplateRef":{"name":"ai-windtunnl-connector-template"}},"schedule":"0 12 * * *","suspend":true},"status":{"active":null,"lastScheduledTime":null,"conditions":null}}]}'
> > > *** ValueError: Invalid value for `active`, must not be `None`
> > 
> > 
> > ## Diagnostics
> > What Kubernetes provider are you using?
> > K8's on GCP
> > What version of Argo Workflows are you running?
> > What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
> > Docker/K8SAPI/
> > Did this work in a previous version? I.e. is it a regression?
> > Hasn't worked before
> > argo-workflows~=5.0.0
> > **Message from the maintainers**:
> > Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
> 
> When creating cron workflow according to the api client, the same exception occurs['ValueError: Invalid value for active, must not be None']
> So i want to confirm whether it is solved, or some insight. Big thx~

Solved luckily, turn to an alternative way using kubernetes python sdk, maybe it is a better way according k8s python sdk more generally . 
The example is as follow, hope it helps~
`config.kube_config.load_kube_config(config_file=CONF_FILE)
with open(yaml_conf) as file:
        body = yaml.load(file, Loader=yaml.FullLoader)
        resp = client.CustomObjectsApi().create_namespaced_custom_object(namespace='argo', group='argoproj.io',
                                                                                   version='v1alpha1',
                                                                                   plural='cronworkflows', body=body)
print(resp)`

**Comment by alexec** [comment]
We don't support that SDK. Can you please try with CoulerProj?

**Comment by Nayan155** [comment]
I am facing the same issue. does anyone have a solution?

**Comment by bensternlieb** [comment]
Same issue.  Used to use this simple 
```
    def submit(self):
        """Generates and submits a cron workflow."""
        load_kube_config()
        V1alpha1Api().create_namespaced_workflow(
            "default", self.get_cron_workflow()
        )
```

I'd use the create_namespaced_custom_object mentioned above, but guess the Argo folks say not too?  Anyway - exposing the Argo Server for me is not possible.  Might have to do something pokey like exec `Argo server` in a context and then connect to it via `argo_workflows.Configuration(host="https://127.0.0.1:2746")`
