### ISSUE TITLE
argo-server asks for authentication despite the fact that it is in server mode

### ISSUE THREAD

**Issue by sylock** [argoproj/argo-workflows#6404]
## Summary 

I upgraded argo-workflows from 3.0.1 to 3.1.2 on my local setup. The upgrade seems fine the the web interface request a token despite the fact that I'm in "server" mode.

Here are the logs of the argo-server pod
```
time="2021-07-22T14:08:27.700Z" level=info authModes="[client]" baseHRef=/ managedNamespace= namespace=argo-wf-development secure=false
time="2021-07-22T14:08:27.700Z" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argoproj.github.io/argo-workflows/tls/"
time="2021-07-22T14:08:27.700Z" level=info msg="config map" name=workflow-controller-configmap
time="2021-07-22T14:08:27.700Z" level=info msg="SSO disabled"
time="2021-07-22T14:08:27.744Z" level=info msg="Starting Argo Server" instanceID= version=v3.1.2
time="2021-07-22T14:08:27.744Z" level=info msg="Creating DB session"
time="2021-07-22T14:08:27.806Z" level=info msg="Node status offloading config" ttl=5m0s
time="2021-07-22T14:08:27.806Z" level=info msg="Creating event controller" operationQueueSize=16 workerCount=4
time="2021-07-22T14:08:27.823Z" level=info msg="Argo Server started successfully on http://localhost:2746"
time="2021-07-22T14:09:42.362Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2021-07-22T14:09:42Z" grpc.time_ms=0.54 span.kind=server system=grpc
```

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
# I'm on Openshift
$ oc version
Client Version: 4.7.2
Server Version: 4.5.5
Kubernetes Version: v1.18.3+08c38ef

What version of Argo Workflows are you running? 
v3.1.2

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
PNS

Did this work in a previous version? I.e. is it a regression?
Yes in 3.0.1 (but did not tested in-between 3.0.1 and 3.1.2)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
```
level=info authModes="[client]" 
```

Double-check your manifests.

**Comment by sylock** [comment]
Yes, mistake from my side. Thanks.
