### ISSUE TITLE
invalid container names (i.e. not "main") are allowed and causes bugs

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6405]
We should not allow invalid container names. It is confusing for users and costs time to investigate.

I think we can add a check here:

https://github.com/argoproj/argo-workflows/blob/092b4271b9b57ce9dbff0d988b04ddbf9742425c/workflow/validate/validate.go#L372

@stevenbressey would you be interested in helping fix this as you were impacted by this recently?

**Comment by stevenbressey** [comment]
@alexec with pleasure !
Just give me the requirements and I can start working on it next week.

**Comment by alexec** [comment]
I think basically if you validate a workflow, and the container is not named "main", there should be an error.

**Comment by alexec** [comment]
This is actually a regression.

**Comment by alexec** [comment]
feat(controller): Container set template. Closes #2551 (#5099)
