### ISSUE TITLE
Workflows not getting terminated automatically

### ISSUE THREAD

**Issue by sbjetty** [argoproj/argo-workflows#6407]
## Summary 

I have argo workflow setup with multiple steps. In one of the steps pods are stuck in running state for more than a day. When I checked the pod info using` kubectl describe pod ` it shows pod status as terminated with reason `Message:  error dialing backend: dial tcp 127.0.0.40:10260: connect: connection refused`. Even If I force terminate using the "terminate" button in UI, it does not seem to do anything. 

What happened/what you expected to happen?
I expect the workflow to be terminated and trigger the exit handler I had setup for workflow. 

Before we start, around 2/3 of issues can be fixed by one of the following:

* Have you double-checked your configuration? Maybe 30% of issues are wrong configuration.
* Have you tested to see if it is fixed in the latest version? Maybe 20% of issues are fixed by this.
* Have you tried using the PNS executer instead of Docker? Maybe 50% of artifact related issues are fixed by this.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 
argo: v2.12.3
  BuildDate: 2021-01-05T00:49:48Z
  GitCommit: 93ee530126cc1fc154ada84d5656ca82d491dc7f
  GitTreeState: clean
  GitTag: v2.12.3
  GoVersion: go1.13
  Compiler: gc
  Platform: darwin/amd64

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
ContainerRuntimeExecutor: k8sapi

Did this work in a previous version? I.e. is it a regression?
This is first time setting up. Haven't tried older versions. 

Are you pasting thousands of log lines? That's too much information. 
Nope. 

```bash
# Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:
kubectl get wf -o yaml ${workflow}

# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@sbjetty share the workflow and pod yaml file. 
Can you try on v3.1.2?
