### ISSUE TITLE
wait container won't exit

### ISSUE THREAD

**Issue by philosophicus** [argoproj/argo-workflows#6415]
## Summary 

I'm using argo v3.0.7 and came across a rare case today.

![Screen Shot 2021-07-23 at 6 02 13 PM](https://user-images.githubusercontent.com/9477891/126767051-f2dacaec-9c4e-4d02-b3e1-2da5ce31d183.png)
(creation times of all the containers and pod of a task, output of `docker ps`)

A wait container won't exit because it was created too late, according to https://github.com/argoproj/argo-workflows/blob/c9246d3d4c162e0f7fe76f2ee37c55bdbfa4b0c6/workflow/executor/docker/docker.go#L277 . Is it possible to use a greater number? Furthermore, is it really necessary to check the time lag? 

Is that anything I can do to make the workflow continue to run normally?  

```

---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by philosophicus** [comment]
https://github.com/argoproj/argo-workflows/issues/6345, another issue from me, which is not related to this one. Many thanks to anyone who checks that out.

**Comment by sarabala1979** [comment]
@philosophicus can you share the `wait` container log?

**Comment by philosophicus** [comment]
@sarabala1979 Thanks for you reply. Here is the `wait` container log.
<img width="1316" alt="Screen Shot 2021-07-24 at 1 32 14 AM" src="https://user-images.githubusercontent.com/9477891/126819878-782d65da-ec6f-4ef0-af5d-6861c3e28fb3.png">

**Comment by sarabala1979** [comment]
@philosophicus Will your main container takes more than 15s to start?

**Comment by alexec** [comment]
@sarabala1979 I think I need to take a deep dive into docker executor. I will own this.

**Comment by philosophicus** [comment]
@alexec Thanks for the fix.
