### ISSUE TITLE
container logs always get truncated

### ISSUE THREAD

**Issue by philosophicus** [argoproj/argo-workflows#6416]
## Summary 

I'd like to know when logs will be truncated. The logs are definitely not too large in size. It seems that the truncation always takes place in specific lines. I'm wondering whether it's because there are some invisible characters which cause the truncation. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by philosophicus** [comment]
@sarabala1979 Hi, any comments on this issue?

**Comment by sarabala1979** [comment]
@philosophicus are you seeing the log truncation in UI or CLI?

**Comment by philosophicus** [comment]
@sarabala1979 Both in UI and when I use `kubectl logs` to examine the container logs
