### ISSUE TITLE
Use PNS with`emissary` executor to kill more kinds of injected sidecar

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6417]
We could get the benefits of both by adding some of the features of PNS to emissary.

Specifically, PNS can kill injected sidecars easily, just using kill. If emissary used PNS, then we could probably fix that problem effectively.

**Comment by Bobgy** [comment]
I like this, but note that this will mean emissary will not be able to run on GKE autopilot, because SYS_PTRACE is the permission not allowed, so probably this has to be an option too.
