### ISSUE TITLE
Allow to pass imagePullSecret for a argoexec image

### ISSUE THREAD

**Issue by BohdanKalytka** [argoproj/argo-workflows#6423]
# Summary

There is a security requirement to pull all images from private repositories. We have all the required images already mirrored in our private repo, but after changing the image repo and adding imapePullSecret into deployment spec I still see that `argoexec` image cannot be pulled.  Everything else seems to be working fine.
I looked through docs and workflow-controller options but didn't find a way to to add image pull secrets into workflow-controller options.
It would be great to have a possibility to pull executor images from private repos.

# Use Cases

Security enforcement to pull all images from the private repo.
Using custom executor image from the private repo.

---
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tczhao** [comment]
Hi @BohdanKalytka ,
I think you can use podspecpatch to add imagepullsecret to the init/wait container (where the argoexec image is used)
https://github.com/argoproj/argo-workflows/blob/master/examples/pod-spec-patch.yaml

**Comment by BohdanKalytka** [comment]
Hi @tczhao Thanks, that worked. However, it does not feel like the correct way of solving this problem. I would be glad to see some other options in the future. 
I will close the issue anyway. Thanks for prompt support.
