### ISSUE TITLE
Binary download links in Releases point to old repo (404)

### ISSUE THREAD

**Issue by mac9416** [argoproj/argo-workflows#6440]
The "quick start" binary download links in the 3.1.3 [release page](https://github.com/argoproj/argo-workflows/releases/tag/v3.1.3) point to `argoproj/argo` instead of `argoproj/argo-workflows`, [causing some confusion](https://stackoverflow.com/questions/68557958/how-to-install-argo-cli).

It might be worth changing the `curl` flags to be more verbose so people can more easily self-diagnose this.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
updated the release note. I will fix the ci
