### ISSUE TITLE
UI cron section crashes with "Cannot read property 'toString' of undefined"

### ISSUE THREAD

**Issue by avifried1** [argoproj/argo-workflows#6447]
## Summary 

Can't seem to reproduce this, but at some conditions, the Cron workflows section (and only that section) crashes with:

```
react_devtools_backend.js:2574 TypeError: Cannot read property 'toString' of undefined
    at t.Timestamp (timestamp.tsx:11)
    at $i (react-dom.production.min.js:150)
    at Io (react-dom.production.min.js:178)
    at qa (react-dom.production.min.js:232)
    at Ga (react-dom.production.min.js:233)
    at Os (react-dom.production.min.js:249)
    at Ls (react-dom.production.min.js:248)
    at Ms (react-dom.production.min.js:245)
    at Qa (react-dom.production.min.js:243)
    at Object.enqueueSetState (react-dom.production.min.js:130)
```

This apparently traces back to this component in timestamp.tsx:

```
  <span>
           {date === null ? (
               '-'
           ) : (
               <span title={date.toString()}>
                   <Ticker intervalMs={1000}>{() => ago(new Date(date))}</Ticker>
               </span>
           )}
       </span>
```

date isn't null, but it's undefined.

Argo version `v3.1.2`.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@avifried1 can you send your cronworkflow yaml. looks like some date field empty.

**Comment by cosmonova** [comment]
Happen to catch this issue due to a incomplete cronworkflow. 
However this is bug and  the UI should bypass this type of error.

**Comment by sarabala1979** [comment]
@cosmonova incomplete cronworkflow mean, it is not yet started or the controller is down. I am trying understand the scenario and try to reproduce it in my env.

**Comment by cosmonova** [comment]
It means is missing some data fields ( Ex: date ) that are required by the UI to render de page. I haven't spent too much time on this, just removed the cronworkflow that was causing this error.

**Comment by avifried1** [comment]
@sarabala1979 Not sure which cronworkflow caused this, we have a lot. But also, same templates are deployed to multiple environments, and for some reason only 1 environment was having this issue. Redeploying fixed this, but really now sure why.

It's obviously a problem if a workflow (any workflow really), which can be added by any engineer, can crash the entire Cron UI section. This might be a simple check on whether the `date` is also `undefined`.

**Comment by sarabala1979** [comment]
@cosmonova @avifried1 Got it. We can extra condition to check whether date is undefined along with a null check. Would you like to fix this issue and submit the PR?
