### ISSUE TITLE
TestGetPodByNode is flakey

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6458]
This test is sporadically failing (10% of the time maybe).

Caused by: feat(controller): opt-in to sending pod node events as pod (#6377)

**Comment by alexec** [comment]
@josephmcgovern-wf could you please take a look if you have time?

**Comment by alexec** [comment]
This test is flakey.

**Comment by alexec** [comment]
I've commit a change to skip this test.

**Comment by alexec** [comment]
@tczhao still seeing failures.

**Comment by micahbeeman-wf** [comment]
@alexec @tczhao This issue was for `TestGetPodByNode` but was closed for a fix to `TestPodExists`. `TestGetPodByNode` is still skipped so this should be reopened.
