### ISSUE TITLE
Add parameters to argo resubmit client function

### ISSUE THREAD

**Issue by Guillermogsjc** [argoproj/argo-workflows#6463]
It would be really useful to allow to the argo client function `resubmit` to admit the `--parameter` flag as does `submit`.

Something like

`argo resubmit -n argo -p UPDATED_PARAMETER=updated_value EXISTING_WORKFLOW_NAME`

The use case is pretty clear, you want to retry a workflow changing some parameters. This is a situation natural on an `onExit` stage (exit handler) with an `argocli` image, that could retry the execution of a workflow changing some configuration on the executed one.

**Comment by sarabala1979** [comment]
@Guillermogsjc `argo resubmit -n argo -p UPDATED_PARAMETER=updated_value EXISTING_WORKFLOW_NAME` is equivalent to submit the new workflow.  you can submit the same workflow with a new parameter.
Is there any specific reason not to submit the workflow again?

**Comment by Guillermogsjc** [comment]
@sarabala1979 right now it looks as not possible to use `submit` with `--from` `wf/EXECUTED_WORKFLOW`.

```
argo submit -n argo --from wf/hello-world-kk9jv
FATA[2021-08-01T14:39:28.388Z] Failed to submit workflow: Resource kind 'wf' is not supported for submitting`
```

Of course this would be a solution, to allow `argo submit` to launch an executed workflow, or to add `parameters` to resubmit.

Think that you want to keep the exact parameters asociated to the workflow that you want to resubmit, and change them, and the spec may not be on any workflow template or cron workflow to submit from again.

**Comment by sarabala1979** [comment]
you achieve same functionality using `workflowtemplate` with `argo submit --from workflowtemplate/<name> -p params`
Convert workflow type to workflowtemplate and create it in your namespace using `argo template create <x.yaml>`

**Comment by sarabala1979** [comment]
@Guillermogsjc

**Comment by Guillermogsjc** [comment]
@sarabala1979 thanks for the workaround, I suggest to add this functionality on client also (as [UI aproved it on 4662](https://github.com/argoproj/argo-workflows/issues/4662)).

Think about workflows being created programatically inside another workflows, having an initial template as parent but having a potential evolution on parameters (needed on re-executions or variations dinamically established inside a workflow that configures the other workflow, or at the exit handler of a workflow to resubmit current one depending on success metrics).

For now instead of cli one must do as long as I understand:

0. Export the executed workflow to yaml.
1. Create a template from an executed workflow `argo template create <x.yaml>`
2. Laungh with argo submit changing the parameters `argo submit --from workflowtemplate/<name> -p params`
3. Delete the created template to cleanup template space.

I guess that this sounds a reasonable workaround but does not look as a natural client solution to this use case, specially it is not clean to create the temporary template.

Kind regards.

**Comment by sarabala1979** [comment]
@Guillermogsjc got it your usecase. it would be a great enhancement on CLI to update the parameter values. Would you like to contribute to this enhancement?

**Comment by Guillermogsjc** [comment]
@sarabala1979 hopefully I could study Go (level 0) and contribute sooner, right now it is hard to collaborate :(

**Comment by ziv-codefresh** [comment]
@sarabala1979 hey we would like to contribute this one, there are few points i would like to clarify:
1. do we want to extend it to other capabilities beside parameters such as entry point, annotations or any other option we have in the submit command?
2. i see there is an option to resubmit by selector, meaning we can resubmit more than 1 workflow. what is the expected behavior in this case? apply the new attributes for each of the workflows?

**Comment by agilgur5** [comment]
This was completed by #9141
