### ISSUE TITLE
Incorrect redirect from argoproj/argo to argoproj/argocon21

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#6464]
## Summary 

It looks like https://github.com/argoproj/argo now redirects to https://github.com/argoproj/argocon21 (forked from https://github.com/todaywasawesome/argo).

This would break all the old issue/PR links that uses "argoproj/argo" and make it hard to find past discussions. 

cc @todaywasawesome who owns the original fork https://github.com/todaywasawesome/argo and might have a better idea on the best way to fix it.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I don't think this is fixable.

**Comment by todaywasawesome** [comment]
All fixed!

**Comment by terrytangyuan** [comment]
Thank you!
