### ISSUE TITLE
Why does a failed pod task have no exit code?

### ISSUE THREAD

**Issue by philosophicus** [argoproj/argo-workflows#6474]
## Summary 

The containers' statuses are shown in the picture.

![Screen Shot 2021-08-03 at 8 46 17 PM](https://user-images.githubusercontent.com/9477891/128019582-3bf72ce9-9f70-475e-b1f1-f0e0738a0d78.png)

And why is the phase of the task `Failed` rather than `Error`?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@philosophicus Can you provide more details like `init` container logs?
