### ISSUE TITLE
v3.1.5 did not contain the fix from #5953

### ISSUE THREAD

**Issue by michael132** [argoproj/argo-workflows#6482]
## Summary 

We upgraded to `v3.1.5` and found out the fix from #5953 was not included in the release

## Diagnostics
PR was merged and stated it will be part of `v3.1.4` release. However, it does not seem to be the case.
https://github.com/argoproj/argo-workflows/blob/v3.1.5/server/auth/types/claims.go

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
This feature PR is not included into 3.1 release. Normally features will not include in the patch release until the user requested.  We created cherry-pick with the list of issue and announce in the channel for select the issue that needs to include on coming patch. only regression issues will be added by default for a patch release.

**Comment by michael132** [comment]
> This feature PR is not included into 3.1 release. Normally features will not include in the patch release until the user requested. We created cherry-pick with the list of issue and announce in the channel for select the issue that needs to include on coming patch. only regression issues will be added by default for a patch release.

Sorry I did not know this. I saw #5953 PR mentioned it'll be available after `v3.1.4` 
https://github.com/argoproj/argo-workflows/blob/90341524935287c7db30f34132c2a1aa4f1ea170/docs/argo-server-sso.md#custom-claims

What would I need to do to make the request? I do see #6468 which is still open

**Comment by sarabala1979** [comment]
cherry-pick is done for 3.1.5. We are in the process of releasing 3.2-rc1 soon. This will include 3.2-rc1.  We may release another patch if there is any regression or high-demand issue. I will create cherry-pick issue and I will notify in the channel. you can select this issue.

**Comment by sarabala1979** [comment]
I will close this issue
