### ISSUE TITLE
Argo v.2.12.6 - Unexpected non 200 status code: 401 body: Unauthorized

### ISSUE THREAD

**Issue by arkgonzales** [argoproj/argo-workflows#6492]
Hi, 

I would like to report an intermittent issue when Argo runs our workflows. At a random point, we get an "Unexpected non 200 status code" error from one of the pods that Argo runs while executing our workflow. It happens to different steps, sometimes frequent.

Hope you could share an insight on why this error is being returned. We believe it's not a service credential issue as no changes were made to the initial setup, and we were able to run our workflows on the same environment without issues.

Please see below for the stacktrace:

time="2021-07-28T09:50:39.426Z" level=info msg="Starting deadline monitor"
time="2021-07-28T09:50:49.427Z" level=info msg="/argo/podmetadata/annotations updated"
time="2021-07-28T09:50:50.432Z" level=warning msg="Failed to wait for container id '8e177955fe0afe4387e1ebc1910964db2aa0eda634e0449a1b2baa78a08a7c2a': unexpected non 200 status code: 401, body: Unauthorized"
time="2021-07-28T09:50:50.432Z" level=error msg="executor error: unexpected non 200 status code: 401, body: Unauthorized\ngithub.com/argoproj/argo/errors.Wrap\n\t/go/src/github.com/argoproj/argo/errors/errors.go:88\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/go/src/github.com/argoproj/argo/errors/errors.go:71\ngithub.com/argoproj/argo/workflow/executor/kubelet.(*kubeletClient).GetContainerStatus\n\t/go/src/github.com/argoproj/argo/workflow/executor/kubelet/client.go:172\ngithub.com/argoproj/argo/workflow/executor/common.WaitForTermination\n\t/go/src/github.com/argoproj/argo/workflow/executor/common/common.go:57\ngithub.com/argoproj/argo/workflow/executor/kubelet.(*kubeletClient).WaitForTermination\n\t/go/src/github.com/argoproj/argo/workflow/executor/kubelet/client.go:285\ngithub.com/argoproj/argo/workflow/executor/kubelet.(*KubeletExecutor).Wait\n\t/go/src/github.com/argoproj/argo/workflow/executor/kubelet/kubelet.go:60\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).Wait.func1\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:1042\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:292\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).Wait\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:1041\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:40\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:13\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"

**Comment by sarabala1979** [comment]
@arkgonzales which executor are you configured in your environment? looks like your k8s API service returns 401 for accessing main container status. 
Do you have a plan to upgrade to v3.1.5? 3.1 has a lot performance improvement on handling k8s API calls. We stop supporting v2.12.x.

**Comment by arkgonzales** [comment]
@sarabala1979 the executor we're using is via kubelet.

Noted on the end of support for ver 2.12.x, we'll check on v3.1.5.

Thank you
