### ISSUE TITLE
Revert fix(executor/docker): fix random errors with message "No such contain… CI #8670

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6499]
This has broken the build on master and needs to be reverted. See #8670

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/commit/e4a53d4bf021fd4dce1374bb7fd4320d733e57ba
@Bobgy

**Comment by alexec** [comment]
![image](https://user-images.githubusercontent.com/1142830/128545087-dfea1100-960d-40ee-afe4-38463717805a.png)

**Comment by alexec** [comment]
Reverted in a3fd704a1.

**Comment by Bobgy** [comment]
Thanks, let's keep tracking the resolution in https://github.com/argoproj/argo-workflows/issues/6352.
