### ISSUE TITLE
Support Server Side Encryption for S3 Artifact Repository

### ISSUE THREAD

**Issue by kevanslumin** [argoproj/argo-workflows#6504]
# Summary

Would you consider adding support for server side encryption in an S3 Artifact Repository?   Here is an example using a customer provided key (SSE-C): https://github.com/minio/minio-go/blob/master/examples/s3/put-encrypted-object.go. However, I'd be interested in using the S3 master key (SSE-S3).  There is also SSE-KMS that others might need.

# Use Cases

My organization requires encrypted S3 buckets, so it would be nice to be able to use an encrypted S3 bucket as an artifact repository for argo workflows.

Thanks.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Duplicate of #2800 ?

**Comment by kevanslumin** [comment]
Yes, I apologize.
