### ISSUE TITLE
delete workflow then create workflow with same name immediately, may cause workflow stuck til another cache sync period

### ISSUE THREAD

**Issue by motocoder-cn** [argoproj/argo-workflows#6526]
## Summary 

What happened/what you expected to happen?

delete workflow then create workflow with same name immediately, may cause workflow stuck til another cache sync period

want second workflow run  as noraml

## Diagnostics

What Kubernetes provider are you using? 

local k8s cluster

What version of Argo Workflows are you running? 
3.0.8

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
docker

i found logs in workflow-controller:

**Failed pods xxx  creations, already exists..**

(i think this maybe first workflow's pods not been deleted yet.)

then about 30 min pass, this workflow run normal（maybe cache sync period meet?）**(no! this not happen every time, current workflow has stuck for 40 min......)**

any possible avoid this, 3Q

**Comment by ZhengJuCn** [comment]
maybe not first workflow's pod..

i check creationTimestamp of the exist pod, it more close to second

i found  more related log in workflow-controller:

**Workflow pod is missing "namespace=xx nodePhase=xx podName=xx"**

i search this in the argo-worflow code, found

https://github.com/argoproj/argo-workflows/blob/a105b137c97e5aea852c6db6e77997ca3713cb08/workflow/controller/operator.go: 1035

someone could explain why this happen and how to avoid this,  3q

**Comment by ZhengJuCn** [comment]
@sarabala1979 any possible to give some help, thank you~..

**Comment by sarabala1979** [comment]
@ZhengJuCn Can you provide your reproduction steps? If you delete workflow and create the same name simultaneously, the created workflow is stuck for the next sync period(20m).  Possible informer events will be overwritten with the latest event.
how busy is your cluster? you can increase the no of workflow work to pick all events immediately. So, Delete and create will be process. default `workflow-workers` is 32 workers.

**Comment by ZhengJuCn** [comment]
@sarabala1979 

**reproduction steps:**
1 . create workflow-A (entrypoint: steps -> steps: A-template (only one step) -> A-template: sleep 5 second then exit)
2.  wait worflow-A to be completed
3.  delete workflow-A then create workflow-A (same name & same spec, all same) (actually this time i wait get workflow-A return notfound & list all pods with label workflow-A with notfound then create workflow-A)
4.  then sometimes second workflow-A stuck (mosttime can normal run, sometimes stuck for 20-30 min, but most recent i met is stuck forever when get stuck)

i try to wait some time before create second workflow-A (15 seconds), then stuck happen  frequency decrease a lot
when i only wait 1-2 seconds then stuck happen more  frequency

**how busy is your cluster?**

cluster is for debug, actually not busy

**Comment by sarabala1979** [comment]
@ZhengJuCn It looks like your k8s API is taking a delay to send delete events for workflow. and missed the create event. That's why you are seeing this behavior. I tried my local with the above steps couldn't reproduce it. 
try it with different clusters or in local.

**Comment by tooptoop4** [comment]
@sarabala1979 is it safe to do 'kubectl delete events' every 20mins? or is argo controller/server relying on reading the events?
