### ISSUE TITLE
Error while using argo commands

### ISSUE THREAD

**Issue by wdma** [argoproj/argo-workflows#6528]
## Summary 

I have installed the latest Argo Workflows using the manifest found here:

https://github.com/argoproj/argo-workflows/releases/tag/v3.1.5

When I run the Hello World example, I am getting the following error:

FATA[2021-08-11T08:50:53.533Z] rpc error: code = NotFound desc = the server could not find the requested resource (get workflows.argoproj.io)

There is also the following non fatal error:

ERRO[2021-08-11T08:50:53.479Z] Create request failed: the server could not find the requested resource (post workflows.argoproj.io)
There is at least one other person that appears to be having a similar problem (https://github.com/hyfen-nl/PIVT/issues/109)

Here is the output of   argo version:

argo: v3.1.5
  BuildDate: 2021-08-04T07:03:32Z
  GitCommit: 3dbee0ec368f3ea8c31f49c8b1a4617cc32bcce9
  GitTreeState: clean
  GitTag: v3.1.5
  GoVersion: go1.15.7
  Compiler: gc
  Platform: linux/amd64

Before we start, around 2/3 of issues can be fixed by one of the following:

* Have you double-checked your configuration? Maybe 30% of issues are wrong configuration.
* Have you tested to see if it is fixed in the latest version? Maybe 20% of issues are fixed by this.
* Have you tried using the PNS executer instead of Docker? Maybe 50% of artifact related issues are fixed by this.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
Docker Desktop

What version of Argo Workflows are you running? 
3.1.5

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Docker

Did this work in a previous version? I.e. is it a regression?
Yes.

Are you pasting thousands of log lines? That's too much information. 

```bash
# Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:
kubectl get wf -o yaml ${workflow}

# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

This produces the non fatal error noted above.

---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@wdma It looks like CRD didn't get installed on your cluster. Have you applied below command on your cluster?
```
kubectl create namespace argo
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.1.5/install.yaml
```

**Comment by wdma** [comment]
Hm.  I thought i had....  

It worked! Thank you
