### ISSUE TITLE
Show workflow title/description in UI

### ISSUE THREAD

**Issue by atombender** [argoproj/argo-workflows#6529]
# Summary

Support showing a title and/or description for workflows in the UI, instead of the less readable `metadata.name`.

# Motivation

The `metadata.name` is an identiifer, not a title. It ends up being something like:

> test-someproject-pr-123-aff39ee

It would be much more readable if you could have something like:

> **Build and test**
> `SuperDuperProject` PR #6529: Implement frobbing (aff39ee)

Should be easy enough to read a standard annotation such as `workflows.argoproj.io/description` for this. It'd be nice to support Markdown here, for markup and linking.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by jmeridth** [comment]
I'd like to snag this one.  If I need a mentor I'll fill out a [mentor request](https://github.com/argoproj/argo-workflows/issues/new?assignees=&labels=mentoring%2Ctriage&template=mentoring_request.md)

**Comment by anil10032** [comment]
@jmeridth Please continue on this 👍 . I will take up something else!

**Comment by jmeridth** [comment]
Got things working.  Will be push up PR in next few days.

**Comment by jmeridth** [comment]
One last hurdle then will get the PR ready for this.
