### ISSUE TITLE
workflow-controller memory usage increases monotonically

### ISSUE THREAD

**Issue by tymokvo** [argoproj/argo-workflows#6532]
## Summary 

Opened by request of @sarabala1979 on slack [here](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1628702076319100?thread_ts=1628701743.317800&cid=C01QW9QSSSK).

What happened/what you expected to happen?

workflow-controller's memory usage increased monotonically for each submitted workflow. I expected its memory usage to free up some time after the workflow transitioned to a "finished" state.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 

GKE

What version of Argo Workflows are you running? 

3.1.0-rc14

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

Emissary

Did this work in a previous version? I.e. is it a regression?

Unknown

Are you pasting thousands of log lines? That's too much information. 

Yes, kind of, but I was asked to in this case.

The logs are 5.4MB, so I put them on GCS [here](https://storage.googleapis.com/pollination-public/blobs/argo-test/controller-logs_2021-08-11.txt).

The workflows in question completed at around 06:55 UTC

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
I can see log `Deleting TTL expired workflow` so I think TTL is working. Can you provide little more information about your environment? how busy is your cluster?  
Can you check your cluster whether already deleted workflow is still there?
`Deleting TTL expired workflow '793fb579-caf4-49d1-a7e6-f4bb1d246095/bf14d17b-a55f-50d3-8420-f6196563b19e'"`

**Comment by tymokvo** [comment]
The cluster is under pretty heavy load. This workflow `bf14d17b-a55f-50d3-8420-f6196563b19e` was one of 216 that a user submitted at once which created a total of 3493 nodes.

**Comment by sarabala1979** [comment]
@tymokvo it means TTL is deleting. Because of Big workflows and heavy load on new workflows controller informer size is growing. 
Can you try to reduce TTL time?

**Comment by tymokvo** [comment]
Yep, I will do that and follow up here. Thanks!

**Comment by alexec** [comment]
Memory usage should be less that 1GB in most use cases:

* How many workflows are you running.
* How many nodes per workflows on average?

Can we get a pprof dump please?

This is an example: https://github.com/argoproj/argo-workflows/blob/master/hack/capture-pprof.sh

**Comment by tymokvo** [comment]
We have seen it increase to ~10GB after running 215 workflows with a total of 55,492 nodes over the course of 8 hours at which point the node was OOM and killed the workflow-controller and a few of our other monitoring services.

I will get the pprof dump asap.

**Comment by tymokvo** [comment]
pprof output files [1](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-11/pprof.workflow-controller.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz), [2](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-11/pprof.workflow-controller.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz), and [3](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-11/pprof.workflow-controller.samples.cpu.001.pb.gz). (I don't know what these are :grimacing: )

**Comment by tymokvo** [comment]
For the same duration as the log file linked above `2021-08-10T06:50:00` to `2021-08-11T17:30:00` (~10.5hrs) we ran 452 workflows. These were started in groups of related workflows that we call "jobs"

Here's a table of how the load over time breaks down:

| job_id   | started_at          | finished_at         | workflow_count | nodes |
| -------- | ------------------- | ------------------- | -------------- | ----- |
| 9b0feb31 | 2021-08-10 07:10:08 | 2021-08-10 07:17:32 | 1              | 1102  |
| 07084fdd | 2021-08-10 07:20:05 | 2021-08-10 07:39:21 | 4              | 4408  |
| 27bfa22a | 2021-08-10 07:22:12 | 2021-08-10 07:25:39 | 1              | 71    |
| 8c7d1f83 | 2021-08-10 08:11:15 | 2021-08-10 08:13:41 | 1              | 122   |
| b50d9c33 | 2021-08-10 08:11:16 | 2021-08-10 08:14:05 | 1              | 122   |
| 64c3714e | 2021-08-10 08:11:17 | 2021-08-10 08:14:02 | 1              | 122   |
| c8d6a157 | 2021-08-10 08:30:24 | 2021-08-10 08:31:58 | 1              | 122   |
| 5f20fee0 | 2021-08-10 10:13:55 | 2021-08-10 10:27:48 | 1              | 2602  |
| 5bc52074 | 2021-08-10 11:54:06 | 2021-08-10 12:16:37 | 1              | 2602  |
| b5cd4ac1 | 2021-08-10 12:17:03 | 2021-08-10 12:23:20 | 1              | 202   |
| 3d92c52d | 2021-08-10 17:06:29 | 2021-08-10 17:13:20 | 1              | 485   |
| fd8391df | 2021-08-10 17:18:27 | 2021-08-10 17:24:30 | 1              | 468   |
| 88f43ad7 | 2021-08-10 17:18:35 | 2021-08-10 17:22:27 | 1              | 399   |
| db98f1a7 | 2021-08-10 17:20:18 | 2021-08-10 17:23:15 | 1              | 400   |
| 98a90a6e | 2021-08-10 18:13:43 | 2021-08-10 18:21:42 | 1              | 468   |
| a7db6e70 | 2021-08-10 18:13:53 | 2021-08-10 18:19:01 | 1              | 399   |
| 6776dea9 | 2021-08-10 18:14:04 | 2021-08-10 18:18:38 | 1              | 400   |
| b4309ad5 | 2021-08-11 06:37:28 | 2021-08-11 06:39:22 | 216            | 3493  |
| 25eecca4 | 2021-08-11 06:45:19 | 2021-08-11 06:55:13 | 216            | 4321  |

**Comment by alexec** [comment]
> pprof output files [1](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-11/pprof.workflow-controller.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz), [2](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-11/pprof.workflow-controller.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz), and [3](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-11/pprof.workflow-controller.samples.cpu.001.pb.gz). (I don't know what these are 😬 )

The heap dump is missing, and allows appears to be attached twice? It's the heap I want to see most.

**Comment by alexec** [comment]
It might be good to set-up 30m: https://bit.ly/book-30m-with-argo-team

**Comment by tymokvo** [comment]
Ok, I will try to find some time. I ran it again and captured the heap dump svg [here](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-11/pprof001.svg).

**Comment by alexec** [comment]
I though I'd jump in - but I didn't see anything out of the ordinary in the pprof dumps.

Can I ask you to review https://argoproj.github.io/argo-workflows/running-at-massive-scale/

Additionally, you didn't state if this is a regression or not, is this is a brand new installation?

**Comment by tymokvo** [comment]
It's hard to tell if it's a regression, it's the first time that we've experienced this specific issue. We weren't running this kind of load before upgrading to Argo 3 and we've been using 3.1.0-rc14 for a while now (though we had to fork and patch to mitigate #6276 )

Re: running at massive scale, we've implemented parallelism limits, and we're using the emissary executor, and the k8s cluster can handle the load (the good thing about the issue that we've been having is that the workflows have all been completing successfully). But, the memory consumption by workflow controller is starving all the other infrastructure services (fluentbit, prometheus, some custom eventing services, etc.)

I will look into implementing rate limiting and the reque time, though.

**Comment by alexec** [comment]
Try the re-queue setting, if that works great, if not - lets get on a call.

**Comment by alexec** [comment]
Code - you really should be running the latest version which will be v3.1.5 (or v3.1.6 if that is released today). If needs be, fork and re-apply your patch.

**Comment by tymokvo** [comment]
Ok, I'll start there.

**Comment by tymokvo** [comment]
One thing I forgot to mention: we are using per-user namespaces with resource limits to prevent users starving each other of CPU/memory. This and our resource allocation settings amount to each namespace being able to run ~66 pods simultaneously.

In order to test the suggested changes appropriately, I've been trying to replicate the memory consumption behavior on our test cluster and have gotten similar behavior by running jobs that create >200 workflows in two _different_ user namespaces simultaneously.

In the monitoring screenshot below, the spike in activity between 12:15 and 12:30 is in the same user namespace and the memory usage doesn't appear to increase. 

In the spike in activity between 12:40 and 12:55, the workflows are the same two as the previous spike, but in separate namespaces. Here, the memory consumption does seem to increase.

![workflow-controller-mem-increase](https://user-images.githubusercontent.com/12144028/129122766-81565e12-6e9a-4c45-be0f-b113d26c47e9.png)

pprof heap dump [1](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-11/pprof-staging-1628729701.svg), [2](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-11/pprof-staging-1628729695.svg), [3](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-11/pprof-staging-1628729407.svg).

workflow-controller [logs](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-11/workflow-controller-staging.txt).

**Comment by alexec** [comment]
Did you try the newer version? I'm not clear.

**Comment by tymokvo** [comment]
Yeah, sorry for the delay. We have been doing a lot of testing in addition to fixing our own systems. I just ran the latest test over night.

We've upgraded to 3.1.6, increased the requeue time to 30s, and reduced the TTL time to 1200 seconds for all finished states. We're still seeing memory consumption by the controller exceed 10GB for some of our workflows.

This is the memory consumption reported by GCP metrics for the one I ran last night:

![workflow-controller-post-changes](https://user-images.githubusercontent.com/12144028/130652891-347e3d6e-fe7c-4b1c-aac6-4476afa226ff.png)

**Comment by alexec** [comment]
>  We're still seeing memory consumption 

So generally reduced?

**Comment by tymokvo** [comment]
Yeah, initially it seemed to be resolved until I ran this test case again last night.

**Comment by alexec** [comment]
So we're making progress.

Can I request dumps when the memory usage is high again?

**Comment by tymokvo** [comment]
Sure thing, it's still over 10GB so I can do it now.

**Comment by tymokvo** [comment]
Dump [1](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-24/pprof-staging-1629823198.svg), [2](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-24/pprof-staging-1629823225.svg), [3](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-24/pprof-staging-1629823264.svg)

**Comment by tymokvo** [comment]
So this is the current kubectl top output:

```console
POD                                    NAME                  CPU(cores)   MEMORY(bytes)   
workflow-controller-7f7bd4cdc9-tf4qb   argo-dumpster         2m           127Mi           
workflow-controller-7f7bd4cdc9-tf4qb   workflow-controller   89m          7733Mi
```

Here's the pprof [allocs](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-24/allocs.pdf), [heap](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-24/heap.pdf), and [profile](https://storage.googleapis.com/pollination-public/blobs/argo-test/workflow-controller-pprof-2021-08-24/profile.pdf).

The `pprof` calls were taking so long over HTTP that `kubectl port-forward` kept timing out so I had to make a pod in the cluster to generate them. If anyone else needs an image to do this, I made one [here](https://hub.docker.com/repository/docker/tykom/go-pprof).

**Comment by alexec** [comment]
Hotspots

* util.MergeTo
* WorkflowSemaphoneKeyIndexFunc

**Comment by alexec** [comment]
Can you run you controller with INDEX_WORKFLOW_SEMAPHORE_KEYS=false? Note that this will disable semaphores.
