### ISSUE TITLE
Workflow install.yaml should switch from docker.io to quay.io

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-workflows#6537]
# Summary

Argo project install manifests should install from quay.io instead of docker.io due to the rate limiting enforced by docker.io. All other projects (CD, Rollouts, Events) install manifests have been updated to quay.io and Workflows is the last remaining.

# Use Cases

Install without rate limiting. The error users are getting is:

```
You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limits
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by wanghong230** [comment]
I will pick up this issue.

**Comment by wanghong230** [comment]
The helm chart has adopted quay.io. Great!
https://github.com/argoproj/argo-helm/blob/master/charts/argo-workflows/values.yaml

**Comment by sarabala1979** [comment]
I think images are pushing quay.io https://quay.io/repository/argoproj/workflow-controller?tab=tags
only we need to update the manifests (install.yaml(
