### ISSUE TITLE
`argoproj/argoexec:latest` sometimes only contains `linux/amd64`

### ISSUE THREAD

**Issue by omus** [argoproj/argo-workflows#6541]
## Summary 

Submitting any Argo workflow fails when running on an M1 Mac due to "argoproj/argoexec:latest" not including a linux/arm64 image.

The failures message from `kubectl describe`:
```
Failed to pull image "argoproj/argoexec:latest": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries
```

![Screen Shot 2021-08-13 at 11 25 01](https://user-images.githubusercontent.com/1675958/129390528-8b02d308-5f2d-47c1-8db5-8a4b0ac7897e.png)

## Diagnostics

What Kubernetes provider are you using? 

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/arm64"}
```

What version of Argo Workflows are you running? 

```
❯ argo version
argo: v3.1.3+9337abb.dirty
  BuildDate: 2021-07-28T08:20:43Z
  GitCommit: 9337abb002d3c505ca45c5fd2e25447acd80a108
  GitTreeState: dirty
  GitTag: v3.1.3
  GoVersion: go1.16.6
  Compiler: gc
  Platform: darwin/arm64
```

What executor are you running? Docker

Did this work in a previous version? I.e. is it a regression? Yes, worked yesterday on the same versions

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by omus** [comment]
I could work around this by specifying an alternate image such as "argoproj/argoexec:latest-linux-arm64" but I don't believe there is a way to change via `argo submit`.

**Comment by omus** [comment]
As of this moment the "latest" tag includes all of the expected OS/ARCH combos:
![Screen Shot 2021-08-13 at 11 35 44](https://user-images.githubusercontent.com/1675958/129391323-a3875091-27b4-4ec7-99ee-960389562023.png)
To me this points to there being a Docker build issue where "latest" is being updated too early resulting in runtime failures for those using linux/arm64 or windows/amd64.

**Comment by wanghong230** [comment]
Do you see the same problem with the released images? not latest, eg: v3.1.x image/

**Comment by omus** [comment]
I haven't noticed it myself personally. Based upon how `latest` behaved there's probably only a ~9 minute window where someone would notice this issue

**Comment by sarabala1979** [comment]
something in your node or pod configuration which doesn't match with the default image `Linux/arm64/v8`  I am not sure about `v8`.

**Comment by omus** [comment]
Just happened again:
![Screen Shot 2021-08-20 at 09 52 31](https://user-images.githubusercontent.com/1675958/130252225-84f3bc3e-f25a-403f-a1b4-8b0d301a7147.png)

**Comment by omus** [comment]
Looks like the "latest-windows" and "latest-linux-arm64" images have been updated "latest-linux-amd64" has not yet been updated:
![Screen Shot 2021-08-20 at 10 01 21](https://user-images.githubusercontent.com/1675958/130253748-6d0fa5ba-c258-49a8-b9a0-bb011c9da857.png)

And the "latest" manifest has been updated to include all architectures again:

![Screen Shot 2021-08-20 at 10 04 27](https://user-images.githubusercontent.com/1675958/130253874-b0bd30d8-96d2-42c9-aad5-3fd9411f2e62.png)

**Comment by sarabala1979** [comment]
@omus Is this issue resolved?

**Comment by omus** [comment]
> @omus Is this issue resolved?

No, the issue is not resolved. The problem is that Argo workflows break on ARM64 every time a new `latest` build is initially released.

Until the build system is updated to only push a `argoexec:latest` manifest once (which includes all supported platforms) the issue will keep occurring.

**Comment by alexec** [comment]
@omus this would need fixing here: 

https://github.com/argoproj/argo-workflows/blob/master/.github/workflows/release.yaml

Do you want to try and submit a PR?
