### ISSUE TITLE
GCS artifact saving as ZIP when archive is none

### ISSUE THREAD

**Issue by christophercutajar** [argoproj/argo-workflows#6553]
## Summary 

What happened/what you expected to happen?

I noticed that when configuring a GCS output artifact with `archive: none{}` as per below, while Argo Workflows logs highlights that an XLSX is being uploaded, GCP illustrates that the uploaded file is of type `applicaation/ZIP`. [uploadObject](https://github.com/argoproj/argo-workflows/blob/88520891a0376ec43760b317fbc4f453a00a8d3e/workflow/artifacts/gcs/gcs.go#L283) seems to be correct when comparing to [go sample doc from Google](https://cloud.google.com/storage/docs/samples/storage-upload-file#storage_upload_file-go).

Output Workflow:

```json
outputs:
    artifacts:
    - name: excel-workbook
        path: '/src/Test 1.xlsx'
        archive:
            none: {}
      gcs:
        bucket: test-bucket
        key: 'Test 1.xlsx'
```

Logs highlighting XLSX file upload to GCS:

```
time="2021-08-13T13:21:46.499Z" level=info msg="Staging artifact: excel-workbook"
time="2021-08-13T13:21:46.499Z" level=info msg="Staging /src/Test 1.xlsx from mirrored volume mount /mainctrfs/src/Test 1.xlsx"
time="2021-08-13T13:21:46.499Z" level=info msg="No compression strategy needed. Staging skipped"
time="2021-08-13T13:21:46.499Z" level=info msg="GCS Save path: /mainctrfs/src/Test 1.xlsx, key: Test 1.xlsx"
time="2021-08-13T13:21:47.521Z" level=info msg="Successfully saved file: /mainctrfs/src/Test 1.xlsx"
time="2021-08-13T13:21:47.521Z" level=info msg="Annotating pod with output"
time="2021-08-13T13:21:47.543Z" level=info msg="Killing sidecars"
time="2021-08-13T13:21:47.560Z" level=info msg="Alloc=30284 TotalAlloc=40328 Sys=70080 NumGC=6 Goroutines=12"
```

GCS UI:

![image](https://user-images.githubusercontent.com/60098546/129738563-54a6803b-a7c9-4da4-9acd-4d44f6036563.png)

When I upload the XLSX manually to GCS it's of type `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`

![image](https://user-images.githubusercontent.com/60098546/129738501-cfef1314-df16-427d-a490-1dcde0f4ae32.png)

Discussion slack thread: https://cloud-native.slack.com/archives/C01QW9QSSSK/p1628860355404000

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? Google Cloud - GKE

What version of Argo Workflows are you running? v2.12.5

What executor are you running? Docker

Did this work in a previous version? I.e. is it a regression? There is not evidence that this was working in the previous version or it's working in the newer versions.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
I think it might be related to the name of your file `'/src/Test 1.xlsx'`. Could you try removing the space in the file name? `application/zip` looks like a Windows zip, which might be caused by the space in the file name.

**Comment by christophercutajar** [comment]
A few minutes ago tested it using `Argo Workflow v3.1.5` having

```yaml
outputs:
  artifacts:
  - name: excel-workbook
    path: /src/Test1.xlsx
    archive:
      none: {}
    gcs:
      bucket: test-bucket
      key: Test1.xlsx
```

Logs from pod:

```bash
time="2021-08-17T15:56:52.326Z" level=info msg="Main container completed"
time="2021-08-17T15:56:52.326Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2021-08-17T15:56:52.326Z" level=info msg="No output parameters"
time="2021-08-17T15:56:52.326Z" level=info msg="Saving output artifacts"
time="2021-08-17T15:56:52.326Z" level=info msg="Staging artifact: Test1"
time="2021-08-17T15:56:52.326Z" level=info msg="Staging /src/Test1.xlsx from mirrored volume mount /mainctrfs/src/Test1.xlsx"
time="2021-08-17T15:56:52.326Z" level=info msg="No compression strategy needed. Staging skipped"
time="2021-08-17T15:56:52.326Z" level=info msg="GCS Save path: /mainctrfs/src/Test1.xlsx, key: Test1.xlsx"
time="2021-08-17T15:56:52.570Z" level=info msg="not deleting local artifact" localArtPath=/mainctrfs/src/Test1.xlsx
time="2021-08-17T15:56:52.570Z" level=info msg="Successfully saved file: /mainctrfs/src/Test1.xlsx"
time="2021-08-17T15:56:52.657Z" level=info msg="Annotating pod with output"
time="2021-08-17T15:56:52.674Z" level=info msg="Patch pods 200"
```

This uploaded XSLX still remained with type `application/zip`.

**Comment by sarabala1979** [comment]
@christophercutajar @terrytangyuan  Is there any file header/type that needs to send before uploading the file to the GCS client?

**Comment by terrytangyuan** [comment]
Looks like GCS client's `NewWriter()` uses `net/http.DetectContentType` to detect content type automatically if it's not specified. In this case the type might be detected incorrectly so we may want to pass it explicitly.

**Comment by christophercutajar** [comment]
Reading the [NewWriter docs](https://pkg.go.dev/cloud.google.com/go/storage#ObjectHandle.NewWriter) in more detail, as correctly highlighted by @terrytangyuan, if no `ContentType` attribute is specified, the content type will be automatically sniffed using `net/http.DetectContentType`.

My first thought would be to have an optional parameter say `fileType` that would set the `ContentType`. If this is not set, Argo would rely on GCS client which is leveraging `net/http.DetectContentType`.

The below is a sample of my thought:

```yaml
outputs:
  artifacts:
  - name: excel-workbook
    path: /src/Test1.xlsx
    fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    archive:
      none: {}
    gcs:
      bucket: test-bucket
      key: Test1.xlsx

```

```go
// upload an object to GCS
func uploadObject(client *storage.Client, bucket, key, localPath string, fileType string) error {
	f, err := os.Open(filepath.Clean(localPath))
	if err != nil {
		return fmt.Errorf("os open: %v", err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			log.Fatalf("Error closing file[%s]: %v", localPath, err)
		}
	}()
	ctx := context.Background()
	wc := client.Bucket(bucket).Object(key).NewWriter(ctx)
	
    if fileType != nil {
    	wc.ContentType := fileType
	}

	if _, err = io.Copy(wc, f); err != nil {
		return fmt.Errorf("io copy: %v", err)
	}
	if err := wc.Close(); err != nil {
		return fmt.Errorf("writer close: %v", err)
	}
	return nil
}
```
