### ISSUE TITLE
argoexec image building fails with /bin/sh/setcap: not found

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#6556]
## Summary 

Example failed CI build: https://github.com/argoproj/argo-workflows/runs/3352788744?check_suite_focus=true

```
#30 [argoexec-build 4/4] RUN setcap CAP_SYS_PTRACE,CAP_SYS_CHROOT+ei dist/argoexec
#30 0.362 /bin/sh: 1: setcap: not found
#30 ERROR: executor failed running [/bin/sh -c setcap CAP_SYS_PTRACE,CAP_SYS_CHROOT+ei dist/argoexec]: exit code: 127
------
 > [argoexec-build 4/4] RUN setcap CAP_SYS_PTRACE,CAP_SYS_CHROOT+ei dist/argoexec:
#30 0.362 /bin/sh: 1: setcap: not found
------
error: failed to solve: executor failed running [/bin/sh -c setcap CAP_SYS_PTRACE,CAP_SYS_CHROOT+ei dist/argoexec]: exit code: 127
make: *** [Makefile:226: argoexec-image] Error 1
Error: Process completed with exit code 2.
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This passes from a fresh build locally...?

**Comment by terrytangyuan** [comment]
Local builds have the same issue.

**Comment by alexec** [comment]
https://pkgs.alpinelinux.org/contents?branch=edge&name=libcap&arch=x86&repo=main

installing `libcap` should install `setcap` - can you build without cache?

**Comment by terrytangyuan** [comment]
no-cache didn't work either. It seems like we need to install `libcap2-bin`. Sending fix in https://github.com/argoproj/argo-workflows/pull/6559.
