### ISSUE TITLE
Cannot get the install manifest from v2.12.12

### ISSUE THREAD

**Issue by ado120** [argoproj/argo-workflows#6564]
I am getting a 404 error when going to this link.. is anyone getting the same issue?

https://raw.githubusercontent.com/argoproj/argo/v2.12.12/manifests/install.yaml

**Comment by alexec** [comment]
This is not the place to get this for v2.12.2. Let me find the right place...

**Comment by alexec** [comment]
https://raw.githubusercontent.com/argoproj/argo-workflows/v2.12.12/manifests/install.yaml

**Comment by ado120** [comment]
@alexec 

Thanks! If you look in the latest releases section this is the link posted there. Also I was unable to curl and gunzip the argo cli tool, you might have a typo in the releases section..
