### ISSUE TITLE
Mount a volume in kubernetes resource

### ISSUE THREAD

**Issue by gpsingh-1991** [argoproj/argo-workflows#6586]
# Summary 

Unable to launch the containers launching kubernetes resource because of PSP.

When we try to create a kubernetes volume in a template with PSP enabled. It fails complaining the root FS is read only. It would be great if we could mount an empty dir on the /tmp so that we can get pass this error.

# Use Cases

When we try and create a kubernetes resource with default PSP.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This is a duplicate. Not sure of the issue number I'm afraid.
