### ISSUE TITLE
Argo Server's Prometheus metrics exposed without auth

### ISSUE THREAD

**Issue by sebnyberg** [argoproj/argo-workflows#6592]
Unlike the rest of the web server (which is conditionally protected by auth), the argo server's prometheus metrics are available without auth on `/metrics`.

This potentially leads to unnecessary exposure of internal information about the application.

I'll leave the solution open for discussion.

**Comment by alexec** [comment]
@sarabala1979 we should fix this:

1. Move Prometheus metrics to a new port.
2. Add authentication to metrics.
