### ISSUE TITLE
cannot make inputs artifacts optional

### ISSUE THREAD

**Issue by philosophicus** [argoproj/argo-workflows#6598]
## Summary 

The workflow in [test/e2e/testdata/input-artifacts.yaml](https://github.com/argoproj/argo-workflows/blob/4e450e250168e6b4d51a126b784e90b11a0162bc/test/e2e/testdata/input-artifacts.yaml) fails like this
<img width="975" alt="Screen Shot 2021-08-25 at 3 26 40 PM" src="https://user-images.githubusercontent.com/9477891/130746105-43de7650-c359-4267-b8b1-1febc0a23736.png">

We're using argo v3.1.6

Init container logs are like this:
> time="2021-08-25T06:52:45.318Z" level=info msg="Start loading input artifacts..."
time="2021-08-25T06:52:45.318Z" level=info msg="Downloading artifact: my-http-artifact"
time="2021-08-25T06:52:45.318Z" level=info msg="curl -fsS -L -o /argo/inputs/artifacts/my-http-artifact.tmp https://github.com/argop
roj/argo-workflows/not-found"
time="2021-08-25T06:54:46.808Z" level=info msg="curl: (52) Empty reply from server\n"
time="2021-08-25T06:54:46.808Z" level=error error="exit status 52"
time="2021-08-25T06:54:46.808Z" level=error msg="executor error: artifact my-http-artifact failed to load: exit status 52"
time="2021-08-25T06:54:46.809Z" level=info msg="Alloc=4874 TotalAlloc=9829 Sys=74577 NumGC=4 Goroutines=3"
time="2021-08-25T06:54:46.849Z" level=fatal msg="artifact my-http-artifact failed to load: exit status 52"

We're trying to pass caches to templates as optional artifacts, so templates won't fail when certain caches don't exist. However, the `optional` field is not working as expected. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by philosophicus** [comment]
https://github.com/argoproj/argo-workflows/blob/4e450e250168e6b4d51a126b784e90b11a0162bc/workflow/artifacts/hdfs/hdfs.go#L145

Take this for example. If the file doesn't exist on hdfs, `hdfscli.Stat` won't succeed. However, a specific error which is not `CodeNotFound` is returned, even when `optional` is specified.

**Comment by alexec** [comment]
This looks like HDFS only. Would you like to submit a fix to do the error mapping?
