### ISSUE TITLE
throttler broken on workflow-controller restart 

### ISSUE THREAD

**Issue by smile-luobin** [argoproj/argo-workflows#6599]
## Summary 

What happened/what you expected to happen?

In our cluster, we set the workflow parallelism as 80, and submit 1000 workflows to argo-workflow at the same time; 
of course there are only 79 workflows (<parallelism) at running phase, and others are pending.
But then the pod of workflow-controller is restarted, there are 158 workflows at running phase.

For example:
Submit 1000 workflows: 
- workflows: [1, 2, ..., 79, 80, ...., 1000]
- running workflows: [1, 2, .., 79], 
- pending workflows: [80, ..., 1000];

Restart workflow-controller:
- waitCacheSynced, list-workflow: [80, ..., 1000, 1, 2, ..., 79];
- add CacheKeys to throttler: [80, ..., 158]; 
- processNextItem will process these workflows in throttler: [80, ..., 158];
- running workflows: [1, 2, ..., 79, 80, ..., 158];

As workflow-controller restarted: the controller will list-watch workflows. During waiting all workflows cache synced, list-watch will list all workflows in cluster, these workflows will be added into cache store, and cacheKey added into throttler. But the list-watch list all workflows ordered by latest resourceVersion (maybe). And these workflows already at running phase are sorted after these pending workflows.  The throttler will add these pending workflows cacheKeys at first, and workflow-controller will process these pending workflows at first. 

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
1.9.0

What version of Argo Workflows are you running? 
v3.1.3

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
k8sapi

**Comment by sarabala1979** [comment]
Workflow controller queue up the workflows based on k8s informer event. The controller has a phase indexer https://github.com/argoproj/argo-workflows/blob/530c21d3cc0f5c738d06e16d88b7ce63dbeeb64e/workflow/controller/controller.go#L186
are you using 1.9.0 Kubernetes version?
If the metaWorkflowPhaseIndexer is not correct,  we need to fix it.
https://github.com/argoproj/argo-workflows/blob/530c21d3cc0f5c738d06e16d88b7ce63dbeeb64e/workflow/controller/indexes/labels.go#L15
@jessesuen Please comment. on this.

**Comment by sarabala1979** [comment]
As long as, the controller re-sync the workflow with phase. order `Running` first and `Pending` after this issue will fix it. I think this is the way it should work now.

**Comment by sarabala1979** [comment]
@smile-luobin Can you provide impact and how frequently the controller gets restarted(reason)?  looks like it edge case scenario. This information will help us to prioritize the issue.
