### ISSUE TITLE
Workflow restrictions for cron workflows

### ISSUE THREAD

**Issue by droctothorpe** [argoproj/argo-workflows#6640]
# Summary
Apply workflow restrictions to cron workflows.

What change needs making?
Presumably adding some validation logic to the cron workflow controller code. Hopefully, it can mirror whatever is available in the workflow operator. 

I would be happy to tackle this work if it seems like a reasonable proposal. 

# Use Cases
I want to be able restrict what templates are available to cron workflows via template refs. 

When would you use this?
Any time I wanted workflow restrictions to encompass both workflows and cron workflows. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by droctothorpe** [comment]
I'm going to close this until I validate whether or not workflow restrictions are imposed on the workflows that a cron workflow generates. If so, this issue is basically moot.

**Comment by sarabala1979** [comment]
Do you want to cronworkflow’s workflowspec need to validate the restriction mode during cronworkflow creation time if restriction enabled in controller?

Currently workflow restriction mode will be validated once cronworkflow generated workflow.

**Comment by droctothorpe** [comment]
The former is kind of what I had in mind. It would prevent the creation of CronWorkflows whose workflows will fail due to them not meeting the workflow restrictions.
