### ISSUE TITLE
Archive logs in workflow level with default artifact repository

### ISSUE THREAD

**Issue by nmyalik** [argoproj/argo-workflows#6663]
# Summary

Have ability to enable archive logs in workflow level with default artifact repository

# Use Cases

Have default artifact repo and want to log only selected workflows without overriding archive repo for each. Want to set `archiveLogs: false` in config map and set it to true in workflow level

# Current behavior 
If we will set `archiveLogs: false` in config map and use 
```
archiveLocation:
        archiveLogs: true
```
in workflow level we have an error 
`Error (exit code 1): key unsupported: cannot get key for artifact location, because it is invalid`. Looks like there is required filed under `s3` property named `key`, but redefinition for artifact repo for each workflow look like bad idea.

Argo Workflows version: 3.0.7
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by rwong2888** [comment]
I am interested in having the inverse where artifactRepository.archiveLogs and persistence.archive enabled by default and having some workflows be able to disable individually.

**Comment by tczhao** [comment]
There's https://github.com/argoproj/argo-workflows/blob/master/examples/archive-location.yaml
allow you to set archive at individual step (did a test, doesn't seem working... will investigate on this)

It doesn't seem there's a parameter to configure archive log at the workflow level
I think this is a good feature to have
and we will have the archive config priority: template > workflow > configmap

**Comment by rwong2888** [comment]
@tczhao is there similar for `persistence.archive`?

**Comment by alexec** [comment]
IMHO it is better to use a logging facility like Splunk for keeping logs in. Searchable and indexable. You're welcome to submit a PR of course.
