### ISSUE TITLE
UI for supplied values

### ISSUE THREAD

**Issue by keshamin** [argoproj/argo-workflows#6665]
# Summary

Provide functionality to set supplied values via Web UI. Currently it can be set with Argo CLI, REST or k8s API ([docs](https://argoproj.github.io/argo-workflows/fields/#suppliedvaluefrom)), but it is not friendly for non-technical users like managers/business analysts/etc... 

# Use Cases

Supplied values allows to bring additional parametrization right in the middle of DAG execution, but if I have to go to CLI to use it it is not very useful.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by basanthjenuhb** [comment]
This should be available in next release
https://argoproj.github.io/argo-workflows/intermediate-inputs/

**Comment by agilgur5** [comment]
Fixed in #8472
