### ISSUE TITLE
Independent suspension nodes

### ISSUE THREAD

**Issue by keshamin** [argoproj/argo-workflows#6666]
# Summary

Currently if 2 independent branches of a DAG pause execution because of `SuspendTemplate` node it is not possible to resume only one branch. Clicking "Resume" leads to resuming both branches. I understand that apparently as for now "suspended" state is global for the whole workflow, and it is expected behavior. But it is highly desired feature to allow independent resuming of suspension nodes.

![Peek 2021-09-03 14-06](https://user-images.githubusercontent.com/25623173/131995978-42de130a-0cfc-4d5a-8e02-23e1e6baeed1.gif)

# Use Cases

I use suspension nodes for operator to manually approve some further actions. If a DAG has 2 independent branches with different actions I want to approve them independently. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by daniel-winter** [comment]
Yes, we would also prefer to see this feature in action. I also have the same use case where it would be cool to have independent resuming of suspension nodes.
