### ISSUE TITLE
Release page download notes use incorrect URLs

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-workflows#6671]
https://github.com/argoproj/argo-workflows/releases/tag/v3.1.8

The release page still has `/argo/` instead of `/argo-workflows`.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by reinvantveer** [comment]
:+1:

**Comment by reinvantveer** [comment]
Additionally, it would be good to `curl -fsSLO` to fail early instead of storing a 404 response
