### ISSUE TITLE
State store across k8s clusters?

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#6687]
Every 3 months I have to teardown my k8s cluster and create new one. Is there anyway the argo UI can show me the workflow history from 4 months ago?

**Comment by sarabala1979** [comment]
@tooptoop4 you can enable the archive feature to store the completed workflow in secondary storage DB.
https://github.com/argoproj/argo-workflows/blob/master/docs/workflow-archive.md
