### ISSUE TITLE
set stdout=true when kill sidecars

### ISSUE THREAD

**Issue by henrywangx** [argoproj/argo-workflows#6693]
## Summary 

We face Timeout error when argoexec trying to kill the sidecar.
Our executor is K8SAPI.

## RootCause
With @kubeway's help, we found https://github.com/argoproj/argo-workflows/blob/master/workflow/executor/k8sapi/client.go#L101 didn't set `stdout=true` when call `ExecPodContainer`.
```go
func (c *k8sAPIClient) KillContainer(pod *corev1.Pod, container *corev1.ContainerStatus, sig syscall.Signal) error {
	command := []string{"/bin/sh", "-c", fmt.Sprintf("kill -%d 1", sig)}
	exec, err := common.ExecPodContainer(c.config, c.namespace, c.podName, container.Name, false, true, command...)
	if err != nil {
		return err
	}
	_, _, err = common.GetExecutorOutput(exec)
	return err
}
```
But GetExecutorOutput https://github.com/argoproj/argo-workflows/blob/620cb414a7797b67a2d34d55c3b6258b3c86aca4/workflow/common/util.go#L100 trying to receive the message from stdout. So the `exec.Stream` goroutine is blocked until timeout occurs. 

## Workaround
set `stdout=true` in https://github.com/argoproj/argo-workflows/blob/master/workflow/executor/k8sapi/client.go#L101 and build a private argoexec image.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@hanrywangx would you like to submit the PR for this fix?

**Comment by henrywangx** [comment]
> @hanrywangx would you like to submit the PR for this fix?

@sarabala1979 ok，I'm learning to give a PR for this fix
