### ISSUE TITLE
Dedicated state for suspended workflows

### ISSUE THREAD

**Issue by keshamin** [argoproj/argo-workflows#6710]
# Summary

I use `SuspendTemplate` for cases when human approve is required to pass on for further actions. But these further actions are not needed for all the suspended workflows eventually. So non-approved Workflows stay on suspend step infinitely and are displayed as Running. It misleads because they're not actually running and never will.

I suggest to introduce new Workflow state that would indicate such state. Like "Paused" or "Suspended". 
As a reference of such behavior I think of GitLab CI with its "manual" steps. 

![image](https://user-images.githubusercontent.com/25623173/132985478-476cd285-3f13-4650-9376-31d93ad3564b.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I get this issue, but I don't think we can ever fix it due to the number of users that depend on it.
