### ISSUE TITLE
Fail to get events and logs by HTTP API, because of the client.

### ISSUE THREAD

**Issue by neWs1587** [argoproj/argo-workflows#6733]
`
func (h Facade) EventStreamReader(in interface{}, path string) (*bufio.Reader, error) {
	method := "GET"
	u, err := h.url(method, path, in)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "text/event-stream")
	req.Header.Set("Authorization", h.authorization)
	log.Debugf("curl -H 'Accept: text/event-stream' -H 'Authorization: ******' '%v'", u)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	err = errFromResponse(resp)
	if err != nil {
		return nil, err
	}
	return bufio.NewReader(resp.Body), nil
}
`

As you can see,  EventStreamReader uses DefaultClient, while others uses client like the one below
`
client := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: h.insecureSkipVerify,
			},
		},
	}
`

As a result, when I attempt to get the Workflow Event or workflow Logs by https with InsecureSkipVerify, it comes with an error, "x509: certificate signed by unknown authority".

**Comment by alexec** [comment]
Here is where the code change needs to be made:

https://github.com/argoproj/argo-workflows/blob/master/pkg/apiclient/http1/facade.go#L55

Would you be interested in submitting a PR to fix?
