### ISSUE TITLE
s3 event example

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#6736]
I am looking for an example template to do the following:

Whenever an object/file lands on an s3 bucket then auto start an argo workflow which runs this command: python3 myscript.py <new_s3_object_path>

**Comment by sarabala1979** [comment]
To Achieve this use case, you have to use the Argo Event and Argo Workflow. Argo Event will monitor the SNS for S3 events and trigger the workflow. https://github.com/argoproj/argo-events/blob/master/examples/event-sources/minio.yaml
