### ISSUE TITLE
where is the "argo/staging/script" suffix coming from?

### ISSUE THREAD

**Issue by wdma** [argoproj/argo-workflows#6744]
## Summary 

What happened/what you expected to happen?
I have modified the example found here (https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/memoize-simple.yaml) for my system and am expecting the whalesay output "test-5" but am getting "test-5 /argo/staging/script" like this:

 _____________________________
< test-5 /argo/staging/script >
 -----------------------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/

Before we start, around 2/3 of issues can be fixed by one of the following:

* Have you double-checked your configuration? Maybe 30% of issues are wrong configuration.
* Have you tested to see if it is fixed in the latest version? Maybe 20% of issues are fixed by this.
* Have you tried using the PNS executer instead of Docker? Maybe 50% of artifact related issues are fixed by this.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
Calico Bare metal installation
What version of Argo Workflows are you running? 
Argo 3.0.10
What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Emmisary
Did this work in a previous version? I.e. is it a regression?
The example works as is.
Are you pasting thousands of log lines? That's too much information. 
Here is my yaml:

{
   "apiVersion": "argoproj.io/v1alpha1",
   "kind": "Workflow",
   "metadata": {
      "annotations": {
         "argo": "workflows"
      },
      "generateName": "memoized-simple-workflow--",
      "labels": {
         "workflows.argoproj.io/archive-strategy": "false"
      },
      "namespace": "argo"
   },
   "spec": {
      "arguments": {
         "parameters": [
            {
               "name": "message",
               "value": "test-5"
            }
         ]
      },
      "entrypoint": "entrypoint",
      "parallelism": 3,
      "podGC": {
         "strategy": "OnWorkflowSuccess"
      },
      "securityContext": {
         "fsGroup": 2000,
         "runAsGroup": 3000,
         "runAsNonRoot": true,
         "runAsUser": 1000
      },
      "serviceAccountName": "argouser",
      "templates": [
         {
            "inputs": {
               "parameters": [
                  {
                     "name": "message"
                  }
               ]
            },
            "name": "entrypoint",
            "outputs": {
               "parameters": [
                  {
                     "name": "hello",
                     "valueFrom": {
                        "path": "/tmp/hello_world.txt"
                     }
                  }
               ]
            },
            "script": {
               "args": [
                  "{{inputs.parameters.message}}"
               ],
               "command": [
                  "cowsay"
               ],
               "image": "docker/whalesay:latest",
               "source": "{{args}} > /tmp/hello_world.txt"
            }
         }
      ],
      "ttlStrategy": {
         "secondsAfterSuccess": 5
      }
   }
}

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@wdma I am seeing only `test-5` in my env. Can you try the v3.1.11?

**Comment by wdma** [comment]
@sarabala1979 thank you for your reply. I am getting the same result as before. I have updated test-5 to test-6 as a reality check, but everything else stays the same.

```
argo: v3.1.11
  BuildDate: 2021-09-14T07:27:28Z
  GitCommit: 665c08d2906f1bb15fdd8c2f21e6877923e0394b
  GitTreeState: clean
  GitTag: v3.1.11
  GoVersion: go1.15.7
  Compiler: gc
  Platform: linux/amd64
```

and the output
```
 _____________________________
< test-6 /argo/staging/script >
 -----------------------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```

**Comment by sarabala1979** [comment]
@wdma Is it CLI version or controller version?

**Comment by wdma** [comment]
@sarabala1979 , I used the installation instructions (Linux) found here:

https://github.com/argoproj/argo-workflows/releases/tag/v3.1.11

 and am interacting with Argo on the command line.

**Comment by sarabala1979** [comment]
@wdma Can you try just argo submit [hello-world.yaml](https://github.intuit.com/kubernetes/cluster-deployments/pull/844)?

**Comment by wdma** [comment]
I am getting an error with that link(?)

![image](https://user-images.githubusercontent.com/8416524/133647630-7dd77a97-d391-4901-b731-b77695e72c41.png)

**Comment by wdma** [comment]
This is the output from argo submit...

FATA[2021-09-16T16:13:42.633Z] Get "https://github.intuit.com/kubernetes/cluster-deployments/pull/844": dial tcp: lookup github.intuit.com on 127.0.0.53:53: no such host

**Comment by terrytangyuan** [comment]
Try this link instead: https://github.com/argoproj/argo-workflows/blob/master/examples/hello-world.yaml

**Comment by wdma** [comment]
It works! (BTW, I had to use https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/hello-world.yaml)

 _____________
< hello world >
 -------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/

**Comment by wdma** [comment]
I think I found it.  removing the part of the command that saves the output ("> /tmp/hello_world.txt") produces the correct output in the logs..  I have to do some more checking to see if the output can be passed correctly, but it is something(!)

**Comment by wdma** [comment]
Closing this issue and starting another one because now I have killed argo(?)
