### ISSUE TITLE
hello-world job is stuck when running in microk8s 1.22/stable using docker executor

### ISSUE THREAD

**Issue by junjie-landing** [argoproj/argo-workflows#6752]
## Summary 

Try to run hello-world job
```
▶ argo submit --watch -n argo https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/hello-world.yaml
```
Then it stucks forever, even after hello world job is already completed. 

```
Name:                hello-world-2fnzw
Namespace:           argo
ServiceAccount:      default
Status:              Running
Conditions:
 PodRunning          True
Created:             Fri Sep 17 06:38:46 +0000 (5 minutes ago)
Started:             Fri Sep 17 06:38:46 +0000 (5 minutes ago)
Duration:            5 minutes 24 seconds
Progress:            0/1
```

![image](https://user-images.githubusercontent.com/81201171/133737217-5ea37112-5260-401b-ac43-51e996263c0b.png)

However, after switching to pns, it works fine.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 

```
sudo snap install microk8s --classic --channel=1.22/stable
```

What version of Argo Workflows are you running? 

`v3.1.12`. Here is the installation spec: https://gist.github.com/junjie-landing/0281b939eb33301d78f12e08fbd575c1

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

`Docker`

Did this work in a previous version? I.e. is it a regression?
It was not working in `3.0.10` neither.

It is working well in minikube v1.22.0 tho.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Could you run a kubectl describe on your workflow pod and controller pod? Any logs would be useful as well.
