### ISSUE TITLE
Upgrade coreos/go-oidc to v3 to enable OIDC-Connect issuerverifyskip check

### ISSUE THREAD

**Issue by liafizan** [argoproj/argo-workflows#6759]
# Summary

coreos/go-oidc has [v3](https://pkg.go.dev/github.com/coreos/go-oidc/v3) available which has also a fix for [issuer-mismatch   ](https://github.com/coreos/go-oidc/issues/250)

# Use Cases

This issuer mismatch becomes a problem with some OIDC providers when the discovery-url and issuer name differ. In this scenario, we get the error below:

`issuer did not match the issuer returned by provider, expected "xxx" got "yyy"`

With the fix in v3 we will be able to overcome this restriction and continue using Argo SSO 

#### Note: v2 -> v3 has two breaking changes and one of that impacts Argo. Move `github.com/coreos/go-oidc` to `github.com/coreos/go-oidc/v3/oidc` 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Would you like to submit a PR to fix this?

**Comment by stsully** [comment]
Hi guys
I would like to take a look at this
