### ISSUE TITLE
Replace docker.io with quay.io to avoid the image pull limit in namespace-install.yaml (and others?)

### ISSUE THREAD

**Issue by gdubya** [argoproj/argo-workflows#6770]
# Summary

#6539 Started work to replace the use of docker.io with quay.io, however we recently noticed the same issue in the latest version of Workflows, specifically when trying to fetch the "executor-image" for a series of steps in a workflow. 

This task is to update the namespace-install.yaml (and other yamls?) to use the quay.io image.

Furthermore consider adding imagePullPolicy (e.g. "IfNotPresent") to avoid unnecessary downloads. Note that this would also require version pinning, instead of specifying "latest" in the YAML. This is probably a good idea anyway, but perhaps should be split as a separate task?

**Comment by alexec** [comment]
Would you like to submit a PR to fix this?

**Comment by gdubya** [comment]
Sure, I can edit the files, but there's a comment at the top that says they are generated. What's the process for generating them?

**Comment by gdubya** [comment]
oh ffs. I was looking at an old branch. Master is indeed updated. Sorry.
