### ISSUE TITLE
Utilize k3s for e2e testing

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo-workflows#678]
**Is this a BUG REPORT or FEATURE REQUEST?**:
More like a FEATURE REQUEST.

**What happened**:
Current e2e tests don't run all existing examples.

**What you expected to happen**:
It should be possible to run all existing examples as an e2e test.

There is a make target right now that runs unit tests. It'll be good have a make target, say `make e2e-test` that runs the above.

**Comment by jessesuen** [comment]
We now have a `test/e2e/functional` directory containing symlinks to the example yamls which can be run as functional tests. Remaining piece is to invoke this in an automated fashion.

**Comment by jessesuen** [comment]
Updating the issue to use something like k3s to automate e2e testing of workflows.
