### ISSUE TITLE
Argo site SEO improvements

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-workflows#68]
Argo site pages title and description should be updated according to following table:

  |   |   |   |  
-- | -- | -- | -- | --
  |   |   |   |  
  | URL | title (60 char) | description (100-120 char) | URL keywords ?
  |   |   |   |  
  |   |   |   |  
Home | https://argoproj.github.io/argo-site/#/ | Argo \| Open source container-native workflow engine for Kubernetes | Argo is an open source container-native workflow engine for developers working with Kubernetes to orchestrate pipelines and jobs for continuous integration, deployment, and microservices. | n/a
  |   |   |   |  
Get Started | https://argoproj.github.io/argo-site/#/get-started/overview | Argo \| Get started with tutorials, training on workflows for Kubernetes | Get started with an overvirew of Argo, an open source workflow engine for Kubernetes. Step through  Installation, Architecture, Features and Tutorials. | looks good as is (leaf pages have keywords such as 'overview'  'get started' and 'tutorials' in Url
  |   |   |   |  
Docs | https://argoproj.github.io/argo-site/#/docs | Argo \| Documentation for open source workflow engine on Kubernetes | Documentation for Argo, open source workflow engine for Kubernetes.  Tutorials, User guide, CLI reference, FAQs, release notes. |  
  |   |   |   |  
  |   | EACH LEAFLET PAGE (or component page) OF DOCS NEEDS UNIQUE <TITLE> <DESCRIPTION> |   |  
  |   |   |   |  
  |   |   |   |  
Community | https://argoproj.github.io/argo-site/#/community/overview | Argo \| Community support, forums, release notes | Discuss and contribute to Argo, an open source workflow engine for Kubernetes.  GitHub, Slack and Google groups. | looks good as is - has community in the URL
  |   |   |   |  
Install | https://argoproj.github.io/argo-site/#/get-started/installation | Argo \| Install open source workflow engine for Kubernetes on AWS | install Argo, an open source engine for Kubernetes,  on AWS with CLI commands for Mac and Linux. | looks good as is.

**Comment by mukulikak** [comment]
[Argo SEO fields .xlsx](https://github.com/argoproj/argo/files/1271043/Argo.SEO.fields.xlsx)

Alex, adding title and description for docs starting row 27.

For the pages above row 27, have changed the titles. Moved Argo to the end instead of beginning acc to best practice.

**Comment by alexmt** [comment]
Done

**Comment by cyee88** [comment]
Added descriptions for title, description, path, and summary fields with this commit:  

Added final SEO changes for title/description fields in structure.json file; minor corrections to markdown files
Commit:
d8a232f006996ba01627155b7b2e5d3eaa6b0586 [d8a232f]
Parents:
83925cf2fd
Author:
Calvin Yee <calvin@applatix.com>
Date:
September 14, 2017 at 8:26:44 PM PDT
