### ISSUE TITLE
`generateName` with customized suffix length

### ISSUE THREAD

**Issue by treeguard** [argoproj/argo-workflows#6807]
## Summary

Currently the workflows generated by workflowTemplate where the `generateName` is defined will have a suffix which is a random string of length 5, see https://github.com/argoproj/argo-workflows/blob/e5b131a333afac0ed3444b70e2fe846b86dc63e1/workflow/util/util.go#L613 this has brought up workflow name conflicts in our use case. It would be great if the length of the random string can be customized. 

What change needs making?
Add one more parameter in the workflow definition, for example, `generateNameSuffixLength` so that it can be customized. 

## Use Cases

When would you use this?

ASAP, we are now trying to override the `name` field when submitting the workflow as a workaround now. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tooptoop4** [comment]
@treeguard how do u handle this for cronworkflows?

**Comment by LinuxSuRen** [comment]
I'm wondering if it's ok to let Kubernetes generate the name. I mean just provide the `generateName` instead of the `name` field.

**Comment by tooptoop4** [comment]
@LinuxSuRen generateName only provides 5 random characters which is not unique, we facing collisions

**Comment by LinuxSuRen** [comment]
> @LinuxSuRen generateName only provides 5 random characters which is not unique, we facing collisions

That is the limit of Argo workflow. I'm talking about letting Kubernetes to generate it.

**Comment by agilgur5** [comment]
https://github.com/argoproj/argo-workflows/issues/7900 seems like a more generic option that would supersede this.
