### ISSUE TITLE
`quick-start-postgres.yaml` should install the current release of Argo components

### ISSUE THREAD

**Issue by spkane** [argoproj/argo-workflows#6808]
# Summary

The Kubernetes manifest at:

https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/quick-start-postgres.yaml

should be upgraded to use the current release of Argo Workflows

# Use Cases

When would you use this?

This is a nice way to quickly spin up a functional environment for demos and testing, but the fact that it lags behind in features and behaviors can lead to suprises.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by spkane** [comment]
I did realize that it is here:

https://github.com/argoproj/argo-workflows/releases/download/v3.1.12/quick-start-postgres.yaml

But it does still seem like the stable version should point to the current (non RC/beta) release.

**Comment by alexec** [comment]
Pointing to latest is intentional. Nothing in the repository can be versioned.

**Comment by bbrandt** [comment]
For others that would like to know how to get the latest stable of `quick-start-postgres.yaml`, this looks like it: 
https://github.com/argoproj/argo-workflows/releases/latest/download/quick-start-postgres.yaml
