### ISSUE TITLE
current_namespace needs to be updated

### ISSUE THREAD

**Issue by boehb-efs** [argoproj/argo-workflows#6813]
## Summary

What happened/what you expected to happen?
After installing 2 namespaced instances of argo with ingresses on different paths but within the same domain, argo seems to have problem with its cache when switching between the instances (managedNamespace differs from current_namespace). 
I expected the switch to run smoothly, however I received this error:
`Unsuccessful HTTP response: workflows.argoproj.io is forbidden: User "system:serviceaccount:**argo-mgmt**:admin" cannot list resource "workflows" in API group "argoproj.io" in the namespace "**argo**"`

What version of Argo Workflows are you running?
3.1.8

## Diagnostics

What Kubernetes provider are you using? Azure Kubernetes Service

What executor are you running? K8SAPI

![argo](https://user-images.githubusercontent.com/78801071/135055225-afe3889e-686c-4c03-a2b7-e9ca94f2422c.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@alexec Do we have browser cache for a namespace?
