### ISSUE TITLE
Use either expr or govaluate consistently, not both

### ISSUE THREAD

**Issue by scravy** [argoproj/argo-workflows#6823]
# Summary

Either `when:` should use [antonmedv/expr](https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md) or `depends:` and `{{#` template tags should use [Knetic/govaluate](https://github.com/Knetic/govaluate).

There should be just one expression language/syntax be used consistently. Personally I'd be in favor of `expr`, but that matters less to me than to have a consistent developer experience.

# Use Cases

`when:`, `depends:` and `{{#` expr template tags. Currently these use different expression syntax, `when:` uses `govaluate`, whereas `depends:` and `{{#` uses `expr`. This is confusing and not very maintainable.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I agree with this, but i don't know how we'd remove support without breaking users workflows.

**Comment by scravy** [comment]
Are there any usages of govaluate other than `when:`? Maybe `when:` could be deprecated (without removal) and an `if:` could be introduced which uses antonmedv/expr. This way user workflows using `when:` with govaluate expressions should continue to work.

**Comment by alexec** [comment]
I think a new `if` is a great idea.

**Comment by agilgur5** [comment]
Going to close this out as duplicative of #7831 since the decision has been made with multiple maintainers accepting and #7831 is a specific proposal to address it.
