### ISSUE TITLE
How do I work with /argo/staging/script/ at a non-elevated level?

### ISSUE THREAD

**Issue by wdma** [argoproj/argo-workflows#6829]
QUESTION: How can I debug this?

the command I am using is:

argo submit -n argo --watch https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/hello-world.yaml --serviceaccount argo

I am using 
argo: v3.1.12
  BuildDate: 2021-09-16T13:59:01Z
  GitCommit: e62b9a8dc8924e545d57d1f90f901fbb0b694e09
  GitTreeState: clean
  GitTag: v3.1.12
  GoVersion: go1.15.7
  Compiler: gc
  Platform: linux/amd64

I am testing the emmisary container runtime executor

I am using the argo serviceaccount and a role that has permission to do many things including creating and viewing workflows and pods.

There are no pod logs to report.
The last few lines of the workflow-controller log are:

time="2021-09-29T15:37:47.704Z" level=info msg="Update leases 200"
time="2021-09-29T15:37:52.722Z" level=info msg="Get leases 200"
time="2021-09-29T15:37:52.746Z" level=info msg="Update leases 200"
time="2021-09-29T15:37:57.767Z" level=info msg="Get leases 200"
time="2021-09-29T15:37:57.793Z" level=info msg="Update leases 200"
time="2021-09-29T15:37:59.042Z" level=info msg="List workflows 200"
time="2021-09-29T15:37:59.043Z" level=info msg=healthz age=5m0s err="<nil>" instanceID=hippocampus-controller labelSelector="!workflows.argoproj.io/phase,workflows.argoproj.io/controller-instanceid=hippocampus-controller" managedNamespace=
time="2021-09-29T15:38:00.041Z" level=info msg="Watch workflowtemplates 200"

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@wdma are you using `instanceID=hippocampus-controller` for submitting your workflow?

**Comment by wdma** [comment]
Yes, I am.  Apologies. It is below

```
apiVersion: v1
data:
  containerRuntimeExecutor: emmisary
  instanceID: hippocampus-controller
  workflowDefaults: '{"ca.crt": "-----BEGIN CERTIFICATE-----REDACTED-----END
    CERTIFICATE-----", "metadata": {"annotations": {"argo": "workflows"}}, "spec":
    {"parallelism": 3, "securityContext": {"fsGroup": 2000, "runAsGroup": 3000, "runAsNonRoot":
    true, "runAsUser": 1000}, "ttlStrategy": {"secondsAfterSuccess": 5}}}'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"containerRuntimeExecutor":"emmisary","instanceID":"hippocampus-controller","workflowDefaults":"{\"ca.crt\": \"-----BEGIN CERTIFICATE-----REDACTED-----END CERTIFICATE-----\", \"metadata\": {\"annotations\": {\"argo\": \"workflows\"}}, \"spec\": {\"parallelism\": 3, \"securityContext\": {\"fsGroup\": 2000, \"runAsGroup\": 3000, \"runAsNonRoot\": true, \"runAsUser\": 1000}, \"ttlStrategy\": {\"secondsAfterSuccess\": 5}}}"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"workflow-controller-configmap","namespace":"argo"}}
  creationTimestamp: "2021-09-28T19:23:47Z"
  name: workflow-controller-configmap
  namespace: argo
  resourceVersion: "137365"
  uid: 7fe732c4-e99b-46d5-b788-40df67888b1d
```

**Comment by wdma** [comment]
additional testing. I deleted the configmap and reran some tests

Interestingly, the logs still show the controller in place.  Hello-world still launches the workflow and no pods. 

QUESTION:
aside from       kubectl delete -f <the configmap.yaml> are there additional steps I must take to remove the controller?

 
```
time="2021-09-29T19:06:55.209Z" level=info msg="Update leases 200"
time="2021-09-29T19:06:59.053Z" level=info msg="List workflows 200"
time="2021-09-29T19:06:59.053Z" level=info msg=healthz age=5m0s err="<nil>" instanceID=hippocampus-controller labelSelector="!workflows.argoproj.io/phase,workflows.argoproj.io/controller-instanceid=hippocampus-controller" managedNamespace=
time="2021-09-29T19:07:00.221Z" level=info msg="Get leases 200"
time="2021-09-29T19:07:00.244Z" level=info msg="Update leases 200"
time="2021-09-29T19:07:00.465Z" level=info msg="Watch clusterworkflowtemplates 200"
time="2021-09-29T19:07:05.280Z" level=info msg="Get leases 200"
time="2021-09-29T19:07:05.290Z" level=info msg="Update leases 200"
time="2021-09-29T19:07:10.299Z" level=info msg="Get leases 200"
time="2021-09-29T19:07:10.307Z" level=info msg="Update leases 200"
time="2021-09-29T19:07:15.324Z" level=info msg="Get leases 200"
time="2021-09-29T19:07:15.333Z" level=info msg="Update leases 200"
time="2021-09-29T19:07:20.339Z" level=info msg="Get leases 200"
time="2021-09-29T19:07:20.346Z" level=info msg="Update leases 200"
time="2021-09-29T19:07:25.366Z" level=info msg="Get leases 200"
time="2021-09-29T19:07:25.381Z" level=info msg="Update leases 200"
```

**Comment by sarabala1979** [comment]
Can you delete the `argo` namespace and reinstall it? I really don't have an idea about the current state of your controller and namespace.

**Comment by wdma** [comment]
@sarabala1979 Thank you for your attention. I have rebuilt my cluster and am testing as I go.  If I find the error is with Argo, I will add to this thread, but I am closing it for now as I am starting from scratch.

**Comment by wdma** [comment]
@sarabala1979 I have rebuilt the cluster and have made progress, but still do not understand the proper settings.  I am getting the following error:

```
Error: failed to start container "main": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/argo/staging/script": permission denied: unknown
```

here is the yaml:

```
{
   "apiVersion": "argoproj.io/v1alpha1",
   "kind": "Workflow",
   "metadata": {
      "annotations": {
         "argo": "workflows"
      },
      "generateName": "hello-test-",
      "labels": {
         "workflows.argoproj.io/archive-strategy": "false"
      }
   },
   "spec": {
      "entrypoint": "entrypoint",
      "parallelism": 3,
      "podGC": {
         "strategy": "OnWorkflowSuccess"
      },
      "securityContext": {
        "runAsUser": 1000,
        "runAsGroup": 3000,
        "fsGroup": 2000,
      },
      "templates": [
         {
            "dag": {
               "tasks": [
                  {
                     "name": "h",
                     "template": "hello"
                  }
               ]
            },
            "name": "entrypoint"
         },
         {
            "name": "hello",
            "script": {
               "image": "ubuntu:latest",
               "imagePullPolicy": "IfNotPresent",
               "source": "echo Hello; exit",
               "securityContext": {
                 "runAsNonRoot": true,
               },
            },
         }   
      ],
      "ttlStrategy": {
         "secondsAfterSuccess": 5
      }
   }
}
```

everything else (configmaps and user roles) are the same as above.  

QUESTION:
Are the security settings correct and if so, what else do I need to do?

**Comment by wdma** [comment]
Solved!  I had assigned improper annotations to my pod, so it was calling on the wrong ConfigMap.  Apologies, my fault.
