### ISSUE TITLE
enable `bodyclose` lint, fix issues

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6837]
We should enable this linter and fix the issues it shows.

**Comment by strantalis** [comment]
I can try to tackle this issue along with the other issues #6838 #6840 around enabling linters if you would like.

**Comment by alexec** [comment]
yes please

**Comment by strantalis** [comment]
Did you want the additional linters in a separate pull requests?

**Comment by alexec** [comment]
please
