### ISSUE TITLE
Pause steps so users can shell in and debug them

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6841]
# Summary

Users want their container to stop so the can shell in (e.g `kubectl exec -ti -c main -- /bin/bash`) and debug it.

# Use Cases

You can do this with container-set today, a work-around:

1. Container A sleeps forever.
2. Container B depends on container A.
3. You will be able to shell into container B.
4. When ready for container B to start, create the marker file in the /var/run/argo volume.

With the emissary, we could potentially make this feature available to script and container templates by some kind of 1st-class support. Maybe a way to annotate the step? 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by NikeNano** [comment]
I am working on a PR for this, will create a draft later tonight.

**Comment by alexec** [comment]
@NikeNano do you have any thoughts on how this should work? I think the uses would want to control this and be able to turn it on and off temporary for a single step.

What about a special env var which you can set, and the emissary recognises? If it sees it (on init), it creates a marker file under `/var/run/argo/pause` and the main container then will not start until the file is deleted?

**Comment by NikeNano** [comment]
I have create a draft [here](https://github.com/argoproj/argo-workflows/pull/6868) @alexec. I have to admit I might need to read up further on the emissary controller. 

> What about a special env var which you can set, and the emissary recognises? If it sees it (on init), it creates a marker file under /var/run/argo/pause and the main container then will not start until the file is deleted?

How would it work with an 'env' variable in relation to which step to paus? I think it would make more sens to rely on annotations or some filed on the workflow for this(as you mention in the issue description).

**Comment by alexec** [comment]
I'll only want to pause some workflows, so I can't change a `WorkflowTemplate`, I must change the workflow.

Do you think we might need a selector perhaps? 

```yaml
spec:
  pause:
    expression: 'node.name == "whatever"'
```

I don't think we should use annotation to signal that the emissary should pause before starting, as it is hard for process to read annotation. Better to use env var set by controller.

The controller should log when it adds the pause marker.

It'd be good to come up with another term rather than "pause" as we already use "pause". Maybe "debug pause"?

**Comment by NikeNano** [comment]
> I'll only want to pause some workflows, so I can't change a `WorkflowTemplate`, I must change the workflow.
> 

I see your point, and defiantly agree. 

> Do you think we might need a selector perhaps?
> 
> ```yaml
> spec:
>   pause:
>     expression: 'node.name == "whatever"'
> ```
> 
> I don't think we should use annotation to signal that the emissary should pause before starting, as it is hard for process to read annotation. Better to use env var set by controller.
> 

Sound good to use a selector. But what is the need for env var if we use the selector?


> The controller should log when it adds the pause marker.
> 
> It'd be good to come up with another term rather than "pause" as we already use "pause". Maybe "debug pause"?
> 

Agree. 

> > The current suggestion blocks the write of the 'exitcode' file and should allow the users to continue the workflow if they manually create it from the shell within the container as I understand, think that would be nice to allow users to "start" the workflow again if they like to.
> 

> You could create this file if they wanted to set the exit code manually. The Emissary should not start the sub-process if that file has been manually created by the user. 

ok, then I guess it will not matter. However I could see use cases where it would be nice to see if a potential fix done in the container made it work(but this is limited to relativly few use cases I guess).

**Comment by alexec** [comment]
> But what is the need for env var if we use the selector?

Workflow pod do not have access to workflow spec. So the workflow controller must tell them they should go into debug pause.

>  it would be nice to see if a potential fix done in the container made it work

I don't think it would be hard to support this use case, so perhaps we should.

Refined spec:

```yaml
spec:
  debug: 
     pause: 'node.name == "whatever"'
```


@jessesuen - any input?

**Comment by jessesuen** [comment]
Some thoughts: ephemeral containers were designed for debugging live pods. The advantage of using ephemeral containers is that you don't need to bundle in all your anticipated debugging tools (curl, kubectl, etc...) ahead of time. However, they were meant to troubleshoot long-lived deployments. Luckily, we could instrument argoexec to decide to run indefinitely when a "debug/pause" is requested.

I think we should consider leveraging ephemeral containers as the mechanism for shelling in and debugging. The advantage I see is that it would work with any executor, not just the emissary. Also, users would be able to use native `kubectl debug` debug command to start their session.

The feature that we would need from workflow-controller and argoexec, is to signal the argoexec sidecar to not quit immediately when debugging is desired. By allowing the pod to live longer, it allows `kubectl debug` to be possible.

Caveat: ephemeral containers is still alpha and so is gated by a feature flag.

**Comment by NikeNano** [comment]
Got stuck with work so will first have time to look at this during whe weekend, thanks for the feedback.

**Comment by NikeNano** [comment]
To debug before main process is started we need to add a sleep before the main process starts. This should be possible for the `emissary executor` (adding a sleep command based upon an env variable which we can set on the `container`). It is not clear how we would do this for the other executors since it would require do add a cmd to sleep before the main command is run, or how is `argoexec` used here?. Can we expect certain commands to be available in the container and does it make sens to mutate the command in this case?

For debugging while running no changes should be needed as you point out @alexec. 

Debugging after the process has run should be simple to implement for all executors if we pursue to add a sleep command in the wait container. It would also required to remove the deadline for the workflow to make sure it is not GC if I understand the code correctly?

**Comment by NikeNano** [comment]
After doing some work on it, have the pause stuff set up before and after I realised that the signal to remove the pause will be a bit tricky. As I understand I will not be able to change the enviroment varialbe of the running process and thus can not update it. Neaither will I be able to make updates to the pod in relation to the enviroment variable.  I thought about adding a volume and constantly checking for a file, then when using an ephemeral container I could make changes to the file(or simply just delete it) to make allow the paused container(template) to start again. Do you have some thoughts on this @alexec?

**Comment by NikeNano** [comment]
I suggest we stick to marker files to avoid having to use Process Namespace Sharing in order to access Process Namespace from other containers to be able to send the signals. It also makes more sens to me to use marker files since the emissary already uses that for triggering as I understand to be more consistent @alexec.
