### ISSUE TITLE
failed to verify token: failed to verify signature: fetching keys oidc: failed to decode keys: got Content-Type = application/json, but could not unmarshal as JSON: square/go-jose: invalid JWK, x5t#S256 header has invalid encoding

### ISSUE THREAD

**Issue by nvenkatapavan** [argoproj/argo-workflows#6843]
## Summary

What happened/what you expected to happen?
We have configured sso with Argo Workflows.  **v2.12.5** of Argo Workflows was working with out any issues. When we try deploy newer version of Argo Workflows ( v3.1.5 and v3.1.8  ), its giving below error. We tried upgrade / fresh install in both cases it's giving same error. 

**Configuration from Pod**
  containers:
  - args:
    - server
    - --configmap=argo-argo-workflows-workflow-controller-configmap
    - --auth-mode=sso
    - --auth-mode=client
    - --secure=false
** Configmap ***
apiVersion: v1
data:
  config: |
    containerRuntimeExecutor: pns
    artifactRepository:
      s3:
        accessKeySecret:
          key: accesskey
          name: argo-s3-creds
        secretKeySecret:
          key: secretkey
          name: argo-s3
        bucket: mydemo
        endpoint: s3.amazonaws.com
        insecure: false
    sso:
      clientId:
        key: client_id
        name: argo-oidc
      clientSecret:
        key: client_secret
        name: argo-oidc
      issuer: https://demo.myargo.com
      redirectUrl: https://demo.myargo.com/oauth2/callback

   
**Getting below error:**
`failed to verify token: failed to verify signature: fetching keys oidc: failed to decode keys: got Content-Type = application/json, but could not unmarshal as JSON: square/go-jose: invalid JWK, x5t#S256 header has invalid encoding {
  "keys": [
    {
      "alg": "RS256",
      "e": "AQAB",
      "kid": "*******************",
      "kty": "RSA",
      "n": "***********************",
      "use": "sig",
      "x5t#S256": "*******************"
    }
  ]
}`

What version of Argo Workflows are you running?
v3.1.8

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
kubectl get wf -o yaml ${workflow}
```

What Kubernetes provider are you using?

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
PNS

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I've not seen this before. Could you book in 30m so we can debug?

https://bit.ly/book-30m-with-argo-team

**Comment by sudarshntn** [comment]
I have scheduled a meeting for Monday 4th Oct 12:30 slot.

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/pull/6831

**Comment by alexec** [comment]
What we use for Github:

https://github.com/argoproj/argoproj-deployments

**Comment by nvenkatapavan** [comment]
@alexec I tried deploying https://github.com/argoproj/argo-workflows/blob/master/manifests/install.yaml
modified argo-server deployment with below params to enable sso. 


        - server
        - --configmap=workflow-controller-configmap
        - --auth-mode=sso
        - --secure=false
        image: quay.io/argoproj/argocli:latest
        name: argo-server
        ports:
        - containerPort: 2746
          name: web
        readinessProbe:
          httpGet:
            path: /
            port: 2746
            scheme: HTTP
---
I created ingress and secrets manually. We are getting same error. 

`failed to verify token: failed to verify signature: fetching keys oidc: failed to decode keys: got Content-Type = application/json, but could not unmarshal as JSON: square/go-jose: invalid JWK, x5t#S256 header has invalid encoding { "keys": [ { "alg": "RS256", "e": "AQAB", "kid": "*******************", "kty": "RSA", "n": "***********************", "use": "sig", "x5t#S256": "*******************" } ] }`

**Comment by alexec** [comment]
Ok, so still a problem with latest. Did you try installing Dex?
