### ISSUE TITLE
We could use `net.Error.Temporary()` and `net.Error.Timeout()` in `IsTransientErr`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6848]
## Summary

We want to factor in more types of errors that can be retried.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@terrytangyuan thoughts?

**Comment by terrytangyuan** [comment]
We covered these already:
```
func isTransientNetworkErr(err error) bool {
	switch err.(type) {
	case net.Error:
		switch err.(type) {
		case *net.DNSError, *net.OpError, net.UnknownNetworkError:
			return true
```

`Temporary()` and `Timeout()` are two methods implemented for those error types (`*net.DNSError, *net.OpError, net.UnknownNetworkError`):
```
type UnknownNetworkError string

func (e UnknownNetworkError) Error() string   { return "unknown network " + string(e) }
func (e UnknownNetworkError) Timeout() bool   { return false }
func (e UnknownNetworkError) Temporary() bool { return false }
```
However, I just noticed that we are retrying on all those network errors without checking whether they are temporary, e.g. via `err.(net.Error).Temporary()`. We should probably fix that.

**Comment by alexec** [comment]
👍
