### ISSUE TITLE
Parse JSON structured logs in Argo UI

### ISSUE THREAD

**Issue by astanway** [argoproj/argo-workflows#6856]
# Summary

When using FluentBit / FluentD, logs are written to stdout/stderr in a structured JSON format. It is difficult to read these easily in the Argo UI

# Use Cases

When clicking through to the node `main` logs, it would be nice to see only the `message` component of a JSON structured log/

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by pmbrull** [comment]
Thanks for popping this issue. We are seeing the same error when working with the logs on the Java SDK. We are getting an object that it's not parseable as a JSON (it's formatted as a JSONL).

The call fails internally in the SDK with `com.google.gson.JsonSyntaxException`. The only workaround is to patch internal calls to cast the result to a `String` that we then need to cook.

This is reproducible in the following example: https://github.com/pmbrull/argo-java-examples/blob/main/playground/src/main/java/SimpleWorkflowLogs.java

Thanks
