### ISSUE TITLE
Argo Workflows does not report failure and sits in pending when failing due to RBAC. 

### ISSUE THREAD

**Issue by todaywasawesome** [argoproj/argo-workflows#6857]
## Summary

What happened/what you expected to happen?

Setting up a quick demo and started with the namespace example install of Argo WF https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml

When submitting a template through the UI and specifying a new namespace an error was thrown. `Bad Request: the namespace of the provided object does not match the namespace sent on the request` which seems appropriate if not a tad obtuse. 

When submitting the same workflow through the CLI it was accepted and put in pending. 
![Screen Shot 2021-10-04 at 11 30 56 AM](https://user-images.githubusercontent.com/3849900/135897127-936fcd04-f6c5-41b3-8664-b6696554b603.png)

But, because the Argo user does not have permission to submit these jobs to the new namespace they stay in pending forever and no pods are spun up. Ideally, this should throw an error "Argo does not have permission to this namespace. [Please configure permissions.](https://argoproj.github.io/argo-workflows/security/)" 

What version of Argo Workflows are you running?

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```bash
kubectl create ns demo
argo submit https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/hello-world.yaml -n demo --watch
```

What Kubernetes provider are you using?
Docker desktop

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Kubelet

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by thalleslmF** [comment]
can you assign me @todaywasawesome?
