### ISSUE TITLE
support loading parameter values from configmaps not working

### ISSUE THREAD

**Issue by softwarebloat** [argoproj/argo-workflows#6861]
## Summary

What happened/what you expected to happen?
I tried the new feature implemented by @terrytangyuan in #6662 using this example https://github.com/argoproj/argo-workflows/blob/master/examples/arguments-parameters-from-configmap.yaml but it doesn't work to me

What version of Argo Workflows are you running?
3.2.0-rc5

## Diagnostics

This is the configmap
```yaml
apiVersion: v1
data:
  msg: hello world
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-27T15:42:48Z"
  name: simple-parameters-configmap
  namespace: my-namespace
  resourceVersion: "252410349"
  selfLink: /api/v1/namespaces/my-namespace/configmaps/simple-parameters-configmap
  uid: 65d4258f-38fb-498c-81dd-18b1862b5fa6

```

What Kubernetes provider are you using?
kubernetes is native on our host

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Docker

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
time="2021-10-05T12:48:36.808Z" level=error msg="error in entry template execution" error="unable to retrieve inputs.parameters.message from ConfigMap: ConfigMap 'simple-parameters-configmap' does not exist" namespace=data workflow=arguments-parameters-from-configmap


# The workflow's pods that are problematic:
no pod started

# Logs from in your workflow's wait container, something like:
no pod started so no container logs too
```
Any idea on why isn't working?
Thanks!

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
You are missing the labels in configmap: https://github.com/argoproj/argo-workflows/blob/master/examples/configmaps/simple-parameters-configmap.yaml#L7

It is required for the controller to pick up only the necessary configmaps.

**Comment by softwarebloat** [comment]
Thanks for the quick answer. I fixed the configmap but nothing changed. Same error :disappointed:

**Comment by terrytangyuan** [comment]
Could you paste your controller pod's log?

**Comment by terrytangyuan** [comment]
Also seems like your ConfigMap is in `namespace: my-namespace` but your workflow is in `namespace=data`?

**Comment by softwarebloat** [comment]
yes sorry, `data` is the right one (i put my-namespace before manually)

here's the controller log before,during and after i run the workflow

```
E1005 14:15:56.755426       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.5/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: wor │
│ E1005 14:16:35.510288       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.5/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: wor │
│ time="2021-10-05T14:17:01.317Z" level=warning msg="Non-transient error: configmaps \"artifact-repositories\" not found"                                                                                 │
│ time="2021-10-05T14:17:01.317Z" level=error msg="error in entry template execution" error="unable to retrieve inputs.parameters.message from ConfigMap: ConfigMap 'simple-parameters-configmap' does no │
│ time="2021-10-05T14:17:01.317Z" level=warning msg="Non-transient error: unable to retrieve inputs.parameters.message from ConfigMap: ConfigMap 'simple-parameters-configmap' does not exist"
```

don't know what's that `artifact-repositories` configmap is :man_shrugging:

**Comment by terrytangyuan** [comment]
`artifact-repositories` in unrelated and can be ignored.

The log seems truncated. Could you make sure you re-install to a clean namespace and create/use your configmap in that namespace and then paste your log again?

**Comment by softwarebloat** [comment]
sorry, here you have

```
time="2021-10-05T14:17:01.317Z" level=warning msg="Non-transient error: configmaps \"artifact-repositories\" not found"
time="2021-10-05T14:17:01.317Z" level=error msg="error in entry template execution" error="unable to retrieve inputs.parameters.message from ConfigMap: ConfigMap 'simple-parameters-configmap' does not exist" namespace=data workflow=arguments-parameters-from-configmap-kmhvd
time="2021-10-05T14:17:01.317Z" level=warning msg="Non-transient error: unable to retrieve inputs.parameters.message from ConfigMap: ConfigMap 'simple-parameters-configmap' does not exist"

```

**Comment by terrytangyuan** [comment]
Unfortunately, I still cannot reproduce the issue with the latest versions, e.g. `v3.2.0-rc6`. 

```
$ kubectl create -f examples/configmaps/simple-parameters-configmap.yaml
configmap/simple-parameters created

$kubectl create -f examples/arguments-parameters-from-configmap.yaml
workflow.argoproj.io/arguments-parameters-from-configmap-kx56l created

arguments-parameters-from-configmap-kx56l   0/2     Completed   0          15s
```

**Comment by guidorice** [comment]
If anyone else runs across this, it's rather tricky if you don't know k8s. It turns out that some forms of kubectl commands will drop the labels section from the configmap!

Works: `kubectl create -n argo -f path/to.yaml`

Does not work: `kubectl create configmap configmapname -n argo --from-file path/to.yaml`

Verify by: `kubectl get cm -n argo -o yaml configmapname`

And make sure `workflows.argoproj.io/configmap-type: Parameter`  is in the metadata!
