### ISSUE TITLE
Change default executor from docker to k8sapi

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#6873]
Since k8s is deprecating docker runtime, maybe we should default the executor to k8sapi
https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

E.g. when a user is testing argo in latest stable gke, the default configuration won't work due to docker executor

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Duplicate of https://github.com/argoproj/argo-workflows/issues/6785

**Comment by tczhao** [comment]
Thanks, I could've done a better search
