### ISSUE TITLE
more helpful error than `unknown (watch pods)` when workflow role is set-up incorrectly

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6886]
Time and time again, I find myself telling users this is actually a permission issue. It is usually accompanied by `Watch pods 403'. We could easily improve this experience by printing a link to [the FAQ](https://github.com/argoproj/argo-workflows/blob/master/docs/faq.md), and then making sure the FAQ has some helpful text.

**Comment by momom-i** [comment]
Hello, I'm interested in argo and I'd like to understand how to work, doing some task. Can I do this task?
