### ISSUE TITLE
Update README to show massive workflow

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6889]
Look how big you can go:

![big-wf-3](https://user-images.githubusercontent.com/1142830/136454022-ad755a68-24bb-4f77-97f2-4132293e8d78.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by 2kindsofcs** [comment]
Hi, I want to take this issue.

**Comment by alexec** [comment]
I don't know who's workflow this is. Don't have permission.
