### ISSUE TITLE
Low Friction Contribution

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6890]
Make it easy to contribute.

* [x] #6892
* [x] #6519 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by agilgur5** [comment]
Looks like the above issues were resolved. this is also 2 years old now and we have things like Codespaces #11981 et al, devcontainers, etc, that all help pretty greatly too.
