### ISSUE TITLE
adding hacktoberfest topic

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#6891]
# Summary

Like argo-cd, I think we can add a "hacktoberfest" topic so it aligns with this years hacktoberfest repository participation rules and welcomes people to contribute

![image](https://user-images.githubusercontent.com/20961507/136471688-dcdae83a-c9a1-42ec-878a-4e8b0079283a.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tczhao** [comment]
Hi @alexec, Is "adding a `hacktoberfest` topic" something we can do?

**Comment by alexec** [comment]
what is the "rule"?

**Comment by alexec** [comment]
done
