### ISSUE TITLE
Improve security posture by running `wait` container as non-root

### ISSUE THREAD

**Issue by paolocarta** [argoproj/argo-workflows#6895]
# Summary
I am using a security context for Workflows using the pns executor. Below an example of the sec context:
`  securityContext:
      runAsNonRoot: true
      runAsUser: 1001
      fsGroup: 999`

Using this context the argoproj/argoexec:v3.1.3 cannot run. Apparently it requires root privileges. Below a YAML snippet from the Pod's status:
`    - image: argoproj/argoexec:v3.1.3
      name: wait
          message: container has runAsNonRoot and image will run as root`

# What change needs making?

- Would be ideal to be able to run without root privileges.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you please try with the emissary executor?

**Comment by tooptoop4** [comment]
can close according to https://blog.argoproj.io/practical-argo-workflows-hardening-dd8429acc1ce ? @alexec

**Comment by agilgur5** [comment]
PNS no longer exists after #8296 / 3.4 and Emissary does not run as root, so this has been completed
