### ISSUE TITLE
Kubeflow Pipelines "Intermediate Representation"

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6919]
# Summary

KFP v2 will support a generalised workflow specification. We may want to have support for that.

# Use Cases

Relates to #873 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by isubasinghe** [comment]
Not sure if this is the workflow specification you are referring to but if it is, seems like you are able to close this issue since those pipelines seem to transpile to argo https://github.com/kubeflow/pipelines/issues/3253

**Comment by isubasinghe** [comment]
Is this https://www.kubeflow.org/docs/components/pipelines/sdk-v2/build-pipeline/ what you are referring to? Not entirely sure about much of this but seems like kfp v1 supported compiling to argo workflows, so perhaps v2 will as well? 

Which may mean our job is easier.

**Comment by alexec** [comment]
See https://github.com/kubeflow/pipelines/issues/3703
