### ISSUE TITLE
Typo in function "WriteTeriminateMessage"

### ISSUE THREAD

**Issue by SunSparc** [argoproj/argo-workflows#6999]
I hesitate to even report this because it is such a small thing. I was looking through the code and came across a type in the function name: `WriteTeriminateMessage`

This function is found in the [/util/util.go](https://github.com/argoproj/argo-workflows/blob/9ca9d2e683420b1ff76afde848880963ea52d39c/util/util.go#L53) file.

I would expect the function name to be: `WriteTerminateMessage`

**Comment by dinever** [comment]
Thanks for reporting this! Would you like to submit a PR?
