### ISSUE TITLE
retryStrategy needs exponential backoff controls

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-workflows#700]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What happened**:
Now that we have a retryStrategy field, we need some knobs to control how to retry.

Taking from the k8s backoff struct/terminology:
```
// Backoff holds parameters applied to a Backoff function.
type Backoff struct {
	Duration time.Duration // the base duration
	Factor   float64       // Duration is multiplied by factor each iteration
	Jitter   float64       // The amount of jitter applied each iteration
	Steps    int           // Exit with error after this many steps
}
```

I think we need duration and factor. Steps is already covered by the `limit` field. Jitter is probably unnecessary since pod scheduling will naturally introduce some jitter.

**Environment**:
- Argo version: 2.0.0-beta1

**Comment by jessesuen** [comment]
Also I think Max time.Duration would be needed.

**Comment by eggsbenjamin** [comment]
*bump*
