### ISSUE TITLE
Set Default workflowMetadata

### ISSUE THREAD

**Issue by hbrewster-splunk** [argoproj/argo-workflows#7011]
# Summary

Currently, argo-workflows supports a few `workflowDefaults` in the workflow-controller-configmap. However, it does not support setting `spec.workflowMetadata.labels` as a controller level default which causes difficulty when implementing archived workflows: 

# Use Cases

A workflow is only archived if it meets a specific archive label, e.g. if the following label exists `spec.workflowMetadata.labels[x].workflows.argoproj.io/archive-strategy = always` so without the capability of setting this label as default, we cannot guarantee workflow archival by default.

The alternative would be to tailor the workflow-controller to archive workflows based on a metadata.spec label. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
But you could do `spec.metadata.labels`?

**Comment by hbrewster-splunk** [comment]
I've tried that. The workflow is only archived if the label is matched in spec.workflowMetadata.labels not spec.metadata.labels
