### ISSUE TITLE
Unable to parse schedule value with 30 18 ? * MON#3

### ISSUE THREAD

**Issue by sanjaytangudu230** [argoproj/argo-workflows#7015]

**Comment by alexec** [comment]
Please add more information.

**Comment by sanjaytangudu230** [comment]
> Please add more information.
 whenever I am giving "30 18 ? * MON#3" as schedule value it is throwing an error

 Internal Server Error: cron schedule is malformed: failed to parse int from MON#3: strconv.Atoi; parsing "MON#3": invalid syntax

**Comment by sanjaytangudu230** [comment]
> Hi @sanjaytangudu230, thanks for reporting this!
> 
> We have two cron libraries:
> 
> * The React cron library `cron-parser` which is used on UI for helper messages
> * The Golang cron library `github.com/robfig/cron` which is used in backend for actual validation
> 
> These two cron libraries don't share the exact same behaviors.
> 
> Looks like [github.com/robfig/cron](https://github.com/robfig/cron) doesn't support the `#3` syntax of corn.
> 
> Try this: https://play.golang.org/p/H--VRN7uR58
> 
> ```go
> package main
> 
> 
> import (
>   "fmt"
>   "github.com/robfig/cron/v3"
> )
> 
> 
> func main() {
>   _, err := cron.ParseStandard("30 18 ? * MON#3")
>   if err != nil {
>     fmt.Println(err)
>   }
> }
> ```
> 
> ```
> failed to parse int from MON#3: strconv.Atoi: parsing "MON#3": invalid syntax
> ```

even the above one was failing.I want to give this syntax in cron workflow template

**Comment by sanjaytangudu230** [comment]
How to kill(delete)  the cron workflow template  automatically after specific number of times it has been triggered or until a specific date

**Comment by sanjaytangudu230** [comment]
how to validate 5 valued argo cron expression
