### ISSUE TITLE
Allow external identity provider authorization services for SSO

### ISSUE THREAD

**Issue by jcmuller** [argoproj/argo-workflows#7050]
# Summary

What change needs making?

There are cases where organizations prefer to use the same identity provider across all their applications. I would like to suggest that argo accepts OIDC bearer tokens from upstream providers and only does the RBAC check based on the groups passed in.

This would allow organizations to not have to configure 2 inlined sso processors: whatever the upstream is, be it Keycloak, Authelia, oauth2-proxy, etc as well as argo server itself.

# Use Cases

When would you use this?

- Every time an user logs into the argo UI.
- Users of argocli configured to talk to argo-server -- with the current way you have to export the bearer token from argo UI to be used in the cli
- Service to service requests via grpc

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by jcmuller** [comment]
@sarabala1979 @alexec I am happy to take a stab at this if you guys think it would be useful/make it in.

**Comment by agilgur5** [comment]
Marking this as superseded by #12049 as that one has received more attention
