### ISSUE TITLE
UI: make somewhat skinnable / themable

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7054]
# Summary

Allows users to skin the UI with new colours, their own loge, but keep Argo bits.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by krrrr38** [comment]
In my cases, it's enoght to change banner colour by environments.
It may be possible by argocd this feature https://argo-cd.readthedocs.io/en/stable/operator-manual/custom-styles/.

**Comment by agilgur5** [comment]
See also #10825 for custom themes
