### ISSUE TITLE
Possibility to add PriorityClass to workflow submits via REST

### ISSUE THREAD

**Issue by fwfichtner** [argoproj/argo-workflows#7059]
# Summary

`podPriorityClassName` is not part of the [submitOpts](https://github.com/argoproj/argo-workflows/blob/4734cbc44dedeb2c7e5984aab5dc9b0c846ff491/pkg/apis/workflow/v1alpha1/common.go#L43). So an API submit does ignore any `PriorityClassName` we set.

# Use Cases

When submitting workflows via REST it is useful to set different `PriorityClasses` depending on timeliness or importance of our workflows.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by nmandery** [comment]
Is there anything we can do to help with this issue? Would this feature be of interest for the project and be included in argo?

I assume the best way to set a development environment to contribute is to look at the CI workflows in the `.github` directory. Does any further developer onboarding documentation exist?

**Comment by terrytangyuan** [comment]
> Is there anything we can do to help with this issue? Would this feature be of interest for the project and be included in argo?
> 
> 
> 
> I assume the best way to set a development environment to contribute is to look at the CI workflows in the `.github` directory. Does any further developer onboarding documentation exist?

Check out https://github.com/argoproj/argo-workflows/blob/master/docs/running-locally.md

**Comment by nmandery** [comment]
@terrytangyuan Thanks for the link.
