### ISSUE TITLE
Generate Workflow OpenAPI models and spec

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-workflows#707]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What happened**: With the fix in https://github.com/kubernetes/kube-openapi/pull/34, we can generate the OpenAPI workflow models and spec so that a client could be generated and things like a workflow libsonnet for ksonnet.

**Environment**:
- Argo version: 2.0.0-beta1

**Comment by bhack** [comment]
@jessesuen Is it already used in  https://github.com/tensorflow/k8s/pull/358?

**Comment by jessesuen** [comment]
No, what we have now is just the OpenAPI golang models. The missing pieces are:
1. a swagger (OpenAPI) spec - argo-ui wants this so that it can generate a client for node.
2. a workflow libsonnet file - i'm working with ksonnet team on how to do this.

I believe tensorflow/k8s is a hand-rolled workflow libsonnet and not anything auto-generated from source. But once there is an official argo workflow libsonnet which is auto-generated from the workflow spec, it would probably make sense for them to use the auto-generated one and create their helpers on top of it.

**Comment by bhack** [comment]
Yes writing extended yaml is quite time consuming.
