### ISSUE TITLE
"expression" syntax should be the same across all of the places it is used

### ISSUE THREAD

**Issue by denis-codefresh** [argoproj/argo-workflows#7089]
# Summary
Further thoughts on #6823.

Currently there are 2 different syntaxes to write expressions(conditions) and it can be a bit confusing for the users.
The goal of this enhancement is to keep only 1 way of writing them.

Available syntaxes:
* [antonmedv/expr](https://github.com/antonmedv/expr) – used with: [depends](https://argoproj.github.io/argo-workflows/enhanced-depends-logic/), [template tags](https://argoproj.github.io/argo-workflows/variables/#template-tag-kinds) 
* [Knetic/govaluate](https://github.com/Knetic/govaluate) – used with: when

Since the only place where *govaluate* package used is the `when` expression, in order to unify the syntax the package should be changed  to *expr*.
They are **NOT** compatible between each other. To not brake users workflows we should introduce another field `if` that uses *expr* syntax and announce deprecation of `when` in the future.

I checked both packages and it looks like *expr* has more richer out of the box syntax (built in functions) and faster then *govaluate* according to the [published benchmarks](https://github.com/antonmedv/golang-expression-evaluation-comparison).

Also there is a [Slack conversation](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1633532770124500) where some person faced the limitation of *govaluate* package. I believe it is possible to do with *expr* package – [demo](https://play.golang.org/p/2u9rve_5G7T).

# 

I have already put some time to check the challenges of implementing this enhancement and it looks not hard to achieve.
BUT there is one drawback that I have noticed with using *expr*. I saw @jessesuen (the one who introduced *govaluate* package to this project) did a workaround in order to use strings without quoting them.
For example: 
```go
foo != bar       // valid expression
```
According to my investigation it will not be possible with *expr* package. Each unquoted string will be treated as a variable and will result to an error ([playground](https://play.golang.org/p/f-_FxMcH6Cu)). Need to consider are we OK with this change. So @jessesuen, can you advice here please?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by scravy** [comment]
> BUT there is one drawback that I have noticed with using expr. I saw @jessesuen (the one who introduced govaluate package to this project) did a workaround in order to use strings without quoting them.
For example:

This, to me, has been a source of frustration as it is not clear in which context a string is a string or not, especially with templates. This workaround is not very well communicated and absolutely counter intuitive.

I think the right way to go would be to just expose the objects `steps`, `workflows`, etc. to the expr-evaluate engine/function. This way one would not need to resort to templating things into the expression language, but could just use the values directly.

i.e. instead of

```
when: {{workflows.inputs.whatever}} == 'foo'
```

one could have

```
if: worksflows.inputs.whatever == 'foo'
```

I think @alexec's comment about workflow event bindings is basically proposing the same thing.

**Comment by alexec** [comment]
> think @alexec's comment about workflow event bindings is basically proposing the same thing.

yes

**Comment by agilgur5** [comment]
Going to close this out as duplicative of #7831 since the decision has been made already with multiple maintainers accepting and #7831 is a specific proposal to address it.
