### ISSUE TITLE
Support timelines for release 2.12.x

### ISSUE THREAD

**Issue by vikulaggarwal** [argoproj/argo-workflows#7102]
### Discussed in https://github.com/argoproj/argo-workflows/discussions/7101

<div type='discussions-op-text'>

<sup>Originally posted by **vikulaggarwal** October 29, 2021</sup>
Is the release 2.12.X still officially supported? If yes, are there any timelines around till when it will continue to be supported?</div>

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/blob/master/docs/releases.md
