### ISSUE TITLE
Bug in default executor code

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7118]
## Summary

This link looks wrong, "" should not be docker anymore:

https://github.com/argoproj/argo-workflows/blob/ca87f2906995b8fecb796d94299f54f6dfbd6a41/workflow/controller/workflowpod.go#L538

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by mweibel** [comment]
I took an initial attempt at a fix of it, but couldn't complete it yet. Feel free to take it over :+1:

**Comment by tczhao** [comment]
Thanks, @mweibel. I will raise a PR
