### ISSUE TITLE
Is `TestCounterMetric` flakey?

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7120]
I've only seen this fail once, but for no apparent reason:

```
--- FAIL: TestCounterMetric (0.10s)
1162
    operator_metrics_test.go:125: 
1163
        	Error Trace:	operator_metrics_test.go:125
1164
        	Error:      	Expected value not to be nil.
1165
        	Test:       	TestCounterMetric
```

**Comment by tczhao** [comment]
I tried to run it 1000 times, didn't fail once..
`go test -count=1000 -run=TestCounterMetric  ./workflow/controller/`

**Comment by alexec** [comment]
Typically test that are flakey on CI, only flake on CI. Something you can get them to fail locally if you run the whole suite many times (rather than just the test). I've only seen this once, so I'm going to let it rest for now

**Comment by sarabala1979** [comment]
tracking in #7133
