### ISSUE TITLE
parallel e2e test in CI

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#7126]
A recent change in CI https://github.com/argoproj/argo-workflows/commit/c78ee6ec8cf1162070f6ddc0731c1d687fab1f95
- adds dependencies to e2e test
- limits e2e parallel run to 2

I wonder if we can remove the e2e parallel restriction since
- e2e tests are already depending on success run of `test, codegen, lint`
- the entire CI is now taking over 1hr (https://github.com/argoproj/argo-workflows/actions/runs/1410585773)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I'm conflicted:

* New contributors get confused by the large number of checks. Failing sooner helps them address one problem at a time.
* Running fewer in parallel reduces the burden on Github Actions runners.

vs:

* I'd like to get rapid feedback on my tests, I'm happy to wait 10m, but I don't like waiting 1h.

What about running 3 or 4 e2e tests in parallel?

**Comment by tczhao** [comment]
I feel since `e2e` is dependent on `test, codegen, lint`, these 3 will address most of the issues.

I think we can start with 4 parallel e2e, that'd be good

**Comment by alexec** [comment]
fixed
