### ISSUE TITLE
Update `mkdocs-material` to latest version to support dark mode

### ISSUE THREAD

**Issue by denis-codefresh** [argoproj/argo-workflows#7129]
# Summary

Currently in the docs we are using mkdocs-material 4.1.1. The latest is 7.3.6.
In mkdocs-material since [5.2.0](https://github.com/squidfunk/mkdocs-material/releases/tag/5.2.0) there is a support for dark theme.
After the upgrade the dark mode switch will appear at the top of the page.
Example: https://squidfunk.github.io/mkdocs-material

I see that we are using the same version in argo-events, so probably changes should be done in both places.

PS. argo-cd is using 7.1.7 👀

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I'm not fussed by dark modes myself (I will not turn to the darkside). But a style refresh of the docs would be nice.
