### ISSUE TITLE
Storing Workflow Spec and Status in alternative storage (Database)

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#7137]
# Summary
Inspiration from #7121, Current Argo has etcd limitation of 1 MB on workflow object.   Argo is already supported nodestatus offload. to. DB helps for large output workflows but if we have a large no of steps/templates. It couldn't create workflow objects in k8s.

Proposal:
The entire workflow can be stored in DB and the controller will interact with the DB for workflow updates.  and execute steps in k8s pods.

What change needs making?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
Duplicates #7121.
