### ISSUE TITLE
In-app survey

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7160]
We currently don't really have any way to connect to our end users. Most bugs are raised by operators - proxies for the end users. This seems to be reflected in our survey, where ops-engineer is well represented, but ML-engineer, not so much.

We could use two techniques.

(1)

Ask the user about their use case the first time they open the UI, and forward them to public docs helping them with that use case (capturing what they choose):

https://www.appcues.com/blog/how-turbotax-makes-a-dreadful-user-experience-a-delightful-one

![image](https://user-images.githubusercontent.com/1142830/140246375-7242d9c0-dc36-48bb-8461-3f0c32889901.png)

(2) 

After two weeks of using the users interface, we should ask them how they are doing?

![image](https://user-images.githubusercontent.com/1142830/140246652-5665aa3a-bbe2-4852-aa65-10d752074cfd.png)

(3)

When they get a major/minor version (not patches), we should signpost the blog to point out the new version and its features.

```

            You've just upgraded to v3.2. Did you know about???

 * HTTP template for making fast HTTP request-
 * Multi-cluster for running workflows that span clusters/namespaces

[ Show me all the new features ] [ Dismiss ] [ Never show this again ] 
```

**Comment by alexec** [comment]
@rbreeze thoughts?

**Comment by rbreeze** [comment]
I really like both ideas, especially getting feedback from users about their experience. One note is, I believe this would require "phoning home" which may pose an issue. 

The navigation piece of this, though, seems easy enough to implement and it would be a nice user experience.

**Comment by alexec** [comment]
I think we need to do this without in-app telemetry, otherwise operators will want to disable it.

I thought each icon could lead to a page on the docs, which in turn have Google Analytics.

![image](https://user-images.githubusercontent.com/1142830/140256789-4f95bf0c-ce5a-46b9-a1e4-9a88401ea6fb.png)

**Comment by edlee2121** [comment]
We would only phone home if they want to share their feedback. I think that is fine.
