### ISSUE TITLE
Sidecar container exits with non-zero exit status when the pod completes.

### ISSUE THREAD

**Issue by gpanagiotidis** [argoproj/argo-workflows#7164]
## Summary

Running a workflow with a postfix sidecar container, results the container to exit with a non-zero exit status. Although this behavior is expected by argo workflows which reports the workflow as completed successfully, kubernetes reports the pod as in Error state. This causes problem with other components installed in the cluster, for example alert manager, prometheus etc.

I am using:
Argo Workflows version 3.2.0
Kubernetes version 1.21.1
Executor: PNS

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
More information needed:

* What sidecar are you running?
* What error messages is returned to stderr/exit code/container status.

**Comment by gpanagiotidis** [comment]
## What sidecar are you running?

I am running a postfix sidecar container along my main container in order to send logs by email.

`      sidecars:
      - image: gitlab-registry.cern.ch/jeedy/utils/postfix-docker/postfix:1.3
        imagePullPolicy: Always
        name: email
        command: ["/root/start.sh"]
`

## What error messages is returned to stderr/exit code/container status.

The email container exits with:

`
  email:
    Container ID:  containerd://c538d4849fd829c1123fc999f42c72b2561e1dd1185827f8d29a403e6a28315d
    Image:         gitlab-registry.cern.ch/jeedy/utils/postfix-docker/postfix:1.3
    Image ID:      gitlab-registry.cern.ch/jeedy/utils/postfix-docker/postfix@sha256:dc80e9baca0c8d9ca048966e98f286f2032f05f7fee8d14f0fe6593da0b44672
    Port:          <none>
    Host Port:     <none>
    Command:
      /root/start.sh
    State:          Terminated
      Reason:       Error
      Exit Code:    143
      Started:      Fri, 05 Nov 2021 09:01:13 +0100
      Finished:     Fri, 05 Nov 2021 09:08:10 +0100
    Ready:          False
    Restart Count:  0
`

Logs from the container:

`
2021-11-05T09:01:13.514766+01:00 test-node-scanner-jtdzm rsyslogd:  [origin software="rsyslogd" swVersion="8.24.0-52.el7_8.2" x-pid="76" x-info="http://www.rsyslog.com"] start
2021-11-05T09:01:13.910374+01:00 test-node-scanner-jtdzm postfix/postfix-script[135]: warning: group or other writable: /etc/postfix/./main.cf
2021-11-05T09:01:13.922826+01:00 test-node-scanner-jtdzm rsyslogd: action 'action 2' suspended, next retry is Fri Nov  5 09:01:43 2021 [v8.24.0-52.el7_8.2 try http://www.rsyslog.com/e/2007 ]
2021-11-05T09:01:13.950078+01:00 test-node-scanner-jtdzm postfix/postfix-script[151]: starting the Postfix mail system
Nov  5 09:01:13 test-node-scanner-jtdzm postfix/postfix-script[135]: warning: group or other writable: /etc/postfix/./main.cf
Nov  5 09:01:13 test-node-scanner-jtdzm postfix/postfix-script[151]: starting the Postfix mail system
2021-11-05T09:01:13.976201+01:00 test-node-scanner-jtdzm postfix/master[153]: daemon started -- version 2.10.1, configuration /etc/postfix
Nov  5 09:01:13 test-node-scanner-jtdzm postfix/master[153]: daemon started -- version 2.10.1, configuration /etc/postfix
`

Logs from the wait container:

`
time="2021-11-05T08:00:49.954Z" level=info msg="Starting Workflow Executor" executorType=pns version=v3.2.0
time="2021-11-05T08:00:49.960Z" level=info msg="Creating a pns executor"
time="2021-11-05T08:00:49.960Z" level=info msg="Initialized PNS executor (namespace: dbjeedy-ns, pod: test-node-scanner-jtdzm, pid: 36)"
time="2021-11-05T08:00:49.960Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=dbjeedy-ns podName=test-node-scanner-jtdzm template="{\"name\":\"job\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"gitlab-registry.cern.ch/jeedy/utils/internal-jobs-image:merge_all_scripts\",\"command\":[\"/opt/jeedy_kubernetes/jobs/shared-vars-entrypoint.sh\"],\"env\":[{\"name\":\"USER_COMMAND\",\"value\":\"sh /opt/scripts/check_status_nodes.sh\"},{\"name\":\"JOB_NAME\",\"value\":\"test-node-scanner\"},{\"name\":\"JSONFILE\",\"value\":\"test-jobs.json\"}],\"resources\":{},\"volumeMounts\":[{\"name\":\"entrypoint\",\"mountPath\":\"/opt/jeedy_kubernetes/jobs\"},{\"name\":\"sharedsecrets\",\"mountPath\":\"/ORA/dbs01/syscontrol/projects/systools/etc/\"},{\"name\":\"sharedsyscontrol\",\"mountPath\":\"/ORA/dbs01/syscontrol/etc/json\"},{\"name\":\"jsonfile\",\"mountPath\":\"/opt/jeedy_kubernetes/jsonfile\"}],\"imagePullPolicy\":\"Always\"},\"initContainers\":[{\"name\":\"init\",\"image\":\"gitlab-registry.cern.ch/jeedy/utils/internal-jobs-image:latest\",\"command\":[\"/opt/jeedy_kubernetes/jobs/init-entrypoint.sh\"],\"resources\":{},\"volumeMounts\":[{\"name\":\"mastersecret\",\"mountPath\":\"/opt/jeedy_kubernetes/jobs/mastersecret\"},{\"name\":\"sharedsecrets\",\"mountPath\":\"/ORA/dbs01/syscontrol/projects/systools/etc/\"},{\"name\":\"init-entrypoint\",\"mountPath\":\"/opt/jeedy_kubernetes/jobs\"},{\"name\":\"init-config\",\"mountPath\":\"/opt/jeedy_kubernetes/jobs/config/\"},{\"name\":\"sharedsyscontrol\",\"mountPath\":\"/ORA/dbs01/syscontrol/etc/json\"}]}],\"sidecars\":[{\"name\":\"email\",\"image\":\"gitlab-registry.cern.ch/jeedy/utils/postfix-docker/postfix:1.3\",\"command\":[\"/root/start.sh\"],\"resources\":{},\"imagePullPolicy\":\"Always\"}],\"activeDeadlineSeconds\":1200,\"metrics\":{\"prometheus\":[{\"name\":\"custom_status\",\"labels\":[{\"key\":\"status\",\"value\":\"{{status}}\"},{\"key\":\"workflow_name\",\"value\":\"test-node-scanner-jtdzm\"},{\"key\":\"job_name\",\"value\":\"test-node-scanner\"},{\"key\":\"workflow_namespace\",\"value\":\"dbjeedy-ns\"},{\"key\":\"user_community\",\"value\":\"JEEDY\"},{\"key\":\"cluster\",\"value\":\"k8s-ims-batch-prod-multi-v21\"}],\"help\":\"My custom status metric\",\"counter\":{\"value\":\"1\"}},{\"name\":\"custom_job_status\",\"labels\":[{\"key\":\"job_name\",\"value\":\"test-node-scanner\"},{\"key\":\"workflow_namespace\",\"value\":\"dbjeedy-ns\"},{\"key\":\"user_community\",\"value\":\"JEEDY\"},{\"key\":\"cluster\",\"value\":\"k8s-ims-batch-prod-multi-v21\"}],\"help\":\"My gauge status metric\",\"when\":\"{{status}} == Failed || {{status}} == Error\",\"gauge\":{\"value\":\"0\",\"realtime\":null}},{\"name\":\"custom_job_status\",\"labels\":[{\"key\":\"job_name\",\"value\":\"test-node-scanner\"},{\"key\":\"workflow_namespace\",\"value\":\"dbjeedy-ns\"},{\"key\":\"user_community\",\"value\":\"JEEDY\"},{\"key\":\"cluster\",\"value\":\"k8s-ims-batch-prod-multi-v21\"}],\"help\":\"My gauge status metric\",\"when\":\"{{status}} == Succeeded\",\"gauge\":{\"value\":\"1\",\"realtime\":null}},{\"name\":\"custom_execution_duration\",\"labels\":[{\"key\":\"job_name\",\"value\":\"test-node-scanner\"},{\"key\":\"workflow_namespace\",\"value\":\"dbjeedy-ns\"},{\"key\":\"workflow_name\",\"value\":\"test-node-scanner-jtdzm\"},{\"key\":\"user_community\",\"value\":\"JEEDY\"},{\"key\":\"cluster\",\"value\":\"k8s-ims-batch-prod-multi-v21\"}],\"help\":\"My duration metric\",\"gauge\":{\"value\":\"{{duration}}\",\"realtime\":true}},{\"name\":\"custom_memory_resource_duration\",\"labels\":[{\"key\":\"job_name\",\"value\":\"test-node-scanner\"},{\"key\":\"workflow_namespace\",\"value\":\"dbjeedy-ns\"},{\"key\":\"workflow_name\",\"value\":\"test-node-scanner-jtdzm\"},{\"key\":\"user_community\",\"value\":\"JEEDY\"},{\"key\":\"cluster\",\"value\":\"k8s-ims-batch-prod-multi-v21\"}],\"help\":\"My memory metric\",\"gauge\":{\"value\":\"{{resourcesDuration.memory}}\",\"realtime\":null}},{\"name\":\"custom_cpu_resource_duration\",\"labels\":[{\"key\":\"job_name\",\"value\":\"test-node-scanner\"},{\"key\":\"workflow_namespace\",\"value\":\"dbjeedy-ns\"},{\"key\":\"workflow_name\",\"value\":\"test-node-scanner-jtdzm\"},{\"key\":\"user_community\",\"value\":\"JEEDY\"},{\"key\":\"cluster\",\"value\":\"k8s-ims-batch-prod-multi-v21\"}],\"help\":\"My cpu metric\",\"gauge\":{\"value\":\"{{resourcesDuration.cpu}}\",\"realtime\":null}}]}}" version="&Version{Version:v3.2.0,BuildDate:2021-10-12T15:25:27Z,GitCommit:a29495bb5b4aedcbd8fa7bc433c1bccbc374e6d1,GitTag:v3.2.0,GitTreeState:clean,GoVersion:go1.16.9,Compiler:gc,Platform:linux/amd64,}"
time="2021-11-05T08:00:49.961Z" level=info msg="Starting deadline monitor"
time="2021-11-05T08:00:54.986Z" level=info msg="Watch pods 200"
time="2021-11-05T08:01:13.122Z" level=info msg="secured root for pid 53 root: runc:[2:INIT] (\"/proc/53/root\")"
time="2021-11-05T08:01:13.123Z" level=info msg="mapped container name \"pid/53\" to pid 53"
time="2021-11-05T08:01:13.174Z" level=info msg="secured root for pid 53 root: shared-vars-ent (\"/proc/53/root\")"
time="2021-11-05T08:01:13.174Z" level=info msg="mapped container name \"main\" to pid 53"
time="2021-11-05T08:05:49.961Z" level=info msg="Alloc=4515 TotalAlloc=25242 Sys=73297 NumGC=9 Goroutines=8"
time="2021-11-05T08:08:10.814Z" level=info msg="Main container completed"
time="2021-11-05T08:08:10.814Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2021-11-05T08:08:10.814Z" level=info msg="No output parameters"
time="2021-11-05T08:08:10.814Z" level=info msg="No output artifacts"
time="2021-11-05T08:08:10.816Z" level=info msg="Killing sidecars [\"email\"]"
time="2021-11-05T08:08:10.831Z" level=info msg="Get pods 200"
time="2021-11-05T08:08:10.836Z" level=info msg="Sending SIGTERM to pid 67"
time="2021-11-05T08:08:11.837Z" level=info msg="PID 67 completed"
time="2021-11-05T08:08:11.837Z" level=info msg="Alloc=5385 TotalAlloc=26116 Sys=73297 NumGC=10 Goroutines=7"
`

**Comment by alexec** [comment]
I'm not sure what is happening here. The `wait` container does not appear to be killing PID 53 (the "email" sidecar). However, exit code can happen when you receive SIGKILL, not SIGTERM.

Container processes on Kubernetes must gracefully handle SIGTERM. I can see you're running a shell script, and scripts rarely correctly handle SIGTERM. Try addressing that, reading material that should help:

https://tasdikrahman.me/2019/04/24/handling-singals-for-applications-in-kubernetes-docker/
