### ISSUE TITLE
Adding resource status check retry and timeout setting

### ISSUE THREAD

**Issue by AlexChenSkyBlue** [argoproj/argo-workflows#7179]
# Summary

What change needs making?
right now， when argo workflow create resource. it will try to using k8s api server to check resource status. but it has fixed 32s timeout withour retry. if there are any network issue during this period. it will fail as below

Error (exit code 1): Get "https://10.233.0.1:443/apis/kubeflow.org/v1/namespaces/training/mpijobs/mpimulti-m6knf?timeout=32s": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
# Use Cases
When would you use this?
we using argo to create multiple resources such as k8s job. 
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
You can use TRANSIENT_ERROR_PATTERN to add additional errors that can be retried.
