### ISSUE TITLE
multi-controllers cause empty metrics from workflow-controller-metrics service

### ISSUE THREAD

**Issue by book987** [argoproj/argo-workflows#7188]
## Summary

Our controller have 2 replicas, and our Prometheus fetch metrics through service workflow-controller-metrics. And now we're getting wrong metrics value with 50% probability because the same-name workflow-controller-metrics include the stand-by controller pod.

Fetching metrics through all pods might be a workaround, but this metrics service will stay crash for multi-controllers.

Here's the results through service:
![image](https://user-images.githubusercontent.com/17219814/140890351-d1555754-31dd-492c-b0b5-9bee720c0900.png)

Here's some other things:
```
λ k get pods -n argo -lapp=workflow-controller
NAME                                  READY   STATUS    RESTARTS   AGE
workflow-controller-d569df89c-kjkd8   1/1     Running   0          4d21h
workflow-controller-d569df89c-vpv5q   1/1     Running   0          4d21h
λ k get endpoints workflow-controller-metrics -n argo
NAME                          ENDPOINTS                                AGE
workflow-controller-metrics   10.xxx.xxx.xxx:9090,10.xxx.xxx.xxx:9090   333d
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Hmm. You can't ever really collect Prometheus metrics from a service, because metrics are specific to the pod, you don't know which pod's metric you'll get. You should only get them directly from the pod. 

I'm not sure we should even run the service.

**Comment by book987** [comment]
> Hmm. You can't ever really collect Prometheus metrics from a service, because metrics are specific to the pod, you don't know which pod's metric you'll get. You should only get them directly from the pod.
> 
> I'm not sure we should even run the service.

Got it, you're right. Thanks!
