### ISSUE TITLE
Workflows spawned from WorkflowTemplates have no ownerReferences

### ISSUE THREAD

**Issue by mf-lit** [argoproj/argo-workflows#7192]
# Summary

Workflows spawned from WorkflowTemplates have no ownerReferences

(v3.2.0)

# Diagnosis

We use ArgoCD to deploy/manage our WorkflowTemplates, but because the Workflows spawed from those WorkflowTemplates don't have ownerReferences, those spawned Workflows don't appear in ArgoCD UI. That's our use-case, though I think having ownerReferences would be correct practice regardless.

As a reference, Workflows spawned from CronWorkflows **do** have ownerReferences in their metadata (and therefore do appear in the ArgoCD UI).

<details>
<summary><code>Example of metadata from a CronWorkflow</code></summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: exampleworkflow-1636452120
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: CronWorkflow
    name: exampleworkflow
    uid: c78f9864-1710-4b5b-aac3-05a9d85fed26
  resourceVersion: "250150533"
  uid: c3cb3156-2e19-4ea3-b24b-769e9ce5c2e6
```

</details>

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by mf-lit** [comment]
Not to go out-of-scope too much, but speaking of enhancements, do you think there's any potential of using ownerReferences as a way to reveal more in the Argo Workflows UI itself?

So if any resources (not explicitly part of the workflow) are marked as _owned by_ this `Workflow`, `container`, or `resource` they also show up as elements in the workflow graph.

In our particular use-case, we use a Workflow to create a `SparkApplication` resource, which in turn creates multiple pods. It would be very convenient to see and explore these directly from the Workflows graph UI.

**Comment by terrytangyuan** [comment]
Some kind of resource tree similar to Argo CD would be useful here.

**Comment by sarabala1979** [comment]
> Interesting. This makes a lot of sense the me. I'm not sure I'd class it as a bug but as an enhancement.

I think this is enhancement. it should be based on a flag to enable set ownreference. 

 `WorkflowTemplate` is more like a definition (template storage) object. When we create a workflow, the controller will copy the content into the workflow in `storedWorkflowSpec`. I don't think there needs to be OwnerReference for this. In other cases, both objects are running objects and that object controller is creating a child objects and keeping track of the child execution. 

@jessesuen what is your thought?

**Comment by simster7** [comment]
I agree with @sarabala1979 thinking.

Something to consider: if we set the WorkflowTemplate as the ownerReference of a Workflow, when a WorkflowTemplate is deleted K8s will delete all respective Workflows by default. I don't think this is desired behavior if we consider WorkflowTemplates as definitions, and if the controller copies content to a Workflow, there really is no "dependency" anymore.

If something like this is implemented, it should be strictly opt-in with a warning provided.

**Comment by simster7** [comment]
I think the CronWorkflow -> Workflow dependency is a bit stronger: you create a CronWorkflow with the full expectation that it will itself spawn Workflows. With WorkflowTemplates, you create a WorkflowTemplate and then in the future – in a separate action – you create some Workflows that reference (maybe just a subset) of a WorkflowTemplate.

**Comment by alexec** [comment]
I agree with Simon. I actually don’t think this is ownership relationship.

**Comment by mf-lit** [comment]
> Something to consider: if we set the WorkflowTemplate as the ownerReference of a Workflow, when a WorkflowTemplate is deleted K8s will delete all respective Workflows by default.

I hadn't thought of this. I now agree, there shouldn't be ownership.

I'm happy to close this, but I also think I'd like to open a new enhancement request asking for more to be revealed in the Argo-Workflows UI....

>Not really. The API are not generic, they only know about certain kinds of resource (Pod, Workflow etc), even if they did, the underlying Kubernetes API do not provide any method (AFAIK) to list objects owed by this object.

I see what you mean, but I'm curious then how ArgoCD does it so effectively?...

**Comment by alexec** [comment]
> I see what you mean, but I'm curious then how ArgoCD does it so effectively?...

Argo CD does this:

* Dear Kubernetes, tell me about every single API resource you have.
* Now create a list/watch for each of those.
* Now I know everything!

**Comment by alexec** [comment]
Won't fix.

**Comment by caspereijkens** [comment]
> I hadn't thought of this. I now agree, there shouldn't be ownership.

@alexec
Why shouldn't there be an ownership? In case of a failure, a WorkflowTemplate keeps rescheduling its Workflows. This can flood the cluster with new pods all stuck in pending. We would like to be able to manage these workflows. Ownership would be ideal because you could remove all those Workflows in one go.
