### ISSUE TITLE
Limit Cronworkflow Runtime count

### ISSUE THREAD

**Issue by sundbing** [argoproj/argo-workflows#7201]
# Summary

Add a Max counter to the cronworkflowtemplate that is limiting the amount of reschedules and allows to run a workflow for the given number of Times on a cron schedule. 

# Use Cases

Current cronworkflows are running infint till it is removed. That way running a scheduled workflow one time or a fixed amount of times isn't easy to implement. 
E.g. Run a workflow every hour but only 10 times. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by NikeNano** [comment]
I would be happy to help out with this @simster7 if you haven't started the work?

**Comment by simster7** [comment]
Actually, I'll take this one. I have some ideas with how to fit this request into a bigger feature I'm thinking about

**Comment by eduardodbr** [comment]
closed by #12305
