### ISSUE TITLE
Wait container stuck in a loop while main container finished successfully

### ISSUE THREAD

**Issue by avifried1** [argoproj/argo-workflows#7213]
not sure why this was closed, the issue hasn't been solved - it has been circumvented by using k8sapin executor. Using the default Docker executor still has this issue.

_Originally posted by @avifried1 in https://github.com/argoproj/argo-workflows/issues/6115#issuecomment-881783449_

**Comment by gastonborba** [comment]
I have the same error with cluster install.

**Comment by alexec** [comment]
Duplicate of #7224 ?
