### ISSUE TITLE
Github Sunset public key prevents artifact cloning

### ISSUE THREAD

**Issue by jccarte** [argoproj/argo-workflows#7225]
## Summary

As of November 16, 2021 we are no longer able to clone github repositories as artifiacts without setting `insecureIgnoreHostKey: true` It appears that the go tests pass on master at least. So it could be fixed in the go-git changes that are in master but not in any of the official releases

[Github Sunset Announcement](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints)

What version of Argo Workflows are you running? 3.1.8

## Diagnostics

Logs from the argoexec init container:

```
time="2021-11-16T18:20:27.183Z" level=error msg="executor error: artifact git-repo failed to load: ssh: handshake failed: knownhosts: key mismatch"
time="2021-11-16T18:20:27.183Z" level=info msg="Alloc=4485 TotalAlloc=9777 Sys=74833 NumGC=4 Goroutines=3"
time="2021-11-16T18:20:27.183Z" level=fatal msg="artifact git-repo failed to load: ssh: handshake failed: knownhosts: key mismatch"
```

Also running the go tests fail for both 3.2.3 and 3.1.8

```bash
➜  argo-workflows git:(e5dc961b7) ✗ make test | grep "FAIL"
--- FAIL: TestGitArtifactDriverLoad_SSL (0.01s)
    --- FAIL: TestGitArtifactDriverLoad_SSL/Insecure (0.00s)
    --- FAIL: TestGitArtifactDriverLoad_SSL/Secure (0.00s)
    --- FAIL: TestGitArtifactDriverLoad_SSL/Insecure#01 (0.00s)
    --- FAIL: TestGitArtifactDriverLoad_SSL/Secure#01 (0.00s)
FAIL
FAIL	github.com/argoproj/argo-workflows/v3/workflow/artifacts/git	11.484s
FAIL
make: *** [test] Error 1
```

What Kubernetes provider are you using?
GKE
What executor are you running? PNS

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by jccarte** [comment]
Running argo-workflows against latest appears to also have this issue. So it might not be relevant that tests are passing on master afterall.

**Comment by jccarte** [comment]
running ./update-ssh-known-hosts.sh and creating a new argoexec image appears to take care of the issue.

**Comment by prein** [comment]
Would it be possible to manipulate known_hosts file globaly, in a config map, like it's done with ArgoCD?
Any chance hardcoding the know_hosts file in the argoexec container can be avoided?

I guess a temporary workaround could also be running `ssh-keyscan github.com gitlab.com bitbucket.org ssh.dev.azure.com vs-ssh.visualstudio.com | sort -u >> /etc/ssh/ssh_known_hosts` (which is what `update-ssh-known-hosts.sh` does) as part of the task.

**Comment by tcolgate** [comment]
Can also confirm. Running `hack/update-ssh-known-hosts.sh`, run `make argoexec-image`, then reconfigured worfkflow controller to use the new image, and all is now well.

**Comment by tcolgate** [comment]
I'd also +1 for making known hosts configurable.

**Comment by terrytangyuan** [comment]
FYI https://github.com/argoproj/argo-workflows/pull/7226 is trying to fix this.

**Comment by alexec** [comment]
@sarabala1979 this issue has 44x 👍 in just 1 day. Please back port to both v3.1 and v3.2. I think this is urgent for most users.

**Comment by alexec** [comment]
v3.1.x released (just this fix)
v3.2.x being released (many fixes)
