### ISSUE TITLE
Improve taskset/HTTP template logging

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7243]
A lot of the logging for taskset/http template logs the Go object, which results in log lines that are (a) not very human readable and (b) not very machine readable, therefore less helpful that they could be:

Example:

```
             controller | time="2021-11-17T18:01:51.237Z" level=debug msg="patching the exiting taskset" TaskSet="map[controller-plugin-template-qj4gt:{main {[] []} {[] [] <nil> <nil>} map[] nil {map[] map[]} <nil> [] nil nil nil nil nil nil nil nil 0xc0005b5308 [] [] [] nil <nil> nil <nil> <nil> []   <nil>  <nil> nil [] nil  nil nil nil }]" namespace=argo workflow=controller-plugin-template-qj4gt
```

We could log the JSON of the object, but that's not machine readable. Better to just be structured.

**Comment by alexec** [comment]
@sarabala1979 could ask you to own this please?

**Comment by sarabala1979** [comment]
I will take it

**Comment by alexec** [comment]
@sarabala1979 I'm going to pick this up:

1. I have a clear idea of what changes I want
2. It'll take about 1h for me to do.
3. This is blocker for the plugins.
