### ISSUE TITLE
Update the generated Python package name to be "argo-workflows"

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#7248]
# Summary

Currently this is called "openapi_client". We'd like to rename it to be "argo-workflows" before publishing.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
@flaviuvadan volunteered to take this.

**Comment by alexec** [comment]
I'm not able to assign @flaviuvadan for some reason.

**Comment by terrytangyuan** [comment]
Perhaps because he's not a member of the argoproj org.

**Comment by flaviuvadan** [comment]
We can close this one @terrytangyuan!
