### ISSUE TITLE
Argo Workflow SSO not working with Azure Active Directory B2C

### ISSUE THREAD

**Issue by sky29** [argoproj/argo-workflows#7250]
## Summary
We are trying to integrate Argo Workflow SSO with Azure Active Directory B2C. But it is not working. Though We are able to integrate this with Keycloak perfectly.

Version of Argo Workflow we are using: v3.1.2

## Diagnostics
With Keycloak our argo-workflow configmap (workflow-controller-configmap) looks like below, which is working perfectly fine.
```yaml
kubectl get cm workflow-controller-configmap -n argo -o yaml

apiVersion: v1
kind: ConfigMap
data:
  ...
  sso: |
    issuer: https://<keycloak-base-url>/auth/realms/<realm-name>
    clientId:
      name: argo-sso
      key: clientID
    clientSecret:
      name: argo-sso
      key: clientSecret
    redirectUrl: https://<argo-base-url>/oauth2/callback
```

But if I try to modify same with Azure Active Directory B2C url like below, it is not working:

```yaml
kubectl get cm workflow-controller-configmap -n argo -o yaml

sso: |
    issuer: https://<b2c-domain>.b2clogin.com/<azure-ad-b2c-tenant-id>/v2.0/
    clientId:
      name: argo-sso
      key: clientID
    clientSecret:
      name: argo-sso
      key: clientSecret
    redirectUrl: https://<argo-base-url>/oauth2/callback
```

We are following below documentation as reference (search for SSO): https://argoproj.github.io/argo-workflows/workflow-controller-configmap.yaml

We also checked with Microsoft Team & Azure B2C side we are able to run sample userflows (https://jwt.ms/) & verify authentication token also. So our understanding is Azure B2C configuration looks good, but somehow "Argo Workflow Integration with Azure B2C" not working.

Can anyone please help, it is a blocker for us.

What Kubernetes provider are you using? --> Azure Kubernetes Service (AKS)

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary --> K8SAPI

```bash
# Logs from the argo server:
kubectl logs argo-server-56f94b844b-8hz9f -n argo

time="2021-11-18T20:50:15.335Z" level=debug msg="CLI version" version="{v3.1.2 2021-07-15T21:17:57Z 98721a96eef8e4fe9a237b2105ba299a65eaea9a v3.1.2 clean go1.15.7 gc linux/amd64}"
I1118 20:50:15.336171       1 merged_client_builder.go:121] Using in-cluster configuration
I1118 20:50:15.336427       1 merged_client_builder.go:163] Using in-cluster namespace
time="2021-11-18T20:50:15.337Z" level=info authModes="[sso client]" baseHRef=/ managedNamespace= namespace=argo secure=false
time="2021-11-18T20:50:15.337Z" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argoproj.github.io/argo-workflows/tls/"
time="2021-11-18T20:50:15.337Z" level=info msg="config map" name=workflow-controller-configmap
I1118 20:50:15.364978       1 round_trippers.go:444] GET https://192.168.0.1:443/api/v1/namespaces/argo/configmaps/workflow-controller-configmap 200 OK in 27 milliseconds
I1118 20:50:15.374213       1 round_trippers.go:444] GET https://192.168.0.1:443/api/v1/namespaces/argo/secrets/argo-sso 200 OK in 4 milliseconds
Error: 404 Not Found: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
Usage:
  argo server [flags]
404 Not Found: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

Examples:
See https://argoproj.github.io/argo-workflows/argo-server.md

```

**Comment by alexec** [comment]
Your logs say you did not create the secret.

**Comment by sky29** [comment]
@alexec  We already have secret in place, something like below:

`kubectl get secret argo-sso -n argo -o yaml

apiVersion: v1
data:
  clientID: azure-b2c-app-registration-client-id-base64-enncrypted
  clientSecret: azure-b2c-app-registration-client-secret-base64-enncrypted
kind: Secret
metadata
  name: argo-sso
  namespace: argo
type: Opaque
`

**Comment by alexec** [comment]
```
Error: 404 Not Found: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
Usage:
  argo server [flags]
404 Not Found: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

```

???

**Comment by sky29** [comment]
Yes, we saw "404 Not Found: error", but we couldn't able to figure that out why is it throwing ? ..... same configuration is working fine for us with Keycloak.

Second thing when we were discussing with Microsoft Team, they asked question: if "issuer" configuration (in workflow-controller-configmap) is enough?, because somewhere we need to plug Azure B2C "UserFlow" or "CustomPolicy" in argo configuration side ...... which we didn't find anywhere in the argo documentation ?

**Comment by alexec** [comment]
I don't know what "UserFlow" or "CustomPolicy" are, so these are presumably Azure things. Argo Workflows is vanilla Outh, and we don't support these. However, many users have success using Dex for non-vanilla providers:

https://dexidp.io/docs/connectors/microsoft/

We use it for Github ourselves: 

https://github.com/argoproj/argoproj-deployments/tree/master/dex

**Comment by tiwarisanjay** [comment]
@sky29  Were you able to solve this ?

**Comment by tiwarisanjay** [comment]
@alexec  How the config.yaml looks like in your configmap  `dex` ? Thats where I am having trouble as issuer url is throwing 404 not found error. I am sure you know this issue. :) Really appreciate your help
