### ISSUE TITLE
Distribute more secure and lightweight docker images with docker-slim

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#7253]
# Summary

What change needs making?

Switch to use docker-slim for image building. https://github.com/docker-slim/docker-slim

# Use Cases

When would you use this?

I liked the security part of it in particular. Here's what it claims:
>  docker-slim will optimize and secure your containers by understanding your application and what it needs using various analysis techniques. It will throw away what you don't need, reducing the attack surface of your container.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
We've made a lot of changes in the last year to improve the security of our published images:

* Use Snyk for image scanning.
* Switch to Alpine base image for the executor.
* Controller and server do not run as root anymore.
* Deprecation of the Docker executor.

I think we're in a good place today, but security best practices change overtime, so this might be the right thing tomorrow.

Any thoughts on how this works with image scanning? Does it make that harder to do?

**Comment by terrytangyuan** [comment]
I don't have any experience with docker-slim personally so I'll defer that to others to answer.
