### ISSUE TITLE
argo-workflows with java container

### ISSUE THREAD

**Issue by naveenc** [argoproj/argo-workflows#7265]
### Discussed in https://github.com/argoproj/argo-workflows/discussions/7264

<div type='discussions-op-text'>

<sup>Originally posted by **naveenc** November 23, 2021</sup>
Hi ,
I need some help to find the java logs 
I created a java project which just has a main method and which prints an message. 
public static void main(String[] args) throws IOException {
            System.out.println("*****************Hello world ******************");
    }
Created the docket image and deployed as a Cron workflow using below template.

apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cron-wf
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: example
    templates:
    - name: example
      container:
        image: docker-java:1.0
        command: [sh, -c]
        args: ["date; sleep 9"]

The workflow is triggered and running successfully But i am not able to figure out the message 
"*****************Hello world ******************"

Could you please help where do i find this . I verified in main,init and wait logs

Actually my use-case is using cron worklow i will ready the nats message and push to time series DB

</div>

**Comment by alexec** [comment]
Duplicates discussion.
