### ISSUE TITLE
v3.4 turn on experimental features

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7267]
In environment-variables.md, enable ones that were opt-in in v3.2.

When complete, create new issue for v3.5.

https://argoproj.github.io/argo-workflows/environment-variables/

- [x] #7279
- [x] #8592

**Comment by terrytangyuan** [comment]
Which features will we be turning on?

**Comment by alexec** [comment]
not sure, need to look at doc when time comes

**Comment by terrytangyuan** [comment]
This should be kept open for discussion but not necessarily targeting for v3.4.
