### ISSUE TITLE
Wrong version in manisfest

### ISSUE THREAD

**Issue by guillaumBrisard** [argoproj/argo-workflows#7282]
## Summary

I used kustomize to install Argo
https://github.com/argoproj/argo-workflows/tree/master/manifests#kustomize

With 3.0, the tag version was correct
https://github.com/argoproj/argo-workflows/blob/v3.0.10/manifests/base/workflow-controller/workflow-controller-deployment.yaml#L17

After it was wrong, always latest's tag 
https://github.com/argoproj/argo-workflows/blob/v3.2.4/manifests/base/workflow-controller/workflow-controller-deployment.yaml#L17

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
@sarabala1979 There is an error in the release process?

**Comment by sarabala1979** [comment]
you can get it from release page.  https://github.com/argoproj/argo-workflows/releases/download/v3.2.4/install.yaml

**Comment by guillaumBrisard** [comment]
So now, we have to update the version according to your release version when we use your manifest before kustomization ?
If so, it will be good to add it to this doc
https://github.com/argoproj/argo-workflows/tree/master/manifests#kustomize
