### ISSUE TITLE
Expose workflow.labels and workflow.annotations as JSON string

### ISSUE THREAD

**Issue by scravy** [argoproj/argo-workflows#7289]
# Summary

It is possible to access individual parameters, labels, or annotations from within a workflow via

- `workflow.parameters.<NAME>`,
- `workflow.labels.<NAME>`,
-  and `workflow.annotations.<NAME>` respectively.

It is also possible to get all parameters as a JSON string:

- `workflow.parameters`

It would be great if also labels and annotations could be exposed that way:

- `workflow.labels`
- `workflow.annotations`

# Use Cases

I have for instance some default templates in the configuration of the controller which I would like to control via the labels/annotations on the particular workflows. Also it would be nice to introspect labels like `submitted from ui` or `cron workflow` for complex workflows that spawn other workflows (they generate names based on this and there are notifications in our system which are confusing if they all look the same which I would like to control via the labels).

It would be nice to have all labels exposed that way as this allows argo lint to still validate references to missing variables. Also good to just hook them into a python script step for instance and then deal with that.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by sarabala1979** [comment]
@scravy it is a good enhancement. Do you. like to submit the PR for this enhancement?

**Comment by scravy** [comment]
@sarabala1979 Thank you for pointing out the appropriate place in the code. I'll give it a try over the weekend!

**Comment by sarabala1979** [comment]
@scravy if you have too many on your plate. We have a new team member. He can help with this.
Please let me know it is ok to you

**Comment by scravy** [comment]
Sure, that's okay.

**Comment by sarabala1979** [comment]
@dpadhiar Please take this issue
