### ISSUE TITLE
Mentoring

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7307]
We would like to support new contributors with mentoring. This would probably need to be lead by the main contributors:

@sarabala1979 @alexec @terrytangyuan etc

**Comment by simster7** [comment]
Also happy to help here

**Comment by terrytangyuan** [comment]
Happy to help mentor new contributors. Some programs to consider unless we are organizing this ourselves:
* https://github.com/cncf/mentoring
* https://summerofcode.withgoogle.com/archive/

**Comment by alexec** [comment]
It seems we have some summer programs for newer programmers to learn to code. I wonder what our scope should be? 

I was initially planning on a short term mentorship, i.e the mentor helps the mentee get started with coding, learning the code base, fixing and issue or implementing a feature, getting it reviewed and approved and merged. 

Maybe there are other interpretations.

**Comment by alexec** [comment]
https://jisajournal.springeropen.com/articles/10.1186/s13174-021-00140-z

**Comment by softwarebloat** [comment]
> It seems we have some summer programs for newer programmers to learn to code. I wonder what our scope should be?
> 
> I was initially planning on a short term mentorship, i.e the mentor helps the mentee get started with coding, learning the code base, fixing and issue or implementing a feature, getting it reviewed and approved and merged.
> 
> Maybe there are other interpretations.

Yes that was exactly my point when asking on slack and I would love that! 
But maybe there are other needs too?

**Comment by terrytangyuan** [comment]
> It seems we have some summer programs for newer programmers to learn to code. I wonder what our scope should be?

Just to clarify. The students in those programs may not be new programmers. Although they maybe new to open source contributions. For Google Summer of Code (GSoC), for example, it's up to the project maintainers to decide whether to provide a few project ideas and then the students (applicants) will be drafting proposals either based on those ideas or their own ideas. Upon completion of project by the selected students, they will get paid. The mentorship lasts for one summer. 
> I was initially planning on a short term mentorship, i.e the mentor helps the mentee get started with coding, learning the code base, fixing and issue or implementing a feature, getting it reviewed and approved and merged.
> 
> Maybe there are other interpretations.

I just wanted to throw some ideas there but not necessarily a preference. What you mentioned here sounds great and requires less communication overhead. From my past experience with GSoC, there will be a lot of communication overhead to participate the program and select students but the benefit is that the project gets more public exposure and the quality of participants is high with commitment and incentive.

**Comment by terrytangyuan** [comment]
My opinion is very biased since I've done mentoring three times so it would be great to hear from others too.

Argo will first need to apply to be a mentor organization and wait until accepted. The timeline is still TBD: https://developers.google.com/open-source/gsoc/timeline.
