### ISSUE TITLE
archiveTTL not respected ?

### ISSUE THREAD

**Issue by christopheblin** [argoproj/argo-workflows#7333]
## Summary

What happened/what you expected to happen?

In the configmap, I set persisntece.archiveTTL to 60d (the line was previously commented in my configmap)

I then restarted the pods with `k rollout restart deployment workflow-controller` and `k rollout restart deploy argo-server`

However, in my db, I still have rows in argo_archived_workflows older than 60d and I still have log files in my artifactRespoitory

-> Did I miss something when I reconfigured ? How can I see what config argo has loaded in order to check ?

Another question : will the archiveTTL also clean the artifact repository because I have archiveLogs: true in the artifactRespoitory section ?

What version of Argo Workflows are you running? 

3.1.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can you please look at the section of the controller logs does archiving? Maybe there is an error there?

**Comment by christopheblin** [comment]
@alexec The keywords "archive" & "archiving" do not appear in the workflow-controller logs

The only ting I can see is a block of 6
```
time="2021-12-03T08:19:03.096Z" level=info msg="Enforcing history limit for 'xxx'" namespace=staging-argo workflow=xxx
```

where xxx are the names of my 6 cron workflows

What should I see in the logs ?

**Comment by christopheblin** [comment]
@alexec could you also give me a pointer about the cleaning of logs (i.e if the archiveTTL only delete archived workflows in the db, I need to create a routine to delete the log files in the artifact repository because my main problem is the fact that the artifactRepository contains 1 directory per workflow and so I have 30K directories...)

**Comment by christopheblin** [comment]
@alexec ok, it seems there is some "cron" somewhere because now I have this in the logs 

```
time="2021-12-03T15:57:36.115Z" level=info msg="Performing archived workflow GC"
time="2021-12-03T15:59:59.150Z" level=info msg="Deleted archived workflows" rowsAffected=16527
```

So the only thing to know is : did it also clean the logs in the artifactRepository ?

**Comment by alexec** [comment]
It will not clean up your logs. You must do that yourself.

**Comment by vitalyrychkov** [comment]
#10904 10904
