### ISSUE TITLE
Add support for signing and verifying container images with cosign

### ISSUE THREAD

**Issue by kimsterv** [argoproj/argo-workflows#7334]
# Summary

[Sigstore](https://sigstore.dev) is a project under [openssf.org](https://openssf.org/). It provides an elegant solution for signing and verifying software to ensure artifacts haven't been tampered with along the supply chain. There is a sub-project in sigstore called [cosign](https://github.com/sigstore/cosign) that makes signing and verifying containers super simple. It would be awesome if Argo added support for sigstore/cosign to allow users to sign and verify software in their Argo workflows.

# Use Cases

Users can use this as part of their argo workflows to gain confidence in the software they're producing or consuming. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Related project: https://github.com/IBM/argocd-interlace

**Comment by 34fathombelow** [comment]
@terrytangyuan I believe this issue can now be closed.  PR 9837 has implemented this.
