### ISSUE TITLE
When configuring input.artifact  pull from S3 in init container, the first pull failed due to network reasons. The following 5 retries were reported that  fileName is a directory.i think it is  when calling minioClient's FGetObject method because the TMP folder already existed locally.

### ISSUE THREAD

**Issue by zcerhub** [argoproj/argo-workflows#7336]
## Summary
When configuring input.artifact  pull from S3 in init container, the first pull failed due to network reasons. The following 5 retries were reported that  fileName is a directory.i think it is  when calling minioClient's FGetObject method because the TMP folder already existed locally.
What happened/what you expected to happen?
Subsequent retries succeed after the first failure
What version of Argo Workflows are you running?
argo-workflow:3.0.1
## Diagnostics

What Kubernetes provider are you using?
v1.21.2
What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Kubelet
```bash
# Logs from the init container:



time="2021-11-26T09:49:47.294Z" level=info msg="Start loading input artifacts..."
time="2021-11-26T09:49:47.294Z" level=info msg="Downloading artifact: devops-codecompile-source-s3"




time="2021-11-26T09:49:47.294Z" level=info msg="S3 Load path: /argo/inputs/artifacts/devops-codecompile-source-s3.tmp, key: hello/world/src/code"
time="2021-11-26T09:49:47.294Z" level=info msg="Creating minio client minio:9000 using static credentials"
time="2021-11-26T09:49:47.295Z" level=info msg="Getting from s3 (endpoint: minio:9000, bucket: devops, key: hello/world/src/code) to /arg
o/inputs/artifacts/devops-codecompile-source-s3.tmp"
time="2021-11-26T09:49:47.312Z" level=info msg="Getting directory from s3 (endpoint: minio:9000, bucket: devops, key: hello/world/src/cod
e) to /argo/inputs/artifacts/devops-codecompile-source-s3.tmp"
time="2021-11-26T09:49:47.312Z" level=info msg="Listing directory from s3 (endpoint: minio:9000, bucket: devops, key: hello/world/src/cod
e)"
time="2021-11-26T09:49:54.980Z" level=warning msg="Failed get directory: read tcp 172.40.165.83:55948->10.48.196.248:9000: read: connection reset by peer"





time="2021-11-26T09:49:57.065Z" level=info msg="S3 Load path: /argo/inputs/artifacts/devops-codecompile-source-s3.tmp, key: hello/world/src/code"
time="2021-11-26T09:49:57.065Z" level=info msg="Creating minio client minio:9000 using static credentials"
time="2021-11-26T09:49:57.065Z" level=info msg="Getting from s3 (endpoint: minio:9000, bucket: devops, key: hello/world/src/code) to /arg
o/inputs/artifacts/devops-codecompile-source-s3.tmp"
time="2021-11-26T09:49:57.065Z" level=warning msg="Failed get file: fileName is a directory."



time="2021-11-26T09:50:01.340Z" level=info msg="S3 Load path: /argo/inputs/artifacts/devops-codecompile-source-s3.tmp, key: hello/world/src/code"
time="2021-11-26T09:50:01.340Z" level=info msg="Creating minio client minio:9000 using static credentials"
time="2021-11-26T09:50:01.340Z" level=info msg="Getting from s3 (endpoint: minio:9000, bucket: devops, key: hello/world/src/code) to /arg
o/inputs/artifacts/devops-codecompile-source-s3.tmp"
time="2021-11-26T09:50:01.341Z" level=warning msg="Failed get file: fileName is a directory."



time="2021-11-26T09:50:09.393Z" level=info msg="S3 Load path: /argo/inputs/artifacts/devops-codecompile-source-s3.tmp, key: hello/world/src/code"
time="2021-11-26T09:50:09.393Z" level=info msg="Creating minio client minio:9000 using static credentials"
time="2021-11-26T09:50:09.393Z" level=info msg="Getting from s3 (endpoint: minio:9000, bucket: devops, key: hello/world/src/code) to /arg
o/inputs/artifacts/devops-codecompile-source-s3.tmp"
time="2021-11-26T09:50:09.394Z" level=warning msg="Failed get file: fileName is a directory."




time="2021-11-26T09:50:25.644Z" level=info msg="S3 Load path: /argo/inputs/artifacts/devops-codecompile-source-s3.tmp, key: hello/world/src/code"
time="2021-11-26T09:50:25.644Z" level=info msg="Creating minio client minio:9000 using static credentials"
time="2021-11-26T09:50:25.644Z" level=info msg="Getting from s3 (endpoint: minio:9000, bucket: devops, key: hello/world/src/code) to /arg
o/inputs/artifacts/devops-codecompile-source-s3.tmp"
time="2021-11-26T09:50:25.644Z" level=warning msg="Failed get file: fileName is a directory."




time="2021-11-26T09:50:25.644Z" level=error msg="executor error: timed out waiting for the condition"
time="2021-11-26T09:50:25.645Z" level=info msg="Alloc=7046 TotalAlloc=24068 Sys=74321 NumGC=8 Goroutines=3"
time="2021-11-26T09:50:25.645Z" level=fatal msg="timed out waiting for the condition"

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@zcerhub can you provide your use-case and minio version? Is minio object get updated during the workflow execution?

**Comment by alexec** [comment]
I note you're running an old unsupported version. Have you tried in v3.2?

**Comment by zcerhub** [comment]
> @zcerhub can you provide your use-case and minio version? Is minio object get updated during the workflow execution?

thank you for reply.
1)my minio version is minio RELEASE.2021-07-12T02-44-53Z.
2)for example: there are two tasks:codecheckout task and codecompile task.In the codecompile,the inputs.artifacts.s3'key is from codecheckout's outputs.artifacts.s3.key. the following is the my yaml:


    - name: codecheckout-task
      inputs:
        parameters:
          - name: work-dir
            value: "/src/code"
          - name: workflow-instance-id
            value: "124312431313273"
          - name: current-task-name
            value: "checkoutcode-task"
      container:
        image: biyi/git-devops:1.0.0
        imagePullPolicy: IfNotPresent
        command: [ "bash","-c" ]
        args: [""]
      outputs:
        artifacts:
          - name: devops-codecheckout
            path: '{{inputs.parameters.work-dir}}'
            archive:
              none: { }
            s3:
              endpoint: minio.biyi:9000
              insecure: true
              bucket: devops-artifacts
              key: '{{inputs.parameters.workflow-instance-id}}/{{inputs.parameters.current-task-name}}{{inputs.parameters.work-dir}}'
              accessKeySecret:
                name: minio-secret
                key: accessKey
              secretKeySecret:
                name: minio-secret
                key: secretKey
        parameters:
          - name: code-minio-path
            value: "{{inputs.parameters.workflow-instance-id}}/{{inputs.parameters.current-task-name}}{{inputs.parameters.work-dir}}"
            globalName: 'code-minio-path'

    - name: codecompile-task
      inputs:
        parameters:
          - name: work-dir
            value: "/src/code"
          - name: current-task-name
            value: "compilecode-task"
        artifacts:
          - name: devops-codecompile-source-s3
            path: '{{inputs.parameters.work-dir}}'
            s3:
              endpoint: minio.biyi:9000
              bucket: devops-artifacts
              insecure: true
              key: '{{workflow.outputs.parameters.code-minio-path}}'
              accessKeySecret:
                name: minio-secret
                key: accessKey
              secretKeySecret:
                name: minio-secret
                key: secretKey
      container:
        image: biyi/jdk8-maven311-devops:2.0.1
        imagePullPolicy: IfNotPresent
        command: [ bash,-c ]
        args: [""]

**Comment by zcerhub** [comment]
> I note you're running an old unsupported version. Have you tried in v3.2?

thank you for reply.yes, the version is some elder.i am sorry for that it's hard to upgrade because of much of relevant testing.i search in issue lists but not find the same bug issue as me.in https://github.com/argoproj/argo-workflows/blob/master/docs/upgrading.md,i hasn't found message like my question.

**Comment by zcerhub** [comment]
> > I note you're running an old unsupported version. Have you tried in v3.2?
> 
> thank you for reply.yes, the version is some elder.i am sorry for that it's hard to upgrade because of much of relevant testing.i search in issue lists but not find the same bug issue as me.in https://github.com/argoproj/argo-workflows/blob/master/docs/upgrading.md,i hasn't found message like my question.

i search the code and notice that the argo use minioClienet.FGetObjects pull objects from minio.
![image](https://user-images.githubusercontent.com/23258611/145143944-a2d35469-feb8-48b4-88e3-8d0ef257cd46.png)
i also view the source of minioClienet.FGetObjects.
![image](https://user-images.githubusercontent.com/23258611/145145122-e63fb6b0-1f09-41f0-8d57-0433ba3e0e9a.png)
obviously,the hint of my bugs is from go-sdk of minioclinet.the reason is the filepath is dir.

**Comment by sarabala1979** [comment]
Latest 3.2.4 will have minio client update too. Please try the same scenario on v3.2.4
