### ISSUE TITLE
workflow-controller makes k8s calls to list cronworkflow

### ISSUE THREAD

**Issue by vikulaggarwal** [argoproj/argo-workflows#7337]
### Discussed in https://github.com/argoproj/argo-workflows/discussions/7327

<div type='discussions-op-text'>

<sup>Originally posted by **vikulaggarwal** December  2, 2021</sup>
I'm using argo workflows version 2.12.13

In the workflow controller logs, I can see log statements like the following:

`E1130 05:17:38.084433       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.8/tools/cache/reflector.go:105: Failed to list *unstructured.Unstructured: cronworkflows.argoproj.io is forbidden: User "system:serviceaccount:namespace:argo-sa" cannot list resource "cronworkflows" in API group "argoproj.io" at the cluster scope
`

On giving adequate permissions to the service account `argo-sa`, the errors change to the following:

`E1202 06:25:20.511159       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.8/tools/cache/reflector.go:105: Failed to list *unstructured.Unstructured: the server could not find the requested resource
`
We don't really use cronworkflows and use only workflows. Is there a way to turn these calls off? These calls are happening at the rate of ~1 per second and we think might be causing unnecessary load on the api server.</div>

**Comment by alexec** [comment]
v2.12 is no longer supported. Please try with a newer version.
