### ISSUE TITLE
additional argo cron command, argo cron replace

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#7344]
# Summary

maybe argo cron can introduce an additional replace command

`argo cron replace wf1`

so that users can update cron 
- without the need to figure out patching `kubectl patch` 
- nor delete existing cronjobs `argo cron delete` (removes all the jobs and pods it created and stops it from creating additional jobs)
- while having the argo validation before updating the cron resource

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
#5464 is a more generalized version of this
