### ISSUE TITLE
Improve "artifact repo not configured" error message

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-workflows#7372]
# Summary

When you run a workflow which uses artifacts, but you do not have an artifact repo configured (like with the default install.yaml), the workflow will fail with `key unsupported: cannot get key for artifact location, because it is invalid`.

This message doesn't effectively convey the real problem: the user needs an artifact repo. I know of at least two [goose](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1638825025074900) [chases](https://github.com/argoproj/argo-workflows/issues/6497#issuecomment-894350506) caused by the misleading error message.

To reproduce: 
1. install default install.yaml
2. run the [artifact passing example](https://github.com/argoproj/argo-workflows/blob/master/examples/artifact-passing.yaml)

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
maybe we should like to help?

**Comment by crenshaw-dev** [comment]
Yeah I think that would be great. A link to the artifact repo config doc I guess.
