### ISSUE TITLE
Inconsistent permission behaviour with memoization

### ISSUE THREAD

**Issue by roofurmston** [argoproj/argo-workflows#7381]
## Summary

The behaviour of Argo Workflows in relation to step memoization and permissions to update the cache configmap are inconsistent and confusing.

What happened/what you expected to happen?

The following currently happens:

- When (1) the `argo-cluster-role` (or `argo-role` in a namespace install) doesn't have permissions to update/create the cache configmap and (2) the cache configmap does not exist then no error is thrown.

- When (1) the `argo-cluster-role` (or `argo-role` in a namespace install) doesn't have permissions to update/create the cache configmap and (2) the cache configmap exists but (3) the configmap does not contain the key then no error is thrown.

- When (1) the `argo-cluster-role` (or `argo-role` in a namespace install) doesn't have permissions to update/create the cache configmap and (2) the cache configmap exists but (3) the configmap does contain the key then a permission error is thrown.

I would expect a permission error to be thrown in all cases.

What version of Argo Workflows are you running?

3.2.4

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

I am using memoize-simple workflow, i.e., [https://github.com/argoproj/argo-workflows/blob/master/examples/memoize-simple.yaml](https://github.com/argoproj/argo-workflows/blob/master/examples/memoize-simple.yaml)

What Kubernetes provider are you using?

Minikube

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

I am using the default executor for v3.2.4, which I believe is Docker.

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

`
time="2021-12-10T18:04:57.611Z" level=info msg="Processing workflow" namespace=argo workflow=memoized-simple-workflow-7g9dw
time="2021-12-10T18:04:57.619Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=memoized-simple-workflow-7g9dw
time="2021-12-10T18:04:57.635Z" level=info msg="Skipped node memoized-simple-workflow-7g9dw initialized Error (message: error updating last hit timestamp on cache: configmaps \"my-config\" is forbidden: User \"system:serviceaccount:argo:argo\" cannot update resource \"configmaps\" in API group \"\" in the namespace \"argo\")" namespace=argo workflow=memoized-simple-workflow-7g9dw
time="2021-12-10T18:04:57.635Z" level=error msg="error in entry template execution" error="error updating last hit timestamp on cache: configmaps \"my-config\" is forbidden: User \"system:serviceaccount:argo:argo\" cannot update resource \"configmaps\" in API group \"\" in the namespace \"argo\"" namespace=argo workflow=memoized-simple-workflow-7g9dw
time="2021-12-10T18:04:57.635Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=memoized-simple-workflow-7g9dw
time="2021-12-10T18:04:57.636Z" level=info msg="Updated message  -> error in entry template execution: error updating last hit timestamp on cache: configmaps \"my-config\" is forbidden: User \"system:serviceaccount:argo:argo\" cannot update resource \"configmaps\" in API group \"\" in the namespace \"argo\"" namespace=argo workflow=memoized-simple-workflow-7g9dw
time="2021-12-10T18:04:57.636Z" level=info msg="Marking workflow completed" namespace=argo workflow=memoized-simple-workflow-7g9dw
time="2021-12-10T18:04:57.636Z" level=info msg="Checking daemoned children of " namespace=argo workflow=memoized-simple-workflow-7g9dw
time="2021-12-10T18:04:57.646Z" level=info msg="Workflow update successful" namespace=argo phase=Error resourceVersion=944 workflow=memoized-simple-workflow-7g9dw
`

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.


# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
We should consider adding update configmap permission to the manifests. Memoization is a great feature and I don't see any harm adding this one additional permission on configmaps, especially given that this is a permission that the controller needs for a supported feature. WDYT? @alexec

**Comment by alexec** [comment]
Not sure about adding `update configmaps` permission. Weakens security posture by giving permission we don't always need. 

Instead, I wonder if we should use a different database for memoization.

**Comment by terrytangyuan** [comment]
> Instead, I wonder if we should use a different database for memoization.

Separate issue to track that https://github.com/argoproj/argo-workflows/issues/3587
