### ISSUE TITLE
Expand documentation on conditional expressions

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-workflows#7382]
# Summary

Inspired by: https://stackoverflow.com/questions/70306572/argo-workflow-when-a-condition-for-substring-match/70308809#70308809

The [conditionals docs](https://github.com/argoproj/argo-workflows/tree/master/examples#conditionals) should point out:
* the [govaluate manual](https://github.com/Knetic/govaluate/blob/master/MANUAL.md#govaluate) which is much more helpful than the base README
* Argo Workflows does not augment govaluate with any additional functions, so you're working with the base comparators
* param substitution happens _before_ govaluate evaluation, so you're not allowed to mix quoted and unquoted strings
* the operator `=~` is doing regex (it's unclear in the current comments)

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by MagicFrogSJTU** [comment]
Really good reference!

**Comment by agilgur5** [comment]
Going to close this one out since `govaluate` is on the way out per #7831. 
Similarly, per https://github.com/argoproj/argo-workflows/issues/7576#issuecomment-1728725234, I plan to remove the `govaluate` references anyway and point folks toward `expr` docs instead.
