### ISSUE TITLE
For expression feature, I deploy 3.2.4 and argo submit expression-destructure-json.yaml, the value is not replaced

### ISSUE THREAD

**Issue by liujiong1982** [argoproj/argo-workflows#7399]
run "argo submit expression-destructure-json.yaml"

I check the pod log, it shows
"{{=jsonpath(workflow.parameters.config, '$.a')}}{{=jsonpath(workflow.parameters.config, '$.b')}}{{=jsonpath(workflow.parameters.config, '$.c')}}"

workflow.parameters.config are not replaced

**Comment by sarabala1979** [comment]
@liujiong1982 I am not able to reproduce.  in 3.2.4 branch. Can you check the your. CLI version? Please provide the controller logs

**Comment by liujiong1982** [comment]
argo: v0.0.0-dev-kc-7
  BuildDate: 2021-11-19T01:29:47Z
  GitCommit: 47a5208e9c940abb014c08847179865a5b227f49
  GitTreeState: clean
  GitTag: v0.0.0-dev-kc-7
  GoVersion: go1.17.3
  Compiler: gc
  Platform: linux/amd64

**Comment by liujiong1982** [comment]
> @liujiong1982 I am not able to reproduce. in 3.2.4 branch. Can you check the your. CLI version? Please provide the controller logs

argo: v0.0.0-dev-kc-7
BuildDate: 2021-11-19T01:29:47Z
GitCommit: 47a5208
GitTreeState: clean
GitTag: v0.0.0-dev-kc-7
GoVersion: go1.17.3
Compiler: gc
Platform: linux/amd64

**Comment by alexec** [comment]
That is a dev version, can you please try again with latest?
