### ISSUE TITLE
GoGo Protobuf is no longer maintained

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-workflows#7400]
# Summary

GoGo Protobuf is no longer maintained. See https://github.com/gogo/protobuf/issues/691

GoGo Protobuf is based on https://github.com/golang/protobuf which has been superseded by [google.golang.org/protobuf ](https://pkg.go.dev/google.golang.org/protobuf)

A related PR where the upgrade was attempted on an argo project: https://github.com/argoproj/argo-rollouts/issues/1091

Once https://github.com/kubernetes/kubernetes/issues/96564 is resolved we can action this.

# Use Cases

Several GoGo features do not appear to be implemented in google.golang.org/protobuf so transitioning might be difficult. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by blkperl** [comment]
I'm going to close this until upstream k8s makes a decision.

**Comment by paralin** [comment]
Closed here and closed in upstream k8s, I guess everyone collectively decided to forget about this.
