### ISSUE TITLE
when doesn't support expression, will it support in the future?

### ISSUE THREAD

**Issue by liujiong1982** [argoproj/argo-workflows#7415]
argo 3.1 supports Expression, see https://argoproj.github.io/argo-workflows/variables/#expression
but when doesn't support it,  see below image, will you support it in the near future? It is useful in our cases
![image](https://user-images.githubusercontent.com/7462724/146101713-e9f50120-47ce-462f-b34a-1e6181be8dc3.png)

**Comment by crenshaw-dev** [comment]
@liujiong1982 workarounds: 1) see if any of the govaluate comparators fit your use case or 2) calculate a value in a param using expressions and then use that param in the when expression.

**Comment by alexec** [comment]
I think there is an issues to add a new type of expression syntax for `when`.

**Comment by liujiong1982** [comment]
> I think there is an issues to add a new type of expression syntax for `when`.

is there any plan for this issue to be resolved in 3.3 release?

**Comment by alexec** [comment]
> Is there any plan for this issue to be resolved in 3.3 release?

No. Sorry.

**Comment by alexec** [comment]
When cannot be changed. Instead, we will replace it.

**Comment by agilgur5** [comment]
Per #7576, `when` actually did support `expr` expressions. And #9761 made that better supported (and removed the error message).

Re: `whenExpression`, see #7831
