### ISSUE TITLE
workflow-event-bindings page support basehref

### ISSUE THREAD

**Issue by chf007** [argoproj/argo-workflows#7416]
# Summary

![image](https://user-images.githubusercontent.com/358650/146137578-a3b9f5ab-1341-4116-8a79-036010e02269.png)

If the `basehref` is set, the placeholder address of the `workflow-event-bindings` page should also be added synchronously

Similarly, the Swagger-API docs needs to be handled

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
This is where this needs to be fixed:

https://github.com/argoproj/argo-workflows/blob/dbda60fc5c72c02729d98b4e5ff08f89a6bf428c/ui/src/app/workflow-event-bindings/components/workflow-event-bindings/workflow-event-bindings.tsx#L109

Should be like this:

https://github.com/argoproj/argo-workflows/blob/master/ui/src/app/apidocs/components/apiDocs.tsx#L10

Would you like to submit a PR? We can set you up with a mentor to help if you're interested.
