### ISSUE TITLE
Argo Workflows server not starting after enabling SSO (AD), using ArgoCD Dex 

### ISSUE THREAD

**Issue by pavmohan1** [argoproj/argo-workflows#7417]
## Summary
I am trying to enable SSO login on an Argo Workflows server. I want the Argo Workflows server to use the Argo CD Dex instance for authentication. SSO is working on the Argo CD server with no problems. 

I am using the Helm templating from [this](https://argoproj.github.io/argo-workflows/argo-server-sso-argocd/#example-helm-chart-configuration-for-authenticating-against-argocds-dex) documentation.

#### What happened/what you expected to happen?
The Argo Workflows server pod does not startup and throws an `Error 502: Bad Gateway`. The complete startup logs of the pod are below.

#### What version of Argo Workflows are you running?
`v3.2.4`

## Diagnostics

Here is the templating used for the Argo CD `values.yaml`.

```yaml
dex:
	image:
		tag: v2.23.0
	env:
		 - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
		valueFrom:
		 secretKeyRef:
		name: argo-workflows-sso
		key: client-secret

dex.config: | 
	staticClients:
	- id: argo-workflows-sso
		name: Argo Workflow
		 redirectURIs:
			- https://argo-workflows.URL/oauth2/callback
		secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
```

Here is the templating from the Argo Workflows `values.yaml`

```yaml 
extraArgs:
	- --auth-mode=sso
	 - --verbose
sso:
		issuer: https://argocd.URL/api/dex
		# sessionExpiry defines how long your login is valid for in hours. (optional, default: 10h)
		sessionExpiry: 240h
		clientId:
			name: argo-workflows-sso
			key: client-id
		clientSecret:
			name: argo-workflows-sso
			key: client-secret
		redirectUrl: https://argo-workflows.URL/oauth2/callback
```

This code is almost equivalent to the documentation example (the same variable names have been used).

What Kubernetes provider are you using?
`GKE: "v1.19.14-gke.1900"`

### Logs
```bash
# Logs from the Workflow Server: 
kubectl logs -n argo argo-worfkflows-server
time="" level=debug msg="CLI version" version="{v3.2.4 2021-11-17T23:21:45Z 8771ca279c329753e420dbdd986a9c914876b151 v3.2.4 clean go1.16.10 gc linux/amd64}"
time="" level=info msg="not enabling pprof debug endpoints"
I1215 11:37:20.979706       1 merged_client_builder.go:121] Using in-cluster configuration
time="" level=info authModes="[sso]" baseHRef=/ managedNamespace=bibcd-argo namespace=bibcd-argo secure=false
time="" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argoproj.github.io/argo-workflows/tls/"
time="" level=info msg="config map" name=argo-workflows-workflow-controller-configmap
I1215 11:37:20.991412       1 round_trippers.go:454] GET https://INTERNALIP:443/api/v1/namespaces/argo/configmaps/argo-workflows-workflow-controller-configmap 200 OK in 9 milliseconds
I1215 11:37:20.998422       1 round_trippers.go:454] GET https://INTERNALIP:443/api/v1/namespaces/argo/secrets/argo-workflows-sso 200 OK in 3 milliseconds
Error: 502 Bad Gateway: 
502 Bad Gateway: 
Usage:
  argo server [flags] ...
```

### Possible Causes/Symptoms
- The URL`/oauth2/callback` is not reachable but returns a 501 when trying to visit it. 
- The Argo CD installation is in another namespace to the Argo Workflows server.
-  The Argo CD Server is showing this error: 
`
    http: proxy error: dial tcp INTERNALIP:5556: connect: connection refused
`
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by avtar-mindgrep** [comment]
I am facing this too.

**Comment by pavmohan1** [comment]
Closing as we found the underlying cause. 

To solve this issue we had to enable egress connections from the `argocd-dex` pod to the Kubernetes API.  Also, the ID in the `staticClients` had to be set to the `client-id` of our SSO provider.

**Comment by avtar-mindgrep** [comment]
@pavmohan1  can you please share the snippet of  your dex config file.
