### ISSUE TITLE
v3.2.5 dag workflow wait container raise docker socket

### ISSUE THREAD

**Issue by icecoffee531** [argoproj/argo-workflows#7427]
## Summary

What happened/what you expected to happen?
Make a dag workflow，and then submit it. The pod will NotReady and wait container raise docker socket.
![image](https://user-images.githubusercontent.com/51080110/146368916-b0236daa-1c04-467f-882b-f282c303bf59.png)

What version of Argo Workflows are you running?
v3.2.5
## Diagnostics
```kubeclt logs upgrade-pzqtl-3876002572 wait```
![image](https://user-images.githubusercontent.com/51080110/146369145-8a35482a-4276-46b8-aafe-1f3d968cae38.png)
Check pod yaml，I found the volumes `var-run-argo` isn't mount in pod.
![image](https://user-images.githubusercontent.com/51080110/146369435-8081d498-7e7e-4073-a1ff-68caebb85e7c.png)
![image](https://user-images.githubusercontent.com/51080110/146369493-a099c802-cb65-479c-b574-26f87a452f1d.png)

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@sarabala1979 this is a regression. I think it might make v3.2.5 unusable. Maybe we back ported a fix that depends on making emissary the default executor?

@icecoffee531 can you help confirm this be making sure that in your config map you configure the `containerRuntimeExecutor: docker`?

**Comment by alexec** [comment]
I think this commit should not have been merged:

49b3f0cb2 fix(controller): default volume/mount to emissary (#7125)

**Comment by icecoffee531** [comment]
> @sarabala1979 this is a regression. I think it might make v3.2.5 unusable. Maybe we back ported a fix that depends on making emissary the default executor?
> 
> @icecoffee531 can you help confirm this be making sure that in your config map you configure the `containerRuntimeExecutor: docker`?

Which configmap? I didn't find any configMap mounted on the Pod or argo-server, and the data in workflow-controller-configmap is empty.

**Comment by sarabala1979** [comment]
Argo controller will have configmap workflow-controller-configmap in Argo namespace. Please add this config item  containerRuntimeExecutor: pns or docker(if u r using docker)

**Comment by icecoffee531** [comment]
> 

@sarabala1979 Thank you for your reply.
@alexec I didn't configure `containerRuntimeExecutor: docker`. When I configure the configuration, it works normally.

**Comment by alexec** [comment]
Reverted on release-3.2 branch. Waiting for [build](https://github.com/argoproj/argo-workflows/actions/runs/1593454779) to finish.
