### ISSUE TITLE
k8sapi executor does not support outputs from base image layer.

### ISSUE THREAD

**Issue by wybaron** [argoproj/argo-workflows#7463]
![image](https://user-images.githubusercontent.com/19605510/147101536-df11201c-d518-434c-9d57-b1ccd40fae7f.png)

**Comment by terrytangyuan** [comment]
This is expected behavior and mentioned in the docs: https://github.com/argoproj/argo-workflows/blob/master/docs/workflow-executors.md

I'd suggest using the emissary executor.
