### ISSUE TITLE
"token not valid for running mode"

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#7464]
curl -H "Authorization: Bearer redact" --request GET --url https://redact/api/v1/workflows/argo -vvv

i have sso auth mode on the argoworkflows server, is api not supported in that case?

**Comment by bygui86** [comment]
I have SSO auth mode configured with ArgoCD Dex and in the argo-server logs I see tons of lines like

```
time="2021-12-23T13:16:34.914Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2021-12-23T13:16:34Z" grpc.time_ms=0.063 span.kind=server system=grpc
```

I can't understand where those calls come from.
Ideas?

ArgoWorkflows `v3.2.4`
ArgoCD `2.2.1`

**Comment by tooptoop4** [comment]
link shows solution
