### ISSUE TITLE
GitHub releases CLI instructions also include kubectl apply

### ISSUE THREAD

**Issue by vogre** [argoproj/argo-workflows#7470]
# Summary

GitHub 

When you visit https://github.com/argoproj/argo-workflows/releases, there are install instructions

```
kubectl create namespace argo
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.2.6/install.yaml
```

Those are unrelated to CLI install, and may interfere with previous argo installs

# Use Cases

When downloading argo version

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Thanks! This will be fixed in https://github.com/argoproj/argo-workflows/pull/7477 for future releases.
