### ISSUE TITLE
Make argoexec image scratch/distroless to improve security

### ISSUE THREAD

**Issue by Sh1ftry** [argoproj/argo-workflows#7486]
# Summary

Argoexec image has lots of components, which makes it vulnerable to various security findings. With emissary executor though it's possible to make the image distroless.

# Use Cases

Workflows using emissary executor.

- [x] #7795
- [x] #7796
- [x] #7797
- [x] #7798
- [x] #7799
- [x] #7800

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
We already move to a more secure base image (alpine), but it'd be awesome to go further.

This work would need to be done piecemeal, as we'd probably want to add tests each step of the way:

- [ ] Remove the deprecated Docker executor 
- [ ] Replace use of `kubectl` with Golang Kubernetes client in the resource template code
- [ ] Replace use of `curl` binary by the HTTP artifact driver
- [ ] Replace use of "git" binary by Git artifact driver (does Golang Git client support submodules)
- [ ] Replace the "jq" binary with TBD (hard/risky)
- [ ] Replace use of the "tar" binary in the Kubernetes API executor
- [ ] Update `Dockerflie` to make `argoexec` scratch/distroless

**Comment by alexec** [comment]
@Sh1ftry would you be interested in helping?

**Comment by NikeNano** [comment]
For the work related to replacing `kubectl` do we aim for using the dynamic k8s client? Have looked around and it don't seem like there is any libs that handle this smoothly so it might be quite a lot of code that needs to be brought in to argo to handle this. I will continue to research it to see what I can find.

**Comment by alexec** [comment]
Correct. I think we can use `dynamic.New`.

**Comment by NikeNano** [comment]
As I see the downside atm is that it will be hard to be backwards compatible since the dynamic API don't have the same functionality out of the box as `kubectl`. Specifically there is not direct mapping towards `apply`, but might be in the not to distant future hopefully since k8s now supported `apply` server side, https://pkg.go.dev/k8s.io/client-go/dynamic#NewForConfig. I guess we could implement checks to see if resource exists and then do and patch similar to `kubectl`. Do you have some thoughts on this @alexec ?

**Comment by alexec** [comment]
`kubectl` is written in Golang. Argo CD uses it like that:

https://github.com/argoproj/argo-cd/blob/master/go.mod#L87

**Comment by NikeNano** [comment]
> 
> We can do that. Should we discus this is the right issue? #7797

yes, my bad!

**Comment by alexec** [comment]
I've thought about this and I think there is a third-way that might be easier. Instead of replacing the binaries with pure Go, we actually just want to get rid of the operating system. We can do this by copying just the binaries accross. Assmuming all the biniaries work without the underying OS.
