### ISSUE TITLE
Pod "START TIME"/ "END TIME" popup shows time in UTC instead of local timezone

### ISSUE THREAD

**Issue by oleg-borodai** [argoproj/argo-workflows#7488]
## Summary

Pod START TIME popup shows time in UTC which doesn't match with actual value shown relatively to current moment(see screenshot). I would expect the popup to show time in my local timezone.

argo v3.2.6

## Diagnostics

```argo submit -n argo --watch https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/coinflip-recursive.yaml```

![Pasted Graphic 1](https://user-images.githubusercontent.com/2837437/147958693-4e480149-930c-4647-81eb-5ccfe745298e.png)

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@oleg-borodai  It is a good enhancement. it is really challenging to display the time format.
Would you like to submit the PR for this enhancement?

**Comment by akpsan** [comment]
Hi I would like to work on this issue. If someone can point me in the right direction towards the basic documentation of the application and steps to reproduce. Thanks!

**Comment by sarabala1979** [comment]
@akpsan Good and welcome.  I will help with this. Please setup local env https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md

**Comment by lstolcman** [comment]
> I would expect the popup to show time in my local timezone.

Our team is located in different timezones, and definitely, we would not expect to have local time shown. Having common UTC is a great value for us.

Could you re-spec the proposed change to include UTC too?

**Comment by oleg-borodai** [comment]
> > I would expect the popup to show time in my local timezone.
> 
> Our team is located in different timezones, and definitely, we would not expect to have local time shown. Having common UTC is a great value for us.
> 
> Could you re-spec the proposed change to include UTC too?

Probably having two lines in this popup could be a nice solution? I mean something of this format for the popup on the screenshot: 
"2022-01-03T17:54:55
  2022-01-03T16:54:55Z"
