### ISSUE TITLE
Windows CLI missing extension

### ISSUE THREAD

**Issue by kennedy** [argoproj/argo-workflows#7524]
## Summary

What happened/what you expected to happen?
After unzipping the `argo-windows-amd64.gz` bundle, there should be a executable binary with the file extension of *.exe

What version of Argo Workflows are you running?
0.9.4

## Diagnostics

I manually added the file extension, added to my tools directory in my PATH, then it works.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@argoproj/argo-windows FYI

**Comment by sarabala1979** [comment]
Is  CI  issue?

**Comment by lippertmarkus** [comment]
I think we need to append `.exe` to the output name in `-o` here when creating Windows binary :
https://github.com/argoproj/argo-workflows/blob/b476c4af505b6f24161a3818c358f6f6b012f87e/Makefile#L178
