### ISSUE TITLE
support webhdfs artifacts

### ISSUE THREAD

**Issue by vassap2022** [argoproj/argo-workflows#7540]
# Summary

There is already support for hfds in argo-workflows (https://github.com/argoproj/argo-workflows/blob/master/examples/hdfs-artifact.yaml#L41) but not for the webhdfs protocol. I had a quick look in this repository and I could not find another question about webhdfs.  My team could help in with this implementation (i.e. implement the solution and open a PR in this repository). My question is if this kind of addition would we merged (given that it will follow the guidelines and address any comments that might arise in the PR)?

# Use Cases

Some datasets can be accessed using the webhdfs protocol. We would like to read and write them through argo workflows.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexdittmann** [comment]
I have raised a PR here: https://github.com/argoproj/argo-workflows/pull/8443
