### ISSUE TITLE
DAG can't return a "dag" list

### ISSUE THREAD

**Issue by yaronmat** [argoproj/argo-workflows#7548]
when inside a DAG and trying to return a list of task results:
`x=[task_a() for _ in list(range(10))]`
` return x`

the next error is shown:
TypeError: This DAG returned a value of type [list].DAG's may only return a result of a nested DAG or Task

The problem (and current solution) is transforming this "list" to a real list object.
Current solution is to use a dummy task that gets x as a parameter and then just returns it (with no changes)

**Comment by dinever** [comment]
Hi @yaronmat, thanks for reporting this! Are you using a Python SDK? Could you share the workflow manifest/script that is causing the issue? Thanks!

**Comment by dinever** [comment]
This looks like an issue from [DiagnosticRobotics/argo-workflow-tools](https://github.com/DiagnosticRobotics/argo-workflow-tools):

https://github.com/DiagnosticRobotics/argo-workflow-tools/blob/b90ca2981f5b4dc2c8a868271d0720d419fb04b8/argo_workflow_tools/dsl/dag_compiler.py#L354-L357

**Comment by terrytangyuan** [comment]
@yaronmat Could you comment on how you are using the SDK and which SDK are you using? This repo will be only tracking issues related to https://github.com/argoproj/argo-workflows/tree/master/sdks/python.
