### ISSUE TITLE
Include the timezone in argo cron list output

### ISSUE THREAD

**Issue by bobh66** [argoproj/argo-workflows#7557]
# Summary

It would be helpful if the output of the argo cron list command included the timezone along with the schedule, as it is impossible to correctly interpret the schedule without knowing what timezone it is using.

# Use Cases

This is useful any time the user requests a list of existing cronworkflow objects

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
Looks like OP contributed and fixed this themselves in #7559
