### ISSUE TITLE
Estimated duration for the repeated workflows is not available 

### ISSUE THREAD

**Issue by purin0604** [argoproj/argo-workflows#7574]
## Summary

What happened/what you expected to happen?
- I would like to access the estimated duration from workflow progress info. However, even if I have tried to submit the same workflow templates several times on the same day,  Argo doesn't provide the estimated duration. 

What version of Argo Workflows are you running?
- argo: v3.2.6

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parallel-job10-
spec:
  entrypoint: parallel-job-entry
  arguments:
    parameters:
      # may override by submitting with -p numtasks=xxx
      - name: numtasks
        value: 20

  templates:
  - name: parallel-job-entry
    steps:
    - - name: Start
        template: start-task
    
    - - name: Parallel
        template: parallel-task

    - - name: Finish
        template: finish-task

  - name: parallel-task
    parallelism: 10
    steps:
    - - name: StepA
        template: stepA-task
        arguments:
          parameters:
          - name: taskindex
            value: "{{item}}"
        withSequence:
          count: "{{workflow.parameters.numtasks}}"

  - name: stepA-task
    inputs:
      parameters:
      - name: taskindex
    metadata:
      labels:
        jobindex: "{{inputs.parameters.taskindex}}"
    container:
      image: alpine:3.11
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 0.3
          memory: "400Mi"
      env:
        - name: JOBINDEX
          value: "{{inputs.parameters.taskindex}}"
      command: [sh, -c]
      args: ["echo Step:A Task:{{inputs.parameters.taskindex}}  JOBINDEX=$JOBINDEX; sleep 26"]

  - name: start-task
    container:
      image: alpine:3.11
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 0.3
          memory: "400Mi"

      command: [sh, -c]
      args: ["echo Start; sleep 2"]

  - name: finish-task
    container:
      image: alpine:3.11
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 0.3
          memory: "400Mi"

      command: [sh, -c]
      args: ["echo Finish; sleep 2"]

```

What Kubernetes provider are you using?
- ibmcloud 

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
I am not sure it is right way to check the executor,  but with the "kubectl describe -n argo configmap workflow-controller-configmap
"
the output includes the following 
```
containerRuntimeExecutors:
----
- name: emissary
  selector:
    matchLabels:
      workflows.argoproj.io/container-runtime-executor: emissary
- name: pns
  selector:
    matchLabels:
      workflows.argoproj.io/container-runtime-executor: pns
```

## Reference image files
I have repeated submitting the above "parallel-job10.yaml" for three times less than 20mins as shown in the following screenshot.
![Screenshot from 2022-01-17 23-31-00](https://user-images.githubusercontent.com/38477992/149891253-52d2ac8c-891c-40fd-8958-4a0a1471a33f.png)

And the following is the screenshot of the progress info of the last workflow "parallel-job10-8qxtg", which doesn't show the expected duration.

![Screenshot from 2022-01-17 23-30-08](https://user-images.githubusercontent.com/38477992/149891518-b85c1b32-23c0-4a6e-b1b8-e4c75e024a43.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I believe this is as expected. To determine the estimated duration, there must be a workflow to base that on. That workflow is choose as the most recent cron workflow or workflow template used to submit the workflow. Your sample workflow does not use either of those mechanisms, so will not get estimated duration.
