### ISSUE TITLE
argo CLI list command results not predictable with -o name flag

### ISSUE THREAD

**Issue by samene** [argoproj/argo-workflows#7581]
## Summary

Using argo CLI I want keep the latest 20 workflows and delete the rest. This runs in a cron job (not argo cron job, normal linux cron)

When I do this
```
argo list -n argo --no-headers  | tail -n 6
patch-generator-basic-c2pc5      Succeeded   15d   3m   0
patch-generator-basic-vxj92      Succeeded   15d   3m   0
patch-generator-basic-6db47      Succeeded   15d   2m   0
patch-generator-basic-wcwkb      Succeeded   19d   2m   0
patch-generator-basic-tgpqf      Succeeded   20d   2m   0
patch-generator-basic-ldsrb      Succeeded   20d   2m   0
```
and when I do it with -o name, I get different result
```
argo list -n argo --no-headers -o name | tail -n 6
patch-generator-basic-6db47
patch-generator-basic-ccklj
patch-generator-basic-tgpqf
patch-generator-basic-mc2bp
patch-generator-advanced-rm76g
patch-generator-basic-vtknt
```
As you can see both return a different list.

Is there a way to sort the output of `argo list` in order of creation time? Why ordering is different when `-o name` is used.

Version: v3.2.4
Kubernetes: v1.21.2
Docker: 20.10.7

**Comment by dinever** [comment]
Looks like this issue exists in the latest version.

`sort.Sort(workflows)` will sort the workflows by their `CreationTimestamp` and `FinishedAt`:

https://github.com/argoproj/argo-workflows/blob/f1fe3bee498ac7eb895af6f89a0eba5095410467/pkg/apis/workflow/v1alpha1/workflow_types.go#L130-L145

When we list workflows with `-o name`, these timestamps won't be selected by the field selector, so the workflows we got all have `0001-01-01 00:00:00 +0000 UTC` timestamps, making the sorting inconsistent.
