### ISSUE TITLE
Artifact cannot be fetched from UI when artifact repository is specified using workflow template

### ISSUE THREAD

**Issue by hamza3202** [argoproj/argo-workflows#7587]
## Summary

If [artifact repository](https://argoproj.github.io/argo-workflows/fields/#artifactrepositoryref) is specified with workflow template then even though artifact is saved in artifact repository, It is not retrievable from the UI.

What happened/what you expected to happen?
When artifact is fetched from UI it looks into the default artifact repository instead of the one configured in workflow template.

What version of Argo Workflows are you running?
v3.2.4

## Diagnostics

I have looked into the code and I think this is because the UI only considers the workflow spec when trying to identify the artifact repository.
https://github.com/argoproj/argo-workflows/blob/a94b846e67382252831d44624c2f4b1708f7a30c/server/artifacts/artifact_server.go#L168

I am not sure what should be the right way to do this. Perhaps, the artifact ref should be saved in the status of artifact and then fetched from there just like it fetches the rest of artifact?
https://github.com/argoproj/argo-workflows/blob/a94b846e67382252831d44624c2f4b1708f7a30c/server/artifacts/artifact_server.go#L162 
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Duplicates #7531
