### ISSUE TITLE
v3.2.6 Argo UI failed to render pod log

### ISSUE THREAD

**Issue by liuzqt** [argoproj/argo-workflows#7595]
## Summary

What happened/what you expected to happen?
![image-2022-01-19-22-04-27-808](https://user-images.githubusercontent.com/22358241/150293409-289c985f-0e23-4740-b07f-1c6e57da7268.png)

What version of Argo Workflows are you running?
3.2.6 (we just upgrade it from 3.2.3 today, so I guess this issue might be introduced between 3.2.3 and 3.2.6. We'll try to roll back to 3.2.3 and see if this issue still exist)
## Diagnostics

I'm still not able to find a minimal reproducing example, since this issue only happened in some of our pipelines, and not sure which part of the template triggered this issue.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Most likely introduced by this commit:

f5f6899f5 fix: Add pod name format annotation. Fixes #6962 and #6989 (#6982)

@JPZ13 would you be able to look into this please?

**Comment by JPZ13** [comment]
> Most likely introduced by this commit:
> 
> [f5f6899](https://github.com/argoproj/argo-workflows/commit/f5f6899f531126a18f5f42201156c995630fdf1b) fix: Add pod name format annotation. Fixes #6962 and #6989 (#6982)
> 
> @JPZ13 would you be able to look into this please?

On it

**Comment by JPZ13** [comment]
@liuzqt Can you share what the pod names are in kubernetes for this workflow that are resulting in the error on the UI? I'm working on a fix and need to make sure there's a 1:1 match between the pod names as they appear in k8s and what our UI pod name function returns

Thanks for reporting the issue!

**Comment by liuzqt** [comment]
@JPZ13  the Pod UI is not working, I tried to find their information from the json meta, hopefully this can help:
```
"patch-processing-pipeline-ksp78-1623891970": {
                "id": "patch-processing-pipeline-ksp78-1623891970",
                "name": "patch-processing-pipeline-ksp78.retriable-map-authoring-initializer",
                "displayName": "retriable-map-authoring-initializer",
                "type": "Pod",
                "templateScope": "local/",
                "phase": "Succeeded",
                "boundaryID": "patch-processing-pipeline-ksp78",
                "startedAt": "2022-01-20T01:45:35Z",
                "finishedAt": "2022-01-20T01:45:39Z",
                "progress": "1/1",
                "resourcesDuration": {
                    "cpu": 3,
                    "memory": 3
                },
                ...
```

```
"patch-processing-pipeline-ksp78-1769534216": {
                "id": "patch-processing-pipeline-ksp78-1769534216",
                "name": "patch-processing-pipeline-ksp78.NODE-RETRIABLE-MAP-AUTHORING(1).NODE-GENERATE-EMLANE.pre-emlane-map-builder",
                "displayName": "pre-emlane-map-builder",
                "type": "Pod",
                "templateRef": {
                    "name": "map-builder-task",
                    "template": "map-builder"
                },
                "templateScope": "namespaced/node-generate-emlane-task",
                "phase": "Failed",
                "boundaryID": "patch-processing-pipeline-ksp78-242024017",
                "message": "Error (exit code 1)",
                "startedAt": "2022-01-20T01:53:05Z",
                "finishedAt": "2022-01-20T01:53:08Z",
                "progress": "1/1",
                "resourcesDuration": {
                    "cpu": 4,
                    "memory": 4
                },
                ...

```

**Comment by JPZ13** [comment]
That is super helpful @liuzqt. Thank you for the extra info. I'll tag you on the PR for the fix once it's ready

**Comment by liuzqt** [comment]
@JPZ13  sorry actually I'm just an Argo user in our company and I have to ask our Argo team to help verify this fix later. I'll update once I get feedback from them.

**Comment by JPZ13** [comment]
> @JPZ13 sorry actually I'm just an Argo user in our company and I have to ask our Argo team to help verify this fix later. I'll update once I get feedback from them.

Sounds good. Thank you @liuzqt

**Comment by terrytangyuan** [comment]
@JPZ13 I am in touch of @liuzqt’s team. Let me know if there’s any other information you need.
