### ISSUE TITLE
intermittent errors at scale?

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#7597]
Each workflow takes around 40seconds, i had limit to run 100 workflows in parallel, and was constantly filling up the different workflows to run over few hours so 1000s of workflows ran in total (with constant load of 100 at a time). Various errors below affected less than 1% of the workflows run, is there some settings to avoid these or some retries missing on argo server?

Issue 1:
**pod deleted**
aws-sqs-rsload-workflow-mjnqr --> log does not show completion
{"log":"time=\"2022-01-18T23:19:57.214Z\" level=info msg=\"Step terminated\"\n","stream":"stderr","time":"2022-01-18T23:19:57.230300939Z"}
{"log":"time=\"2022-01-18T23:19:57.215Z\" level=info msg=\"Killing containers\"\n","stream":"stderr","time":"2022-01-18T23:19:57.23032183Z"}
{"log":"time=\"2022-01-18T23:19:57.242Z\" level=info msg=\"Get pods 401\"\n","stream":"stderr","time":"2022-01-18T23:19:57.256728571Z"}
{"log":"time=\"2022-01-18T23:19:57.243Z\" level=warning msg=\"Non-transient error: Unauthorized\"\n","stream":"stderr","time":"2022-01-18T23:19:57.256750692Z"}
{"log":"time=\"2022-01-18T23:19:57.243Z\" level=info msg=\"zero container IDs, assuming all containers have exited successfully\"\n","stream":"stderr","time":"2022-01-18T23:19:57.256755601Z"}

Issue 2:
**Pod failed before wait container starts** -->seems to have completed ok but no logs to s3
aws-sqs-rsload-workflow-75qcl

Issue 3:
Error (exit code 1): **Unauthorized** -->seems to have completed ok and written logs to s3
aws-sqs-rsload-workflow-9m79f
  {"log":"time=\"2022-01-18T23:20:28.919Z\" level=info msg=\"Annotating pod with output\"\n","stream":"stderr","time":"2022-01-18T23:20:28.919200135Z"}
  {"log":"time=\"2022-01-18T23:20:28.925Z\" level=info msg=\"Patch pods 401\"\n","stream":"stderr","time":"2022-01-18T23:20:28.92578341Z"}
  {"log":"time=\"2022-01-18T23:20:28.926Z\" level=warning msg=\"Non-transient error: Unauthorized\"\n","stream":"stderr","time":"2022-01-18T23:20:28.926163363Z"}

Issue 4:
error in entry template execution: Internal error occurred: **failed calling webhook** "critical-pod-identity-webhook.amazonaws.com": Post "https://pod-identity-webhook.kube-system.svc:443/mutate?timeout=30s": no endpoints available for service "pod-identity-webhook"
aws-sqs-rsload-workflow-zn6rn and many others  --> log does not show completion

Issue 5:
**Error (exit code 137)** 
aws-sqs-rsload-workflow-z9kj2

**Comment by tooptoop4** [comment]
I am on latest version, the RBAC is there. This was using pns executor, will try emissary.

**Comment by tyrken** [comment]
FWIW I also had one of the "Issue 1" type where for unknown reasons the Argo sidecar (we also are also using PNS, with v3.2.6 running on AWS EKS) decided to kill the main container.  I did also see in the K8s master audit logs (which I've set to go to AWS CloudWatch logs) the unusual non-JSON entry below, timed just as Argoexec decided to terminate.  Looks like something timed out/errored & that might be the cause of our issues.  Will also try out Emissary when we can safely switch...

```
I0202 11:42:55.666186      11 trace.go:205] Trace[984180032]: "Get" url:/api/v1/namespaces/mynamespace/pods/myapp-t7r72/log,user-agent:argo/v0.0.0 (linux/amd64) kubernetes/$Format/argo-workflows/v3.2.6 argo-server,client:172.31.22.226 (02-Feb-2022 11:26:25.756) (total time: 989909ms):
Trace[984180032]: ---"Transformed response object" 989902ms (11:42:00.666)
Trace[984180032]: [16m29.909335628s] [16m29.909335628s] END
```

**Comment by tooptoop4** [comment]
did u solve @tyrken ?

**Comment by tyrken** [comment]
No ... but did switch to Emissary & don't see it now @tooptoop4
