### ISSUE TITLE
v3.3 Blog post

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7604]
https://blog.argoproj.io/whats-new-in-argo-workflows-v3-3-dd051d2f1c7

**Comment by jmeridth** [comment]
Hosting on medium.com that requires an account is not ideal.  wdyt?

![Screen Shot 2022-01-21 at 11 26 27 AM](https://user-images.githubusercontent.com/35014/150572436-35bc664a-c1ed-4e3d-b6dc-7fd76dd31c53.png)

**Comment by jmeridth** [comment]
please ignore previous (deleted) comment.  realized that's the login link to edit the post.  Not for general consumption 😄

**Comment by blkperl** [comment]
Great blog post @alexec

A few thoughts:

Plugin Templates

* Do plugin templates only support Python? It's not clear in the docs:
  * https://github.com/argoproj/argo-workflows/blob/master/docs/executor_plugins.md
  * https://github.com/argoproj/argo-workflows/blob/master/docs/plugins.md
* Does a plugin failure cause a workflow failure? If so does it support the [continueOn](https://github.com/argoproj/argo-workflows/blob/4e450e250168e6b4d51a126b784e90b11a0162bc/examples/continue-on-fail.yaml) feature?
* How do users securely manage secrets needed for a plugin? Such as a Slack token in your example.
* Should we have an example in https://github.com/argoproj/argo-workflows/tree/master/examples for this feature? 

Debug Pause

* Do we have docs for this feature? I see e2e tests but no docs or example in the example folder.

Emissary

* EKS drops support for K8s 1.21 on February 2023. GKE doesn't have an EOL date posted.  We could target that date for when Argo Workflows will remove the docker executor which gives users 1 year to update. 

Misc

* Any interesting things we could add about what to expect in the next release?

**Comment by alexec** [comment]
I've created issues #7684 and #7684 for the docs.

> EKS drops support for K8s 1.21 on February 2023. GKE doesn't have an EOL date posted. We could target that date for when Argo Workflows will remove the docker executor which gives users 1 year to update.

So we don't need to rush!
