### ISSUE TITLE
Should scaling docs be updated?

### ISSUE THREAD

**Issue by domderen** [argoproj/argo-workflows#7623]
# Summary

Hey, I was reading the [scaling](https://argoproj.github.io/argo-workflows/scaling/) documentation for Argo-Workflows, which says that workflow-controller can only scale vertically, not horizontally. Then I checked the code of the `workflow-controller` and [here](https://github.com/argoproj/argo-workflows/blob/774bf47ee678ef31d27669f7d309dee1dd84340c/workflow/controller/controller.go#L283) I found something that looks like workflow-controller is operating in a cluster of instances, with one leader and multiple workers. 

I'm wondering if my understanding of that part of the code is correct? I tested it out, and scaled my `workflow-controller` to multiple instances, and I saw the load being distributed into those instances. 

If that is correct, I'm wondering if the documentation should be updated to include information that `workflow-controller` can be scaled horizontally? Also, it would be great to document those `workflow-controller` parameters:

- --workflow-workers
- --workflow-ttl-workers
- --qps
- --burst

I blindly updated them by multiplying default values times the number of instances I'm running at a given time, and it seemed to work and allowed me to process a lot more workflows at the same time. But it would be great to know what I'm actually changing to make more educated changes. 

One last thing, it looks like the instance that is elected as a leader is using more resources than other instances of `workflow-controller`. Would it be reasonable to suggest a setup where a leader is created as a separate deployment with custom resource requests/limits, and a different deployment for worker instances?

Thanks in advance for your guidance!

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
The doc is correct - the controller cannot be scaled horizontally - without risk of data corruption. Leader election is used to ensure that only one controller actually operates on workflows. You should expect the leader to use more resources. Leader election is used as a high-available measure, ensuring that is the current leader is terminated for any reason, e.g. zone outage, they another leader will be elected and take over.

Typically you should use pod anti-affinity to ensure different replicas are deployed into different zones. 

Examining the logs should confirm this behaviour.

**Comment by tooptoop4** [comment]
@alexec can we run multi replicas? https://stackoverflow.com/questions/64574129/what-is-the-recommended-number-of-argo-workflow-controller-replicas-in-productio and https://blog.argoproj.io/argo-workflows-v3-0-4d0b69f15a6e suggests yes

**Comment by agilgur5** [comment]
Yea I think the docs could be a lot clearer here:
- https://argoproj.github.io/argo-workflows/scaling/ says it can't be horizontally scaled, but doesn't mention the leader election part for HA, which is closely related
  - these could probably link to the HA docs I suppose to clarify, but would be good for both pages to be consistent
- https://argoproj.github.io/argo-workflows/high-availability/ mentions hot standby and says to run 2 replicas
  - https://blog.argoproj.io/argo-workflows-v3-0-4d0b69f15a6e also says to run 2 replicas
  - There's no replica _limit_ in the charts or docs on that. I imagine more than 2 is fine (e.g. 3 zones), just that anything more than 1 acts as a hot-standby, but the docs don't specifically say you _can_ run more than 2. i.e. I don't know if the leader election feature handles multiple hot-standbys. I imagine yes, but :shrug:

**Comment by agilgur5** [comment]
Addressed the above comments in the docs with #11294
