### ISSUE TITLE
Java client Documentation and Examples 

### ISSUE THREAD

**Issue by dhrsoni19** [argoproj/argo-workflows#7673]
# Summary

Add documentation for java client. 
Also location of the source code in documentation would be very helpful

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by alexec** [comment]
Docs can be found here:

https://github.com/argoproj/argo-workflows/tree/master/sdks/java

This code is generated. So there is not source code in Git. We could create a -source.jar thought. Thoughts?

**Comment by dhrsoni19** [comment]
Hmm, I did find the source jars was hoping to see source code on git. I think the current client is missing a few commits when I compare it to https://github.com/argoproj-labs/argo-client-java
