### ISSUE TITLE
Debug pause docs

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7684]
* Do we have docs for this feature? I see e2e tests but no docs or example in the example folder.

**Comment by alexec** [comment]
@NikeNano @blkperI thinks it would be good to have some docs for this new feature. It'll help users understand how to use it and help promote uptake it too. Would you like to add them?

It'd be great to get them added before we go GA, roughly end of Feb.

**Comment by NikeNano** [comment]
> @NikeNano @blkperI thinks it would be good to have some docs for this new feature. It'll help users understand how to use it and help promote uptake it too. Would you like to add them?
> 
> It'd be great to get them added before we go GA, roughly end of Feb.

I will make a PR for it with some examples, can reuse work for the presentation as well.
