### ISSUE TITLE
Count retries of steps in a workflow

### ISSUE THREAD

**Issue by softwarebloat** [argoproj/argo-workflows#7705]
# Summary
Store somewhere how many times the steps in a workflow hits a retry

# Use Cases
Would be nice to have this info as a Prometheus metric to then query from Grafana 
To then have something like this:  
![image](https://user-images.githubusercontent.com/16540684/151808202-b28d795b-140a-468a-882a-806c4b05ed42.png)

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by AmineAServier** [comment]
A workaround would be to declare "retries" (who is only in container level) as an output parameter and then to label it in out custom metric. But still, if we had that information directly it'd better.

**Comment by moonyoungCHAE** [comment]
I would like to solve this issue! :) 

@softwarebloat You want to see the number of retries for each step in the workflow on the UI, right?
I think i can add retry count to summary.
<img width="293" alt="스크린샷 2023-09-28 오후 3 07 01" src="https://github.com/argoproj/argo-workflows/assets/37133536/cd44839d-b05e-46a1-9a5c-c450d0b6e152">
I wonder if there is a need for me to make it as metrics, either.

@alexec I wonder your opinion on ui for adding retry count field to the summary and whether it might need to make retry count metric.
