### ISSUE TITLE
template.parallelism is limiting the entire workflow instead of just the template

### ISSUE THREAD

**Issue by dmonakhov** [argoproj/argo-workflows#772]
I try to implement common workflow where I have
'M' workers which works in parallel, and each worker should performs 'N' sequential loops.
M and N passed from parameters.  
I try to write it like two level steps, where leaf step performed with parallelism=1 in order to emulate sequential behaviour (see complete example attached), but it limit whole workflow, so only one action performed at a time. How I can implement my example?

**Comment by dmonakhov** [comment]
`# Attempt to implement example with vertical and horizontal scalability                                                                                                                                                                                      
#                                                                                                                                                                                                                                                            
# Imagine we have 'M' workers which work in parallel,                                                                                                                                                                                                        
# each worker should performs 'N' loops sequentially                                                                                                                                                                                                         
#                                                                                                                                                                                                                                                            
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
spec:
  arguments:
    parameters:
      - name: seq-list
        value: |
          [1,2,3,4]
      - name: parallel-list
        value: |
          [1,2,3,4]

  entrypoint: parallel-worker
  templates:
  - name: parallel-worker
    inputs:
      parameters:
      - name: seq-list
      - name: parallel-list
    steps:
    - - name: parallel-worker
        template: seq-worker
        arguments:
          parameters:
          - name: seq-list
            value: "{{inputs.parameters.seq-list}}"
          - name: parallel-id
            value: "{{item}}"
        withParam: "{{inputs.parameters.parallel-list}}"

  - name: seq-worker
    parallelism: 1
    inputs:
      parameters:
      - name: seq-list
      - name: parallel-id
    steps:
    - - name: seq-step
        template: one-job
        arguments:
          parameters:
          - name: parallel-id
            value: "{{inputs.parameters.parallel-id}}"
          - name: seq-id
            value: "{{item}}"
        withParam: "{{inputs.parameters.seq-list}}"

  - name: one-job
    inputs:
      parameters:
      - name: seq-id
      - name: parallel-id
    container:
      image: alpine
      command: ['/bin/sh', '-c']
      args: ["echo {{inputs.parameters.parallel-id}} {{inputs.parameters.seq-id}}; sleep 10"]`

**Comment by jessesuen** [comment]
@dmonakhov `template.parallism` is not expected to limit the entire workflow, just within that invocation of the template. It might be a bug. I'll need some time to investigate.

**Comment by jessesuen** [comment]
This is a bug. Working on the fix.
