### ISSUE TITLE
Cron Workflow show counting time and not execute workflow when hitting 0 seconds

### ISSUE THREAD

**Issue by oranerez** [argoproj/argo-workflows#7720]
## Summary

What happened/what you expected to happen? CronWorkflow to run based on scheduling

What version of Argo Workflows are you running? v3.2.7 (seen previously before upgrade to latest version on v3.1.8)

## Diagnostics

Working with workflows templates and schedule them via cron workflows,
one of the templates has to run in 3 various scheduling times for different days and with different parameters supplied in the cron-workflow level.

The specific template scheduling is working over 2 of the cron-workflows while the 3rd one is counting down in Argo Workflows web GUI and when hit the exact seconds to start nothing happen, counter reset to the next schedule run but no actual workflow being executed, while the other workflows with scheduling running everyday ran and running fine without any issue.

If I hit the 'Submit' button for the same CronWorkflow it will start to run immediately with no issue but I don't need on-demand mechanism and instead Cron one.

Thank you.

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by oranerez** [comment]
Update:
When I query the CronWorkflow for success run I noticed the following fields has been created:
```bash
  annotations:
    cronworkflows.argoproj.io/last-used-schedule: 0 4 * * *

status:
  lastScheduledTime: "2022-02-01T04:00:00Z"
```

While the "skipped" one does not has this nested field in annotations named: 'cronworkflows.argoproj.io/last-used-schedule:' as well as the following appears in the CronWorkflow manifest:
```bash
status: {}
```

Looking in commit: https://github.com/argoproj/argo-workflows/commit/932040848404d42a007b19bfaea685d4b505c2ef
for fixing the 'Skip missed executions if CronWorkflow schedule is changed.' issue I can see there are few functions using the 'c.Annotations[annotationKeyLatestSchedule]' while if that one is empty we are not getting any success for the option to execute the next run, could it be there is a bug in the way of how the controller updated the manifest for managed fields and it's impact randomly CronWorkflow?

**Comment by alexec** [comment]
@simster7 ?

**Comment by ChesoiCarmen** [comment]
Hi
I realise this is a super old, post, but just in case it helps other people.
I had the same issue and it boiled to this : https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#:~:text=Even%20when%20the%20name%20is,no%20more%20than%2063%20characters

CronWorkflow names need to be within the 52 characters limit.

**Comment by slanton-a** [comment]
Old post, but this is the only reference I found for this issue. For me it was the time-zone, CronWorkflow is displaying the countdown based on the local time but if you doesn't provide one it defaults to the server time-zone, confusing.

**Comment by quantm0806** [comment]
Hello @oranerez, I'm facing this issue also. Do you have any more information? How did you overpass this problem?
