### ISSUE TITLE
Add pod priority class to controller

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7733]
We currently schedule the controller at the same priority as workflow pods. This mistake for almost all users, as it can result workflow pods kicking out the controller.

The controller, should, by default, be scheduled with higher priority.

**Comment by rohankmr414** [comment]
@alexec I would like to work on it, could you please provide some information on how to proceed in the task and where the changes needed in the repo. Some code pointers would be really helpful.
