### ISSUE TITLE
Can't parse DataTime type in response when send POST request to create workflow in Java

### ISSUE THREAD

**Issue by jjjjoooo** [argoproj/argo-workflows#7739]
I implemented Java code to send POST request to create a workflow. However, I got the following error,
`Expected BEGIN_OBJECT but was STRING at line1 column 201 path $.meta.creationTimestamp`
I checked source code and found it doesn't register `org.joda.time.DateTime` type when create `gson` in `JSON `class. And  `org.joda.time.DateTime` is the type of `meta.creationTimestamp`. Can someone help me to fix it? Many thanks!
ref link: https://github.com/argoproj/argo-workflows/blob/master/sdks/java/client/docs/WorkflowServiceApi.md#workflowServiceCreateWorkflow

**Comment by sarabala1979** [comment]
@jjjjoooo Are you setting creationTimestamp on your object?

**Comment by jjjjoooo** [comment]
> @jjjjoooo Are you setting creationTimestamp on your object?

No. This version(https://github.com/argoproj-labs/argo-java-client) works. It registers` DateTime` type when initialize Gson instance in `JSON `class.

**Comment by sarabala1979** [comment]
@jjjjoooo Do you like to fix this and submit  PR?

**Comment by jjjjoooo** [comment]
> @jjjjoooo Do you like to fix this and submit PR?

I‘d like to help but I can't find source code of ApiClient.java and I am not familiar with Go.

**Comment by alexec** [comment]
The new Java JAR uses Java8 date time, not JODA. Can you please try a Java 8 date time.

**Comment by jinbu6666** [comment]
Can I ask you some questions about creating workflow using java?
