### ISSUE TITLE
Demo environment does not seem functional

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#7742]
The demo environment mentioned in https://github.com/argoproj/argo-workflows#try-argo-workflows does not seem functional.  I recall that we had an issue with it earlier too but fixed it afterwards. If we are not actively monitoring/using it, should we remove it from the README?

https://workflows.apps.argoproj.io/workflows/argo

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/4269898/152367970-d123c336-4d6b-4619-9f4f-6a6916ec3fb5.png">

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Runbook:

* You up app https://cd.apps.argoproj.io/applications/argo-workflows
* Login 
* Restart argo-server deployment
