### ISSUE TITLE
Suggest going to the archive if workflow not found in UI

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7745]
# Summary

If you deep-link into a workflow, but the workflow is deleted you are shown this:

![image](https://user-images.githubusercontent.com/1142830/152437655-c0ebd4c4-03d1-4234-914e-6272e7870e0f.png)

Add a link to the archive to see if it could be found there.

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by caelan-io** [comment]
Thanks for creating this issue @alexec! This encapsulates issues #2890 and #5824. @JPZ13 or I will circle back once we have an ETA for this.

**Comment by isubasinghe** [comment]
Should be done before 11pm AEST time tomorrow.

**Comment by isubasinghe** [comment]
Done, addressed comment in #5824
