### ISSUE TITLE
Configure a proxy for the docker hub?

### ISSUE THREAD

**Issue by sylock** [argoproj/argo-workflows#7750]
## Summary

Very often now, I get the following error at a step execution: 
```
35s         Warning   Failed                  pod/create-new-argo-project-r6tdk-1089076405   Failed to pull image "argoproj/argoexec:v3.2.2": rpc error: code = Unknown desc = Error loading manifest for target platform: Error reading manifest sha256:bd8ce56bb9dbe7dc641f8d3a605c0e3c508b9efea732aee612549d143dd07c3a in docker.io/argoproj/argoexec: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
Source: oc get events

From my understanding, this image is pulled from the backend code for the sidecars. (because I don't pull myself the argoexec image in the workflow).
We have an artifactory proxy for dockerhub and other docker proxy. Is it possible to configure it at the argo-level?

I'm on Openshift 4.8.28 with PNS.

Currently this issue it makes argo not usable from where it is installed.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
The Argo images are all on quay.io now so you should pull images from there instead of DockerHub, e.g. quay.io/argoproj/argocli:latest

**Comment by sylock** [comment]
Sure but the point is: I don't defined this image myself in the workflow. So I guess it is done from the argo-controller code and I don't have the hand on it.
- Can you confirm that argoproj/argoexec is automatically pulled from sidecars?
- Is it possible to setup a proxy?

**Comment by terrytangyuan** [comment]
They are defined in the installation manifests. Search for "image" in https://github.com/argoproj/argo-workflows/blob/v3.2.8/manifests/install.yaml#L652-L661

**Comment by sylock** [comment]
Very nice. This is what I needed:
```
        - --executor-image
        - quay.io/argoproj/argoexec:latest
```

**Comment by sylock** [comment]
Searching on the doc, I don't see any mention of this workflow-controller option?

https://argoproj.github.io/argo-workflows/

**Comment by terrytangyuan** [comment]
It's in the same manifests link I posted above.

**Comment by sylock** [comment]
Sure, but I think it would be an improvement to the documentation if all options available to argo-workflow and argo-server would be listed and commented in the documentation pages (and not in the manifest).

**Comment by terrytangyuan** [comment]
Feel free to submit PRs to improve the documentation. The reason you are seeing the DockerHub issue is because you are using an older version of Argo where the manifests still point to DockerHub. All new versions have migrated to quay.io so users should not see this rate limit issue any more.

**Comment by sylock** [comment]
ok thanks for the help.
