### ISSUE TITLE
Submit to Google Summer of Code before Feb 14th

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7754]
> CNCF
>  has been participating in the Google Summer of Code during the[
>  last few years](https://www.cncf.io/blog/2021/11/01/16-cncf-interns-graduated-from-google-summer-of-code-gsoc-2021/) and now we are ready to start the 2022 program cycle.
>  
> All CNCF
>  projects are eligible to participate in the Google Summer of Code. Please start working on the project ideas, and submit them via pull request:[
>  https://github.com/cncf/mentoring/blob/master/summerofcode/2022.md#project-ideas](https://github.com/cncf/mentoring/blob/master/summerofcode/2022.md#project-ideas). 
> 
> The deadline
>  to submit the project ideas is February 14, 2022.
> 
> Please
>  reach out to us on the [CNCF
>  mentoring forums](https://github.com/cncf/mentoring/discussions) if you have any questions/suggestions, or file an
>  issue on GitHub:[
> https://github.com/cncf/mentoring](https://github.com/cncf/mentoring).

**Comment by terrytangyuan** [comment]
https://github.com/cncf/mentoring/pull/482
