### ISSUE TITLE
"Invalid type for variable 'received_data'" when getting logs using the python client

### ISSUE THREAD

**Issue by gmouchakis** [argoproj/argo-workflows#7781]
I'm trying to get workflow logs using the python client library but an ApiTypeError exception is raised with message  `argo_workflows.exceptions.ApiTypeError: Invalid type for variable 'received_data'. Required value type is StreamResultOfIoArgoprojWorkflowV1alpha1LogEntry and passed type was str at ['received_data']`. Any solutions or workarounds for this? `_check_return_type=False` did not help.

code:
```
from pprint import pprint

import argo_workflows
from argo_workflows import ApiException
from argo_workflows.api import workflow_service_api

configuration = argo_workflows.Configuration(host="https://localhost:8111")
configuration.verify_ssl = False

api_client = argo_workflows.ApiClient(configuration)
api_instance = workflow_service_api.WorkflowServiceApi(api_client)


namespace = 'argo'
name = 'hello-world-vnsdv'

api_response = api_instance.workflow_logs(namespace, name, _check_return_type=False)
pprint(api_response)
```
Exception Traceback:
```
Traceback (most recent call last):
  File "/home/gmouchakis/git/workflow-service/list.py", line 32, in <module>
    api_response = api_instance.workflow_logs(
  File "/home/gmouchakis/git/workflow-service/venv/lib/python3.8/site-packages/argo_workflows/api_client.py", line 771, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/gmouchakis/git/workflow-service/venv/lib/python3.8/site-packages/argo_workflows/api/workflow_service_api.py", line 2505, in __workflow_logs
    return self.call_with_http_info(**kwargs)
  File "/home/gmouchakis/git/workflow-service/venv/lib/python3.8/site-packages/argo_workflows/api_client.py", line 833, in call_with_http_info
    return self.api_client.call_api(
  File "/home/gmouchakis/git/workflow-service/venv/lib/python3.8/site-packages/argo_workflows/api_client.py", line 408, in call_api
    return self.__call_api(resource_path, method,
  File "/home/gmouchakis/git/workflow-service/venv/lib/python3.8/site-packages/argo_workflows/api_client.py", line 223, in __call_api
    return_data = self.deserialize(
  File "/home/gmouchakis/git/workflow-service/venv/lib/python3.8/site-packages/argo_workflows/api_client.py", line 324, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/home/gmouchakis/git/workflow-service/venv/lib/python3.8/site-packages/argo_workflows/model_utils.py", line 1540, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/home/gmouchakis/git/workflow-service/venv/lib/python3.8/site-packages/argo_workflows/model_utils.py", line 1422, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes,
argo_workflows.exceptions.ApiTypeError: Invalid type for variable 'received_data'. Required value type is StreamResultOfIoArgoprojWorkflowV1alpha1LogEntry and passed type was str at ['received_data']
```

argo version:
```
$ argo version
argo: v3.2.6
  BuildDate: 2021-12-17T20:59:31Z
  GitCommit: db7d90a1f609685cfda73644155854b06fa5d28b
  GitTreeState: clean
  GitTag: v3.2.6
  GoVersion: go1.16.12
  Compiler: gc
  Platform: linux/amd64
```
python client version:
`argo-workflows==6.3.0rc2`

**Comment by terrytangyuan** [comment]
StreamResultOfIoArgoprojWorkflowV1alpha1LogEntry needs to disable the type check via _check_type=False. However it looks like there isn't a way to pass that flag to workflow_logs(). 

@flaviuvadan Did you have this issue too when using the latest version?

**Comment by flaviuvadan** [comment]
@terrytangyuan I started exploring this and it's a bit unclear to me what is really going on. I attempted performing the call with a `pod_name` as well but nothing comes back from the Argo server (I edited the library code on local and added a bunch of print statements around the API response and it's... empty, even if there are logs). I have to dive into this and see whether the server does not return the data at all.

**Comment by gmouchakis** [comment]
bump since this is still an issue.

**Comment by ipythonlamp** [comment]
Same error also happend to me today,  hope to fix it ASAP

**Comment by terrytangyuan** [comment]
I am not investigating this at the moment. @flaviuvadan Have you got a chance to look into this yet?

**Comment by Colstuwjx** [comment]
Hi @terrytangyuan , I found that the exception is thrown at [get_type_error](https://github.com/argoproj/argo-workflows/blob/master/sdks/python/client/argo_workflows/model_utils.py#L1422), I tried to fix this issue by adding the following issue:

```
configuration.discard_unknown_keys = True
```

And it didn't panic anymore, instead, it returned an empty string.

**Comment by Colstuwjx** [comment]
I've tried the raw http api, it also didn't work, returned nothing:

```
➜  ~ curl -k https://127.0.0.1:2746/api/v1/workflows/argo/hello-world-c2gzc/log
➜  ~
```

And when I turned to use argo cli, it worked again:

```
➜  Projects argo logs hello-world-c2gzc -n argo
hello-world-c2gzc: time="2022-03-12T08:26:51.636Z" level=info msg="capturing logs" argo=true
hello-world-c2gzc:  _____________
hello-world-c2gzc: < hello world >
hello-world-c2gzc:  -------------
hello-world-c2gzc:     \
hello-world-c2gzc:      \
hello-world-c2gzc:       \
hello-world-c2gzc:                     ##        .
hello-world-c2gzc:               ## ## ##       ==
hello-world-c2gzc:            ## ## ## ##      ===
hello-world-c2gzc:        /""""""""""""""""___/ ===
hello-world-c2gzc:   ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
hello-world-c2gzc:        \______ o          __/
hello-world-c2gzc:         \    \        __/
hello-world-c2gzc:           \____\______/
```

What's the difference between argo cli and raw http api?

**Comment by Colstuwjx** [comment]
I'm not sure which api the argo-cli used, but according to the network request, I could confirm that we could view the logs via artifacts api: 

```
➜  Projects curl -k https://localhost:2746/artifacts/argo/hello-world-c2gzc/hello-world-c2gzc/main-logs
 _____________
< hello world >
 -------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```

Since our python client has been hardcoded [response_type as None](https://github.com/argoproj/argo-workflows/blob/master/sdks/python/client/argo_workflows/api/artifact_service_api.py#L410) while it call with `get_output_artifact`, I have no idea about which direction to go...

**Comment by alexec** [comment]
Same as this?

https://github.com/argoproj/argo-workflows/issues/7278

**Comment by alexec** [comment]
I've created a fix for this, but I need someone to test. Any volunteers?

**Comment by Colstuwjx** [comment]
Hi @alexec , I'm wondering if it's not client issue, the api that argo ui used was `https://localhost:2746/artifacts/argo/hello-world-c2gzc/hello-world-c2gzc/main-logs`, which was different to `https://localhost:2746/api/v1/workflows/argo/hello-world-c2gzc/log`.

What's the difference between these two apis? I've been tried the second api, as I mentioned before, it [didn't work](https://github.com/argoproj/argo-workflows/issues/7781#issuecomment-1066002900), therefore, I don't think it would be fixed by python client side.

What's more, I've tried your PR change, same exception output as below:

```
(argodev) ➜  client git:(fix-py) ✗ python3.8 setup.py install
(argodev) ➜  client git:(fix-py) ✗ pip3.8 list
Package            Version
------------------ ---------
argo-workflows     0.0.0rc0

# run the call
(argodev) ➜  argo-playground python3.8 test.py
argo_workflows.exceptions.ApiTypeError: Invalid type for variable 'received_data'. Required value type is StreamResultOfIoArgoprojWorkflowV1alpha1LogEntry and passed type was str at ['received_data']
```

**Comment by alexec** [comment]
Yes. I they are different APIs. Both the Java and Python SDKs are broken.

**Comment by Colstuwjx** [comment]
As a result, I don't think this issue has been fixed by #8332, instead, we might need to figure out which api we should use to get logs, and turn to use it in the client library.

**Comment by alexec** [comment]
It’s not possible to fix this AFAIK. OpenAPI does not support SSE. PodLogs and WorkflowLogs both use SSE. You could use a Python SSE client and marshal into objects provided by the SDK.

That could be added to the SDK.

**Comment by alexec** [comment]
Would anyone like to investigate?

**Comment by munachisonwadike** [comment]
> Would anyone like to investigate?

@alexec @sarabala1979 @gmouchakis I noticed this issue has been closed, was it resolved? I am currently using version 3.3.4 and still facing the same error? If it has not, could you kindly shed more light on the workaround with Python SSE Client? :)

**Comment by gmouchakis** [comment]
@munachisonwadike not sure if this is fixed or not and i'm not able to investigate these days.

**Comment by inkinworld** [comment]
same error with latest version.

**Comment by inkinworld** [comment]
> @inkinworld can you try v3.4.0?

we try to use argo-server v3.4.0 with python sdk 6.4.0, still occurs this error.

**Comment by rajaie-sg** [comment]
Also ran into this issue on v3.4.1, a temporary workaround I used is to set the "preload_content" flag to "False"

```
wf_client.workflow_logs(
                    namespace=constants.NAMESPACE, name=workflow_name, _check_return_type=True,
                    log_options_insecure_skip_tls_verify_backend=True, _check_input_type=True,
                    log_options_container="main-container", _preload_content=False
                )
```

and then parse the result with `api_response.read().decode("utf-8")`

not ideal..but unblocks us for now

**Comment by edwardzjl** [comment]
Same error with python sdk 6.4.3 and argo server v3.4.4
