### ISSUE TITLE
UI: filter dropdown bar arrow is half hidden

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#7789]
v3.3.0-rc3

Examples see the dropdown for workflow template and cron workflow.

<img width="325" alt="Screen Shot 2022-02-07 at 1 26 38 PM" src="https://user-images.githubusercontent.com/4269898/152849275-dd0e1c94-e401-474e-8d32-e5040814d24a.png">

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by agilgur5** [comment]
Fixed in https://github.com/argoproj/argo-ui/pull/178, so we just need to update `argo-ui` here
