### ISSUE TITLE
Delete `helpwanted` label

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7794]
The original goal of this label was to encourage users to fix issues themselves. I don't see any evidence of that happening.

@sarabala1979 @terrytangyuan

**Comment by alexec** [comment]
Done.

**Comment by terrytangyuan** [comment]
Do we need an alternative like “contributions welcomed”?

**Comment by alexec** [comment]
I don't think it would affect behaviour either. Better would be organisations committing to certain areas :)

**Comment by terrytangyuan** [comment]
Sounds good
