### ISSUE TITLE
Remove the deprecated `docker` executor

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7795]
Remove the executor code. Remove `docker` binary from executor.

**Comment by terrytangyuan** [comment]
This would also remove the `gzip` binary: https://github.com/argoproj/argo-workflows/blob/6566396666163198f2520c9a0790b01ada3863fd/workflow/executor/docker/docker.go#L445

**Comment by blkperl** [comment]
@alexec are we ready for PRs that remove this to be opened?

**Comment by terrytangyuan** [comment]
@blkperl I actually have something in progress locally but let me know if you’d like to work on it and I’ll re-assign to you.

**Comment by alexec** [comment]
We also need to remove other executors. Plenty for all.

**Comment by blkperl** [comment]
@terrytangyuan I will grab a different one, I didn't notice you were assigned 👍🏻
