### ISSUE TITLE
Replace the `jq` with pure Go

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7799]

**Comment by terrytangyuan** [comment]
The use of `jq` is tied to a particular functionality `param.ValueFrom.JQFilter`. I am not sure if any rewrite in pure Go would be fully featured. One way to remove this is to expose this logic as a custom command that users can specify, e.g. `kubectl get xxx -o json | jq -rc xxx` or `kubectl get -o xxx  jsonPath=xxx` and users can choose to provide a custom executor image that includes the necessary binaries.

**Comment by alexec** [comment]
The goal is to create a distroless image, but I think we can probably keep JQ to archive that.

**Comment by alexec** [comment]
I think we might not need this. JQ is a standalone binary. We just need to copy it to the container.
