### ISSUE TITLE
Replace use of the `tar` with pure Go in the Kubernetes API executor

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7800]
This maybe obviated by #7802 .

**Comment by terrytangyuan** [comment]
Assigned to @ehienabs

**Comment by alexec** [comment]
I think, as this is superceeded by #7802, maybe we could work on that instead?

**Comment by terrytangyuan** [comment]
You are right. @ehienabs Would [that](https://github.com/argoproj/argo-workflows/issues/7802) be something you are interested in working on?

**Comment by ehienabs** [comment]
@terrytangyuan Of course. I am wondering though, would you still be staying on as my mentor?

**Comment by terrytangyuan** [comment]
Yes
