### ISSUE TITLE
`argo submit --strict=false` option not clearly documented

### ISSUE THREAD

**Issue by ndamclean** [argoproj/argo-workflows#7806]
# Summary

The `--strict` option for `argo submit` is a flag-style argument where the default value is `true`.

~This means the argument is useless because it is not possble to set `strict` to `false` via the CLI.~

~The CLI should support syntax similar to one of the two following options:~
```
argo submit --strict false ...
```
~or~
```
argo submit --no-strict ...
```
The CLI documentation does not make it clear how you would set this to false (`--strict=false`). Most of the other CLI options that take a value are shown used with spaces between the argument and the value (e.g. `--status string`).

# Use Cases

I want to run `argo submit --dry-run` without strict validation for debugging purposes.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
You should be able to set it via `--strict=false`.

**Comment by ndamclean** [comment]
@terrytangyuan I see that works. Thanks!

I do think this could be made clearer in the CLI help text as it was not obvious to me.

**Comment by terrytangyuan** [comment]
Other boolean flags such as `--log`, `--watch`, and `--wait` are handled in the same way so the use of `--strict` should be pretty straightforward. Feel free to submit a PR to improve the documentation though.

**Comment by agilgur5** [comment]
`--secure=false` is one with a `true` default that users often have set.

Given that no PR was made and that this has received no upvotes in 2+ years, I'm going to close this out as not necessary
