### ISSUE TITLE
Remove `github.com/prometheus/client_model` dependency

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-workflows#7815]
# Summary

The module is deprecated and is only used by tests.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by khanjasir90** [comment]
@terrytangyuan i would love to take this up

**Comment by blkperl** [comment]
Hi @khanjasir90,

Thanks for volunteering. I've assigned the issue to you. Please do reach out to Terry or I if you have questions either here or on the slack in #argo-contributors.

**Comment by khanjasir90** [comment]
sure! thanx

**Comment by prithvihv** [comment]
how can i request for a reviewer on https://github.com/argoproj/argo-workflows/pull/8114 @blkperl

**Comment by blkperl** [comment]
One of the commiters will review in the next few days.  I don't believe there is an official request process. If you nobody comments on the PR, you can ask on Slack in #argo-contributors.

**Comment by blkperl** [comment]
Closing until there is a migration path documented upstream.
