### ISSUE TITLE
Update `colinmarc/hdfs` to  version 2.x

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-workflows#7816]
# Summary

The 2.x releases notes contains breaking changes: https://github.com/colinmarc/hdfs/releases/tag/v2.0.0

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by yashvardhan-kukreja** [comment]
Hi @blkperl , I'd love to pick this up as I think it would be a good place for me start contributing to argo-workflows :)

**Comment by blkperl** [comment]
Thanks for the volunteering @yashvardhan-kukreja. If there are breaking changes please make sure to document them on the PR.

**Comment by alexec** [comment]
Is there somekind of stand-alone HDFS server?

**Comment by terrytangyuan** [comment]
Removing assignee as there hasn't been any progress. Feel free to update here if you are still working on it.
