### ISSUE TITLE
Review fuzzers

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7823]
Review the oss-fuzz and see what we have and what we need.

**Comment by blkperl** [comment]
We could also investigate adding our own fuzz tests coming in 1.18 https://go.dev/blog/fuzz-beta

**Comment by terrytangyuan** [comment]
@blkperl We already have fuzzers now and it will use CNCF's computational resources to run fuzz tests.

**Comment by alexec** [comment]
@hblixt I don't want to do this. I think there are better places to focus our energy.

**Comment by hblixt** [comment]
There were a few more fuzzers added as part of the latest assessment, so we're probably in pretty good shape now

**Comment by agilgur5** [comment]
For reference, the CNCF fuzzers are here: https://github.com/cncf/cncf-fuzzing/tree/07bfece/projects/argo
