### ISSUE TITLE
Improve managed namespace docs

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-workflows#7838]
# Summary

1. It needs to be clearer when/why someone might choose a managed namespace install over a namespace install.
2. It needs to be clearer where the `--managed-namespace` arg needs to be set (I think in both workflow-controller and argo-server?).

Feel free to copy/paste from my [StackOverflow answer](https://stackoverflow.com/a/71052112/684776) if it's useful. (I think all SO answers are licensed CC-by-attribution, but I hereby license it CC0 or public domain or whatever makes it copy/pasteable. :-P)

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by mahi072** [comment]
I would like to work on this issue.

**Comment by agilgur5** [comment]
Hmm I think this was already added in #2292: https://argoproj.github.io/argo-workflows/managed-namespace/
