### ISSUE TITLE
I would like a ~mentor~ GSoC

### ISSUE THREAD

**Issue by LaloLoop** [argoproj/argo-workflows#7849]
# Summary
I just saw the post about GSoC and I’d like to work on #7588 or #1915 , or any other controller related tasks :)

# Use Cases

At my current job we are already using Argo CD Workflows, Events and some of the other components of the Argo project. I do devops and will mostly benefit from the improvements. I know some Go and Typescript as well.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
@sarabala1979 @alexec @simster7 Anyone vulunteers?

**Comment by terrytangyuan** [comment]
@alexec Looks like the issue description already links to a couple of issues that @LaloLoop is interested in working on. Those are non-GSOC issues.

**Comment by LaloLoop** [comment]
Oh my bad, I completely misunderstood the GSoC and the mentors process. My interest is to contribute features for the GSoC and I just saw the page for available projects.
I see some people have already raised interest for some of them. If available, I'd like to work on this one

https://github.com/argoproj/argo-workflows/issues/3587

Thank you both.

**Comment by terrytangyuan** [comment]
If you are interested in GSoC, take a look at https://github.com/argoproj/argo-workflows/blob/master/docs/mentoring.md#how-to-participate-google-summer-of-code

I am closing this for now. If you are looking for non-GSoC or general mentoring, feel free to re-open this.
