### ISSUE TITLE
Allow 'http' as an option for artifact upload

### ISSUE THREAD

**Issue by 0xdevalias** [argoproj/argo-workflows#785]
From Slack discussion with @jessesuen: Currently HTTP artifacts are 'input only'. It would be cool if we were able to upload them as well.

There are 2 main ways that I see this could be implemented:
* There is typical ‘form upload’ type HTTP stuff, that any upload field on a website would use
* The other way I would do it is more a ‘http api’ style, where it is a POST (potentially structured in some way) of the file contents, maybe as json/similar.

The second option is probably getting more nuanced and less generic. That sort of method might make more sense in somehow supporting ‘artifact plugins’, where these specific things could be ‘plugged in’ to the current architecture. That way I could say “upload this file as DevaliasJsonPluginStyle” and it would ‘just work’.

My main use case/thought for this is to support large file outputs (eg. too big to use `globalOutput`) back to some wrapping 'golang worker code', without the 'overhead' of having to upload then re-download from minio/etc.

Ideally in this case, i'd like to create a tiny API endpoint that accepts some kind of POST, and then uses the uploaded file directly 'in code', without it ever having to touch disk.

Currently we use a similar method with the http 'download' to populate a 'file' into the argo workflow from an in-memory store.

**Comment by alexec** [comment]
@rohankmr414 I reverted your commit because it was causing master build to fail with a panic. 

You need to guard `UsernameSecret` and `PasswordSecret` with a nil-check.
