### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by pavan541cs** [argoproj/argo-workflows#7850]
# Summary

I just saw the post about GSoC and I’d like to work on https://github.com/argoproj/argo-workflows/issues/7618 or https://github.com/argoproj/argo-workflows/issues/1915, or any other controller related tasks :)

# Use Cases

At my current job we are already using Argo CD . I do DevOps and will most benefit from the improvements. I know some Go.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Is this for general mentoring or GSoC mentoring? For GSoC, please refer to: https://github.com/argoproj/argo-workflows/blob/master/docs/mentoring.md#how-to-participate-google-summer-of-code

**Comment by pavan541cs** [comment]
I am looking for general mentoring and would love to contribute to enhancing argoCD by working and delivering a feature.

**Comment by terrytangyuan** [comment]
This is Argo Workflows repo though. Not Argo CD. You might want to discuss that in Argo CD instead. In the meantime, we'd be happy to mentor any issues you are interested in picking up in Argo Workflows.

**Comment by pavan541cs** [comment]
I would love to work on #7618 and #1915 issues

**Comment by alexec** [comment]
Hi @pavan541cs - I'll be your mentor. What timezone are you in? We can have a Zoom to discus.

**Comment by pavan541cs** [comment]
I am in IST timezone

**Comment by alexec** [comment]
Ah. There is no good time overlap between IST and PST for doing meetings. Options:

1. We can try and find you mentor in a timezone that overlaps.
2. We can do mentoring async.

What would you like?

**Comment by alexec** [comment]
Hi - is seen we’ve not had recent activity.

**Comment by terrytangyuan** [comment]
It's been more than a month without activities. Closing this for now.
