### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by khanjasir90** [argoproj/argo-workflows#7866]
I need a mentor to get started with the Agro Project.

**Comment by khanjasir90** [comment]
Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).
Answer : Yes I have read the mentoring guide.

Question : What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?
Answer : I am familiar with React and Typescript.Learning Kubernetes and Go

Question : Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).
Answer : Yes I would like to work on #7801 and #7819

**Comment by terrytangyuan** [comment]
The issue to be worked on https://github.com/argoproj/argo-workflows/issues/7815.

**Comment by terrytangyuan** [comment]
Would you like to be a mentor on this? @blkperl

**Comment by blkperl** [comment]
@terrytangyuan Yep

@khanjasir90 Let me know if you would like to zoom or have a slack conversation about #7815 or any of the other various getting started items.
