### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by SkRai0** [argoproj/argo-workflows#7867]
I need a mentor to get started with the argo project.

**Comment by terrytangyuan** [comment]
Could you answer the questions in this issue template? https://github.com/argoproj/argo-workflows/blob/master/.github/ISSUE_TEMPLATE/mentoring_request.md

**Comment by SkRai0** [comment]
I answered the questions and pushed the README file.

**Comment by terrytangyuan** [comment]
Where did you answer the questions and what README file are you referring to?

**Comment by SkRai0** [comment]
Here is the link where I have answered the questions: https://github.com/SkRai0/argo-workflows/blob/master/.github/ISSUE_TEMPLATE/mentoring_request.md

> Could you answer the questions in this issue template? https://github.com/argoproj/argo-workflows/blob/master/.github/ISSUE_TEMPLATE/mentoring_request.md

**Comment by terrytangyuan** [comment]
Please answer questions here directly so that we can see if other potential mentors might be able to mentor.

**Comment by SkRai0** [comment]
Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).

Answer: Yes I have read the mentoring guide.

What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?

Answer: I have previous experience in React.

Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

Answer: I would like to work with issue #7920

**Comment by terrytangyuan** [comment]
@SkRai0 Would you still like to work on #7920?

@tczhao Would you like to be a mentor on that issue?

**Comment by tczhao** [comment]
Sure thing.
@SkRai0 if you are still keen to work on the issue, you can first set up your dev environment by following https://github.com/argoproj/argo-workflows/blob/master/docs/running-locally.md

**Comment by tczhao** [comment]
Hi @SkRai0 , are you still interested in working on issue #7920 ?
