### ISSUE TITLE
Mentoring request

### ISSUE THREAD

**Issue by CIPHERTron** [argoproj/argo-workflows#7870]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: Yes

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: I've been making UIs with React & TS for over a year and I also have worked with K8s and Go during my past internship at CNCF. Would love to contribute!

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: I have the project up and running in my local system and would like to work on #7378. It would be great if I could get some pointers on the same.

If I manage to fix issue #7378 quickly then I'm also interested in taking up #7405

**Comment by alexec** [comment]
Hi @CIPHERTron,

I'd like to offer to be your mentor. Let me know if that is acceptable to you.

It sounds like you've gotten started already, but not submitted a PR yet. I've added a brief comments to both the issue hoping to give some pointers for direction. You may need more. We can have a Zoom if you like, use Slack, or message via the issues.

Alex

**Comment by CIPHERTron** [comment]
> I'd like to offer to be your mentor. Let me know if that is acceptable to you.

Hey @alexec thank you so much for the offer. I would love to have you as my mentor. Sorry for the late response as I was sick since the past 2 days

>  It sounds like you've gotten started already, but not submitted a PR yet.

Nope, I haven't submitted a PR. I had a couple of questions that are acting as a blocker for me as of now.

> We can have a Zoom if you like, use Slack, or message via the issues.

A zoom call would be really helpful. Also, I'm available in CNCF slack. Both of them work for me. Let me know what works for you and I'll also send a DM to you on slack.

**Comment by alexec** [comment]
Zoom might be easiest. When's good for you? Which TZ are you in?

**Comment by CIPHERTron** [comment]
> Zoom might be easiest. When's good for you? Which TZ are you in?

I'm in the IST Timezone and it's 2:00 AM here right now.
https://time.is/IST

**Comment by alexec** [comment]
Hi - I'm in Pacific Time, so we don't have overlapping hours :(

For the template-defaults - I think there is a bug in the UI where it looks at the wrong field - it's looking at spec, but it should be looking at status.storeWorkflowSpec.

To start the UI, run `make start UI=true` and open http://localhost:8080.

**Comment by CIPHERTron** [comment]
> Hi - I'm in Pacific Time, so we don't have overlapping hours :(

Yeah.Time zones can be daunting :(

> To start the UI, run make start UI=true and open http://localhost:8080/.

I already have the local setup ready i.e. both UI and argo-server API but am unable to figure out which route to go in-order to find the template defaults.

**Comment by CIPHERTron** [comment]
@alexec isn't the required UI supposed to be here in the workflow templates?

<img width="1438" alt="Screenshot 2022-02-21 at 11 35 55 PM" src="https://user-images.githubusercontent.com/56754747/155007259-0deccb71-c475-4335-b3c8-9432fcb25ea8.png">

**Comment by CIPHERTron** [comment]
I'm not able to hunt down where the `env` field is present :(

**Comment by CIPHERTron** [comment]
NVM. I found it 💪🏻 

https://github.com/argoproj/argo-workflows/blob/79fc4a9bea8d76905d314ac41df7018b556a91d6/ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx#L332

If you check here, we are actually checking if the container has any `env` with the help of the `hasEnv` function. If we get a `true` then we are rendering the `<EnvVar />` component which will display the env otherwise we aren't displaying anything or just rendering an empty div.

So, I think this is more of error handling and not what issue #7378 describes it to be. So, when we don't have any `env`, we could simply print _no envs found_ or something similar. 

Thoughts? @alexec

**Comment by alexec** [comment]
I’d need to check the code, but maybe WorkflowNodeContainer Is being passed the container from .spec, not from .status.storedWorkflowSpec?

**Comment by alexec** [comment]
@CIPHERTron how is it going so far?

**Comment by CIPHERTron** [comment]
Heyy @alexec 👋🏻 
I recently moved out thus there was a delay in response.

> WorkflowNodeContainer Is being passed the container from .spec, not from .status.storedWorkflowSpec?

I tried to search from where the `WorkflowNodeContainer` is being passed but I didn't find it anywhere. Kinda stuck atm 

> If you check here, we are actually checking if the container has any env with the help of the hasEnv function. If we get a true then we are rendering the <EnvVar /> component which will display the env otherwise we aren't displaying anything or just rendering an empty div.

This was the only conclusion I was able to find :(

**Comment by alexec** [comment]
Sorry. I seem to not have seen your reply. Did you manage to fix?
