### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by adeniyistephen** [argoproj/argo-workflows#7877]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: Yes

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: Yes I'm a software engineer with 1 and half years of Golang experience, 1-year experience with Kubernetes but I don't have experience with React and typescript. I also worked with the Kubernetes API on my Linux Foundation internship to build an image vulnerability scanner.

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: Yes!  issue #7405, #4867, and #7819 look good to me, But I'm also interested in any project that would make me learn and grow in my Golang, Linux, and Kubernetes ecosystem career.

**Comment by alexec** [comment]
Hi @adeniyistephen can I ask what TZ you're in please?

**Comment by adeniyistephen** [comment]
Hello @alexec Thank you for reaching out, I'm in the (UTC +1/ GMT +1) time zone.

**Comment by terrytangyuan** [comment]
I can be a mentor for this one. @adeniyistephen Looks like you might want to re-pick issues: one of them is closed and another one is front-end issue. I am not 100% sure if https://github.com/argoproj/argo-workflows/issues/4867 would be a good one to work on.

**Comment by adeniyistephen** [comment]
Hello, @terrytangyuan Thank you for letting me know more about the issues, I think #4561 is still open? @alexec am I right.

**Comment by terrytangyuan** [comment]
I assigned that issue to you.

**Comment by adeniyistephen** [comment]
Awesome! please what would be the next steps?

**Comment by terrytangyuan** [comment]
Try take a look at the issue/discussions and let me know if you have any specific questions.

**Comment by adeniyistephen** [comment]
@terrytangyuan Thank you, I believe I understand the issue and the use case 
- but just to be clear we need to allow the controller to be able to create a maximum of 5k pods not to max out our Kubernetes cluster for safety?
- and is there a slack channel where I should be part of and I might need help setting up my environment if there's a specific way for the project.

**Comment by terrytangyuan** [comment]
> @terrytangyuan Thank you, I believe I understand the issue and the use case
> 
>     * but just to be clear we need to allow the controller to be able to create a maximum of 5k pods not to max out our Kubernetes cluster for safety?

Yes
> 
>     * and is there a slack channel where I should be part of and I might need help setting up my environment if there's a specific way for the project.

https://argoproj.github.io/community/join-slack
I think #argo-contributors would be the best place.

**Comment by adeniyistephen** [comment]
Awesome, please let me know if there's anything I should do next.

**Comment by terrytangyuan** [comment]
Have you looked into the issue and set up your local dev environment yet? Let me know if you have any specific questions.

**Comment by adeniyistephen** [comment]
I have looked into the issue, that was the first task, which I asked some questions about it in our previous messages.
No, I haven't set up my local dev environment yet, I would love pointers/input into setting it up in a good manner. Thank you.

**Comment by terrytangyuan** [comment]
Check out the existing documentation: https://argoproj.github.io/argo-workflows/running-locally/

**Comment by terrytangyuan** [comment]
There are many other documentation exist for developers. See "developer guide" section in https://argoproj.github.io/argo-workflows/

**Comment by terrytangyuan** [comment]
Any progress on https://github.com/argoproj/argo-workflows/issues/4561?
