### ISSUE TITLE
pypi package for rc missing Licence

### ISSUE THREAD

**Issue by bchalk101** [argoproj/argo-workflows#7881]
## Summary

What happened/what you expected to happen?
The tar/package of argo-workflows on pypi, is missing the LICENSE file, whereas in previous versions this was included. We internally use conda, and wanted to bump the conda-forge recipe, however, it has a dependency on the LICENSE file and therefore is not publishing. See https://github.com/conda-forge/hera-workflows-feedstock/pull/10 

What version is it broken in?
v6.0.0rc and higher

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by bchalk101** [comment]
Happy to do a MR for this

**Comment by terrytangyuan** [comment]
Yes feel free to submit a fix for this.
