### ISSUE TITLE
argo lint always print "found nothing to lint in the specified paths, failing..."

### ISSUE THREAD

**Issue by spothound** [argoproj/argo-workflows#7887]
## Summary

I have recently started using argocd and I am interested in adding automatic gitlabci pipelines to our argocd workflow. I tried to make some tests with the argo client linter to see if I could use this tool to prevent syntax error or similar but **I always get the message "found nothing to lint in the specified paths, failing..."** when I run this on any argocd repository.

I have even created an invalid yaml file on purpose, when I run argo lint on the directory containing this file I get:
```
ERRO[2022-02-15T10:52:51.347Z] yaml file at index 0 is not valid: error converting YAML to JSON: yaml: line 4: could not find expected ':' 
✖ found nothing to lint in the specified paths, failing...
```
So, even when argo find an error in one file it reports that it found nothing to lint in the path...

I am wondering if this client tool may be broken :)

|     |     |
|-------------------|----------------------------------------------|
| **argo version:**         | **v3.3.0-rc4**                               |
| **BuildDate:**    | **2022-02-08T20:01:35Z**                     |
| **GitCommit:**    | **032520f026f909ff110972aa50c4651280a68022** |
| **GitTreeState:** | **clean**                                    |
| **GitTag:**       | **v3.3.0-rc4**                               |
| **GoVersion:**    | **go1.17.6**                                 |
| **Compiler:**     | **gc**                                       |
| **Platform:**     | **linux/amd64**                              |

## Diagnostics

Create an YAML file with this content:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
met
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
  namespace: default
```
run 

```
argo lint ./myfile.yaml
```

I don't know if I am missing something here, any help would be appreciated.

**Comment by terrytangyuan** [comment]
This is for linting workflows|workflowtemplates|cronworkflows|clusterworkflowtemplates.

**Comment by spothound** [comment]
Oh, I see, so for any other resource managed by argo, I guess I'll just check yaml syntax with a yaml linter and that's all. 

Sorry I didn't notice it was only for those, thanks!
