### ISSUE TITLE
Request help, can realize drawing the way to generate workflow?

### ISSUE THREAD

**Issue by LingHuaHui** [argoproj/argo-workflows#7892]
1. Can Argo UI add workflow by drawing?
2. The flow chart drawn by Activiti is imported into Argo to implement the workflow.

**Comment by terrytangyuan** [comment]
This issue template is only for mentoring. Not feature request. 

Also this is a duplicate of https://github.com/argoproj/argo-workflows/issues/5610 so I am closing this.

**Comment by LingHuaHui** [comment]
Asking for help, can you now implement the way drawing generates workflow?

**Comment by LingHuaHui** [comment]
> This issue template is only for mentoring. Not feature request.
> 
> Also this is a duplicate of #5610 so I am closing this.

Asking for help, can you now implement the way drawing generates workflow?

**Comment by terrytangyuan** [comment]
No that's not supported which is why the linked issue is still open.

**Comment by LingClassmate** [comment]
> No that's not supported which is why the linked issue is still open.

Is there any requirement that can be realized:
Flowchart drawing tools such as Activiti and Camunda can be used to design a flowchart and then be connected to or imported into Argo Workflow for execution
