### ISSUE TITLE
Does pod names v2 result in too long pod names?

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7896]
Pod names can only be so long:

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names

We don't want to break any workflows when you enable this feature. So we should trim the pod name.

Maybe we already do this?

**Comment by alexec** [comment]
@JPZ13 can you check pls?

**Comment by JPZ13** [comment]
@alexec Happy to. Can you assign to me?

**Comment by isubasinghe** [comment]
@alexec see the long case here: https://github.com/argoproj/argo-workflows/blob/master/workflow/util/pod_name_v2_test.go
And this: https://github.com/argoproj/argo-workflows/blob/master/workflow/util/pod_name.go#L68

I am closing this because the generation seems to take care of this.
