### ISSUE TITLE
Save containerSet logs in logs archive

### ISSUE THREAD

**Issue by noam-codefresh** [argoproj/argo-workflows#7897]
# Summary

Currently, the logs archive only saves the "main" container logs. When using a ContainerSet, a lot of information is being lost once the pod is removed from the cluster.
I propose saving all the container logs in the archive (with the exception of the `init` and `wait` containers).

# Use Cases

In many cases, immediately or shortly after a wf has completed its run, its pod are getting garbage collected. In order to later view the Workflow's logs, it is very handy to set up a log archive in S3 (or similar storage solutions). It seems natural to expect the ContainerSet logs to also end up in the same log archive.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Potential duplicate but this is more related to containerSet: https://github.com/argoproj/argo-workflows/issues/7830 

I don't think we support saving logs for non-main containers but we probably should support it for containerSet containers.

**Comment by noam-codefresh** [comment]
I have PR *almost* ready for it. i still need to iron out some kinks, but the main flow is working for me.
Regarding the archived-workflow-archive-logs - I am not sure it is directly related.

**Comment by RyanW8** [comment]
Is there an ETA on when this will be completed & merged?
