### ISSUE TITLE
Start/End times in UI missing detailed timestamp (HH:MI:SS)

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#7920]
UI start/end times don't show exact timestamp ie HH:MI:SS . When debugging a failed workflow the exact minute/second is very useful to know.

![image](https://user-images.githubusercontent.com/33283496/154706143-ef11130e-e94b-49dc-91aa-817f54bce8cf.png)

**Comment by alexec** [comment]
Timestamps are rendered using the `<Timestamp/>` component:

https://github.com/argoproj/argo-workflows/blob/16fef4e5498fac88dc80d33d653c99fec641150d/ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx#L112

https://github.com/argoproj/argo-workflows/blob/16fef4e5498fac88dc80d33d653c99fec641150d/ui/src/app/shared/components/timestamp.tsx#L5

To fix this, modify that component to render the time too. E.g. `2pm (1h ago)`

**Comment by yavulan** [comment]
![argo-workflows](https://user-images.githubusercontent.com/7360866/169504314-1d457e35-e59f-418b-be36-edda30d17cd7.png)

When you hover on time, the timestamp is shown.
In my opinion, this change might degrade UX.

**Comment by YashasviChaurasia** [comment]
@tooptoop4 @alexec  I would like to work on this issue.

**Comment by ibotdotout** [comment]
I would like to pick up this one.

**Comment by tooptoop4** [comment]
superseded by https://github.com/argoproj/argo-workflows/issues/12943

**Comment by agilgur5** [comment]
@tooptoop4 This issue was fixed by #9834 so there is nothing to supersede.

#12943 is about the format of the time, not the fidelity of it.
