### ISSUE TITLE
Ask for timezone in mentoring guide

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7923]
We should ask both mentors and mentees what TZ they are in, as it is not great to mentor people in IST if you are is PST.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by tczhao** [comment]
Maybe we can specify/request the TZ in both

- mentoring document
- mentoring issue template

**Comment by alexec** [comment]
Maybe just as - are you in:

* Americas
* Europe, Middle East or Africa (EMEA)
* Asia Pacific (APAC)
