### ISSUE TITLE
Windows Release  is failing in  v3.3.0-rc5

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#7935]
<img width="914" alt="image" src="https://user-images.githubusercontent.com/33908564/154860991-effeb278-c567-4f45-bfeb-5411c06104fb.png">

## Summary

What happened/what you expected to happen?

What executor are you using? PNS/Emissary

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml

```

What executor are you running? PNS/Emissary

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
This has already been fixed https://github.com/argoproj/argo-workflows/issues/7931

**Comment by terrytangyuan** [comment]
You’ll probably want to cherry pick that Windows fix.

**Comment by sarabala1979** [comment]
I took the entire master for RC. Let me check it the PR merged after I  merged
