### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by PradeepLoganathan** [argoproj/argo-workflows#7937]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: Yes

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer:  I have extensive experience on Kubernetes and have deployed multiple systems using K8s as the underlying container orchestration system. I have primarily worked on Microsoft Stack (dotnet, Azure etc. ). I have good experience with typescript, Angular and other web frameworks. A substantial portion of my development workflow is on Linux in WSL2. I am learning GO and would like to augment it by contributing to solving a real-world problem.

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: I would be interested in helping with https://github.com/argoproj/argo-workflows/issues/6924 and https://github.com/argoproj/argo-workflows/issues/6888

**Comment by alexec** [comment]
Hi @PradeepLoganathan - can I ask what TZ you're in please?

**Comment by sarabala1979** [comment]
@PradeepLoganathan Let me know when you ready to contribute the above issue

**Comment by sarabala1979** [comment]
Hi @PradeepLoganathan Do you need any help

**Comment by PradeepLoganathan** [comment]
Hello @sarabala1979 apologies for the delayed response. I am currently available to get started. What is the best way to reach you directly and get started please.

**Comment by sarabala1979** [comment]
you can find me on slack or my email sarabala1979@gmail.com.

**Comment by terrytangyuan** [comment]
@PradeepLoganathan Any update on this?
