### ISSUE TITLE
How to patch workflow with K8s client-go api

### ISSUE THREAD

**Issue by journey-wang** [argoproj/argo-workflows#7938]
# Summary

How to patch worfklow annotations/labels?

# Use Cases

I need to update the workflow annotations/labels via api, but unfortunately, argo sdk didn't provide this API. WIth kubectl, like kubectl label/annotation, or kubectl edit workflow <workflow-name>, this can be easilily.

But I wonder how to do this work via Kubernetes go client sdk?

Thanks very much.

**Comment by alexec** [comment]
Yes. Just use the standard client-go for this.
