### ISSUE TITLE
Why is Curl unable to access nginx?

### ISSUE THREAD

**Issue by LingClassmate** [argoproj/argo-workflows#7953]
`apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: generate-message
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"
 
  - name: generate-message
    container:
      image: nginx:latest
      command: [sh, -c]
      args: ["curl http://localhost | tee /tmp/hello_world.txt"] 
    outputs:
      artifacts:
      - name: hello-art          
        path: /tmp/hello_world.txt
 
  - name: print-message
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]`

An error：
`curl: (7) Failed to connect to localhost port 80: Connection refused`

**Comment by LingClassmate** [comment]
`args: ["curl http://localhost | tee /tmp/hello_world.txt"]`
I want to use curl to access the nginx container and transfer the data to the consumer

**Comment by alexec** [comment]
I'm really not sure how to help you. This is core Kubernetes, not really Argo. Just curl the service name, endpoint, or load-balancer.
