### ISSUE TITLE
I Would like a mentor

### ISSUE THREAD

**Issue by ehienabs** [argoproj/argo-workflows#7957]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: Yes I have,

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: I have experience with Kubernetes but I am very excited about learning Go.

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: https://github.com/argoproj/argo-workflows/issues/7405

**Comment by terrytangyuan** [comment]
You mentioned that you'd like to learn Go but the issue you linked to is a front-end issue which requires knowledge in React.

**Comment by ehienabs** [comment]
Thank you for getting back to me Terry. I have found some issues I would love to work on. I think I am interested in tech debt. So I found some issues I am interested in.
https://github.com/argoproj/argo-workflows/issues/7829
https://github.com/argoproj/argo-workflows/issues/7815
https://github.com/argoproj/argo-workflows/issues/7802
https://github.com/argoproj/argo-workflows/issues/7800
https://github.com/argoproj/argo-workflows/issues/7785
https://github.com/argoproj/argo-workflows/issues/7803

**Comment by terrytangyuan** [comment]
Perhaps try take a look at this one? https://github.com/argoproj/argo-workflows/issues/7800

The rest of them either already have an assignee or non-trivial as first contributors. 

I can be your mentor.

**Comment by ehienabs** [comment]
This looks really great and I would be so honoured. Thank you so much!

**Comment by alexec** [comment]
How’s this going?

**Comment by ehienabs** [comment]
@alexec It's going great. @terrytangyuan and I are working together on this. He has so far given me resources to learn Golang, plus the Youtube Vid introducing new contributors to the project, as a sort of on-boarding.
We are currently touching base on Slack.
Thank you so much for asking.

**Comment by terrytangyuan** [comment]
Closing since this hasn't been active for more than a month. The assigned issue has already been addressed. Feel free to re-open if you still need mentoring.
