### ISSUE TITLE
Argo CLI support for custom request headers

### ISSUE THREAD

**Issue by tatodorov** [argoproj/argo-workflows#7985]
# Summary

Add support for setting custom HTTP headers to `argo` CLI, similar to `argocd` `-H, --header`.

# Use Cases

When Argo Workflows is configured behind IAP proxy like Cloudflare Access, we need to set a custom header with key `cf-access-token` and the actual token as a value.
Otherwise, when we execute `argo list`, we face the following error:
```bash
FATA[2022-02-23T22:38:56.530Z] invalid character '<' looking for beginning of value
```
This is already implemented in `argocd` CLI.
As an example, you can see issue [#7036](https://github.com/argoproj/argo-cd/issues/7036).

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
I'm assuming you're using `ARGO_HTTP1=true`.

We would need to pass the header here:

https://github.com/argoproj/argo-workflows/blob/6076524cd51484b5f1efb3b6ff96cebdd020eba2/pkg/apiclient/http1/facade.go#L60

It would get the header values from here:

https://github.com/argoproj/argo-workflows/blob/6076524cd51484b5f1efb3b6ff96cebdd020eba2/pkg/apiclient/argo-server-opts.go#L7

Which would be set here:

https://github.com/argoproj/argo-workflows/blob/6076524cd51484b5f1efb3b6ff96cebdd020eba2/cmd/argo/commands/client/conn.go#L48

Would you like to submit a PR?

**Comment by tatodorov** [comment]
> Would you like to submit a PR?

Yes, I will be working on a PR.
