### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by rohankmr414** [argoproj/argo-workflows#7997]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have previous experience in Go and I'm currently learning Kubernetes.**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I'm currently working on issue #7390 and have opened a draft PR  #7929. Need help with the PR.**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: async

**Comment by alexec** [comment]
Hi @rohankmr414 

I would like to offer my help as a mentor. Please let me know if you'd like that.

**Comment by rohankmr414** [comment]
Thank you for helping me
