### ISSUE TITLE
How to reuse existing clientConfig? (Go Client Library)

### ISSUE THREAD

**Issue by riscie** [argoproj/argo-workflows#8007]
Hi Everyone!

Thank you so much for this project. I really appreciate the time that went into creating it, great work! :+1: :+1: 

I have a question reagrding the usage of the go client library.
In the [linked example](https://github.com/argoproj/argo-workflows/blob/master/cmd/argo/commands/submit.go) a new serviceClient gets created like so:

```
ctx, apiClient := client.NewAPIClient(cmd.Context())
serviceClient := apiClient.NewWorkflowServiceClient()
```

How would I be able to create a new serviceClient with an existing ClientConfig. My goal is to make sure I am using the correct kubernetes context (which is not always the one which is set on the system at the moment.)

I've tried using `NewClientFromOpts` which I found browsing the source code.
The following approach seems to work, but I am not sure if this is the preferred approach.

```
ctx, apiClient, err := apiclient.NewClientFromOpts(
apiclient.Opts{
	ArgoServerOpts: apiclient.ArgoServerOpts{},
	InstanceID:     "",
	AuthSupplier: func() string {
		return client.GetAuthString()
	},
	ClientConfigSupplier: k8s.GetClientConfig, // my own method, returning a `clientcmd.ClientConfig` which we also use for the k8s client within the same app
	Offline:              client.Offline,
	Context:              context.TODO(),
    })

if err != nil {
log.Fatal(err)
}

serviceClient := apiClient.NewWorkflowServiceClient()
```
I am particulary clueless if I am using `ArgoServerOpts`, `InstanceID` and the other properties of the `apiclient.Opts` struct correctly? Or is there even another, better approach?

Any guidance is very welcomed! 

Kindly, Riscie

**Comment by alexec** [comment]
This looks correct to m.

**Comment by riscie** [comment]
Thanks so mich for the fast feedback @alexec
