### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by gandeevan** [argoproj/argo-workflows#8008]
Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? 
Answer: Yes I have read the mentoring guide.

What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?
Answer: I have previous experience with Go and Kubernetes

Is there any particular issue you'd like to work on?
Answer: I would like to work on 7994

Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)? Please include your time-zone if you want to work sync.
Answer: async

**Comment by sarabala1979** [comment]
I can mentor you, Please let me know if you need any help

**Comment by terrytangyuan** [comment]
Closing this due to no response. Feel free to reopen if you decide to contribute again.
