### ISSUE TITLE
Provide a way to know a third-party plugin is safe to run ( e.g. `argo executor-plugin scan`)

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8019]
# Summary

Hopefully, we’ll see a growing community of plugins for workflows. Maybe we’ll end up with an App Store of plugins :)? “Plug-in Hub”. 

OK. So either we have some kind of “Plugin Store” (maybe just repos in Argo Labs). How can we say that plugin is ok to install?

(1) Introduce a badging system, they could just the one we use:

https://bestpractices.coreinfrastructure.org/en

How will users be able to know a plugin is safe to run?

# Does it compromise security?

We can check the following:

* Is the image safe?
* Is the security context correct? Run-as-non-root etc.

This is all visibility in the manifest. Perhaps we could just refuse to load plugins that have weak security context?

# Does it contain a security compromise?

This is harder to check - the actual code. We’re talking supply chain security. Compare:

* Compiled code - e.g. Rust or Golang - code is obfuscated.
* Interpreted code - e.g. Python - code is readable.

In both cases, the problem is really the same, we need to link the source code to the binary, verify the binary is complied from the source code. 

Ultimately, you could always build a scratch binary that passes security scanning yet quietly mines crypto while running a python script.

Lets assume the image registry only contains good images.

Each binary is described by the image name. You could allow-list images, but not super easy to use. 

There also several steps from known safe source code. Is there anyway to to link commit SHA to a binary?

I think maybe we start with some security best practices documentation.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by UrielCohen456** [comment]
Perhaps a rating style system (akin to git project stars) that enable users to find community updated and trusted plugins.

Also I think a badge system sounds great, with a final certified plugin type badge issued to plugins verified by the argo workflow maintainers (Possibly even from verified companies if they create/support plugins, for example certified badge on an ansible plugin supported by RedHat).

**Comment by alexec** [comment]
I’m not sure about a rating system. They can be gamed. I’m not sure about CII badge either. It self-certifaction, which would be suitable for plugins where you’re confident that the authors are trustable.

**Comment by UrielCohen456** [comment]
Perhaps a way to allow every plugin to define what privileges and permissions it needs inside a cluster and providing a way to rank them based on it? That way when you install a plugin it asks if you want yo give those permissions.

For example a plugin that needs read access to all secrets in a cluster would be rated lower on the security scale.

That way community feedback isn't the only parameter.

**Comment by alexec** [comment]
So here is the security scope:

* We do not enforce defaults more secure than Kubernetes does. 
* We will make it possible to run workflows using more secure defaults.

Unlike a conventional deployment, it is not be possible to use static analysis on workflows, pods specs are generated at runtime. Instead, you can use something like Open Policy Agent to enforce security policies (e.g. allowed images, resource limits and security contexts, run-as-non-root set).

We shoud make it possible to run hardened workflows:

* Use `templateDefaults` to set more secure defaults.
* Appy labels suitable for `NetworkPolicy`. 

How does this impact plugins? We've tightened security:

* The workflow service account, used by plugins, no longer needs `pod patch`.
* Plugins do not get a service account token at all.

Plugin user need to ask themselves:

* Does the image have any vulns? 
* Does it come from a trusted source?
* Does it have hardened security context?
* Does it have sensible resource limits?

So any plugin author may wish to help by:

* Running a Snyk build to scan their image and dependencies.
* Have a CII best practices badge
* Vend with good defaults.
