### ISSUE TITLE
[UI] Feature Request: Show and filter by labels in the UI

### ISSUE THREAD

**Issue by jlewi** [argoproj/argo-workflows#802]
FEATURE REQUEST

In the Argo UI list view for workflows, I'd like to be able to

- See labels associated with a workflow
- Filter by labels

Kubeflow uses Argo to run our tests so we have 100's of workflows. We use labels to encode relevant information about a test such as

- PR #
- Git Commit
- Repository

So being able to see labels and filter by label would be very useful for identifying the workflow of interest.

Right now the fields I see

name
namespace
created at

Our UI is publicly available here
http://testing-argo.kubeflow.org/workflows

**Comment by ghostsquad** [comment]
some other things to filter/sort on (besides labels): timestamps, status

**Comment by wangli1426** [comment]
May I ask if this feature will implemented in the near future?

**Comment by sudermanjr** [comment]
Also filter by namespace would be awesome.

**Comment by sarabala1979** [comment]
@simster7 is working on a refactoring  Argo UI for Argo API server.  namespace filter is already a requirement in that.

**Comment by alexec** [comment]
We recently added a similar ability to Argo CD:

* Show and filter workflows in the UI by label.
* CLI:
  * List workflows with a label.
  * Delete all workflows with a label.

We should decide whether or not to support labels on templates, cron workflows, and archived workflows (probably not for a v1).

**Comment by alexec** [comment]
I'm going to create separate issues for the the other types.

**Comment by alexec** [comment]
@whynowy and I will pair on this. @simster7 would you willing to be the reviewer? It'll be at least a week before we have anything to review.

**Comment by simster7** [comment]
@alexec Yes, I'd be happy to review
