### ISSUE TITLE
Use config/mainContainer for security context and more

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8026]
# Summary

Currently, this field is only used for executor resource. We should use it for security contex and others too.

# Use Cases

Harden default configuration. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
@terrytangyuan fancy owning this?

**Comment by terrytangyuan** [comment]
Sure, happy to. Anything other than security context that you can think of?

**Comment by alexec** [comment]
this is not top priority, I think we have bigger issues to fix, firstly `pod patch` - which I could do with a review

**Comment by terrytangyuan** [comment]
Happy to prioritize reviews. Noticed that it's still in draft. Please assign/request review when ready.

**Comment by alexec** [comment]
I'm going to close this. The real use case is in #7962
