### ISSUE TITLE
I would like a Mentor

### ISSUE THREAD

**Issue by a-muk** [argoproj/argo-workflows#8032]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I am currently a beginner in Kubernetes. I am ready to learn these technologies under a mentor.**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #7920 **

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: Async

**Comment by alexec** [comment]
@a-muk would you like a mentor? I wonder if @dpadhiar might be interested in helping you with this UI change?

**Comment by a-muk** [comment]
Thank you for replying. I would surely like a mentor.

**Comment by alexec** [comment]
@dpadhiar say he does not know much React. But I can help. It is a steep learning curve! 

To start out, I suggest learning some basics to get started:

* https://go.dev/tour/welcome/1 is a really great intro to Golang (allow 2-3hrs)
* https://reactjs.org/tutorial/tutorial.html is the React tutorial

Let me know your thoughts.

**Comment by a-muk** [comment]
Thank you. Do you suggest me to start with both of them together now?

**Comment by alexec** [comment]
It is up to you. You might find the React one more useful.

**Comment by a-muk** [comment]
Okay. Thank you.

**Comment by alexec** [comment]
How's it going?

**Comment by alexec** [comment]
Excellent! Let me know if you need any help.
