### ISSUE TITLE
Patch activeDeadlineSeconds can not failed running workflow

### ISSUE THREAD

**Issue by peterandluc** [argoproj/argo-workflows#8051]
## Summary

What happened/what you expected to happen?
When we try to patch ```activeDeadlineSeconds: 0``` to a running workflow, we expect to see the workflow status to be failed, however after patched, the status is running.

What executor are you using? PNS/Emissary
Docker executor: argoexec-image:3.2.4
## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        while True:
          print(2)
```

What executor are you running? PNS/Emissary
- Docker executor: argoexec-image:3.2.4
- argo version: argo-workflow:3.2.4
- kubectl version: 
  * Client: v1.19.1
  * Server: v1.21.7

```bash
# Create workflow as example
> kubectl create -n argo -f hello.yaml
  workflow.argoproj.io/hello-world-ngkbm created

# Check workflow
> kubectl get wf -n argo hello-world-ngkbm
  NAME                STATUS    AGE
  hello-world-ngkbm   Running   64s

# Patch activeDeadlineSeconds: 0
> kubectl patch wf -n argo hello-world-ngkbm --type='json' -p '[{"op":"add", "path":"/spec/activeDeadlineSeconds", "value":0}]'
  workflow.argoproj.io/hello-world-ngkbm patched

# Status of workflow and pod
> kubectl get pod -n argo
  NAME                                   READY   STATUS    RESTARTS   AGE
  hello-world-ngkbm                      2/2     Running   0          5m18s
> kubectl get wf -n argo
  NAME                STATUS    AGE
  hello-world-ngkbm   Running   6m44s
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
What happens if you patch 1s rather than 0s?

**Comment by peterandluc** [comment]
It's same, no different.

**Comment by peterandluc** [comment]
Another information, if we patch to workflow pod, and the pod failed immediately.
```Bash
# Patch to workflow pod
> k patch pod -n argo hello-world-ngkbm --type='json' -p '[{"op":"add", "path":"/spec/activeDeadlineSeconds", "value":1}]'
  pod/hello-world-ngkbm patched

> k get pod -n argo
  NAME                                   READY   STATUS             RESTARTS   AGE
  hello-world-ngkbm                      0/2     DeadlineExceeded   0          46m
```
Could you help me to point out where the related codes located?

**Comment by alexec** [comment]
I don't think this should work. Not a bug.

**Comment by peterandluc** [comment]
> I don't think this should work. Not a bug.

I think the behavior is different with argo workflow [document ](https://argoproj.github.io/argo-workflows/fields/#fields_3) explanation:
```
A value of zero is used to terminate a Running workflow.
``` 
And it is also different with kubernetes behavior. We use it to terminate workflow in v2.10.1 without problem. Is there any explanation why we make difference?

**Comment by alexec** [comment]
Can't argue with the docs. This is a regression then.

**Comment by alexec** [comment]
v2.10 is out of support. To help determine when the regression occured, have you found the same regression in any version between v2.10 and v3.2?

**Comment by peterandluc** [comment]
Hi, I haven't had chance to test it in any other argo version. But I can try it in v2.11 and v3.1?

**Comment by alexec** [comment]
That'd be helpful if it is not too hard.

**Comment by sarabala1979** [comment]
it looks like a missing usecase.  Patching activeDeadlineSeconds will only apply for pending pods, not in running pods. 
https://github.com/argoproj/argo-workflows/blob/e7ff3f5aec16dfb436ebd8b13450209f3c6ff79d/workflow/controller/exec_control.go#L29
