### ISSUE TITLE
Support private registry credential imagePullSecrets for argoproj/argoexec

### ISSUE THREAD

**Issue by GitHubFor122** [argoproj/argo-workflows#8074]
# Summary
When we deploy a argo-workflow in private internal datacenter, have no intenet access, we would like to pull argoproj/argoexec with a docker registry crendential,  but no such args in deployment yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap   # Set configmap name here
        - --executor-image
        - argoproj/argoexec:latest
        - --namespaced
        command:
        - workflow-controller
        image: argoproj/workflow-controller:latest
        name: workflow-controller
      serviceAccountName: argo
      nodeSelector:
              kubernetes.io/os: linux
What change needs making?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
You can customize your container in executor field in the controller configmap: https://github.com/argoproj/argo-workflows/blob/master/docs/workflow-controller-configmap.yaml#L216

**Comment by GitHubFor122** [comment]
but no any registry secret can pass on workflow-controller-configmap.

**Comment by PidgeyBE** [comment]
Is there already a solution for this?
I'm also interested to know how to apply imagePullSecrets to the executor...

**Comment by Jonilei** [comment]
Is there any solution?
I think it is an important issue because it affects the use of workflows.

**Comment by tiborauer** [comment]
Is there already an implementation for using a private registry?

**Comment by agilgur5** [comment]
`imagePullSecrets` are Pod-level, not container-level. The Executor is another container that runs in your template's Pods. So whatever `imagePullSecrets` you have on your template will be used

**Comment by tiborauer** [comment]
Thank you, @agilgur5! I already found this info on another source.
