### ISSUE TITLE
Proposal: support for multiple serviceAccount login

### ISSUE THREAD

**Issue by junjunjunk** [argoproj/argo-workflows#8075]
# Summary
Allow users to sign in using multiple service accounts when signing in to Argo Workflows.

This is primarily for the purpose of enhancing SSO RBAC .
https://argoproj.github.io/argo-workflows/argo-server-sso/#sso-rbac-namespace-delegation

When using SSO RBAC, it is possible that someone may need to have permissions to multiple namespaces.
It could happen, for example, if the same person develops multiple services.
It is inconvenient to assign only one service account to one user.

# Use Cases
Service-accounts for SSO RBAC are placed in each namespace.
The service account in namespace A is set to grant privileges to users belonging to Group A.
The service account in namespace B is set to grant privileges to users belonging to Group B.

However, there are users who belong to both Group A and Group B.
When that user tries to sign in, there is more than one service account available.
If the `workflows.argoproj.io/rbac-rule-precedence` set in each service account is the same, sign in with both privileges.
Or allow that user to switch the service account used in the UI.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by basanthjenuhb** [comment]
@junjunjunk This use case is already solved via the existing feature.
So you setup service account in both namespace_A and namespace_B.
If the user is performing workflow operations in namespace_A, the backend looks for service accounts only in namespace_A.
If the user is performing workflow operations in namespace_B, the backend looks for service accounts only in namespace_B.
So the user will have access to both the namespaces.

**Comment by junjunjunk** [comment]
@basanthjenuhb 
Thanks for the comment.
I understand.

I missed the following text.
> Using this, whenever a user is logged in via SSO and makes a request in 'my-namespace', and the rbac-rulematches, we will use this service account to allow the user to perform that operation in the namespace. If no serviceaccount matches in the namespace, the first serviceaccount(user-default-login) and its associated role will be used to perform the operation in the namespace.

Thank you! I will be closing this issue.
