### ISSUE TITLE
Examples should be added for failfast & withParam

### ISSUE THREAD

**Issue by MagicFrogSJTU** [argoproj/argo-workflows#8081]
# Summary
Before all, I am new to all K8S and argo workflow stuff.
Recently I am struggling with finding solutions for having sequential task pipeline of arbitrary steps. After endless searching on official argo documentation and googling, I finally ended up at: https://github.com/argoproj/argo-workflows/issues/3644. And that is exactly what I need, failfast & withParam!  
I strongly recommend that we have a example for that simple but splendid solution in repos. If authors are currently too busy, I am willing to write it myself.

# Use Cases

For those new to argo workflow.

---
**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Yes feel free to submit a PR with a proposed new example.

**Comment by MagicFrogSJTU** [comment]
Will submit one within days!
