### ISSUE TITLE
Wait container won't exit when main container open iptables rules

### ISSUE THREAD

**Issue by tastelikefeet** [argoproj/argo-workflows#8093]
## Summary

We have a scenario in which we must keep the pod network off, so when working with argo, we config the yaml file like this:
```
...
securityContext
  capabilities:
    add:
    - NET_ADMIN
...
args:
- iptables -I INPUT \\! --src hub-server-service -m tcp -p tcp -j DROP; iptables -I OUTPUT \\! -d hub-server-service -m tcp -p tcp -j DROP; <a custom command here>
```

We opened the NET_ADMIN permission and configured the iptables rules, which allowed the certain kube service in/out.

What actually happened:
Main container exited normally, but wait container still waiting on main container(stucked).
Wait container logs:
```
time="2022-03-07T11:35:04.214Z" level=info msg="Waiting on main container"
time="2022-03-07T11:40:04.215Z" level=info msg="Alloc=5404 TotalAlloc=15214 Sys=70848 NumGC=7 Goroutines=7"
time="2022-03-07T11:40:06.100Z" level=warning msg="Pod watch closed unexpectedly"
time="2022-03-07T11:40:36.100Z" level=warning msg="Pod watch closed unexpectedly"
time="2022-03-07T11:41:06.100Z" level=warning msg="Pod watch closed unexpectedly"
time="2022-03-07T11:41:36.101Z" level=warning msg="Pod watch closed unexpectedly"
time="2022-03-07T11:42:06.101Z" level=warning msg="Pod watch closed unexpectedly"
time="2022-03-07T11:42:36.102Z" level=warning msg="Pod watch closed unexpectedly"
time="2022-03-07T11:43:06.102Z" level=warning msg="Pod watch closed unexpectedly"
time="2022-03-07T11:43:36.102Z" level=warning msg="Pod watch closed unexpectedly"
time="2022-03-07T11:44:06.103Z" level=warning msg="Pod watch closed unexpectedly"
time="2022-03-07T11:44:36.103Z" level=warning msg="Pod watch closed unexpectedly"
time="2022-03-07T11:45:04.215Z" level=info msg="Alloc=5399 TotalAlloc=15425 Sys=71104 NumGC=9 Goroutines=7"
time="2022-03-07T11:45:06.104Z" level=warning msg="Pod watch closed unexpectedly"
time="2022-03-07T11:45:36.104Z" level=warning msg="Pod watch closed unexpectedly"
```

What we wish to happen:
Wait container can exit normally.

I think this problem happened because of the iptables rules(probably not a bug, We didn't change the docker image or any config of the wait container, maybe the wait container uses some extra tcp connections? ), but still have no idea to solve it.
Any advice may help, thx.

**Comment by alexec** [comment]
Please add version, and type of executor used.

**Comment by tastelikefeet** [comment]
> Please add version, and type of executor used.

argo version:

argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
(base)

executor:
time="2022-03-07T11:35:04.210Z" level=info msg="Starting Workflow Executor" version=v2.12.10
time="2022-03-07T11:35:04.214Z" level=info msg="Creating a docker executor"
Seems to be the docker executor.

wait container describe:
    Container ID:  docker://151d878b3c4f14f9565d4099ef271e4c1aab04c530f8d0d1dbcf0cc5dda96b47
    Image:         argoproj/argoexec:v2.12.10
    Image ID:      docker-pullable://argoproj/argoexec@sha256:6edb85a84d3e54881404d1113256a70fcc456ad49c6d168ab9dfc35e4d316a60
    Port:          <none>
    Host Port:     <none>
    Command:
      argoexec
      wait
    State:          Running
      Started:      Mon, 07 Mar 2022 19:35:04
    Ready:          True
    Restart Count:  0
    Environment:
      ARGO_POD_NAME:  blackbox-68be9f635cb6-3704668052 (v1:metadata.name)
    Mounts:
      /argo/podmetadata from podmetadata (rw)
      /mainctrfs/dev/shm from share-memory (rw)
      /mainctrfs/sofa from blackbox-68be9f635cb6 (rw,path="blackbox-68be9f635cb6")
      /var/run/docker.sock from docker-sock (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from argo-token-fcxvc (ro)

kube version:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tastelikefeet** [comment]
> Please add version, and type of executor used.

Please review the information above, thanks!

**Comment by alexec** [comment]
You are using a version that is no longer supported. Can you please try with v3.2.9?

**Comment by tastelikefeet** [comment]
> You are using a version that is no longer supported. Can you please try with v3.2.9?

Thanks! I will try
