### ISSUE TITLE
ttlStratergy not applied to the workflows and workflow does not get deleted

### ISSUE THREAD

**Issue by vivekthangathurai** [argoproj/argo-workflows#8101]
## Summary

What happened/what you expected to happen?

A workflow was triggered with the ttlStrategy and the workflow does not get deleted and also kubectl get workfow -oyaml does not show the ttl section.

What version is it broken in?
latest
What executor are you using? PNS/Emissary
Not sure
## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
curl -v --request POST \
  --header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Il9OdXNOVjl5YVNHRkIxQ05hTlZFUVo3aU5HQk5XWElSckhydjd6X0NRQAmfKT_4nS_v0AU8NLicR8hpJxfh1hFQ9y5kvjHf-DQEZfzx77BJ1lfKIPGb85IRfa-2jvZDQqQwYO3a5ypPyj6pmOoH3BU2Z6nR2L1zLP-QI9IMOamO1ktdtpOfKflw737mAaRVXzbcr10pDiz_zxI5L3u7a147q5VrMHrJ-Sig' \
  --url http://localhost:2746/api/v1/workflows/workflow \
  --header 'content-type: application/json' \
  --insecure \
  --data '{
  "namespace": "workflow",
  "serverDryRun": false,
  "workflow": {
    "metadata": {
      "name": "hello-world-test1",
      "namespace": "workflow",
      "labels": {
        "workflows.argoproj.io/completed": "false"
      }
    },
    "spec": {
      "activeDeadlineSeconds": 28800,
      "ttlStrategy": {
        "secondsAfterCompletion": 5 
      }
      "templates": [{
        "name": "whalesay",
        "arguments": {},
        "inputs": {},
        "outputs": {},
        "metadata": {},
        "container": {
          "name": "",
          "image": "docker/whalesay:latest",
          "command": [
            "cowsay"
          ],
          "args": [
            "hello world"
          ],
          "resources": {}
        }
      }],
      "entrypoint": "whalesay",
      "arguments": {}
    }
  }
}'
```
Command: kubectl get wf hello-world-m2tzm -oyaml -n workflow 
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2022-03-08T08:05:55Z"
  generation: 4
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/creator: system-serviceaccount-workflow-jenkins
    workflows.argoproj.io/phase: Succeeded
  name: hello-world-test1
  namespace: workflow
  resourceVersion: "109163"
  uid: f0583d3d-e0fe-426d-aade-ce118fb53a2a
spec:
  activeDeadlineSeconds: 28800
  arguments: {}
  entrypoint: whalesay
  templates:
  - container:
      args:
      - hello world
      command:
      - cowsay
      image: docker/whalesay:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: whalesay
    outputs: {}
status:
  finishedAt: "2022-03-08T08:06:02Z"
  nodes:
    hello-world-test1:
      displayName: hello-world-test1
      finishedAt: "2022-03-08T08:06:01Z"
      id: hello-world-test1
      name: hello-world-test1
      phase: Succeeded
      startedAt: "2022-03-08T08:05:55Z"
      templateName: whalesay
      type: Pod
  phase: Succeeded
  startedAt: "2022-03-08T08:05:55Z"
```

command: Kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:08:39Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
PU-VTHANGATHURA:

What executor are you running? PNS/Emissary

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by piyushsinghal3** [comment]
> 
It worked with kubernetes version **1.15** & **1.16**
argo workflow version used - **3.2.8**

**kubernetes version -** 
user:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by alexec** [comment]
If the workflow is not being created with ttlStrategy, it is being stripped from the manifests because it is invalid. That suggests a syntax error in you JSON API request. Can you double check this is correct? All JSON is upper-case or whatever it needs to be?

**Comment by piyushsinghal3** [comment]
@alexec yeah, i checked the input json workflow content again, that looks good to me and it is working as expected with lower versions of kubernetes like **1.15/1.16** but not with latest kubernetes versions.

so we doubt something is not appropriate in between the argo client and kubernetes version.

Below you can see the workflow.yaml content that is being used by argo workflow client (golang) to trigger workflow in kubernetes cluster.

golang argo/k8s libraries were used - 
```
	github.com/argoproj/argo v2.5.2+incompatible
	github.com/argoproj/pkg v0.11.0 // indirect
	k8s.io/api v0.17.8
	k8s.io/apimachinery v0.17.8
	k8s.io/client-go v0.17.8
	k8s.io/klog v1.0.0
	sigs.k8s.io/yaml v1.2.0 // indirect
```

workflow.yaml file content -

`apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-hello-world-
  namespace: workflow
spec:
  entrypoint: whalesay
  serviceAccountName: argo
  ttlSecondsAfterFinished: 86400
  ttlStrategy:
    secondsAfterCompletion: 120 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 120     # Time to live after workflow is successful
    secondsAfterFailure: 180     # Time to live after workflow fails
  templates:
    - name: whalesay
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["hi.............. world"]`

**Comment by sarabala1979** [comment]
@vivekthangathurai Can you try to submit the workflow with `argo` cli `argo submit <yaml>`?
looks like some stale CRD or Argo server is in your cluster which doesn't have `ttlStrategy`
