### ISSUE TITLE
Set to stable image tag in manifests/ instead of latest with each release

### ISSUE THREAD

**Issue by LukeRobbo** [argoproj/argo-workflows#8125]
# Summary

I think it's probably bad practice to have the images in the manifests/ directory set to use the "latest" image tag.
I've just come across a situation where upon restarting the workflow controller pod it's pulled down the latest image, which is expecting to use what looks like a new CRD type (WorkflowTaskResult), which the service account and relevant RBAC permissions I installed initially alongside it don't have permissions to list.
Makes it difficult to track the versions of the manifests you're running against the image versions.

I'd expect that on a tagged release in the manifests/ dir, the image versions should match the latest stable version of quay.io/argoproj/argocli for the argo-server deployment and quay.io/argoproj/workflow-controller for the wf controller.

# Use Cases

Anyone who (perhaps foolishly) just installed using the quick start installation might get a nasty surprise when the image updates itself out of compatibility with the other k8s resources required for it to run correctly.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
Duplicates #8124

**Comment by LukeRobbo** [comment]
ah apologies @alexec, thanks for the quick reply
