### ISSUE TITLE
A beginner has a problem in a real project and asks for a solution.

### ISSUE THREAD

**Issue by LingClassmate** [argoproj/argo-workflows#8134]
My workflow:
start——>Task1——>Task2——>Task3——>end

My application scenario:
After Workflow Task1 is executed, wait for Events to trigger task2. After Task2 is executed, you do not need to trigger task3.

I want to be able to execute the Workflow task first, and then set an events in the workflow to trigger the subsequent task flow.

Thank you very much!

**Comment by sarabala1979** [comment]
There are two  options
1.   Use the `suspend` template  (resume suspend   template using argo  API  call)
2.  Have your own   container (Waiting for the event  to  exit   it)
