### ISSUE TITLE
Improve contributing guide for e2e tests

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-workflows#8158]
# Summary

There are no docs for contributing e2e tests or running them locally. It would help new contributors add test coverage or debug existing tests if the process was clear. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/blob/5efc9fc995ac898672a575b514f8bfc83b220c4c/test/e2e/executor_plugins_test.go#L1

**Comment by alexec** [comment]
```
go test --tag=functional -t TestFoo ./test/e2e
```
