### ISSUE TITLE
Error submitting workflow via argo cli when passing --parameter-file flag

### ISSUE THREAD

**Issue by asaunders57** [argoproj/argo-workflows#8160]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
Connected to the Argo server API by setting the environment variables found in the User Info section of the Argo Workflows UI.

Attempted to submit a Workflow from an existing WorkflowTemplate:
`argo --loglevel debug submit --from wftmpl/deployment-workflow-template -n argo --parameter-file deploy-config.yaml`

Logs below showing evidence of:
- successful connection to Argo server API
- ability to submit a Workflow when not using the `--parameter-file` flag

> $ ls -la deploy-config.yaml
-rw-rw-rw-    1 root     root           459 Mar 15 22:01 deploy-config.yaml
$ argo submit --from wftmpl/deployment-workflow-template -n argo
Name:                deployment-workflow-template-j2v74
Namespace:           argo
ServiceAccount:      unset
Status:              Pending
Created:             Tue Mar 15 22:01:29 +0000 (now)
Progress:            
$ argo --loglevel debug submit --from wftmpl/deployment-workflow-template -n argo --parameter-file deploy-config.yaml
time="2022-03-15T22:01:29.056Z" level=debug msg="CLI version" version="{v3.3.0 2022-03-14T22:52:31Z c6f1e4a0ece96f774f75699eba741dc85af18f31 v3.3.0 clean go1.17.7 gc linux/amd64}"
time="2022-03-15T22:01:29.056Z" level=debug msg="Client options" opts="(argoServerOpts=(url=server:port,path=,secure=true,insecureSkipVerify=false,http=true),instanceID=)"
time="2022-03-15T22:01:29.056Z" level=debug msg="curl -X POST -H 'Authorization: ******' -d '{\"namespace\":\"argo\",\"resourceKind\":\"wftmpl\",\"resourceName\":\"deployment-workflow-template\",\"submitOptions\":{\"parameterFile\":\"deploy-config.yaml\"}}' 'server:port/api/v1/workflows/argo/submit?'"
time="2022-03-15T22:01:29.156Z" level=fatal msg="Failed to submit workflow: rpc error: code = Unknown desc = open deploy-config.yaml: no such file or directory"

I've omitted the server URL and port.

argo-workflows-server log entry:
> time="2022-03-15T22:01:29.154Z" level=error msg="finished unary call with code Unknown" error="open deploy-config.yaml: no such file or directory" grpc.code=Unknown grpc.method=SubmitWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2022-03-15T22:01:29Z" grpc.time_ms=14.878 span.kind=server system=grpc

The commands above are executed in a GitLab runner container. When I run the same command locally - connecting via the k8s API server with no ARGO env vars set, it succeeds.

The deploy-config.yaml exists and the file permissions are fine, so I am unsure as to the origin of the error. Further, it's odd that this does not occur in the case mentioned above.

What version are you running?
v3.3.0, this behaviour also occurs in v3.2.9

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@asaunders57 Can you try without argo server? looks like the file is not able in your current folder/doesn't have permission to open it.

**Comment by alexec** [comment]
There is a bug here that could have been a security issue. When submitting via the server, the parameter file is read, but is read from the server file-system. Luckily `--parameter-file=/etc/passwd` would not work. I'm going to raisea PR to fix this.
