### ISSUE TITLE
Artifact uploads do not have proper content-encoding metadata set

### ISSUE THREAD

**Issue by Mins** [argoproj/argo-workflows#8161]
## Summary

The default behavior for uploading artifacts is to first tar and gzip them. For uploads to S3, the `content-encoding` is not properly detected when the filename ends with `.tgz`. This is because Go's [built-in mapping table](https://go.dev/src/mime/type.go) is rather basic.

[Argo's S3  PutFile](https://github.com/argoproj/pkg/blob/0708446cf474068ebd2ee84183fb1b9798ae9e6c/s3/s3.go#L174)
[Minio's FPutObject](https://github.com/minio/minio-go/blob/v7.0.23/api-put-object-file-context.go#L59 )

As such, `.tgz` files are being tagged with the wrong `Content-Encoding: "application/octet-stream"` instead.

The issue can likely be solved by adding [mailcap](https://pkgs.alpinelinux.org/package/edge/main/x86/mailcap) as part of the [argoexec-base image in the Dockerfile](https://github.com/argoproj/argo-workflows/blob/200ae9c032dd6d6510d5cd9a1317cd1f9d60bc53/Dockerfile#L48) to bring in `/etc/mime.types`. It adds 84kb to the image size though.

What version are you running?
3.2.8

## Diagnostics

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Could be achieved by copying the file from the argoexec-builder stage in the Dockerfile?

**Comment by Mins** [comment]
> Could be achieved by copying the file from the argoexec-builder stage in the Dockerfile?

Ah yes, Debian has the [media-types](https://packages.debian.org/search?keywords=media-types) package that can be installed to get `/etc/mime.types`. Then we should be good to copy from the `argoexec-build` stage into the final `argoexec` image.

**Comment by whynowy** [comment]
Would you like to submit a PR for it?

**Comment by Mins** [comment]
@whynowy I've created a PR https://github.com/argoproj/argo-workflows/pull/8171 for this. It turns out that the base `golang:1.17` image already contains the `/etc/mime.types` file as @alexec suggested, so there is no need to add extra packages 👍
