### ISSUE TITLE
v3.3: "'workflow.duration' is not available as a real time metric"

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8180]

**Comment by alexec** [comment]
fix: trim spaces while parse realtime metrics value. Fixes #7819 (#7856)

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/blob/537dd3be6bf93be37e06d768d9a610038eafb361/workflow/controller/operator.go#L3249

**Comment by alexec** [comment]
fix: resolve resourcesDuration (#7299)

**Comment by alexec** [comment]
@kennytrytek I know your commit is old, but it has token 6 months to get to v3.3. 

I believe it has introduced a bug. Would you be willing to investigate and fix?

**Comment by terrytangyuan** [comment]
This should be fixed by https://github.com/argoproj/argo-workflows/pull/8181
