### ISSUE TITLE
Plugin service account RBAC support

### ISSUE THREAD

**Issue by berlinsaint** [argoproj/argo-workflows#8196]
The plugin is here: [argo-volcano-executor-plugin
](https://github.com/xfyun/argo-volcano-executor-plugin)

For now, the limits of the plugin is not compatiable for the release argo version. And it need argo modify as [pr](https://github.com/argoproj/argo-workflows/pull/8104) did.

Now argo support an environment variable way that you need specify a token using sercrets, i think it's not convienient at all. what i need is only to allow plugin connect to k8s'api  or volacno crd api..so i enable the sa auto mount, and give it the privileges.

**Comment by alexec** [comment]
Fixed by #8176
