### ISSUE TITLE
Compatibility with K8 version

### ISSUE THREAD

**Issue by jay-lee-otsk** [argoproj/argo-workflows#8198]
# Summary

The documentation should contain Compatibility Matrix with K8s. 
It is required when we walk through the service impact analysis before upgrading the K8 cluster. 
As I look through the doc, I couldn't find one. If there already exists, please let me know.

**Comment by blkperl** [comment]
@alexec How about adding the following to [release.md](https://github.com/argoproj/argo-workflows/blob/master/docs/releases.md)?

## Kubernetes Compatibility Matrix

| Argo Version | K8s Versions   |
|--------------|----------------|
| 3.3          | 1.23 1.22 1.21 |
| 3.2          | 1.21 1.20 1.19|
| 3.1          | 1.19 1.18 1.17 |

### Notes on Compatibility

The main branch of Argo Workflows is currently tested on K8s 1.21
