### ISSUE TITLE
Let Argo retry when communication with API server fails.

### ISSUE THREAD

**Issue by xMAC94x** [argoproj/argo-workflows#8204]
# Summary

Not sure if this falls in enhancement or bug category:
 
On our cluster we noticed may failures in combination with argo 3.2.6 when the API server is under high load.
Problem is, the API server might return HTTP 429 (or other non-200) when creating a Workflow-Step-Pod which results in the workflow failing.
The respective event looks like this:
```json
{
	"metadata": {
		"name": "workflow-controller-77dc559b88.16da830b98497b43",
		"namespace": "argo",
		"uid": "d24ac559-ceb0-4ea1-8783-48ff988d7d8a",
		"resourceVersion": "1002",
		"creationTimestamp": "2022-03-08T20:51:39Z",
		"managedFields": [
			{
				"manager": "kube-controller-manager",
				"operation": "Update",
				"apiVersion": "v1",
				"time": "2022-03-08T20:51:39Z",
				"fieldsType": "FieldsV1",
				"fieldsV1": {
					"f:count": {},
					"f:firstTimestamp": {},
					"f:involvedObject": {
						"f:apiVersion": {},
						"f:kind": {},
						"f:name": {},
						"f:namespace": {},
						"f:resourceVersion": {},
						"f:uid": {}
					},
					"f:lastTimestamp": {},
					"f:message": {},
					"f:reason": {},
					"f:source": {
						"f:component": {}
					},
					"f:type": {}
				}
			}
		]
	},
	"involvedObject": {
		"kind": "ReplicaSet",
		"namespace": "argo",
		"name": "workflow-controller-77dc559b88",
		"uid": "8688d778-b37b-4636-8bb7-7807099a5758",
		"apiVersion": "apps/v1",
		"resourceVersion": "5598"
	},
	"reason": "FailedCreate",
	"message": "Error creating: Internal error occurred: failed calling webhook \"validating-webhook.openpolicyagent.org\": Post \"https://opa.opa.svc:443/?timeout=10s\": endpoints \"opa\" not found",
	"source": {
		"component": "replicaset-controller"
	},
	"firstTimestamp": "2022-03-08T20:51:39Z",
	"lastTimestamp": "2022-03-08T20:51:39Z",
	"count": 2,
	"type": "Warning",
	"eventTime": null,
	"reportingComponent": "",
	"reportingInstance": ""
},
```

We also get the following status on a workflow. The workflow just creates a simple step that executes some pyhton code. It fails even to create the respective pod.
```
status: {
	...
	nodes: {
		...,
		"0bd2cae9-6725-45ba-8b43-2db5afbdaa3c-foobar-workflow-3238633154": {
			"boundaryID": "0bd2cae9-6725-45ba-8b43-2db5afbdaa3c-foobar-workflow-3668161203",
			"children": [
				"0bd2cae9-6725-45ba-8b43-2db5afbdaa3c-foobar-workflow-3689503718"
			],
			"displayName": "[1]",
			"finishedAt": "2022-03-08T23:34:05Z",
			"id": "0bd2cae9-6725-45ba-8b43-2db5afbdaa3c-foobar-workflow-3238633154",
			"message": "step group deemed errored due to child 0bd2cae9-6725-45ba-8b43-2db5afbdaa3c-foobar-workflow[2].create-python-step[1].wait-for-completion-in-python error: Internal error occurred: failed calling webhook \"validating-webhook.openpolicyagent.org\": Post \"https://opa.opa.svc:443/?timeout=10s\": context deadline exceeded",
			"name": "0bd2cae9-6725-45ba-8b43-2db5afbdaa3c-foobar-workflow[2].create-python-step[1]",
			"phase": "Error",
			"progress": "1/1",
			"startedAt": "2022-03-08T23:33:55Z",
			"templateScope": "local/",
			"type": "StepGroup"
		},
	}
}
```

This leads me to the source code location: https://github.com/argoproj/argo-workflows/blame/88ede91784fb0e73192e83739c5728bd68bf0c85/workflow/controller/steps.go#L257
Which results form a PR: "Report reconciliation errors better", so i am wondering. What is the behavior argo should follow in such case ? What should I as a argo consumer do ?
Ideally i would like that argo detects that the pod creation failed due to some API-Server not available for a second. and just retry the pod creation. Because it feels weird to pass on such k8s-api errors (which are like timeouts) to the user, who expects that argo just retries the creation a few times (maybe configureable).
Or does such a setting already exist ?

# Use Cases

Useful when the server is under high load. We notice that argo fails in those cases. Unfortunately i couldn't reproduce it locally (I tried creating a NetworkPolicy as well as modifying the Role of the workflow and argo pod. Trying this with the latest version of argo would take a weeks of preperation. but according to the source code it doesn't look like that behavior was changed in between.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
You can specify TRANSIENT_ERROR_PATTERN environment variable: https://github.com/argoproj/argo-workflows/blob/master/docs/environment-variables.md

**Comment by xMAC94x** [comment]
@terrytangyuan  thank you, that worked.
It took some time, and we find out that the following pattern worked for argo `3.2.4`
`.*Internal error occurred.*(Post|Get|Delete|Put|Patch).*https.*`
