### ISSUE TITLE
Rename the default branch to `main` 

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-workflows#8239]
# Summary

We should rename the branch `master` to `main` to be consistent with the new Github and Git default. We will need to update the workflows in `.github/workflows`, the Makefile, the README.md and any other docs not covered by automation. 

# Use Cases

* Described in https://github.com/github/renaming

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
Thanks for closing this! This ended up getting duplicated / superseded by #12127, which I completed in #12149
