### ISSUE TITLE
Wait Container keeping running due to networkpolicy enable for the argoexec

### ISSUE THREAD

**Issue by JwzBen** [argoproj/argo-workflows#8260]
## Checklist

 

* [ ] Double-checked my configuration.
* [ ] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
Since we have used the istio egress proxy, we set up the network policy Kubeflow pipeline to only allow Kubeflow Pipeline send out request via istio egress proxy, currently, we only set two egress networkpolicy,  one is for the istio egress proxy, the other is for gke metadata (127.0.0.1:988);
What version are you running?
Kubeflow Version is 1.0
argoexec: v2.10.0
gke:1.19
## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml

```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow} 
no argo namespace
# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by JwzBen** [comment]
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
log:
Starting workflow executor version=2.10.0
creating a docker executor
wating on main container
warning msg="Pod watch closed unexpectedly"

**Comment by alexec** [comment]
/area executor

Can you please attach the manifest for the NetworkPolicy and your Workflow?
Can you also please test with the latest version? 2.10 is very old.

**Comment by JwzBen** [comment]
> /area executor
> 
> Can you please attach the manifest for the NetworkPolicy and your Workflow? 
Ben: After further checked, we find that we need that we need to add a egress networpolicy for notebook-controller in kubeflow pipelien. Then the issue can be fixed;
Currently, the network policy are egress policy:
1. for istio egress proxy(egress-gateway-service.egress.svc): 3128
2. for gke metadata server(127.0.0.1): 988
3. for the notebook-controller:443

For the workflow pipeline:
we will three steps:
1. parameter init:
    a. image: argoutils:v2.10.0
    b. command: /bin/bash -c 'echo hello world'
2. build image
    a. init container:
        1. image: argoutils:v2.10.0
        2. command: curl -s google metadata
    b. container:
        1. image: executor
        2. cmd: kaniko/executor --build-argxxxxxx
3. run step 2 image
Can you also please test with the latest version? 2.10 is very old.
Ben: Since we are using the kubeflow 1.0, is it able to use the latest argo version?

**Comment by sarabala1979** [comment]
I would recommend to see the resources conception on k8s api server pod and verify the api calls latency.

**Comment by alexec** [comment]
I don't think there's acceptable value investigating v2.x issues.
