### ISSUE TITLE
Versioned documentation to distinguish between upcoming and existing features

### ISSUE THREAD

**Issue by kostis-codefresh** [argoproj/argo-workflows#8273]
# Summary

Documentation should get a drop-down menu  of versions

# Use Cases

Help users understand what is already in the project and what is upcoming.

Also to align with the rest of the Argo Projects:

https://github.com/argoproj/argo-rollouts/issues/1518
https://github.com/argoproj/argo-cd/pull/5099

![versions](https://user-images.githubusercontent.com/39800303/160560800-7a8add63-0620-4526-963d-4e7c27f7b90e.jpg)

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Duplicate https://github.com/argoproj/argo-workflows/issues/5609

**Comment by terrytangyuan** [comment]
@kostis-codefresh Thanks for opening this. Feel free to continue discussing this in #5609.
