### ISSUE TITLE
v3.3: stop results in `Failed` workflow, rather than `Succeeded`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8279]
## Checklist

 

* [ ] Double-checked my configuration.
* [ ] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

What version are you running? v3.3, worked in v3.2

> stopping a pipeline cause it to have a status of Failed instead of Succeeded as in the previous version.

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml

```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
Argo stop and terminate should make the workflow failed.  There is error log after stop the workflow which is triggering alerts

time="2022-03-29T15:57:42.700Z" level=error msg="node is already fulfilled" fromPhase=Succeeded namespace=data-datalake-poscontroller-usw2-e2e nodeName="ramezdeletemejavaproc-ramezspokdeleteme-82zvw[0].observer(0)" toPhase=Failed workflow=ramezdeletemejavaproc-ramezspokdeleteme-82zvw


I will look into that. I am trying to reproduce my local
