### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by prichrd** [argoproj/argo-workflows#8286]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have experience with Go and Kubernetes.**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to contribute to a small/medium sized feature (open to suggestions)**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: async

**Comment by prichrd** [comment]
Hey @alexec , please assign it to me! I'll look at this next week. Is there someone I can bother on slack if I get stuck?

**Comment by prichrd** [comment]
Great, thank you Alex!

**Comment by alexec** [comment]
@prichrd how is it going?

**Comment by prichrd** [comment]
@alexec it is progressing. There seem to be some corner cases that need to be considered, I will submit a proposal over the weekend.

**Comment by alexec** [comment]
no problem
