### ISSUE TITLE
Show message in `kubectl get wf` and `argo list`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8307]
We don't surface the message for either. We should as it would be very helpful for understanding why a workflow failed.

https://github.com/argoproj/argo-workflows/blob/9c901456a44501f11afc2bb1e856f0d0828fd13f/util/printer/workflow-printer.go#L57

https://github.com/argoproj/argo-workflows/blob/9c901456a44501f11afc2bb1e856f0d0828fd13f/pkg/apis/workflow/v1alpha1/workflow_types.go#L122

This feature will have massive big bang for the buck.

**Comment by sourikghosh** [comment]
@alexec Can I pick this ??
/assign
