### ISSUE TITLE
Improve templating diagnostics

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8311]
# Summary

Users often struggle to diagnoes templating problems. Helping them is time consuming. Everybody looses.

Instead, we log more diagnostics whenever resolution fails:

https://github.com/argoproj/argo-workflows/blob/9c901456a44501f11afc2bb1e856f0d0828fd13f/util/template/simple_template.go#L26

Several times here:

https://github.com/argoproj/argo-workflows/blob/9c901456a44501f11afc2bb1e856f0d0828fd13f/util/template/expression_template.go#L34

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
@lambertsbennett will be working on this.

**Comment by terrytangyuan** [comment]
This is not being worked on.

**Comment by alexec** [comment]
Add some logging debug statements to that file so when the controller is started with debug logging, then the reason is shown. For example:


Change:

```golang
	if err != nil && allowUnresolved {
		return w.Write([]byte(fmt.Sprintf("{{%s%s}}", kindExpression, expression)))
	}
```

To:

```golang
	if err != nil && allowUnresolved {
                log.WithError(err).Debug("unresolved is allowed ")
		return w.Write([]byte(fmt.Sprintf("{{%s%s}}", kindExpression, expression)))


	}
```

**Comment by surbhiahuja** [comment]
@alexec,  I have added log.WithError(err).Debug("unresolved is allowed ") in expression_template.go and import 
log "github.com/sirupsen/logrus", but getting error in line: undefined err
Can you help me with which import will this error be fixed?

<img width="398" alt="Screenshot 2022-09-06 at 12 04 21 PM" src="https://user-images.githubusercontent.com/42321035/188563483-9c8ecb19-26c2-4391-9b4f-06c2cdf582fa.png">

**Comment by surbhiahuja** [comment]
@alexec , I have created PR: https://github.com/argoproj/argo-workflows/pull/9533. Please take a look and suggest changes if required.

**Comment by Sajiyah-Salat** [comment]
is this issue still exist or it is solved?

**Comment by tooptoop4** [comment]
https://github.com/argoproj/argo-workflows/pull/13778 is related
