### ISSUE TITLE
Manifests at specific tag, different from release manifests

### ISSUE THREAD

**Issue by jemag** [argoproj/argo-workflows#8317]
## Summary

Currently, the manifests provided by the Github release seem to differ from the manifests that are provided by the git repository at the same specific tag. 

For example:

The release
`https://github.com/argoproj/argo-workflows/releases/download/v3.3.0/install.yaml` will properly provide image tag `v3.3.0`.

Whereas the manifests at : 
`https://raw.githubusercontent.com/argoproj/argo-workflows/v3.3.0/manifests/install.yaml` will use the `latest` image tag.

## Additional notes

I realize that the documentation mentions using the manifests provided by the releases, although I do think it would be less error-prone for new users if both matched the same content, especially since argo-cd seems to be using the `raw.githubusercontent` approach.

Feel free to close the issue if you think having them match is not a significant concern.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Duplicate.
