### ISSUE TITLE
when: condition on outputs.artifact is false

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#8322]
`when: "'{{steps.parse-messages-split.outputs.artifacts.dag-name}}' == snow"`

this never gets matched

but 

`when: "{{steps.parse-messages-split.outputs.result}} == snow"`

does get matched (even though the value in the artifact and echoed in the step result are same.

argowf version 3.2.9

**Comment by Hunter-Thompson** [comment]
could you add the smallest possible workflow to reproduce the bug?

**Comment by tooptoop4** [comment]
crispy

**Comment by tooptoop4** [comment]
crispy

**Comment by sarabala1979** [comment]
@tooptoop4  you can't reference the Artifacts content in when condition. The workflow controller doesn't have permission to access the artifact content. There is a workaround you can add one more step in between to stdout the artifact content and reference intermediate `steps.output.result`

**Comment by tooptoop4** [comment]
crunchy

**Comment by tooptoop4** [comment]
@sarabala1979 @alexec can this be added to the docs?
