### ISSUE TITLE
Date range filter for workflow list in UI

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8329]
# Summary

Users want to be able to find workflows by time. Add a filter to the UI for date range (same as archived workflows).

Note that the API does not support time filters, and cannot, because it essentially proxies to the Kubernetes API, which does not support it.

That means we need to warn users that maybe need to increase the number of records per page..

This feature will never be perfect, but would be useful.

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by momom-i** [comment]
I'd like to work on this issue! Can I assign it to myself?

**Comment by momom-i** [comment]
Hi, I've worked on it and done the frontend side part but now I get stuck when trying to send GET request to `/api/v1/workflows/{namespace}` endpoint.

When I try to send the request like `http://localhost:8080/api/v1/workflows/argo?listOptions.fieldSelector=spec.startedAt%3E2022-03-29T15:00:00.000Z,spec.startedAt%3C2022-04-30T15:00:00.000Z&listOptions.limit=500&fields=metadata,items.metadata.uid,items.metadata.name,items.metadata.namespace,items.metadata.creationTimestamp,items.metadata.labels,items.status.phase,items.status.message,items.status.finishedAt,items.status.startedAt,items.status.estimatedDuration,items.status.progress,items.spec.suspend` in the very similar way to archived workflow one, 
it returns error like `message: "invalid selector: 'spec.startedAt>2022-03-29T15:00:00.000Z,spec.startedAt<2022-04-30T15:00:00.000Z'; can't understand 'spec.startedAt<2022-04-30T15:00:00.000Z'"`.

I'm thinking it occurred between backend and frontend but I don't understand why the archived workflow one works successfully but this one doesn't.
I'd happy if someone let me know what is the problem.
I can open PR for it, It's still being worked on though.

**Comment by alexec** [comment]
The backend proxies through to the Kubernetes APIs. These APIs do not support date or time filtering. Filtering must be done in the client.

**Comment by momom-i** [comment]
Oh I completely missed your issue comment. I'm sorry, I understand now.
