### ISSUE TITLE
Erratum in docs

### ISSUE THREAD

**Issue by felix-dpg** [argoproj/argo-workflows#8342]
# Summary

What change needs making?

In the docs, recursion section has an erratum in the Workflow template
```
      - name: tails                     # keep flipping coins if "tails"
        template: coinflip
        when: "{{steps.flip-coin.outputs.result}} == tails"
```
Template must be **flip-coin**

Thanks in advance and BTW, very nice work with argo workflow!!!

**Comment by alexec** [comment]
Could you like to submit a PR to fix?

**Comment by msidana** [comment]
Can I work on this ?
