### ISSUE TITLE
Allow images map for emissary to be overridden at a namespace level

### ISSUE THREAD

**Issue by lucastheisen** [argoproj/argo-workflows#8344]
# Summary

When using `emissary`, we have to either specify the `command` on every `container` or we have to specify a map in the `workflow-controller-configmap`. The problem is that the default deployment has the `workflow-controller` as a cluster level resource and the individual workflows are namespace specific. In a shared cluster, that makes it impractical to use the image map. Having to specify command is bad enough (as the containers are all designed to have that embedded), but having to specify it in _many_ places is far worse as the maintenance effort goes way up.

# Use Cases

This would be used for ALL images run in argo workflows in individual namespaces.  When we create new images to be run or have to change an existing image, this would provide a single place that needs updating rather than every deployed WorkflowTemplate/CronWorkflow that happens to use that image.

I would propose something like `workflow-emissary-images-configmap` that if defined in a namespace, would be used to augment or override the configuration in the `workflow-controller-configmap`. Another nice-to-have would be a _default_ as a large number of images provide a conventional `/docker-entrypoint.sh`.

_Side note, is there any documentation as to the reason why it is necessary or a good idea to force `command` to be specified to start with?  It is certainly something that can easily lead to hard to reason bugs as you might change the image but not see your changes reflected because the workflow still contains an old `command`...._

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
> Side note, is there any documentation as to the reason why it is necessary or a good idea to force command to be specified to start with? It is certainly something that can easily lead to hard to reason bugs as you might change the image but not see your changes reflected because the workflow still contains an old command....

We re-write the container command to pre-pend it with `argoexec emissary`. Unfortunatly, we cannot determine the command unless it is specified. This is the same as TektonCD, but we do not have the capabilite to look-up the image from the Docker registry:

https://tekton.dev/vault/pipelines-v0.14.3/container-contract/

You can set them in the controller config:

https://argoproj.github.io/argo-workflows/workflow-executors/#image-index


```yaml
  images: |
    argoproj/argosay:v1:
      command: [cowsay]
    argoproj/argosay:v2:
      command: [/argosay]
    docker/whalesay:latest:
      command: [cowsay]
    python:alpine3.6:
      command: [python3]
```

**Comment by alexec** [comment]
I think we could base an automatic look-up on this:

https://github.com/tektoncd/pipeline/blob/385421f44d3ab7cf8c91df21203ce6bc8d4a021e/pkg/pod/entrypoint_lookup.go

**Comment by marwatk** [comment]
One possible long-term solution could be to get the `ENTRYPOINT` and `CMD` from the image in the [Downward API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#the-downward-api), but that's probably a long shot. I may take a stab at opening a KEP for it just to see what response I get.

In the mean time, though, I'd agree that at least attempting to read what exists in the image is a better solution than mandating violating the image's encapsulation in every case.

**Comment by tooptoop4** [comment]
the breaking change notes are not very clear, is this still allowed? https://github.com/argoproj/argo-workflows/blob/dd19e49f07c0a4ecf35fce8f5c2d9ed1d2d1541e/examples/workflow-template/templates.yaml#L26-L30
