### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by bariqhibat** [argoproj/argo-workflows#8368]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have a lot of experience in React using Javascript and Typescript, and some in Golang, and Kubernetes. Would love to learn more on Golang or Kubernetes side and delve more into CNCF**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **#7618 looks great, I am open to work on other things as well**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: It'd be helpful to include both in my opinion. When there's a blockers, it'd be good to use Zoom (sync) if I can't really find a way to pass it, other times I can do some research by myself and ask through Slack (async), which I think is better to my learning as well since I need to go through the codebase myself. I am staying at Singapore so it's GMT+8.00

**Comment by terrytangyuan** [comment]
I'd be happy to mentor. Can you try you can reproduce #7618 first?

**Comment by bariqhibat** [comment]
> I'd be happy to mentor. Can you try you can reproduce #7618 first?

Hi @terrytangyuan, thanks for the help! I'll check this out before next week
