### ISSUE TITLE
TOB-ARGO-TM14 -  User authentication is not logged if user isn’t mapped to RBAC rules

### ISSUE THREAD

**Issue by hblixt** [argoproj/argo-workflows#8370]
When using SSO authentication, a user is mapped to RBAC rules and logging is performed.
However, when a user is not RBAC-enabled, authentication is not logged for that user.
Consequently, in some configurations, authentication may not be logged, which could
hinder an operator’s ability to mitigate or understand certain classes of attacks.

Request
Enhance logging operations so all authentication attempts are logged.

**Comment by alexec** [comment]
Logged here unless I've missed something?

https://github.com/argoproj/argo-workflows/blob/55ecfeb7b0e300a5d5cc6027c9212365cdaf4a2b/server/auth/gatekeeper.go#L218

**Comment by sarabala1979** [comment]
@hblixt I think we addressed this issue.

**Comment by alexec** [comment]
#trail of bits
