### ISSUE TITLE
Add K8s auto scaler `safe-to-evict` annotation to the workflow pod

### ISSUE THREAD

**Issue by haoxins** [argoproj/argo-workflows#8376]
# Summary

Hi, I'd like to add the annotation `cluster-autoscaler.kubernetes.io/safe-to-evict: false` to the workflow pod
It will look like

```go
// AnnotationKeyAutoScalerSafeToEvict is the annotation that specify pod is safe to be evicted by autoscaler
AnnotationKeyAutoScalerSafeToEvict = "cluster-autoscaler.kubernetes.io/safe-to-evict"
```

```go
Annotations: map[string]string{
  common.AnnotationKeyNodeName:              nodeName,
  common.AnnotationKeyNodeID:                nodeID,
  common.AnnotationKeyAutoScalerSafeToEvict: "false",
},
```

# Use Cases

This will prevent the pod's node been scale down when the pod is still running.
And it will not prevent the node been remove successfully if the pod is failed or succeeded.

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/drain/drain.go#L209

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by haoxins** [comment]
so, we can mount the `emptyDir` volume into the wait container?
(I don't think the init container need this.)

**Comment by alexec** [comment]
Correct. We want to do that, because (a) we want to change the Dockerfile to use `FROM scratch`, but that image does not have a `/tmp` directory, and (b) it would allow users to set the security context to have read-only root FS.

**Comment by alexec** [comment]
Changes to make:

Change `gcr.io/distroless/static` to `scratch`. 
https://github.com/argoproj/argo-workflows/blob/637d14c88f7d12c1c0355d62c2d1d4b03c4934e1/Dockerfile#L95

Add a new empty-dir volume called `wait-tmp` to the pod and add a volume mount to the wait container:

https://github.com/argoproj/argo-workflows/blob/637d14c88f7d12c1c0355d62c2d1d4b03c4934e1/workflow/controller/workflowpod.go#L74
