### ISSUE TITLE
Track/log UI usage

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8402]
# Summary

We could add a beacon endpoint that could by the UI to track usage of the UI

```xml
<TrackEvent event='viewNodeSummary'/>
```

This just makes a HTTP request to `/api/v1/collect?t=trackEvent&event=viewNodeSummary`, similar to:

https://developers.google.com/analytics/devguides/collection/protocol/v1/reference

This event could be logged, with the SSO subject/email so Splunk queries could be created and we can speak to users about their experience.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by momom-i** [comment]
I'd like to work on this. Could you tell me more details?

**Comment by alexec** [comment]
To complete this feature:

* Update info.Porto to add the new endpoint and run `make codegen` to generate stubs.
* Implement the new endpoint in info_server.go
* Add a function to info.ts.
* Create a new shared React component.
* Embed that component into any page your wish to track.

**Comment by momom-i** [comment]
Thank you very much. It's very helpful.

I'm thinking this beacon endpoint is meant to be sent and it doesn't do any special processing in `info_server.go`. 
Is my understanding correct?

**Comment by alexec** [comment]
That is correct. You can then create reports on those logs in Splunk.

**Comment by momom-i** [comment]
I will make a PR for it, but I'm not sure where to insert this tracking component.
Could you give me your advice about it?
