### ISSUE TITLE
I would like a Mentor

### ISSUE THREAD

**Issue by lambertsbennett** [argoproj/argo-workflows#8403]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer:  Yes I have read the mentoring guide.

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: I currently work as a data scientist and use Argo Workflows as an end user. I have programmed in Go before, although it is not my daily driver. I currently work with Kubernetes on a daily basis.

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: I would be happy to work on "support binary HTTP template bodies #6888" as a first issue.

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: I would be interested in a mixture of sync and async if possible. My timezone is Central European Time.

**Comment by lambertsbennett** [comment]
I see this issue already has an associated pull request, but this issue would also be interesting for me https://github.com/argoproj/argo-workflows/issues/785

**Comment by terrytangyuan** [comment]
That issue has already been worked on. Is there anything other issues you might be interested in?

**Comment by lambertsbennett** [comment]
@terrytangyuan this issue also looks very interesting and seems new: https://github.com/argoproj/argo-workflows/issues/8474

**Comment by terrytangyuan** [comment]
@alexec Is that issue being worked on?

**Comment by lambertsbennett** [comment]
Ok what about this issue https://github.com/argoproj/argo-workflows/issues/8311. I see no comments or links to previous issues.

**Comment by lambertsbennett** [comment]
@terrytangyuan what is the best way to reach out with questions? Slack? 

From the initial issue description it is not that clear to me what is desired. In areas where 
```
return w.Write([]byte(fmt.Sprintf("{{%s%s}}", kindExpression, expression)))
```
is present, should more logic be added to capture issues with the template?

**Comment by terrytangyuan** [comment]
Either here or Slack should be fine. In that code, we should surface the error instead of just writing back the same string.

**Comment by lambertsbennett** [comment]
I'm really sorry for the lack of activity. I've started a new job and don't have time to contribute anymore.

**Comment by terrytangyuan** [comment]
No problem. Feel free to revisit when you get a chance.
