### ISSUE TITLE
Depend on success of previous CronWorkflow run

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#8406]
if CronWorkflow is scheduled every 4 hours
would like an option to only run the 8pm workflow if the 4pm workflow was successful

**Comment by tooptoop4** [comment]
covered by https://github.com/argoproj/argo-workflows/pull/12305

**Comment by agilgur5** [comment]
@tooptoop4 does that mean this was a duplicate of #5659?

#12305 fully stops a CronWorkflow, it does not skip as a once off

**Comment by tooptoop4** [comment]
my intention was to only ever run next cron if all prior succeeded
