### ISSUE TITLE
Windows builds broken

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8417]
tep 13/26 : COPY --from=builder C:/ProgramData/chocolatey/lib/docker-cli/tools/docker/docker.exe C:/app/docker.exe
[212](https://github.com/argoproj/argo-workflows/runs/6082729800?check_suite_focus=true#step:5:212)
COPY failed: stat C:\ProgramData\chocolatey\lib\docker-cli\tools\docker\docker.exe: file does not exist

https://github.com/argoproj/argo-workflows/runs/6082729800?check_suite_focus=true

**Comment by alexec** [comment]
@argoproj/argo-windows can anyone please take a look?

**Comment by alexec** [comment]
If I get no reply in 24h, I'll disable the builds.

**Comment by lippertmarkus** [comment]
@alexec as the Docker executor is removed anyway with https://github.com/argoproj/argo-workflows/issues/7795, we can remove the binary for as well, right?

**Comment by alexec** [comment]
Correct.

**Comment by JulianZhang** [comment]
@alexec @lippertmarkus  Dears,
I am using argo-workflow version 3.3.6 with windows worker now. When I run the windows-helloworld workflow, the main container with end as success. But the wait container can't get the main container's information. The stage aways in the running  status.

The log from wait container is 


```
time="2022-08-03T14:56:46.749Z" level=info msg="Starting Workflow Executor" executorType=docker version=v3.3.6+2b428be.dirty
time="2022-08-03T14:56:46.756Z" level=info msg="Creating a docker executor"
time="2022-08-03T14:56:46.757Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2022-08-03T14:56:46.757Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false na
mespace=argo-pipeline podName=hello-windows-d7tvq template="{\"name\":\"hello-win\",\"inputs\":{},\"outputs\":{},\"nodeSelector\":{\"kubern
etes.io/os\":\"windows\"},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"mcr.microsoft.com/windows/nanoserver:1809\",\"command\":
[\"cmd\",\"/c\"],\"args\":[\"echo\",\"Hello from Windows Container!\"],\"resources\":{}},\"archiveLocation\":{\"archiveLogs\":true,\"s3\":{
\"endpoint\":\"172.30.0.67:32401\",\"bucket\":\"argo-workflow\",\"insecure\":true,\"accessKeySecret\":{\"name\":\"minio\",\"key\":\"accessk
ey\"},\"secretKeySecret\":{\"name\":\"minio\",\"key\":\"secretkey\"},\"key\":\"hello-windows-d7tvq/hello-windows-d7tvq\"}}}" version="&Vers
ion{Version:v3.3.6+2b428be.dirty,BuildDate:2022-05-25T23:55:18Z,GitCommit:2b428be8001a9d5d232dbd52d7e902812107eb28,GitTag:v3.3.6,GitTreeSta
te:dirty,GoVersion:go1.17,Compiler:gc,Platform:windows/amd64,}"
time="2022-08-03T14:56:46.758Z" level=info msg="Starting deadline monitor"
time="2022-08-03T14:56:46.759Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}
|{{.ID}}|{{.CreatedAt}} --filter=label=io.kubernetes.pod.namespace=argo-pipeline --filter=label=io.kubernetes.pod.name=hello-windows-d7tvq"
time="2022-08-03T14:56:46.759Z" level=error msg="failed to poll container IDs" error="exec: \"docker\": executable file not found in %PATH%"

```

I also try to change the executor as the following example, But the wait aways run  as docker executor.

https://github.com/argoproj/argo-workflows/blob/62e0a8ce4e74d2e19f3a9c0fb5e52bd58a6b944b/examples/selected-executor-workflow.yaml

linux Dockerfile had docker cli now.

**Comment by JulianZhang** [comment]
I had change my argo-workflow version to 3.3.1, before this change merged, The hello-windows can end with success now.

**Comment by lippertmarkus** [comment]
@JulianZhang I think you need to set the executor in the global configmap to affect the wait container

**Comment by JulianZhang** [comment]
@lippertmarkus Thank you. After change containerRuntimeExecutor from docker to emissary, It works.
