### ISSUE TITLE
Interactive Argo workflows

### ISSUE THREAD

**Issue by basanthjenuhb** [argoproj/argo-workflows#8425]
# Summary
- Currently Argo workflows accepts parameters only at workflow start and after that workflow just runs on autopilot without any human interaction (except for suspend)
- But there are use cases where the workflow could intelligently generate and accept parameters in different stages of workflows
- This proposal adds the following capabilities
- Ability for any node to generate inputs programatically for the next node
- And these inputs could be of the form text, multi select etc
- User should have the ability to select from the dropdown like he does when starting the workflow 
- Jenkins has a similar feature: https://www.jenkins.io/doc/pipeline/steps/pipeline-input-step/

# Use Cases
- We use argo workflows to update schemas for our postgres instances
- So our DBA has to first search for available shards, then search for an available database, then search for an available schema manually from our internal metadata.
- If the workflow when started listed all the shards and DBS could just choose from the dropdown, then the workflows uses the selected shard to list all available databases and so on for schema, his job would be much more friendly
- This leads to more interactive workflows where the workflows are getting constant feedback from the user on how the workflow should proceed.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by dpertin** [comment]
It would be great to have this feature!
Currently, it is possible to suspend a workflow and request users to provide a set of parameters as depicted here: https://github.com/argoproj/argo-workflows/blob/e67e94c02e52eb9097b8f1316e7b3cddd091e121/examples/suspend-template-outputs.yaml#L27-L33
However, users are not able to set those parameters through the UI. They can be set through the CLI or API as explained in the example: https://github.com/argoproj/argo-workflows/blob/e67e94c02e52eb9097b8f1316e7b3cddd091e121/examples/suspend-template-outputs.yaml#L1-L7
This is a requirement for non-developers.

Here is a related request: https://github.com/argoproj/argo-workflows/issues/6665

**Comment by basanthjenuhb** [comment]
Yup, planning to work on it next week for an internal hackathon at Intuit.

**Comment by basanthjenuhb** [comment]
This should be available in next release
https://argoproj.github.io/argo-workflows/intermediate-inputs/

**Comment by feiluo-db** [comment]
Any idea how we can integrate this feature with identity management to support features such as `second person approval`?
