### ISSUE TITLE
Wrong version in namespace-install.yaml (release v3.3.1)

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-workflows#8429]
It seams like the versions in the namespace-install.yaml within the release are not up to date.
**Release 3.3.1:**

```
image: quay.io/argoproj/workflow-controller:v3.2.9
https://github.com/argoproj/argo-workflows/releases/tag/v3.3.1
```

**Comment by alexec** [comment]
Looks correct to me?

![image](https://user-images.githubusercontent.com/1142830/164261543-9b21e0ab-c0ac-4823-a1c4-e1201c63e891.png)

**Comment by nice-pink** [comment]
Now I see the same. Strange. Downloaded the file several times this morning. Could be closed then.
