### ISSUE TITLE
Quitting mentoring?

### ISSUE THREAD

**Issue by softwarebloat** [argoproj/argo-workflows#8434]
# Summary

At the Argo Data weekly of yesterday (2022/04/19) we talked about the possibility to quit the mentoring support.

We would like to have more opinions about it

If I'm not wrong, problem seem to be that people are asking for mentorship and then "disappear" causing a waste of time.

I'm the one who proposed the mentorship program and i think it's really useful both for the mentee and for the project. But I'm not a mentor, I'm a mentee so I could only imagine the effort to mentor others.

Maybe, instead of quitting it, we could find other solutions that'll help us with the process?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
My main comment here is mentoring, if it is to stay in its current form, needs a lead mentor. I'd like to canvas for volunteers.

**Comment by terrytangyuan** [comment]
I can help triage mentoring requests (if that's what you meant by lead mentor) but we need a process to close stale requests that unassign the existing issue that's originally assigned to the mentee if it's no longer being worked on. We should also consider using a bot (stale bot) that periodically pings the mentees.

**Comment by alexec** [comment]
> I can help triage mentoring requests (if that's what you meant by lead mentor) 

Yes. That's the primary task. Also, if there are any problems, you'd need to help with that.

> but we need a process to close stale requests that unassign the existing issue that's originally assigned to the mentee if it's no longer being worked on. We should also consider using a bot (stale bot) that periodically pings the mentees.

Stale bot should stale these already.

**Comment by terrytangyuan** [comment]
> Stale bot should stale these already.
It doesn't seem so. Would you like me to enable that for mentoring label? https://github.com/argoproj/argo-workflows/blob/master/.github/stale.yml#L9

**Comment by alexec** [comment]
stale bot is configured aggressively, for mentoring, maybe we should change to 10+5 rather than 7+3 or other values

**Comment by terrytangyuan** [comment]
Looks like stale bot doesn't support different configurations for different labels.

**Comment by danielhelfand** [comment]
Just throwing in here that it would be helpful to have a specific message to encourage mentees to reopen issue in event issue gets closed. This could be configured by adding a [closing message](https://github.com/argoproj/argo-workflows/blob/master/.github/stale.yml#L21) or as suggested in community meeting to add something to the [stale warning message](https://github.com/argoproj/argo-workflows/blob/37a8a81df1d7ef3067596199f96974d31b200b88/.github/stale.yml#L16).
