### ISSUE TITLE
Add darwin-arm64 CLI binary

### ISSUE THREAD

**Issue by clelange** [argoproj/argo-workflows#8450]
# Summary

Currently, there are only `darwin-amd64` CLI binaries built as part of a release. I propose to add `darwin-arm64` ones as well.

# Use Cases

Building also `darwin-arm64` ones will make use of argo workflows on Apple silicon easier, removing the need for Rosetta.
I will submit a PR soon if you agree that this is useful.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
Implementation instructions:

Add code here:

https://github.com/argoproj/argo-workflows/blob/79508cc78bd5b79762719c3b2fbe970981277e1f/Makefile#L169
