### ISSUE TITLE
Add `ArtifactDriver.Delete` (internal API)

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8470]
Create a `Delete` func to support #3102 .

https://github.com/argoproj/argo-workflows/blob/e368f504307ecbbfa2f228bccfab1f943efaca9d/workflow/artifacts/common/common.go#L11

Only implement for S3.

https://github.com/argoproj/argo-workflows/blob/e368f504307ecbbfa2f228bccfab1f943efaca9d/workflow/artifacts/s3/s3.go#L22

If we have not yet implemented we should return an error, and that error should ask the user to vote for support by linking to a Github issue.

Implementations should be idempotent.

**Comment by mboussarov** [comment]
Please assign me to this issue
