### ISSUE TITLE
Artifact GC: add finalizer to workflows

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8474]
Depends on #8483.

When a workflow completes, or is deleted, we need to delete the artifacts. This might fail because of some transient error. In that case, we want to block deletion of the workflow. This can be done using a finalizer:

https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/

When we start processing a workflow, we do one time initialisation:

https://github.com/argoproj/argo-workflows/blob/e368f504307ecbbfa2f228bccfab1f943efaca9d/workflow/controller/operator.go#L3439

At this point, if the workflow has any GC strategies at all, add a finalizer. I think it should be named `workflows.argoproj.io/artifact-gc`.  You can add a a constant to `common.go`.

**Comment by basanthjenuhb** [comment]
@alexec I can pick this up

**Comment by alexec** [comment]
You can find out if a finalizer needs adding using `Workflow.SearchArtifacts`. @dpadhiar is working on that today.
