### ISSUE TITLE
`argo cp`/UI: Argo Server `ArtifactServer.ServeFile` endpoint

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8481]
Depends on #8396 

We need a more flexible endpoint to get artifact files from. 

The essential goal of this is to allow the Argo Server to allow directory like access to artifacts.

The format of the new URL is:

```
http://localhost:2746/artifact-files/{namespace}/[archived-workflows|workflows]/{id}/{nodeId}/outputs/{artifactName}
```

* `{namespace}` = The workflow namespace.
* `[archived-workflows|workflows]` the string literal. When this is `workflows`, it is a normal workflow. When `archived-workflow` then it is an archived workflow.
* `{id}` either the workflow name or the workflow UID.
* `{nodeId}` the node ID.
* `outputs` - the string literal "outputs". So that in the future we may support `inputs`. 
* `{artifactName}` - the name of the input or output artifact.

What should we return? 

We can use `ListObjects` to determine if an object is a directory (it'll error if it is a file) and return the file listing if not. This is only implemented for S3, but that is fine for MVP.

* If the artifact is a file, return that. 
* If the artifact is a directory, return a directory listing.

/artifact-files/{namespace}/[uid|name]/{id}/{nodeId}/outputs/{artifactName}/{filename}

## Access Control

The rule is, you can only see an artifact if you can see the workflow that created it. There is existing examples of this in the code-base.

**Comment by alexec** [comment]
Implementation:

* Add a new func to ArtifactServer called GetArtifactFile. 

https://github.com/argoproj/argo-workflows/blob/7376e7cda4f72f0736fc128d15495acff71b987d/server/artifacts/artifact_server.go#L28

* In argo_server.go add the HandleFunc:

https://github.com/argoproj/argo-workflows/blob/7376e7cda4f72f0736fc128d15495acff71b987d/server/apiserver/argoserver.go#L347

Add a new `filename` parameter to `returnArtifact`:

https://github.com/argoproj/argo-workflows/blob/7376e7cda4f72f0736fc128d15495acff71b987d/server/artifacts/artifact_server.go#L159

This needs to be set by each calling func. For the old func (e.g. GetArtifact) it can be empty string.

If `returnArtifact` has a filename, then use `Artifact.AppendToKey` to append it. Santize filename using `path.Clean` to remove `../` and prevent path traversal attacks.

Use `ListObjects` to determine if the artifact is a directory, and if so, return the directory listing as HTML:

https://github.com/argoproj/argo-workflows/blob/7376e7cda4f72f0736fc128d15495acff71b987d/server/artifacts/artifact_server.go#L187

**Comment by juliev0** [comment]
Please assign to me

**Comment by juliev0** [comment]
@alexec Should the directory listing be hrefs? (and if so, relative or absolute?)

**Comment by alexec** [comment]
Yes, relative.
