### ISSUE TITLE
Add correct CSP/XFO to served artifacts

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8492]
## Content-Security-Policy

CSP must be set for HTML files, and harmless for other file types. So always set it.

CSP should be as strict as possible, and MUST block script execution. `X-Frame-Options` or `<iframe sandbox/>` will not be enough. 

https://csp.withgoogle.com/docs/strict-csp.html  - not strict enough, I think it should allow images and styles, but essentially block everything else:

```
Content-Security-Policy: sandbox; base-uri 'none'; default-src 'none'; image-src: 'self'; style-src: 'self'
```

https://web.dev/csp/

And X-Frame-Options should be the standard value:

```
X-Frame-Options: SAMESITE
```

**Comment by alexec** [comment]
Add these two header here:

https://github.com/argoproj/argo-workflows/blob/7376e7cda4f72f0736fc128d15495acff71b987d/server/artifacts/artifact_server.go#L199

Test here:

https://github.com/argoproj/argo-workflows/blob/7376e7cda4f72f0736fc128d15495acff71b987d/test/e2e/argo_server_test.go#L1058

**Comment by alexec** [comment]
If the environment variable `ARGO_ARTIFACT_CONTENT_SECURITY_POLICY` is set, use that for the CSP. If `ARGO_ARTIFACT_X_FRAME_OPTIONS` use that.

**Comment by mboussarov** [comment]
Please assign to me
