### ISSUE TITLE
Do not return cause of internal server error

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8514]
We currently return the cause of the error:

https://github.com/argoproj/argo-workflows/blob/cb616556c965329284553d4a634bbf8f0a588195/server/artifacts/artifact_server.go#L155

We should not do that, because that could reveal internal workings. Delete that line.

Also, this logging should be structured:

https://github.com/argoproj/argo-workflows/blob/cb616556c965329284553d4a634bbf8f0a588195/server/artifacts/artifact_server.go#L156

By removing the 500 error, we'll make it harder for client to understand errors.

**Comment by mboussarov** [comment]
Please assign this to me
