### ISSUE TITLE
UI: Report times and durations with minute resolution

### ISSUE THREAD

**Issue by Topher-the-Geek** [argoproj/argo-workflows#8515]
# Summary

Generally, I'm loving Argo Workflows. Thanks all for this great tool!

I constantly have to hover over times to get real answers.

What I see
<img width="392" alt="Screen Shot 2022-04-27 at 11 09 28 AM" src="https://user-images.githubusercontent.com/588423/165594864-54db6fef-e08d-4483-b6aa-6751a9a60880.png">

First I have to hover here
<img width="454" alt="Screen Shot 2022-04-27 at 11 09 43 AM" src="https://user-images.githubusercontent.com/588423/165594879-2f4cd757-757f-4d52-9739-9c23b9b8a1fb.png">

Then I have to hover here
<img width="463" alt="Screen Shot 2022-04-27 at 11 09 50 AM" src="https://user-images.githubusercontent.com/588423/165594887-2c78bebf-a8a1-420a-84fd-58a4f8242bbf.png">

Now I can learn the real duration was about 1h 57m, which is really far off from 1h.

Note, just improving rounding isn't enough. Sure, the above 1h 57m would be fine to round to 2h, but rounding 1h 31m to 2h is no good.

# Use Cases

- I want to know how long it took a workflow or step to run to the minute
- I want to know how long ago something began running to the minute

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Would you like to submit a PR to improve this?

**Comment by lstolcman** [comment]
Should be fairly easy to fix.
File: https://github.com/tinoschroeter/argo-workflows/blob/3e8aa6f24f4072aef4959684675430bbca174f37/ui/src/app/shared/components/duration-panel.tsx

A connected one was fixed here: https://github.com/argoproj/argo-workflows/pull/7694

**Comment by Unperceivable** [comment]
Seems already implemented. What version of Argo Workflows was being used? I think we can close this issue.
![image](https://github.com/user-attachments/assets/8fc580fa-f5d7-4e24-959d-7924812d62de)

**Comment by Unperceivable** [comment]
Just to clarify, looking at the code, resolution is always two "significant figures" (i.e d,h,m,s) so you wont always see seconds as suggested by someone else. I think it makes sense how it is currently implemented.   
Ran an hour long workflow for reference:   
![image](https://github.com/user-attachments/assets/4d5b2787-0062-4b89-9587-f749b44fdc43)

**Comment by Topher-the-Geek** [comment]
Yes, I agree this has been fixed, and it has been very helpful. I see <H>h<MM>m or <M>m<SS>s, which I think is a great balance of resolution and visual clarity.
