### ISSUE TITLE
 The node was low on resource: ephemeral-storage. Container wait was using 60Ki, which exceeds its request of 0.

### ISSUE THREAD

**Issue by trondhindenes** [argoproj/argo-workflows#8526]
## Checklist
* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary
We're seeing some workflow pod failures with this error:
"The node was low on resource: ephemeral-storage. Container wait was using 60Ki, which exceeds its request of 0."

Is it possible to configure the wait pod with an ephemeral-storage requests?

## Diagnostics

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by viploveb** [comment]
@trondhindenes This might help - https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#setting-requests-and-limits-for-local-ephemeral-storage

**Comment by trondhindenes** [comment]
thanks!

**Comment by kostas-theo** [comment]
Just a note to anyone else who ends up here - if the disk usage on the node your workflow step is running on spikes to dangerous levels (~90%+) causing your pod to fail - argo can give this exact error.
