### ISSUE TITLE
Fix the swagger.json file

### ISSUE THREAD

**Issue by swafa** [argoproj/argo-workflows#8528]
# Summary

What change needs making?

The [swagger.json](https://github.com/argoproj/argo-workflows/blob/master/api/openapi-spec/swagger.json) file seems to have a mistake in it as shown below. It's an additionally-defined "namespace" parameter in the "/input-artifacts-by-uid/{uid}/{nodeId}/{artifactName}" endpoint that does not accept a namespace parameter. It would be great if this gets fixed, I have submitted a [PR](https://github.com/argoproj/argo-workflows/pull/8527)

![image](https://user-images.githubusercontent.com/8384031/165735805-c8db3c3a-08d7-440a-a2d4-ae22dc656c41.png)

# Use Cases

When would you use this?

When using the swagger file for exposing our deployed Argo instance through API management services.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
This can be fixed in this file:

https://github.com/argoproj/argo-workflows/blob/master/pkg/apiclient/_.primary.swagger.json

**Comment by terrytangyuan** [comment]
@dalongfan Any updates on this?

**Comment by jyeray** [comment]
@terrytangyuan I was looking for good first issues, and just saw that this issue was solve on [this commit](https://github.com/argoproj/argo-workflows/commit/7dacb5bcaeae8e3be64bb1fbf54024401d42d867#diff-a343bd8d7da95528694b5dbdf8d10d73c9ba60bb61b5a7b13807aaad88ef1094L264)
