### ISSUE TITLE
allow reusing cronworkflow with adhoc execution and overridden inputs

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#8531]
# Summary

allow adhoc trigger of cronworkflow via cli/ui with arbitrary arguments passed in (ie string arguments or runtime argument) ie similar to https://airflow.apache.org/docs/apache-airflow/stable/dag-run.html#using-cli or https://airflow.apache.org/docs/apache-airflow/1.10.11/dag-run.html#external-triggers

this would be simpler for user than needing to write a 2nd file (ie workflow template) or learning about backfill command

# Use Cases

Testing
Historical data migrations

**Comment by terrytangyuan** [comment]
Duplicates https://github.com/argoproj/argo-workflows/issues/2706
