### ISSUE TITLE
UI should default to the namespace associated with ServiceAccount

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-workflows#8533]
# Summary

When choosing a namepsace to use when filtering workflows:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/12677113/165870697-1ab896b7-fad0-4e17-9e7c-62b4d13d74b4.png">

The UI / argo-server could default to the namespace associated with the service account used to login with (unless they already explicitly selected a different service account)

# Use Cases

When would you use this?

This is based on user feedback of the workflow UI/UX. The UX is not ideal in a multi-tenant environment because the immediate view is that the user does not have permission to view workflows in `argo` namespace, (but they can in their own namespace).

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
I sent a draft for this in https://github.com/argoproj/argo-workflows/pull/9008. Feel free to take a look.
