### ISSUE TITLE
PodGC Timeout

### ISSUE THREAD

**Issue by SebastianGoeb** [argoproj/argo-workflows#8539]
# Summary

Would it be possible to introduce a `podGC.timeout: [15m|1h|2d]` property to delay deletion of pods?

# Use Cases

We have an issue with our fluentbit not collecting logs from pods that vanish quickly (or so it seems at least). The pod in question also provisions a fat EC2 instance that we want to get rid of ASAP when it's done, hence we use `podGC: OnPodCompletion`. Unfortunately, sometimes our logs are cut off, and sometimes logs from short-lived pods are cut off too.

I don't think this is fixable in fluentbit because if the pod is gone, then it's gone. Fluentbit wouldn't be able to do anything about it (or maybe it would, by attaching some kind of finalizer that doesn't release the pod until all logs have been collected???).

Anyway, I thought podGC might benefit from a timeout property, that would let us add a grace period of some seconds/minutes/whatever to pod termination. Do you think this would be a useful feature to have?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
This already exists. See docs.

**Comment by SebastianGoeb** [comment]
@alexec I'm sorry, either I'm blind or we misunderstood each other. The only properties I can find in the docs relating to timeout/ttl/deadline/etc. are
- podGC.strategy (don't support a timeout)
- activeDeadlineSeconds (kills a workflow if it does over X time)
- startingDeadlineSeconds (analogous to CronJob startingDeadline)
- ttlStrategy (removes the Workflow X time after completion)

Those are all not what I was describing. I was after something like this:

config: {podGC.ttl: 60s}
0s -> workflow start, pod 1 start
30m -> pod1 completed (stays in Completed status for now), pod2 start
31m -> pod1 deleted
60m -> pod2 completed, workflow complete
61m -> pod2 deleted

I tried out [TTLStrategy](https://argoproj.github.io/argo-workflows/fields/#ttlstrategy), which I believe is what you're referring to, but that results in this behavior:

config: {workflow.ttlStrategy: 60s}
0s -> workflow start, pod 1 start
30m -> pod1 completed (deleted immediately), pod2 start
60m -> pod2 completed (deleted immediately), workflow complete
61m -> workflow deleted

Did I miss something? I was after podGC, not workflowGC.

**Comment by SebastianGoeb** [comment]
Another two I found are
- deletionGracePeriodSeconds (docs say "read-only", and only im combination with deletionTimestamp, so is this only set by the workflow controller? When I explicitly set it, it's ignored).
- `podSpec.terminationGradePeriodSeconds` via `podSpecPatch`: https://github.com/argoproj/argo-workflows/issues/1012 (not obvious in the docs btw)

The latter one controls the delay between K8s sending SIGTERM and SIGKILL during forcible pod deletion. I'm after a delay between pod regular pod exit (0) and the deletion of the pod resource in K8s. It seems this isn't covered by terminationGracePeriodSeconds (I tried it out, pods have the property and still vanish immediately).

**Comment by SebastianGoeb** [comment]
@alexec could you briefly elaborate which feature you mean, when you say this already exists? I really don't see how this already exists. I've already named a bunch of features that don't cover my use case.

Do you mean I should rely on preStop? That only run during external termination, not on crash or exit.
Do you mean finalizers? Those are metadata and metadata.finalizers is filtered out by the workflow controller when I try to set it.

I am looking for pod-exit-0 -> pod-complete -> workflow-complete -> ... wait 2 minutes -> delete pod

All the various termination options only cover external termination, not regular exit 0, and ttl only delays workflow deletion not pod deletion.

**Comment by tooptoop4** [comment]
https://github.com/argoproj/argo-workflows/pull/6168 might be the one?

**Comment by artem-zherdiev-ingio** [comment]
Seems documentation doesn't have it

**Comment by artem-zherdiev-ingio** [comment]
@yu-croco Hi, could you also see this to update in helm chart. Thanks!

**Comment by yu-croco** [comment]
Hi @artem-zherdiev-ingio, thank you for mentioning!
I will add it on helm chart. 🙋

**Comment by agilgur5** [comment]
I similarly couldn't find any documentation and wrote some custom workarounds around this issue. Stumbled upon this from the Helm chart values.

Added docs for this and other missing configurations in #11297
