### ISSUE TITLE
`TestWorkflow_SearchArtifacts` failing on master

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8561]
Caused by #8557.
https://github.com/argoproj/argo-workflows/actions/workflows/ci-build.yaml?query=branch%3Amaster

@rohankmr414 could you please take a look?

**Comment by rohankmr414** [comment]
```
error: error pruning namespaced object /v1, Kind=PersistentVolumeClaim: rpc error: code = Unavailable desc = transport is closing
make: *** [Makefile:434: install] Error 1
```
@alexec I guess there is some issue with the installation. Not sure if #8557 caused this.

**Comment by alexec** [comment]
Not sure what is going on here. This is failing in unrelated PRs.

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/runs/6242825979?check_suite_focus=true

**Comment by rohankmr414** [comment]
> An example of a build that is failing, yet is on a branch which does not contain releated changes:
> 
> https://github.com/argoproj/argo-workflows/runs/6242825979?check_suite_focus=true

@alexec looks like I messed up the unit tests for `ArtifactSearchResults` #8557. Looks like the fix https://github.com/argoproj/argo-workflows/pull/8554/commits/70c6a9d6bbab740a288fe7447cda574aa8739d3f by @wujayway in #8554 should fix the issue

**Comment by alexec** [comment]
I think the fix should come in its own PR, otherwise all PR are blocked until that PR is merged,. Could I please ask you to submit that?

**Comment by rohankmr414** [comment]
> I think the fix should come in its own PR, otherwise all PR are blocked until that PR is merged,. Could I please ask you to submit that?

yeah sure
