### ISSUE TITLE
Looks like the `burst` configuration for the Workflow Controller doesn't actually do anything

### ISSUE THREAD

**Issue by Radolumbo** [argoproj/argo-workflows#8576]
Was hunting down what `burst` actually does for https://cloud-native.slack.com/archives/C01QW9QSSSK/p1651410938829379

Looking for `burst` in https://github.com/argoproj/argo-workflows takes us to https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/config.go#L85

Looks like it's using a built in golang Library, time/rate .. so we can take a look at https://pkg.go.dev/golang.org/x/time/rate#Limiter.Burst

This tells us
>Burst returns the maximum burst size. Burst is the maximum number of tokens that can be consumed in a single call to Allow, Reserve, or Wait, so higher Burst values allow more events to happen at once. A zero Burst allows no events, unless limit == Inf.

Interesting. Where are we using any of those calls in the Workflow controller on this `rateLimiter` object from the first link? Looks like .. here

https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/workflowpod.go#L429

So, we're using `Allow`. Based on

https://pkg.go.dev/golang.org/x/time/rate#Limiter.Allow

`Allow` is shorthand for `AllowN(time.Now(), 1)`.

So wait -- `burst` tells us how many tokens for rate limiting can be requested in a single call to `Allow`. However, the controller only ever requests a single token at time.

Thus -- I actually think that the configured `burst` for the Workflow Controller doesn't do anything at all.

Let me know if it seems like I missed anything here, but I'm pretty sure `burst` does nothing for the Workflow controller.

**Comment by alexec** [comment]
This bug is correct. Yet, I don't think we can change the code to use `AllowN`, `createWorkflowPod` does not know how many pods will be created.

**Comment by Radolumbo** [comment]
Sure, I totally agree -- not suggesting we try to add that functionality, but rather we should probably clear out code/guidance that is confusing to users. Maybe I can take a crack at some point soon.

**Comment by thor** [comment]
Coming across this by chance, I suggest re-opening this issue and marking it as frozen.

**Comment by CiprianAnton** [comment]
Seems like --qps and --burst are used in controller main: https://github.com/argoproj/argo-workflows/blob/master/cmd/workflow-controller/main.go#L86.

Can it have an impact on calls to k8s api?
