### ISSUE TITLE
Show name of person who created workflowtemplate/cronworkflow

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#8580]
# Summary

In the UI have another column next to each cronworkflow/workflowtemplate row that shows the username that created it

# Use Cases

auditability. currently we need oauth/dex/ldap credentials to login to the UI and we can add template/cronworkflow manifests in the UI but there is nothing that shows which user created which template/cronworkflow

**Comment by alexec** [comment]
The username of the creator is found in the reource labels. You could surface the "creator" label in the UI.

Would you like to submit a PR?

**Comment by tooptoop4** [comment]
not a javascript person :) but seems even creator is wrong - showing some hash type string instead of real username:
![image](https://user-images.githubusercontent.com/33283496/166567501-abe0b22b-3e97-4b4a-83fb-6ddf958f4a72.png)

**Comment by alexec** [comment]
It is correct. The `creator` is the value of OIDC subject. This is sometimes the username, but often the OIDCs identifier for the user. `creator-email` might be more useful. You must enable that.

**Comment by tooptoop4** [comment]
can creator-email be automatically derived from my login? or I have to type in the value on each workflow template/cronworkflow?

**Comment by alexec** [comment]
It should come from your OIDC claims.

**Comment by tooptoop4** [comment]
related to https://github.com/argoproj/argo-workflows/issues/10827 / https://github.com/dexidp/dex/issues/1719
