### ISSUE TITLE
examples/README.md content was moved and link to new location is broken

### ISSUE THREAD

**Issue by hblixt** [argoproj/argo-workflows#8601]
The [documentation update](url) (https://github.com/argoproj/argo-workflows/pull/8562) replaced the content of the [examples/README.md](https://github.com/argoproj/argo-workflows/tree/master/examples) file with a link that points to https://github.com/argoproj/argo-workflows/blob/master/docs/examples,  which 404s.

**Comment by terrytangyuan** [comment]
Thanks. Fixing in https://github.com/argoproj/argo-workflows/pull/8607.
