### ISSUE TITLE
argowf domain name environment variable?

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#8615]
I have an argo workflow that sends alerts, but wondering how to indicate if the alert came from DEV, SIT, PROD environments? is there any builtin argo variable that has the fully qualified DNS name of argoworkflows UI or something else?

update: use helm template language instead

**Comment by chandanpjain** [comment]
@tooptoop4 - I am looking for FQDN as captured in this ticket. Could you please explain your `update`? Do you mean passing the domain from helm template or is there a way to get the FQDN from a running workflow?

**Comment by tooptoop4** [comment]
just passed into helm
