### ISSUE TITLE
profile equiv ie inject environment variables into ALL workflows/cronworkflows

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#8616]
On linux hosts (non-k8s) its common to have a .profile file containing many environment variables. Does argo have similar concept? Can i define several environment variables in a single place and have them injected into ALL workflows? I know each workflow can reference a secret (not sure if it can reference configmap) per variable BUT i want a way that doesn't involve putting 10s of lines (ie diff env variables) in 100s of yaml files (ie diff cronWfs)

**Comment by terrytangyuan** [comment]
You can define template defaults at controller level to reduce duplication: https://argoproj.github.io/argo-workflows/template-defaults/

**Comment by tooptoop4** [comment]
@terrytangyuan do you know if these get injected into all EventSources/Sensors too?

**Comment by terrytangyuan** [comment]
It's only for the templates defined in your workflow spec.
