### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by Qalifah** [argoproj/argo-workflows#8625]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have previous experience in Go.**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #7618**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: **async**

**Comment by terrytangyuan** [comment]
That issue has already been worked on by another mentee. Would you like to pick another issue?

**Comment by Qalifah** [comment]
okay. what about issue #8613 ?

**Comment by terrytangyuan** [comment]
Sure. Assigned.

**Comment by terrytangyuan** [comment]
@alexec Would you like to mentor this since you created that issue?

**Comment by Qalifah** [comment]
@terrytangyuan i have created a PR to resolve the issue.
