### ISSUE TITLE
Argo Workflows v3.4: screenshots of archive retry and resubmit feature 

### ISSUE THREAD

**Issue by dpadhiar** [argoproj/argo-workflows#8637]
# Summary

Creating screenshots for Argo Workflows v3.4 blog to demonstrate argo archive retry/resubmit features.

Argo Workflows UI:

archive list with workflows to retry / resubmit

![argo archive ui list](https://user-images.githubusercontent.com/38965141/167022961-2d439556-4cf6-43ab-9663-e9eecd535325.png)

successful archived workflow able to be resubmitted but not retried (retry button disabled since wf is not failed)

![argo archive resubmit ui](https://user-images.githubusercontent.com/38965141/167023199-9adec6d7-2a32-41ed-b805-6f7b5aef667f.png)

failed archived workflow able to be retried and resubmitted

![argo archive ui retry button example](https://user-images.githubusercontent.com/38965141/167023773-b0029f01-6e75-46d7-9d17-d359317b9c42.png)

resubmit button prompt

![argo archive resubmit prompt ](https://user-images.githubusercontent.com/38965141/167024331-2a3ca73a-a892-4675-a454-0a422a876ad2.png)

retry button prompt

![argo archive retry prompt](https://user-images.githubusercontent.com/38965141/167024741-fa4284a4-971a-44b4-8e48-c78074250879.png)

**Comment by alexec** [comment]
Thank you.
