### ISSUE TITLE
Validate config-map links do not contain XSS

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8645]
We need to validate all links on Argo Server start-up to ensure they do not contain XSS:

- [ ] ADA-ARGO-SA-03: XSS in Argo Workflows chat url
- [ ] ADA-ARGO-SA-04: XSS in Workflows workflow link
- [ ] ADA-ARGO-SA-05: XSS in Pod Logs link
- [ ] ADA-ARGO-SA-06: XSS in sensor logs link
- [ ] ADA-ARGO-SA-07: XSS in Event Source logs url
- [ ] ADA-ARGO-SA-08: XSS in Pod link url

I think all links are set here:

https://github.com/argoproj/argo-workflows/blob/e6e0c9bb3b923a6d977875cbbd2744b8bacfce15/config/config.go#L71

Add `Config.Validate()` that checks all links are in-fact valid URLs (e.g. using `url.Parse)` so they cannot contain `javascript:` . Call `Validate()` when Argo Server starts-up.

**Comment by tczhao** [comment]
I wonder how robust do you want this feature to be?
We can implement quick checks for javascript prefix/protocol.
But for fully xss url prevention, it seems to be much more complicate
https://github.com/mganss/HtmlSanitizer

**Comment by alexec** [comment]
It only needs to block JavaScript. Whatever does that.
