### ISSUE TITLE
Support loops in `containerSet`

### ISSUE THREAD

**Issue by bencompton** [argoproj/argo-workflows#8647]
# Summary

It doesn't appear that loop constructs like `withItems` and `withParams` are currently supported within `containerSet`.

# Use Cases

The goal is to be able to dynamically add containers to a `containerSet` when the number of steps required aren't known until runtime, whereas this is possible today with pod-based steps.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
This is a nice idea, but it's not possible to achieve I'm afraid. A pod can only contain a small finite number of containers that must be defined in the spec. For looping, you'll have to use normal container template.
