### ISSUE TITLE
Workflows search box is useless (faster to use browser search)

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8648]
Remove the workflow search box.

https://github.com/argoproj/argo-workflows/blob/3e678b6cac42635588f04b22908f01693a95265a/ui/src/app/workflows/components/workflows-list/workflows-list.tsx#L168

**Comment by SaumyaBhushan** [comment]
CI / UI (pull_request) is failing. Don't know why? Any help?

**Comment by agilgur5** [comment]
Removed in #9208
