### ISSUE TITLE
show higher resolution of time for duration > 1 hour

### ISSUE THREAD

**Issue by ibuder** [argoproj/argo-workflows#8650]
# Summary

Show higher resolution of time when duration is > 1 hour (show minutes or hours and minutes). This applies everywhere duration is shown e.g. the "Workflows" view, "Workflow Details" view, and stage "Summary" view.

# Use Cases

I frequently use Argo Workflows to understand how long jobs take and how that changes over time as data and code changes. Because duration may only show resolution of one hour, there are ambiguous cases. For example, suppose workflow A shows a duration of 1 hour and workflow B shows a duration of 2 hours. I cannot tell if the real durations are
A = 1.000
B = 2.000
in which case B took twice as long, or

A = 1.499
B = 1.511
in which case they took nearly the same time.

ibuder @ Intuit

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
Internal ask.

**Comment by alexec** [comment]
To fix this, we can try making the default value of `sigfigs` of 2 in `formatDuration`:

https://github.com/argoproj/argo-workflows/blob/3e678b6cac42635588f04b22908f01693a95265a/ui/src/app/shared/duration.ts#L9

@ibuder would you like to implement this?

**Comment by ibuder** [comment]
@alexec Sure I will give it a try.

**Comment by alexec** [comment]
Here is the guide for contributing: https://argoproj.github.io/argo-workflows/CONTRIBUTING/
