### ISSUE TITLE
Inconsistent cron execution planning

### ISSUE THREAD

**Issue by disenchant** [argoproj/argo-workflows#8653]
I've submitted a scheduled workflow with a schedule of `0 0 22-28 * 2` in the web-UI the description of the execution schedule is correct "At 12:00 AM, between day 22 and 28 of the month, and on Tuesday" but the next run field shows 3 days (at the time of writing it's the 6th of May 2022) which means the next execution would be the 10th of May 2022 which is wrong. The next execution should be the 24th of May 2022 according to the cron schedule.

<img width="1436" alt="Screenshot_06_05_22__14_20" src="https://user-images.githubusercontent.com/686611/167077792-47488ab2-9bcf-4a72-ba96-50749bedf508.png">

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
If the UI is wrong, we should remove the code that is getting it wrong:

https://github.com/argoproj/argo-workflows/blob/master/ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx#L158

Would you be interested in submitting a fix to remove `getNextScheduledTime`?

**Comment by disenchant** [comment]
@alexec thanks for the pointer to the code in question. I didn't investigate yet if the actual cron schedule is properly used and just the UI is displaying a wrong next run or if the logic of the code actually believes this is correct (aka. my example would already execute on the 10th of May). Unfortunately I likely won't get to investigate and submit a fix any time soon 😖

**Comment by terrytangyuan** [comment]
@alexec Do we want to fix `getNextScheduledTime` or remove `NEXT RUN` column completely?

**Comment by alexec** [comment]
Remove it completely.

**Comment by tooptoop4** [comment]
its a useful field

**Comment by alexec** [comment]
Maybe we could try upgrading `cron-parser` or trying a different library?

**Comment by disenchant** [comment]
Please note that **it isn't just about what the field displays** as the `0 0 22-28 * 2` schedule actually executed today (10th of May 2022) which is **not** in line with the schedule as it is not in the range of the 22th to 28th day of the month.

**Comment by alexec** [comment]
https://crontab.guru/#0_0_22-28_*_2

This says “and on every Tuesday”, which the 10th is.

**Comment by alexec** [comment]
In fact, I can see the “and…” in your screenshot.

**Comment by disenchant** [comment]
@alexec true and I might be mistaken here but IMHO a job should only trigger if **all** fields of the cron expression are met. Else it could be argued that e.g. [`0 6 * * *`](https://crontab.guru/#0_6_*_*_*) would not only trigger at 06:00 but at every full hour as the fields would be independent which they aren't. Anyway, [`0 0 22-28 * */3`](https://crontab.guru/#0_0_22-28_*_*/3) might therefore be a better way of specifying what I want - at least it doesn't seem to include the "... and ..." anymore but I didn't yet give it a try in Argo 😅
