### ISSUE TITLE
Intermittently failing Argo Workflow pods

### ISSUE THREAD

**Issue by prasad-1729** [argoproj/argo-workflows#8671]
We are using Argo Workflow version-3.2.9

Error Message : **step group deemed errored due to child sample-test.onExit[0].exit-time error: Internal error occurred: admission plugin "OwnerReferencesPermissionEnforcement" failed to complete validation in 13s**

Any idea , how to fix this?

Thanks!

**Comment by terrytangyuan** [comment]
I don't think this has something to do with Argo Workflows. You probably want to look into your admission controller configurations: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/
