### ISSUE TITLE
Support specifying the pattern for transient errors in argo 2.12

### ISSUE THREAD

**Issue by kingsxiaoz** [argoproj/argo-workflows#8681]
# Summary

We are using argo 2.12.10 currently. It is quite stable, but we found sometimes admission controller webhook failed(network issue) which caused the failure of pod creation. Argo will then mark this node to error. We have to manually rerun these error steps. We found there is an enhancement (https://github.com/argoproj/argo-workflows/pull/4889) already in argo 3.x which will help us to solve this problem by specifying additional transient error pattern via env.

Since it will take us some time to upgrade from argo 2.12.10 to argo 3.x, I'm wondering if it is possible to cherrypick this commit (https://github.com/argoproj/argo-workflows/pull/4889) to argo version 2.12? Thanks.

# Use Cases

We are using argo workflow to execute some long running data processing tasks. If there is any network issue between API server and admission controller webhook, the pod creation will be failed and argo will mark the node to error. We have to rerun these error tasks manually currently.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
I’m afraid not. 2.12 has been out of support for sometime.
