### ISSUE TITLE
when an workflow started, quickly cancel this workflow , but the first step still execute...

### ISSUE THREAD

**Issue by ipythonlamp** [argoproj/argo-workflows#8682]
#### What happened:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/35916286/167339844-eaa482bf-baba-4ab8-9da4-c59bbb00b1f8.png">

when this workflow started, i quickly click cancel, but the first step still runing.... , as the above pic show.

#### What I expected?

I hope the whole step canceled

#### What version are you running?
```
argo: v3.2.7
  BuildDate: 2022-01-28T02:12:09Z
  GitCommit: bdc14b0d2e50b6d3b30f7b6ffbfd8ceae3214413
  GitTreeState: clean
  GitTag: v3.2.7
  GoVersion: go1.16.13
  Compiler: gc
  Platform: darwin/amd64
```

**Comment by sarabala1979** [comment]
@ipythonlamp Can you provide the Workflow controller log, wait container log of first step pod  and full workflow yaml (After stopped)
