### ISSUE TITLE
The `/signal` file is not used in v3.4 and can be deleted

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8702]
Search for `/signal` in the code to find it.

**Comment by hzliangbin** [comment]
@alexec may I have a try on this ?

**Comment by terrytangyuan** [comment]
@hzliangbin Yes feel free to submit a PR

**Comment by hzliangbin** [comment]
@alexec hi, I noticed that there is filed named `signal` in workflow, but signalContainer is still referenced. would you mind giving me some help docs ? thx

**Comment by terrytangyuan** [comment]
Removing assignee as there hasn't been any progress. Feel free to update here if you are still working on it.

**Comment by rakshitgondwal** [comment]
Hey @surbhiahuja !!
I would like to know that are you still working on this issue. 
If not, can I give it a try?

**Comment by deepyaman** [comment]
> @alexec hi, I noticed that there is file named `signal` in workflow, but signalContainer is still referenced. would you mind giving me some help docs ? thx

@hzliangbin FWIW I ran into the same issue; I can only assume the [`signal.SignalContainer` call in `signalContainers`] is necessary.

**Comment by hzliangbin** [comment]
@deepyaman yes, seems still in use。

**Comment by hzliangbin** [comment]
@terrytangyuan hi, maybe this issue could be closed
