### ISSUE TITLE
Remove security nudge from CLI

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8713]
The CLI displays a nudge, but this makes output harder to read, and I don't believe has impact:

```
This workflow does not have security context set. You can run your workflow pods more securely by setting it.
Learn more at https://argoproj.github.io/argo-workflows/workflow-pod-security-context/
```

I don't believe users change their behaviour (or are really that much interested in security) as a result of this.

Delete this func and its invocations:

https://github.com/argoproj/argo-workflows/blob/ee3765643632fa6d8dbfb528a395cbb28608e2e8/util/printer/workflow-printer.go#L117

**Comment by TheSwarnim** [comment]
I want to work on this issue. I've some experience using k8s previously and would like to work on this project. Can anyone assign this issue to me?

**Comment by terrytangyuan** [comment]
Assigned to you.
