### ISSUE TITLE
UI rendering fails if clearing template

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#8715]
1. click 'workflow templates'
2. click 'create new workflow template'
3. highlight the text as shown below then press 'DELETE' or 'Backspace' key on keyboard
4.
![image](https://user-images.githubusercontent.com/33283496/167911817-28046f30-69eb-4528-8e54-d8f79bb1d116.png)
5. observe the error:
![image](https://user-images.githubusercontent.com/33283496/167912039-e2da546a-fbb7-4c01-bd90-9c775d1d0d8f.png)

**Comment by alexec** [comment]
This is probably one of these places:

https://github.com/argoproj/argo-workflows/search?l=TSX&q=workflowMetadata

**Comment by tooptoop4** [comment]
crispy

**Comment by tooptoop4** [comment]
@alexec can u reopen?

**Comment by skalteis** [comment]
I still seem to hit this one (though I don't see an error message but the form just disappears entirely) in version 3.7.10
