### ISSUE TITLE
Argo worklow pods hang due to a bad interaction with Berglas

### ISSUE THREAD

**Issue by RmStorm** [argoproj/argo-workflows#8741]
## Summary

We are using Argo workflows extensively in our cluster for a large diversity of tasks, occasionally they fail _and hang_ forever. We finally nailed the thing down to a bad interaction between our secret injector ([Berglas](https://github.com/GoogleCloudPlatform/berglas)) and Argo Workflows. The problem is that Berglas relies on a mutating webhook that wraps the process in a pod to resolve secrets from urls to their actual values. Since Berglas runs after the workflow process has been wrapped by the Emissary, Berglas is outside the emissary. If Berglas fails for whatever reason the pod hangs forever.

We have resolved the issue by detecting when a pod is spawned by a workflow and putting berglas in between the process and the emissary. See the [issue I created here in the Berglas repo](https://github.com/GoogleCloudPlatform/berglas/issues/190). So that's a nice but extremely narrow solution. Is there a better way to go about this? If Argo workflows also relied on a mutating webhook to do the final emissary wrapping, is it possible to dictate the mutating webhook execution order and fix this problem in a more structural way? 

Anyway, I would love for someone to chime in, it's been bugging us for a while and we have simply been killing the stuck workflows whenever we noticed. I thought it would be helpful to at least have this issue out here and written up in case other people run into it as well.

## Diagnostics

Any workflow that uses the Emissary executor is vulnerable to this bug.

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by steinarvk-kolonial** [comment]
One way to fix this that avoids special-casing anything for Berglas would be to detect when the emissary doesn't even start up.

For instance, use a file just like the "exitcode" file that's already used for process exit:

- In the emissary command: on startup, create a file /var/run/argo/ctr/${containerName}/emissary-started
- In the wait command: time out after a short time (e.g. 30 seconds) if the emissary-started file is not detected.
