### ISSUE TITLE
DAG error

### ISSUE THREAD

**Issue by journey-wang** [argoproj/argo-workflows#8743]
What happened/what you expected to happen?

unable to evaluate expression '(0e62948f_e887_4daf_b5cb_10c1e74a61ea.Succeeded || 0e62948f_e887_4daf_b5cb_10c1e74a61ea.Skipped || 0e62948f_e887_4daf_b5cb_10c1e74a61ea.Daemoned)': bad number syntax: "0e62948f" (1:10)
 | (0e62948f_e887_4daf_b5cb_10c1e74a61ea.Succeeded || 0e62948f_e887_4daf_b5cb_10c1e74a61ea.Skipped || 0e62948f_e887_4daf_b5cb_10c1e74a61ea.Daemoned)
 | .........^

What version are you running?
v2.12.2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
We are not supporting v2.12..x Please upgrade to 3.2.x
