### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by jaimeamesti** [argoproj/argo-workflows#8751]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have previous experience in Kubernetes and Typescript.**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to get Argo Workflows running in development mode on my dev machine and some help to create my first pull request. I'm creating a new artefact connector for Azure Blob Storage.**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: **async or sync, CEST (Central European Summer Time)**

**Comment by terrytangyuan** [comment]
Please let us know if you are having issues setting up your dev environment. Please also pick an issue to work on once it's set up successfully.

**Comment by jaimeamesti** [comment]
I'm having issues setting up my dev environment.

I've added new code, some unit tests and I'm executing the tests without problems but I'm not able to run my changes on my local machine because I've never used vs develop containers.

My dev machine is a virtual machine with Windows server 2019, vs code and docker desktop. 

Could you send me some documentation about how to debug changes in local environment?

I miss some details from developer portal pages.

**Comment by terrytangyuan** [comment]
Unfortunately I don’t have much experience with Windows. Perhaps you could try the new dev container setup https://github.com/argoproj/argo-workflows/pull/8677.

**Comment by jaimeamesti** [comment]
Ok. I will try it. I will let you know my advances. Thanks @terrytangyuan

**Comment by jaimeamesti** [comment]
Hi again
I almost have everything ready with my dev machine.
I want to pick this issue: https://github.com/argoproj/argo-workflows/issues/1540

**Comment by terrytangyuan** [comment]
Sounds good.

**Comment by terrytangyuan** [comment]
That may not be a good first issue to work on. Do you want to pick up any other tasks?
