### ISSUE TITLE
Slack link is broken

### ISSUE THREAD

**Issue by alexrosenfeld10** [argoproj/argo-workflows#8752]
This link: https://slack.cncf.io/ found from https://argoproj.github.io/community/join-slack/ is broken.  I have burning questions but no place to ask them ☹️

**Comment by terrytangyuan** [comment]
It's working for me. Try again?

**Comment by alexrosenfeld10** [comment]
How strange. It fails for me in a regular browser, but works in incognito. 
![Uploading Screen Shot 2022-05-13 at 10.46.11 AM.png…]()

**Comment by alexrosenfeld10** [comment]
I guess we can close this seems like it's just a me issue

**Comment by mewa** [comment]
It doesn't seem to work for me either (both PC and mobile, tried different browsers).
