### ISSUE TITLE
v3.3.5 's web can't be access by using nodePort

### ISSUE THREAD

**Issue by berlinsaint** [argoproj/argo-workflows#8781]
v3.3.5 version argo 's web can't be accessed by using nodePort

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-05-16T10:05:03Z"
  name: argo-server
  namespace: argo
  resourceVersion: "20106136"
  selfLink: /api/v1/namespaces/argo/services/argo-server
  uid: 03fd27bc-de00-4893-a898-8ac10176e377
spec:
  clusterIP: 10.243.123.240
  externalTrafficPolicy: Cluster
  ports:
  - name: web
    nodePort: 30277
    port: 2746
    protocol: TCP
    targetPort: 2746
  selector:
    app: argo-server
  sessionAffinity: None
  type: NodePort
```

very slow  and  finally.. 
![image](https://user-images.githubusercontent.com/10629930/168592414-fe547366-9212-4a2a-aa0d-b897e6751534.png)

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by 9a8t9m8** [comment]
On my side also ClusterIP + manual port forward didn't change a thing and Argo behaved as described above.

**Quickfix that worked for me**
Download the manifest, e.g. quick start https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml. Then replace image tag: quay.io/argoproj/argocli:latest with prior version, e.g. quay.io/argoproj/argocli:v3.2.11.

**Comment by kianpu34593** [comment]
I manually changed the version of argocli to an older one in the quick-start-postgres.yaml. 
quay.io/argoproj/argocli:latest -> quay.io/argoproj/argocli:v3.2.11 

But when I tried to launch it, argo-server will CrashLoopBackOff
```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  6m37s                  default-scheduler  Successfully assigned argo/argo-server-85dc57ddc9-jc4zb to minikube
  Normal   Pulling    6m36s                  kubelet            Pulling image "quay.io/argoproj/argocli:v3.2.11"
  Normal   Pulled     5m22s                  kubelet            Successfully pulled image "quay.io/argoproj/argocli:v3.2.11" in 1m13.815124367s
  Normal   Created    3m58s (x5 over 5m22s)  kubelet            Created container argo-server
  Normal   Started    3m58s (x5 over 5m22s)  kubelet            Started container argo-server
  Normal   Pulled     3m58s (x4 over 5m21s)  kubelet            Container image "quay.io/argoproj/argocli:v3.2.11" already present on machine
  Warning  BackOff    93s (x22 over 5m20s)   kubelet            Back-off restarting failed container
```

I also tried to use an older commit SHA#eefc60b. But it also results in CrashLoopBackOff state.

**Comment by kianpu34593** [comment]
To follow up, I didn't know that I have to wait for DB and scheduler to be ready. So after waiting for a while. I can access the UI using manual port-forward.

**Comment by alexec** [comment]
I'm not sure I understand this bug. Please can you include any errors from the web console and log files.

**Comment by juliev0** [comment]
I believe I narrowed it down to this commit: 026298671
