### ISSUE TITLE
Use finalizer to prevent `pod deleted`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8783]
Like Spark does, we can add a finalizer to workflow pods. This will stop them being deleted by eviction etc and allow to controller to reconcille the without getting a "pod deleted" error.

## Implementation

Add a finalizer here named `workflow.argoproj.io`:

https://github.com/argoproj/argo-workflows/blob/37a3eb375410dd778d44f9965d9ec4465f1011d9/workflow/controller/workflowpod.go#L159

This needs to be removed when the pod is complete:

https://github.com/argoproj/argo-workflows/blob/859ebe99f760c6fb30870993359274a92cec2fb9/workflow/controller/controller.go#L481

And also here:

https://github.com/argoproj/argo-workflows/blob/859ebe99f760c6fb30870993359274a92cec2fb9/workflow/controller/controller.go#L492

**Comment by clementemmanuel** [comment]
@alexec sorry for the @ but any update or plans for when this implementation would ship or possible interim workarounds? Would love a resolution/workaround within argo but this is starting to be a more significant blocker for us in maintaining adoption. Kind of surprised there aren't more impacted by this, though i suppose smaller workloads just won't see this at all.  
  
Some more context on our issue; #8957, seems like if i could just manually update the workflow controller myself we'd be able to get around it

**Comment by alexec** [comment]
Someone needs to implement this. I won't be doing that I'm afraid.

**Comment by tooptoop4** [comment]
is there any workaround I can put in my wf yaml?
