### ISSUE TITLE
Workflow template concurrency 

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8785]
# Summary

An option to cancel in progress workflows when another workflow template is invoked concurrently. 

# Use Cases

So that we don’t have two instances of a workflow template running at the same time. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
This is more or less superseded by #12757
