### ISSUE TITLE
log version information in startup message

### ISSUE THREAD

**Issue by krancour** [argoproj/argo-workflows#8799]
# Summary

Hopefully it's not staring me in the face and I'm just missing it, but I don't see any version information of any kind in the startup messages from components like argo-server and workflow-controller.

# Use Cases

This would be extremely valuable information for community members who are submitting bug reports.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
You can check the image version specified in each of the deployments.

**Comment by krancour** [comment]
Sometimes. Running through the quickstart, I see latest...

**Comment by agilgur5** [comment]
The Controller and Server should have been printing their versions correctly in their logs since https://github.com/argoproj/argo-workflows/pull/2806. It is an `info` level log, for reference
