### ISSUE TITLE
training module bug? cannot access ui

### ISSUE THREAD

**Issue by krancour** [argoproj/argo-workflows#8800]
## Checklist

 

* [ ] Double-checked my configuration.
* [ ] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary

My apologies in advance if this isn't the correct repo to open this issue in...

Stepping through the ["Getting Started" scenario on KataCoda](https://www.katacoda.com/argoproj/courses/argo-workflows/getting-started), the "Argo Server" tab doesn't work, even after Argo is installed and running, and even after waiting up to 5 minutes, as KataCoda indicates may be necessary.

![Screen Shot 2022-05-18 at 8 28 11 PM](https://user-images.githubusercontent.com/1821014/169177194-448e32f2-15e0-4c2e-84f1-a52e23688a38.png)

(To be clear, I don't think this is a bug in Argo Workflows so much as I think it's an issue with the training module that might be worth fixing.)

What version are you running?

It appears to run v3.0.3.

## Diagnostics

To reproduce, just follow the ["Getting Started" scenario on KataCoda](https://www.katacoda.com/argoproj/courses/argo-workflows/getting-started).

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zhuyaguang** [comment]
please wait mins
