### ISSUE TITLE
argo-darwin-arm64 is not in release assets

### ISSUE THREAD

**Issue by jackliusr** [argoproj/argo-workflows#8812]
## Checklist

 

* [ ] Double-checked my configuration.
* [ ] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
argo-darwin-arm64 is not in release assets.  

What version are you running?

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml

```

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
@alexec @sarabala1979 Looks like we need to update the Makefile in the release 3.3 branch to include darwin-arm64. It's available in master branch but not the release branch. https://github.com/argoproj/argo-workflows/blob/release-3.3/Makefile#L170

**Comment by alexec** [comment]
Not a bug. #8450 is not in v3.3
