### ISSUE TITLE
"artifact not found" on UI when try to retrieve logs for pod log on s3.

### ISSUE THREAD

**Issue by xubofei1983** [argoproj/argo-workflows#8814]
## Checklist

 

* [ *] Double-checked my configuration.
* [ *] Tested using the latest version.
* [ *] Used the Emissary executor.

## Summary

Try to see pod log from argo UI (the workflow finished, and node deleted)

UI shows "artifact not found"

Inspect shows

http://argo.bravo.kariusdx.com/artifacts/workflow/import-readset-testkk2g8/import-readset-testkk2g8-3242695070/import-readset-logs
500 Internal Server Error
Response:  artifact not found

log exists on s3:
aws s3 ls s3://argo.bravo.kariusdx.com/import-readset-testkk2g8/import-readset-testkk2g8-3242695070/main.log
2022-05-20 12:02:15       6992 main.log

helm values:

      useDefaultArtifactRepo: true
      artifactRepository:
        # -- Archive the main container logs as an artifact
        archiveLogs: true
        # -- Store artifact in a S3-compliant object store
        # @default -- See [values.yaml]
        s3:
          bucket: argo.bravo.kariusdx.com
          #keyPrefix: prefix/in/bucket     #optional
          endpoint: s3.amazonaws.com       #AWS => s3.amazonaws.com; GCS => storage.googleapis.com
          insecure: true
          accessKeySecret:
            name: argo-s3-secrets-config
            key: aws_access_key_id
          secretKeySecret:
            name: argo-s3-secrets-config
            key: aws_secret_access_key

What happened/what you expected to happen?

retrieve log from artifact successfully.

What version are you running?

latest helm '0.15.0'

## Diagnostics

server log no error: 

time="2022-05-20T21:22:23.898Z" level=info msg="Download artifact" artifactName=import-readset-logs isInput=false namespace=workflow nodeId=import-readset-testkk2g8-3242695070 workflowName=import-readset-testkk2g8
time="2022-05-20T21:22:24.060Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2022-05-20T21:21:29Z" grpc.time_ms=54560.2 span.kind=server system=grpc

workflow yaml from k8s:
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    workflows.argoproj.io/pod-name-format: v1
  creationTimestamp: "2022-05-20T16:09:18Z"
  generateName: import-readset-test
  generation: 14
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Succeeded
    workflows.argoproj.io/workflow-archiving-status: Archived
  name: import-readset-testkk2g8
  namespace: workflow
  resourceVersion: "247556511"
  uid: 9b372075-7758-45f1-ba91-8668c5d9957f
spec:
...
status:
  artifactRepositoryRef:
    artifactRepository:
      archiveLogs: true
      s3:
        accessKeySecret:
          key: aws_access_key_id
          name: argo-s3-secrets-config
        bucket: argo.bravo.kariusdx.com
        endpoint: s3.amazonaws.com
        insecure: true
        secretKeySecret:
          key: aws_secret_access_key
          name: argo-s3-secrets-config
    default: true

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by efekete** [comment]
Are there any news on this? Same happens to me, too.

**Comment by xubofei1983** [comment]
I think It was some s3 permission issue.  I forgot exact changes but It works for me now.

The argo server log was not informative, but you can try access s3 from the pod to test the accessibility issue.
