### ISSUE TITLE
failed to check if secret argo-workflows-agent-ca-certificates exists: secrets "argo-workflows-agent-ca-certificates" is forbidden: User "system:serviceaccount:argo:argo" cannot get resource "secrets" in API group "" in the namespace "argo-sample"

### ISSUE THREAD

**Issue by sandeepitachi** [argoproj/argo-workflows#8829]
When tried to run HTTP hello world template, workflow is not running and throws below error 
`failed to check if secret argo-workflows-agent-ca-certificates exists: secrets "argo-workflows-agent-ca-certificates" is forbidden: User "system:serviceaccount:argo:argo" cannot get resource "secrets" in API group "" in the namespace "argo-cpe"` 

To run HTTP templates - created new executor clusterrole with minimum and agent clusterrole along with clusterrole bindings.
These Clusterrolebindings are binded to `service account: argo`

We also have serviceaccount named `argo` in argo-sample

**HTTP templates runs successfuly in `argo `namespace (cluster install was in this namespace)** 👍 

But HTTP temaplates are not running in `argo-sample` namespace

- Using the Emissary executor
- Argo workflows verison **v3.3.5**
- **Argo workflows Cluster Install (installed in namespace - `argo`)**
- We have multiple namespaces - `argo `and `argo-sample`
- **Workflow defaults service account is `argo`**

Example HTTP workflow using - https://github.com/argoproj/argo-workflows/blob/master/examples/http-hello-world.yaml

![image](https://user-images.githubusercontent.com/25717719/169925307-b8c61a44-8c30-4530-b095-c3633c7adccb.png)

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by nianqingdeguowang** [comment]
I faced the same error when started a HTTP workflow in other namespace (argo cluster install in argo namespace run HTTP workflow in argo-sample namespace)，I had configured the above configuration.  but it didn't work,Here is the sa I was used   
<img width="218" alt="log" src="https://github.com/user-attachments/assets/a941d739-2b75-49a7-b7e9-2379d06d838a">
I'm sure the sa have the role to access all api Resource in k8s(It has the admin role)
