### ISSUE TITLE
Have errors for swagger.json when opening with https://editor.swagger.io

### ISSUE THREAD

**Issue by JessieTeng89** [argoproj/argo-workflows#8830]
I found there are some errors when opening swagger.json with https://editor.swagger.io like below, I am new to GitHub, can you please help to assign this bug to me?  I want to work on this
![image](https://user-images.githubusercontent.com/101035990/169935003-5c576541-4cf4-437c-9336-c59482192a2a.png)
Structural error at paths./artifact-files/{namespace}/{idDiscriminator}/{id}/{nodeId}/{artifactDiscriminator}/{artifactName}.get.parameters
should NOT have duplicate items (items ## 4 and 6 are identical)
i: 6
j: 4
Jump to line 5861
Semantic error at paths./artifact-files/{namespace}/{idDiscriminator}/{id}/{nodeId}/{artifactDiscriminator}/{artifactName}.get.parameters.6
Sibling parameters must have unique name + in values
Jump to line 5890
Semantic error at paths./input-artifacts-by-uid/{uid}/{nodeId}/{artifactName}.get.parameters.0.name
Path parameter "namespace" must have the corresponding {namespace} segment in the "/input-artifacts-by-uid/{uid}/{nodeId}/{artifactName}" path
Jump to line 5971

What change needs making?
Update swagger.json file to fix the issue 

# Use Cases

When would you use this?
See API details

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by JessieTeng89** [comment]
Hi, I am new to Github.
Could you please assign it to me? I will try to fix it, this will be my first pr
Thanks

**Comment by agilgur5** [comment]
This apparently duplicated #8528
