### ISSUE TITLE
Slack invite link broken

### ISSUE THREAD

**Issue by mewa** [argoproj/argo-workflows#8831]
It seems the slack invite (https://slack.cncf.io) found at https://argoproj.github.io/community/join-slack/ is broken again (#8752). I tried accessing from PC, mobile, also tried different browsers, to no avail.

**Comment by dpadhiar** [comment]
I am seeing the same error on incognito both typing in `slack.cncf.io` as well as just clicking on the link. Will investigate further but this may be an issue with the CNCF slack itself.

**Comment by terrytangyuan** [comment]
It should work now. Usually it takes some time for CNCF to fix it.

**Comment by dpadhiar** [comment]
Thank you Terry!
