### ISSUE TITLE
Per-workflow dependent service

### ISSUE THREAD

**Issue by johnlinp** [argoproj/argo-workflows#8834]
I have a WorkflowTemplate for data processing. When a Workflow is created from the WorkflowTemplate, I need a corresponding database service to start in order to let my Workflow use it. When the Workflow finish its steps, I want this database service to stop and clean up itself.

I wish this database service to be "per-workflow" style, i.e. starts when the Workflow starts and ends when the Workflow ends. The reason I want it this way is that I want to give each Workflow instance a clean and independent database service so that I don't have to worry about these Workflows mess up with each other.

I'm filing this feature request because I failed to find a straightforward way to achieve this. Please let me know if I miss something. Thank you.

**Comment by alexec** [comment]
You may use a daemon step to do this.

**Comment by johnlinp** [comment]
@alexec Thank you! The daemon step looks promising to me.
