### ISSUE TITLE
Remove Katacoda links from docs by 15th June

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8840]
Katacoda is being shuttered:

https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html

We need to remove it from the docs:

https://github.com/argoproj/argo-workflows/search?q=katacoda

**Comment by caelan-io** [comment]
Ah, bummer! That's really annoying. I can take this docs change on and see to it about finding another online course/ tutorial solution.

Do you happen to know of any other online course/ tutorial options off the top of your head?

**Comment by alexec** [comment]
No, I'm not sure replacing it is worthwhile, and can be dealt with separately.

**Comment by terrytangyuan** [comment]
An alternative: https://instruqt.com/
