### ISSUE TITLE
Remove "30m to talk anything Argo" 

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8868]
Remove from here:

https://github.com/argoproj/argo-workflows/blob/e24ecd6c4b81a169cb1259895f11a5249d164471/.github/ISSUE_TEMPLATE/config.yml#L14

**Comment by kevgeo** [comment]
HI @alexec , I would like to take up this issue. Since this is just editing a file within .github folder, we don't have to run any tests after removing the relevant lines right?

**Comment by sarabala1979** [comment]
@kevgeo Please submit the PR
