### ISSUE TITLE
Adding Sensor dashboard to UI

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-workflows#888]
**Is this a BUG REPORT or FEATURE REQUEST?**: 
FEATURE REQUEST

With addition of argo-events to argoproj ecosystem, it would be nice to have a Sensor dashboard integrated in Argo-UI.

@jessesuen  @alexmt 

Thoughts?

**Comment by alexmt** [comment]
I very like the idea. I can image lots of useful features which such UI might give to argo users: browse available sensors; find which sensor triggered workflow; probably even manage sensors. I would be happy to work on it.

**Comment by VaibhavPage** [comment]
@alexmt , shall we target this feature (basic read only Sensor dashboard) in next Argo UI release?

**Comment by alexmt** [comment]
As far as I know we have two use-cases which might benefit from events management UI: continuous integration and ML use case.
For CI use case following UI changes are required:

- add Sensors list page - allows list/filter configured Sensors; allows navigate to Sensor details page 
- add Sensors detail page - allows to see Sensor CRD Yaml;  allows to find workflows triggered by Sensor (navigate to workflows list with appropriate filter set )
- add sensors filter to workflows list page

Listed features should be enough to completely replace https://github.com/argoproj/argo-ci .

@jlewi can you think of any other UI features for your use case?

**Comment by VaibhavPage** [comment]
Also one of the future development tasks for argo-events is to store the events in some datastore and make sensor re-playable.  If we can let user replay Sensor from UI, that would add great value.

**Comment by jlewi** [comment]
@alexmt Nothing comes to mind; but to be honest I haven't thought much about it.

/cc @vicaire

**Comment by alexec** [comment]
![sensors](https://user-images.githubusercontent.com/1142830/85061352-8cc3bd80-b15b-11ea-91e5-367add173b48.png)

**Comment by alexec** [comment]
So technical barriers are removed - the question now becomes - what use cases are we supporting?

**Comment by lkeijser** [comment]
Quickly viewing the logs of the various pods in the argo-events namespace would come in handy. I would like to give some people access to them, without requiring them to log into a shell and operate k8s commands.
