### ISSUE TITLE
better error message when same env variable is in workflow and templatedefaults

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#8887]
```
"Pod "mywf-1653974400-2680345542" is invalid: [spec.containers[1].env[3].valueFrom: Invalid value: "": may not be specified when `value` is not empty, spec.containers[1].env[4].valueFrom: Invalid value: "": may not be specified when `value` is not empty, spec.containers[1].env[5].valueFrom: Invalid value: "": may not be specified when `value` is not empty]"
```
currently getting an error like that when i have same env name in templateDefaults and in the workflow. the message is a bit confusing, perhaps a better message would be `"error: same env key '<theActualKey>' being specified twice"`

**Comment by terrytangyuan** [comment]
Could you provide a minimal reproducible example?

**Comment by tooptoop4** [comment]
probably fixed by https://github.com/argoproj/argo-workflows/pull/12426
