### ISSUE TITLE
Create a new web course for an intro to Argo Workflows

### ISSUE THREAD

**Issue by caelan-io** [argoproj/argo-workflows#8899]
# Summary

[Katacoda is being shuttered](https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html), so the Argo Workflows Katacoda course was removed from the docs.

Proposal: Pipe Katacoda content into a new web-based course platform and then update the docs. (quick-start.md, training.md, others)

Current candidates:

- https://instruqt.com/
- https://killercoda.com/

# Use Cases

New users would still like an easy way to a) try out Argo Workflows without setting up a K8s cluster, and b) learn the basics of Argo Workflows.

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by mashriram** [comment]
Can we use **killercoda** as a solution
as we can directly **migrate katacoda  projects** without starting from scratch

**the link attached below is the about page of their official website** 
https://killercoda.com/about

**this link below shows an example  of kubernetes-dashboard running from killercoda**
https://killercoda.com/kubernetes/scenario/kubernetes-dashboard
`_Follow the steps mentioned to run the dashboard_`

**Comment by mashriram** [comment]
Im interested in working on this particular issue

**Comment by caelan-io** [comment]
Thanks, @mashriram. Yes, I have been testing Killercoda and Instruqt with a couple other contributors, and we plan to have an update posted within 4-6 weeks about a new course for the community to try out and provide feedback.

**Comment by alexec** [comment]
This is number 3 most popular issue. How is it going?

**Comment by caelan-io** [comment]
Going well! We should have a new course live in a couple weeks, around ArgoCon. We'll post an update here and will open a PR to update the docs.

We will need folks to take the new course and provide feedback.

**Comment by caelan-io** [comment]
Hi Everyone, @tico24 and I have updated the intro to Argo Workflows course that @alexec initially created last year. Please access it here on Killercoda (a free Katacoda replacement): https://killercoda.com/pipekit/course/argo-workflows/ 

We made some improvements based on prior feedback and enabled the course for the latest version of Argo Workflows, v3.4.2. Next, we're going to add additional modules to the course based on user feedback!

Please note that **Killercoda is in beta as a new platform**, so we expect that you may encounter some bugs. That said, we have tested the course and it is functional. **It's important to use either Chrome or Safari browser to complete the course.** To access the course, you will need to create a Killercoda account.

We're going to close this issue now. We're taking feedback for improving the course on the course repo here: 
https://github.com/pipekit/argo-workflows-intro-course/

**If you encounter bugs**, please open issues on [the course repo](https://github.com/pipekit/argo-workflows-intro-course/).

**If you have ideas or requests for future course content**, please also open issues on [the course repo](https://github.com/pipekit/argo-workflows-intro-course/).

**If you would like to contribute** to the course, please open an issue on the course repo with the title "Contributor request - your name" and describe a) how/what you would like to contribute, and b) your experience level with Argo Workflows.

Also, once the course is stable (and Killercoda is also stable, which is a factor we can't control) we will migrate it to the Argoproj GitHub org.

Thanks for your support in improving the course! We're looking forward to your feedback.
