### ISSUE TITLE
Upload  archivelogs of init and wait containers

### ISSUE THREAD

**Issue by DiegoFlop** [argoproj/argo-workflows#8902]
# Summary

I would like to be able to upload the logs of the init and wait containers along with the main one.
I currently have the archiveLogs configured with S3 and everything works correctly, except that the S3 bucket only uploads the main container log.
Due to resource issues we use a PodGC to delete them as soon as they are completed and the workflow is deleted after 2 minutes.
In the file tab they are maintained because I have persistence with a Posgress but when it comes to review why something may have failed as we do not have the init or wait logs it is very difficult to trace the problem.

# Use Cases

- Flow traceability
- Audit
- Performance

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
Superseded by #12640 which has more details and more upvotes
