### ISSUE TITLE
Support MYSQL DB options for persistence

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#8905]
# Summary

What change needs making?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
Duplicate of #8901 and already completed in #8157 per [JM's comment there](https://github.com/argoproj/argo-workflows/issues/8901#issuecomment-1212385568)
