### ISSUE TITLE
Make side panels resizable

### ISSUE THREAD

**Issue by dakotalillie** [argoproj/argo-workflows#8917]
# Summary

It would be nice if side panels (such as the ones for viewing workflow node details and logs) were resizable.

# Use Cases

The primary use case I have in mind would be to make it easier to view content which exceeds the standard width of the side panel. It might also be useful with the logs side panel, to allow the primary page content to be visible alongside the logs.

I did a rough mockup (sorry for the poor performance, screen recording slows my computer down significantly):

https://user-images.githubusercontent.com/20373585/172034555-5ada41e7-3e61-443a-8680-676bae3a50a3.mov

I'd be happy to submit a PR if this gets the go-ahead.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by sarabala1979** [comment]
@dakotalillie Nice enhancement. Do you like to submit the PR for this feature?

**Comment by dakotalillie** [comment]
Sure thing! I'll submit a PR shortly.
