### ISSUE TITLE
cannot start argo workflow using template manifest

### ISSUE THREAD

**Issue by kianpu34593** [argoproj/argo-workflows#8919]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

I was using a template manifest provided: https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start-postgres.yaml

When I ran: 
```
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start-postgres.yaml
```

It output the error:
```
error: error parsing https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start-minimal.yaml: error converting YAML to JSON: yaml: line 28: mapping values are not allowed in this context
```
The expected behavior is `kubectl` will apply this manifest and start the argo workflow.

The interesting thing is when I copy the manifest to my local machine and apply it will work.

What version are you running?

minikube 1.25.2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
You need to use the raw URL for GitHub content.

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/raw/master/manifests/quick-start-minimal.yaml
