### ISSUE TITLE
Container steps also have stdout stored in result output parameter

### ISSUE THREAD

**Issue by lacarvalho91** [argoproj/argo-workflows#8921]
# Summary

The [docs](https://github.com/argoproj/argo-workflows/blob/master/docs/walk-through/output-parameters.md) seem to suggest that only `script` steps will automatically capture `stdout` into the `result` output parameter. I did some testing and this doesn't seem to be the case and I couldn't see anywhere in the code that only makes this happen for `script` steps.

For this card I believe we should update the docs to reflect this and rename functions for capturing `stdout` to remove references to script (e.g. [this function](https://github.com/argoproj/argo-workflows/blob/cb616556c965329284553d4a634bbf8f0a588195/workflow/executor/executor.go#L705)). 

# Use Cases

From the docs I was under the impression `container` steps wouldn't have their `stdout` automatically captured in the `result` output parameter.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Feel free to submit a PR to improve the docs.

**Comment by lacarvalho91** [comment]
I'd be happy to. Could I get some confirmation that I'm correct and not missing something before I do so?

**Comment by kasteph** [comment]
Hey @lacarvalho91 I just wanted to let you know that I verified this by running a workflow that uses `{{ tasks.previous-task.outputs.result }}` as an input and it worked.
