### ISSUE TITLE
Have errors for swagger.json when opening with https://editor.swagger.io

### ISSUE THREAD

**Issue by JessieTeng89** [argoproj/argo-workflows#8922]
I found there are some errors when opening _.primary.swagger.json with https://editor.swagger.io/ like below:
![image](https://user-images.githubusercontent.com/101035990/172135467-859887e1-27f2-4291-b37b-304f8088352b.png)

Errors
Semantic error at paths./artifact-files/{namespace}/{idDiscriminator}/{id}/{nodeId}/{artifactDiscriminator}/{artifactName}.get.responses.default.schema.$ref
$refs must reference a valid location in the document
Jump to line 71
Semantic error at paths./artifacts/{namespace}/{name}/{nodeId}/{artifactName}.get.responses.default.schema.$ref
$refs must reference a valid location in the document
Jump to line 104
Structural error at paths./input-artifacts/{namespace}/{name}/{nodeId}/{artifactName}.get.responses.200
should NOT have additional properties additionalProperty: content
Jump to line 129
Semantic error at paths./input-artifacts/{namespace}/{name}/{nodeId}/{artifactName}.get.responses.default.schema.$ref
$refs must reference a valid location in the document
Jump to line 138
Structural error at paths./artifacts-by-uid/{uid}/{nodeId}/{artifactName}.get.responses.200
should NOT have additional properties additionalProperty: content
Jump to line 159
Semantic error at paths./artifacts-by-uid/{uid}/{nodeId}/{artifactName}.get.responses.default.schema.$ref
$refs must reference a valid location in the document
Jump to line 168
Semantic error at paths./input-artifacts-by-uid/{uid}/{nodeId}/{artifactName}.get.responses.default.schema.$ref
$refs must reference a valid location in the document
Jump to line 197
Semantic error at definitions.github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ParallelSteps.items.$ref
$refs must reference a valid location in the document
Jump to line 206

**Comment by JessieTeng89** [comment]
I would like to work on this issue, please assign it to me if possible, Thanks

**Comment by terrytangyuan** [comment]
Assigned

**Comment by Agitatra** [comment]
I get the same error, both with the downloaded version 4.2.7 and using editor.swagger.io.
What boggles me, is that my openapi file is literally a downgraded/reduced version of the pet-store supplied with the swagger-editor, which also has features 200 responses accompanied by content, but does not trigger this message.  The only difference I see is, that the pet shop version refers to a complex type while my return content is simply a string.

**Comment by JessieTeng89** [comment]
I am still working on this issue, will create the PR soon

**Comment by JessieTeng89** [comment]
I have created a PR for this issue, and it is pending on merge, so this is still active
