### ISSUE TITLE
Error "Create pods 403" in workflow-controller when setting istio annotation

### ISSUE THREAD

**Issue by cotjoey** [argoproj/argo-workflows#8928]
Hello,

I am trying to configure Istio on my batch pods, but when I do so, I get a "Create pods 403" in the workflow-controller pod logs:

```
time="2022-06-07T02:02:07.820Z" level=info msg="Create events 201"
time="2022-06-07T02:02:07.937Z" level=info msg="Create pods 403"
time="2022-06-07T02:02:07.937Z" level=warning msg="Non-transient error: pods \"my-batch-8m6bt-1795743203\" is forbidden: non-admin user \"argo:argo\" [service account \"my-namespace:submit-workflow-serviceaccount\"]. The configured privileged attributes access for non-admin users (\"[]\")(\"[]\") and for service accounts (\"[]\")(\"[]\") lack required permissions to use attributes [kernelcapabilities] for resource my-batch-8m6bt-1795743203"
time="2022-06-07T02:02:07.937Z" level=info msg="Failed to create pod my-batch-8m6bt.prs-to-maax-provider-producer (my-batch-8m6bt-1795743203): pods \"my-batch-8m6bt-1795743203\" is forbidden: non-admin user \"argo:argo\" [service account \"my-namespace:submit-workflow-serviceaccount\"]. The configured privileged attributes access for non-admin users (\"[]\")(\"[]\") and for service accounts (\"[]\")(\"[]\") lack required permissions to use attributes [kernelcapabilities] for resource my-batch-8m6bt-1795743203" namespace=my-namespace workflow=my-batch-8m6bt
time="2022-06-07T02:02:07.937Z" level=warning msg="Non-transient error: pods \"my-batch-8m6bt-1795743203\" is forbidden: non-admin user \"argo:argo\" [service account \"my-namespace:submit-workflow-serviceaccount\"]. The configured privileged attributes access for non-admin users (\"[]\")(\"[]\") and for service accounts (\"[]\")(\"[]\") lack required permissions to use attributes [kernelcapabilities] for resource my-batch-8m6bt-1795743203"
time="2022-06-07T02:02:07.937Z" level=error msg="Mark error node" error="pods \"my-batch-8m6bt-1795743203\" is forbidden: non-admin user \"argo:argo\" [service account \"my-namespace:submit-workflow-serviceaccount\"]. The configured privileged attributes access for non-admin users (\"[]\")(\"[]\") and for service accounts (\"[]\")(\"[]\") lack required permissions to use attributes [kernelcapabilities] for resource my-batch-8m6bt-1795743203" namespace=my-namespace nodeName=my-batch-8m6bt.prs-to-maax-provider-producer workflow=my-batch-8m6bt
time="2022-06-07T02:02:07.937Z" level=info msg="node my-batch-8m6bt-1795743203 phase Pending -> Error" namespace=claim-payment workflow=my-batch-8m6bt 
```

The way I configure istio on my batch pods is by adding the following annotation to the workflowtemplate:

```
spec:
  templates:
      metadata:
        annotations:
          sidecar.istio.io/inject: 'true'
```

My batch pods can launch successfully when I remove the annotation from the workflow template. It defaults to sidecar.istio.io/inject: 'false' when I don't specify it.

In tried adding a psp (PodSecurityPolicy) to both the "argo:argo" and "my-namespace:submit-workflow-serviceaccount" service accounts using a ClusterRoleBinding - I get the same error.

I also tried to remove the securityContext that I have set in my workflow-controller deployment:

```
securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
```

.... I get the same error also.

I understand that there might be a problem with using Istio with Argo, but our idea was to use the above annotation along with this property in the istio configuration to make sure istio is up before the batch pod is:

```
proxy.istio.io/config: |
            holdApplicationUntilProxyStarts: true
```

I also don't understand the format of the exception itself. Normally it points to one service account, but in my case it seems to be point to two ('argo:argo' & 'my-namespace:submit-workflow-serviceaccount'):

```
non-admin user \"argo:argo\" [service account \"my-namespace:submit-workflow-serviceaccount\"].
```

I am using Argo argoproj/argoexec:v3.1.13, Istio 1.13.3, Kubernetes v1.20.8-mirantis-2.

Thank you,
Joey

**Comment by agilgur5** [comment]
There is a documentation page on [Sidecar Injection](https://argoproj.github.io/argo-workflows/sidecar-injection/).

> I also tried to remove the securityContext that I have set in my workflow-controller deployment:

The error is from the executor Pod, so I don't think the Controller's `securityContext` is relevant.

> In tried adding a psp (PodSecurityPolicy) to both the "argo:argo" and "my-namespace:submit-workflow-serviceaccount" service accounts using a ClusterRoleBinding - I get the same error.

PSPs are deprecated in k8s now, but your SA must have `use` permissions for the relevant PSPs _and_ the `securityContext` must require the PSP (as you cannot directly set a PSP).

Also you shouldn't need elevated permissions if you use [`istio-cni`](https://istio.io/latest/docs/setup/additional-setup/cni/), which is recommended when using Istio in general.
