### ISSUE TITLE
feature: allow special characters in label values and length > 63

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#8931]
getting this error when i try to save s3 path argument with slashes into a label:

```a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?') Invalid```

or 
"must be no more than 63 characters, metadata.labels: Invalid value:"

**Comment by alexec** [comment]
Not a bug. 

https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
