### ISSUE TITLE
Resources for artifact input init-containers

### ISSUE THREAD

**Issue by scott-grimes** [argoproj/argo-workflows#8948]
# Summary

Users should be able to specify the resources for artifact input init-containers

# Use Cases

In our multi-tenant environment we strictly enforce quotas and have limitranges to ensure that containers set memory and cpu limits+requests by default. 

The limitrange is set low by default to encourage developers to set them up properly, while still providing a low-friction developer experience when iterating on new projects. 

In our particular use case a git artifact pulling a large-ish repo is causing problems. Right now you can specify init containers as part of a workflow, but you cannot specify resources used for the init containers responsible for fetching workflow inputs (from git, s3, etc)

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
You should be able to set a global value for this in the controller config-map. Alternatively, you could use `podSpecPatch` to set it.

**Comment by scott-grimes** [comment]
ah excellent, that will work perfectly. for those following: https://github.com/argoproj/argo-workflows/blob/master/examples/pod-spec-patch.yaml
