### ISSUE TITLE
Unable to run artifact private git test

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo-workflows#8953]
## Summary

```
			if os.Getenv("CI") == "true" {
				t.SkipNow()
			}
			privateKey, err := os.ReadFile(homedir.HomeDir() + "/.ssh/id_rsa")
			assert.NoError(t, err)
			driver := &ArtifactDriver{SSHPrivateKey: string(privateKey)}
			assert.NoError(t, load(driver, &wfv1.GitArtifact{Repo: "git@github.com:argoproj-labs/private-test-repo.git"}))
			assert.FileExists(t, path+"/README.md")
```

https://github.com/argoproj/argo-workflows/blob/master/workflow/artifacts/git/git_test.go#L29-L36

Most of the contributors don't have access to this private repo
perhaps we should guard this test in a different way

@alexec 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by ibotdotout** [comment]
I faced this issue too. I would like to help to clean it up. 
Do you have any suggestion for this ?

**Comment by tczhao** [comment]
I'm thinking for these steps that require private key
skip them if certain environmental variable are not present
https://docs.github.com/en/actions/learn-github-actions/environment-variables

**Comment by alexec** [comment]
We can’t run this test locally, or on CI. The only place it can be run is my laptop. Let’s skip this test for everyone.
