### ISSUE TITLE
v3.3.5: workflow-controller panic at context.go:125 GetTemplateFromRef

### ISSUE THREAD

**Issue by khmjp** [argoproj/argo-workflows#8956]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

Workflow-controller panics suddenly, and once the panic occurs, it continues.
I found other user had same panic in slack.
https://cloud-native.slack.com/archives/C01QW9QSSSK/p1652457569109429

What version are you running?
v3.3.5
This panic was not happend at v3.1.6

## Diagnostics
Note that 
- ClusterWorkflowTemplate certainly exists although it got an error.
- Controller restarts does not fix it.
```
time="2022-06-13T06:04:09.208Z" level=info msg="Get clusterworkflowtemplates 200"
time="2022-06-13T06:04:09.251Z" level=info msg="Processing workflow" namespace=ns1 workflow=wf-lx4zf
time="2022-06-13T06:04:09.251Z" level=info msg="Queueing Failed workflow ns2/wf-kzrs5 for delete in -29s due to TTL"
time="2022-06-13T06:04:09.251Z" level=info msg="Deleting garbage collected workflow 'ns2/wf-kzrs5'"
time="2022-06-13T06:04:09.258Z" level=info msg="Task-result reconciliation" namespace=ns1 numObjs=1 workflow=wf-lx4zf
time="2022-06-13T06:04:09.258Z" level=info msg="task-result changed" namespace=ns1 nodeID=wf-lx4zf-671665593 workflow=wf-lx4zf
time="2022-06-13T06:04:09.259Z" level=error msg="Mark error node" error="clusterworkflowtemplates.argoproj.io \"cluster-template-wf\" not found" namespace=ns1 nodeName="wf-lx4zf[0].wf[0].wf-main-pvc(0)" workflow=wf-lx4zf
time="2022-06-13T06:04:09.259Z" level=info msg="node wf-lx4zf-671665593 phase Running -> Error" namespace=ns1 workflow=wf-lx4zf
time="2022-06-13T06:04:09.259Z" level=info msg="node wf-lx4zf-671665593 message: clusterworkflowtemplates.argoproj.io \"cluster-template-wf\" not found" namespace=ns1 workflow=wf-lx4zf
time="2022-06-13T06:04:09.259Z" level=info msg="node wf-lx4zf-671665593 finished: 2022-06-13 06:04:09.259111158 +0000 UTC" namespace=ns1 workflow=wf-lx4zf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x19937b6]

goroutine 292 [running]:
github.com/argoproj/argo-workflows/v3/workflow/templateresolution.(*Context).GetTemplateFromRef(0x0, 0xc009b2c030)
	/go/src/github.com/argoproj/argo-workflows/workflow/templateresolution/context.go:125 +0x36
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).GetNodeTemplate(0xc007632240, 0xc00a8b4b00)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2093 +0x105
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).assessNodeStatus(0xc007632240, 0xc004a16e30, 0xc00a8b4b00)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1162 +0x9e
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation.func1(0xc004a16e30)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:997 +0x345
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation.func2(0xc000b94fb8)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1037 +0x92
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1035 +0x21a"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by juliev0** [comment]
@khmjp can you provide an example Workflow and WorkflowTemplate that cause this, so I can try to reproduce it? Also, how often does it happen?

**Comment by juliev0** [comment]
@khmjp It would also be great if you could provide the full log as an attachment. Thanks.

**Comment by khmjp** [comment]
This is caused by any workflow have clusterworkflowtemplates reference.

I’m trying to reproduce this in staging environment, but I cannot now. It may be caused by performance issue.

**Comment by juliev0** [comment]
So, looking at your log I see: "Queueing Failed workflow ns2/wf-kzrs5 for delete in -29s due to TTL"

Any concerns that:
a) the workflow was in "Failed" state? or does that make sense for your case?
b) the garbage collection time was a negative number? (-29s)

What is your PodGC setting? It would be great if you could provide some sort of Workflow and ClusterWorkflowTemplate that I could look at so I can see what settings are being used.

**Comment by juliev0** [comment]
It's interesting that in both your case and the slack post you referenced, there was a failure in the Workflow that seems to have preceded not finding the Template. I'm guessing that's not a coincidence? If you know that this occurred before when there was no failure let me know.

**Comment by khmjp** [comment]
After further investigation, we found that the panic occurs immediately after switching the leader of workflow-controller, which is configured as HA.

The workflows that logged "Queueing Failed" were all workflows that failed even under normal conditions.

The garbage collection time was all within the secondsAfterFailure range in the log output at the time of the first panic.
It seems that the repeated panics resulted in a negative time because they were not processed.

**Comment by juliev0** [comment]
Thanks for investigation. Do you know if it happens _every_ time that a leader election occurs?

The Kubernetes client _Informer_ we're using provides status updates about entities (such as ClusterWorkflowTemplate) to the Controller asynchronously with the Controller keeping a local cache of the information. When the leader election occurs, the Controller creates an Informer [here](https://github.com/argoproj/argo-workflows/blob/master/workflow/controller/controller.go#L421) and runs it _asynchronously_ on the next line. I'm thinking maybe when we try to use that Informer to do our "list ClusterWorkflowTemplates" operation, that asynchronous call hasn't been made yet, and the cache we're reading from is empty. I'll investigate further.

**Comment by khmjp** [comment]
Thanks for resolving the issue so promptly. Looking forward to the release.

> Do you know if it happens every time that a leader election occurs?

Yes, now that I am able to reproduce this, I confirm that it happens every time.
