### ISSUE TITLE
Variable whitespace not behaving as documented

### ISSUE THREAD

**Issue by caelan-io** [argoproj/argo-workflows#8960]
Creating an issue to document a regression report from @RyanCopley, quoted below from closed PR #8867.

As a first step, I can add a doc to document this unexpected behavior for whitespace between the brackets and the variable. More reproducible spacing errors need to be reported in order to rule out this unintended behavior elsewhere.

## Summary

> I work for a company that has a large argo workflow, and we've been struggling to reconcile strange behaviors around the space needed for the interpolated variables. I believe this is because this specific regex is not meeting the contract that was documented, and does not allow for those additional white space between the bracket and variable.
> https://github.com/argoproj/argo-workflows/blob/master/docs/variables.md#simple
> Simple tags may have white-space between the brackets and variable.
> https://github.com/argoproj/argo-workflows/blob/master/util/template/simple_template.go#L13 provides that contract during the workflows actual execution (e.g. argo submit), however, there is a code path during argo lint that tries to use the file i'm changing to determine if it is or isn't a parameter, in order to detect if it should allow that as a "global" param, but it doesn't follow that same contract?
> https://github.com/argoproj/argo-workflows/blob/master/workflow/validate/validate.go#L872
> I posted about this in the slack:
> https://cloud-native.slack.com/archives/C01QW9QSSSK/p1653497167145119
> https://cloud-native.slack.com/archives/C01QW9QSSSK/p1653600495901169

What version are you running?
3.0.7

---
**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by JPZ13** [comment]
| **Name** | **Test case** | **Interpolates successfully?** |
| --- | --- | --- |
| Base case | {{foo}} | Yes |
| Base case w/ whitespace | {{ foo }} | Yes |
| Unresolved reference | {{foo}} | Yes |
| Unresolved reference w/ whitespace | {{ foo }} | Yes |
| Expression base case | {{=foo}} | Yes |
| Expression w/ whitespace | {{ =foo }} | No |
| Unresolved expression | {{=foo}} | Yes |
| Unresolved expression w/ whitespace | {{ =foo }} | Yes |
| Allowed retries | {{=sprig.int(retries)}} | Yes |
| Allowed retries w/ whitespace | {{ =sprig.int(retries) }} | Potentially, barring changing the expected result of the test case |
| Disallowed expression | {{=foo}} | Yes |
| Disallowed expression w/ whitespace | {{ =foo }} | No |
| Nested base case | {{- with secret &quot;{{inputs.parameters.message}}&quot; -}}<br>{{ .Data.data.gitcreds }}<br>{{- end }} | Yes |
| Nested case with whitespace | {{- with secret &quot;{{ inputs.parameters.message }}&quot; -}}<br>{{ .Data.data.gitcreds }}<br>{{- end }} | No |
| Second layer nesting | {{- with {{ secret &quot;{{inputs.parameters.message}}&quot; -}}<br>{{ .Data.data.gitcreds }}<br>{{- end }} | Yes |
| Second layer nesting with whitespace | {{- with {{ secret &quot;{{ inputs.parameters.message }}&quot; -}}<br>{{ .Data.data.gitcreds }}<br>{{- end }} | No |
| Third layer nesting | {{- with {{ secret &quot;{{inputs.parameters.message}}&quot; -}} }}<br>{{ .Data.data.gitcreds }}<br>{{- end }} | Yes |
| Third layer nesting with whitespace | {{- with {{ secret &quot;{{ inputs.parameters.message }}&quot; -}} }}<br>{{ .Data.data.gitcreds }}<br>{{- end }} | No |
| Extra bracket set | {{- with secret &quot;{{inputs.parameters.message}}&quot; -}} }}<br>{{ .Data.data.gitcreds }}<br>{{- end }} | Yes |
| Extra bracket set with whitespace | {{- with secret &quot;{{ inputs.parameters.message }}&quot; -}} }}<br>{{ .Data.data.gitcreds }}<br>{{- end }} | No |
| Extra closed bracket set | {{- with {{ {{ }} secret &quot;{{inputs.parameters.message}}&quot; -}} }}<br>{{ .Data.data.gitcreds }}<br>{{- end }} | Yes |
| Extra closed bracket set with whitespace | {{- with {{ {{ }} secret &quot;{{ inputs.parameters.message }}&quot; -}} }}<br>{{ .Data.data.gitcreds }}<br>{{- end }} | Yes) |

Hey @sarabala1979 - I'd like to re-open this issue. I put together the above table using existing test cases in `./util/template` package and modified them to have whitespace. Lastly I recorded which cases passed and failed to interpolate

cc @RyanCopley, are these matching what you're seeing as well?

**Comment by RyanCopley** [comment]
Hey sorry, I have been on vacation without access to slack. One important thing to also validate is running Argo lint on those exact same use cases. If you do that, I believe the issue will be very apparent. I can give the reproducer a shot on Monday when I’m back in town

**Comment by agilgur5** [comment]
May have been fixed by #11781
