### ISSUE TITLE
CLI: compile for Macs backed by Apple Silicon processors.

### ISSUE THREAD

**Issue by debayande** [argoproj/argo-workflows#8969]
# Summary

The Argo Workflows CLI executable (`argo`) currently doesn't appear to be compiled for Macs backed by Apple Silicon processors. While https://github.com/argoproj/argo-workflows/issues/5745 claims to the contrary, here's the list of executables for the latest version of the CLI:

<img width="993" alt="image" src="https://user-images.githubusercontent.com/28745111/173814517-25965154-a2a6-4620-a73e-9ca2a6e6103e.png">

I'd like to request for a version compiled to the Darwin/ARM64 target.

Thanks.

# Use Cases

A version of the Argo Workflows CLI compiled for the Darwin/ARM64 target would be of great help to operators like me who have Macs backed by Apple Silicon processors as their primary development environment.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
It will be available in 3.4 release. You should also be able to use the amd64 binary as well.
