### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by dalongfan** [argoproj/argo-workflows#8970]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have previous experience in Kubernetes, Java, Promethus, ArgoCD, Docker.**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #8528**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: slack/issue comments/zoom sync/async is good. timezone: UTC 5：30am - 11:15 am

**Comment by terrytangyuan** [comment]
The issue is resolved so closing this.
