### ISSUE TITLE
Tree UI icons not working in Ubuntu 20.04 

### ISSUE THREAD

**Issue by rpalloni** [argoproj/argo-workflows#8984]
As you see in the image, icons are not working in ubuntu 20.04
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.23.3

![image](https://user-images.githubusercontent.com/17080117/174111263-09ff0548-d485-400d-ad0f-924baeda9351.png)

**Comment by rpalloni** [comment]
@dpadhiar Firefox on Ubuntu 20.04

**Comment by alexec** [comment]
Fixed in v3.4
