### ISSUE TITLE
Log in JSON when monitoring a child workflow

### ISSUE THREAD

**Issue by alexrosenfeld10** [argoproj/argo-workflows#8986]
# Summary

I use the "workflow of workflows" pattern, basically this: https://argoproj.github.io/argo-workflows/workflow-of-workflows/ . In doing so, when the parent workflow runs, it polls the status of the child workflow to see if it's running or if terminated successfully or not. When it does that, it logs like this:

```text 
17:45:29.261 main time="2022-06-16T17:45:29.261Z" level=info msg="failure condition '{status.phase in [Error Failed]}' evaluated false"
17:45:29.261 main time="2022-06-16T17:45:29.261Z" level=info msg="success condition '{status.phase == [Succeeded]}' evaluated false"
17:45:29.261 main time="2022-06-16T17:45:29.261Z" level=info msg="0/1 success conditions matched"
17:45:29.261 main time="2022-06-16T17:45:29.261Z" level=info msg="Waiting for resource workflow.argoproj.io/dev-workflow-z8tr4 in namespace default resulted in retryable error: Neither success condition nor the failure condition has been matched. Retrying..."
17:45:34.260 main time="2022-06-16T17:45:34.260Z" level=info msg="Get workflows 200"
17:45:34.261 main time="2022-06-16T17:45:34.261Z" level=info msg="failure condition '{status.phase in [Error Failed]}' evaluated false"
17:45:34.261 main time="2022-06-16T17:45:34.261Z" level=info msg="success condition '{status.phase == [Succeeded]}' evaluated false"
17:45:34.261 main time="2022-06-16T17:45:34.261Z" level=info msg="0/1 success conditions matched"
17:45:34.261 main time="2022-06-16T17:45:34.261Z" level=info msg="Waiting for resource workflow.argoproj.io/dev-workflow-z8tr4 in namespace default resulted in retryable error: Neither success condition nor the failure condition has been matched. Retrying..."
17:45:39.270 main time="2022-06-16T17:45:39.270Z" level=info msg="Get workflows 200"
17:45:39.270 main time="2022-06-16T17:45:39.270Z" level=info msg="failure condition '{status.phase in [Error Failed]}' evaluated false"
17:45:39.270 main time="2022-06-16T17:45:39.270Z" level=info msg="success condition '{status.phase == [Succeeded]}' evaluated false"
17:45:39.270 main time="2022-06-16T17:45:39.270Z" level=info msg="0/1 success conditions matched"
```

I forward the logs from standard out to my log indexer of choice, which expects logs to be json-formatted (which most log ingestion services expect). However, I'm unable to find a way to change these "child resource creation" type logs to be json formatted. I'd love to have control over that because I want to create alerts and monitoring using the `level` property, for example.

# Use Cases

When would you use this?

When logging to a log provider, so almost always.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexrosenfeld10** [comment]
Can any maintainers of argo comment on this? It's pretty impactful for my alerting and monitoring for these workflows.

**Comment by sarabala1979** [comment]
@alexrosenfeld10 Do you like to contribute to this feature.
you can set the log formatted during the startup 
```go
  // Log as JSON instead of the default ASCII format.
  log.SetFormatter(&log.JSONFormatter{})
```

**Comment by alexrosenfeld10** [comment]
@sarabala1979 sure, I'm happy to open a PR.

Are you suggesting we simply hard code it to be logged as JSON? I'd imagine we want it configureable to the user. Can you point me to how I might do that?
