### ISSUE TITLE
keycloak's logout endpoint support

### ISSUE THREAD

**Issue by gwqu** [argoproj/argo-workflows#8994]
Similar to this https://github.com/argoproj/argo-cd/issues/3792

The keycloak is used together for argo workflow sso support.

After user logout the UI page, and then click login, the UI will skip login process and directly turn to main page without login requirement.

Is there a way to configure to also call keycloak's logout endpoint on clicking the logout button in argo workflow?

**Comment by vavdoshka** [comment]
+1 
also relevant when use AWS Cognito with built-in user pool

**Comment by doru-b** [comment]
Any updates on supporting this?

**Comment by agilgur5** [comment]
Superseded by #12389 , as that has more details and activity on it
