### ISSUE TITLE
Remove argo-dataflow pipelines component from the UI

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#8998]
# Summary

What change needs making?

People ask a lot about what this is and why it always errors out on this page. Given that argo-dataflow is still in argoproj-labs and under major refactoring/updates (possibly no longer part of Argo?), we should consider removing it from the UI.

WDYT? @alexec 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by alexec** [comment]
Yes. I think this is a dupe?

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/issues/7088 is a more general request. I can take this specific one though.

**Comment by alexec** [comment]
Not a dupe. I think most of the original work would have been done in a57b3ad9e. Try reverting that. You'll find a lot of conflicts, prefer what is on `master`. The search for `dataflow`, `Dataflow`, `pipeline` to see what was missed.

**Comment by louisnow** [comment]
@alexec @terrytangyuan
We currently use argo dataflow pipelines and rely on it being present and usable within argo.
Does this change mean we can't use argo dataflow pipelines with Argo 3.4+ ?

**Comment by terrytangyuan** [comment]
Yes you'll have to use it separately.
