### ISSUE TITLE
Documentation for the Python SDK

### ISSUE THREAD

**Issue by samunaai** [argoproj/argo-workflows#9016]
### Summary

👋🏾👋🏾 Hello! We are working on a serious project with Argo Python SDK and hoped to inquire about the documentation to better understanding how we can correctly use the API.

### Use Cases

For now, it appears that most of the documentation for the Argo Python SDK centers on the hello world example [[in the README](https://github.com/argoproj/argo-workflows/tree/master/sdks/python)]. 

However, we are also looking for if there are any additional documentation we can use for this. We are specifically interested in how to use a mounted volume, how to pass artifacts, and, **most importantly**, how to trigger memoization using the Python SDK. 

As per the screenshot below, we are asked to visit [[this link](https://github.com/argoproj/argo-workflows/tree/master/sdks/python/tests)] for additional examples. However, the link currently contains a unit test corresponding to the "hello world" example which is present in the read me. 

We also had a look at the [[API reference](https://github.com/argoproj/argo-workflows/tree/master/sdks/python/client/docs)], but it mostly contains details of how to use the various classes which have been implemented using the API.

Would the argo workflows team kindly have any examples that may have been used in unit testing for some other parts of API reference? Or just any documentation links that may be on another website, which would be helpful for us?

Warm regards,

<img width="400" alt="stack" src="https://user-images.githubusercontent.com/22077758/174754453-02508ed6-ea14-4b33-b6dd-71105667641f.png"> 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Yes I agree that we lack of examples currently. Feel free to help convert existing YAML examples to Python.

**Comment by munachisonwadike** [comment]
Thank you very much @terrytangyuan . If I may ask, is there an easy way to know how to convert the YAML to Python? Right now I am not perfectly sure how to correctly use the Python Classes which have been provided. Do you have any recommendations as I work this out?🙏🏿🙏🏿

**Comment by caelan-io** [comment]
Sidenote: There are a couple other Python SDK options that may have more documentation/ active users & maintainers for your needs:

1. [Hera](https://github.com/argoproj-labs/hera-workflows)
2. [Couler](https://github.com/couler-proj/couler)

**Comment by flaviuvadan** [comment]
@munachisonwadike Hera v5 offers a fully featured Argo Workflows + Events SDK now!

**Comment by tooptoop4** [comment]
maybe this should be deprecated

**Comment by agilgur5** [comment]
Superseded by #13719, suggesting Hera (and Couler) as [per above](https://github.com/argoproj/argo-workflows/issues/9016#issuecomment-1163650050).

Hera is also in progress to being the "official" Python SDK per https://github.com/argoproj/argoproj/issues/286
