### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by christianh814** [argoproj/argo-workflows#9021]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **Kubernetes, Argo CD, Go**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #8685**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: async (US Pacific)

**Comment by terrytangyuan** [comment]
Welcome! Someone else also expressed interest in working on that issue. Is there any other issue you'd like to work on? 

@tczhao Would you be interested in mentoring this?

**Comment by tczhao** [comment]
I'd love to.
Hi @christianh814, let us know if there's any other issue you'd like to work on
I would be more responsive on [slack](https://argoproj.github.io/community/join-slack/)
