### ISSUE TITLE
build timeout

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#9024]
The `functional` test suite is hitting is 20m limit. 20m is a long time for a test suite to run because it means that the engineer does not have fast enough feedback. IMHO less than 10m is a good target time.

 This usually happens when:

1. A slow test has been introduced. 
2. A build step has become slow due to problems with cache.
3. Incremental new tests push the time limit.

If it is (2), then all builds become slower. The fastest build takes about 4m20. I think that's pretty fast so it is probably not (2).

Therefore, I think it is probably (1). 

Actions:

* Look at the build and see if anything is slow (look for "slow" in the logs). Anything systemic?
* Are there just too many tests and maybe we should break some out into a new suite?

**Comment by juliev0** [comment]
Added this one to address intermittent failures as well: https://github.com/argoproj/argo-workflows/issues/9027
