### ISSUE TITLE
UI/API: show all namespaces possibilities 

### ISSUE THREAD

**Issue by bengoldenberg** [argoproj/argo-workflows#9140]
we would like to have the option to see all the namespaces we have in our cluster, in the Namespace section inside the ui as a dropdown list or something like this.
today we have many namespaces and once we have added more namespaces, we cant manage them manually.
![Screen Shot 2022-07-12 at 14 06 17](https://user-images.githubusercontent.com/71871067/178476348-33f9a875-cf00-4938-8900-06a0bed9dc1d.png)

**Comment by amitde69** [comment]
This is a critical feature in order to provide argo workflows as a tool to the organization.

**Comment by OneCricketeer** [comment]
Or workaround has been to create an external tool to provision namespaces and app git repos (e.g. Backstage software templates) with markdown links in the README that link direct to the workflow UI with `/<namespace>` where that repo would be built

**Comment by angapov** [comment]
namespace dropdown would be awesome

**Comment by fingeromer** [comment]
Hi, is this feature in your roadmap?

**Comment by agilgur5** [comment]
The main issue with this is that this requires a namespace query, which the Server and users do not normally have permissions to do. The alternative would be to pull out the namespace from every Workflow a user has permission to see, but there's performance ramifications with that as well

**Comment by agilgur5** [comment]
Turns out this is effectively a duplicate of #7405, which mentions needing a new `ListNamespaces` query and RBAC as well
