### ISSUE TITLE
Intermittent CI failures in Unit Tests

### ISSUE THREAD

**Issue by juliev0** [argoproj/argo-workflows#9146]
My PR doesn't make any code changes, yet I just had two different unit test failures that passed later after an "empty commit".

Test name: TestRetriesVariableInPodSpecPatch
File name: workflow/controller/operator_test.go
Line: 1196
Link: https://github.com/argoproj/argo-workflows/runs/7333472812?check_suite_focus=true

Test name: TestFormulateRetryWorkflow/Nested_DAG
File name: workflow/util/util_test.go
Line: 910
Link: https://github.com/argoproj/argo-workflows/runs/7332453716?check_suite_focus=true

Update 7/15/22: @terrytangyuan has now fixed the second one

Test name: TestEmissary/Stdout and TestEmissary/Comined
File name: emissary_test.go
Lines: 45,52
Link: https://github.com/argoproj/argo-workflows/runs/7643460317?check_suite_focus=true 

Test name: TestGlobalVarsOnExit
File name: operator_test.go
Line: 5609
Link: https://github.com/argoproj/argo-workflows/runs/7656323758?check_suite_focus=true

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by juliev0** [comment]
note there's a separate issue related to intermittent e2e test failures in CI [here](https://github.com/argoproj/argo-workflows/issues/9027)

**Comment by juliev0** [comment]
@terrytangyuan I'm not sure why I saw these two intermittent unit test failures yesterday (and now they're working), but interestingly the second one above is related to a new test you added. Could you take a look and see if you have any idea why it might have failed? Thank you!

**Comment by terrytangyuan** [comment]
I'll see if I can reproduce locally.

**Comment by juliev0** [comment]
> I'll see if I can reproduce locally.

Thank you!

**Comment by terrytangyuan** [comment]
@juliev0 That test case should be fixed in https://github.com/argoproj/argo-workflows/pull/9156.

**Comment by juliev0** [comment]
> @juliev0 That test case should be fixed in #9156.

Thank you so much for doing that right away!!

**Comment by juliev0** [comment]
keeping this alive...

**Comment by binkoni** [comment]
I encountered a similar issue today
Here is the log
https://github.com/argoproj/argo-workflows/actions/runs/5653773150/job/15315538326#step:4:98
