### ISSUE TITLE
workflow-controller CrashLoopBackOff 

### ISSUE THREAD

**Issue by wekinu** [argoproj/argo-workflows#9147]
│ time="2022-07-14T07:55:48.221Z" level=info msg="Starting Workflow Controller" defaultRequeueTime=10s version=untagged                                                                               │
│ time="2022-07-14T07:55:48.221Z" level=info msg="Current Worker Numbers" podCleanup=4 workflow=32 workflowTtl=4                                                                                      │
│ time="2022-07-14T07:55:48.221Z" level=info msg="Watching task results" labelSelector="!workflows.argoproj.io/controller-instanceid,workflows.argoproj.io/workflow"                                  │
│ time="2022-07-14T07:55:48.221Z" level=info msg=Plugins executorPlugins=false                                                                                                                        │
│ time="2022-07-14T07:55:48.221Z" level=info msg="List workflows 404"                                                                                                                                 │
│ time="2022-07-14T07:55:48.221Z" level=fatal msg="the server could not find the requested resource (get workflows.argoproj.io)" 

I don't know if it's the same question
time="2022-07-14T07:23:58.491Z" level=info msg="not enabling pprof debug endpoints"                                                                                                                     │
│ time="2022-07-14T07:23:58.491Z" level=info msg="config map" name=workflow-controller-configmap                                                                                                          │
│ time="2022-07-14T07:23:58.506Z" level=info msg="Get configmaps 403"                                                                                                                                     │
│ time="2022-07-14T07:23:58.506Z" level=fatal msg="Failed to register watch for controller config map: configmaps \"workflow-controller-configmap\" is forbidden: User \"system:serviceaccount:argo:argo\ │

Plz Tell me the solution.

**Comment by alexec** [comment]
This is permission issue. Please check to make sure you have `get configmaps` permission for your service account.
