### ISSUE TITLE
Workflow templates should be more easily discoverable/organized

### ISSUE THREAD

**Issue by balint-bg** [argoproj/argo-workflows#9171]
# Summary

My team uses a lot of WorkflowTemplates to create and run Workflows. These WFTs are scattered around a few environments (test, prod, etc), operation types (system-level-operations, utility workflows, custom jobs, etc etc.) and categories (soft- or hard- operations for startup or shutdown).
It'd be great if we didn't have to name the WFTs cleverly, to make sure related items show up next to each other in the UI.
Either some labeling system "this workflow has `system_level_operation`, `production` and `soft-stop` labels on it), or even a simple directory structure (this top level dir is for production WFTs so I expand this on the UI and know that I'll only see WFTs that touch the prod cluster)

# Use Cases

When would you use this?
Every time I need to do anything on Argo, every day, multiple times, especially during development of new systems.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
> Either some labeling system "this workflow has `system_level_operation`, `production` and `soft-stop` labels on it

Workflow Templates have had a label filter since #6955, which was released in 3.3.

So I believe this is already doable as such.

> or even a simple directory structure 

labels are a native k8s concept, so I think labels make more sense than a directory structure (and are straightforward to implement in k8s, as labels can be filtered on in the k8s API).
