### ISSUE TITLE
CLI should warn when CLI version is outdated

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-workflows#9212]
# Summary

In  #9209, the user was using a version of the Argo CLI that was 2 minor versions behind the operator running on the cluster. It would be a nice feature if the Argo CLI could throw a warning if the CLI version is older than version running on the cluster and it would be nice if the Argo CLI could tell the user that a new version is available. 

# Use Cases

* Use case 1: As a cluster administrator, I want users of Argo to receive a warning when the version of Argo CLI is older than the version running in the cluster
* Use case 2: As an Argo maintainer, I want users aware they are using older versions of Argo CLI so that they can choose to update the CLI

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
They may also be using a pretty new version of CLI while running older versions of the controller. We should just check whether the versions match and if not, print out a warning.

Would you like to contribute a PR for this?

**Comment by Bhavya-official** [comment]
I would like to contribute a PR for this. Would you like to guide me.

> They may also be using a pretty new version of CLI while running older versions of the controller. We should just check whether the versions match and if not, print out a warning.
> 
> Would you like to contribute a PR for this?

**Comment by terrytangyuan** [comment]
> I would like to contribute a PR for this. Would you like to guide me.
> 
> > They may also be using a pretty new version of CLI while running older versions of the controller. We should just check whether the versions match and if not, print out a warning.
> > Would you like to contribute a PR for this?

Please file a mentoring request. It would be good to know your background and see if you have the right prerequisites: https://github.com/argoproj/argo-workflows/blob/master/docs/mentoring.md

**Comment by fhochleitner** [comment]
@terrytangyuan I have a version check and warning print working locally. I'll be doing a little cleanup and try to figure out where to best put the additional code for it to be a clean solution and create a PR on the weekend or the beginning of next week.

**Comment by terrytangyuan** [comment]
Sounds good
