### ISSUE TITLE
request mentorship to fix a small bug/issue

### ISSUE THREAD

**Issue by corneredrat** [argoproj/argo-workflows#9225]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have previous experience in Golang, Kubernetes ; but not react.**

**Is there any particular issue you'd like to work on?**

Answer: **I would like to work with issue #9224**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: (async) (timezone/ IST)

**Comment by terrytangyuan** [comment]
@sarabala1979 Would you like to mentor this given that you already commented in the mentioned issue?
