### ISSUE TITLE
Wrong pod name is visualised in the workflow 

### ISSUE THREAD

**Issue by IoanaIvanova** [argoproj/argo-workflows#9227]
## Summary

What happened/what you expected to happen?

I started a workflow in my local k8s cluster with the latest version of argo-server and I observed that the name of the pod mentioned in the workflow step is wrong it is not actually the name of the pod which is started which includes the name of the step in the middle.
I expected that executing argo get <name-of workflow> will show me the correct pod name.

Output from argo get `<name of workflow>` -n argo
<img width="1168" alt="Screenshot 2022-07-25 at 8 54 18" src="https://user-images.githubusercontent.com/20287101/180707693-a8136d2f-65f2-4ac1-a843-80cf713e9705.png">

Output from kubectl get pods -n argo | grep `<name of workflow>`
<img width="716" alt="Screenshot 2022-07-25 at 8 54 19" src="https://user-images.githubusercontent.com/20287101/180707726-c4b793bc-c363-4c7d-9561-a156f289b2fd.png">

What version are you running?

Latest.
I have installed argo using this set of commands before 3 days: 
```
kubectl create ns argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-minimal.yaml
```

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
@JPZ13 This seems related to pod name change. Would you like to take a look?

**Comment by JPZ13** [comment]
@terrytangyuan Yep! I'll take a look this afternoon Eastern Time. Thanks for the heads up

**Comment by JPZ13** [comment]
@IoanaIvanova Could you post the workflow that you ran or a reproducible example? I ran a fresh quick start install from the command you provided and submitted a couple workflows from the examples folder. Outputs are looking good on my end:
```
STEP                  TEMPLATE  PODNAME                            DURATION  MESSAGE
 ✔ dag-diamond-4cxgz  diamond
 ├─✔ A                echo      dag-diamond-4cxgz-echo-3871903043  12s
 ├─✔ B                echo      dag-diamond-4cxgz-echo-3888680662  16s
 ├─✔ C                echo      dag-diamond-4cxgz-echo-3905458281  16s
 └─✔ D                echo      dag-diamond-4cxgz-echo-3922235900  5s
```

Might be an edge or corner case I haven't seen yet. Thanks for reporting the issue!

**Comment by sarabala1979** [comment]
@IoanaIvanova Can you check your Argo Cli version?

**Comment by IoanaIvanova** [comment]
It is reproducible on my side with your simple workflow example with steps defined [here](https://github.com/argoproj/argo-workflows/blob/master/examples/steps.yaml).  

The `argo version` command return as follow 
```
argo: v3.2.4+8771ca2.dirty
  BuildDate: 2021-11-18T05:15:20Z
  GitCommit: 8771ca279c329753e420dbdd986a9c914876b151
  GitTreeState: dirty
  GitTag: v3.2.4
  GoVersion: go1.17.2
  Compiler: gc
  Platform: darwin/amd64
```

**Comment by JPZ13** [comment]
@IoanaIvanova Can I get you to update your Argo CLI version and try again? I'm on a later CLI version:
```
argo: v3.3.5+eefc60b.dirty
  BuildDate: 2022-05-04T05:14:44Z
  GitCommit: eefc60b155c4011a3706d2e3cba90f099ee93b39
  GitTreeState: dirty
  GitTag: v3.3.5
  GoVersion: go1.18.1
  Compiler: gc
  Platform: darwin/arm64
```

I ran the example you gave and got the following output:
```
Name:                steps-ddwfk
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Succeeded
Conditions:
 PodRunning          False
 Completed           True
Created:             Wed Aug 03 18:28:57 -0400 (18 seconds ago)
Started:             Wed Aug 03 18:28:57 -0400 (18 seconds ago)
Finished:            Wed Aug 03 18:29:15 -0400 (now)
Duration:            18 seconds
Progress:            3/3
ResourcesDuration:   19s*(1 cpu),10s*(100Mi memory)

STEP            TEMPLATE           PODNAME                          DURATION  MESSAGE
 ✔ steps-ddwfk  hello-hello-hello
 ├───✔ hello1   whalesay           steps-ddwfk-whalesay-1020413787  6s
 └─┬─✔ hello2a  whalesay           steps-ddwfk-whalesay-3775412509  8s
   └─✔ hello2b  whalesay           steps-ddwfk-whalesay-3725079652  6s
```

These pod names match what I'm seeing in K8s:
```
NAME                              READY   STATUS      RESTARTS   AGE
httpbin-6f9dc6d779-4jn2c          1/1     Running     0          6m25s
minio-76fd8cb46d-wd66h            1/1     Running     0          6m25s
steps-ddwfk-whalesay-1920012444   0/2     Completed   0          4m36s
steps-ddwfk-whalesay-1970345301   0/2     Completed   0          4m36s
steps-ddwfk-whalesay-3941472404   0/2     Completed   0          4m44s
```

Let me know if you're still running into this issue after upgrading the CLI

**Comment by IoanaIvanova** [comment]
Thanks it is working with version
``` 
argo: v3.3.8+621b0d1.dirty
  BuildDate: 2022-06-24T01:56:09Z
  GitCommit: 621b0d1a8e09634666ebe403ee7b8fc29db1dc4e
  GitTreeState: dirty
  GitTag: v3.3.8
  GoVersion: go1.18.3
  Compiler: gc
  Platform: darwin/amd64
```
Could you tell me also from which version or argo-server/argo go client is the pod name change introduced as we have some functionality which is related to the failed pod name and as I can see when the workflow fails there is no direct information in the workflow kind for the name of the failed pod which was the behaviour in the older version of argo server?
