### ISSUE TITLE
CLI: Support submission of json and STDIN

### ISSUE THREAD

**Issue by ethron123** [argoproj/argo-workflows#926]
FEATURE REQUEST

Would like the ability to submit workflows using json from the Argo cli.

**Comment by jessesuen** [comment]
I agree. Also, I think we should support submission of workflows from STDIN. Will take care of both use cases with this issue.

**Comment by philBrown** [comment]
Any chance [the docs](https://argo-workflows.readthedocs.io/en/latest/cli/argo_submit/) could be updated to show a `STDIN` example?

From looking at the source code it appears to be flagged by passing `-` in place of a file but it would be nice to confirm

**Comment by agilgur5** [comment]
PR welcome. Otherwise this is a 6 year old closed issue, so commenting on it (also known as necroing) is not particularly actionable.

**Comment by agilgur5** [comment]
> PR welcome.

For posterity, @philBrown added a `stdin` example in #12820
