### ISSUE TITLE
Unschedulable: 0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.

### ISSUE THREAD

**Issue by wekinu** [argoproj/argo-workflows#9270]
After the Ubuntu OS format and Installed kuberentes and Argo,
when i run the pvc-related template provided by Argo, A message is coming out.
message : Unschedulable: 0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.

I am attaching the log.

│ Events:                                                                                                                                                                                                 │
│   Type     Reason            Age   From               Message                                                                                                                                           │
│   ----     ------            ----  ----               -------                                                                                                                                           │
│   Warning  FailedScheduling  21m   default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.                                                                      │
│   Warning  FailedScheduling  20m   default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.

LOG

time="2022-08-02T02:05:43.612Z" level=info msg=healthz age=5m0s err="<nil>" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=argo
time="2022-08-02T02:05:44.577Z" level=info msg="Alloc=9707 TotalAlloc=53703 Sys=35921 NumGC=19 Goroutines=166"
time="2022-08-02T02:05:44.809Z" level=info msg="Performing periodic workflow GC"
time="2022-08-02T02:05:44.810Z" level=info msg="Deleting old offloads that are not live" len_wfs=0
time="2022-08-02T02:05:44.810Z" level=info msg="Workflow GC finished"
time="2022-08-02T02:05:47.214Z" level=info msg="Get leases 200"
time="2022-08-02T02:05:47.218Z" level=info msg="Update leases 200"
time="2022-08-02T02:05:47.603Z" level=info msg="Processing workflow" namespace=argo workflow=volumes-pvc-tflk4
time="2022-08-02T02:05:47.603Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=volumes-pvc-tflk4
time="2022-08-02T02:05:47.603Z" level=info msg="node changed" namespace=argo new.message="Unschedulable: 0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims." new.phase=Pending new.progress=0/1 nodeID=volumes-pvc-tflk4-339652589 old.message= old.phase=Pending old.progress=0/1 workflow=volumes-pvc-tflk4
time="2022-08-02T02:05:47.603Z" level=info msg="Workflow step group node volumes-pvc-tflk4-205260336 not yet completed" namespace=argo workflow=volumes-pvc-tflk4
time="2022-08-02T02:05:47.603Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=volumes-pvc-tflk4
time="2022-08-02T02:05:47.603Z" level=info msg=reconcileAgentPod namespace=argo workflow=volumes-pvc-tflk4
time="2022-08-02T02:05:47.603Z" level=info msg="Workflow to be dehydrated" Workflow Size=2257
time="2022-08-02T02:05:47.607Z" level=info msg="Update workflows 200"
time="2022-08-02T02:05:47.607Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=10835 workflow=volumes-pvc-tflk4
time="2022-08-02T02:05:52.222Z" level=info msg="Get leases 200"
time="2022-08-02T02:05:52.224Z" level=info msg="Update leases 200"
time="2022-08-02T02:05:57.233Z" level=info msg="Get leases 200"
time="2022-08-02T02:05:57.236Z" level=info msg="Update leases 200"
time="2022-08-02T02:06:02.240Z" level=info msg="Get leases 200"

**Comment by terrytangyuan** [comment]
Please fill out the issue template.

**Comment by wekinu** [comment]
> Please fill out the issue template.

https://github.com/argoproj/argo-workflows/blob/master/examples/volumes-pvc.yaml

In addition to this link, the volumeClaimTemplates related functions all output the same message

**Comment by DiegoFlop** [comment]
I use volumeClaimTemplates with AWS cloud and all works properly.

This is my workflow configuration:
```yaml
volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
```

**Comment by wekinu** [comment]
> I use volumeClaimTemplates with AWS cloud and all works properly.
> 
> This is my workflow configuration:
> 
> ```yaml
> volumeClaimTemplates:
>   - metadata:
>       name: workdir
>     spec:
>       accessModes: [ "ReadWriteOnce" ]
>       resources:
>         requests:
>           storage: 5Gi
> ```

Thank you for your answer.
I also work well on AWS EKS.
However, in the bare metal environment, it comes out like the above message.
Is there an impact with the Kubernetes platform?
