### ISSUE TITLE
Documentation for argo workflows

### ISSUE THREAD

**Issue by jomach** [argoproj/argo-workflows#9279]
# Summary

Hey, it would be great if we could add a field on the Argo workflow for a doc string. This way if you have multiple workflows on a big company you can describe it a little bit and place persons in charge or just describe what the flow does. This could be pick up by the UI then. 

# Use Cases

Always

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by DiegoFlop** [comment]
You can use some annotations metadata annotations.

In argohub uses a few annotations to describe the project: https://github.com/codefresh-io/argo-hub#WorkflowTemplate-manifest-conventions

**Comment by jomach** [comment]
Still the UI is not updated with it right ?

**Comment by agilgur5** [comment]
> Duplicate #2871

That's for step names, not Workflows names. This actually duplicated #6529, which has been implemented
