### ISSUE TITLE
Does P/R/C reporting on argo list -o wide still work?

### ISSUE THREAD

**Issue by withnale** [argoproj/argo-workflows#9281]
Whenever I try running any of our workflows and I used 

```
argo list -o wide  -A

NAMESPACE   NAME                                                         STATUS      AGE   DURATION   PRIORITY   P/R/C   PARAMETERS
dev         dev-abc-defghij-default-1659528000                           Running     4m    4m         0          0/0/0
dev         stable-another-job-def-g64cn                                 Succeeded   11d   7h         0          0/0/0
```

I've tried this with our job definitions and I've also tried this out of the box some of the workflows in `argo-workflows/examples` and I've yet to see a case where it works. 

## Summary

What happened/what you expected to happen?

The `P/R/C` column is populated based on the number of pending/running/completed steps of the workflow.

What version are you running?

We're running v3.2.9 but I've also tried it with v3.3.7

**Comment by alexec** [comment]
This happen because of this line of code:

https://github.com/argoproj/argo-workflows/blob/f27475feb850dc43e07c3c5215cc9638947f0859/cmd/argo/commands/list.go#L48

It should be easy to add an option for `wide`.

**Comment by aditya-shrivastava** [comment]
Hi @alexec, I am new to open source and would like to try and work on this issue. 
Can you assign it to me?

**Comment by aditya-shrivastava** [comment]
Update on the issue: I have been learning Go and Kubernetes and reviewing the documentation to better understand the project.

**Comment by aditya-shrivastava** [comment]
Hi @alexec, I have made the following changes: 
![bug-fIx](https://user-images.githubusercontent.com/39914834/196519205-b87effa7-a3cc-432b-bb9c-0468f2aa055d.png)

After this I ran the command `make cli` and was able to submit an example workflow to get the expected P/R/C results.
![submit-workflow](https://user-images.githubusercontent.com/39914834/196520058-655df862-813d-4026-b310-de3eaf755512.png)

![prc-working](https://user-images.githubusercontent.com/39914834/196520250-2fa4148b-121c-4ef8-b5dc-b5e04396b249.png)

Kindly let me know if this fixes the issue or if I need to make more changes.
Also, I would highly appreciate it if you could tell me what unit tests I should add for the above changes before making a pull request. :smiley:
