### ISSUE TITLE
Add "argo delete --force" to force deletion of a workflow which has a finalizer

### ISSUE THREAD

**Issue by juliev0** [argoproj/argo-workflows#9315]
Artifact GC creates a finalizer to prevent Workflows from being deleted until their artifacts have been deleted. But if the artifacts fail to get deleted, the finalizer will remain.

This CLI command would force delete a workflow which has a finalizer, removing the finalizer first. (And thus the ArtifactGCTask, which is owned by it, and the ArtifactGC pod owned by the ArtifactGCTask would all get deleted.)

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by juliev0** [comment]
@sarabala1979 Added this per your suggestion. Can you add it to "Artifacts" project?

**Comment by Piroddi** [comment]
Would it make sense to add this `--force` field to the UI as well ? Also would it make sense to only update the finalizer after the workflows creates the artifact? As currently if a workflow fails before an artifact exists, the finalizer is present thus  preventing the workflow from being deleted until the finalizer been removed.

**Comment by juliev0** [comment]
> Would it make sense to add this `--force` field to the UI as well ? 

You can add an enhancement Issue for that if you like. The UI would of course still need to offer the "non-force" option as well. 

> Also would it make sense to only update the finalizer after the workflows creates the artifact? As currently if a workflow fails before an artifact exists, the finalizer is present thus preventing the workflow from being deleted until the finalizer been removed.

Hmm, there might be a bug if that's happening. The way it should work is that if you set your artifact GC to "OnWorkflowCompletion" for example, then when the Workflow completes, only artifacts that actually exist should get deleted, and then once all of these artifacts have been deleted the finalizer gets removed. If you believe there's a bug, you can write up an issue and let me know. I'm curious whether an Artifact GC Pod was created and if there's an associated WorkflowArtifactGCTask (`kubectl get wfat`) which would contain in its Spec the set of artifacts that need to be deleted. (Those would ultimately come from the Workflow object's `status.nodes[x].outputs.artifacts`.)
