### ISSUE TITLE
Argo server shuts down and the UI doesn't connect

### ISSUE THREAD

**Issue by AbdAlRahman-Odeh-99** [argoproj/argo-workflows#9323]
Environment:
- Ubuntu 20.04
- Minikube: 1.26.1
- Kubernetes Version: 1.24.3
- Docker: 20.10.17
Issue:
- The argo server shuts down after the first request and doesn't connect to the UI.
Steps:
- Install minikube and kubectl
- Run minikube
- kubectl create ns argo
- kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml
- kubectl -n argo port-forward deployment/argo-server 2746:2746
Error:
Forwarding from 127.0.0.1:2746 -> 2746
Forwarding from [::1]:2746 -> 2746
Handling connection for 2746
E0809 14:52:26.276669  210191 portforward.go:406] an error occurred forwarding 2746 -> 2746: error forwarding port 2746 to pod f67b99d82c22e7ca265c55c1ccf2d8583215c4eb392bbaedbcf547aa459147e7, uid : exit status 1: 2022/08/09 11:52:26 socat[11159] E connect(5, AF=2 127.0.0.1:2746, 16): Connection refused
E0809 14:52:26.277235  210191 portforward.go:234] lost connection to pod
Handling connection for 2746
E0809 14:52:26.277652  210191 portforward.go:346] error creating error stream for port 2746 -> 2746: EOF
![Screenshot from 2022-08-09 14-52-48](https://user-images.githubusercontent.com/66207782/183641628-6b9d4b5b-288d-415a-aa83-23ebb1c63701.png)

**Comment by sarabala1979** [comment]
@AbdAlRahman-Odeh-99 can you provide more information on why the argo server pod is going down?

**Comment by AbdAlRahman-Odeh-99** [comment]
Here are the logs of the pods that have CrashLoopBackOff error:

Argo Server Logs:
time="2022-08-10T09:02:59.890Z" level=info msg="not enabling pprof debug endpoints"
time="2022-08-10T09:02:59.891Z" level=info authModes="[server client]" baseHRef=/ managedNamespace=argo namespace=argo secure=true ssoNamespace=argo
time="2022-08-10T09:02:59.891Z" level=info msg="Generating Self Signed TLS Certificates for Secure Mode"
time="2022-08-10T09:02:59.891Z" level=info msg="SSO disabled"
time="2022-08-10T09:02:59.921Z" level=info msg="Starting Argo Server" instanceID= version=untagged
time="2022-08-10T09:02:59.934Z" level=fatal msg="dial tcp 10.98.231.247:5432: connect: connection refused"

Postgres Logs:
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... UTC
creating configuration files ... ok
child process was terminated by signal 7: Bus error
initdb: removing contents of data directory "/var/lib/postgresql/data"

Workflow Container Logs:
time="2022-08-10T09:01:22Z" level=info msg="index config" indexWorkflowSemaphoreKeys=true
time="2022-08-10T09:01:22Z" level=info msg="cron config" cronSyncPeriod=10s
time="2022-08-10T09:01:22Z" level=info msg="Memoization caches will be garbage-collected if they have not been hit after" gcAfterNotHitDuration=30s
time="2022-08-10T09:01:22.561Z" level=info msg="not enabling pprof debug endpoints"
time="2022-08-10T09:01:22.778Z" level=info msg="Get configmaps 200"
time="2022-08-10T09:01:22.789Z" level=info msg="Configuration:\nartifactRepository:\n  s3:\n    accessKeySecret:\n      key: accesskey\n      name: my-minio-cred\n    bucket: my-bucket\n    endpoint: minio:9000\n    insecure: true\n    secretKeySecret:\n      key: secretkey\n      name: my-minio-cred\nexecutor:\n  name: \"\"\n  resources:\n    requests:\n      cpu: 10m\n      memory: 64Mi\nimages:\n  docker/whalesay:latest:\n    cmd:\n    - cowsay\ninitialDelay: 0s\nlinks:\n- name: Workflow Link\n  scope: workflow\n  url: http://logging-facility?namespace=${metadata.namespace}&workflowName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\n- name: Pod Link\n  scope: pod\n  url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\n- name: Pod Logs Link\n  scope: pod-logs\n  url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\n- name: Event Source Logs Link\n  scope: event-source-logs\n  url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\n- name: Sensor Logs Link\n  scope: sensor-logs\n  url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\nmetricsConfig:\n  enabled: true\n  path: /metrics\n  port: 9090\nnamespaceParallelism: 10\nnodeEvents: {}\npersistence:\n  archive: true\n  archiveTTL: 168h0m0s\n  connectionPool:\n    maxIdleConns: 100\n  nodeStatusOffLoad: true\n  postgresql:\n    database: postgres\n    host: postgres\n    passwordSecret:\n      key: password\n      name: argo-postgres-config\n    port: 5432\n    tableName: argo_workflows\n    userNameSecret:\n      key: username\n      name: argo-postgres-config\npodSpecLogStrategy: {}\nretentionPolicy:\n  completed: 10\n  errored: 3\n  failed: 3\nsso:\n  clientId:\n    key: \"\"\n  clientSecret:\n    key: \"\"\n  issuer: \"\"\n  redirectUrl: \"\"\n  sessionExpiry: 0s\ntelemetryConfig: {}\n"
time="2022-08-10T09:01:22.789Z" level=info msg="Persistence configuration enabled"
time="2022-08-10T09:01:23.171Z" level=info msg="Get secrets 200"
time="2022-08-10T09:01:23.175Z" level=info msg="Get secrets 200"
time="2022-08-10T09:01:23.179Z" level=fatal msg="Failed to update config: dial tcp 10.98.231.247:5432: connect: connection refused"

**Comment by juliev0** [comment]
Definitely seems specific to the Postgres Pod, since that's listening on port 5432 and the reason that Argo Server and Workflow Controller are going down.

I just tried "kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml" (but on k3d, not minikube) and everything came up fine. I guess we need to understand what would cause Postgres to get "child process was terminated by signal 7: Bus error".

**Comment by juliev0** [comment]
Here are some people who've encountered the same thing: https://github.com/docker-library/postgres/issues/451

Can any of this work for you?

**Comment by AbdAlRahman-Odeh-99** [comment]
I have tried the following:
- The suggested solutions, but none worked
- Use 14-alpine version and changing the port number but that didn't work
I have also installed the Postgres pod following this tutorial: https://itnext.io/basic-postgres-database-in-kubernetes-23c7834d91ef . So I was able to start the pod, but this still leaves the problem with the Argo script on https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml the postgres pod started by this script keeps failing.

**Comment by AbdAlRahman-Odeh-99** [comment]
I managed to run the Argo server by using MySQL as a database instead of Postgres through the following start-up config file https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start-mysql.yaml. But still don't know the issue with the postgres one and whether I will be able to use it in the future or not.

**Comment by juliev0** [comment]
I’m glad to hear. Thanks for trying that work around.

**Comment by AbdAlRahman-Odeh-99** [comment]
Sure @juliev0  you're welcome. Actually after I solved this issue I ran into another issue with running my workflow that is available at https://github.com/argoproj/argo-workflows/issues/9361. I would appreciate if you look into it.

**Comment by juliev0** [comment]
Unfortunately, I’m on vacation all this week but I see my colleague has replied.
