### ISSUE TITLE
Workflow Controller Crashing v3.3.8 

### ISSUE THREAD

**Issue by sandeepitachi** [argoproj/argo-workflows#9324]
* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

Workflow controller is crashing with large workloads in a workflow. We started seeing this behavior in the last 2 weeks
We have around 40k network devices and collect the status of the devices using the workflows. The corn wf runs by dividing them into batches of around 80-90. We have similar other cron wfs running. As soon as wfs runs the workflow controller crashes with the error  `Failed to update lock ` and `failed to renew lease argo/workflow-controller: timed out waiting for the condition` and restarts continuously

What version are you running?
`v3.3.8`

Executor - emissary

# Logs from the workflow controller:
```
E0808 20:46:20.179509       1 leaderelection.go:367] Failed to update lock: Put "https://x.x.x.x:443/apis/coordination.k8s.io/v1/namespaces/argo/leases/workflow-controller": context deadline exceeded
I0808 20:46:20.179617       1 leaderelection.go:283] failed to renew lease argo/workflow-controller: timed out waiting for the condition
time="2022-08-08T20:46:20.179Z" level=info msg="stopped leading" id=workflow-controller-57986d49bc-h2rp8
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
you can disable the leader election if you are not using HA mode.  you can set env var `LEADER_ELECTION_DISABLE= true`

**Comment by sandeepitachi** [comment]
Thanks, @sarabala1979 controller stopped crashing now
