### ISSUE TITLE
Aggregating the output artifacts of parallel steps (fan-in)

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-workflows#934]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What happened**:

Separating this issue from #861 to handle aggregation of output artifacts. Similar to output parameters which have been expanded using loops, we need some mechanism to aggregate artifacts from parallel steps. With parameters, the solution was to introduce a new variable, `steps.XXXX.outputs.parameters` as a json list. For artifacts we need something similar. The trick is how we would place aggregate artifacts into a subsequent pod.

**Comment by edlee2121** [comment]
When aggregating and importing the artifacts generated by steps in a loop, I think the most useful option may be to allow subsequent steps to reference a **composite** artifact that is a merge of the contents of all the output artifacts into a single composite artifact.

Each instance of the loop could use the iteration index or other parameter passed in to appropriately name the output file/directory so that the merge does not overwrite content. This gives the user control over how to name/structure the layout of the output artifact.

Example:
If the output artifact directory in each step is output-artifact-dir, each step would generate a file or artifact name something like output-artifact-dir/<input-param>-artifact.

The composite artifact could be referenced normally as
```steps.my-loop-step.outputs.artifacts.name1```
Where name1 is the name of the artifact generated by the output steps. This would create a composite artifact my merging all output artifacts with the name ‘name1’. Note that, one could create multiple output artifacts in a loop step using different names.

What do you think?

**Comment by edlee2121** [comment]
Even with an off-the-shelf image, I think the user could override the `command` parameter to customize the name of the output file/directory.

If desired, we could support a second form for accessing the composite output artifact. E.g. if the input artifact is specified as, for example, `steps.my-loop-step.output.artifacts.*` the unpacked input artifacts could be placed at `input-artifact-dir/{0,1,2,3,...}/`. That is, each input artifact is unpacked into a subdirectory corresponding to an index number.

One draw back with this approach is that it only works well with loops. I think the first approach is more general.

**Comment by mamoit** [comment]
This seems to be a fairly stale issue, but it would be extremely handy for easily parallelizable tasks such as scraping multiple sources and generating large datasets that need to be merged in the end and analysed as a whole.
Just spent the past couple of hours trying to achieve this :smile:

**Comment by jessesuen** [comment]
Since this bug was filed, we now support artifacts with `archive: none: {}`, and now there is a pattern developed where parallel steps can output to a common s3 "directory". The following step (which needs the aggregated outputs), will download the s3 "directory" as an artifact.

**Comment by fj-sanchez** [comment]
@jessesuen can you point me to that pattern where multiple steps can output to a common s3 directory?

**Comment by jessesuen** [comment]
Need to write a proper example, but the idea is that you would disable .tgz archiving on a file like so:
https://github.com/argoproj/argo/blob/master/examples/artifact-disable-archive.yaml#L38

And then the subsequent step would recursively download the s3 key as a "directory." The enhancement that was made in v2.2, is that if the S3 location appears to be a "directory" instead of a file, it performs a recursive download of all of the contents of that "directory." Directory is in quotes because S3 is really just a key/value store.

**Comment by fj-sanchez** [comment]
So, does your container job need to be aware of its "index" or is the template using it to save the artifacts with unique names (using the item index i.e.)?

**Comment by mostaphaRoudsari** [comment]
@jessesuen, did you ever get a chance to add an example which uses `archive: none: {}` to pass outputs to common s3 directory for parallel task?

**Comment by laubosslink** [comment]
@jessesuen extremely interesting as well to perform experiments

**Comment by Downchuck** [comment]
This seems potentially broken for GCS per https://github.com/argoproj/argo/issues/1351

**Comment by Downchuck** [comment]
@jessesuen: Is there a particular concern in trying to support tasks.X.outputs.artifacts.selector when using loops, and simply extracting all matches? It's up to the workflow designer to ensure the overlay is correct.

@edlee2121 @fj-sanchez I'm suggesting we skip any complexity around indexes and just use unique names.

For example, this is working just fine in a loop to get the artifact onto storage:
```
    outputs:
      artifacts:
      - name: split
        path: "/tmp/split-{{inputs.parameters.offset}}"
```

All I'd need to pull out of storage is to just loop through the list, much as parameter aggregation does, and unpack the archives into the target folder.

Unfortunately, due to the GCS folders bug, I can't use the folder clone technique to just download all of the {{workspace.name}} key. And parameter aggregation is a little funky, because I can't trivially aggregate the {{pod.name}} variables (I have to write them to a file, and use valueFrom).

**Comment by sebinsua** [comment]
Does anybody have a working example of how to do this?

If not, I'll work something out myself.

**Comment by TekTimmy** [comment]
> Does anybody have a working example of how to do this?
> 
> If not, I'll work something out myself.
> 
> **Edit 1**: One thing I tried was using `{inputs,outputs}.artifacts.s3` to access the same S3 bucket and key from different pods, however I would need them to use a key which is specific to the current `workspace.name`, and currently it doesn't seem that `{{workspace.name}}` is interpolated within `inputs.artifacts.s3.key`.
> 
> **Edit 2**: I got something to work! Here is my attempt: [**`sebinsua/k8s-argo-parallel-aggregate-workflow`**](https://github.com/sebinsua/k8s-argo-parallel-aggregate-workflow)

I have used that approach initially as well, **it works as long as all steps are running on the same Node or the volume runs in `ReadWriteMany` mode.**. Minikube provides volumes in mode "ReadWriteMany" but EKS (AWS Kubernetes) EBS volumes do not support to be mounted to several nodes at once.

**Comment by jd0x** [comment]
@sebinsua This example rocks, thanks for sharing!

I was able to get this running with ReadWriteMany volumes using nfs-server-provisioner on multiple cloud providers backed with volumes that are usually constrained to ReadWriteOnce. @TekTimmy if you are still blocked on this, I provided a link to the helm chart below.

https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner

**Comment by alexec** [comment]
Document the pattern. #2549

**Comment by foobarbecue** [comment]
I'm having a little trouble figuring out the state of this. Looks like there's a solution that works on a volume mount but not on an artifact store? And this is because argo can't specify absolute paths (yeah, I know, "they're keys not paths") if you're writing to an artifact store?

**Comment by foobarbecue** [comment]
Wow, I found a solution that works OK for me. Trick was to use parameter as part of the artifact key. I might post an example tomorrow.

**Comment by alexec** [comment]
> Phew, I found a solution that works OK for me. Trick was to use parameter as part of the artifact key. I might post an example tomorrow.

Yes please - would you like to update the example too?

**Comment by foobarbecue** [comment]
Here's an example of how I'm doing it. I could contribute as an example but it's more of a hack than a pattern at this point I think! I'll see if I can make it a little less hacky and submit as an example with caveat. https://gist.github.com/foobarbecue/bb6c5a1a5c67ad17b9c6cbb7fd32f5ee

**Comment by Arkanayan** [comment]
> Here's an example of how I'm doing it. I could contribute as an example but it's more of a hack than a pattern at this point I think! I'll see if I can make it a little less hacky and submit as an example with caveat. https://gist.github.com/foobarbecue/bb6c5a1a5c67ad17b9c6cbb7fd32f5ee

@foobarbecue Your solution seems to achieve it. But it seems incredibly hacky. Maintaining that would be a nightmare. 
We have a use case where actually need to loop over artifacts. And I was thinking along the same lines. But I think it should be implemented at argo feature level, like with a `withArtifacts` parameter.

I was thinking of contributing to the project. But being mainly a python developer and never having used golang. The code is going over my head. @alexec Any pointers on that? Maybe an architecture document?

**Comment by foobarbecue** [comment]
I am in the same boat, mostly python and javascript and haven't used go.

I think the critical missing feature here is the ability to specify output artifact keys in the workflow without having to do backflips (changing the configmap and using the "hard-wired" artifact spec style). Those would eliminate the hackyness from my example. I was hoping there was a way to use the default artifact store and specify keys, but there doesn't seem to be.

**Comment by alexec** [comment]
Hmm. Should not have been closed.

**Comment by alexec** [comment]
I've created an example of a map-reduce job in Argo Workflows that aggregates outputs. Please take a look

https://github.com/argoproj/argo/pull/4175

**Comment by Ark-kun** [comment]
> If desired, we could support a second form for accessing the composite output artifact. E.g. if the input artifact is specified as, for example, `steps.my-loop-step.output.artifacts.*` the unpacked input artifacts could be placed at `input-artifact-dir/{0,1,2,3,...}/`. That is, each input artifact is unpacked into a subdirectory corresponding to an index number.

I like this form, but I think there needs to be a way to access artifacts per-output. For example `tasks.my-loop.output.artifacts.something`. Then the artifacts are downloaded into `input-artifact-dir/{0,1,2,3,...}/` sudirectories as you've proposed.

**Comment by Ark-kun** [comment]
> I've created an example of a map-reduce job in Argo Workflows that aggregates outputs. Please take a look
> #4175

Interesting example.
The problem I see is that it requires explicit manipulation of the artifact location, which makes the workflows less reusable.

**Comment by Ark-kun** [comment]
The map-reduce example gave me an idea how Argo could solve the artifact aggregation with minimal effort.
But then I understood that this is a bad idea and won't support DAGs or artifacts with custom URIs.

`<bad_idea>`
Suppose there is a normal task. It outputs all its artifacts to `<run-id>/<task-id>/<output-name>`.
Now we make this task a loop by adding `withItems`, `withParam` or `withSequence`.
What if the resulting sub-nodes would output their artifacts to `<run-id>/<task-id>/<output-name>/<loop-idx>`?
In this case the loop node's output artifact URI is still `<run-id>/<task-id>/<output-name>` and when downloaded by downstream component it will automatically contain artifacts from all lop iterations.
`</bad_idea>`

**Comment by Ark-kun** [comment]
Perhaps we could implement artifact aggregation the same way as for parameters - the loop node should collect per-output artifact lists and the `init` executor should be able to download multiple artifacts under a single path.

```
name: aggregate
inputs:
  artifacts:
  - name: in-art-1
    path: /tmp/inputs/in-art-1/  #Artifacts end up in /tmp/inputs/in-art-1/{1,2,3,4}
    uris:
    - s3: ...
    - s3: ...
```

```
name: dag-aggregate-task
template: aggregate
arguments:
- name: in-art-1
   from: {{tasks.loop-task.outputs.artifacts.out1}}
```

**Comment by Downchuck** [comment]
It's simply that map reduce patterns need some enthusiastic support.

I found the easiest way to explore the space was to actually mock out the yaml flows as objects. In one experiment, I just used javascript with a dag library.

Looking forward to seeing what the community comes up with (my experiment was nuked by the client); I'm just saying: yes, map reduce needs to happen, but you can experiment with it in just thinking about an in memory dag.

**Comment by alexec** [comment]
I think this could be fixed by using key-only artifacts. See #4341

**Comment by bklaubos** [comment]
@jessesuen Can we get on slack/zoom to talk to about this?
