### ISSUE TITLE
Implement Artifact Garbage Collection for Azure

### ISSUE THREAD

**Issue by juliev0** [argoproj/argo-workflows#9344]
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by brianloss** [comment]
Does the implementation of this boil down to implementing the Delete method for the artifact driver? If so, then this is already implemented for Azure: https://github.com/argoproj/argo-workflows/blob/master/workflow/artifacts/azure/azure.go#L311

I have done some sniff testing with https://github.com/argoproj/argo-workflows/blob/master/examples/artifact-gc-workflow.yaml and it appears to be doing the right thing.

**Comment by juliev0** [comment]
Cool. I should’ve looked to see if any were implemented rather than relying on heresay. Thanks for saying. We can close then.
