### ISSUE TITLE
Implement Artifact Garbage Collection for OSS Artifacts

### ISSUE THREAD

**Issue by juliev0** [argoproj/argo-workflows#9349]
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by shuangkun** [comment]
This is already supported, right?

**Comment by AlbeeSo** [comment]
> This is already supported, right?

https://github.com/argoproj/argo-workflows/blob/3b4551b6f33bd22519cc98e2d8c157a92720b5d7/workflow/artifacts/oss/oss.go#L225
Not yet, I will submit a PR to implement it.:) @shuangkun
