### ISSUE TITLE
"Please reduce your request rate" when using withSequence.count: 600 * 5GB saved to S3

### ISSUE THREAD

**Issue by mm-fsai** [argoproj/argo-workflows#9360]
I am using v3.3.8

I am using withSequence.count: 600. Each pod does some processing and then tries to save about 5GB to S3 (at roughly the same time).

About 30.5% of the 600 pods fail to complete. The wait container responds with the error message level=fatal msg="timed out waiting for the condition: failed to put directory: Please reduce your request rate."

The wait container does not seem to retry and instead just hangs indefinitely.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@mm-fsai Can you provide the wait container logs?

**Comment by alexec** [comment]
This means that the wait container has tried multiple times to put your artifact and subsequently given up. Maybe use the paralellism feature?
