### ISSUE TITLE
Blank workflow info page once submitted through the UI

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#9371]
## Summary

What happened/what you expected to happen?

The workflow information page is bank after I clicked submit through the UI.

What version are you running?

3.4-rc1

## Diagnostics

See the gif below.
![Screen Recording 2022-08-15 at 3 33 41 PM](https://user-images.githubusercontent.com/4269898/184933411-34780768-bb8f-4d93-bcf2-f3b4fc0e5404.gif)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Console logs:
![image](https://user-images.githubusercontent.com/4269898/184933776-7444c5ec-00ca-4913-865f-2cdb92ad6e5a.png)
@juliev0 Seems like related to the artifactGC change.

**Comment by juliev0** [comment]
@dpadhiar Since I’m out can you take a look at this if you have bandwidth?

**Comment by dpadhiar** [comment]
@juliev0 Yes.

**Comment by terrytangyuan** [comment]
I am fixing this in https://github.com/argoproj/argo-workflows/pull/9377.

**Comment by jiantang99** [comment]
Hi, @terrytangyuan I am experiencing this same issue now, can you help me check what went wrong for me?
These are some of the logs from the argo-server pod :
![Screenshot 2024-04-08 at 11 09 41 AM](https://github.com/argoproj/argo-workflows/assets/85147635/687b1662-92ba-4e24-b244-9fd4c1936a76)
The UI error is the same as the one reported in this issue.
