### ISSUE TITLE
Increase CI test timeout

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#9379]
Test are timing out after 7m. Increase to 10m.

**Comment by alexec** [comment]
Wrong solution. Problem appears to be that caches have become large.

**Comment by alexec** [comment]
https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions


env GH_REPO=argoproj/argo-workflows gh api /repos/$GH_REPO/actions/caches --jq '.actions_caches[].id' | while read ID; do gh api --method DELETE /repos/$GH_REPO/actions/caches/$ID --silent ; done

**Comment by JessieTeng89** [comment]
@alexec Can I try to work on this issue if possible?
I am very appreciate it if you could provide more information to fix it

**Comment by alexec** [comment]
This issue does not need to be worked on. The actual problem was that the Github Actions cache got very big and took too long to upload/download. I deleted the caches using the command above.
