### ISSUE TITLE
argo依赖问题

### ISSUE THREAD

**Issue by chenjunyu0103** [argoproj/argo-workflows#9384]
你好，从官方给出的goland的argo的客户端，这个依赖k8s的open-api的ref地址还是老地址，这个问题算是一个bug吗？ 
![image](https://user-images.githubusercontent.com/72799872/185017789-dad5cf31-08d7-45bc-b50f-a887e0832949.png)
![image](https://user-images.githubusercontent.com/72799872/185017924-ca353fcb-9fcd-47c4-b1fe-ff81e7fabe38.png)

**Comment by thinkhoon** [comment]
大哥，argo又不是中国人维护的，你发中文有咩用

**Comment by terrytangyuan** [comment]
Please use English and fill in the issue template. Thanks.
