### ISSUE TITLE
v3.4: clicking on input arifact in UI crashes UI

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#9391]
1. Run the `artifact-workflowtemplate.yaml`. 
2. Click on the "annual.csv" input artifacts. 
3.See `undefined is not an object (evaluating 'Y.find((function(e){return e.name===x.name})).artifactGC')` error.

Clicking "Reload the page" fixes the issue.

I think it must be this:

https://github.com/argoproj/argo-workflows/blob/b356cb503863da43c0cc5e1fe667ebf602cb5354/ui/src/app/workflows/components/workflow-details/artifact-panel.tsx#L60

Change to 

```typescript
const artifactGCStrategy = artifacts?.find(a => a.name === artifact.name)?.artifactGC?.strategy || spec.artifactGC?.strategy;
```

**Comment by terrytangyuan** [comment]
We had the same issue and went ahead and fixed (different from what you suggested) to make it to the next release candidate today. https://github.com/argoproj/argo-workflows/pull/9392
