### ISSUE TITLE
Diminish the use of quickstart manifests to improve first-time user experience

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#9398]
# Summary

The Argo Workflows quickstart manifests are referenced heavily within the Argo Workflows documentation. It is highly likely that the first experience of Argo Workflows to newcomers will be via these quickstart manifests. (Note, for the purpose of this document, “Quick Start” refers to anything in the argo/manifests directory on github.)

These manifests rely on referencing the `latest` image for various Workflows components. Examples:

https://github.com/workflow/argo/blob/master/manifests/base/workflow-controller/workflow-controller-deployment.yaml#L17

https://github.com/workflow/argo/blob/master/manifests/base/argo-server/argo-server-deployment.yaml#L17

The `latest` images are naturally bleeding-edge versions of Argo Workflows. At best, this produces unexpected results for new users, which gives a poor first impression. At worst, Argo Workflows simply doesn’t install properly, users get frustrated and move to an alternative tool.

A high number of slack queries have a root cause of the user using an unstable quickstart manifest and receiving an unexpected outcome.

I am proposing that the Getting Started documentation stops referencing the quick start manifests and instead references the official release manifests. This then smooths the upgrade flow from quick start > production.

I am NOT proposing to remove the quickstart manifests themselves, certainly as part of this enhancement. There may be people who historically rely on them, so we shouldn't just make them disappear.

I am happy to make this change myself.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by caelan-io** [comment]
I agree with this suggestion. If we can direct more users to the release manifests, they should have a smoother first-time experience based on a stable release.

Here are some recent specific examples of where the Quick Start manifests confused users and led them to post in Slack:
- https://cloud-native.slack.com/archives/C01QW9QSSSK/p1660203791944519
- https://cloud-native.slack.com/archives/C01QW9QSSSK/p1652937644933039
- https://cloud-native.slack.com/archives/C01QW9QSSSK/p1660152290188619
- https://cloud-native.slack.com/archives/C01QW9QSSSK/p1658392626200229
- https://cloud-native.slack.com/archives/C01QW9QSSSK/p1653066322698639
- https://cloud-native.slack.com/archives/C01QW9QSSSK/p1656362156477829 
- https://cloud-native.slack.com/archives/C01QW9QSSSK/p1652777948773689
- https://cloud-native.slack.com/archives/C01QW9QSSSK/p1652259965656789
