### ISSUE TITLE
containerRuntimeExecutor usage needs clarifying before 3.4 release

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#9432]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

[This page](https://argoproj.github.io/argo-workflows/workflow-executors/) of the documentation advises users to use the `containerRuntimeExecutor` value in the configmap.

This value has been removed in 3.4.

No other alternative is documented. The example configmap implies (but doesn't explictly say) that one can use an arg on the workflow controller, but this doesn't appear to be documented (and is also wrong, because the alternative executors have been removed)

What version are you running 3.4-rc2

## Diagnostics

```bash
level=fatal msg="Failed to register watch for controller config map: error unmarshaling JSON: while decoding JSON: json: unknown field \"containerRuntimeExecutor\""
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tim-sendible** [comment]
`containerRuntimeExecutors` has the exact same issue. No documentation explaining what I can do instead.

**Comment by terrytangyuan** [comment]
Thank you! Added in https://github.com/argoproj/argo-workflows/pull/9437.
