### ISSUE TITLE
Argo-workflows workflow-controller crashing after upgrading from 3.2.x to 3.3.x

### ISSUE THREAD

**Issue by cklucker-w** [argoproj/argo-workflows#9454]
We deploy our argo-workflows workflow-controller using the argoproj's helm chart onto a k8s/eks 1.22 cluster.  After upgrading our chart/app from `argo-workflows-0.9.4    v3.2.6` to `argo-workflows-0.16.9	v3.3.9` (and also tested the same unplanned behavior on `argo-workflows-0.16.7	v3.3.8`) we noticed that our workflow-controller seemed to crash every few minutes when actively processing one of our workflows.  The submitted workflows would still run to completion and complete successfully, however the workflow controller might crash 50x or more times in the process. This behavior is not seen after downgrading back to `argo-workflows-0.9.4    v3.2.6`.

Example workflow-controller logs right before crash:
```
time="2022-08-11T16:05:24.266Z" level=info msg="node changed" new.message= new.phase=Succeeded new.progress=0/1 nodeID=<redacted name> old.message= old.phase=Pending old.progress=0/1
fatal error: concurrent map read and map write

goroutine 6976 [running]:
runtime.throw({0x1fbf96b, 0x1cbfc00})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc04e7658c8 sp=0xc04e765898 pc=0x436ed1
runtime.mapaccess1(0xc04b524300, 0xc01ae2d800, 0x1f892cc)
...
```

In searching issue logs, I've noticed that similar `fatal error: concurrent map read and map write` crash-logs has been resolved by a number of different bug fixes in the past, however I have not been able to find any similar reported issues relating to v3.3.x.

**Comment by terrytangyuan** [comment]
Could you try v3.4-rc2?
