### ISSUE TITLE
Replace the jsonpath library used with a library that is more fully featured

### ISSUE THREAD

**Issue by aaronmell** [argoproj/argo-workflows#9455]
# Summary
The current library is missing a bunch of features as compared to several other libraries. It also no longer seems to be actively maintained. 

https://cburgmer.github.io/json-path-comparison/

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by agilgur5** [comment]
This was fixed by https://github.com/argoproj/pkg/pull/486 / #11704 which updated to a newer and more comprehensive JSONPath library. That was released recently in 3.5.0-rc2
