### ISSUE TITLE
Argo - The server could not find the requested resource (get workflows.argoproj.io)

### ISSUE THREAD

**Issue by decipher27** [argoproj/argo-workflows#9461]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

Cluster Configuration:
Eks clusters having 4 spot nodes.

We noticed our workflows are failing due to this error - "Failed to wait for service account secret: timed out waiting for the condition". , this started happening after upgrading k3s to v1.24.3.

Here, we had to perform argoCD CLI version upgrade in order to fix the above [Upgraded it to 2.3.7] [Fix - https://github.com/argoproj/argo-cd/issues/9422#issuecomment-1128135869, PR FIX - https://github.com/argoproj/argo-cd/pull/9546]

Next issue started happeningg after upgrading argoCD CLI version to 2.3.7.
Related ArgoCD ticket - https://github.com/argoproj/argo-cd/issues/10422

The cluster got created successfully but we believe the CRD's did not get applied here. Please Note that  it was getting applied prior to upgrading ARGO CD CLI version..

When I do an "argo list" below is the log that I see. 

```
❯ argo list
FATA[2022-08-29T14:44:59.636Z] rpc error: code = NotFound desc = the server could not find the requested resource (get workflows.argoproj.io)
```

What version are you running?
Current argo CD CLI version: 2.3.7
k3s version: v1.24.3-k3s1
ARGO workflows CLI : v3.1.3
## Diagnostics

We have a sequential workflow that runs one after the other. Hope this much information is sufficient.

Cluster got created but there are no resources find under it. When I do an argo list, I do see this error:
```
❯ argo list
FATA[2022-08-29T14:44:59.636Z] rpc error: code = NotFound desc = the server could not find the requested resource (get workflows.argoproj.io)
```

# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@dpadhiar can you do the initial triage?

**Comment by dpadhiar** [comment]
This may be an error with the CRD installation, could you try reapplying these and reporting back if the error occurs?

**Comment by alexec** [comment]
This is likely a set-up issue. If you can show othewise, please re-open.

**Comment by decipher27** [comment]
Found that since we are using latest version of k3s i.e v1.24.3+k3s1, it requires latest CRD's updated with the latest apiVersion

**Comment by Talador12** [comment]
> Found the issue, since we are using latest version of k3s i.e v1.24.3+k3s1, it requires latest CRD's updated with the latest apiVersion.

What change in apiVersion/CRDs did you make? We are using the most recent CRDs on this github with the same error as you. I can see the `v1` CustomResourceDefinition  with an `argoproj.io/v1alpha1` apiVersion, but we are on the latest `v1.26.1-k3s1` k3s
