### ISSUE TITLE
Workflow / event pods block scale down

### ISSUE THREAD

**Issue by elizabethking2** [argoproj/argo-workflows#9481]
## Checklist

* [X] Double-checked my configuration.
* [x] Tested using the latest version.
* [X] Used the Emissary executor.

## Versions

- Argo workflows version: v3.3.6
- Argo events version: 1.12.0
- K8s GKE version: v1.21.1

## Summary

After a large event kicked off 100s of workflows several weeks ago, our prod cluster has not been able to scale back down. Both workflow and event pods block the cluster scale down due to `Pod is blocking scale down because it has local storage` and `Pod is blocking scale down because it's not backed by a controller` in GKE:
![Screenshot 2022-08-31 at 11 28 11](https://user-images.githubusercontent.com/66312232/187658154-ccb0a727-1550-454e-a4d3-7d3cd17fd207.png)

What is the best practice here? Both these warning suggest adding a `safe-to-evict` annotation - is this safe to add?

Worth noting that both CPU and memory utilisation are low:
![Screenshot 2022-08-31 at 11 32 15](https://user-images.githubusercontent.com/66312232/187659073-d6ee4e2a-7ef6-4109-92d1-67ab5462cac6.png)

Additionally, we've implemented pod disruption budgets to reduce the chance of voluntary disruption of workflow pods. In the meantime are investigating internally if this could be one factor blocking the scale down after a surge.

## Diagnostics

This can be reproduced by kicking off +100 workflows that sleep for 1000+ seconds.

We see ~13k logs / hour on local storage scale down issues:
![Screenshot 2022-08-31 at 11 23 45](https://user-images.githubusercontent.com/66312232/187662469-7fde5971-6d81-4273-a657-8e4e2a55b621.png)

And ~100 logs / hour on the no controller scale down issue:
![Screenshot 2022-08-31 at 11 58 41](https://user-images.githubusercontent.com/66312232/187663659-4b5fccc2-0c8d-4301-bd36-7fa4461a4dd2.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
It looks like more related to the GKE issue.

**Comment by alexec** [comment]
+1 to @sarabala1979. Does not seem like an Argo issue. Please re-open if you have more info.

**Comment by dis-sid** [comment]
Hello, no one answered his question though, GKE needs pods to be managed by something deployment, statefulset etc or else use the safe-to-evict annotation. Is this argo orchestrator pod safe to evict ?

**Comment by agilgur5** [comment]
> Is this argo "orchestrator" pod safe to evict ?

Yes, the Controller is designed to be resilient to restarts as it stores all state in its managed CRs. Intermediate state, such as Pod changes, may be missed during downtime however. See also the ["High Availability" documentation](https://argo-workflows.readthedocs.io/en/release-3.5/high-availability/)
