### ISSUE TITLE
archived-workflows API Endpoint Incorrect Return Type

### ISSUE THREAD

**Issue by rajaie-sg** [argoproj/argo-workflows#9482]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

In the Argo Workflows server `/apidocs` page, the documentation for the `GET /api/v1/archived-workflows` shows that a response type of `io.argoproj.workflow.v1alpha1.WorkflowList` is expected, similar to what the the `GET /api/v1/workflows/{namespace}` endpoint returns.

What actually happens when I curl the `archived-workflows` endpoint is that I receive a response that excludes many fields that I see in the regular `workflows` endpoint.

Response from `archived-workflows`

![image](https://user-images.githubusercontent.com/74200541/187721224-9a1a0aba-0638-4603-910f-7d53017bb0c5.png)

Response from `workflows` endpoint (just a part of it)

![image](https://user-images.githubusercontent.com/74200541/187721425-e969eca2-b567-45af-8235-168cd2de780a.png)

I can get the full archived workflow metadata through the `api/v1/archived-workflows/UID` endpoint, so it seems that the `archived-workflows` endpoint is not including all the fields it should for any reason (or, this is just an API documentation issue).

What version are you running?

3.3.9

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This is correct behavour. Only a subset of fields in returned because that is all that is stored. To get the detail, you must get the individual workflow.

**Comment by rajaie-sg** [comment]
Is this an API documentation error then? If this API endpoint has the same return type (`io.argoproj.workflow.v1alpha1.WorkflowList`), then should it not return the same type of response?

**Comment by alexec** [comment]
It does return that type, but many optional fields are blank.
