### ISSUE TITLE
input artifacts are duplicated in argo_archived_workflows.workflow column value

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#9484]
argo_archived_workflows table stores json blob related to workflow in the 'workflow' column, when i look inside the json i see the input artifacts value are repeated for as many times as there are steps....to save space i think just one instance of each artifact should be stored

**Comment by alexec** [comment]
The `workflow` column is a copy of the workflow. I can't see how this could happen. Please share archived workflow.

**Comment by tooptoop4** [comment]
what I can see is that its a 4 step workflow where the artefact from step 1 is passed into step 2/3/4. to save space I think it should refer to a pointer id of the artefact and only store the artefact once rather than x times

**Comment by tooptoop4** [comment]
not a bug, it was because wf has workflow.params being copied into each template/step level params
