### ISSUE TITLE
errored: Timeout: request did not complete within requested timeout context deadline exceeded

### ISSUE THREAD

**Issue by hitk6** [argoproj/argo-workflows#9485]
Receiving `context deadline exceeded` error. This issue occurs intermittently. Facing this issue on multiple customers. We are running k8s clusters on k3s platform.
How can we solve this issue ?

```
errored: Timeout: request did not complete within requested timeout context deadline exceeded
```

* [x] Used the Emissary executor.

argo version: v3.2.9

**Comment by blkperl** [comment]
Hi @hitk6, I believe that message is returned by the K8s API server. Are you able to review your API server logs to determine what the slow requests might be?

**Comment by alexec** [comment]
No likely an Argo issue. Instead, you probably need to increase the size of your Kubernetes master. Alternatively, check you do not have 1000s of workflows in `kubctl get wf`. This may timeout.
