### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by mashriram** [argoproj/argo-workflows#9490]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have a basic understanding of Go, Kubernetes and Javascript**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work on the issue #8685**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: **(I am fine either ways) (+5:30)**

**Comment by terrytangyuan** [comment]
The linked issue is already being worked on.

**Comment by mashriram** [comment]
Sorry, I can work on this issue https://github.com/argoproj/argo-workflows/issues/4561

**Comment by terrytangyuan** [comment]
Feel free to start working on it and let us know if you need any help.

**Comment by mashriram** [comment]
Sure, I will start this weekend and let you know if I face any issues

**Comment by mashriram** [comment]
@terrytangyuan - After a little bit of struggle, I was able to run argo locally in my machine (Ubuntu 22.04). Can you please let me know what I should do next?

**Comment by terrytangyuan** [comment]
You can pick up an issue to start working on.

**Comment by agilgur5** [comment]
Closing as stale as OP never responded.
We have also removed the mentoring template as there is not bandwidth to support all mentees and we prefer to assist directly on an issue or PR per #11805
