### ISSUE TITLE
3.4rc3 - Node selector on logs screen is always blank

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#9491]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary
![image](https://user-images.githubusercontent.com/69461449/188119473-5c73e383-dbed-4991-b598-e6706c04b28a.png)

* With log archiving enabled, run a workflow.
* When complete, choose a node, and click to view the logs.
* As per the screenshot above, the node selector is always blank, even after clicking something.

This also happens for archived workflows.

This was not the case in 3.3.9

What version are you running? 3.4 - rc3

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Can you try rc2? If rc2 doesn't have this issue, then it might come from this change: https://github.com/argoproj/argo-workflows/pull/9464

If rc2 also has this problem, another change we can look into is this:  https://github.com/argoproj/argo-workflows/pull/8655

**Comment by juliev0** [comment]
I was able to reproduce it, and it does seem like it was a side effect of my fix in rc3. Let me see about fixing it.

**Comment by juliev0** [comment]
Oh, I see. There was a change in my PR that on its face looked like it was just the linter changing the formatting so I ignored it, but it looks like a real code change was accidentally made in there when I was playing around with things. If I set that line back to how it was, it works. I'll submit a PR.

**Comment by tim-sendible** [comment]
This is confirmed resolved in rc4
