### ISSUE TITLE
Cron schedule syntax documentation

### ISSUE THREAD

**Issue by Fran-Rg** [argoproj/argo-workflows#9493]
# Summary

Documentation for the Description of the "schedule" in CronWorkflow is laking a reference to the actual syntax format: "Schedule at which the Workflow will be run. E.g. 5 4 * * *". I'm assuming since this is all very integrated to kubernetes that it is using that said syntax: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-schedule-syntax

Would be good to add a reference to the above link if that's the case.

# Use Cases

New to kubernetes schedule thus didn't know what to expect. Would be good to have it there

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Would you like to submit a PR to enhance the docs?

**Comment by tim-sendible** [comment]
@terrytangyuan if you (or someone) can confirm which cron syntax is used, I don't mind adding this in sometime.

**Comment by terrytangyuan** [comment]
We use this library: https://github.com/robfig/cron

Its syntax is described here: https://pkg.go.dev/github.com/robfig/cron#hdr-CRON_Expression_Format
