### ISSUE TITLE
When Running Argo in sso mode  , its throwing error Not found 

### ISSUE THREAD

**Issue by gyanprakash48** [argoproj/argo-workflows#9519]
I am getting below error when setting auth mode sso. error is Error: 404 Not Found. What not found is not clear, possible to help here ?

time="2022-09-04T11:52:08.535Z" level=info msg="not enabling pprof debug endpoints"
time="2022-09-04T11:52:08.536Z" level=info authModes="[sso]" baseHRef=/ managedNamespace= namespace=argo secure=true
time="2022-09-04T11:52:08.536Z" level=info msg="Generating Self Signed TLS Certificates for Secure Mode"
time="2022-09-04T11:52:08.536Z" level=info msg="config map" name=workflow-controller-configmap
Error: 404 Not Found:
Usage:
argo server [flags]

**Comment by alexec** [comment]
`workflow-controller-configmap` does not exist. Please create it.
