### ISSUE TITLE
`docs` are not being build on master 

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#9522]
I think this is because the Github Token needs to be updated.

No changes to `docs` will be publish until this is fixe.

**Comment by alexec** [comment]
@sarabala1979 I think you, me or @terrytangyuan need to do this.

**Comment by terrytangyuan** [comment]
I don’t have permission on repo settings.

**Comment by terrytangyuan** [comment]
@sarabala1979 @alexec Ping

**Comment by ravitejasssihl** [comment]
Hey @alexec  @terrytangyuan  can you please assign me this project,I would like to work on this.

**Comment by terrytangyuan** [comment]
You won't have permission to work on this.

**Comment by jmeridth** [comment]
@sarabala1979 @alexec any updates on this?

**Comment by terrytangyuan** [comment]
Temporarily fixed.

**Comment by terrytangyuan** [comment]
This is happening again: https://github.com/argoproj/argo-workflows/actions/runs/3270632353/jobs/5379483358

**Comment by alexec** [comment]
Maybe we can fix like this:

https://squidfunk.github.io/mkdocs-material/publishing-your-site/

**Comment by terrytangyuan** [comment]
@sarabala1979 will look into this
