### ISSUE TITLE
workflow(template) name reported in prometheus metrics

### ISSUE THREAD

**Issue by lkeijser** [argoproj/argo-workflows#9527]
# Summary

The prometheus metrics exposed by argo should include the name of the workflow(template), as well as its parameters, if any.

# Use Cases

As it is now, we can only use the metrics to report if any workflow has failed. If we could filter on the name of the workflow, and optionally its parameters, we would filter out certain failed workflows as they aren't relevant for production.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by tico24** [comment]
This is a valid request. I'm going to close it in favour of the older, more thumb'd-up #6772 to make tracking easier.
