### ISSUE TITLE
Use GoTemplate

### ISSUE THREAD

**Issue by speedfl** [argoproj/argo-workflows#9534]
# Summary

In ArgoCd I implemented usage of GoTemplate for ApplicationSet. Purpose is to do the same in workflow

https://github.com/argoproj/argo-cd/pull/10026

# Use Cases

It will be useful in all complex case needing advanced templating features.

Work done with expressions is going in this direction.

Here is an example: examples/expression-reusing-verbose-snippets.yaml

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by callmetushar123** [comment]
Hey I would like to work on this issue please assign it to me.

**Comment by alexec** [comment]
Adendmum, to fix both (a) and (b) we need to converge on one techonlogy, which is `expr` and, wherever we might need to evaluate something, allow the user to define the expression and add it. Example is this:

https://github.com/argoproj/argo-workflows/blob/3a3f1599718453ca79800cfc28f6631ee780911b/pkg/apis/workflow/v1alpha1/workflow_types.go#L452

**Comment by agilgur5** [comment]
Closing this as not planned per above comments. See #9529 et al for `expr` standardization
