### ISSUE TITLE
Changing port number results in permission denied 

### ISSUE THREAD

**Issue by vinaypuranik** [argoproj/argo-workflows#9555]
![image](https://user-images.githubusercontent.com/6823168/189323579-b47a6a09-e8ae-4a04-9428-a44bf016674c.png)
Hi, Is there a way to change the default port from 2746 ? I  get permission denied error

**Comment by agilgur5** [comment]
There is a `port` flag available on the `argo server` command: https://argoproj.github.io/argo-workflows/cli/argo_server/
