### ISSUE TITLE
Change regressions and bug reports to use form

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#9556]
Too many user files incomplete bug reports, or have not done any basic diagnosis of the issue.

We could try https://beyondco.de/blog/github-issue-forms to reduce this problem and reduce the number of bug reports.

**Comment by alexec** [comment]
@caelan-io would you be interested in doing this?

**Comment by caelan-io** [comment]
Yes, happy to take this on after ArgoCon 👍
