### ISSUE TITLE
'ARCHIVED WORKFLOWS' UI page needs pagination

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#9570]
The UI page for 'ARCHIVED WORKFLOWS' takes a while to load and brings back over 6000 workflow entries for me. It seems the default is last month of workflows. I think there should be pagination to only show last 100 workflows (maybe 100 is configurable), also possibly the date range could be configurable from a month to a week?

**Comment by agilgur5** [comment]
This ended up getting duplicated by #10820, which got more upvotes and had a reference too. So closing in favor of that one, although it is already completed anyway (although there are currently other issues with 3.5's unified Archived + Live UI, c.f #12025)
