### ISSUE TITLE
Updating the correct state of issues/tasks which are in closed state.

### ISSUE THREAD

**Issue by surbhiahuja** [argoproj/argo-workflows#9576]
# Summary

What change needs making?
For most of the issues which are actually closed/PR closed, the Status is not getting updated correctly. 

# Use Cases
We can have an auto-close functionality enabeled once PR to an issue is closed and merged in main.

When would you use this?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
This is already available via GitHub automation.

**Comment by tooptoop4** [comment]
close?
