### ISSUE TITLE
Add node retry option to UI

### ISSUE THREAD

**Issue by skirklin** [argoproj/argo-workflows#9579]
# Summary

Add a button (probably to the node summary panel) to manually trigger retry of a failed task.

# Use Cases

When a single node has failed and I want to re-run it, I should be able to do that from the UI.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by tooptoop4** [comment]
superseded by https://github.com/argoproj/argo-workflows/issues/10139
