### ISSUE TITLE
3.4Rc4 - ${metadata.name} seems to always get the workflow name, not pod name

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#9588]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using `:latest` images.

## Summary

What happened/what you expected to happen?
In accordance with [the documentation](https://argoproj.github.io/argo-workflows/links/), I should be able to place `${metadata.name}` into a custom pod link and it should output the pod name. Instead, it always outputs the workflow name.

This is a regression from 3.3.

I have tried with `POD_NAMES` set to `v1` and this *seems* to resolve the issue.

What version are you running? 3.4 rc4

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
@JPZ13 Would you like to look into this when you get a chance?

**Comment by JPZ13** [comment]
> @JPZ13 Would you like to look into this when you get a chance?

Happy to. I'm a little tied up for the rest of the day, but @rohankmr414, could you take a look at this today and post any of your findings? I'll then take it from there

Also, @terrytangyuan what do we want the ideal behavior to be? The documentation says `${metadata.name}: Name of the current workflow / pod / event source / sensor` but now that the workflow name and the pod name have diverged with pod names v2, it might make more sense to have the `${metadata.name}` variable be the workflow name and add another variable to get the pod name. More than happy to go with whichever cc @tim-sendible

**Comment by sarabala1979** [comment]
@terrytangyuan @JPZ13 is it blocker for 3.4 GA?

**Comment by JPZ13** [comment]
@sarabala1979 I personally think it makes more sense to have `${metadata.name}` interpolate to the workflow name and wouldn't consider this a 3.4 GA release blocker, but I also want to hear @terrytangyuan and @tim-sendible's thoughts

**Comment by terrytangyuan** [comment]
Workflow name sounds more reasonable to me.

**Comment by tico24** [comment]
Still an issue.

**Comment by JPZ13** [comment]
I synced with @tim-sendible today - the `${metadata.name}` field is working properly in the `workflow-controller-configmap`

**Comment by JPZ13** [comment]
I would suggest closing this issue

**Comment by tim-sendible** [comment]
Agreed. From what I saw on @JPZ13's screen it all looks good now. Thanks.

**Comment by as42sl** [comment]
Still an issue with 3.4.1! This used to work in previous versions. Please allow to reference the pod name in links

**Comment by boniek83** [comment]
It almost works in 3.4.2: For this link:
`http://grafana.home.local/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22expr%22:%22%7Bcontainer%3D%5C%22main%5C%22,pod%3D%5C%22${metadata.name}%5C%22%7D%22,%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D`
_${metadata.name}_ correctly is resolved to a pod BUT %3D is not resolved to a = so loki gets this query:
`{container%3D"main",pod%3D"backfill-worker-go62jrw-962151937"}`
instead of this:
`{container="main",pod="backfill-worker-go62jrw-962151937"}`

**Comment by tico24** [comment]
@boniek83 - this is a different issue to the one I raised. I have covered it in #9935
