### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by anil10032** [argoproj/argo-workflows#9611]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: Yes I have read the mentoring guide.

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer:  We are experimenting with argo in our organization and found it awesome. I have experience working with Go, React and Kubernetes.

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: I have gone through the open issues and I found #6535 #6529 would be great issues to get started.

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: I can communicate with my mentor in async and I am located in IST timezone.

**Comment by terrytangyuan** [comment]
Feel free to start working on it and let us know if you have any questions.
