### ISSUE TITLE
Archived Workflows Tree view UI is broken

### ISSUE THREAD

**Issue by rajaie-sg** [argoproj/argo-workflows#9614]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using `:latest` images.
* [x] Attached the smallest workflow that reproduces the issue.
* [x] Attached logs from the workflow controller.
* [x] Attached logs from the wait container.

## Summary

After upgrading to Argo workflows 3.4.0, the "Archived Workflows" tree view UI seems to be broken.

![image](https://user-images.githubusercontent.com/74200541/191070476-ba1141b5-9e9c-4f00-b6ef-3df377b0e8d0.png)

![image](https://user-images.githubusercontent.com/74200541/191070542-5c70c774-1a92-4bb6-8946-e80f3e657c57.png)

I need to zoom out multiple times so that I can view the rest of the side panel options (like the Logs button). This issue happens both in Chrome and Safari.

What version are you running?

3.4.0

## Diagnostics

This happens with any workflows I create. The workflow UI is fine, but the Archived Workflows UI is broken.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by dakotalillie** [comment]
I think I caused this when I submitted https://github.com/argoproj/argo-workflows/pull/8963. Working on a fix.
