### ISSUE TITLE
add option to store single artifact/archive files (ie .txt) as-is without creating .tgz on it 

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#9626]
.tgz artifacts can't be viewed in 3.4.0 UI (unless i download), but my artifacts are .txt, i did not specify to make .tgz so would be good to have these stored raw and viewable

![image](https://user-images.githubusercontent.com/33283496/191157664-4e7ab2bd-37c0-4a10-a1f6-5e089e3c80b0.png)

**Comment by Omenien** [comment]
Per https://argoproj.github.io/argo-workflows/artifact-visualization/#tgz you can use the `none` [ArchiveStrategy](https://argoproj.github.io/argo-workflows/fields/#archivestrategy) to prevent creation of an archive.

**Comment by tooptoop4** [comment]
thx, https://github.com/argoproj/argo-workflows/blob/4e450e250168e6b4d51a126b784e90b11a0162bc/examples/artifact-disable-archive.yaml shows full spec
