### ISSUE TITLE
artifactgc not working because of labels

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#9628]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

expected artifact to be gc'd

but see "Logs from the workflow controller" below, nothing on the UI indicates issue except that the workflow stays in 'workflows 
 UI' instead of moving to 'archived workflows UI', also the artifact still remains on s3

### Version

3.4.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

`time="2022-09-20T04:34:37.029Z" level=error msg="failed to GC artifacts" error="failed to Create WorkflowArtifactGCTask '' for Garbage Collection: WorkflowArtifactGCTask.argoproj.io \"bitbucket-workflow-20220920t1414421000pbjt2-artgc-wfcomp-2166136261-0\" is invalid: metadata.labels: Invalid value: \"bitbucket-workflow-20220920t1414421000pbjt2-artgc-wfcomp-2166136261\": must be no more than 63 characters" namespace=auth workflow=bitbucket-workflow-20220920t1414421000pbjt2
`

### Logs from in your workflow's wait container

kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

**Comment by tooptoop4** [comment]
in my opinion the step to do aws rm should not care about labels (just pick a random 63 length val if needed)

**Comment by sarabala1979** [comment]
@tooptoop4 Is workflow created by cronworkflow?

**Comment by juliev0** [comment]
Maybe we can use an Annotation instead of a Label, which apparently doesn't restrict to 63 characters

**Comment by juliev0** [comment]
> in my opinion the step to do aws rm should not care about labels (just pick a random 63 length val if needed)

That is a possibility. Maybe something random but repeatable like a hash.

**Comment by tooptoop4** [comment]
@sarabala1979 by argo-event sensor
