### ISSUE TITLE
v3.4.0 release assets: quick-start-* manifests include invalid references to httpbin that results in a failed deployment

### ISSUE THREAD

**Issue by hype-eater** [argoproj/argo-workflows#9659]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I regularly use the `quick-start-minimal.yaml` produced as a release asset to install are usable (and useful!) Argo Workflows in small or ephemeral test/development/demo environments. The quick-start manifests from the latest release include an additional Deployment for httpbin (presumably for testing) which is doomed to fail due to an invalid image tag. Argo Workflows works as expected (as far as I have tested), and it seems fine to just delete the httpbin Deployment. I'm not sure httpbin really belongs in the quick-start manifests, but if it's going to be there, the image tag should be valid.

The "Quick Start" documentation includes instructions to use these assets to install Argo Workflows.

---

**I expected**: 1. A minimal installation of components that enable use of Argo Workflows. 2. Those components should be deploy successfully.

**I experienced**: Starting with 3.4.0, I see the installation includes a Deployment of httpbin, but the Deployment uses the image tag corresponding to the Argo Workflows release version rather than a tag that is valid for the httpbin image.  

---

The problem appears to come from the fact that the `latest` tag is specified in the quick-start base configuration:
https://github.com/argoproj/argo-workflows/blob/e556fe3eb355bf9ef31a1ef8b057c680a5c24f06/manifests/quick-start/base/httpbin/httpbin-deploy.yaml#L16-L18

When producing dist artifacts, the string "latest" is replacement by the (Argo Workflows) version:
https://github.com/argoproj/argo-workflows/blob/e556fe3eb355bf9ef31a1ef8b057c680a5c24f06/Makefile#L389-L391

### Version

v3.4.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A No workflow - this is solely about the quick-start-* manifests in the release assets.
```

### Logs from the workflow controller

N/A not the workflow-controller

### Logs from in your workflow's wait container

N/A not a workflow

---

# To reproduce

Install using quick-start manifest:

```
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/latest/download/quick-start-minimal.yaml
```
or
```
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.4.0/quick-start-minimal.yaml
```

Outcome:
```
$ kubectl get deploy -n argo
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
argo-server           1/1     1            1           38m
httpbin               0/1     1            0           38m
minio                 1/1     1            1           38m
workflow-controller   1/1     1            1           38m
$ kubectl get events --field-selector=type!=Normal
LAST SEEN   TYPE      REASON   OBJECT                        MESSAGE
36m         Warning   Failed   pod/httpbin-7c5dfc9db-m9cb7   Failed to pull image "kennethreitz/httpbin:v3.4.0": rpc error: code = Unknown desc = Error response from daemon: manifest for kennethreitz/httpbin:v3.4.0 not found: manifest unknown: manifest unknown
36m         Warning   Failed   pod/httpbin-7c5dfc9db-m9cb7   Error: ErrImagePull
36m         Warning   Failed   pod/httpbin-7c5dfc9db-m9cb7   Error: ImagePullBackOff
```

**Comment by alexec** [comment]
To fix, prefix image with `quay.io/`?
