### ISSUE TITLE
failed to authenticate /metrics endpoint

### ISSUE THREAD

**Issue by mikutas** [argoproj/argo-workflows#9662]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened

argo-server's log:

`"failed to authenticate /metrics endpoint" error="rpc error: code = Unauthenticated desc = token not valid for running mode"`

We're using in auth-mode=sso, and token is in cookie.

No problem accessing endpoints except /metrics.

I guess it's because metadata has only `Authorization` data from header. 🤔 

https://github.com/argoproj/argo-workflows/blob/769896eb5bf0a7d8db1a94b423e5bc16cf09d5aa/server/apiserver/argoserver.go#L383

### what you expected to happen?

No problem accessing endpoints including /metrics.

### Version

v3.2.9 and master

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
No workflow is needed to reproduce
```

### Logs from the workflow controller

None

### Logs from in your workflow's wait container

None

**Comment by sarabala1979** [comment]
Can you inspect the network call for the metrics call?

**Comment by mikutas** [comment]
Is this ok?
![image](https://user-images.githubusercontent.com/23391543/191885003-8dbccb00-20f0-4de7-a483-d2be7b1113b1.png)
