### ISSUE TITLE
Error when clicking "Logs" button if "retryStrategy" is specified for containerSet

### ISSUE THREAD

**Issue by rajaie-sg** [argoproj/argo-workflows#9669]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When I click the "Logs" button on a container, I expect to see the "Logs" dialog pop up, instead I got the error below

![image](https://user-images.githubusercontent.com/74200541/192056544-dfc4df9c-5d6c-479b-ab50-dd7e45727dc5.png)

![image](https://user-images.githubusercontent.com/74200541/192056488-1b4010f7-e3e4-46c3-b51c-d52ae502dcdf.png)

### Version

v3.4.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

When the following conditions are met, clicking the "Logs" button on an archived workflow results in the error shared above.

1. Log archiving is enabled
2. Workflow archiving is enabled
3. A containerSet is used
4. A retryStrategy is set

```YAML
name: argosay
inputs:
  parameters:
    - name: message
      value: '{{workflow.parameters.message}}'
outputs: {}
metadata: {}
containerSet:
  containers:
    - name: main
      image: argoproj/argosay:v2
      command:
        - /argosay
      args:
        - echo
        - '{{inputs.parameters.message}}'
      resources: {}
retryStrategy:
  limit: '3'
  retryPolicy: Always
```

Logs from web browser:

```
react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'templateName')
    at t.getTemplateNameFromNode (pod-name.ts:53:14)
    at t.get (archived-workflow-details.tsx:255:34)
    at t.renderArchivedWorkflowDetails (archived-workflow-details.tsx:236:97)
    at t.render (archived-workflow-details.tsx:160:128)
    at Fa (react-dom.production.min.js:182:192)
    at Ra (react-dom.production.min.js:181:224)
    at gs (react-dom.production.min.js:263:490)
    at ul (react-dom.production.min.js:246:265)
    at sl (react-dom.production.min.js:246:194)
    at Xs (react-dom.production.min.js:239:172)
```
```


### Logs from the workflow controller

kubectl logs -n argo deploy/workflow-controller | grep lovely-python-gpghj

```
time="2022-09-23T21:13:54.020Z" level=info msg="Processing workflow" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:13:54.036Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:13:54.041Z" level=info msg="Retry node lovely-python-gpghj initialized Running" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:13:54.041Z" level=info msg="Pod node lovely-python-gpghj-4282202647 initialized Pending" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:13:54.074Z" level=info msg="Created pod: lovely-python-gpghj(0) (lovely-python-gpghj-argosay-4282202647)" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:13:54.075Z" level=info msg="Container node lovely-python-gpghj-759088314 initialized Pending" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:13:54.075Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:13:54.075Z" level=info msg=reconcileAgentPod namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:13:54.088Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=18919626 workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.075Z" level=info msg="Processing workflow" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.076Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.076Z" level=info msg="task-result changed" namespace=argo nodeID=lovely-python-gpghj-4282202647 workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.076Z" level=info msg="node lovely-python-gpghj-759088314 phase Pending -> Succeeded" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.076Z" level=info msg="node lovely-python-gpghj-759088314 finished: 2022-09-23 21:14:04.076298992 +0000 UTC" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.076Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=lovely-python-gpghj-4282202647 old.message= old.phase=Pending old.progress=0/1 workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.076Z" level=info msg="node lovely-python-gpghj phase Running -> Succeeded" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.076Z" level=info msg="node lovely-python-gpghj finished: 2022-09-23 21:14:04.076497793 +0000 UTC" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.076Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.076Z" level=info msg=reconcileAgentPod namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.076Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.076Z" level=info msg="Marking workflow completed" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.076Z" level=info msg="Marking workflow as pending archiving" namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.076Z" level=info msg="Checking daemoned children of " namespace=argo workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.081Z" level=info msg="cleaning up pod" action=deletePod key=argo/lovely-python-gpghj-1340600742-agent/deletePod
time="2022-09-23T21:14:04.089Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=18919690 workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.168Z" level=info msg="archiving workflow" namespace=argo uid=0f29a9b7-f029-4d8c-8449-e7adc57038bc workflow=lovely-python-gpghj
time="2022-09-23T21:14:04.222Z" level=info msg="Queueing Succeeded workflow argo/lovely-python-gpghj for delete in 1m0s due to TTL"
time="2022-09-23T21:14:09.168Z" level=info msg="cleaning up pod" action=deletePod key=argo/lovely-python-gpghj-argosay-4282202647/deletePod
```

### Logs from in your workflow's wait container

kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

**Comment by sarabala1979** [comment]
@rajaie-sg can you try on v3.3.9?

**Comment by sarabala1979** [comment]
https://github.com/argoproj/argo-workflows/issues/9627

**Comment by rajaie-sg** [comment]
> @rajaie-sg can you try on v3.3.9?

yes I confirmed this still happens in 3.3.9
