### ISSUE TITLE
allow cronworkflow's schedule field accept multiple strings

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#9734]
ie schedule: ["*/20 * 1-5 * *", "*/15 * 25-31 * *"]
so that the cronworkflow is run on any of these schedules

this is less duplication than making 2 different cronworkflows with one schedule each

**Comment by sarabala1979** [comment]
@tooptoop4 is a good idea. Do you like to contribute to it?

**Comment by shraddhazpy** [comment]
@sarabala1979 I will want to take this up!
