### ISSUE TITLE
Cert manager suddenly a dependency???

### ISSUE THREAD

**Issue by allemp** [argoproj/argo-workflows#9737]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

The following pull request #9423 added a mandatory cert manager dependency to the manifests. This is not documented anywhere beyond a new line in the readme to install cert manager and quite frankly caught myself by surprise that a minor version upgrade could introduce breaking changes and new dependencies in the cluster.

If this is intentional and necessary then I think some better documentation and a mention of breaking changes/new dependencies could be added to the change log and upgrade guide, not just the readme.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Not relevant
```

### Logs from the workflow controller

Not relevant

### Logs from in your workflow's wait container

Not relevant

**Comment by sarabala1979** [comment]
@chtcvl  Can you fix this issue?

**Comment by chtcvl** [comment]
Sure, which approach is better:
1. Update documentation and provide additional manifests that don't require cert-manager (and disable TLS).
2. Update manifests to use something like https://github.com/jet/kube-webhook-certgen and remove cert-manager dependency at all

**Comment by alexec** [comment]
This fix for this is to revert 7e40d93. @chtcvl  will need to raise a new PR that does not add cert manager.

@allemp would you like to submit a PR to revert?

**Comment by terrytangyuan** [comment]
I am going to revert it now since our customers are affected by this change and this is a blocker for upgrading: https://github.com/argoproj/argo-workflows/pull/9756
