### ISSUE TITLE
Bring CLOMonitor Score to 100%

### ISSUE THREAD

**Issue by eddie-knight** [argoproj/argo-workflows#9769]
Per discussion in slack, this issue is to track the efforts necessary to bring argo-workflow [CLOMonitor](https://clomonitor.io/projects/cncf/argo#argo-workflows) score to 100% as part of the CNCF security slam.

Below is a checklist of action items. I will add comments if there is anything that can't be addressed or if I am unsure of how to address it. It is possible to [exclude checks](https://github.com/cncf/clomonitor/blob/0942e124e116c2d46b3eeb8204579722ba1ff329/docs/metadata/.clomonitor.yml) with a written justification if that becomes necssary.
### Summary

**Repository**: argo-workflows
**URL**: https://github.com/argoproj/argo-workflows
**Checks sets**:  `CODE`
**Score**: 88

### Checks passed per category

| Category  |  Score  |
| :----------------- | --------: |
|  Documentation  |  100%  |
|  License  |  75%  |
|  Best Practices  |  100%  |
|  Security  |  80%  |
|  Legal  |  n/a  |

### Documentation [100%]

  - [x] [Changelog](https://github.com/argoproj/argo-workflows/blob/master/CHANGELOG.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [x] [Contributing](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [x] [Maintainers](https://github.com/argoproj/argo-workflows/blob/master/OWNERS) ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/argoproj/argo-workflows/blob/master/README.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  
### License [75%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#license_spdx_id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#license_approved))
  - [ ] License scanning ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))
  
### Best Practices [100%]

  - [x] [Artifact Hub badge](https://artifacthub.io/packages/helm/argo/argo-workflows) ([_docs_](https://clomonitor.io/docs/topics/checks/#artifacthub_badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#cla)) `EXEMPT`
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#dco))
  - [x] [OpenSSF badge](https://bestpractices.coreinfrastructure.org/projects/3830) ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf_badge))
  - [x] [Recent release](https://github.com/argoproj/argo-workflows/releases/tag/v3.4.1) ([_docs_](https://clomonitor.io/docs/topics/checks/#recent_release))
  
### Security [80%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary_artifacts))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code_review))
  - [x] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous_workflow))
  - [x] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency_update_tool))
  - [x] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained))
  - [x] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#sbom))
  - [x] [Security policy](https://github.com/argoproj/argo-workflows/blob/master/SECURITY.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#security_policy))
  - [ ] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed_releases))
  - [x] Token permissions ([_docs_](https://clomonitor.io/docs/topics/checks/#token_permissions))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).

**Comment by eddie-knight** [comment]
The `Token-Permissions` check is actively being refined right now, so we shouldn't put too much thought into that until this issue closes: https://github.com/ossf/scorecard/issues/2338

**Comment by agilgur5** [comment]
> * [x]  Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed_releases))

This was completed in #9837

> * [ ]  License scanning ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))

I believe Snyk's [security scans](https://github.com/argoproj/argo-workflows/blob/5def5289a6c010265bb9e8a6bfcd6f1bba80624b/.github/workflows/snyk.yml) do license checks as well, so I think this might just need a badge on the README to satisfy.

And there's a new one now:

* [ ] OpenSSF Scorecard Badge ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf-scorecard-badge))

Assigning to myself right now as I may be working on the related SLSA Level 3, Level 4 checks soon. But anyone can feel free to add as well!

**Comment by agilgur5** [comment]
> I believe Snyk's [security scans](https://github.com/argoproj/argo-workflows/blob/5def5289a6c010265bb9e8a6bfcd6f1bba80624b/.github/workflows/snyk.yml) do license checks as well, so I think this might just need a badge on the README to satisfy.

Welp, never mind, apparently Snyk does not support this for Go deps (see also the CLOMonitor issue: https://github.com/cncf/clomonitor/issues/50#issuecomment-1039557687). So I integrated FOSSA [same as Argo CD](https://github.com/argoproj/argo-cd/blob/a9f03aa8ccdafc350b96ee90db054b11cad44692/README.md?plain=1#L11) (see also #12023 that was made automatically).

So am gonna make a PR for that badge for CLOMonitor and that should bring our non-security scores at 100%.

I'm going to open a separate issue for the security scores / OpenSSF checks so that we can close this one out and that one can be more focused. There's also a few other newer OpenSSF checks as well, and `Token-Permissions` seems to be refined now.

**Comment by agilgur5** [comment]
> The `Token-Permissions` check is actively being refined right now, so we shouldn't put too much thought into that until this issue closes: [ossf/scorecard#2338](https://github.com/ossf/scorecard/issues/2338)

@eddie-knight curious if the `SECURITY-INSIGHTS.yml` checks ("Dependencies policy", "Security insights", and "Self-Assessment) are going through similar refinement? They aren't listed under OpenSSF Scorecard's checks right now.

I also haven't seen any project (including k8s itself) adopt a `SECURITY-INSIGHTS.yml` other than some of the OpenSSF related repos.

**Comment by eddie-knight** [comment]
Yep @agilgur5, the SI was adopted by CLOMonitor (not via Scorecard) at the beginning of this month in order to streamline the hygiene checks you listed there.

If there's a clarity gap I'd love to get more insight from you so that I can make sure to improve the related [supporting material](https://github.com/security-slam/metrics/blob/main/resource-library/securityinsights-guide.md) for the Slam.

**Comment by agilgur5** [comment]
> The SI was adopted by CLOMonitor (not via Scorecard) at the beginning of this month in order to streamline the hygiene checks you listed there.

Is it going to be added to Scorecard? It's a bit confusing that most, but not all, of the security checks are via Scorecard

> If there's a clarity gap

Not really a clarity gap, I understand what `SECURITY-INSIGHTS.yml` is for and have read [the spec](https://github.com/ossf/security-insights-spec/blob/v1.0.0/specification.md) etc. I am bit surprised that CLOMonitor is pushing it despite current lack of adoption though.

More specifically, the lack of adoption for it currently (including in Scorecard) combined with how much information there is to fill out for it (plus yet another file at the root of the repo) makes the effort/value ratio feel not really worthwhile right now. 
Especially as `SECURITY-INSIGHTS.yml` does not really improve any security on its own as it's just a metadata file; feels like there are (much?) more valuable uses of time for the same effort (e.g. adding SLSA Level 3+ provenance, adding CodeQL, fixing vulns per #12031, adding [`step-security/harden-runner`](https://github.com/step-security/harden-runner), etc).

**Comment by eddie-knight** [comment]
I can't speak on the Scorecard roadmap (but there are folks in the CNCF Slack #security-slam channel who can). I believe there is discussion of extending Scorecard to reference the SI in situations where less-predictable things such as SBOM artifacts are needing to be detected.

That's the idea behind integrating it into CLOMonitor— we tried to capture the results of those discussions in a [CLOMonitor GitHub issue](https://github.com/cncf/clomonitor/issues/1290#issuecomment-1749638426) for posterity. You can see there was debate around whether the new checks should be in the `Documentation` or `Code` check set... but the intent at the end of the day is to use these new checks to find the harder-to-detect elements that TAG Security recommends.

**Comment by agilgur5** [comment]
Yea I guess I am confused as to CLOMonitor's security checks and Scorecard's checks; one would think they'd be the same. 

I see that Security Policy and SBOMs are also CLOMonitor-only.
It could make sense if Scorecard was all quantitative things and CLOMonitor was all metadata, but that's also not the case right now since Scorecard has "OpenSSF Best Practices Badge", "License", etc (also "Maintained", which is more of an opinionated check). Some standardization and/or explicit delegation of checks between the two would be good to see.

> More specifically, the lack of adoption for it currently (including in Scorecard) combined with how much information there is to fill out for it (plus yet another file at the root of the repo) makes the effort/value ratio feel not really worthwhile right now.

Well ok this got completed in CD https://github.com/argoproj/argo-cd/pull/16135 so the effort is now significantly reduced as Workflows would be very similar

**Comment by eddie-knight** [comment]
CLOMonitor currently runs a subset of scorecard checks and run a few additional checks that have been recommended by either TAG Security or maintainers of graduated CNCF projects.

To compare and contrast a bit... In scorecard, nobody is reasonably expected to have a full 10/10 score, so checks can't be optionally skipped. In contrast, projects can skip CLOMonitor checks (including the checks that harness Scorecard) by providing a written justification in the CLOMonitor config.
