### ISSUE TITLE
pod deleted error when running multiple workflows concurrently

### ISSUE THREAD

**Issue by sanqiuli** [argoproj/argo-workflows#9780]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I wrote a workflow about biological data processing. This workflow may require a lot of cpu and memory during the running process, but I did not specify the amount of resources required by the template in the workflow. This workflow I run individually is It is 100% successful, but the pod deleted error will appear when running more than one at the same time, but because the pod has been deleted, I cannot see the logs of the init, wait, and main containers in the pod.
![image](https://user-images.githubusercontent.com/61610792/194787881-84112af9-b183-4338-a45c-8b5bdb60b5a0.png)

### Version

v3.4.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
none
```

### Logs from the workflow controller

 kubectl logs -n argo deploy/workflow-controller | grep sky2-pipeline-jwtf8.feature-classify.feature-classify-1   
time="2022-10-09T12:05:06.044Z" level=info msg="All of node sky2-pipeline-jwtf8.feature-classify.feature-classify-1 dependencies [] completed" namespace=argo workflow=sky2-pipeline-jwtf8
time="2022-10-09T12:05:06.054Z" level=info msg="Created pod: sky2-pipeline-jwtf8.feature-classify.feature-classify-1 (sky2-pipeline-jwtf8-qiime2-picrust2-2951325495)" namespace=argo workflow=sky2-pipeline-jwtf8
time="2022-10-09T12:08:32.500Z" level=info msg="Workflow pod is missing" namespace=argo nodeName=sky2-pipeline-jwtf8.feature-classify.feature-classify-1 nodePhase=Running recentlyStarted=false workflow=sky2-pipeline-jwtf8

### Logs from in your workflow's wait container

none

**Comment by sarabala1979** [comment]
I think pod deletion because of node auto scale or node rotation. You  can prevent this with two options.

1. Add retry strategy for every step
2. Enable the PDB on workflow

**Comment by sanqiuli** [comment]
> What is PDB? There are many steps in the workflow, and Add retry strategy for every step is very troublesome.

**Comment by sarabala1979** [comment]
https://github.com/argoproj/argo-workflows/blob/master/examples/default-pdb-support.yaml

**Comment by sanqiuli** [comment]
> https://github.com/argoproj/argo-workflows/blob/master/examples/default-pdb-support.yaml
> […](#)
> Sent from my iPhone
> On Oct 9, 2022, at 6:36 PM, sanqiuli ***@***.***> wrote: ﻿ What is PDB? There are many steps in the workflow, and Add retry strategy for every step is very troublesome. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.
![image](https://user-images.githubusercontent.com/61610792/194793848-cd091918-7752-4b3b-907e-eac6e3a579f1.png)
![image](https://user-images.githubusercontent.com/61610792/194793875-e5d60c18-0424-433b-a9e2-5be34721b6ea.png)
![image](https://user-images.githubusercontent.com/61610792/194794163-68799f47-9192-4b73-8ad0-2b75998966ef.png)

it didn't work

**Comment by sarabala1979** [comment]
@sanqiuli can you provide the pod describe? Can you gett more details why the POD is getting deleted in kubernetes?

**Comment by sanqiuli** [comment]
> @sanqiuli can you provide the pod describe? Can you gett more details why the POD is getting deleted in kubernetes?

I didn't set argo's gc, but my pods are garbage collected
I only query the log of the pod being gc
```
~$ kubectl logs -n kube-system -f kube-controller-manager-picb2-master-1 | grep sky2-pipeline-ff5gq
I1010 11:16:53.226435       1 gc_controller.go:78] PodGC is force deleting Pod: argo/sky2-pipeline-ff5gq-script-2925226625
I1010 11:16:53.226680       1 gc_controller.go:78] PodGC is force deleting Pod: argo/sky2-pipeline-ff5gq-script-1056479775
I1010 11:17:53.271529       1 gc_controller.go:78] PodGC is force deleting Pod: argo/sky2-pipeline-ff5gq-script-3730124130
I1010 11:19:33.319019       1 gc_controller.go:78] PodGC is force deleting Pod: argo/sky2-pipeline-ff5gq-qiime2-picrust2-1605826948
```I didn't set argo's gc, but my pods are garbage collected
I only query the log of the pod being gc
I found an article that is somewhat familiar to my problem [link](https://blog.csdn.net/alex_yangchuansheng/article/details/119156912)

**Comment by alexec** [comment]
see #9058

**Comment by sanqiuli** [comment]
I succeeded after adding both retry and pdb in yaml

**Comment by sanqiuli** [comment]
> 见#9058
I found that when my pod is waiting to be scheduled, it is garbage collected, which is related to the --terminated-pod-gc-threshold (default 12500, I set it to 100) set by the kube-controller-manager of k8s. When the number of terminated pods exceeds When this value is used, a pod deleted error will occur
