### ISSUE TITLE
Link templates do not work when template is in URL path

### ISSUE THREAD

**Issue by AndrewChubatiuk** [argoproj/argo-workflows#9791]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I have workflow controller links configuration
```
links: |
   - name: Spark UI
      scope: workflow
      url: https://example.com/workflow/${metadata.name}/jobs/
```
when I press `Spark UI` button it redirects me to `https://example.com/workflow/$%7Bmetadata.name%7D/jobs/`.
Info API returns already encoded links. They become encoded when URL object reassembles string https://github.com/argoproj/argo-workflows/blob/master/config/config.go#L155

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Any workflow can be used here
```

### Logs from the workflow controller

No errors in logs expected

### Logs from in your workflow's wait container

No errors in logs expected

**Comment by bkanuka** [comment]
I can confirm.  To add, the following link config *works*:
```
    - name: Pod Link Working
      scope: pod-logs
      url: https://logging-facility?namespace=${metadata.namespace}
```
The following does *not work*:
```
    - name: Pod Link Not Working
      scope: pod-logs
      url: https://logging-facility/namespace=${metadata.namespace}
```
The second generates the link `https://logging-facility/namespace=$%7Bmetadata.namespace%7D`
