### ISSUE TITLE
argo server install error because of secret `argo-server-tls` not found

### ISSUE THREAD

**Issue by zwwhdls** [argoproj/argo-workflows#9796]
### Pre-requisites

- [X] I have double-checked my configuration
- [ ] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

When I install argo server under the guidance of installation in [release note](https://github.com/argoproj/argo-workflows/releases/tag/v3.4.1), argo server failed with the following log:

```
root@iZbp14pqgyt68f8g7bik3tZ:~# kubectl -n argo logs argo-server-5dc857976f-t2hzw
time="2022-10-12T03:25:47.665Z" level=info msg="not enabling pprof debug endpoints"
time="2022-10-12T03:25:47.665Z" level=info authModes="[client]" baseHRef=/ managedNamespace= namespace=argo secure=true ssoNamespace=argo
time="2022-10-12T03:25:47.665Z" level=info msg="Getting contents of Kubernetes secret argo-server-tls for TLS Certificates"
time="2022-10-12T03:25:47.682Z" level=warning msg="Non-transient error: secrets \"argo-server-tls\" not found"
Error: secrets "argo-server-tls" not found
secrets "argo-server-tls" not found
Usage:
  argo server [flags]

Examples:

See https://argoproj.github.io/argo-workflows/argo-server/
```

Also, I can not find secret `argo-server-tls` in `https://github.com/argoproj/argo-workflows/releases/download/v3.4.1/install.yaml`. Release v3.4.0 has no this issue. Is secret `argo-server-tls` missed in `install.yaml`?

### Version

v3.4.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
no workflow
```

### Logs from the workflow controller

kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

### Logs from in your workflow's wait container

kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

**Comment by tczhao** [comment]
Thanks, I think we got a "fix" from this PR.
https://github.com/argoproj/argo-workflows/pull/9756

The reverted feature is implementing in https://github.com/argoproj/argo-workflows/pull/9789
