### ISSUE TITLE
Bring CLOMonitor Score to 100%

### ISSUE THREAD

**Issue by hernanpl** [argoproj/argo-workflows#9819]
This repo is signed up as part of the KubeCon [Security Slam](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/experiences/#security-slam). I'm bringing to your attention the checklist from the official [CLOMonitor page for Argo](https://clomonitor.io/projects/cncf/argo#argo-workflows) -- it refreshes every hour, so it should be up-to-date.

### Summary

**Repository**: argo-workflows
**URL**: https://github.com/argoproj/argo-workflows
**Checks sets**:  `CODE`
**Score**: 88

### Checks passed per category

| Category  |  Score  |
| :----------------- | --------: |
|  Documentation  |  100%  |
|  License  |  75%  |
|  Best Practices  |  100%  |
|  Security  |  80%  |
|  Legal  |  n/a  |

### Documentation [100%]

  - [x] [Changelog](https://github.com/argoproj/argo-workflows/blob/master/CHANGELOG.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [x] [Contributing](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [x] [Maintainers](https://github.com/argoproj/argo-workflows/blob/master/OWNERS) ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/argoproj/argo-workflows/blob/master/README.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  
### License [75%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#license_spdx_id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#license_approved))
  - [ ] License scanning ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))
  
### Best Practices [100%]

  - [x] [Artifact Hub badge](https://artifacthub.io/packages/helm/argo/argo-workflows) ([_docs_](https://clomonitor.io/docs/topics/checks/#artifacthub_badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#cla)) `EXEMPT`
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#dco))
  - [x] [OpenSSF badge](https://bestpractices.coreinfrastructure.org/projects/3830) ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf_badge))
  - [x] [Recent release](https://github.com/argoproj/argo-workflows/releases/tag/v3.4.1) ([_docs_](https://clomonitor.io/docs/topics/checks/#recent_release))
  
### Security [80%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary_artifacts))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code_review))
  - [x] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous_workflow))
  - [x] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency_update_tool))
  - [x] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained))
  - [x] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#sbom))
  - [x] [Security policy](https://github.com/argoproj/argo-workflows/blob/master/SECURITY.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#security_policy))
  - [ ] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed_releases))
  - [ ] Token permissions ([_docs_](https://clomonitor.io/docs/topics/checks/#token_permissions))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).

**Comment by eddie-knight** [comment]
whoops-- duplicate of #9769
