### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by aditya-shrivastava** [argoproj/argo-workflows#9832]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I have previous experience in React.**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #9281**

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: (async)

**Comment by terrytangyuan** [comment]
Feel free to start working on that issue and let us know if you have any questions.

**Comment by aditya-shrivastava** [comment]
Hi @terrytangyuan, I have made some changes and the bug seems to be fixed. I have added a comment in the issue #9281 with snapshots of the same. Can I get some feedback on it? :smile:

**Comment by terrytangyuan** [comment]
Could you send a PR, and the team will review it?

**Comment by aditya-shrivastava** [comment]
Sure, I will do that.

**Comment by terrytangyuan** [comment]
It should be part of this test suite: https://github.com/argoproj/argo-workflows/blob/master/test/e2e/cli_test.go

**Comment by aditya-shrivastava** [comment]
Thanks for the help. I was able to make a PR #9874  but one of the checks seems to have timed out and got cancelled. How can I re-run the checks?

**Comment by terrytangyuan** [comment]
You can trigger the CI by pushing new commits.

**Comment by aditya-shrivastava** [comment]
Thanks all the checks have passed now. I have marked the PR as "Ready for review".

**Comment by terrytangyuan** [comment]
Merged. Congrats on your first contribution!

**Comment by aditya-shrivastava** [comment]
Thanks. I would definitely try and contribute more. :smiley:
