### ISSUE TITLE
click 'Retry' button throws error

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#9843]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

so a workflow failed, then i clicked 'retry' button in UI and received this screen:

![image](https://user-images.githubusercontent.com/33283496/196073492-59775be1-0874-4c42-ac8f-24ff5898c1cc.png)

### Version

v3.4.1

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

### Logs from in your workflow's wait container

kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

**Comment by ibotdotout** [comment]
I can't reproduce this one on v3.4.1 and latest on master branch. 

I tested with https://github.com/argoproj/argo-workflows/blob/master/examples/continue-on-fail.yaml

Could you help to provide example workflow that able to reproduces the issue ?

**Comment by sarabala1979** [comment]
@tooptoop4  can you provide the reproducible workflow?

**Comment by tooptoop4** [comment]
this still affects 3.4.3

**Comment by tooptoop4** [comment]
be sure to click retry without clicking any task circle

**Comment by tooptoop4** [comment]
fixed by https://github.com/argoproj/argo-workflows/pull/11071/files
