### ISSUE TITLE
 plan to add workflow labels to the metric?

### ISSUE THREAD

**Issue by linkingli** [argoproj/argo-workflows#9848]
# Summary

 add workflow/workflowTemplate's label to the metric

# Use Cases

When I have two workflowTemplates (A,B), I want to know the overall situation of workflow of A and B respectively. The current metric does not support me to do this. Since there is no label for workflow.
NOW:
argo_workflows_count{container="workflow-controller", endpoint="metrics", 
instance="127.0.0.1:9090", job="workflow-controller-metrics", namespace="argo",
 pod="workflow-controller-7d69c4b564-t6xn8",
 service="workflow-controller-metrics", status="Error"}
BETTER:
argo_workflows_count{container="workflow-controller", endpoint="metrics", 
instance="127.0.0.1:9090", job="workflow-controller-metrics", namespace="argo",
 pod="workflow-controller-7d69c4b564-t6xn8",
 service="workflow-controller-metrics", status="Error",templateName="test"}
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Duplicate https://github.com/argoproj/argo-workflows/issues/9849
