### ISSUE TITLE
Mutex issue on Argo workflows making workflow live forever

### ISSUE THREAD

**Issue by uday-mandava** [argoproj/argo-workflows#9854]
### Pre-requisites

- [X] I have double-checked my configuration
- [ ] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

![image](https://user-images.githubusercontent.com/98283868/196312234-0308d60c-0b8e-4031-a870-0c3a028074af.png)

### Version

v3.3.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
This is happening in a random manner. Consistently seeing once in every few days.
```

### Logs from the workflow controller

kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

time="2022-10-12T22:43:00.805Z" level=info msg="Processing workflow" namespace=* workflow=*
time="2022-10-12T22:43:00.807Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" namespace=* workflow=*

### Logs from in your workflow's wait container

kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

**Comment by terrytangyuan** [comment]
Please try the newest version. There have been some related fixes.

**Comment by uday-mandava** [comment]
Okay, will do that. Thank you!

**Comment by sarabala1979** [comment]
@uday-mandava are you using v3.0.9? 1time="2022-10-12T22:43:00.807Z" level=warning msg="Workflow processing has been postponed due to concurrency limit" namespace=* workflow=*` is expected behavior if lock is acquired by some other workflow.

Can you share the metadata of both workflows?

**Comment by uday-mandava** [comment]
Updated the version info.
