### ISSUE TITLE
GitHub checks for PRs are not reliable

### ISSUE THREAD

**Issue by anilkumar-pcs** [argoproj/argo-workflows#9861]
# Summary

What change needs making?

Random GitHub checks fail at every iteration and it is very unproductive. The failure reasons are also intermittent and mostly will go away if the checks are retriggered.

Currently, the only way to retrigger the checks is to make an empty commit to the PR.

For example, I am making a series of empty commits on my PR #8685 just to make sure all the checks are green.

Can we enable re-run for GitHub checks or make them reliable which helps all the contributors?

# Use Cases

When would you use this?

This saves a lot of time for all the contributors.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Which test is failing? If it's a flaky test, we should fix it. If it's something with GitHub Actions, we can retry is like this: https://github.com/argoproj/argo-workflows/blob/master/.github/workflows/ci-build.yaml#L157-L161

**Comment by anil10032** [comment]
@terrytangyuan It is not the same test always. You can check the commits in #9859 to see how a different check fails at every iteration.
I have verified all the tests working in my local before committing my changes.

**Comment by isubasinghe** [comment]
@terrytangyuan I've had issues with the Github tests too, we should try and address this somehow, additionally the maintainers should take note that failed Github checks don't necessarily mean the proposed change introduced it.  

See https://github.com/argoproj/argo-workflows/pull/9909
https://github.com/argoproj/argo-workflows/pull/9918

**Comment by isubasinghe** [comment]
It seems to be `FunctionalSuite/TestOutputArtifactS3BucketCreationEnabled` that is causing issues.

**Comment by isubasinghe** [comment]
@terrytangyuan can you please approve: https://github.com/argoproj/argo-workflows/pull/10084
This should be fixed afterwards

**Comment by terrytangyuan** [comment]
Merged
