### ISSUE TITLE
Request for mentor

### ISSUE THREAD

**Issue by ravitejasssihl** [argoproj/argo-workflows#9871]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: No

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #9274 **

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: (async/sync) (Indian Standard Time)

**Comment by terrytangyuan** [comment]
Hi @ravitejasssihl, I assigned that issue to you. Looks like you don't have any experience with the relevant technologies so you might need to catch up before working on it.
