### ISSUE TITLE
Create wait container for resource templates when archiveLogs: true

### ISSUE THREAD

**Issue by Freia3** [argoproj/argo-workflows#9911]
# Summary

I need a wait container for workflows containing a resource template when archiveLogs: true

# Use Cases

I'm running a spark application in a Workflow using a resource template. I want to archive the logs in an artifact repository. To archive the logs, I need a wait container.

Check out the comment here:
https://github.com/argoproj/argo-workflows/blob/6b086368f6480a2de5e2d43eec73514de0ad01ac/workflow/controller/workflowpod.go#L213
```
	if tmpl.GetType() != wfv1.TemplateTypeResource && tmpl.GetType() != wfv1.TemplateTypeData {
		// we do not need the wait container for resource templates because
		// argoexec runs as the main container and will perform the job of
		// annotating the outputs or errors, making the wait container redundant.
		waitCtr := woc.newWaitContainer(tmpl)
		pod.Spec.Containers = append(pod.Spec.Containers, *waitCtr)
```

I created an issue for this before: https://github.com/argoproj/argo-workflows/issues/9900

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Duplicate https://github.com/argoproj/argo-workflows/issues/9900
