### ISSUE TITLE
Creating a workflow with the Python client errors

### ISSUE THREAD

**Issue by filippomc** [argoproj/argo-workflows#9919]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Using the [Python api](https://pypi.org/project/argo-workflows/) on version 6+ I am not able to create a workflow anymore.

The error is:

```
argo_workflows.exceptions.ApiTypeError: Invalid type for variable 'started_at'. Required value type is datetime and passed type was NoneType at ['received_data']['status']['started_at']
```

Looks like the openapi specs do not comply to the value that is returned for the workflow status by argo on create: argo is indeed returning

```
{
...
    "status": {
        "startedAt": null,
        "finishedAt": null
    }
```

which cannot be corced to a date as the library is attempting to.

### Version

v3.1.8+, python api 6+

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Install argo and use the following snippet

from argo_workflows import ApiClient, Configuration
from argo_workflows.api.workflow_service_api import WorkflowServiceApi,\
    IoArgoprojWorkflowV1alpha1WorkflowCreateRequest

namespace = "argo"
argo_host = "http://argo.local"
workflow = {
    "metadata": {
        "generateName": "hello-world-",
        "namespace": namespace,
        "labels": {
            "workflows.argoproj.io/completed": "false"
        }
    },
    "spec": {
        "templates": [
            {
                "name": "whalesay",
                "arguments": {},
                "inputs": {},
                "outputs": {},
                "metadata": {},
                "container": {
                    "name": "",
                    "image": "docker/whalesay:latest",
                    "command": [
                        "cowsay"
                    ],
                    "args": [
                        "hello world"
                    ],
                    "resources": {}
                }
            }
        ],
        "entrypoint": "whalesay",
        "arguments": {}
    }
}


def test_submit():
    wf = IoArgoprojWorkflowV1alpha1Workflow._new_from_openapi_data(
        **workflow, _check_type=False)
    api_client = ApiClient(Configuration(host=argo_host))
    service = WorkflowServiceApi(api_client=api_client)

    req = IoArgoprojWorkflowV1alpha1WorkflowCreateRequest(
        workflow=wf, instance_id=namespace, namespace=namespace)

    wf = service.create_workflow(namespace, req)
```

### Logs from the workflow controller

The workflow is submitted correctly

### Logs from in your workflow's wait container

The workflow is submitted correctly

**Comment by terrytangyuan** [comment]
Check out the examples in the README file. I believe you need to skip validations.

**Comment by filippomc** [comment]
Thanks @terrytangyuan. I wasn't aware that examples were available, it would have helped having at least a link in the pip page.
Wonder whether there is a the will to make a specification and code generation compliant to the implementation (or vice-versa) or this is the intended way to go.

**Comment by terrytangyuan** [comment]
This is the way to go for now since it's an issue with openapi-gen.
