### ISSUE TITLE
Variable retries (retrystrategy) cannot be accessible inside the container code

### ISSUE THREAD

**Issue by tahasharif2000** [argoproj/argo-workflows#9922]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

I have a argo workflow application with multiple steps that are configured with retrystrategy and retry is working fine but when I tried accessing "retries" variable inside the container code, it says variable or function "retries" is not configured.
I just need to pass the current retry count inside the container or the application for logging purpose.
It is also fine to pass it as a parameter, but please help me with how to pass reties in the input parameters. Thanks

### Version

3.2.6

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
name: random-fail
        retryStrategy:
          limit: "10"
container:
          image: (removed full path)python:3.6-alpine
          command: [python, -c]
          args: ["import random; import sys; print('retries: {{retries}}'); exit_code = random.choice([0, 1, 1]); sys.exit(exit_code)"]

Error
Error: INSTALLATION FAILED: parse error at ********.yaml:80): function "retries" not defined
```

### Logs from the workflow controller

Error
Error: INSTALLATION FAILED: parse error at ********.yaml:80): function "retries" not defined

### Logs from in your workflow's wait container

Error
Error: INSTALLATION FAILED: parse error at ********.yaml:80): function "retries" not defined

helm install itself is failing

**Comment by sarabala1979** [comment]
@tahasharif2000 can you try on v3.4.x?

**Comment by tczhao** [comment]
tried on v3.5.2, works fine
