### ISSUE TITLE
I would like a mentor

### ISSUE THREAD

**Issue by StevenYuanyuan** [argoproj/argo-workflows#9931]
**Question: Have you read the [mentoring guide](https://argoproj.github.io/argo-workflows/mentoring/)? Please only submit this request for general mentoring (not GSoC).**

Answer: **Yes I have read the mentoring guide.**

**What is your background? Any experience with Go, Kubernetes, React, Typescript, etc.?**

Answer: **I'm DevOps Engineer. I had some coding experience with Java/Python. I recently self-learned GoLang. I'm currently in a team that maintains our k8s clusters and I had my CKA cert 2 years ago. Not too much React/Typescript knowledge yet, I'm learning React at this moment.**

**Is there any particular issue you'd like to work on? You may want to check out the [list of good first issues](https://github.com/argoproj/argo-workflows/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).**

Answer: **I would like to work with issue #8591, this seems a good start. **

**Do you want to work with your mentor async (i.e. by Slack messaging or issue comments), or sync (e.g. using Zoom video)?** Please include your time-zone if you want to work sync.

Answer: Sync. Timezone: PST.

**Comment by sarabala1979** [comment]
@StevenYuanyuan let us know what kind of help you need it.

**Comment by StevenYuanyuan** [comment]
Hi @sarabala1979 , thank you for the fast response.

Currently I read 2 GoLang book (Learning Go, Cloud Native Go) and wrote a helper go CLI tool for our LDAP management. And I'm learning Frontend skills (Javascript/React) from online courses right now. I want to make a contribution to the argo project and it can also give me a real world project experience.

What I need is that how to get up to speed with this project. E.g. how is this project is structured/build, what should I focus on when reading this project code, how to practice/use my coding skill to contribute to this project, what's the gap that I need to fill to get up with the speed and make a good contribution?

Thanks!

**Comment by terrytangyuan** [comment]
These might be helpful:
* https://github.com/argoproj/argo-workflows/blob/master/docs/architecture.md
* https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md

**Comment by StevenYuanyuan** [comment]
Hi @terrytangyuan, thanks again for the link above. I finished reading the above 2 links and my local environment is now setup. And now I can run `make pre-commit -B` without any error. What's the next step you suggest?

**Comment by terrytangyuan** [comment]
Great! Feel free to pick up an issue to work on.

**Comment by agilgur5** [comment]
Closing as stale as OP did not respond to previous comments.

We have also removed the mentoring template as there is not enough bandwidth to support all mentees and we prefer to assist directly on an issue or PR per #11805
