### ISSUE TITLE
HTML encoding still breaking some log links

### ISSUE THREAD

**Issue by tico24** [argoproj/argo-workflows#9935]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Reference #9435 where this was originally reported.

Given I have a custom link in my configmap:

`http://grafana.home.local/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22expr%22:%22%7Bcontainer%3D%5C%22main%5C%22,pod%3D%5C%22${metadata.name}%5C%22%7D%22,%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D`

${metadata.name} is correctly resolved to a pod BUT %3D is not resolved to a = so loki gets this query:

`{container%3D"main",pod%3D"backfill-worker-go62jrw-962151937"}`

instead of this:

`{container="main",pod="backfill-worker-go62jrw-962151937"}`

It all worked well in 3.3.x

### Version

3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
Any workflow.
```

### Logs from the workflow controller

n/a

### Logs from in your workflow's wait container

n/a

**Comment by terrytangyuan** [comment]
@tczhao Would you like to take another look?

**Comment by tczhao** [comment]
Sure

**Comment by tczhao** [comment]
The problem is we now introduced url encode and decode. These function in go/javascript doesn't encode reserved characters
```
$&+,/:;=?@
```

If the user provided URL includes the encoded version of the reserve char e.g. having `%3D` instead of `=`
The UI attemps decodes it first then encodes it thus becomes:
 `%3D` -decode-> `%3D` -encode-> `%253D`

@tico24 
I replaced the `%3D` with `=`, try and see if this works
```
http://grafana.home.local/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22expr%22:%22%7Bcontainer=%5C%22main%5C%22,pod=%5C%22${metadata.name}%5C%22%7D%22,%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D
```

**Comment by tico24** [comment]
While replacing `%3D` with `=` does indeed work, it's _very_ counter-intuitive to the average user.

Taking grafana as the example, it outputs its urls encoded. Users should not be expected to break this encoding just to make the grafana links work with workflows.

Similarly, the change to the docs in PR #9944 doesn't go far enough to explain that this is necessary. It makes no sense to the non-technical, or even semi-technical user.
