### ISSUE TITLE
Add message field to lastRetry for conditional retries

### ISSUE THREAD

**Issue by pjo256** [argoproj/argo-workflows#9937]
# Summary

In https://argoproj.github.io/argo-workflows/retries/#conditional-retries, `lastRetry` cannot access workflow error/failure messages such as `Pod was terminated due to imminent node shutdown`. This request is for adding a `message` on `lastRetry` containing this error message.

# Use Cases

In https://github.com/argoproj/argo-workflows/issues/9880, we captured preemptions by setting `OnTransientError` and `TRANSIENT_ERROR_PATTERN`. However, we would also like to retry `OnError`. Using conditional retries, we cannot do both since `lastRetry` does not include a `message` field - e.g.

```
retryStrategy:
        limit: "3"
        expression: "lastRetry.status == 'Error' || lastRetry.message.contains('imminent node shutdown')"
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by aarushisoni** [comment]
HI! I would like to work on this issue.

**Comment by terrytangyuan** [comment]
Please go ahead and submit a PR if you'd like to contribute.
