### ISSUE TITLE
ArtifactGC failing but reporting success (permissions)

### ISSUE THREAD

**Issue by stbeckers** [argoproj/argo-workflows#9953]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

We implemented the ArtifactGC with the new version 3.4 like described [here](https://argoproj.github.io/argo-workflows/walk-through/artifacts/#artifact-garbage-collection). However after running the first workflows we were not able to delete them any more (GC the workflows after a set time did not work anymore).

After a lengthy debugging session and reading documentation (it was really hard to find the necessary points about permissions changing....) we finally figured out what the ArtifactGC is doing (or why it was not doing anything):

`<***>-artgc-wfcomp-2166136261 main Error: workflowartifactgctasks.argoproj.io is forbidden: User "<***>" cannot list resource "workflowartifactgctasks" in API group "argoproj.io" in the namespace "<***>"
<***>-artgc-wfcomp-2166136261 main workflowartifactgctasks.argoproj.io is forbidden: User "<***>" cannot list resource "workflowartifactgctasks" in API group "argoproj.io" in the namespace "<***>"`

However we did **not** get the mentioned `Artifact GC Failure`. So we first thought our issue is somewhere else.

When we looked into the permissions stuff we found [this](https://argoproj.github.io/argo-workflows/workflow-rbac/) piece of documentation. But even in the links presented on this page we did not see anything regarding permissions needed for ArtifactGC. We finally found what we were looking for when we [searched for `workflowartifactgctasks`](https://github.com/argoproj/argo-workflows/search?q=workflowartifactgctasks).

All of our logs indicated a success except the ones in the ArtifactGC pod and we did not get the specific `Artifact GC Failure` Event / Status. Making sure this status really shows up even in cases of permission errors would have saved us time.
Furthermore adding the necessary Permissions on this page or at least a link to the [quickstart-minimal](https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start-minimal.yaml#L1100) would make adding this new feature way more convenient.

### Version

v3.4.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-gc-
spec:
  entrypoint: main
  artifactGC:
    strategy: OnWorkflowCompletion
  templates:
    - name: main
      container:
        image: argoproj/argosay:v2
        command:
          - sh
          - -c
        args:
          - |
            echo "can throw this away" > /tmp/temporary-artifact.txt
            echo "keep this" > /tmp/keep-this.txt
      outputs:
        artifacts:
          - name: temporary-artifact
            path: /tmp/temporary-artifact.txt
            s3:
              key: temporary-artifact.txt
```

### Logs from the workflow controller

argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:22.129Z" level=info msg="Processing workflow" namespace=<***> workflow=dag-parallel-dummy-dqfxj
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:22.133Z" level=info msg="Creating Artifact GC Task dag-parallel-dummy-dqfxj-artgc-wfcomp-2166136261-0" namespace=<***> workflow=dag-parallel-dummy-dqfxj
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:22.141Z" level=info msg="Create workflowartifactgctasks 201"
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:22.141Z" level=info msg="creating pod to delete artifacts: dag-parallel-dummy-dqfxj-artgc-wfcomp-2166136261" namespace=<***> strategy=OnWorkflowCompletion workflow=dag-parallel-dummy-dqfxj
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:22.211Z" level=info msg="Create pods 201"
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:22.212Z" level=info msg="Checking daemoned children of " namespace=<***> workflow=dag-parallel-dummy-dqfxj
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:22.212Z" level=info msg="Workflow to be dehydrated" Workflow Size=34633
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:22.299Z" level=info msg="Update workflows 200"
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:22.301Z" level=info msg="Workflow update successful" namespace=<***> phase=Succeeded resourceVersion=735639313 workflow=dag-parallel-dummy-dqfxj
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:22.305Z" level=info msg="DeleteCollection workflowtaskresults 200"
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:22.305Z" level=info msg="Queueing Succeeded workflow <***>/dag-parallel-dummy-dqfxj for delete in 23h59m49s due to TTL"
argo-workflows-server-75c456b89f-k496d argo-server time="2022-10-31T17:17:26.860Z" level=info duration="100.222µs" method=GET path=index.html size=473 status=0
[...]
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:32.214Z" level=info msg="Processing workflow" namespace=<***> workflow=dag-parallel-dummy-dqfxj
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:32.218Z" level=info msg="reconciling artifact-gc pod" message= namespace=<***> phase=Failed pod=dag-parallel-dummy-dqfxj-artgc-wfcomp-2166136261 workflow=dag-parallel-dummy-dqfxj
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:32.218Z" level=info msg="processing completed Artifact GC Pod 'dag-parallel-dummy-dqfxj-artgc-wfcomp-2166136261'" namespace=<***> workflow=dag-parallel-dummy-dqfxj
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:32.222Z" level=info msg="List workflowartifactgctasks 200"
argo-workflows-workflow-controller-569fdd8c68-8nwsf controller time="2022-10-31T17:17:32.230Z" level=info msg="Delete workflowartifactgctasks 200"

### Logs from in your workflow's wait container

There was nothing regarding the ArtifactGC.

**Comment by terrytangyuan** [comment]
@juliev0 Could you take a look when you get a chance?

**Comment by juliev0** [comment]
Sorry for the trouble. Maybe the real issue here is that it appears that the install.yaml file from our Release page should include the necessary roles and rolebindings? (rather than their just being incorporated into quick-start-minimal.yaml) I am not sure why they're not in there.

**Comment by juliev0** [comment]
> I think I kind of ran into the same issue. However, I wasn't able to find any logs, I just suspected that this might have something to do with the ArtifactGC feature. After upgrading to Argo Workflows 3.4.3, I enabled the ArtifactGC feature for one of my workflows and noticed that (a) the success ttl wasn't working anymore and (b) I couldn't even delete those workflows manually through the Argo web UI. I think this is because the ArtifactGC is probably failing in the background for some reason. By now I've undeployed my workflow from my Kubernetes cluster and even undeployed Argo itself. The workflows, I couldn't delete earlier are still present in the Kubernetes cluster and I can't get rid of them. The "workflows.argoproj.io" CRD currently remains in the "Terminating" state, probably waiting for the remaining workflows to be removed. I tried `kubectl delete workflow [...]` with `--force`, `--grace-period=0`, `--now=true`, several `--cascade=[...]` options ... nothing works. The `kubectl delete` command is just waiting forever. I don't even know where to look for potential logs or events, to figure out what the actual issue is.
> 
> Does anyone have an idea how to remove those orphaned workflows from my Kubernetes cluster? I really really need to clean up that mess before I can even think of trying it again.

Sorry for the troubles. If you had ArtifactGC set in your workflow then a "finalizer" would've been set on your Workflow. This prevents the Workflow from being deleted until ArtifactGC has occurred successfully. The last section [here](https://argoproj.github.io/argo-workflows/walk-through/artifacts/) speaks to that. Also, there is now a "--force" option for "argo delete" (CLI).

**Comment by juliev0** [comment]
So, I guess the `argo-cluster-role` in the install.yaml file from the [Releases](https://github.com/argoproj/argo-workflows/releases) page is what needs to be bound to the ServiceAccount being used. I can add some documentation for that. It's interesting, because that same `argo-cluster-role` needs to be used for access to other CRD elements for running Workflows, including `workflowtasksets` and `workflowtaskresults` but I couldn't find anywhere in the documentation where we recommend that users bind to that role.
