### ISSUE TITLE
"Access demo environment" link in readme doesn't work

### ISSUE THREAD

**Issue by tico24** [argoproj/argo-workflows#9998]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

There is a link in the readme to a demo environment. This goes to a blank page. Ideally, we'd like it not to.

### Version

n/a

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

n/a

### Logs from in your workflow's wait container

n/a

**Comment by terrytangyuan** [comment]
I cannot log in to the Argo CD dashboard. @alexec @sarabala1979 Could you take a look?

**Comment by tico24** [comment]
Cool. I'll update the bug then.

**Comment by alexec** [comment]
Should work now.

Run book:

1. Login to Argo CD.
2. Open workflows app.
3. Delete ALL pods.
